### ISSUE TITLE
typo in documentation[Bug]

### ISSUE THREAD

**Issue by feilun-feilun** [aptos-labs/aptos-core#1007]
# 🐛 Bug
https://aptos.dev/tutorials/validator-node/run-validator-node-using-source
On this page, left a '$' in the example as shown below.
<img width="1244" alt="截屏2022-05-15 下午7 24 53" src="https://user-images.githubusercontent.com/49551621/168470561-3fcb7489-e344-4802-ac89-90d64217f321.png">

**Comment by gregnazario** [comment]
Fixed https://github.com/aptos-labs/aptos-core/pull/1010
