### ISSUE TITLE
[Bug]run validator node error : code :2, kind: NotFound, message:"No such file or directory"

### ISSUE THREAD

**Issue by kuncle** [aptos-labs/aptos-core#1016]
# 🐛 Bug
after run:cargo run -p aptos-node --release -- -f ~/$WORKSPACE/validator.yaml
I got below error message:
code :2, kind: NotFound, message:"No such file or directory"
aptos-node/src/main.rs:75:61

**Comment by huukhoa1412** [comment]
![IMG_20220516_063913_119](https://user-images.githubusercontent.com/59795495/168610715-d4c3e0e8-b57b-4d63-89d6-9d515a3b49c1.jpg)
I too this error

**Comment by VadimYevtushenko** [comment]
check your directory path in validator.yaml,
that's how it is for me
root@nodes:~/testnet# cat validator.yaml
base:
   role: "validator"
   data_dir: "/root/testnet/data"
   waypoint:
     from_file: "/root/testnet/waypoint.txt"

**Comment by huukhoa1412** [comment]
> check your directory path in validator.yaml, that's how it is for me root@nodes:~/testnet# cat validator.yaml base: role: "validator" data_dir: "/root/testnet/data" waypoint: from_file: "/root/testnet/waypoint.txt"

You edit missing
type: "on_disk_storage"
      path: /root/testnet/data/secure-data.json  <==
      namespace: ~
If it no edit change , error : code :2, kind: NotFound, message:"No such file or directory" 
now , edit it , run ok

**Comment by davidiw** [comment]
Going to close this out, since there's been advice given. If it persists, please provide your configuration files.
