### ISSUE TITLE
[Bug] Docker exited with code 132

### ISSUE THREAD

**Issue by VadimYevtushenko** [aptos-labs/aptos-core#1019]
After "docker-compose up" the process is interrupted

###################
root@nodes:/home/user/aptos/testnet# docker-compose up
[+] Running 3/1
  ⠿ Network aptos-docker-compose-shared Created 0.1s
  ⠿ Container testnet-fullnode-1 Created 0.0s
  ⠿ Container testnet-validator-1 Created 0.0s
Attaching to testnet-fullnode-1, testnet-validator-1
testnet-fullnode-1 exited with code 132
testnet-validator-1 exited with code 132

####################
Ubuntu 20.04.4
Linux nodes 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Server Dell T620 2xE5-2650
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 45
 model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
 stepping	: 7
 microcode	: 0x71a
 cpu MHz		: 1200.026
 cache size	: 20480 KB
 physical id	: 1
 siblings	: 16
 core id		: 7
 cpu cores	: 8
 apicid		: 47
 initial apicid	: 47
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 13
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
 bogomips	: 4013.94
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 46 bits physical, 48 bits virtual

Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by hyperleex** [comment]
Can you show logs output by typing:
`docker-compose logs `

**Comment by VadimYevtushenko** [comment]
> Can you show logs output by typing: `docker-compose logs `

empty, no output

**Comment by davidiw** [comment]
Please provide your process and your configuration files.

**Comment by VadimYevtushenko** [comment]
Install clear ubuntu 20.04.4 
Install Docker https://docs.docker.com/engine/install/ubuntu/
[Run Validator Node Using Docker] step by step
(https://aptos.dev/tutorials/validator-node/run-validator-node-using-docker)

[testnet.tar.gz](https://github.com/aptos-labs/aptos-core/files/8706505/testnet.tar.gz)

**Comment by 0wx** [comment]
@VadimYevtushenko try `docker builder prune -a -f` and then `docker compose up -d`

Also. you just uploading sensitive information, don't forget to re-do key generating process `aptos genesis generate-keys --output-dir ~/$WORKSPACE`

**Comment by VadimYevtushenko** [comment]
I think the problem is in the docker image, the problem was similar in
<img width="341" alt="image" src="https://user-images.githubusercontent.com/12593968/168993726-8766cca5-da2b-4a0e-8dbb-f7060da04874.png">

**Comment by yhs12345678** [comment]
same error

$ docker compose up
[+] Running 2/0
 ⠿ Container testnet-validator-1  Created                                                                                                  0.0s
 ⠿ Container testnet-fullnode-1   Created                                                                                                  0.0s
Attaching to testnet-fullnode-1, testnet-validator-1
testnet-fullnode-1 exited with code 132
testnet-validator-1 exited with code 132

sudo cat /proc/cpuinfo | grep avx
sudo: unable to resolve host yisu-628449fad35c2: Name or service not known
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat

**Comment by davidiw** [comment]
I suspect this is a hardware incompatibility in how the Rust binary is being built. My recommendation is to build from source. Let me know if you do that. Feel free to re-open if that doesn't work. I suspect we should determine the architecture that we're building on and be more clear about where it has been built and tested. CC: @sherry-x
