### ISSUE TITLE
[TS SDK V2] Fee payer example

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#10242]
Make an example where one account pays for another's gas.  As well as a multiagent example, with a fee payer.

**Comment by flex-enjoy** [comment]
need this too

**Comment by flex-enjoy** [comment]
Seems already have https://github.com/aptos-labs/aptos-ts-sdk/blob/main/examples/typescript/simple_sponsored_transaction.ts

**Comment by gregnazario** [comment]
Closed, already supported
