### ISSUE TITLE
[Bug] move compiler v1 jump folding is flawed

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#10253]
# 🐛 Bug

The bytecode generated for [bug_9717.move](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler/transactional-tests/tests/inlining/bug_9717.move), shown here: [bug_9717.exp](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler/transactional-tests/tests/inlining/bug_9717.exp), has some inefficient jump-to-jump code which should have been eliminated by 
third_party/move/move-compiler/src/to_bytecode/optimize/remove_fallthrough_jumps.rs.
```
	7: Lt
	8: BrFalse(30)
B2:
	9: Branch(10)
B3:
	10: CopyLoc[1](loc0: &vector<u8>)
```

Not clear why this wasn't folded away.

**Comment by brmataptos** [comment]
I glanced at it briefly, and the CFGIR has code like
```
        label 0:
            (i: u64) = 0u64;
            (flipsref3: &vector<u8>) = &flips;
            jump 1
        label 1:
            jump_if(copy i < (std=0x1)::vector::length<u8>(copy flipsref3)) 2 else 3
        label 2:
            (i: u64) = move#last i + 1u64;
            jump 1
```
So the inline_blocks pass is working correctly, but the bytecode generation is inserting an unnecessary additional block for this case.  The problem is that the IR is just too high level to express this.

So it's a new problem, not related to code changed in fixing #9717.  And stricly for V1, to my understanding.

The code that should deal with this situation is in third_party/move/move-compiler/src/to_bytecode/optimize/remove_fallthrough_jumps.rs.

**Comment by fEst1ck** [comment]
This doesn't appear in V2 (with CFG simplification enabled).
