### ISSUE TITLE
[Feature Request] [SDK v1] Add different functions for normalizing addresses for different use cases

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#10344]
Currently addresses returned in different parts of the ecosystem don't follow the same standards - some have suffixes of 0s, some don't. This creates mismatches in different components/systems such as between custom event processors (event data has leading 0s) vs data in standard index tables provided by Aptos (e.g. coin_activities).

One solution here is to expose different utils function that translate an address into what would be accepted by and used in APIs, event processors, and queries against standard index tables. For example:

1. standardizeAddress which adds prefixes of 0s (if address is not yet 64 digits) https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_types/account_address.ts#L95.
2. shortenAddress which removes prefixes of 0s if any. This is useful for querying against index tables provided by Aptos that don't have these prefixes.

**Comment by wrwg** [comment]
How does this relate with @banool's address standard AIP?

**Comment by gregnazario** [comment]
Closed, both functions are available `long` and `normal` in the SDK v2
