### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v6.20.3`

### ISSUE THREAD

**Issue by captainhiro** [aptos-labs/aptos-core#1034]
## ❓ Questions and Help
It happened when Install the aptos CLI:

error: failed to run custom build command for `librocksdb-sys v6.20.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installQuxJNt/release/build/librocksdb-sys-ebfc38d70ae9cd40/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/lighthouse/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Building [=================>      ] 789/1051: libgit2-sys(build), libgit2-sys(build)

**Comment by waha3** [comment]
you should install clang > 5.x version

**Comment by davidiw** [comment]
Did you run dev setup script?

**Comment by RafaBlockDev** [comment]
why do u close the issue is was not soled @davidiw 

really bad issue management 👎🏻

**Comment by davidiw** [comment]
> why do u close the issue is was not soled @davidiw
> 
> really bad issue management 👎🏻

Thanks for the feedback! It was a known issue that was resolvable by running the script. If it was unresolved, I would have expected the author to re-open it. If we left these issues opened, in most cases, no one would comment resolved or close them.

By the way this is a 2.25 year old issue :)
