### ISSUE TITLE
[Feature Request] SDK support for two upcoming AIPs on sponsored transaction

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#10491]
# 🚀 Feature Request
SDK should support two upcoming AIPs in sponsored transaction:

- AIP-52 automated account creation for sponsored transactions
- AIP-53 make fee-payer address optional in transaction authenticator

**Comment by gregnazario** [comment]
AIP-52 is automatic, AIP-53 is supported.
