### ISSUE TITLE
[Bug] [data-streaming-service] Unable to satisfy stream engine

### ISSUE THREAD

**Issue by yourmoonlight** [aptos-labs/aptos-core#1062]
# 🐛 Bug

I am running a full node  by following the official doc, https://aptos.dev/tutorials/validator-node/run-validator-node-using-docker
When the full node is running, I checked the log, and got this error msg.

**Stack trace/error message**
```
// Paste the output here
2022-05-18T10:02:01.225563Z [data-streaming-service] ERROR state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:106 {"error":{"DataIsUnavailable":"Unable to satisfy stream engine: ContinuousTransactionStreamEngine(ContinuousTransactionStreamEngine { request: ContinuouslyStreamTransactionOutputs(ContinuouslyStreamTransactionOutputsRequest { start_version: 4249, start_epoch: 2, target: None }), current_target_ledger_info: None, end_of_epoch_requested: false, next_stream_version_and_epoch: (4249, 2), next_request_version_and_epoch: (4249, 2), stream_is_complete: false }), with advertised data: account_states: [CompleteDataRange { lowest: 0, highest: 4248 }], epoch_ending_ledger_infos: [CompleteDataRange { lowest: 0, highest: 1 }], synced_ledger_infos: [LedgerInfo { commit_info: BlockInfo { epoch: 2, version: 4248 } }], transactions: [CompleteDataRange { lowest: 0, highest: 4248 }], transaction_outputs: [CompleteDataRange { lowest: 0, highest: 4248 }]"},"event":"error","name":"handle_stream_request"}

```

**Comment by JoshLind** [comment]
Thanks @yourmoonlight! Do you have more logs? This simply says that the data streaming engine can't find any peers advertising the data you require. The rest of the logs will show us why that is. I suspect it's because you probably don't have any peers 😄

**Comment by toinouu** [comment]
same issue for me

My validator log

`testnet-validator-1  | 2022-05-19T03:33:33.276026Z [aptos-data-client] ERROR state-sync/aptos-data-client/src/aptosnet/mod.rs:370 {"error":"TimeoutWaitingForResponse(\"Rpc timed out\")","event":"response_error","name":"storage_service_response","peer":"vfn:7ce0dc13","request_id":69764,"request_type":"get_storage_server_summary"}
testnet-validator-1  | 2022-05-19T03:33:33.276071Z [aptos-data-client] ERROR state-sync/aptos-data-client/src/aptosnet/mod.rs:649 {"error":"TimeoutWaitingForResponse(\"Rpc timed out\")","event":"peer_polling_error","message":"Error encountered when polling peer!","name":"storage_summary_response","peer":"vfn:7ce0dc13"}
`
And fullnode log

`fullnode-fullnode-1  | 2022-05-19T03:34:39.535409Z [data-streaming-service] ERROR state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:106 {"error":{"DataIsUnavailable":"Unable to satisfy stream engine: ContinuousTransactionStreamEngine(ContinuousTransactionStreamEngine { request: ContinuouslyStreamTransactionOutputs(ContinuouslyStreamTransactionOutputsRequest { start_version: 145199, start_epoch: 3, target: None }), current_target_ledger_info: None, end_of_epoch_requested: false, next_stream_version_and_epoch: (145199, 3), next_request_version_and_epoch: (145199, 3), stream_is_complete: false }), with advertised data: account_states: [CompleteDataRange { lowest: 0, highest: 145198 }], epoch_ending_ledger_infos: [CompleteDataRange { lowest: 0, highest: 2 }], synced_ledger_infos: [LedgerInfo { commit_info: BlockInfo { epoch: 3, version: 145198 } }], transactions: [CompleteDataRange { lowest: 0, highest: 145198 }], transaction_outputs: [CompleteDataRange { lowest: 0, highest: 145198 }]"},"event":"error","name":"handle_stream_request"}
`

My validator continues to work but I have to restart my fullnode for it to synchronize

**Comment by Nelrann** [comment]
while waiting to find a solution, I automatically restart the container of my fullnode if this error appears

**Comment by JoshLind** [comment]
@Nelrann, thanks for the logs. Couple questions:
- Which guides are you using to run to code? Docker?
- When you see the error messages, is the node still syncing or has it stopped? For example, I am seeing `We're already at the highest synced ledger info version!`, which tells me the fullnode thinks it's at the latest version. When you see these errors, is the fullnode at the same version as the validator?

I wouldn't worry too much about this now. When AIT1 starts there will be many peers to connect to, so fullnode synchronization should be smoother.

**Comment by Nelrann** [comment]
@JoshLind, thanks for your responses

I used this guide https://aptos.dev/tutorials/validator-node/run-validator-node-using-docker

At first I did installation which contained the fullnode + validator in the same docker compose, in this case I had no problem.

Then, I updated my VPS to move my fullnode to another VPS, it was from this change that I had problems with synchronization / RPC timeout (but my validator continue to works normaly)

When I see error ``We're already at the highest synced ledger info version!`` on my fullnode, it stops syncing, and I get this error on loop `` Unable to satisfy stream engine `` on my fullnode

**Comment by JoshLind** [comment]
> Then, I updated my VPS to move my fullnode to another VPS, it was from this change that I had problems with synchronization / RPC timeout (but my validator continue to works normaly)

Yeah, I think this is probably related. The validator continues normally because it's a single validator deployment and doesn't need to communicate with anything/anyone. It sounds like there might be connection issues between the fullnode and validator

Given that this isn't that important for now and fullnodes are optional, I'd argue we close the issue until AIT has launched. Things should be smoother by then. If not, we can return to it :)
