### ISSUE TITLE
Does the documentation consider supporting other prophecies

### ISSUE THREAD

**Issue by kylesliu** [aptos-labs/aptos-core#1063]
## ❓ Questions and Help

I am a programmer from other countries, and I am more interested in blockchain, is it possible to consider speaking about the translation of the documentation into other countries' languages, such as Chinese

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by davidiw** [comment]
This is the plan of record!!!
