### ISSUE TITLE
[Python SDK] Add explicit support for setting an API key

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#10646]
Currently to set an API key you must do it yourself:
```python
node_api_client = RestClient(args.node_api_url)
node_api_client.client.headers["Authorization"] = f"Bearer {args.api_key}"
```

It'd be nice if the constructor of RestClient took in an optional API key arg, probably in that ClientConfig class.

**Comment by harsha-mangena** [comment]
@lbmeiyi , Can I work on this issue

**Comment by banool** [comment]
Feel free to submit a PR! Make sure to check out our [contributing guidelines](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) 😄

**Comment by harsha-mangena** [comment]
@banool 

Are we looking something like this?
```
class RestClient:
    def __init__(self, base_url: str, config: ClientConfig = ClientConfig()):
        self.client = requests.Session()
        self.client.headers.update({"Content-Type": "application/json"})
        if config.api_key:  # Check if API key is provided
            self.client.headers["Authorization"] = f"Bearer {config.api_key}"
```

**Comment by Sigma2345** [comment]
Have updated sdk for api_key support at PR #11513

**Comment by gregnazario** [comment]
Awesome, thanks @Sigma2345.
