### ISSUE TITLE
[Bug] Getting DUPLICATE_MODULE_NAME during move publish

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#1068]
# 🐛 Bug

Hey, 

I have project contains one module and one script, when i'm running `aptos move publish` i'm getting error:

```
{
  "Error": "API error: transaction execution failed: Transaction Executed and Committed with Error DUPLICATE_MODULE_NAME"
}

```

## To reproduce

Create new Move package contains the following files.

`sources/empty.move`:

```
script {
    use Std::Signer;

    fun empty(acc: signer) {
        let _ = Signer::address_of(&acc);
    }
}
```

`sources/MyEmptyModule.move`:

```
module Sender::MyEmptyModule {

}

```

Compile it and try to publish: 

```
aptos move compile
aptos move publish
```

## Expected Behavior

Have to publish my `MyEmptyModule` without errors.

## System information

I'm using local environment, commit is [86fbd35d6d24e6149e48ca0aad55322a8713f9cb](https://github.com/aptos-labs/aptos-core/commit/86fbd35d6d24e6149e48ca0aad55322a8713f9cb).

**Comment by magnum6actual** [comment]
You currently cannot update modules. Once you publish - if you try to publish the same module again you'll get this error.

**Comment by davidiw** [comment]
I wonder if this is an upstream move issue.

**Comment by davidiw** [comment]
Upgrades are coming.
