### ISSUE TITLE
[Bug] Aptos CLI doesn't accept address argument with 0x prefix

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#1070]
# 🐛 Bug

I tried to run contract (`aptos move run`) and used address as and argument.

Because of `0x` prefix of address i got an error:

```
error: Invalid value "address:0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9" for '--args <ARGS>...': Unable to parse 'address': error: Unable to parse AccountAddress (must be hex string of length 32)
```

## To reproduce

Just run some script using Aptos CLI, e.g.:

```
aptos move run --function-id 0x1::TestCoin::transfer --args address:0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9 --args u64:100
```

## Expected Behavior

I think it should parse address with `0x` prefix.

**Comment by davidiw** [comment]
@gregnazario , this is addressed, right?
