### ISSUE TITLE
[Feature Request] it should be possible to provide module name during publish

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#1071]
# 🚀 Feature Request

When i run `aptos move publish` it would be nice to have a way to publish only one specific contract.

## Motivation

I think motivation is case when you already deployed your contracts and want to deploy a new one contains scripts for example. Because currently you can't run pure script with Aptos as i understood, so it could be a lot of pain to publish new script module for your code if you forgot something. 

## Pitch

Let's add a flag to publish command, maybe `--filter` flag, similar to that one test runner has.

**Comment by davidiw** [comment]
> run pure script with Aptos as i understood

This is not accurate. We support scripts.

Your proposal won't work with the model we're moving toward as each bundle is a version and new bundles would have to be versioned.
