### ISSUE TITLE
[Bug] third_party/move/move-model/src/ast.rs methods "uses_memory" name is negated

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#10725]
# 🐛 Bug

Methods "uses_memory" at lines https://github.com/aptos-labs/aptos-core/blob/059808f9c0618a876a21f40e69e8c4fcb47855c6/third_party/move/move-model/src/ast.rs#L1226 and https://github.com/aptos-labs/aptos-core/blob/059808f9c0618a876a21f40e69e8c4fcb47855c6/third_party/move/move-model/src/ast.rs#L1283 return `false` if global memory is used, and `true` if not (expression is "pure").

This should be renamed to make the name match the behavior.

**Comment by wrwg** [comment]
Its an easy fix, only used one time for the spec language, and where its used its used with the correct semantics (but wrong naming).
