### ISSUE TITLE
[Feature Request] Self-contained light client module

### ISSUE THREAD

**Issue by huitseeker** [aptos-labs/aptos-core#10747]
## Is there an authoritative, self-contained light client tool I missed?

As Aptos is moving from [Jolteon](https://arxiv.org/abs/2106.10362) to a [DAG-based BFT consensus protocol](https://arxiv.org/pdf/2306.03058.pdf), I was wondering if the developers were maintaining a self-cointained software tool (e.g. crate) for verifying [the light client protocol](https://a16zcrypto.com/posts/article/an-introduction-to-light-clients/#section--1) of AptosBFT?

Does such a self-contained software tool exist? Did I miss it? If not, is this something that would be useful?

## What would a self-contained light-client verification tool entail

Such a tool, inspired by [Helios](https://github.com/a16z/helios) (for Ethereum) would tie together
-  the [accumulator root](https://github.com/aptos-labs/aptos-core/blob/14758a1e2c846ae37126fc5de7fc30d59408c40d/types/src/block_info.rs#L35) (and a Jellyfish Merkle tree [proof](https://github.com/aptos-labs/aptos-core/tree/mainnet/types/src/proof) leading to it), 
- a block's validity conditions ([well-formedness](https://github.com/aptos-labs/aptos-core/blob/14758a1e2c846ae37126fc5de7fc30d59408c40d/consensus/consensus-types/src/block.rs#L279-L356), [signature validation](https://github.com/aptos-labs/aptos-core/blob/14758a1e2c846ae37126fc5de7fc30d59408c40d/consensus/consensus-types/src/quorum_cert.rs#L109-L138), and passing the commit rule), 
- how to maintain block info and QCs as they arrive from the chain in a minimalistic piece of state,
- [epoch change / reconfiguration](https://github.com/aptos-labs/aptos-core/blob/a2d40de75398d5b3f807e3adcfe11f35ceb507e1/types/src/block_info.rs#L40-L41) messages and how to update the quorum information in aforementioned state.

## Why this may be useful for Aptos

The `consensus` module (plus its dependencies in `types`) probably started as this minimalistic approach, but it now (understandably) contains more information than that, including in particular:
- voting rules, 
- liveness considerations, 
- general legacy code, affected by changes in the protocol, e.g. on-chain config or experimental modules.

In case the locations of the links above aren't enough to show there's a lot of ground to cover to assemble this information, here's the result of a fresh tokei run on the mainnet consensus directory:
```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 Markdown                1           59            0           39           20
 TOML                    3          189          173            3           13
-------------------------------------------------------------------------------
 Rust                  187        37776        32109         1751         3916
 |- Markdown           106         1352            0         1286           66
 (Total)                          39128        32109         3037         3982
===============================================================================
 Total                 191        38024        32282         1793         3949
===============================================================================
```

A self-contained light client implementation
- would serve as an authoritative "integration test" for the consensus,
- its changes would be informative when / if anything about the major protocol safety conditions change (including, of course, the consensus algorithm),
-  If authoritative, this would also help the implementation of valid & safe light clients in other languages, as well as 
- provide documentation.

/cc @zekun000 @ibalajiarun who should probably close this issue with a terse link in comment in case I missed the relevant info

**Comment by zekun000** [comment]
Nice to see you here @huitseeker  😄 not sure if you're aware of the original design goal for the LedgerInfo is to encapsulate "consensus" and expose a generic quorum signatures which allows us to evolve consensus and make it clients agnostic, e.g. moving from 3-chain commit rule to 2-chain commit rule or from 2-chain commit rule to DAG are agnostic to light clients.

Light clients are able to verify these properties, but not consensus specific information like commit rules, QC's etc.
- quorum signatures on root hash
- merkle proof according to the root hash
- epoch change proof that carries next epoch pubkeys signed by the current epoch committees

We have this TrustedState implementation if you're interested https://github.com/aptos-labs/aptos-core/blob/edcae567b88d706b848e89885005efc772259715/types/src/trusted_state.rs#L27

**Comment by huitseeker** [comment]
Thanks, this is quite useful. The `TrustedState` implementation is quite useful re: managing the `EpochState`s.

When you say "Light clients are able to verify these properties but not [those properties]", it means you have specific expectations what a light client is or should be able to do. Where can I learn more about where those expectations are defined, from a protocol spec standpoint? (though the answer may be a code pointer - I'm happy with that too!)

**Comment by zekun000** [comment]
I don't think we specifically call out our expectations, but you're right, as we don't expose consensus details we expect light client verifier to adopt the BFT assumptions (trusting quorum signatures).

what you described are similar to what I have in mind, trusted state is a reference implementation. After verifying the `EpochState` the light client could use the root hash to verify merkle proof according to our authentication data structure spec.

**Comment by aching** [comment]
Hi @huitseeker! Great to hear from you!!!

**Comment by huitseeker** [comment]
@zekun000 Thanks for those precisions, that's very clarifying.

**Comment by lbmeiyi** [comment]
Thank you for filing the issue, seems like your questions are addressed, we will go ahead and close this out for now!
