### ISSUE TITLE
cargo run validator server error

### ISSUE THREAD

**Issue by waha3** [aptos-labs/aptos-core#1078]
![image](https://user-images.githubusercontent.com/12130012/169188526-a1f29189-ef05-44fe-80d3-73e1df2df9be.png)
![image](https://user-images.githubusercontent.com/12130012/169188673-52990207-3645-47a7-bfc1-413ca07927c0.png)
cargo run validator server error but i have all config file

**Comment by davidiw** [comment]
not enough info, if you have issues, please re-open and add the config and version of the repo.
