### ISSUE TITLE
[Bug] Indexer seems not working 

### ISSUE THREAD

**Issue by fenghaojiang** [aptos-labs/aptos-core#10854]
# 🐛 Bug

When I run Indexer for Aptos node, all works are fine and it seems that it suddenly stop one day. I check the my logs: 

## To reproduce. 

Run the indexer. 

**Code snippet to reproduce**

**Stack trace/error message**
```
{
    "level":"ERROR",
    "source":{
        "package":"aptos_indexer",
        "file":"crates/indexer/src/indexer/fetcher.rs:189"
    },
    "thread_name":"indexer-8",
    "hostname":"xxxxxxx",
    "timestamp":"2023-08-14T16:04:55.465180Z",
    "message":"Could not fetch transactions: retries exhausted",
    "data":{
        "error":"Transaction at version 1501 is pruned, min available version is 224341605.",
        "num_transactions":500,
        "starting_version":1501
    },
    "peer_id":"xxxxxx"
}
```

## System information

**Please complete the following information:**
- Aptos Core Version
aptos-release-v1.7.3

- Computer OS
centos

**Comment by bowenyang007** [comment]
This isn't an indexer error per se, but rather you are connecting to a node that is pruned. Check out the guide on archival nodes here: https://aptos.dev/guides/state-sync/#running-archival-nodes

**Comment by bowenyang007** [comment]
Btw we have a new way of indexing coming up soon where you don't have to worry about running a node anymore. Check this one: https://aptos.dev/indexer/txn-stream/labs-hosted

**Comment by fenghaojiang** [comment]
> Btw we have a new way of indexing coming up soon where you don't have to worry about running a node anymore. Check this one: https://aptos.dev/indexer/txn-stream/labs-hosted

Thank you and appreciated for your help. But I checked the docs but it seems that the labs-hosted is a client-side service to receive transaction info from the server. I guess it can not replace the indexer now because the indexer has to be compatible with this form of transaction data. If the indexer can be replaced now, I can not find the relevant docs from the official site.
