### ISSUE TITLE
[Bug]can't run full node

### ISSUE THREAD

**Issue by encrylife** [aptos-labs/aptos-core#1085]
# 🐛 Bug
 Can't run full node server,both of cargo and docker-compose. they have same error as below:

2022-05-19T10:33:08.326532Z [main] INFO storage/schemadb/src/lib.rs:341 Opened RocksDB. {"rocksdb_name":"aptosdb"}
2022-05-19T10:33:08.327484Z [main] INFO storage/aptosdb/src/pruner/db_pruner.rs:19 state store pruner initialized. {"least_readable_version":0}
2022-05-19T10:33:08.327504Z [main] INFO storage/aptosdb/src/pruner/db_pruner.rs:19 ledger pruner initialized. {"least_readable_version":0}
2022-05-19T10:33:08.327600Z [main] INFO storage/aptosdb/src/lib.rs:311 Opened AptosDB. {"path":"/root/data/aptos-data/db/aptosdb","time_ms":"27"}
2022-05-19T10:33:08.327667Z [main] INFO storage/storage-service/src/lib.rs:89 StorageService spawned.
2022-05-19T10:33:08.327853Z INFO secure/net/src/lib.rs:370 {"event":"connection_attempt","mode":"server","service":"storage"}
2022-05-19T10:33:08.327901Z [main] INFO storage/backup/backup-service/src/lib.rs:32 Backup service spawned.
2022-05-19T10:33:08.328163Z [main] INFO aptos-move/aptos-vm/src/adapter_common.rs:170 Executing block, transaction count: 1 {"name":"miscellaneous","txn_id":0}
2022-05-19T10:33:08.447201Z [main] ERROR crates/crash-handler/src/lib.rs:38 details = '''panicked at 'Db-bootstrapper should not fail.: Genesis txn didn't output reconfig event.', aptos-node/src/lib.rs:509:14'''
backtrace = '''
   0:     0x55e1fe520287 - backtrace::backtrace::libunwind::trace::h5cd083e86596066d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h05180ecbb54fc52c
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h4f6a6ff0540b4fee
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:53:14
   1:     0x55e1fe50d4e5 - backtrace::capture::Backtrace::create::h2e5027923e6bde69
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::hc05b6d7429dac080
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:140:22
   2:     0x55e1fcfb4484 - crash_handler::handle_panic::h863b996136297c88
                               at /root/data/aptos-core/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h8b6783b606df99df
                               at /root/data/aptos-core/crates/crash-handler/src/lib.rs:27:9
   3:     0x55e1fe633ca4 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
   4:     0x55e1fe633957 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
   5:     0x55e1fe6314e4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- clone from github
- 
- rustc 1.60.0 (7737e0b5c 2022-04-04
- 
ubuntu20.04 64byte

## Additional context
my public_full_node.yaml:
![222_16529580882521](https://user-images.githubusercontent.com/2277083/169278755-340ec9c0-aae9-440d-ae6d-82265ef99f19.png)

**Comment by JoshLind** [comment]
Thanks! A couple quick questions:
1. What guide are you following?
2. When you checkout github, are you using the `devnet` branch, or just `main`? You need to use `devnet`.
3. Are you trying to connect to devnet, or are you setting up the deployment for incentivized testnet?

**Comment by encrylife** [comment]
> Thanks! A couple quick questions:
> 
> 1. What guide are you following?
> 2. When you checkout github, are you using the `devnet` branch, or just `main`? You need to use `devnet`.
> 3. Are you trying to connect to devnet, or are you setting up the deployment for incentivized testnet?



> Remember
1. I  try many different ways,for example: https://aptos.dev/tutorials/full-node/run-a-fullnode,wiki.aptos.movemove.org and so on
2. use devnet branch
3. it can connect the devnet,but have a few problem
At first I try use centos,the full node work well ,but when I want generate the keys,it report problem :
![FZXi81kkMr](https://user-images.githubusercontent.com/2277083/169635472-994e34ed-9454-404b-8de6-e8d3a75019f4.jpg)
then I change the os to Ubuntu,It report the different error as above.either use source code or docker,the error stiill
finnal I change to azmon's os, it work well,but I register https://community.aptoslabs.com/it1,it require account_address account_key  consensus_key full_node_network_key validator_network_key. https://aptos.dev/tutorials/full-node/run-a-fullnode only how to identity: Network Identity For FullNode and I had generate private.txt and private_txt.pub,peer. How can I get the keys and related full node .
I find I had can't register,it's all over ,the key is still unkonw.
can you  help me ?

**Comment by davidiw** [comment]
My suspicion is you're using incompatible genesis with the node. In order to debug, we would need:
* Pointer to the code version or docker version you're using
* Command to execute
* Waypoint
* Hash of the genesis file

If the issue persists, feel free to re-open and share that info.
