### ISSUE TITLE
[Feature Request][move-compiler-v2] Compiler V2 needs expression simplification

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#10850]
# 🚀 Feature Request

The `deep_exp.move` test uses inlining to generate a temporarily very large expression which simplifies down to reasonably-sized bytecode in the old compiler, where some expression simplification is available.  The V2 compiler needs a similar mechanism.

This would be most efficient if done on the AST using an impl of trait `ExpRewriterFunctions` that can be applied bottom-up during inlining to avoid creating such large expressions in the first place.

However, the `deep_exp` test fails not in the compiler but in final file format generation, when local variable count is exceeded.  So if it's somehow easier to implement we could do it in the bytecode phases.

**Comment by vineethk** [comment]
> So if it's somehow easier to implement we could do it in the bytecode phases.

We can do it fairly cleanly in the stackless bytecode pipeline: https://github.com/aptos-labs/aptos-core/pull/11598
