### ISSUE TITLE
[Feature Request][Compiler-v2] Basic constant folding

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#10880]
# 🚀 Feature Request

Support basic constant folding to support the case such as `const G1_NUM_MAX: u64 = 1048576 / 144;`

**Comment by brmataptos** [comment]
Tangential comment:

That example is not the best one, as the comment is wrong.  Source code could be updated:
```
 const LN2_X_32 : u64 = ... // 32 * ln(2) in fixed 32 representation
```
but there are no uses of that constant, so it really should just be removed.

**Comment by brmataptos** [comment]
There is some overlap between this and https://github.com/aptos-labs/aptos-core/issues/9330.  I suggest that this one should be specialied for "constant folding in expressions", while that one is for constant propagation.

**Comment by rahxephon89** [comment]
> Tangential comment:
> 
> That example is not the best one, as the comment is wrong. Source code could be updated:
> 
> ```
>  const LN2_X_32 : u64 = ... // 32 * ln(2) in fixed 32 representation
> ```
> 
> but there are no uses of that constant, so it really should just be removed.

Here is another [example](https://github.com/aptos-labs/aptos-core/blob/8371518c15a1206054e88db9d0e18c24b736e0c9/aptos-move/framework/aptos-stdlib/sources/cryptography/bls12381_algebra.move#L776). It is only used in testing though. cc @brmataptos @wrwg

**Comment by rahxephon89** [comment]
> There is some overlap between this and #9330. I suggest that this one should be specialied for "constant folding in expressions", while that one is for constant propagation.

Oh, I did not know there is already one, which seems including the case here. I will close this one then.
