### ISSUE TITLE
[Feature Request] [move-compiler-v2] Run aptos tests with compiler v2

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#10895]
# 🚀 Feature Request

We need a way to run all the aptos move tests with v2 compiler as well as v1 compiler.

I see several options, in increasing cost and value:

1. An environment variable could select Move compiler version.  Then we can easily re-run everything as if V2 is used in place of V1.  BUT: Comparisons have to be done outside of build framework.
2. A cargo feature used to select Move compiler version to use.  Same problem here.
3. Something like third_party/move/move-compiler-v2/tests/testsuite.rs and third_party/move/move-ompiler/tests/move_check_testsuite.rs to select a single different compiler option for different subdirs
4. Add an output comparison for v1/v2 tests like those.

We also need something for transactional-tests, if we ever resurrect that dir.

**Comment by sausagee** [comment]
@brmataptos to follow up with @rahxephon89
