### ISSUE TITLE
[compiler v2] Use constraints to express structure access and field access in type inference

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#10897]
Currently, in the type checker (`model/builder`), at certain points a type needs to be concretized to ensure it is a struct or is a struct with a particular field. This can be avoided by instead introducing type constraints for this, adding to the existing definition here:

https://github.com/aptos-labs/aptos-core/blob/58271fd3a4dd3279c4112ba2fff79e28b46149c0/third_party/move/move-model/src/ty.rs#L94-L107

For example, a variant `SomeStruct(Option<(Symbol, Type)>)` could be added. Then checking whether something is a struct / a struct with a given field can be delayed until the type is actually instantiated during unification.

**Comment by rahxephon89** [comment]
What should be stored in `SomeStruct`?  Also when we want to specialize a type variable that with this, do we need a default type for it?

**Comment by wrwg** [comment]
This was fixed recently
