### ISSUE TITLE
[Bug][Compiler-v2] mutability mismatch in inline function

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#10913]
# 🐛 Bug

When compiling `smart_table.move` using `aptos move compile --compiler-version=v2`, the following error is raised:

```
error: mutability mismatch (& != &mut)
    ┌─/aptos-core/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/data_structures/smart_table.move:363:21
    │
363 │                     f(key, value)
    │                     ^^^^^^^^^^^^^

```

The testing is done based on the inlining PR: #10835

**Comment by brmataptos** [comment]
What does this have to do with https://github.com/aptos-labs/aptos-core/pull/10910? That one just shows backtraces on errors in compiler v1.  Perhaps you mean https://github.com/aptos-labs/aptos-core/pull/10835?
