### ISSUE TITLE
[Bug] Compiler v2 error messages have seemingly arbitrary order

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#10935]
# 🐛 Bug

Move compiler v2 produces error messages in a seemingly arbitrary order.

## To reproduce

**Code snippet to reproduce**

https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_const.move

**Stack trace/error message**

https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_const.exp

## Expected Behavior

Error messages appear in some meaningful order, such as by line number.

## System information

**Please complete the following information:**
- Aptos Core Version: main branch at the time of filing the bug.

**Comment by brmataptos** [comment]
Seems fixed by #11675

**Comment by brmataptos** [comment]
Still have a problem with diagnostic ordering in `third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/return_borowed_local_invalid.exp`.
