### ISSUE TITLE
[Feature Request] [move-compiler-v2] Consider using log for compiler messages

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#10977]
# 🚀 Feature Request

Wolfgang notes:

We really should start using log as in the prover and describe here: https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/documentation/coding_guidelines.md#logging

I think we need a bit more work to make that happen and go to the right places.

**Comment by brmataptos** [comment]
Probably we could start with some demo/discussion.

**Comment by vineethk** [comment]
@wrwg Should this be considered completed?

**Comment by vineethk** [comment]
Closing as done.
