### ISSUE TITLE
[Bug] Incorrect semantics when inlining lambdas in compiler v1

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#10991]
# 🐛 Bug

In the following code, the inline function is expanded incorrectly, leading to miscomputation.

## To reproduce

**Code snippet to reproduce**
```move
module 0x42::Test {
    inline fun foo(f:|u64, u64| u64, g: |u64, u64| u64, x: u64, _y: u64): u64 {
        f(x, _y) + g(x, _y)
    }

    public fun test() {
        assert!(foo(|x, _| x, |_, y| y, 10, 100) == 110, 0);
    }
}
```

**Stack trace/error message**
The assertion fails with `foo` returning 20 instead. 

## Expected Behavior

The assertion should not have failed if the inlining expanded lambdas correctly.

There is also a related bug where if you replace `_y` with `y` as the last formal parm of `foo`, then we get an unwarranted unused variable error.

**Comment by brmataptos** [comment]
FYI, move-compiler-v2 succeeds on this test.  Though I supposed you know that.

**Comment by brmataptos** [comment]
The source of this is the '_' parameter name in a lambda.  It gets skipped when assigning parameters to values.  So a pretty simple bug.

**Comment by brmataptos** [comment]
Fixed by https://github.com/aptos-labs/aptos-core/pull/11361
