### ISSUE TITLE
[Feature Request] generate transaction hash of signed transaction

### ISSUE THREAD

**Issue by amirmovafagh** [aptos-labs/aptos-core#10999]
# 🚀 Feature Request

hi
is there any way to generate transaction hash before the submit signed transaction in network ?

i use python aptos-sdk and try to generate hash with hashlib.sha3-256 and the generated hash is different with submitted transaction on network

**Comment by gregnazario** [comment]
Moving to Python SDK repo https://github.com/aptos-labs/aptos-python-sdk/issues/29
