### ISSUE TITLE
[compiler v2] Visibility checker should become responsible to check for private field access

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#11014]
With #11010 field visibility checking does not fit into the type checker anymore, since field access is now handled via type unification which is decoupled from program metadata like visibilities. Instead, the existing bytecode-based visibility checker should handle private fields.

**Comment by vineethk** [comment]
Example test case:

```
module 0x42::m {

struct S {
    f1: u64,
    f2: u64,
    f3: u64,
    f4: u64,
}

public fun consume(_: S) { abort 0 }

}

module 0x42::n {

use 0x42::m::S;

fun f() {
  let s = S {
    f1: 0,
    f4: 0,
    f2: 0,
    f3: 0,
  };
  0x42::m::consume(s);
}

}
```
