### ISSUE TITLE
[Feature Request][aptos-stdlib] bn254 algebra operations

### ISSUE THREAD

**Issue by guangyuz** [aptos-labs/aptos-core#11019]
# 🚀 Feature Request

We need a Move module for bn254 algebra operations. 

## Motivation

With this feature, aptos stdlib's capabilities in zero-knowledge proofs will be greatly enhanced. For example, we (zkMove) are building a [general snark verifier](https://github.com/zkmove/halo2-verifier.move) on Aptos for the halo2/kzg proofs system. With this verifier, developers can easily deploy various zero-knowledge applications on aptos, such as a zkLogin.

## Pitch

I note that the implementation of the bls12-381 algebra is already implemented based on arkworks, so the same can be done with bn254.

## Risks

Smart contracts have gas limitations.

**Comment by zjma** [comment]
+1!

**Comment by guangyuz** [comment]
https://github.com/aptos-labs/aptos-core/pull/11142
