### ISSUE TITLE
[Aptos CLI] Version mismatch results in panic?

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#1108]
A few users are reporting this in discord. Some have reported that using a different version helps. Needs to be debugged.

<img width="1151" alt="Screen Shot 2022-05-20 at 11 00 58 AM" src="https://user-images.githubusercontent.com/4578587/169556364-99b791a7-40a5-4b4b-aa2d-9aec2085172c.png">

thread 'main' panicked at 'There should only be one NewEpochEvent', aptos-move/vm-genesis/src/lib.rs:313:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
silver@DESKTOP-R5TNVP3:~/testnet$

**Comment by rl-crypto** [comment]
Same error here.

**Comment by gregnazario** [comment]
Looks like there's an incompatible framework change, I'm working on fixing the build and instructions now.  Future runners will need the newest CLI, but for now we need one compatible with the saved framework.

**Comment by gregnazario** [comment]
I've updated the release and it should work properly now:
https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v0.1.1

**Comment by gregnazario** [comment]
Meanwhile for devnet, I am looking into what the incompatible change is and making sure everything works properly.

**Comment by rl-crypto** [comment]
Thanks @gregnazario. I installed the cli from cargo before. Should I force install it?

**Comment by gregnazario** [comment]
> Thanks @gregnazario. I installed the cli from cargo before. Should I force reinstall it?

Yes, you can install it with:
```
cargo install --git https://github.com/aptos-labs/aptos-core.git aptos --tag aptos-cli-v0.1.1
```

**Comment by chinapeace** [comment]
> > Thanks @gregnazario. I installed the cli from cargo before. Should I force reinstall it?
> 
> Yes, you can reinstall it with:
> 
> ```
> cargo install --git https://github.com/aptos-labs/aptos-core.git aptos --tag aptos-cli-v0.1.1
> ```
Via docker you can reinstall it with:


```
wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v0.1.1/aptos-cli-0.1.1-Ubuntu-x86_64.zip

sudo unzip aptos-cli-0.1.1-Ubuntu-x86_64.zip

sudo mv aptos /usr/local/bin/ 

sudo chmod +x /usr/local/bin/aptos

sudo ln -s /usr/local/bin/aptos /usr/bin/aptos
```

**Comment by cryptohaunting** [comment]
the Issue still remains. I run the [Shell script](https://github.com/kj89/testnet_manuals/blob/main/aptos/testnet/aptos.sh. )

The issue remains to be:
thread 'main' panicked at 'There should only be one NewEpochEvent', aptos-move/vm-genesis/src/lib.rs:313:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by gregnazario** [comment]
I don't

> the Issue still remains. I run the [Shell script](https://github.com/kj89/testnet_manuals/blob/main/aptos/testnet/aptos.sh)
> 
> The issue remains to be: thread 'main' panicked at 'There should only be one NewEpochEvent', aptos-move/vm-genesis/src/lib.rs:313:5 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Looking into the ubuntu version now.

**Comment by gregnazario** [comment]
@cryptohaunting please try now, I realized there was a caching error on my build

**Comment by leqhabk68** [comment]
Same issues after install aptos-cli-v0.1.1...as mention above. Did you find out ?

**Comment by gregnazario** [comment]
> Same issues after install aptos-cli-v0.1.1...as mention above. Did you find out ?

I pushed a new update, is it still causing issues now?

**Comment by cryptohaunting** [comment]
Works now! Cheers

> > Same issues after install aptos-cli-v0.1.1...as mention above. Did you find out ?
> 
> I pushed a new update, is it still causing issues now?
