### ISSUE TITLE
[Bug] API discriminator values do not conform to OpenAPI specification

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#1110]
# 🐛 Bug

## To reproduce
```
$ curl -s https://fullnode.devnet.aptoslabs.com/transactions/0x1dae5076fa24284660596ddf20754acd67523a9ef5f0ae99e599a91095fba5d4 | jq -r .payload.type
script_function_payload 
```
Here you can see that for a TransactionPayload, the value used for the discriminator is `script_function_payload`. This is not what we would expect as per [the spec](https://spec.openapis.org/oas/v3.0.3#discriminator-object). Since we have not defined an explicit mapping, it should instead be `ScriptFunctionPayload`. 

## To fix
So we have two options:

- Make our API return the correct value to match the implicit behaviour that client generators working with OpenAPI specs assume.
- Add an explicit mapping, for example:

```
    TransactionPayload:
      title: Transaction Payload
      oneOf:
        - $ref: '#/components/schemas/ScriptFunctionPayload'
        - $ref: '#/components/schemas/ScriptPayload'
        - $ref: '#/components/schemas/ModuleBundlePayload'
        - $ref: '#/components/schemas/WriteSetPayload'
      discriminator:
        propertyName: type
        mapping:
          - script_function_payload: '#/components/schemas/ScriptFunctionPayload'
          etc.
```

I'm inclined to say we should do the first one to keep the length of the spec manageable. Rust makes this a little tricky though since you can't easily introspect stuff, but for now we already do this explicitly, so we could just update those strings.

I'll make this change, just looking for thoughts on which direction to go.

**Comment by davidiw** [comment]
I don't think there's a solid position here and I don't know if anyone of us are really experts in the space. In either way, we are giving more information to the developer, which seems like a win.

**Comment by banool** [comment]
For context this was resolved with https://github.com/aptos-labs/aptos-core/pull/1121, so we ended up doing option 2.
