### ISSUE TITLE
[Bug][Compiler-v2] UNEXPECTED_VERIFIER_ERROR is raised when running certain test cases in vector_tests

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11112]
# 🐛 Bug

When running tests using V2, some tests lead to the error:

```
┌── vector_contains ──────
│ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::vector_tests rooted here
└──────────────────

```

Failed tests include:

[test_for_each_mut](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L673), [test_zip_mut](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L700), [test_zip_mut_mismatching_lengths_should_fail](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L732), [test_enumerate_mut](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L758), [test_partition](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L846), 
[test_stable_partition](https://github.com/aptos-labs/aptos-core/blob/c5e4c322d7661eeddb469c8f65929491082d35de/aptos-move/framework/move-stdlib/tests/vector_tests.move#L859). 

Note that these tests all call inline functions with mutable references and the actual error seems to be `VEC_UPDATE_EXISTS_MUTABLE_BORROW_ERROR`. cc @brianrmurphy @wrwg 

To reproduce it, 

- set an environment variable `ENABLE_V2` to 1.
- inside `aptos-move/framework`, run `cargo test`. To reproduce it more easily, you may want to run `move_stdlib_unit_tests` only by commenting out other tests in `move_prover_tests.rs` and `move_unit_test.rs`.

**Comment by rahxephon89** [comment]
For the following function:
```
    fun test_for_each_mut() {
        let v = vector[1, 2, 3];
        let s = 2;
        for_each_mut(&mut v, |e| { *e = s; s = s + 1 });
        assert!(v == vector[2, 3, 4], 0);
    }
```

The following bytecode is generated by V2:

```
// V2
test_for_each_mut() {
L0:	loc0: vector<u64>
L1:	loc1: u64
L2:	loc2: &mut vector<u64>
L3:	loc3: u64
L4:	loc4: u64
L5:	loc5: &mut u64
L6:	loc6: u64
L7:	loc7: u64
L8:	loc8: vector<u64>
B0:
	0: LdU64(1)
	1: LdU64(2)
	2: LdU64(3)
	3: VecPack(17, 3)
	4: StLoc[0](loc0: vector<u64>)
	5: LdU64(2)
	6: StLoc[1](loc1: u64)
	7: MutBorrowLoc[0](loc0: vector<u64>)
	8: StLoc[2](loc2: &mut vector<u64>)
	9: LdU64(0)
	10: StLoc[3](loc3: u64)
	11: CopyLoc[2](loc2: &mut vector<u64>)
	12: FreezeRef
	13: VecLen(17)
	14: StLoc[4](loc4: u64)
B1:
	15: CopyLoc[3](loc3: u64)
	16: CopyLoc[4](loc4: u64)
	17: Lt
	18: BrFalse(39)
B2:
	19: CopyLoc[2](loc2: &mut vector<u64>)
	20: CopyLoc[3](loc3: u64)
	21: VecMutBorrow(17)
	22: StLoc[5](loc5: &mut u64)
	23: CopyLoc[1](loc1: u64)
	24: MoveLoc[5](loc5: &mut u64)
	25: WriteRef
	26: LdU64(1)
	27: StLoc[6](loc6: u64)
	28: MoveLoc[1](loc1: u64)
	29: MoveLoc[6](loc6: u64)
	30: Add
	31: StLoc[1](loc1: u64)
	32: LdU64(1)
	33: StLoc[7](loc7: u64)
	34: MoveLoc[3](loc3: u64)
	35: MoveLoc[7](loc7: u64)
	36: Add
	37: StLoc[3](loc3: u64)
	38: Branch(40)
B3:
	39: Branch(41)
B4:
	40: Branch(15)
B5:
	41: LdU64(2)
	42: LdU64(3)
	43: LdU64(4)
	44: VecPack(17, 3)
	45: StLoc[8](loc8: vector<u64>)
	46: MoveLoc[0](loc0: vector<u64>)
	47: MoveLoc[8](loc8: vector<u64>)
	48: Eq
	49: BrFalse(51)
B6:
	50: Branch(53)
B7:
	51: LdU64(0)
	52: Abort
B8:
	53: Ret
}
```

I think the issue is that `loc2` (mutable ref of v, first assigned at instr: 8) is not popped after the while loop (instr: 39), then at instr:46, v is moved to stack, leading to the invariant violation error. The bytecode generated by V1 is

```
// V1
test_for_each_mut() {
L0:	loc0: &mut u64
L1:	loc1: u64
L2:	loc2: u64
L3:	loc3: u64
L4:	loc4: vector<u64>
L5:	loc5: &mut vector<u64>
B0:
	0: LdConst[3](Vector(U64): [3, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0])
	1: StLoc[4](loc4: vector<u64>)
	2: LdU64(2)
	3: StLoc[3](loc3: u64)
	4: MutBorrowLoc[4](loc4: vector<u64>)
	5: StLoc[5](loc5: &mut vector<u64>)
	6: LdU64(0)
	7: StLoc[1](loc1: u64)
	8: CopyLoc[5](loc5: &mut vector<u64>)
	9: FreezeRef
	10: VecLen(12)
	11: StLoc[2](loc2: u64)
B1:
	12: CopyLoc[1](loc1: u64)
	13: CopyLoc[2](loc2: u64)
	14: Lt
	15: BrFalse(33)
B2:
	16: Branch(17)
B3:
	17: CopyLoc[5](loc5: &mut vector<u64>)
	18: CopyLoc[1](loc1: u64)
	19: VecMutBorrow(12)
	20: StLoc[0](loc0: &mut u64)
	21: CopyLoc[3](loc3: u64)
	22: MoveLoc[0](loc0: &mut u64)
	23: WriteRef
	24: MoveLoc[3](loc3: u64)
	25: LdU64(1)
	26: Add
	27: StLoc[3](loc3: u64)
	28: MoveLoc[1](loc1: u64)
	29: LdU64(1)
	30: Add
	31: StLoc[1](loc1: u64)
	32: Branch(12)
B4:
	33: MoveLoc[5](loc5: &mut vector<u64>)
	34: Pop
	35: MoveLoc[4](loc4: vector<u64>)
	36: LdConst[4](Vector(U64): [3, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0])
	37: Eq
	38: BrFalse(40)
B5:
	39: Branch(42)
B6:
	40: LdU64(0)
	41: Abort
B7:
	42: Ret
}
```

At instr:33, the mutable reference (loc5) is moved to stack and then poped. Then, the vector v (loc4) can be moved to stack and compared. cc @brianrmurphy

**Comment by rahxephon89** [comment]
The following code without using an inline function does not trigger the issue:

```
    fun test_for_each_mut() {
        let v = vector[1];
        let i = 0;
        let len = vector::length(&v);
        while (i < len) {
            let x = vector::borrow_mut(&mut v, i);
            *x = 2;
            i = i + 1
        };
        assert!(v == vector[2], 0);
    }
```

By checking the bytecode, the only difference is that the inline version does something like `CopyLoc[2](loc2: &mut vector<u64>)`, which copies the mutable reference and at the end of execution the copied reference is not popped. The version without inline function does not copy it. So solving the issue #11117 may solve this one. cc @brianrmurphy @wrwg @vineethk

**Comment by brmataptos** [comment]
I suggest you add a use of `x` at the end, perhaps returning its length.
This will make the test less sensitive to dead code elimination.

**Comment by brmataptos** [comment]
This is likely handled by #11119 .
