### ISSUE TITLE
[Feature Request][compiler-v2] Dead code analysis

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#11147]
Identify dead code and produce errors for it. Also identify unused types, functions, variables and fields

**Comment by wrwg** [comment]
Includes detecting unreachable code. Includes unused variables which are not starting with `_`.

**Comment by vineethk** [comment]
To add a bit more structure, here is a list of various warnings that need to be implemented in v2:
- unused assignment
- dead or unreachable code
- unused type parameter
- unused attribute
- unused parameter
- unused local
- unnecessary trailing semicolon
- invalid use of divergent expression

The plan is to break these down into smaller pieces and tackle them.

**Comment by vineethk** [comment]
I have broken this issue up into multiple smaller independent ones:
- https://github.com/aptos-labs/aptos-core/issues/11704
- https://github.com/aptos-labs/aptos-core/issues/11706
- https://github.com/aptos-labs/aptos-core/issues/11707
- https://github.com/aptos-labs/aptos-core/issues/11708
- https://github.com/aptos-labs/aptos-core/issues/11709
- https://github.com/aptos-labs/aptos-core/issues/11710

So, closing this one.
