### ISSUE TITLE
[Feature Request][compiler-v2] Attribute analysis

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#11146]
- Implement analysis of well-known attributes (test, test_only, view, resource_group, deprecated, ...). 
- Check specific Aptos rules for entry functions. 
- This should reuse/refactor existing `[extended_checks.rs](http://extended_checks.rs/)`

**Comment by 0xaptosj** [comment]
Hi I recently discovered view function allows you to do state change in it. I think this might be confusing. 
Additionally it leads to inconsistency between running it on explorer vs unit test.

Here's an example. Note the unit test would pass meaning the state change `counter.counter = counter.counter + 1;` is persisted. But when i deploy it to testnet and call it via explorer, it always returns 1. [Testnet deployment](https://explorer.aptoslabs.com/account/0x875fb4fda8838a55974f9f4342b19bbee9e0d4f7bc367483b9a27811c19a369d/modules/view/counter2/get?network=testnet)

```rust
module counter_addr::counter2 {
    #[view]
    public fun get(): u64 acquires Counter {
        let counter = borrow_global_mut<Counter>(@counter_addr);
        counter.counter = counter.counter + 1;
        counter.counter
    }

    #[test(owner = @test_view)]
    fun test_happy_path(owner: &signer) acquires Counter {
        init_module(owner);

        let i1 = get();
        let i2 = get();

        assert!(i1 == 1, 1);
        assert!(i2 == 2, 1);
    }
}
```
