### ISSUE TITLE
Measure consensus Nakamoto coefficient

### ISSUE THREAD

**Issue by alfredonodo** [aptos-labs/aptos-core#11170]
Hi,
in order to compare the decentralisation of the consensus protocol, it would be important to know the Nakamoto coefficient, which is the measure of the smallest number of independent entities that can act collectively to block the consensus of a blockchain.
There is an interesting [open source third party project](https://nakaflow.io/) that compares all major blockchains. Unfortunately, I do not have sufficient expertise to add [Aptos to it](https://github.com/xenowits/nakomoto-coefficient-calculator/issues/16#issuecomment-1826757138). Can anyone help me on this?
Thank you

**Comment by perryjrandall** [comment]
Hey I put up a PR here 

https://github.com/xenowits/nakomoto-coefficient-calculator/pull/50

**Comment by alfredonodo** [comment]
Done
