### ISSUE TITLE
[Bug][Compiler] Evaluation order of op is not correctly implemented in either V1 or V2

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11270]
# 🐛 Bug

For the function `test` in the test case [binop_eval_order](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-compiler-v2/transactional-tests/tests/control_flow/binop_eval_order.move):

```
    public fun test(): u64 {
        let a = 1;
        a + {a = a + 1; a}
    }
}
```

the correct evaluation order is left to right so the return value of test should be 3. However both V1 and V2 compiler generate the incorrect result of 4 currently.

**Comment by vineethk** [comment]
For now, we have decided to use the existing semantics of v1. Thus, this is considered not a bug for v1, and v2 currently has the same behavior as v1 for the given program (so, closing this bug).

However, there is a related issue being tracked where the semantics differ: https://github.com/aptos-labs/aptos-core/issues/11447
