### ISSUE TITLE
[Feature Request] [IDE] Add original `Move.toml` manifest of the dependency to the `build` directory

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#1131]
# 🚀 Feature Request

Let's add an original dependency manifest to provide the original addresses. This would allow better support for the IDEs. Also, it removes the need to have an additional YAML parser just to read this one file. 

## Motivation

After calling `aptos move compile`, the command-line utility loads all the dependencies in the root `build` directory with the following tree:
```
└── MoveStdlib
    ├── bytecode_modules
    ├── bytecode_scripts
    ├── docs
    ├── source_maps
    └── sources
        ├── ACL.move
        ├── ASCII.move
         .......
    ├── BuildInfo.yaml
```

`.move` files are the original sources of the git dependency, and `BuildInfo.yaml` contains address information of the dependency (among the other things). 

There is no original `Move.toml`. It would be helpful to have to implement "Go-to-definition" for named addresses provided by the dependencies. It's somewhat implementable using a `BuildInfo.yaml` file, but it gives a different low-level view of the addresses, confusing the users. 

## Pitch

1. Data provided in `BuildInfo.yaml` could be serialized as a TOML file instead, removing the need for an additional parser. 
2. Add original `Move.toml` near the `BuildInfo.yaml`.
.
@gregnazario

**Comment by gregnazario** [comment]
Oh, that seems silly, why are there two parsing systems.  This is somewhere in https://github.com/move-language/move

**Comment by gregnazario** [comment]
Closing this, it's in upstream move and basically can't change it now
