### ISSUE TITLE
[Feature Request] Token Indexer improvements

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#1132]
# 🚀 Feature Request

## Motivation

Existing problems to be improved
1. we use u64 in events and diesel only support i64 now.  The serde might have issue later.
2. no easy way to test the processor. need to add token write API in API context and setup processor specific test
3. no burn event and creation event missing initial supply
4. need to add more
    a. retrieve token metadata from URI and store them in indexer DB
    b. finish the collection, ownership tables and token metadata tables
5. move option<T> is serialized in a wrong format now e.g. maximum: Option<u64>  is `"maximum": {
    "vec": []
  },`
6. txn timestamp is not the correct event timestamp

**Comment by davidiw** [comment]
feel free to re-open if need be
