### ISSUE TITLE
[Bug] [Compiler V2] Abort wrongly typed in statements

### ISSUE THREAD

**Issue by fEst1ck** [aptos-labs/aptos-core#11484]
# 🐛 Bug

`abort` when used in statements are not typed correctly:
```move
fun test(): u8 {
	// abort(42) // this works
	abort 42; // this doesn't
}
```
gives error
```
+ error: expected `u8` but found `()`
+    ┌─ tests/ability-checker/bug.move:14:11
+    │
+    │         abort 42;
+    │                 ^
```
Interestingly, this type checks
```move
fun test(): u8 {
	if (true) {
		abort 42;
	};
	42
}
```

Similar issues exist for `return`.
## Expected Behavior

All of the above programs should type check.

**Comment by wrwg** [comment]
Need to check whether this is actually working in v1

**Comment by wrwg** [comment]
What we may need is a heuristic to give error message about missing or superfluous semicolon

**Comment by brmataptos** [comment]
May be related to #11708.

**Comment by wrwg** [comment]
Low priority for v2-stable

**Comment by rahxephon89** [comment]
Confirmed that V1 behaves the same except that it generates the warning `unnecessary trailing semicolon`. cc @fEst1ck @wrwg

**Comment by wrwg** [comment]
We have already a bug for trailing semicolon, so we can close this one.
