### ISSUE TITLE
[Bug] [Compiler V2] Bug in ability checker

### ISSUE THREAD

**Issue by fEst1ck** [aptos-labs/aptos-core#11491]
# 🐛 Bug

The following program passes ability checking
```move
module 0x42::test {
	struct Impotent {}

	fun test(): Impotent {
		let x = Impotent {};
                // x still used
		if (false) { // for the branch instruction x is used before and after
                         // x used
			return x;
		} else {
                         // x not used
                         // no drop generated here!
		};
		return Impotent {}
	}
}
```
The problem is that `x` is not released by any instruction. To fix it, we need to check for variables released where the live after set of an instruction is not the live before set of its successor instruction.

**Comment by brmataptos** [comment]
This vaguely resembles a "critical edge" problem, and it might help to just pre-process the CFG to insert empty blocks on every critical edge.  Then again, if you're only checking for drops at each instruction you'd also need a NOOP inserted in that empty block.
