### ISSUE TITLE
[Bug] Links on Coinmarketcap are outdated

### ISSUE THREAD

**Issue by eirikhanasand** [aptos-labs/aptos-core#11509]
# 🐛 Bug
Most links on your coinmarketcap site are outdated.

## To reproduce
Open https://coinmarketcap.com/currencies/aptos/ in a computer browser, and you will find the outdated links on the lefthand side. Telegram seems to lead to an old chatroom. Whitepaper link is also outdated, after some digging I found it had been moved to a seperate repository.

**Stack trace/error message**
Not relevant

## Expected Behavior
All links should lead to the most up to date information. 
Whitepaper link should lead to https://github.com/aptos-labs/developer-docs/blob/main/static/papers/Aptos-Whitepaper.pdf
Telegram I dont know where should lead.
Discord link should be added.
LinkedIn could also be added.

## System information
Not relevant

## Additional context
These links are important for both developers, investors and anyone else checking out the project. It is important that all of these are provided and up to date to convey the seriousness of the project.

**Comment by eirikhanasand** [comment]
Github link should also be added on there, its very off putting when its missing.

**Comment by Sigma2345** [comment]
should the Linkedin link be of 
aptos labs - https://www.linkedin.com/company/aptoslabs/ 
or 
aptos foundation - https://www.linkedin.com/company/aptos-foundation/        ??

**Comment by eirikhanasand** [comment]
Preferably both, I think there should be a way to do it? If only one is
possible I would put Aptos labs since it has more followers and will better
convey how large of a community there is supporting Aptos.

man. 25. des. 2023 kl. 08:08 skrev quaternion ***@***.***>:

**Comment by gregnazario** [comment]
Hi looks like all have been updated @eirikhanasand please reopen and let us know if there's any other links you think are incorrect.  Thanks!
