### ISSUE TITLE
Cannot develop on Aptos because of error in framework

### ISSUE THREAD

**Issue by AndRockSYS** [aptos-labs/aptos-core#11526]
I'm developing a simple managed_coin like in an example and it has no errors, but when I'm compiling i get this errors
![зображення_2023-12-31_163504876](https://github.com/aptos-labs/aptos-core/assets/106549955/4d2cf46c-ae81-4426-89ec-f5a13fc521a2)

**Comment by banool** [comment]
Can you share your Move.toml? Odds are good that you need to use the framework from a different branch, eg mainnet rather than main.
