### ISSUE TITLE
[Prover][Bug] issue with the return type of `update_field`

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#11532]
The return type of `update_field` is supposed to be the type of the struct. However, it's set to be the type of the field in Prover currently.

### How to reproduce
Go to `aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN`, and run `aptos move prove`

```
aptos move prove
error: expected `AccountLimits::Window<CoinType>` but found `u64` (update field)
    ┌─ /Users/jpark/Work/aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/AccountLimits.move:450:9
    │
450 │ ╭         update_field(update_field(receiving,
451 │ │             window_inflow, receiving.window_inflow + amount),
452 │ │             tracked_balance, receiving.tracked_balance + amount)
    │ ╰────────────────────────────────────────────────────────────────^
...
```

### Expected output

Prover proves it without such an error.

**Comment by junkil-park** [comment]
Here is a minimal example that reproduces the issue:
```
module 0x42::update_field {
    struct R {
        x: u64,
        y: u64,
    }
    
    fun f(r: &mut R) {
        r.x = 1;
    }
    spec f {
        aborts_if false;

        ensures r == update_field(old(r), x, 1); // this works fine.

        ensures update_field(old(r), x, 1); // producing a wrong error message as follows:
        // error: expected a struct with field `x` but found `bool` (update field)
        //    ┌─ update_field.move:20:17
        //    │
        // 20 │         ensures update_field(old(r), x, 1); // producing a wrong error message
        //    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        //
        // error: expected `bool` but found `update_field::R`
        //    ┌─ update_field.move:20:30
        //    │
        // 20 │         ensures update_field(old(r), x, 1); // producing a wrong error message
        //    │
    }

    // spec fun assign_x_1(r: R): R {
    //     update_field(r, x, 1) // error: expected `update_field::R` but found `u64` (update field)
    // }
}
```

**Comment by rahxephon89** [comment]
> Here is a minimal example that reproduces the issue:
> 
> ```
> module 0x42::update_field {
>     struct R {
>         x: u64,
>         y: u64,
>     }
>     
>     fun f(r: &mut R) {
>         r.x = 1;
>     }
>     spec f {
>         aborts_if false;
> 
>         ensures r == update_field(old(r), x, 1); // this works fine.
> 
>         ensures update_field(old(r), x, 1); // producing a wrong error message as follows:
>         // error: expected a struct with field `x` but found `bool` (update field)
>         //    ┌─ update_field.move:20:17
>         //    │
>         // 20 │         ensures update_field(old(r), x, 1); // producing a wrong error message
>         //    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
>         //
>         // error: expected `bool` but found `update_field::R`
>         //    ┌─ update_field.move:20:30
>         //    │
>         // 20 │         ensures update_field(old(r), x, 1); // producing a wrong error message
>         //    │
>     }
> 
>     // spec fun assign_x_1(r: R): R {
>     //     update_field(r, x, 1) // error: expected `update_field::R` but found `u64` (update field)
>     // }
> }
> ```

I think the second error message: "error: expected `bool` but found `update_field::R`" is correct right?

**Comment by rahxephon89** [comment]
> error: expected a struct with field `x` but found `bool` (update field)

The first error message is incorrect because we do not consider the case when the expected type is not struct when the constraint is struct: https://github.com/aptos-labs/aptos-core/blob/0b5bb471418e36b5f5097f70b8c2cfd9e9b7767d/third_party/move/move-model/src/ty.rs#L1688
