### ISSUE TITLE
[Bug][move-compiler] more tests for for loops

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#11583]
# 🐛 Bug

Somehow for loops landed (#10711) without a bug linked to it.  It also could use some better tests.  For example:
- nested loops with break and continue
- transactional test to show that legacy "for_user" code doesn't just pass the compiler but also links and runs
- third_party/move/move-compiler/transactional-tests/tests/control_flow/break_continue_for_loop.exp is a compilation error due to a typo.
- tests with compiler-v2.

Creating this bug to hang some tests.

**Comment by vineethk** [comment]
@brmataptos Should we close this based on your recent PR https://github.com/aptos-labs/aptos-core/pull/11584?

**Comment by brmataptos** [comment]
FIxed by https://github.com/aptos-labs/aptos-core/pull/11584
