### ISSUE TITLE
[Bug] CLI doesn't seem to correctly invalidate cached move on upgrade

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#1159]
# 🐛 Bug

## To reproduce
First, build the `aptos` CLI from main (currently 15c86baf0cd11e1d485832fc8b488ed77348b034):
```
cargo install --git https://github.com/aptos-labs/aptos-core.git --rev 15c86baf0cd11e1d485832fc8b488ed77348b034 aptos 
```

Now pull the code and run the move tests:
```
git clone git@github.com:banool/aptos-infinite-jukebox.git
git checkout 6e5b41c140a480137918e8df64f1f73a32d2ad56
cd move_module
aptos move test
```

Output: https://gist.github.com/banool/6997b4d0760a0398a22db624eba7b4ee

## Expected Behavior
The tests should pass, or at least if something has changed that makes my move invalid, the error message should be more descriptive. This seems like an internal error. These tests were passing with my previous build of the CLI (it said 0.1.1, but that could be from any revision).

## Additional context
From the 0.1.1 from our releases, I get different errors. For example:
```
error[E04007]: incompatible types
    ┌─ ./sources/AptosInfiniteJukebox.move:244:17
    │
 61 │         next_song_votes: IterableTable::IterableTable<address, Vote>,
    │                                                       ------- Expected: 'address'
    ·
244 │         assert!(IterableTable::borrow(votes, &addr2) == &vote2, Errors::internal(E_TEST_FAILURE));
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │                 │                            │
    │                 │                            Given: '&address'
    │                 Invalid call of '(Std=0x1)::IterableTable::borrow'. Invalid argument for parameter 'key'
```

If I make the change it suggests though, it says it's wrong, so I suspect my code is correct for the newer version of the compiler, bar these deeper errors.

**Comment by banool** [comment]
Very strangely I just pulled https://github.com/aptos-labs/aptos-core/releases/download/cli-latest/aptos-v0.1.0-linux-x86_64.zip and found the tests failed, like the last code block above, but they passed with https://github.com/aptos-labs/aptos-core/releases/download/cli-latest/aptos-v0.1.0-macosx-arm64.zip. Probably not directly related to this issue though.

**Comment by wrwg** [comment]
All keys for Table.move have been change to values instead of references. This breaking change became necessary because of restrictions in Move borrow semantics; see also https://github.com/move-language/move/issues/95#issuecomment-1123020857.

Is it possible that we did not update derived data structures like IterableTable (@lightmark)?

**Comment by lightmark** [comment]
It is definite related to my change and I updated `IterableTable` too here:
see https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/IterableTable.move

**Comment by banool** [comment]
Okay so I noticed that I was getting this error:
```
error[E04007]: incompatible types
    ┌─ ./sources/AptosInfiniteJukebox.move:192:14
    │
191 │     fun iterable_table_borrow_mut_with_default<K: copy + drop + store, V: drop + store>(table: &mut IterableTable::IterableTable<K, V>, key: K, default: V): &mut V {
    │                                                                                                                                              - Given: 'K'
192 │         if (!IterableTable::contains(table, key)) {
    │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid call of '(Std=0x1)::IterableTable::contains'. Invalid argument for parameter 'key'
    │
    ┌─ /Users/dport/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/sources/IterableTable.move:87:93
    │
 87 │     public fun contains<K: copy + store + drop, V: store>(table: &IterableTable<K, V>, key: &K): bool {
    │                                                                                             -- Expected: '&K'
```
But looking at https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/IterableTable.move, `contains` expects `K`, not `&K`. This is interesting because I just did a fresh install of the `aptos` CLI. To fix this, I deleted `~/.move`, which made the CLI download that stuff again. Now the dependent code is correct and it's correctly telling me to update everything to use a value instead of a ref.

@gregnazario is this is a known issue with the CLI? I suspect we need to version the cached move stuff, and then on an invocation of a newer version of the CLI, invalidate that cache if the version of the compiler has changed. I'm not sure how much of this stuff we have already.

**Comment by banool** [comment]
I need to look in to this a bit more. It could be the CLI or the move deps (which is a problem in itself, it's pretty hard to get the right combo of CLI + aptos-framework revision + devnet move version).

**Comment by davidiw** [comment]
closing this out, feel free to re-open
