### ISSUE TITLE
[Bug][move-compiler-v2] Compiler V2 dump debugging leaves .bytecode and .dot files in random places

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#11636]
# 🐛 Bug

Maybe this can be put in some common place to make it easier to cleanup.

At the least, it should be documented so devs know to remove them occasionally.  We could even provide a script to do so.

**Comment by brmataptos** [comment]
Note that there are some `.bytecode` files checked into git, e.g.: `third_party/move/move-prover/tests/xsources/design/simple_9_usage_analysis.bytecode`.  Should these be removed?

**Comment by drstevenbrule** [comment]
> Note that there are some `.bytecode` files checked into git, e.g.: `third_party/move/move-prover/tests/xsources/design/simple_9_usage_analysis.bytecode`. Should these be removed?

Aren't these just illustrative examples? Where else are you seeing these files?
