### ISSUE TITLE
Compile error with library

### ISSUE THREAD

**Issue by AndRockSYS** [aptos-labs/aptos-core#11658]
![image](https://github.com/aptos-labs/aptos-core/assets/106549955/a81bfdb1-065c-4197-bae2-9abe986d6214)

I'm getting this error every time I want to compile a script, even thought, I do not import stake.move contract.

**Comment by rahxephon89** [comment]
Hi @AndRockSYS, thanks for reporting this. Could you give more information about the CLI you are using and the script you are trying to compile?

**Comment by AndRockSYS** [comment]
> Hi @AndRockSYS, thanks for reporting this. Could you give more information about the CLI you are using and the script you are trying to compile?

Hi! I'm just using a regular Aptos CLI that I used before, I didn't have this error all the time. The script is just a regular coin from aptos_framework::coin library, but actually script doesn't matter at all, I always have these errors.
![image](https://github.com/aptos-labs/aptos-core/assets/106549955/f77043ba-46a7-4553-93eb-a839dc1f2d58)
This is from Move.toml if it can help you

**Comment by rahxephon89** [comment]
It is possible that the aptos cli you are using (you could use `aptos --version` to check the concrete version) cannot support the newly added smart contract/specifications on the latest main branch. Could you use the latest CLI and try again?

**Comment by AndRockSYS** [comment]
> It is possible that the aptos cli you are using (you could use `aptos --version` to check the concrete version) cannot support the newly added smart contract/specifications on the latest main branch. Could you use the latest CLI and try again?

Oh yeah, it's such a silly one. I just updated Aptos and it's gone. Thank you so much!
