### ISSUE TITLE
aptos-move-analyzer 0.1.1 is not sync with the last version 2.4.0 [Bug]

### ISSUE THREAD

**Issue by dancespiele** [aptos-labs/aptos-core#11668]
# 🐛 Bug

With the last version apt move 2.4.0 my vscode complains if I use the new loop `for`  also I don't autocomplete and I cannot go to any reference anymore

## To reproduce

**Code snippet to reproduce**
install apt move 2.4.0
install aptos-move-analyzer 0.1.1
add the extension aptos-move-analyzer 0.1.1 in vscode

**Stack trace/error message**
error if I use the new loop `for`:
```
: unexpected token
   │78 │     for (i in 0..n) {   │         -  ^ Expected ')'   │         │      │         To match this '('""
```

## Expected Behavior
* Vscode should not complain about new loop `for`
* autocomplete and go to reference should work again

## System information

**Please complete the following information:**
- Aptos Core Version: 2.4.0
- Rust Version: 1.74.1
- Computer OS: Manjaro Linux
- aptos-move-analyzer version: 0.1.1
- aptos-move-analyzer vscode extension: 0.1.1

**Comment by banool** [comment]
CLI 2.5.0 has been released. Please reopen this issue if the problem persists.
