### ISSUE TITLE
[Bug][Prover][Compiler-v2] V2 bytecode does not work with the prover when the code contains constants

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11673]
# 🐛 Bug

When the Move code contains constants such as `const MAX_FRACTIONAL_PART: u128 = 0xFFFFFFFFFFFFFFFF;`, [constant_map](https://github.com/aptos-labs/aptos-core/blob/30e05cf5f025096f6c8e60e642d43bfded6270ff/third_party/move/move-ir-compiler/move-bytecode-source-map/src/source_map.rs#L91) is only generated V1, not V2. So when the prover tries to use the bytecode generated by V2, panic will happen because of the code [here](https://github.com/aptos-labs/aptos-core/blob/c7375b86ff492862f49ee56e994fed9c8af71709/third_party/move/move-model/src/builder/module_builder.rs#L1155).

**Comment by brmataptos** [comment]
Do we have a script/process to follow to exhibit the original bug?

**Comment by rahxephon89** [comment]
> Do we have a script/process to follow to exhibit the original bug?

run `ENV_TEST_FEATURE=v2 cargo test test_bitvector` in `third_party/move/move-prover`.

**Comment by rahxephon89** [comment]
Confirmed that the constant map can be [accessed](https://github.com/aptos-labs/aptos-core/blob/c7375b86ff492862f49ee56e994fed9c8af71709/third_party/move/move-model/src/builder/module_builder.rs#L1155) when running the prover in V2 mode.
