### ISSUE TITLE
[Bug][compiler-v2] Do not generate dead code in the given case

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#11689]
# 🐛 Bug

Compared to v1, v2 compiler is generating some additional dead code. We should not do so when possible, a specific instance is attached.

## To reproduce

Consider the following code:
```
module 0xc0ffee::m {
    fun test() {
        abort 1
    }
}
```

v1 compiles it down to:
```
module c0ffee.m {
test() /* def_idx: 0 */ {
B0:
        0: LdU64(1)
        1: Abort
}
}
```

v2 compiles it down to:
```
module c0ffee.m {
test() /* def_idx: 0 */ {
B0:
        0: LdU64(1)
        1: Abort
B1:
        2: Ret
}
}
```

Notice the additional `Ret` instruction.

## Expected Behavior

Ideally, v2 would not produce the additional `Ret` instruction.

**Comment by rahxephon89** [comment]
I will close the similar issue #11670 because this one has more info

**Comment by vineethk** [comment]
Fixed in https://github.com/aptos-labs/aptos-core/pull/11790
