### ISSUE TITLE
[Bug][Compiler-v2] Process got killed when running unit tests in aptos-gas-schedule-updator using V2

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11720]
# 🐛 Bug

When running the test in `aptos-gas-schedule-updator` using the command `MOVE_COMPILER_EXP=no-safety MOVE_COMPILER_V2=1 cargo test --release`, the process got kill after 2 mins. V1 does not have this problem and can finish testing in 5 mins.

**Comment by rahxephon89** [comment]
I think it got killed because of excessive memory usage.
<img width="826" alt="Screenshot 2024-01-23 at 7 01 56 PM" src="https://github.com/aptos-labs/aptos-core/assets/10296575/bebfa9fc-b1f8-464a-9006-9fac9100d2f2">

**Comment by brmataptos** [comment]
I hadn't enabled Vector constant folding for general code yet, but with that change and the AST simplification PR (https://github.com/aptos-labs/aptos-core/pull/11553) doesn't run out of memory any more.  It's still kind of slow to compile.

**Comment by wrwg** [comment]
After simplification landed, should investigate where and why this happens

**Comment by brmataptos** [comment]
This particular case is a completely constant vector, so once we convert it to a constant vector load the problem goes away with this particular example.

But a slight tweak to the example will exhibit the problem again:  Adding a single non-constant value to the vector will lead to the same problem.

The best way to debug this is probably to create a test which uses a slightly smaller vector (mostly constant, but with 1 variable input) that still runs but uses a lot of memory, and figure out where/why it is using so much memory.

**Comment by brmataptos** [comment]
Ok, I'm puzzled about how this loads in the VM, since a simpler standalone test which pretty much just creates this vector fails to load (both V1 and V2) with too many constants as a move-compiler*/transactional-test/:
```
task 0 'publish'. lines 1-1538:
Error: value (146995) cannot exceed (65535) for constant_size
```
Perhaps limits are set differently in the Aptos world?
