### ISSUE TITLE
[Bug][Compiler-v2][Package] Don't compile #[test] functions outside of test scenario

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11722]
# 🐛 Bug

When running the command `MOVE_COMPILER_EXP=no-safety MOVE_COMPILER_V2=true cargo run -p module-publish` in `testsuite/module-publish`,  V2 will return the error because it cannot filter out the test function `test_set` by the attribute and add it as the compilation target.

```
error: invalid access specifier
    ┌─ /Users/tengzhang/aptos-core/testsuite/module-publish/src/packages/framework_usecases/sources/resource_groups_example.move:268:67
    │
268 │     entry fun test_set(creator: &signer, owner: &signer) acquires Collection {
    │                                                                   ^^^^^^^^^^^

error: invalid call of `resource_groups_example::set`: argument count mismatch (expected 3 but found 4)
    ┌─ /Users/tengzhang/aptos-core/testsuite/module-publish/src/packages/framework_usecases/sources/resource_groups_example.move:269:9
    │
269 │         set(creator, owner, 0, string::utf8(b"a"));
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

**Comment by rahxephon89** [comment]
@brianrmurphy This happens because V2 will compile a function with the attribute `#[test]` while V1 does not. Adding attribute analysis can solve this.

**Comment by vineethk** [comment]
A similar issue exists with `#[test_only]` attributes. Code marked as such should not be part of non-test compilation target.

Addressing this should fix the related issue: https://github.com/aptos-labs/aptos-core/issues/11787.
