### ISSUE TITLE
[Bug] EXECUTION_LIMIT_REACHED in test_smart_data_structures_gas

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11750]
# 🐛 Bug

When running the e2e-move-test `test_smart_data_structures_gas`, the following error is generated:

```
thread 'tests::smart_data_structures::test_smart_data_structures_gas' panicked at aptos-move/e2e-move-tests/src/harness.rs:355:9:
assertion `left == right` failed
  left: Keep(MiscellaneousError(Some(EXECUTION_LIMIT_REACHED)))
 right: Keep(Success)
```

**Comment by brmataptos** [comment]
Does this just mean that we are using more gas in V2?

**Comment by rahxephon89** [comment]
> Does this just mean that we are using more gas in V2?

That is possible but need more investigation

**Comment by rahxephon89** [comment]
> test_smart_data_structures_gas

Another reason may be V2 compiles all code including `#[test]` functions so publishing a package will take more gas?

**Comment by wrwg** [comment]
@brmataptos I wonder whether what Teng said above will be covered by the attribute work? Please unassign if not.

**Comment by wrwg** [comment]
Needs tests but should be done

**Comment by rahxephon89** [comment]
Confirmed that it is fixed @wrwg @brmataptos
