### ISSUE TITLE
[Bug][Compiler-v2]  unbound module in friend declaration

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11787]
# 🐛 Bug

When using V2 compiles the [DPN](https://github.com/aptos-labs/aptos-core/tree/main/third_party/move/documentation/examples/diem-framework/move-packages/DPN), the following error is generated:

```
error: unbound module `0x1::RolesTests` in friend declaration
   ┌─ /Users/tengzhang/aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/Roles.move:16:5
   │
16 │     friend DiemFramework::RolesTests;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unbound module `0x1::ValidatorOperatorConfigTests` in friend declaration
   ┌─ /Users/tengzhang/aptos-core/third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/Roles.move:18:5
   │
18 │     friend DiemFramework::ValidatorOperatorConfigTests;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

It might be related to the friend check and attribute filtering. @vineethk @brianrmurphy

**Comment by vineethk** [comment]
Here is what is happening:
- There is code in the package's `sources` directory, which is marked as `#[test_only]`, that references modules in the package's `tests` directory.
- When doing a `aptos move compile`, stuff in `tests` directory is not included in the compilation, which I believe is the correct semantics.
- However, in compiler v2, we are not yet filtering out `test_only` attributes. Thus, code in `sources` references stuff not included in compilation, causing this error as a side-effect.

If we do `aptos move test`, which does include stuff in `tests` directory for compilation, these errors go away (even with attribute filtering not implemented).

This issue should get resolved when https://github.com/aptos-labs/aptos-core/issues/11722 is fixed.

**Comment by brmataptos** [comment]
How are you running on the diem code?  Do you use thirdparty move or aptos move?
