### ISSUE TITLE
[Feature Request] unit test to generate and serialize core data structures

### ISSUE THREAD

**Issue by huitseeker** [aptos-labs/aptos-core#11824]
## Prior refs

In light of thinking to facilitate the development of a self-contained light client for Aptos, as discussed in prior issues [#7401](https://github.com/aptos-labs/aptos-core/issues/7401) and [#10747](https://github.com/aptos-labs/aptos-core/issues/10747), I'd like to request additional support in the form of specific unit tests.

## This issue

As concluded in issue #10747, a light client's functionality can be segmented into three primary components:

1. Verification of Merkle proofs for the inclusion of values in the executed state Merkle root of a Block header.
2. Execution of the `EpochState` ratcheting for the light client.
3. Verification of the `LedgerInfoWithSignatures` signature, assuming an up-to-date `TrustedState`.

Given these components, ensuring data compatibility with the Aptos blockchain necessitates examination of three key pieces of serialized data:

- A `SparseMerkleProof`,
- A `LedgerInfoWithSignatures`,
- An `EpochChangeProof`.

The purpose of these tests is to produce samples of the aforementioned data structures. This is crucial for a clean-room (yet compatible) reimplementation of Aptos data formats, especially since these assets are signed, and accurate hashing and serialization/deserialization (ser/de) processes are vital.

Currently, generating these assets requires modifications to the Aptos blockchain code or intercepting messages received by a full node. However, maintaining a programmatic method for generating these samples would be beneficial. It would act as an early warning system for changes in the core consensus data structures' standards and could highlight backward-compatibility issues when tests fail.

## Proposed Test Template:
A potential approach for such a test could involve a somewhat artificial serialization/deserialization (ser/de) round-trip test:

- Deterministically generate data for each of the three types mentioned above.
- Serialize the data as would be done by an Aptos node.
- Compute a straightforward, non-`CryptoHasher` hash of these bytes and compare it against a hard-coded value. For maintenance simplicity, consider using [expect-test](https://docs.rs/expect-test/latest/expect_test/).
- Deserialize the data and verify equality.
- Optionally, if an environment variable (e.g., APTOS_TEST_SERIALIZE) is set, write the serialized bytes to a file.

This setup would serve multiple purposes:

- The hash comparison acts as a tripwire for changes that could affect light client code.
- It provides a straightforward method for obtaining all necessary sample data for maintaining a compatible light client.

**Comment by huitseeker** [comment]
@zekun000 @aching might have some ideas (or suggest something I've missed?)

**Comment by msmouse** [comment]
Looks like printing out some proofs here and there from this [ugly monstrous integration test](https://github.com/aptos-labs/aptos-core/blob/ddd07542c24e8704cd26ee6ba5ca5f3b6cd6ed8e/execution/executor/tests/storage_integration_test.rs#L193) will serve your purpose?

**Comment by huitseeker** [comment]
@msmouse Yes, probably, though that test does need some decomposition indeed:
- IIUC, [this](https://github.com/aptos-labs/aptos-core/blob/ce593c4b0c9f066c821b80c403d6b5f8ec12263b/execution/executor-test-helpers/src/integration_test_impl.rs#L191C1-L195C1) is where I'd extract the data necessary for testing `verify_and_ratchet`, which would cover the `EpochChangeProof` and the `LedgerInfoWithSignatures`
- it's still unclear to me if this relates to the `SparseMerkleProof` generation, which relies on doing a low-level authenticated read.

Would you have further pointers on the later point?

**Comment by msmouse** [comment]
@huitseeker I added some more proof verification to that test in https://github.com/aptos-labs/aptos-core/pull/12006

Does it help?

**Comment by huitseeker** [comment]
This helps quite a bit, thanks @msmouse !

**Comment by lbmeiyi** [comment]
Thank you for your contribution to the Aptos network, sounds like the issue is resolved for now. If you encounter further challenges, please let us know!
