### ISSUE TITLE
Remove support for PRE_GENESIS state.

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#1187]
We define `pub const PRE_GENESIS_VERSION: Version = u64::max_value();` and support running the genesis txn (0) on top of the pre genesis state persisted at that version. 

We think it's paranoid to support such a feature.

Remove it. Remove relevant functionality and tests.

**Comment by zcchahaha** [comment]
Related PRs:
https://github.com/aptos-labs/aptos-core/pull/1692
https://github.com/aptos-labs/aptos-core/pull/1689
https://github.com/aptos-labs/aptos-core/pull/1688
https://github.com/aptos-labs/aptos-core/pull/1655
https://github.com/aptos-labs/aptos-core/pull/1647
https://github.com/aptos-labs/aptos-core/pull/1620
