### ISSUE TITLE
[Bug][Compiler-V2] for loop parsing issue

### ISSUE THREAD

**Issue by mergd** [aptos-labs/aptos-core#11921]
# 🐛 Bug

Just a small issue with the parser.

If there's no space between the for and the first parenthesis – this is the error that shows up.
```move


241 │         for(idx in 0..10){
    │            -    ^ Expected ')'
    │            │     
    │            To match this '('

```

## Expected Behavior

It should just work (`if` doesn't require this space to compile for ex.)
## System information

**Please complete the following information:**
- Aptos Core Version: aptos-move 2.4.0

- Rust Version
- Computer OS

**Comment by WGB5445** [comment]
I have identified the cause of this issue, and I am currently working on resolving it.
