### ISSUE TITLE
[Bug] Testnet Faucet CORS issue

### ISSUE THREAD

**Issue by hariria** [aptos-labs/aptos-core#1195]
# 🐛 Bug

CORS policy needs to be modified for localhost faucet

## To reproduce
Start Local Testnet on localhost at `8080`
Start Faucet on localhost  at `8000`
Query the faucetClient (ie. via SDK)
```bash
Access to XMLHttpRequest at 'http://0.0.0.0:8000/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by jjleng** [comment]
I can verify that the CORS header exists. It should work if you pull latest code.
![Screen Shot 2022-06-13 at 8 58 34 PM](https://user-images.githubusercontent.com/962285/173490401-295cb122-29f1-476a-b3f2-9d3177ba2c3b.png)

**Comment by hariria** [comment]
@jjleng what happens when you GET request for `localhost:8000`
