### ISSUE TITLE
[Feature Request] Be able to identify if a struct could be event(V2) in ABI

### ISSUE THREAD

**Issue by zfy0701** [aptos-labs/aptos-core#11980]
# 🚀 Feature Request

In event v1, every event should have a correspond `0x1::event::EventHandle`  in abi retrieve from account module API.
In event v2, however, since there is no `EventHandle` found for them, it's now impossible to tell which structure could be use as a event.

## Motivation
When writing codegen for aptos or other utils based on ABI, it's best we could identify which struct are events and then generate code different.

## Pitch

**Describe the solution you'd like**
Would like a `is_event` field for every struct definition, e.g.

```
{
          "name": "AddStakeEvent",
           "is_event": true,
          "is_native": false,
          "abilities": [
            "drop",
            "store"
          ],
          "generic_type_params": [
            
          ],
          "fields": [
            {
              "name": "pool_address",
              "type": "address"
            },
            {
              "name": "amount_added",
              "type": "u64"
            }
          ]
        }
```

**Comment by banool** [comment]
We implemented this in https://github.com/aptos-labs/aptos-core/pull/14246. Thanks for the request!
