### ISSUE TITLE
[Feature Request] Properties in TokenData

### ISSUE THREAD

**Issue by MartianSiddharth** [aptos-labs/aptos-core#1200]
# 🚀 Feature Request
This is in conjunction with https://github.com/aptos-labs/aptos-core/issues/1199

TokenData should include storing some properties related to the NFT. 

## Motivation
For NFTs, there is a lot of information related to the content that should be stored along with the NFT. This could include attributes like traits of an NFT and their rarities. Properties can store much more information which will be useful to make NFTs complete in themselves.

## Pitch
Add an attribute 'properties to TokenData in Token.move
```
struct Property has copy, drop, store {
        name: ASCII::String,
        value: ASCII::String,
}
struct TokenData has copy, drop, store {
        // Unique name within this creators account for this Token's collection
        collection: ASCII::String,
        // Describes this Token
        description: ASCII::String,
        // The name of this Token
        name: ASCII::String,
        // Optional maximum number of this type of Token.
        maximum: Option<u64>,
        // Total number of this type of Token
        supply: Option<u64>,
        /// URL for additional information / media
        uri: ASCII::String,
        properties: Option<Vector<Property>>,
    }
```

**Comment by davidiw** [comment]
Maybe it is time to bring back my shitty table, @msmouse

**Comment by davidiw** [comment]
We are going to add a new field `properties: SimpleMap<String, String>`

will update
