### ISSUE TITLE
[compiler-v2] Move most ability checking into frontend

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#12036]
Currently we have ability checking split over the model builder frontend and stackless bytecode middle end. Specifically, we check correctness of type instantiations in stackless bytecode. This leads to some unnecessarily generic code in `ty` which is shared between frontend and middle end.

We should move all checking into the frontend except those which are related to automatic generation of implicit copies and drops. This will help cleanup the code and probably also lead to better error message.

Specifically, we should extend the `ty::Constraint` by a variant which specifies which abilities a type must have. This will allow to evaluate type instantiation constraints with error messages pointing to the actual type expression.

**Comment by brmataptos** [comment]
Be sure this fixes deep_exp, as noted in third_party/move/move-compiler-v2/transactional-tests/tests/inlining/deep_exp.move as of PR 12070.

**Comment by brmataptos** [comment]
This but also must resurrect this error:
```
error: Invalid instantiation
  ┌─ tests/ability-checker/invalid_struct_def.move:4:15
  │
4 │     struct Bar { x: Foo<u8> }
  │                  ^
```
which disappears in PR 12070.
