### ISSUE TITLE
[Bug][move-compiler-v2] keep inline functions in code until final codegen phase

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12041]
# 🐛 Bug

because inline function bodies go away by the time of stackless bytecode pipelines, any checkers in the stackless bytecode do not run on such code.

Consider for example, the buggy inline function that is not called yet anywhere:
```
module 0xc0ffee::m {
    public inline fun buggy(): bool {
        let x = 1;
        let r1 = &mut x;
        let r2 = &x;
        *r1 = 42;
        let y = *r2;
        y == x
    }

    fun test() {
    }
}
```
We do not report errors (stackless bytecode based) in the function buggy, unless it is called. This behavior may feel inconsistent to developers (some errors are reported on all functions including uncalled inline, some are not reported on uncalled inline functions).

We could either (a) document this inconsistency in the move book, or (b) consider keeping inline function bodies around in stackless bytecode purely for these checks.

B, definitely B.

**Comment by rahxephon89** [comment]
This is required if we want to use V2 model in docgen.

**Comment by wrwg** [comment]
The experiment flag for this is already there, and IIRC at least codegen, explicitly skips inline functions, so shouldn't be effected if they are kept.

**Comment by brmataptos** [comment]
When I first added inlining there were problems in various later stages if I didn't remove the inlined functions.   That may have been the codegen stuff that Wolfgang says is fixed.  You should be able to keep inline functions in with
```
MVC=inlining=off cargo test -p move-compiler-v2
```
which currently shows a failure in variable-coalescing:
```
+ bug: not yet implemented: 0x6000101f03f0 : Lambda(NodeId(438), Wildcard(NodeId(436)), 0x600010122010 : Value(NodeId(437), Number(3)))
+   ┌─ tests/variable-coalescing/inlining1.move:7:13
+   │
+ 7 │         foo(|_| 3, 10)
+   │             ^^^^^
```
So there are still a few things to fix.

Btw, that experiment needs to be renamed.  Maybe "`keep_inline_functions`".  With the current name it sounds like we're disabling inlining.

**Comment by brmataptos** [comment]
(stackless) bytecode codegen doesn't like Lambda and Invoke, so we need to fix that (Invoke, at least; Lambda should only appear at call sites to inline functions, which will disappear in inlining pass).

**Comment by brmataptos** [comment]
We need
```
MVC_EXP=keep-inline-fun=off,lambda-lifting=on cargo test -p move-compiler-v2
```
but it currently fails on some of our tests due to lambda lifting not handling mutated free variables.

Added an issue to track that: https://github.com/aptos-labs/aptos-core/issues/13221.

**Comment by rahxephon89** [comment]
In PR #13239, we keep the inline function but since invoke and lambda are not supported in the code generator, we still need to keep this issue open and fix it.
