### ISSUE TITLE
[Bug][compiler-v2] Miscompilation from stackless bytecode to fileformat bytecode

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#12052]
# 🐛 Bug

Certain stackless bytecode can cause miscompilation when being translated to file format bytecode, resulting in silent but serious errors.

The following stackless bytecode (which returns 2):
```
 $t2 := 1
 $t2 := 2
 return $t2
```

produces the following file format bytecode (which incorrectly returns 1):
```
0: LdU64(1)
1: LdU64(2)
2: StLoc[0](loc0: u64)
3: StLoc[0](loc0: u64)
4: MoveLoc[0](loc0: u64)
5: Ret
```

It may take certain optimization orders for such stackless bytecode to be produced (but it may happen otherwise too?). Here is a simple way to reproduce this bug:

1. Checkout the branch `vk/ffgen-bug` of `aptos-core` (https://github.com/aptos-labs/aptos-core/tree/vk/ffgen-bug).
2. `cd third_party/move/move-compiler-v2/transactional-tests`
3. `MVC_EXP=optimize MVC_LOG=debug cargo nextest run ffgen_bug --no-capture`

This runs the compiler on the code (in ffgen_bug.move), producing the above stackless bytecode and ff bytecode:
```
    fun test(): u64 {
        let t = 1;
        t = 2;
        t
    }
```

**Comment by brmataptos** [comment]
@vineethk What is `cnr`?  Is that some local alias you use?

**Comment by vineethk** [comment]
> @vineethk What is `cnr`? Is that some local alias you use?

@brmataptos Yes, I have fixed it now: it stood for `cargo nextest run`.
