### ISSUE TITLE
[Bug] Aptos CLI should return correct exit code for failed tests

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#1207]
# 🐛 Bug

Currently `aptos move test` doesn't return correct exit code.

## To reproduce

Create a new project, make a test that always fails, e.g.:

```
#[test]
fun it_fails() {
   assert!(false, 1);
}
```

Run test and see exit code (i'm using Mac OS):

```
aptos move test
echo $?
```

See result:

```
0
```

## Expected Behavior

Exit code should equal `1`.

## Additional context

We are using exit codes in our Github CI - https://github.com/pontem-network/get-aptos

**Comment by borispovod** [comment]
@gregnazario any update on it?

**Comment by gregnazario** [comment]
It's not on my immediate plan on the future, feel free to take a look at it
