### ISSUE TITLE
Can I reverse-resolve the public key from an address or signature?

### ISSUE THREAD

**Issue by liucan163** [aptos-labs/aptos-core#12107]

**Comment by 0xaptosj** [comment]
hey checkout this [thread](https://github.com/aptos-labs/aptos-developer-discussions/discussions/14), but tldr you cannot.

**Comment by 0xaptosj** [comment]
btw fee free to post future questions in the [dev discussion](https://github.com/aptos-labs/aptos-developer-discussions/discussions), thanks!
