### ISSUE TITLE
[Bug][compiler-v2] Missing check for recursive types

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#12169]
# 🐛 Bug

Compiler v2 does not complain about recursive types (eg, in the code below) like compiler v1. This results in bytecode verification error during compilation.

```
module 0xc0ffee::m {
    struct S {
        a: u32,
        b: S,
    }
}
```

**Comment by rahxephon89** [comment]
Is this the same issue: #12119?

**Comment by vineethk** [comment]
@rahxephon89 Yes, somehow my search terms missed this, thanks for pointing it out. Closing this one as duplicate.
