### ISSUE TITLE
Function batch_transfer_coins 

### ISSUE THREAD

**Issue by liucan163** [aptos-labs/aptos-core#12165]
For this transaction type, if one of the transactions fails, will the entire transaction fail, or will it partially fail? If it partially fails, are there specific structs for the failures?

**Comment by 0xaptosj** [comment]
When you call `batch_transfer_coins` function, it's still exected in a single transaction (unless you are calling it from a move script). If one transfer fail the whole function fail and tx will be reverted

**Comment by liucan163** [comment]
Thanks
