### ISSUE TITLE
[Feature Request] Enable 20-byte account address

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#122]
# 🚀 Feature Request

## Motivation
we want to have more bytes in address to provide more addresses for future application scenarios and provide better security. 
Currently, diem move provide a feature supporting 20 bytes address. However, there are still a lot of work required to onboard 20 bytes address. Here are some of steps to be done:

step 1. fix some broken module in Move. This is still in 16 bytes and will make our test broken even if we are on 20 bytes
https://github.com/diem/move/blob/main/language/testing-infra/transactional-test-runner/src/vm_test_harness.rs#L36.

step 2: there are multiple incompatible changes on move side. The function we used no longer exists and we have to change our function call if we want to include change in step 1. some of the incompatible changes are: (1) requiring a pass custom cost table https://github.com/areshand/move/commit/1a039e4e3ffb91d902bf2eaefa77e52177b8ec6f, (2) regex pinned to a higher version in move 1.5.5,  while we pinned to a lower version 1.4.3 in multiple places, which cause conflicts

step 3: we probably could switch to use the 20 bytes address move then by updating our toml file with address20 feature

## Pitch

**Describe the solution you'd like**
use the 20-byte account address provided by move.

**Describe alternatives you've considered**
32 byte address is under discussion.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by davidiw** [comment]
Closing this out as 32-byte address is happening
