### ISSUE TITLE
[Bug][compiler-v2] Reference analysis does not flag mut borrow error

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#12214]
call_mutual_borrows_invalid.move should produce an error:

```
   fun t0(s1: &mut S, _s2: &mut S) {
       ...
        mut_mut(s1, s1);
  }
```

**Comment by wrwg** [comment]
Should be fixed, but needs to be verified

**Comment by rahxephon89** [comment]
cc @wrwg  already fixed: https://github.com/aptos-labs/aptos-core/blob/51122d9e30b0335bc2eddf51d744e810793b8417/third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/call_mutual_borrows_invalid.exp#L49
