### ISSUE TITLE
[docs] python SDK install instruction is out of date

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#12237]
1. The minimal pip3 version is needed to be updated
2. The instruction to install directly from source doesn't work because setup.py has been removed from the repo.  https://aptos.dev/sdks/python-sdk/#install-from-the-source-code

**Comment by gregnazario** [comment]
This was updated. https://aptos.dev/en/build/sdks/python-sdk#install-from-the-source-code
