### ISSUE TITLE
[Bug][compiler-v2] Missing drop ability check when value is unused

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#12309]
# 🐛 Bug

Complier v2 fails to report a missing drop ability in the following code (whereas compiler v1 does report it), causing bytecode verification error.

```
module 0xc0ffee::m {
    public fun consume<T>(_x: T) {}
}
```

**Comment by rahxephon89** [comment]
Interestingly, V1 will not complain this for the following function:
```
    fun ignore<T>(_x: T) {
        abort 0
    }
```
I think it is because it will always abort. cc @vineethk @wrwg
