### ISSUE TITLE
[Bug] CLI flag for override-size-check is missing in CLI v2.5.0

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#12385]
@banool @gregnazario 

As of CLI v2.5.0, the `--override-size-check` flag is now missing, at least for `aptos move publish`

Notably, since the [`MAX_PUBLISH_PACKAGE_SIZE`](https://github.com/aptos-labs/aptos-core/blob/cf8170e3e61b48500d47b0b750f0621507425d08/crates/aptos/src/move_tool/mod.rs#L801) hard-coded in the CLI is less than the *actual* on chain txn limit, a 63k package (like [Econia v4.2.1](https://github.com/econia-labs/econia/tree/v4.2.1-audited/src/move/econia) ) cannot be published with the CLI for included artifacts set to none

- [ ] Fix `MAX_PUBLISH_PACKAGE_SIZE` to use value from gas schedule, padding for overhead as needed 
- [x] Re-enable override size check flag

**Comment by gregnazario** [comment]
Flag was renamed to `--value` erroneously https://github.com/aptos-labs/aptos-core/pull/12386

**Comment by gregnazario** [comment]
Fixed in 3.1.0
