### ISSUE TITLE
[Bug][move-compiler-v2] double-check free variable/temporary handling in inlining and lambdas

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12424]
# 🐛 Bug

@vineethk pointed out that the distinction between `Temporary` and `LocalVariable` in the move-model AST may lead to some incorrect handling of free variables during inlining.  We've already noticed that the `free_vars` check ignores temporaries, which may or may not be a problem.

We need some more test cases where parameters of an outer function are used inside lambdas, and parameters to inlined functions are assigned to (leading to their appearance as both `Temporary` and `LocalVariable` (the latter in an `Assign` expression)).

**Comment by wrwg** [comment]
Lets just get rid of Temporary and use LocalVar everywhere. It is a bug we should have fixed long ago that parameters use Temporary. Lets better not add more stuff trying to compensate this bug.

**Comment by brmataptos** [comment]
I added a new test `transactional-tests/tests/inlining/shadowing_renamed_param.move` for both V1 and V2 and verified that it is handled correctly.  The test be submitted as part of #11553.
