### ISSUE TITLE
[Bug] Timestamp is wrong for state_checkpoint_transaction

### ISSUE THREAD

**Issue by zacharydenton** [aptos-labs/aptos-core#1246]
# 🐛 Bug

## To reproduce

Look at https://fullnode.devnet.aptoslabs.com/transactions/212443. Note the timestamp: `"timestamp":"100306"`.

## Expected Behavior

`timestamp` should be the timestamp in microseconds. For example, https://fullnode.devnet.aptoslabs.com/transactions/212444: `"timestamp":"1654276678564661"`.
## System information

**Please complete the following information:**
- 
- 
-

**Comment by CapCap** [comment]
Fixed by #1237
