### ISSUE TITLE
[compiler-v2] Need to generate vector instructions

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#12492]
Currently compiler v2 generates for functions like `vector::length` the actual call to a function, not the bytecode instruction. Those functions are still around for legacy reasons, that's why it seems to work.

**Comment by wrwg** [comment]
As long as we do not have this on mainnet, its OK

**Comment by fEst1ck** [comment]
Already done by `move-compiler-v2::file_format_generator::module_generator::ModuleContext::get_well_know_function_code`. See for example [https://github.com/aptos-labs/aptos-core/blob/8d0aa5ef42101e216ea2b5e6156381ed8729[…]y/move/move-compiler-v2/tests/file-format-generator/vector.move](https://github.com/aptos-labs/aptos-core/blob/8d0aa5ef42101e216ea2b5e6156381ed87293e10/third_party/move/move-compiler-v2/tests/file-format-generator/vector.move) [https://github.com/aptos-labs/aptos-core/blob/851f9ee81b9b2dcc6be69d1a8a81a005f941[…]ty/move/move-compiler-v2/tests/file-format-generator/vector.exp](https://github.com/aptos-labs/aptos-core/blob/851f9ee81b9b2dcc6be69d1a8a81a005f9415b0b/third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp)
