### ISSUE TITLE
[prover-v2] Boogie type error with bit vector number representatioon

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#12526]
When verifying the aptos-framework with v2 generated code, a type error is reported:

```
[INFO] 528 verification conditions
[INFO] running solver
[internal] boogie exited with compilation errors:
output.bpl(23273,9): Error: invalid type for out-parameter 0 in call to $1_vector_empty'u8': Vec bv8 (expected: Vec int)
```

This happens when `features::change_feature_flags_for_next_epoch` is inlined in some context but not verified.  Strangely, it does not happen if this function is a verification target.

The workaround is for now to declare this function opaque, which should be undone once the bug is fixed. This bug is linked from the code.

**Comment by lnteng** [comment]
I'm having this problem. But I don't understand under what circumstances this problem occurs and why.

**Comment by rahxephon89** [comment]
> I'm having this problem. But I don't understand under what circumstances this problem occurs and why.

Hi @lnteng, thanks for reporting this. Could you share the code that causes this issue?

**Comment by lnteng** [comment]
Hi @rahxephon89, I encountered this issue on this project. https://github.com/CetusProtocol/integer-mate/tree/main/aptos

There are some issues with the invalid type for the argument: int (expected: bv64).

**Comment by rahxephon89** [comment]
> Hi @rahxephon89, I encountered this issue on this project. https://github.com/CetusProtocol/integer-mate/tree/main/aptos
> 
> There are some issues with the invalid type for the argument: int (expected: bv64).

Thanks for sharing the code. I see your code contains bit operation such as : `(((r & hi_mask) >> 128) as u128)`. To prove properties with code like this, you could follow the instruction here: https://aptos.dev/move/prover/spec-lang#bitwise-operators when writing the spec. Please let me know if there are any other issues.

**Comment by rahxephon89** [comment]
@wrwg Cannot reproduce the error, maybe because the usage of `change_feature_flags_for_next_epoch` was changed. Will work on it once we have another example.
