### ISSUE TITLE
Rethink around committed version, synced version, StartupInfo etc..

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#1253]
When a node starts with a large gap behind its peers, it'll commit a lot of transactions without committing a LedgerInfo, hence the sync version is way ahead of the committed version. In this case if the node restarts, get_startup_info will fail if the difference between the two versions is larger than the state prune window. It seems a unnecessary limitation.

**Comment by davidiw** [comment]
I think this is dominated by the fact that we don't have frequent epochs. I might propose that for now, we add an epoch event every 15 minutes regardless of need for it. @zekun000

**Comment by zekun000** [comment]
epoch is not free, it creates a huge LI with all the public keys and stops processing transactions until new epoch starts. for new nodes to sync, it needs to follow the chain of trust of all epoch LIs

**Comment by davidiw** [comment]
> epoch is not free, it creates a huge LI with all the public keys and stops processing transactions until new epoch starts. for new nodes to sync, it needs to follow the chain of trust of all epoch LIs

We will need new epochs for each time someone wants to change configuration or adjust the consensus (sub)-committee, right? I suspect the frequency will be at least on the magnitude of hours?

I understand it will result in some sort of slowing down, maybe we need two chains :trollface:

**Comment by zekun000** [comment]
the current plan is to push all changes into pending queue and they'll take effect on next epoch. I think whether it's 1 day or 2 hours doesn't matter too much to me but 1 mins is not going to work. 🤷‍♂️

**Comment by JoshLind** [comment]
> I think state sync v1 has ability to cache ledger info and commit periodically instead of having only sync version increase.

IIRC, it doesn't really do this as well as we'd want. It only does this when it's in the same epoch already (the peer will respond with its `highest` ledger info, and the node will sync to it. But, even then, the `highest` could be arbitrarily far way). If it's not in the same epoch, it targets epoch ending ledger infos anyway. So, it's exactly the same as v2 😢
