### ISSUE TITLE
[Bug] Aptos CLI unit testing deficiencies

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#1256]
# 🐛 Bug

Issue filed per 2022-06-03 Discord discussion with @gregnazario.

At present, the Aptos CLI breaks with a `VMError` `INTERNAL_TYPE_ERROR` for simple `AptosFramework::Table` commands, e.g. `Table::contains`. For example [this line](https://github.com/econia-exchange/econia/blob/dea740192dcda5a7682061c73c2f59243c18a99a/src/move/econia/sources/Market.move#L267) breaks the VM as described above for [this test](https://github.com/econia-exchange/econia/blob/dea740192dcda5a7682061c73c2f59243c18a99a/src/move/econia/sources/Market.move#L419), which has been commented out in the provided commit blob but can be run locally to reproduce the error. The operation in question is a simple lookup on a custom struct type as a table key.

Additionally, the Aptos CLI offers *no* coverage testing support, which makes it insufficient for testing to software standards such as DO-178B Level A, a design specification intended to prevent catastrophic system failure. The Move CLI, however, does offer coverage testing, which allows for the implementation of pure-Move modules to 100% coverage, for instance like [this one](https://github.com/econia-exchange/econia/blob/main/src/move/econia/build/Econia/docs/CritBit.md). Since the Move CLI does not support AptosFramework native functions, developers are thus forced to use the Aptos CLI to test their code - but the CLI has the bugs described above.

Without the ability to perform coverage testing on AptosFramework native functions, Aptos developers will thus suffer an increased susceptibility to catastrophic system failure (e.g. loss of funds), and as such it is advised that the Aptos CLI be updated to include coverage testing for all AptosFramework native functions.

**Comment by magnum6actual** [comment]
Hitting this same error on tables as well after updating to current devnet.

**Comment by magnum6actual** [comment]
Resolved this for me by updating build of Aptos CLI.

**Comment by alnoki** [comment]
As discussed with @magnum6actual in Discord, the `VMError` can be resolved by omitting `--tag aptos-cli-latest` from the `aptos` CLI cargo install command on [the README](https://github.com/aptos-labs/aptos-core/tree/main/crates/aptos) - hence the CLI installation instructions were simply incorrect, and `aptos` does indeed offer support for `AptosFramework::Table` native functions.

Coverage testing, however, is still not supported, and so this issue has been split off into #1275
