### ISSUE TITLE
[Bug] Run Aptos local multi-nodes  testnet errors

### ISSUE THREAD

**Issue by KunPengRen** [aptos-labs/aptos-core#12606]
Hi, I have built the aptos from source codes successfully. I want to run a local multi-nodes testnet following the https://aptos.dev/guides/running-a-local-multi-node-network.
When I run the command
```
cargo run -p aptos-forge-cli \
        -- \
        --suite "run_forever" \
        --num-validators 4 test local-swarm
```
I face the errors below:

```
= note: ld.lld: error: unable to find library -lpq
          collect2: error: ld returned 1 exit status


error: could not compile `aptos-node` (bin "aptos-node") due to previous error
Error: Failed to build aptos-node: 'cd /aptos/aptos-core && CARGO_TARGET_DIR=/aptos/aptos-core/target cargo build --bin=aptos-node
```

By the way, if there any tutorials that can help me to run a multi-nodes testnet manually in different machines? No like the above one run in one server.

**Comment by UTYichenZhou** [comment]
Hello KunPengRen, have you managed to run a multi-node testnet manually with each node running on a separate machine? I want to do something similar and am wondering if you have figured this part out or found any useful resources/tutorials
