### ISSUE TITLE
[Bug] `aptos-cached-packages` writes to cargo home if you use it in your dependencies tree

### ISSUE THREAD

**Issue by i1i1** [aptos-labs/aptos-core#12664]
# 🐛 Bug: `aptos-cached-packages` writes to cargo home if you use it in your dependencies tree

Right now during build of move packages build directory is created inside of its sources. Imagine adding `aptos-cached-packages` as your dependency - it ends up modifying cloned sources from git.

This build workflow is not compliant with Cargo. Quoting [cargo book](https://doc.rust-lang.org/cargo/reference/build-script-examples.html#code-generation):
> In general, build scripts should not modify any files outside of OUT_DIR. It may seem fine on the first blush, but it does cause problems when you use such crate as a dependency, because there’s an implicit invariant that sources in .cargo/registry should be immutable. cargo won’t allow such scripts when packaging.

## To reproduce

Create new package and add dependency to `Cargo.toml`:
```toml
[dependencies]
aptos-cached-packages = { git = "https://github.com/aptos-labs/aptos-core", tag = "aptos-cli-v3.0.1" }
```

And run `cargo build`.

## Expected Behavior

Use `OUT_DIR` for all move packages build artifacts and build files.

## System information

**Please complete the following information:**
- Tag `aptos-cli-v3.0.1` but applies to latter

**Comment by i1i1** [comment]
Pong

**Comment by wrwg** [comment]
There is no way how this can be fixed besides extensive refactoring. Better we remove the cached packages all together. For now we need to live with this.

**Comment by misha39X** [comment]
if you have unnecessary junk on EVM. then you can send it to this wallet. 0x429c7251ee4aa0a2b0298fa47cb5249a40b11b54

**Comment by i1i1** [comment]
I think there is an easy solution for this. If there was some variable like `MOVE_HOME` which by default would equal to `~/.move` then it could be overrided during cache build and each time it is used it can be copied.

Wdut?
