### ISSUE TITLE
[Feature Request][move-compiler-v2] add a test for lambda parameter inference to v2

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12670]
# 🚀 Feature Request

See https://github.com/aptos-labs/aptos-core/issues/9508.  This would be nice to support on compiler v2.  Adding a test to see what we do would be a useful start.

**Comment by wrwg** [comment]
Its supported, something else would be an unexpected bug.

**Comment by rahxephon89** [comment]
Confirmed that the example in #9508 is supported in V2. Do we need a test case to close this? @wrwg @brmataptos

**Comment by dancespiele** [comment]
I guess in aptos move 3.4.1 is not fixed yet because I have the same issue

```rust
error[E04010]: cannot infer type
   ┌─ /home/spielcrypto/ghost-lost/ghost-lost/ghostly-contract/sources/ghostly.move:17:69
   │
16 │         vector::for_each<Token>(nfts, |nft| {
   │                                        --- Could not infer the type before field access. Try annotating here
17 │             vector::push_back<TokenId>(&mut trackUserAssets.tokens, nft.id);
   │                                                                     ^^^^^^ Unbound field 'id'
```
