### ISSUE TITLE
[Feature Request][move-compiler-v2] allow unconstrained generic inline functions

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12680]
# 🚀 Feature Request

While it's unsafe to allow instantiation of generics in general without traits or other constraints, we can probably allow inlined functions to be used with arbitrary generic type parameters (a la traditional C++ templates) by re-doing type inference/checking on the inlined code during inlining, and complaining then if the type parameter doesn't have needed methods/operations.

Might be a stop-gap until we have traits.

**Comment by wrwg** [comment]
I don't think we want C++ semantics. At the team discussion last October, there was even a large opposition against duck typing, which is is more harmless than this. 

It also collides with traits. Its either traits or ad-hoc polymorhism (aka C++), which is independent of inline functions. We decided against ad-hoc overloading last October as well. 

Those decisions are reflected in the blog article which documents traits as in Rust and Haskell the way we plan to go.

**Comment by brmataptos** [comment]
I agree that this is hacky and is as bad as duck typing.

We should avoid it and wait for traits.

**Comment by brmataptos** [comment]
We'll wait for traits.
