### ISSUE TITLE
[Bug][Compiler-v2] EXECUTION_LIMIT_REACHED when executing some on-chain txns

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#12855]
# 🐛 Bug

When executing some on-chain txns with gas metering using the comparison testing tool, the code generated by V2 will lead to the `EXECUTION_LIMIT_REACHED` error. Need to investigate more on the root cause.

**Comment by wrwg** [comment]
May be fixed by planned optimizations

**Comment by wrwg** [comment]
Rechecked and resolved by comparison testing @rahxephon89
