### ISSUE TITLE
[Bug][move-compiler-v2] Disassembler output combines address and module name in call

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12935]
# 🐛 Bug

See https://github.com/aptos-labs/aptos-core/blob/851f9ee81b9b2dcc6be69d1a8a81a005f9415b0b/third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp:
```
90:        	4: Call 1vector::reverse<u64>(&mut vector<u64>)
```
it seems that address `1` and module name `vector` are being merged together here.  This is not good.

Not sure if this is move-compiler-v2 specific or not, but I only see it in move-compiler-v2 test output.

**Comment by fEst1ck** [comment]
At start there is a https://github.com/aptos-labs/aptos-core/blob/851f9ee81b9b2dcc6be69d1a8a81a005f9415b0b/third_party/move/move-compiler-v2/tests/file-format-generator/vector.exp#L5

**Comment by brmataptos** [comment]
Not really a bug, though it is kind of ugly.
