### ISSUE TITLE
[Feature Request][Compiler-v2] use the model generated by V2 for docgen and abigen 

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#12946]
# 🚀 Feature Request

docgen and abigen still rely on the move model generated by V1 even when "--compiler-version=v2" is set. We need to use the V2 generated code when generating docs and abis. 

This issue is also related to #12914.

**Comment by rahxephon89** [comment]
@brmataptos another issue that prevents us from using V2 generated model is that inline function cannot be found using [find_function](https://github.com/aptos-labs/aptos-core/blob/5422dc17a873fa13faa15762cb7a7e22a5372ad5/third_party/move/move-model/src/model.rs#L2789), which leads to the issue that the link to the inline function will not be generated.

**Comment by brmataptos** [comment]
I'm reducing priority, since it's ok to ship with this, as long as it still works.

**Comment by wrwg** [comment]
Inline functions should really not be removed. I already added an experiment for this as the prover also needs them to be kept. You could just set this experiment for docgen and thinks may work.

https://github.com/aptos-labs/aptos-core/blob/66d9efb7d30b7c6916f79b6ef65f0bdcbe9c6acb/third_party/move/move-compiler-v2/src/experiments.rs#L206

**Comment by brmataptos** [comment]
There's an issue to track keeping inline functions: https://github.com/aptos-labs/aptos-core/issues/12041
