### ISSUE TITLE
[Bug] Aptos-core depends on different versions of `rand` crate

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#13031]
Different crates in aptos-core depend on incompatible versions of the rand crate, preventing us to do clean workspace dependencies, as well as loading redundant code. 

The workspace is currently set to outdated version `0.7.3`. Some code requires newer version `0.8.5`, e.g. third_party/move, network/framework, and others.

**Comment by brmataptos** [comment]
@JoshLind might know something about the files.
