### ISSUE TITLE
[Bug] Unable to build SDK

### ISSUE THREAD

**Issue by andy-thomason** [aptos-labs/aptos-core#13151]
# 🐛 Bug

The SDK does not build out of the box.

## To reproduce

Create a new Rust project.

Follow the instructions in:

https://aptos.dev/sdks/rust-sdk/

Run `cargo check`

**Stack trace/error message**
```
error[E0599]: no method named `clone` found for struct `Ed25519PrivateKey` in the current scope
   --> /data/SuperChainNetwork/aptos-core/sdk/src/types.rs:487:38
    |
487 |             private_key: private_key.clone(),
    |                                      ^^^^^ method not found in `Ed25519PrivateKey`
```

## Expected Behavior

`Ed25519PrivateKey` should have a clone method, but it is gated on the feature "cloneable-private-keys"
which is not set by default.

## System information

- Aptos Core Version
```
commit 685ddcd62c2dd9cacba64a4e2c007ddbd03584f7 (HEAD -> devnet, origin/devnet-685ddcd62c2dd9cacba64a4e2c007ddbd03584f7, origin/devnet)
```
- Rust Version
```
rustc 1.75.0 (82e1608df 2023-12-21)
```
- Computer OS
Ubuntu 20.04.4 LTS

I would suggest adding this to the CI build to ensure a smooth first-time experience of Aptos!

**Comment by xiaodu1993** [comment]
Comment restrictions！！！

//#[cfg(any(test, feature = "cloneable-private-keys"))]
impl Clone for Ed25519PrivateKey {
    fn clone(&self) -> Self {
        let serialized: &[u8] = &(self.to_bytes());
        Ed25519PrivateKey::try_from(serialized).unwrap()
    }
}

**Comment by andy-thomason** [comment]
Thanks, @xiaodu1993 This is a valid work-around :smiley:
