### ISSUE TITLE
[Bug] Decompiling code that includes comparisons between a variable and its old value resulted in incorrect logic

### ISSUE THREAD

**Issue by flex-alcove** [aptos-labs/aptos-core#13155]
# 🐛 Bug

Code block like this 
```
    fun calculate(x: u256, y:u256, z:u256): u256 {
        let y_prev = y;
        if (z > 1000) {
            y = y + 1;
        } else {
            y = y - 1;
        };
        if (y > y_prev) {
            return x
        } else {
            return y
        }
    }
```

Decompile code

```
    fun calculate(arg0: u256, arg1: u256, arg2: u256) : u256 {
        if (arg2 > 1000) {
            arg1 = arg1 + 1;
        } else {
            arg1 = arg1 - 1;
        };
        if (arg1 > arg1) {
            return arg0
        };
        arg1
    }
```

## To reproduce

1. publish the code to testnet with `included-artifacts=none`
2. download bytecode from testnet
3. decompile source from bytecode

## Expected Behavior

`y` should compare with its old value `y_prev` not itself

**Comment by rahxephon89** [comment]
Hi @flex-alcove, thanks for submitting the issue. Would you mind also submitting this to the revela repo: https://github.com/verichains/revela where we keep track all issues related to the decompiler? Thanks!

**Comment by flex-alcove** [comment]
> Hi @flex-alcove, thanks for submitting the issue. Would you mind also submitting this to the revela repo: https://github.com/verichains/revela where we keep track all issues related to the decompiler? Thanks!

Done, https://github.com/verichains/revela/issues/6

**Comment by sausagee** [comment]
Closing this issue, as the bug will be tracked in the revela repo.
