### ISSUE TITLE
invalide_auto_key [Bug]

### ISSUE THREAD

**Issue by hosseinsanjaei** [aptos-labs/aptos-core#13223]
# 🐛 Bug

To report a security issue, please email security@aptoslabs.com.

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- Aptos Core Version
- Rust Version
- Computer OS

**Comment by gregnazario** [comment]
Hi, please provide more information e.g. stack trace, image, etc. and reopen the issue.

**Comment by hosseinsanjaei** [comment]
6 days ago without my permisson hacker send 99 apt from my address to anonymos address
that was their address 0x5dd01200f0fd66f6f5815eccff44a73974b4f5c8a9f2a08c648ec8c24b8eeda9
i think they rotated my auto key and they decreased 99 apt from my account

**Comment by hosseinsanjaei** [comment]
i can not send token with my pontem wallet.and i can not send any thing with  my petra wallet

**Comment by hosseinsanjaei** [comment]
I will send you the details.


‫‪Greg Nazario‬‏ ***@***.***‬‏> در تاریخ سه‌شنبه ۱۴ مه ۲۰۲۴
ساعت ۲:۲۰ نوشت:‬

**Comment by hosseinsanjaei** [comment]
hi
2weeks ago i recieved poison nft in my wallet and unfortountly i open thats.
since then i can not send anytoken with my account and when i want to send
any token my pontem wallet error invalid__auto__key
my address is:
0x7d831c39344997e62c7594ab2fbf3d9fa7208ab6fc8d1dc26aa4bd83b6d64a75

i think i need the new private key

6 days ago without my permisson hacker send 99 apt from my address to
anonymos address
that was their address
0x5dd01200f0fd66f6f5815eccff44a73974b4f5c8a9f2a08c648ec8c24b8eeda9
i think they rotated my auto key and they decreased 99 apt from my account

i can not send token with my pontem wallet.and i can not send any thing
with my petra wallet

i can not take any transaction with my account

‫‪Hossein Sanjaei‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱۵ مه
۲۰۲۴ ساعت ۱۸:۴۱ نوشت:‬

**Comment by hosseinsanjaei** [comment]
can you help me to solved this

‫‪Hossein Sanjaei‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱۵ مه
۲۰۲۴ ساعت ۱۸:۴۳ نوشت:‬
