### ISSUE TITLE
Got error when run as movement example

### ISSUE THREAD

**Issue by AI-Chef** [aptos-labs/aptos-core#13259]
https://github.com/aptos-labs/aptos-core/blob/b159e29605316187135e95d00d26d7cc5ed5fc5e/aptos-move/framework/aptos-framework/sources/keyless_account.move#L122

(base) ➜  hello_blockchain git:(main) movement aptos move test --named-addresses hello_blockchain=default
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Examples
error[E01002]: unexpected token
    ┌─ aptos-core/aptos-move/move-examples/hello_blockchain/../../framework/aptos-framework/sources/keyless_account.move:122:15
    │
122 │         for(i in 0..vector::length(&vk.gamma_abc_g1)) {
    │            -  ^ Expected ')'
    │            │   
    │            To match this '('

**Comment by gregnazario** [comment]
There are two ways around this:
1. put a space after the for e.g. `for (i in 0..`
2. Update to the latest CLI, newer versions fix this bug in the compiler
