### ISSUE TITLE
[Feature Request] Add `--assume-yes` to the `aptos update` to work with IDEs

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#13265]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

Right now `aptos update aptos` feature is not very useful for IDEs. It only supports interactive `[Y/n]` mode of working with the `update aptos`. 

## Pitch

**Describe the solution you'd like**

I would like to have `--assume-yes` to select `Y` automatically, like it's done for other commands (ie. `aptos move publish`). 

**Describe alternatives you've considered**

There's probably a way to imitate interactive mode of working with the shell with stdin handling, but it's costly to implement compared to the proposed CLI flag. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Maybe later.

**Comment by gregnazario** [comment]
@banool this one I think needs a change to your self update to take an override on the y/n prompt
