### ISSUE TITLE
[Feature Request] IP binding option when running local testnet

### ISSUE THREAD

**Issue by CRBl69** [aptos-labs/aptos-core#13277]
# 🚀 Feature Request

Add an option to choose which IP to bind to when starting a local testnet

## Motivation

For testing, we are running the Aptos local testnet using `aptos node run-local-testnet --force-restart --assume-yes --with-indexer-api`.

We have a docker container running a processor.

We wish the processor to have access to the Indexer gRPC node stream endpoint (127.0.0.1:50051).

Unfortunately, since we cannot choose the IP that is used, we cannot.

Example:

```
# Run on host
netcat -l 127.0.0.1 -p 50051

# Run inside the docker container
netcat host.docker.internal -p 50051
netcat: connect to host.docker.internal (172.17.0.1) port 50051 (tcp) failed: Connection refused

# VS

# Run on host
netcat -l 0.0.0.0 -p 50051

# Run inside the docker container
netcat host.docker.internal -p 50051
Connection to host.docker.internal (172.17.0.1) 50052 port [tcp/*] succeeded!
```

Since the Aptos CLI directly binds to 127.0.0.1, we are in the first scenario, and cannot reach the node from inside the docker container.

There are already similar options like `--indexer-api-port <PORT>` to choose a port. This feature request requests a similar option like `--indexer-api-ip <IP>` or a global `--bind-ip <IP>`.

## Additional context

Note: if you want to reproduce the example and are running on Linux, `host.docker.internal` is not present by default, and you have to start your container with `--add-host host.docker.internal:host-gateway` or have

```
extra_hosts:
    - "host.docker.internal:host-gateway"
```

in your compose file.

**Comment by CRBl69** [comment]
While starting work on a PR, I noticed something. It seems that this feature is actually present, but hidden. You can see in the code snippet below:

```rust
/// By default all services running on the host system will be bound to 127.0.0.1,
/// unless you're running the CLI inside a container, in which case it will run
/// them on 0.0.0.0. You can use this flag to override this behavior in both cases.
#[clap(long, hide = true)]
bind_to: Option<Ipv4Addr>,
```

Is there any reason for that ?

This is exactly the feature I was requesting. I'll close the issue, since it's already implemented.

**Comment by banool** [comment]
Oh yeah whoops I do remember that. I hid it because most users don't need it and it might confuse them.
