### ISSUE TITLE
[Bug]aptos-transactional-test-harness doesn't run extended_checks when compiling examples

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#13297]
# 🐛 Bug

My first attempt to add a simple test that seems to violate a check in extended_checks suggests that extended checks are not being run in aptos-transactional-test-harness compilation, for either V1 or V2:

The following script successfully publishes, although extended checks should reject the &mut signer parameter (at line 215 and 518):
```
//# init --addresses Alice=0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6
//#      --private-keys Alice=56a26140eb233750cd14fb168c3eb4bd0782b099cde626ec8aff7f3cceb6364f

//# publish --private-key Alice
module Alice::M {
    #[view]
    fun view(_:&mut signer,value: u64): u64 { value }
}
```
I added this as aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/bad_parameter.move but it also passes if placed in v2-tests

These tests should be added and made to fail as expected by fixing the test harness code.

**Comment by rahxephon89** [comment]
I think the reason is that aptos-transactional-test-harness relies on the transactional-test framework in `third_party`, which is not aware of extended_check. cc @brmataptos @wrwg

**Comment by brmataptos** [comment]
Yeah, it needs some plumbing.  I'm looking into it now.  I just learned that Rust traits don't seem to allow calling a default implementation from a specialized implementation.  So some renaming is needed to provide an augmented compile function in the aptos case.
