### ISSUE TITLE
[Feature Request][move-compiler-v2] Gather some numbers for public launch

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#13305]
# 🚀 Feature Request

Hopefully we can show that compile time and gas cost are both reduced with Compiler V2 when we are ready to launch.

We need to gather some such numbers to share.

**Comment by vineethk** [comment]
When using the default optimizations for compiler v2 as of now (whatever is undergoing the current comparison testing), comparing number of instructions generated by compiler v1 vs. compiler v2 results in roughly *5% increase* for the projects `aptos-framework`, `aptos-token`, `aptos-token-objects` (and all their dependencies).

There are at least two more reviewed and approved optimizations that need to go through comparison testing before becoming default, these are expect to bring in a few percentage points reduction (over 3? these have not been measured together yet) for compiler v2, bringing it very close to parity.

**Comment by wrwg** [comment]
Closing for this release.
