### ISSUE TITLE
[Bug][Compiler-v2] test mode check does not work when running integration tests in move-vm

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#13345]
# 🐛 Bug

When running the following command `cargo test -p move-vm-integration-tests --lib`, the following error is raised:

```
---- tests::binary_format_version::test_run_script_with_custom_max_binary_format_version stdout ----
thread 'tests::binary_format_version::test_run_script_with_custom_max_binary_format_version' panicked at third_party/move/move-vm/integration-tests/src/tests/binary_format_version.rs:117:10:
called `Result::unwrap()` on an `Err` value: VMError { major_status: CODE_DESERIALIZATION_ERROR, sub_status: None, message: Some("[VM] deserializer for script returned error: PartialVMError { major_status: UNKNOWN_VERSION, sub_status: None, message: Some(\"bytecode version 7 only allowed in test code\"), exec_state: None, indices: [], offsets: [] }"), exec_state: None, location: Script, indices: [], offsets: [] }
```

The reason is that the check whether the code is being run in test mode [here](https://github.com/aptos-labs/aptos-core/blob/ef60a5293f591d9cdc81b6996efbffbeaf4fb178/third_party/move/move-binary-format/src/file_format_common.rs#L542) thinks the code is run in the normal mode even if it is triggered in a unit test.

**Comment by mshakeg** [comment]
I got the `CODE_DESERIALIZATION_ERROR` on attempting to publish a package under a resource account. Adding `--bytecode-version 6` fixed it.

> aptos move create-resource-account-and-publish-package --address-name my_package --seed "my_package_seed" --bytecode-version 6
