### ISSUE TITLE
[Feature Request] e2e-move-tests should examine error messages and and match them to .exp files or something

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#13394]
# 🚀 Feature Request

e2e-move-tests just check for success and failure of a compile/run.  They don't look at what the output is,
so manual testing is needed to see whether errors and warnings are good.

For example,
```
UB=1 cargo test -p e2e-move-tests -- test_entry_attribute
```
shows the error messages in the test output, but doesn't consider whether they are correct.

**Comment by wrwg** [comment]
We made an explicit decision some while ago to not use .exp in e2e-move-tests. Instead, assertions in the program should be used. This was because of the frequent change e.g. of gas cost.
