### ISSUE TITLE
[Language] Module-owned Accounts -- Autonomous Accounts

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#1340]
In Web3, it is common that data on-chain is not owned by an individual or even a shared set of individuals but a dynamic autonomous organizations. In particular, these concepts are beneficial for DAO-owned resources, automated LPs (to create and manage new coins), and other autonomous applications.

Key goals:
1) Resources can be owned by autonomous agents
2) Resources can be published by autonomous agents
3) Modules can be published by autonomous agents
4) Both modules and resources must be publishable after the creation of the autonomous agent

Move provides to frictions to these goals:
1) resource management, specifically `move_to` depends on a signer
2) module management is only accessible via a module payload-based transaction. Modules must be published to existing accounts. It is not possible to create an account and publish to it in a single transaction.

### DAO

Assume several users want to create a DAO together that would be governed completely on-chain. This DAO would like to be able to publish new modules that are managed by the DAO. Some example flows:
1) Distributing coins from one account to another
2) Hosting a new type of coin (this requires `move_to` and may require publishing)
3) Managing NFTs

In the current Move landscape, this DAO would be limited to managing resources that it has been delegated. A DAO is unable to effectively own its account due to the inability of being able to either publish modules under an account or instantiate new resources. This is because ownership of an account requires both a signer and interactions that occur outside the VM (module publishing).

### Coins and Liquidity Providers

A liquidity provider supports taking in two coins, `Coin<A>` and `Coin<B>`, and returning a `Coin<LP<A, B>>`. If the liquidity provider is going to support arbitrary types of `A` and `B`, it must be able to dynamically instantiate new `Coin<LP<A0, B0>>`. Secondarily the requirements for `Coin` enforce that the module defining `LP` live within the account that the resource is instantiated. Hence the current signer model precludes the ability for an autonomous liquidity provider that can publish new `Coin<LP<...>>`. See [here](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/Coin.move#L232-L236).

## Solution Exploration

To enable these "autonomous accounts", it seems that the most viable path forward is to:
1) Create a function that generates a new deterministic account and the capability to generate the signer for this account. This will then allow the capability to be stored within a complex module / resource framework. This will then allow for user initiated but module defined usage of this signer.
2) The ability to publish modules from within a running Move script. Since the signer only exists within the module itself, there is no way to construct a transaction that would allow for such operations. Thus the only meaningful method to publish transactions is within the running of the script.

Some issues still persist.

On the account creation:
1. Ensure that the accounts address can be reasonably deterministic, but it should still be uniformly distributed to prevent any style of MEV, specifically attempting to acquire a specific address should be computationally infeasible.
2. The capability model for the signer should be well thought out so that it cannot be abused.

Note: due to the semantics of `move_to`, a `signer` is required. A capability will not suffice, since `move_to` for a given resource type must be within the same module.

On the module publishing:
1. The only means that the VM exposes to the outside world how to publish a module is via the [Session](https://github.com/move-language/move/blob/c2949bc7967de5b93f0850ce4987fc06c529f9f2/language/move-vm/runtime/src/session.rs#L181).
2. A native function only has access to the [NativeContext]. The NativeContext has DataStore but doesn't expose it: https://github.com/move-language/move/blob/8958b40e97a4f94a588e5365fdb90ec18f00d888/language/move-vm/runtime/src/native_functions.rs#L90)

Options:
1) is to try to add the session to the NativeContext -- maybe that will work. 
2) We'll need to open up the can of worms and expose the data store via the native context and copy a lot of the module validation code that occurs between the session and the data store.
3) We rethink this and add some well known fields in storage that say this module can be upgraded so long as the upgrade is with this byte code and it can happen whenever -- this would also require that module publishing upgrades trigger reconfigurations.

## Eliminating the requirement for adding new modules after creation

If we eliminate the requirement of adding new modules after creation, we can simplify the solution substantially:
* User creates a one off account and stores the signer capability in a place only that account can retrieve.
* User publishes an autonomous module to that account.
* That autonomous module executes an `init`, that does whatever it wants with the signer ability and also rotates the key to the account to 0x0 -- implying it is indeed an autonomous account

**Comment by Manahip** [comment]
Option 2 requires more effort from devs to develop 2 sets of interface. Option 1 allows the old interface that takes &signer to just work. I prefer the first option to reduce contract developer workload.

**Comment by wrwg** [comment]
This was/is an item on the Move design tracker, but has been archived since signer-less publishing can be now done via tables. Is it still an issue?

If this is the case, I would prefer (2) (more below). (1) is strange because a signer is basically "root" and each cap can be derived from it. Getting the signer back from a cap may break the cap model.

(2) is actually the way which had been taken by StarCoin's flavor of Move. If we go (2) we may consider to hide/disallow `move_to` (and `move_from`). I think eventually we may need an extension to the bytecode verifier to encode Aptos specific rules anyway (as Sui does). We would then basically come-up with our own cap-based move_to/move_from. However, unfortunately, because of Move's restricted/broken borrow semantics, we cannot define a `borrow_mut_with_cap` ... Thinking a cap-based permission model through is non trivial.

There is possibly an option 3, using a methodology completely based on modular encapsulation and capabilities. In this world, every access to a resource would be controlled by the public API of a module where caps are used to control who can call what functions. Internally of the module, one just uses `move_to_addr` (no signer restriction).

**Comment by borispovod** [comment]
Hey @davidiw ,

> Provide a native function that returns a signer, e.g., signer_with_cap(cap: SignerCap): &signer

Means, there should be `SignerCap` stored somewhere, e.g. under the resource of another account? If i understand it correctly it seems for me it will little break the entire design of language, as we will have to borrow capabilities from some hardcoded address, etc. 


@wrwg suggested:

> There is possibly an option 3, using a methodology completely based on modular encapsulation and capabilities. In this world, every access to a resource would be controlled by the public API of a module where caps are used to control who can call what functions. Internally of the module, one just uses move_to_addr (no signer restriction).

Sounds interesting, I also thought about something similar, but didn't go deep. 

Another option can be: what if we add a 'module signer' and 'module address'? The resources that can be placed on that signer can be stored into module storage itself, like: '0x1::Module::SomeResource'.
 
That kind of signer would be possible to use only inside module functions. It can solve a lot of headaches in some specific cases, like registration of new coins, storing of some configurations, etc. Just a concept.
