### ISSUE TITLE
Add integer types

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#1341]
There are many unsigned integer types that don't exist (u16, u32, u256). Add them to upstream move.

**Comment by optke3** [comment]
Seconded. These would be really valuable to have. Some cross-chain messaging and interoperability protocols have standardized message fields that are u16 or u32. Not having these would break the standardization.

**Comment by wrwg** [comment]
This is a duplicate of an issue in the Move repo, and support has been added over there recently, which is currently in the process of being adopted. Closing here.
