### ISSUE TITLE
[Language] Reconcile error model

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#1346]
Currently, we use a methodology for error reporting in Move which was developed for Diem: we have a canonical error category (alread_published etc.) and an error reason. The error reason is locally defined for each module.

First, the canonical error status is what we strongly want to preserve. There should be only a fixed, small set of error codes which are passed in an actionable way to an application. Arbitrary user defined error codes are a bad thing because they lead to chaotic code on application side which does not work over different layers of abstractions. This has been encoded e.g. in [Google's canonical error codes](https://cloud.google.com/apis/design/errors) but also in HTTP error codes. In fact each of our current error statuses should allow a unique mapping to an HTTP error code (we can use the mapping which is e.g. suggested for the Google codes) which is used by the REST APIs.

Second, however, the way how we define error reasons is awkward and hard to understand for a user. Notice that error reasons, in the methodology, are never intended to be actionable by an app (the error status is), but only meant as additional info for a dev to debug a an error. But this is difficult today because the reason codes are local to a module. One needs to use an extra tool to track down a reason code to the module where it is defined and find the location where an error is raised. All this current reason business is mostly there to work around a problem of the VM, namely that it cannot give as the source position of an abort.

- We should enable source position reporting, possibly full stack traces on abort. This can be achieved by the new metadata entry in the file format which allows us to store the necessary source position information.
- We may want to retire the use of reasons, or replace them simply by strings (once we have those implemented)
- Alternatively, if we don't have strings available, we should make reasons globally unique

**Comment by areshand** [comment]
new to this. would this improvement supports throwing customized error message?
