### ISSUE TITLE
[Bug] [v1.13.1] Aptos Fullnode's synchronization consistently fails.

### ISSUE THREAD

**Issue by jinseon2416** [aptos-labs/aptos-core#13609]
# 🐛 Bug

We are continuously collecting block information through the rpc API while synchronizing the archive fullnode.
After recently upgrading to the latest aptos version v1.13.1, synchronization stops frequently.
I downgraded to 1.12.1 and the same symptom does not occur.
Also, If you simply synchronize without querying the rpc API, the same symptom does not appear.

If synchronization is in progress and then stopped, only the following log is output, and synchronization-related logs are not output.
If I run the aptos process again, the sync will proceed normally again and then stop again.

**Stack trace/error message**
```
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:10.038956Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:10.038975Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:15.038523Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:15.038541Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:19.078768Z [data-client-0] INFO state-sync/aptos-data-client/src/poller.rs:444 {"event":"aggregate_summary","message":"Global data summary: AdvertisedData { Highest epoch ending ledger info, epoch: Some(7285). Highest synced ledger info, epoch: Some(7286), version: Some(970225494). Lowest transaction version: Some(820220494), Lowest transaction output version: Some(820220494), Lowest states version: Some(890225440) }, OptimalChunkSizes { epoch_chunk_size: 200, state_chunk_size: 4000, transaction_chunk_size: 2000, transaction_output_chunk_size: 1000 }","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:20.039162Z [data-client-30] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:20.039180Z [data-client-30] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:25.038909Z [data-client-31] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:25.038928Z [data-client-31] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:25.791820Z [peer-mon-27] WARN peer-monitoring-service/client/src/peer_states/network_info.rs:145 {"event":"invalid_response","message":"Peer returned invalid depth from validators: 1","name":"network_info_request","peer":"Public:568fdb6a"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:29.073928Z [data-client-0] INFO state-sync/aptos-data-client/src/poller.rs:444 {"event":"aggregate_summary","message":"Global data summary: AdvertisedData { Highest epoch ending ledger info, epoch: Some(7285). Highest synced ledger info, epoch: Some(7286), version: Some(970225760). Lowest transaction version: Some(820221010), Lowest transaction output version: Some(820221010), Lowest states version: Some(890225707) }, OptimalChunkSizes { epoch_chunk_size: 200, state_chunk_size: 4000, transaction_chunk_size: 2000, transaction_output_chunk_size: 1000 }","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:30.038314Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:30.038334Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:35.038927Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:35.038945Z [data-client-0] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:36.573597Z [telemetry-27] WARN /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-retry-0.2.3/src/middleware.rs {"message":"Retry attempt #0. Sleeping 264.604842ms before the next attempt"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:37.037511Z [telemetry-0] WARN /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-retry-0.2.3/src/middleware.rs {"message":"Retry attempt #1. Sleeping 8.210725312s before the next attempt"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:39.311962Z [data-client-31] INFO state-sync/aptos-data-client/src/poller.rs:444 {"event":"aggregate_summary","message":"Global data summary: AdvertisedData { Highest epoch ending ledger info, epoch: Some(7285). Highest synced ledger info, epoch: Some(7286), version: Some(970226065). Lowest transaction version: Some(820221010), Lowest transaction output version: Some(820221010), Lowest states version: Some(890225967) }, OptimalChunkSizes { epoch_chunk_size: 200, state_chunk_size: 4000, transaction_chunk_size: 2000, transaction_output_chunk_size: 1000 }","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:40.039141Z [data-client-30] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
Jun 07 19:41:45 dp-aptos-mainnet aptos-fullnode[144386]: 2024-06-07T19:41:40.039159Z [data-client-30] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}

```

## Expected Behavior

It is necessary to determine what differences between versions 1.12.1 and 1.13.1 are causing the synchronization stoppage.

## System information

**Please complete the following information:**
- Aptos Core Version - v1.13.1
- Rust Version - cargo 1.78.0 (54d8815d0 2024-03-26)
- Computer OS - ubuntu 20.04

## Additional context

I encountered an issue after upgrading to a new mainnet release.
The same symptom does not appear in version 1.12.1.

**Comment by p1xel32** [comment]
May I ask you is it was bootstrapped from snapshot?

**Comment by JoshLind** [comment]
Hmm... this is unusual. We haven't seen any other reports of this.

Can you please: (i) stop the fullnode; (ii) restart the fullnode and collect logs; (iii) let the node run for a few minutes (e.g., 5 minutes); and (iv) upload the log file of the node for those 5 minutes. This will hopefully show us the error the node is running into.

**Comment by m229abd** [comment]
Hi there. Here to report another instance of this. I have been in contact with @p1xel32 in discord. I tried Fast sync, then went on to try bootstrapping. Contacted Polkachu team and they can't update the snapshots for bootstrapping neither. BwareLabs snapshot is also lagging behind schedule. I've attached the full log since initial pulling of the docker image.
[log.txt](https://github.com/user-attachments/files/15809018/log.txt)

**Comment by p1xel32** [comment]
@m229abd We have identified several users experiencing similar issues. For those who re-synced using the default configuration, the problem was resolved. If you're encountering character and connectivity issues, especially after bootstrapping your nodes, re-syncing with the default configuration might be beneficial.

Default config you could find below:
https://github.com/aptos-labs/aptos-core/blob/main/config/src/config/test_data/public_full_node.yaml

@JoshLind I believe the original issue is here:
https://github.com/aptos-labs/aptos-core/issues/13553

**Comment by jinseon2416** [comment]
We performed bootstrapping using aptos foundation backup storage snapshots.
What we need now is an archive mainnet.
When running with the default configuration, the entire transaction cannot be saved and executed, so the state sync setting is used as follows.
Are there any other alternatives?
`state_sync:
    state_sync_driver:
        bootstrapping_mode: ExecuteTransactionsFromGenesis
        continuous_syncing_mode: ExecuteTransactions
`

**Comment by jinseon2416** [comment]
We share logs that occur when data synchronization stops. 
It seems to occur when DataStreamNotificationTimeout":"5s" is exceeded. Are there any recommendations?

`2024-06-21T02:51:09.284649Z [sync-driver-1] WARN state-sync/state-sync-driver/src/continuous_syncer.rs:195 Resetting the currently active data stream due to too many timeouts!
2024-06-21T02:51:09.284684Z [sync-driver-1] INFO state-sync/state-sync-driver/src/utils.rs:247 {"message":"Terminating the data stream with ID: 1, notification and feedback: None","name":"driver"}
2024-06-21T02:51:09.284718Z [sync-driver-1] WARN state-sync/state-sync-driver/src/driver.rs:631 {"error":{"CriticalDataStreamTimeout":"12"},"message":"Error found when driving progress of the continuous syncer!","name":"driver"}
2024-06-21T02:51:09.284782Z [stream-serv-9] INFO state-sync/data-streaming-service/src/streaming_service.rs:222 {"event":"success","message":"Terminating the data stream with ID: 1. Notification and feedback: None","name":"handle_terminate_request","stream_id":1}
2024-06-21T02:51:09.291146Z [stream-serv-9] INFO state-sync/data-streaming-service/src/streaming_service.rs:297 {"event":"success","message":"Stream created for request: StreamRequestMessage { stream_request: ContinuouslyStreamTransactionsOrOutputs(ContinuouslyStreamTransactionsOrOutputsRequest { known_version: 992582227, known_epoch: 7451, include_events: false, target: None }), response_sender: Sender { complete: false } }","name":"handle_stream_request","stream_id":2}
2024-06-21T02:51:09.336301Z [stream-serv-1] INFO state-sync/data-streaming-service/src/streaming_service.rs:371 {"event":"success","message":"Data stream initialized.","name":"initialize_stream","stream_id":2}
2024-06-21T02:51:14.036718Z [data-client-9] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
2024-06-21T02:51:14.036834Z [data-client-9] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
2024-06-21T02:51:14.137172Z [data-client-9] INFO state-sync/aptos-data-client/src/poller.rs:444 {"event":"aggregate_summary","message":"Global data summary: AdvertisedData { Highest epoch ending ledger info, epoch: Some(7450). Highest synced ledger info, epoch: Some(7451), version: Some(992584475). Lowest transaction version: Some(842581461), Lowest transaction output version: Some(842581461), Lowest states version: Some(912584460) }, OptimalChunkSizes { epoch_chunk_size: 200, state_chunk_size: 4000, transaction_chunk_size: 2000, transaction_output_chunk_size: 1000 }","name":"peer_states"}
2024-06-21T02:51:14.292451Z [sync-driver-1] WARN state-sync/state-sync-driver/src/driver.rs:631 {"error":{"DataStreamNotificationTimeout":"5s"},"message":"Error found when driving progress of the continuous syncer!","name":"driver"}
2024-06-21T02:51:19.034046Z [data-client-14] INFO state-sync/aptos-data-client/src/client.rs:1190 {"event":"priority_and_regular_peers","message":"Number of priority peers: 6. Number of regular peers: 0","name":"peer_states"}
2024-06-21T02:51:19.034076Z [data-client-14] INFO state-sync/aptos-data-client/src/client.rs:1223 {"event":"priority_peer_categories","message":"Number of connected peers by priority: {HighPriority: 6}","name":"peer_states"}
2024-06-21T02:51:19.293671Z [sync-driver-1] WARN state-sync/state-sync-driver/src/driver.rs:631 {"error":{"DataStreamNotificationTimeout":"5s"},"message":"Error found when driving progress of the continuous syncer!","name":"driver"}`

**Comment by jinseon2416** [comment]
The same synchronization interruption is occurring in the latest version v1.15.2.

`2024-06-28T04:31:30.602374Z [sync-driver-14] WARN state-sync/state-sync-driver/src/bootstrapper.rs:593 Resetting the currently active data stream due to too many timeouts!`

`2024-06-28T04:31:30.602398Z [sync-driver-14] INFO state-sync/state-sync-driver/src/utils.rs:247 {"message":"Terminating the data stream with ID: 24, notification and feedback: None","name":"driver"}`

`2024-06-28T04:31:30.602440Z [sync-driver-14] WARN state-sync/state-sync-driver/src/driver.rs:657 {"error":{"CriticalDataStreamTimeout":"12"},"message":"Error found when checking the bootstrapper progress!","name":"driver"}
`

**Comment by JoshLind** [comment]
@jinseon2416
1. I took a look through all the changes between v1.12 and v1.13, and there's nothing that should affect state sync in the way you are seeing. The same is true for changes between v1.12 and v1.15. Likewise, this is still the only report of this type of issue.
2. Are the logs provided by m229abd ([above](https://github.com/aptos-labs/aptos-core/issues/13609#issuecomment-2163615093)), the same logs as your node? Or are those logs unrelated? Sorry, hard to tell who's within the same org :)
3. If you need an archival mainnet node (and you're trying to sync from genesis, you should use intelligent syncing: https://aptos.dev/en/network/nodes/configure/state-sync#intelligent-syncing). Execution-only can be slow.
4. Looking at the logs you have provided above, it seems to me that your node is experiencing a large amount of timeouts. My first recommendation is to inspect your network, e.g., bandwidth, latency, load balancers, HAProxy, etc. You really shouldn't be timing out so much fetching the data.
5. What does your node config look like? Are you hard coding seed peers? If so, are those peers unreliable/flaky?
6. The logs above are still insufficient to really diagnose the problem. I'd recommend following the steps I mentioned [above](https://github.com/aptos-labs/aptos-core/issues/13609#issuecomment-2161963138) to produce a full log trace. That is, assuming the logs provided by m229abd are unrelated.

**Comment by JoshLind** [comment]
@p1xel32
1. Thanks for pointing to your previous issue (https://github.com/aptos-labs/aptos-core/issues/13553). I'll update the node docs to point out that community snapshots don't provide indexer support. Because they are community snapshots, they are out of our control.
2. But, my feeling is that the issue faced by @jinseon2416 is unrelated to this. If they had bootstrapped from a community snapshot without indexer support, I'd expect the node not to sync at all? As opposed to running for a while and then timing out.

**Comment by JoshLind** [comment]
@m229abd,
1. Looking at the logs, I see these errors:
```
Errors: [InvalidResponse(\"Unexpected error encountered: invalid value: integer `5`, expected variant index 0 <= i < 4\"), InvalidResponse(\"Unexpected error encountered: invalid value: integer `5`, expected variant index 0 <= i < 4\")],
```
This tells me that your node is running an incompatible version with the rest of the network. When it makes calls to receive new data (after fast syncing), it is unable to parse the responses because of the message version incompatibility. Can you please update to the last mainnet version? e.g., currently [v1.15.2](https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.15.2)

**Comment by m229abd** [comment]
Sorry for keeping you uninformed, but we did update shortly after v1.15.2
came out, and it did fix the synchronization.
Thank you for following up on the issue.

**Comment by reinisb123** [comment]
I think I have the same issue as @jinseon2416. 
It only happens when I do somewhat a lot of RPC calls on it.
