### ISSUE TITLE
[Bug] High gas consumption observed when creating transactions with multisig_account V2

### ISSUE THREAD

**Issue by WGB5445** [aptos-labs/aptos-core#13615]
# 🐛 Bug > High gas consumption observed when creating transactions with Multi-signature Account V2.

When executing `create_transaction_with_hash`, I observed that the majority of gas consumption during this transaction process is concentrated in the table's add item operation. 

After reviewing the source code, I believe there is significant room for improvement, such as utilizing `smart_table` or `vector` (with a limit on the number of pending transactions less than 20) to address this issue.

### source code
```
inline fun add_transaction(
        creator: address,
        multisig_account: address,
        transaction: MultisigTransaction
    ) {
        ....
        simple_map::add(&mut transaction.votes, creator, true);

        let sequence_number = multisig_account_resource.next_sequence_number;
        multisig_account_resource.next_sequence_number = sequence_number + 1;
        table::add(&mut multisig_account_resource.transactions, sequence_number, transaction);
        ...
}
```

Therefore, I attempted to deploy similar code on the testnet and profiled different consumption patterns.

| Data Structure   | Gas Consumption | Transaction Link |  Profile Link                                                 |
|------------------|-----------------|-----------------------------------------------|----------------|
| Table            | 467 Gas Units   | [Link](https://explorer.aptoslabs.com/txn/1237166108?network=testnet)   |  [txn-02011f4d-0x4322-multisig_account_table-create_transaction_with_hash.zip](https://github.com/user-attachments/files/15748796/txn-02011f4d-0x4322-multisig_account_table-create_transaction_with_hash.zip)  |
| Smart Table      | 58 Gas Units    | [Link](https://explorer.aptoslabs.com/txn/0xf68d43d044e4491ae9e185cbe3d95de1ae3c65d896f2ea8542275b8d21db58ef?network=testnet) | [txn-e7eb8f45-0x4322-multisig_account_smart_table-create_transaction_with_hash.zip](https://github.com/user-attachments/files/15748801/txn-e7eb8f45-0x4322-multisig_account_smart_table-create_transaction_with_hash.zip) | 
| Vector           | 51 Gas Units    | [Link](https://explorer.aptoslabs.com/txn/0xd201d2648e500986badc264a0d51643676cbaf98e719af95ef9ac2de6332de7b?network=testnet) | [txn-b1c93318-0x4322-multisig_account_vector-create_transaction_with_hash.zip](https://github.com/user-attachments/files/15748799/txn-b1c93318-0x4322-multisig_account_vector-create_transaction_with_hash.zip) |

**Comment by movekevin** [comment]
Multisig account was also created prior to SmartTable/SmartVector existing. It might not be easy to change to those data structures due to backward compat problem. We'd need to add a new struct for the SmartTable and then switch between the 2 for existing multisigs
