### ISSUE TITLE
[Language] Sorting in Move

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#1362]
For ValidatorSets we need sorting in Move:
BlockMetadataTransaction stores the validators in an ordered set: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-vm/src/aptos_vm.rs#L623
Derived from https://github.com/aptos-labs/aptos-core/blob/269ed18b895cb82afcf405288986adb59e8d5ac9/consensus/consensus-types/src/block.rs#L320
Derived from https://github.com/aptos-labs/aptos-core/blob/main/types/src/validator_verifier.rs#L75
Framework code: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/configs/Stake.move#L123

So some options:
* Convert the validators into BTreeMaps and fix all the data sets thereafter
* Add a sorting function for a vector that assumes that bcs serializes the contents of each entry and sorts it
* Wait for something like a macro, closure, lambda that lets sorting on a specific prefix
* Interpret the Move types and sort on them one at a time

I think the two best options to move fast are BTreeMap and sorting on BCS. 

For the BTreeMap:
* Resurrect my old "Table" code
* Update insert, remove, and contains function to use a sorted ordering of the keys -- this may require BCS serialization and comparison in Move
* Rewrite Staking to use BTreeMaps
* Rewrite aptos-types to use the appropriate BTreeMaps validatorset

For the sorting:
* Implement a move or native vector sort using bcs entries
* call that sort right here: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/configs/Stake.move#L459

**Comment by msmouse** [comment]
(links are not pinned to a specific commit)

**Comment by davidiw** [comment]
After hacking a while for a while, I realized that the BTreeMap idea while seemingly elegant is a huge pain:
* Implementing BTreeMap in Move is insane
* Using a SortedMap (built on top of my earlier Table) works, but you pay O(N) insertion and deletion time, which might add a lot of overhead if we support really large subcommittees
* There would still be a lot of work to plumb the rest of the code

Sorting is another mess:
* Using a native sorting adds a lot of complexity
* Implementing quick sort or some other Log N sorting in move sounds fun, but is fraught with potential issues
* Using stupid bubble sort is super easy and while we might pay O(N^2), which I guess is the same as using my Map above, it can be adjusted if this becomes a performance bottleneck
