### ISSUE TITLE
[Feature Request] Improve Simulation for Sponsored Transactions

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#13686]
# 🚀 Feature Request

Sponsored transactions, and any transaction where a publickey is not known, should be able to simulate.  In the event of a 0x0 fee payer, there should be no gas simulation issues.

## Motivation

Sponsored transactions can't be easily simulated without knowing the public key and address of the sponsor for a transaction.  This is messy, since if you may not know the fee payer's address and public key if it's set to `0x0` to allow for any fee payer.

## Pitch

**Describe the solution you'd like**
Simulation ignoring public keys, and if a fee payer is set, ignoring gas fees.

**Describe alternatives you've considered**
^

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
n/a

**Comment by mizu-flex** [comment]
Hi, guys, how is this matter going? Currently, our multisig v2 + fee payer transactions cannot be simulated at all. A lot of gas was wasted due to the submission of incorrect payloads.

**Comment by junkil-park** [comment]
> Hi, guys, how is this matter going? Currently, our multisig v2 + fee payer transactions cannot be simulated at all. A lot of gas was wasted due to the submission of incorrect payloads.

@alex4506 , [the AIP-92](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-92.md) resolves this issue, and it's going to be released with v1.19.
