### ISSUE TITLE
[Bug][compiler-v2] compilation result is different when there is a public friend entry inline function

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#13693]
# 🐛 Bug

When compiling the following code using V1 and V2 respectively, the result is different:

```
module 0x123::a{
    public(friend) entry inline fun a(){}
}
```

![image (1)](https://github.com/aptos-labs/aptos-core/assets/10296575/d673f15e-d859-43f2-9585-6cab37f75bf1)

**Comment by brmataptos** [comment]
So which one is the right answer?

**Comment by rahxephon89** [comment]
> So which one is the right answer?

panic is not a good behavior but I am not sure whether the compiler should generate an error or not for this code. cc @wrwg
