### ISSUE TITLE
[Bug] Subtraction Underflow in Clock Skew Tolerance error handling

### ISSUE THREAD

**Issue by 0xPrimata** [aptos-labs/aptos-core#13704]
# 🐛 Bug

On line 1657 -> 24, `aptos/src/common/types.rs` there is a risk of a subtraction underflow. If timestamp is less than the tolerance, main thread panics. Despite it being very unlikely in production, it might be a common issue for testing environments.

## To reproduce

Self-evident

**Stack trace/error message**
```
thread | 'main'
panicked at crates/aptos/src/common/types.rs: 1639:24:
attempt to subtract with overflow
```

## Expected Behavior

Error is handled and emits a proper error indicating that the current environment timestamp is less than the ACCEPTED_CLOCK_SKEW_US.

## System information

**Please complete the following information:**
- Aptos Core Version 3.4.1
- Rust Version 1.78.0
- Computer OS MacOS

**Comment by l-monninger** [comment]
Testing the CLI against reassembled bits of `aptos-core` is where this is most likely to come up. The method returns a `Result`, so providing a typed `Err` reflecting this possibility would seem reasonable. Otherwise, a more descriptive panic is suitable.
