### ISSUE TITLE
[Bug] UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION error in Multisig V2

### ISSUE THREAD

**Issue by mizu-flex** [aptos-labs/aptos-core#13728]
# 🐛 Bug

Got `UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION` when executed multisig v2 transaction, and all following transactions in this account got move abort errors.

PS: This account is a new created multisig v2 account seconds ago, and all transactions using the same fee payer.

See https://explorer.aptoslabs.com/txn/984867315?network=mainnet

**Comment by sausagee** [comment]
This was resolved in offline DM. cc @lightmark
