### ISSUE TITLE
[Feature Request] run third_party/move/scripts/move_pr.sh -ti2 for any compiler change

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#13750]
# 🚀 Feature Request

Add `third_party/move/scripts/move_pr.sh -ti2` to the script run after any compiler change.

## Motivation

This script catches more regressions, including those in Move Compiler v2.

We already see a case of this.

**Comment by wrwg** [comment]
We need to figure out what of those tests will be run in CI, that is the only reliable way to enforce things. Voluntary running is volatile and will lead to breakages again.

**Comment by brmataptos** [comment]
Probably running `move_pr.sh -2` as part of CI is sufficient.  Other tests get run through other means, I think.
