### ISSUE TITLE
crash when start[Bug], ./aptos node run-local-testnet --with-indexer-api

### ISSUE THREAD

**Issue by jiaoyongqing** [aptos-labs/aptos-core#13920]
Setup is complete, you can now use the localnet!
details = """
panicked at /home/yongqingjiao/.cargo/git/checkouts/aptos-indexer-processors-9c380407f339414a/93d12d9/rust/processor/src/grpc_stream.rs:654:17:
[Parser] Reconnected more than 5 times. Will not retry."""
backtrace = """
   0:     0x564047584733 - backtrace::backtrace::libunwind::trace::h35cda9fe78230a55
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h10442232b9fe0884
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::hd76511621bc56c52
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:53:14
                           backtrace::capture::Backtrace::create::h3e0a78ba2a30eeb2
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::hfd3d178a4eeddf9d
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:140:22
   1:     0x5640423bd29f - aptos_crash_handler::handle_panic::h416922b9e92f8dd7
                               at /home/yongqingjiao/code/github/aptos-core/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::h3fe61e038aacdd3a
                               at /home/yongqingjiao/code/github/aptos-core/crates/crash-handler/src/lib.rs:29:9
   2:     0x5640478af120 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h022ca2c0d8c21c9e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
                           std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   3:     0x5640478aee62 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   4:     0x5640478ad746 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   5:     0x5640478aeb94 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   6:     0x5640478df455 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   7:     0x564042dd3cd7 - processor::grpc_stream::create_fetcher_loop::{{closure}}::ha52c56d1710609e9
                               at /home/yongqingjiao/.cargo/git/checkouts/aptos-indexer-processors-9c380407f339414a/93d12d9/rust/processor/src/grpc_stream.rs:654:17
   8:     0x564042e4ba31 - processor::worker::Worker::run::{{closure}}::{{closure}}::h3d627ec1778d6a40
                               at /home/yongqingjiao/.cargo/git/checkouts/aptos-indexer-processors-9c380407f339414a/93d12d9/rust/processor/src/worker.rs:231:14
   9:     0x564042dbb19b - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hc69c1d9438b24f2c
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:328:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h7c00d51607e8635f
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/loom/std/unsafe_cell.rs:16:9
                           tokio::runtime::task::core::Core<T,S>::poll::h0936274f52656660
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:317:30
  10:     0x564042d3def9 - tokio::runtime::task::harness::poll_future::{{closure}}::h07539bdd85046a1c
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:485:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he72acc25f49f9dba
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
                           std::panicking::try::do_call::h40896e7f263bafd1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
                           std::panicking::try::h7f8fd61767547348
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
                           std::panic::catch_unwind::hbd50449d90744d77
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
                           tokio::runtime::task::harness::poll_future::ha5fa5ea4de09fe96
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:473:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::he13feae92aea74b3
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:208:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::h8a30ce150aa50c4c
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:153:15
  11:     0x5640474a8ec9 - tokio::runtime::task::raw::RawTask::poll::h043659504dba16ea
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:201:18
                           tokio::runtime::task::LocalNotified<S>::run::hb00aa7641b77ab99
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/mod.rs:416:9
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h7dba065b95688aeb
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:576:18
                           tokio::runtime::coop::with_budget::h300c490fd8b8293e
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5
                           tokio::runtime::coop::budget::h48af12dc5b14ba13
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h968387b55fbf5853
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:575:9
  12:     0x5640474a7d68 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hae5d11468290fae5
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:526:24
  13:     0x56404748fa80 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h71a02ec659399f53
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:491:21
                           tokio::runtime::context::scoped::Scoped<T>::set::h8177644d65dbd099
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/scoped.rs:40:9
                           tokio::runtime::context::set_scheduler::{{closure}}::h88b7ad88ad98ce1f
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context.rs:176:26
                           std::thread::local::LocalKey<T>::try_with::h3a21a62fd0833ae7
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:284:16
                           std::thread::local::LocalKey<T>::with::hb5f6d9ea2743f40b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:260:9
                           tokio::runtime::context::set_scheduler::he21b3fad93590b08
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context.rs:176:17
  14:     0x5640474a6f5c - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h1c9e669cbdc717a4
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:486:9
                           tokio::runtime::context::runtime::enter_runtime::h16db4a073e4d148b
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16
                           tokio::runtime::scheduler::multi_thread::worker::run::had0314dbd9f73e76
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:478:5
  15:     0x56404749c69e - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::hded93e10c0010110
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:447:45
                           <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h5aa9321cd88d371a
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/task.rs:42:21
                           tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h027e3837920946b3
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:328:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h03be720da5900bc7
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/loom/std/unsafe_cell.rs:16:9
                           tokio::runtime::task::core::Core<T,S>::poll::hc2de58c336f2cc08
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:317:30
  16:     0x56404748600a - tokio::runtime::task::harness::poll_future::{{closure}}::h3837d91ea0501b9b
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:485:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd6e2d400c712d13e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
                           std::panicking::try::do_call::h5934a5886d1fbd15
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
                           std::panicking::try::h6adc994f223d3557
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
                           std::panic::catch_unwind::h3706e61b758c3739
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
                           tokio::runtime::task::harness::poll_future::h5e637baa9b8b494c
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:473:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::he93b7bc43b8fe1e6
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:208:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::hf4580246c6d24f18
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:153:15
                           tokio::runtime::task::raw::poll::h48ffb6a9465e4a6d
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:271:5
  17:     0x56404748c1e2 - tokio::runtime::task::raw::RawTask::poll::h043659504dba16ea
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:201:18
                           tokio::runtime::task::UnownedTask<S>::run::h12b1dd8cf6430235
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/mod.rs:453:9
                           tokio::runtime::blocking::pool::Task::run::h6e7f53630e319848
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:159:9
                           tokio::runtime::blocking::pool::Inner::run::h2541bfdb2d11b190
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:513:17
  18:     0x5640474b6ab1 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hf5840df039bd82d7
                               at /home/yongqingjiao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:471:13
                           std::sys_common::backtrace::__rust_begin_short_backtrace::h38a2634bf90f6af8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  19:     0x56404749920b - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h6adc690a6e6f11ba
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:528:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha52601d1bf35938d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
                           std::panicking::try::do_call::h744ab531122b7693
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
                           std::panicking::try::hf2e19d2e6cf769f4
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
                           std::panic::catch_unwind::h81a7a394b1bd3483
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::h9999fe2c66da0406
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:527:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::h6949f6eef77f707f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  20:     0x5640478b63c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h19b9e642d37e7272
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h97265befc434d3ae
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
                           std::sys::pal::unix::thread::Thread::new::thread_start::h420dad5cf01a9f35
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/thread.rs:108:17
  21:     0x7feb34ad3609 - start_thread
                               at /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8
  22:     0x7feb348a1353 - clone
                               at /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  23:                0x0 - <unknown>
"""

[Logging] Unable to flush recv: timed out waiting on channel
Timed out flushing telemetry: timed out waiting on channel

**Comment by larry-aptos** [comment]
does `--force-restart` help? this will wipe out your local data and rebuild from genesis.

**Comment by tl5675387** [comment]
I also got the same error when running testnet in localhost with docker:

```
Setup is complete, you can now use the localnet!
details = """
panicked at /usr/local/cargo/git/checkouts/aptos-indexer-processors-4a0c233e54c07e0d/51a3490/rust/processor/src/grpc_stream.rs:654:17:
[Parser] Reconnected more than 5 times. Will not retry."""
backtrace = """
   0:     0x555a465fd1cd - <unknown>
   1:     0x555a465fd17c - <unknown>
   2:     0x555a46601f9c - <unknown>
   3:     0x555a46601f1f - <unknown>
   4:     0x555a458c1615 - <unknown>
   5:     0x555a47a13074 - <unknown>
   6:     0x555a47a12de2 - <unknown>
   7:     0x555a47a11706 - <unknown>
   8:     0x555a47a12b14 - <unknown>
   9:     0x555a46732535 - <unknown>
  10:     0x555a47621792 - <unknown>
  11:     0x555a47696ec2 - <unknown>
  12:     0x555a4745e289 - <unknown>
  13:     0x555a473cfb18 - <unknown>
  14:     0x555a4746e23b - <unknown>
  15:     0x555a4747469a - <unknown>
  16:     0x555a47480224 - <unknown>
  17:     0x555a47aec3c6 - <unknown>
  18:     0x555a47ae98dd - <unknown>
  19:     0x555a47ad8515 - <unknown>
  20:     0x555a47aea782 - <unknown>
  21:     0x555a47ae7ce8 - <unknown>
  22:     0x555a47aec289 - <unknown>
  23:     0x555a47af7dc7 - <unknown>
  24:     0x555a47af30ce - <unknown>
  25:     0x555a47ad8fa0 - <unknown>
  26:     0x555a47af5b4a - <unknown>
  27:     0x555a47af4767 - <unknown>
  28:     0x555a47af46da - <unknown>
  29:     0x555a47af678e - <unknown>
  30:     0x555a47ad73fa - <unknown>
  31:     0x555a47ad8ffa - <unknown>
  32:     0x555a47ad97fb - <unknown>
  33:     0x555a47a18da5 - <unknown>
  34:     0x7f015d023ea7 - start_thread
  35:     0x7f015cdf7acf - clone
  36:                0x0 - <unknown>
"""

Timed out flushing telemetry: timed out waiting on channel
```
