### ISSUE TITLE
[Bug][License] use of number-range under GPL v3.0 license

### ISSUE THREAD

**Issue by huitseeker** [aptos-labs/aptos-core#13931]
# 🐛 Bug

Several aptos core crates depend (transitively) on [`number_range`](https://github.com/Atreyagaurav/number_range), which is a GPLv3.0 crate:
```
huitseeker➜~/tmp/aptos-core(main)» cargo tree -i -p number_range --depth 1                                                                                                                                                
number_range v0.3.2
└── aptos-config v0.1.0 (/Users/huitseeker/tmp/aptos-core/config)
```

IANAL, but if I understand things correctly, under GPL v3, if you redistribute a work that depends on and extends a licensed work, you must also provide access to the complete corresponding source code of the modified work under the same GPL v3 license. To the best of my knowledge, those crates are only distributed under Apache 2.0 only.

**Comment by banool** [comment]
Thanks for the report, we are working on a change now to remove use of the crate. Thanks again!

**Comment by banool** [comment]
We have removed the use of the crate and now use `cargo deny` to prevent onboarding crates with undesirable licenses. Thanks for the report! Closing the issue.
