### ISSUE TITLE
CLA link broken

### ISSUE THREAD

**Issue by aertoria** [aptos-labs/aptos-core#1401]
# 🐛 Bug

The link below is used in readme, is broken.
https://github.com/aptos-labs/aptos-core/tree/main/documentation/contributing

**Comment by JoshLind** [comment]
@aertoria, thankfully CLAs are no longer required. If you're seeing mention of a CLA anywhere, please let us know so we can remove it! I'll close this issue for now, but feel free to reopen it if you find anything mentioning CLAs 🤔
