### ISSUE TITLE
[Bug] AptosCoin does not have a paired metadata

### ISSUE THREAD

**Issue by JoeruCodes** [aptos-labs/aptos-core#14033]
# 🐛 Bug

According to the documentation it says that for migration reasons all coins automatically have a paired_metadata counterpart, but AptosCoin type doesnt seem to have one when 0x1::coin::paired_metadata is called.

https://aptos.dev/en/build/smart-contracts/fungible-asset

## To reproduce

**Code snippet to reproduce**
```rust
    use aptos_framework::aptos_coin::AptosCoin;
    #[test]
    fun test_paired_metadata_for_apt(){
        assert!(option::is_some(&coin::paired_metadata<AptosCoin>()), 1);
    }
```

**Stack trace/error message**
```
┌── test_paired_metadata_for_apt ──────
│ error[E11001]: test failure
│     ┌─ /sources/deployer.move:160:9
│     │
│ 159 │     fun test_paired_metadata_for_apt(){
│     │         ---------------------------- In this function in <addr>::deployer
│ 160 │         assert!(option::is_some(&coin::paired_metadata<AptosCoin>()), 0);
│     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Test was not expected to error, but it aborted with code 0 originating in the module <addr>::deployer rooted here
```

## Expected Behavior

The assert shouldn't fail and instead of being empty, the option should have the paired metadata of the AptosCoin.

## System information

**Please complete the following information:**
- Aptos 3.5.0
- Move
- PopOS!

**Comment by JoeruCodes** [comment]
This function should create fungible_asset in the coin_conversion_table and may resolve this issue the only problem is that, I can't do it in my smart contract as it requires aptos_framework (0x1) as a signer...

Calling this function in the init_module function in the AptosCoin should virtually solve this problem

![image](https://github.com/user-attachments/assets/3e20016a-a962-4aa4-bcd0-efa5a65ac747)

**Comment by lightmark** [comment]
If this is for test, can you see https://github.com/aptos-labs/aptos-core/pull/12028   ?
you can all `ensure_initialized_with_fa_metadata_for_test` before test your own code.

**Comment by JoeruCodes** [comment]
I see thank you
