### ISSUE TITLE
[Bug] TokenClient getTokenData Return Type

### ISSUE THREAD

**Issue by hariria** [aptos-labs/aptos-core#1409]
# 🐛 Bug

```ts
  async getTokenData(creator: MaybeHexString, collectionName: string, tokenName: string): Promise<number> {
```

returns a `Promise<number>` when it should be an axios response type with data
![Screen Shot 2022-06-14 at 6 05 58 PM](https://user-images.githubusercontent.com/31301117/173714643-a5591898-ece0-4ca2-9650-722fd8c55287.png)

## To reproduce

`Creator::Collection::Name`
Run on tokenId: `"0x3a09b34de6a5313def18e7463670a685dddabca2edfe8c8314747cecafee07d2::Degen Ape 2::Degen Ape"`

**Comment by jjleng** [comment]
Are you using the latest SDK? It should have been fixed.

![Screen Shot 2022-06-14 at 6 19 40 PM](https://user-images.githubusercontent.com/962285/173716009-4bb268d8-f57a-4da7-9b92-89cd18887583.png)

**Comment by jjleng** [comment]
https://github.com/aptos-labs/aptos-core/commit/863c5317f8184f2ca93031e3a33b62f31ed58677#diff-142a185ce89366828fe38136f03eb06cded1f659b2d4270333efc0f628d79191L145-R242

**Comment by jjleng** [comment]
Upgrade to TS SDK v1.1.0 should have the issue fixed.
