### ISSUE TITLE
[Bug] Create new BLS12-381 Point from u256

### ISSUE THREAD

**Issue by Tranduy1dol** [aptos-labs/aptos-core#14130]
# 🐛 Bug

When implementing the KZG verifier on Aptos, some elements of BLS12-381 are too large and need to be stored as u256. However, Move on Aptos doesn't have any functions to create BLS G1 and G2 points (or I haven't found any).

## To reproduce
```
input:
      x = x"0000000000000000000000000000000000000000000000000000000000000003"
      BLS_MODULUS = 52435875175126190479447740508185965837690552500527637822603658699938581184513
```

```
        let bls_modulus = bls::get_bls_modulus();
        let fr_g2 = crypto_algebra::from_u64<Fr>((((bls_modulus - from_bcs::to_u256(z)) % bls_modulus) as u64));
        let fr_g1 = crypto_algebra::from_u64<Fr>((((bls_modulus - from_bcs::to_u256(y)) % bls_modulus) as u64));
```

**Stack trace/error message**
```
 17 │     public fun verify_kzg_proof(
│    │                ---------------- In this function in 0xb50b1b8157ebf7315813c1f745a1e1c68c73111afe2b6761975223d317569b69::kzg
│    ·
│ 43 │         let fr_g2 = crypto_algebra::from_u64<Fr>((((bls_modulus - from_bcs::to_u256(z)) % bls_modulus) as u64));
│    │                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Test was not expected to error, but it gave an arithmetic error with error message: "Cannot cast u256(52435875175126190479447740508185965837690552500527637822603658699938581184510) to u64". Error originating in the module b50b1b8157ebf7315813c1f745a1e1c68c73111afe2b6761975223d317569b69::kzg rooted here
│ 
```

## System information

**Please complete the following information:**
- Aptos Core Version: 1
- Rust Version: 1.79.0
- Computer OS: ubuntu 22.04

**Comment by alinush** [comment]
Hi, a bit confused about what you are trying to do. Can you post the piece of code that's failing?

If you are trying to create a BLS12-381 point from `(x,y)` or `(x,y,z)` coordinates, don't! Just deserialize your point via `crypto_algebra::deserialize`

**Comment by alinush** [comment]
cc @zjma

**Comment by alinush** [comment]
Also, not that you should do anything like this, but BLS12-381 points definitely **will not** fit in a `u256`: they are 48-byte sized.

Instead, if you need to store your points on-chain, do it by serializing them via `crypto_algebra::serialize` and getting them back via `crypto_algebra::deserialize`

**Comment by Tranduy1dol** [comment]
Thanks to @alinush's suggestion about the serialization and deserialization of BLS12-381; it's very helpful. I solved my problem.
