### ISSUE TITLE
[Bug] large package publication is not work

### ISSUE THREAD

**Issue by echo-pro-dev** [aptos-labs/aptos-core#14219]
# 🐛 Bug

I met a problem with the large package publish, I used the python sdk https://github.com/aptos-labs/aptos-python-sdk/blob/main/examples/large_package_publisher.py, but I can't publish the package successfully.

reproduce steps:
1 run a local testnet with default config
2 deploy the large_package_publisher package  to local testnet(codes located in aptos-move/move-examples/large_packages/)
3 use the python SDK to publish the large packages(codes located in aptos-move/move-examples/large_packages/large_package_example), changed the MODULE_ADDRESS  to local testnet large package address deploied in step2
4 and got error with LINKER_ERROR or EXECUTION_LIMIT_REACHED.

When I build a package with --included-artifacts none ,  and try to publish with this py, I got this "LINKER_ERROR"
![telegram-cloud-photo-size-5-6163620924570582550-y](https://github.com/user-attachments/assets/32e356c8-0c7c-4057-9694-558f39d80a98)

When I build a package with --included-artifacts all ,  and try to publish with this py, I got this "EXECUTION_LIMIT_REACHED"
![telegram-cloud-photo-size-5-6163620924570582551-y](https://github.com/user-attachments/assets/ae3d57a2-f606-44bb-9ab8-b0a543916594)

**Please complete the following information:**
- Aptos Core Version 3.5.1
- Computer OS: both happened on MacOS13 and Ubuntu 22

**Comment by echo-pro-dev** [comment]
Is there any other way to publish large packages?

**Comment by gregnazario** [comment]
@echo-pro-dev this now exists, you can deploy the large package module either locally or on devnet and override it with an address:

```bash
aptos move publish --chunked-publish --large-packages-module-address <MyAddress>
```
