### ISSUE TITLE
[Bug][move-compiler-v2] Differing behavior w.r.t ability checks in the presence of unreachable code

### ISSUE THREAD

**Issue by zzjas** [aptos-labs/aptos-core#14223]
# 🐛 Bug

```move
module 0xCAFE::Module0 {
    struct S {}

    public fun f() {
        let x = S {};
        abort 1;
        let S {} = x;
    }
}
```

V1 compiles fine and running the compiled function will abort with `1`.

V2 will fail bytecode verifier with `POP_WITHOUT_DROP_ABILITY`:
```
bug: bytecode verification failed with unexpected status code `POP_WITHOUT_DROP_ABILITY`. This is a compiler bug, consider reporting it.
  ┌─ ~/debug_package/sources/repro.move:7:9
  │
7 │         abort 1;
  │         ^^^^^^^
```

**Comment by zzjas** [comment]
Similar problem:

```move
module 0xCAFE::Module0 {
    fun f<T>() {
        let a: T = return;
        if (return == {return; a}) {};
    }
}
```

V2 compiles fine, but V1 reports error:
```
error[E05001]: ability constraint not satisfied
...
4 │         if (return == {return; a}) {};
  │                       ^^^^^^^^^^^ '==' requires the 'drop' ability as the value is consumed. Try borrowing the values with '&' first.'
```

**Comment by zzjas** [comment]
A few examples of how Rust allows invalid code after `return`:
```rust
// Rust doesn't check borrow rules in dead code
fn f1() {
    let x: u32 = 0;
    return;
    let ptr = &x;
    let mptr = &mut x;
    let a = *ptr;
    *mptr = 2;
}

// Rust doesn't check unassigned variables in dead code
fn f2() {
    let x: u32;
    return;
    let y = x;
}

// Rust doesn't check moved values in dead code
fn f3() {
    let x = vec![0u8];
    let ptr = &x;
    return;
    thread::spawn(move || {
        let y = x;
    }).join().unwrap();
    println!("{:?}", ptr);
}
```

Note that if `return; ...`  if changed to `if false { ... }`, then Rust compiler will report errors.

**Comment by zzjas** [comment]
Similar problem:
```
module 0xCAFE::Module0 {
    const ADDR: address = @0xBEEF;
    struct S has copy, drop, store, key { }

    public fun function1() acquires S {
        return;
        function2();
    }
    public fun function2() acquires S {
        borrow_global<S>(ADDR);
    }
}
```

Both V1 and V2 will fail bytecode verifier with `EXTRANEOUS_ACQUIRES_ANNOTATION` for this one.

**Comment by zzjas** [comment]
> Similar problem:
> 
> ```
> module 0xCAFE::Module0 {
>     const ADDR: address = @0xBEEF;
>     struct S has copy, drop, store, key { }
> 
>     public fun function1() acquires S {
>         return;
>         function2();
>     }
>     public fun function2() acquires S {
>         borrow_global<S>(ADDR);
>     }
> }
> ```
> 
> Both V1 and V2 will fail bytecode verifier with `EXTRANEOUS_ACQUIRES_ANNOTATION` for this one.

It seems like that #14334 doesn't fix this `EXTRANEOUS_ACQUIRES_ANNOTATION` failure. Tested on latest main `f554a3185a573bebfd765091aa06ad43db0d3d57`. Similarly, not sure if V2's behavior for https://github.com/aptos-labs/aptos-core/issues/14223#issuecomment-2271943681 has been double-checked to be ok. 

I originally put these two tests in this issue thinking they might share the same root cause. Do you think it's better to create separate issues?

**Comment by vineethk** [comment]
Yes, please create a separate issue with what's remaining, thank you!
