### ISSUE TITLE
[Bug] Unable to publish package with bytecode deps

### ISSUE THREAD

**Issue by jasonxh** [aptos-labs/aptos-core#14311]
# 🐛 Bug

I followed these docs to set up my package with a bytecode dep:

- https://aptos.dev/en/build/smart-contracts/book/packages#using-bytecode-for-dependencies
- https://aptos.dev/en/build/smart-contracts/third-party-dependencies#bytecode

I was able to compile the package successfully. However, when trying to publish it with `create-object-and-publish-package`, it failed with this error

> Simulation failed with status: CONSTRAINT_NOT_SATISFIED
> Execution failed with message: metadata and code bundle mismatch: unregistered dependency

## To reproduce

Here's [minimal package](https://github.com/user-attachments/files/16651004/b.tgz) for repro (the dependency `A` has already been published on [Testnet](https://explorer.aptoslabs.com/object/0x8ae94b63db9b31761835258cd938ef670235069d37c17c616d06d28860dffe87/modules/code/a?network=testnet)).

**Code snippet to reproduce**
```shell
tar -xzvf ./b.tgz
cd b
# Assuming the default profile is set up for Testnet
aptos move create-object-and-publish-package --address-name b
```

**Stack trace/error message**
```
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY A
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING B
Do you want to publish this package at object address 0x9995f8435c2bf9f13c1877b82b3c97df076c68fe86ada0aa1b6c471334847d84 [yes/no] >
yes
package size 728 bytes
{
  "Error": "Simulation failed with status: CONSTRAINT_NOT_SATISFIED\nExecution failed with message: metadata and code bundle mismatch: unregistered dependency: '8ae94b63db9b31761835258cd938ef670235069d37c17c616d06d28860dffe87::a'"
}
```

## Expected Behavior

Publication is successful.

## System information

**Please complete the following information:**
- Aptos Core Version: 4.0.0
- Rust Version: 1.80.0
- Computer OS: macOS

## Additional context

I did some digging and it looks like bytecode deps were missing from `PackageMetadata` in the publish transaction payload. Further digging showed they were missing from the [CompiledPackage](https://github.com/aptos-labs/aptos-core/blob/8825060eb3db7f610616d3cb7f5b54b6e53f930e/third_party/move/tools/move-package/src/compilation/compiled_package.rs#L76), because they were technically not part of `deps_compiled_units`. In fact, I was able to make some small changes to `CompiledPackage` to include `bytecode_deps` and propagate that to `PackageMetadata`, which was sufficient to get the package published successfully. However, a proper fix would require associated changes in [OnDiskCompiledPackage](https://github.com/aptos-labs/aptos-core/blob/8825060eb3db7f610616d3cb7f5b54b6e53f930e/third_party/move/tools/move-package/src/compilation/compiled_package.rs#L125C6-L125C27) as well.

**Comment by vgao1996** [comment]
Thanks so much for flagging this! Your analysis makes sense.

> In fact, I was able to make some small changes to CompiledPackage to include bytecode_deps and propagate that to PackageMetadata, which was sufficient to get the package published successfully.

Fantastic! Would you be willing to open a PR with your changes? It would be a great starting point for the full fix, and it's an excellent opportunity for a community contribution.

> However, a proper fix would require associated changes in [OnDiskCompiledPackage](https://github.com/aptos-labs/aptos-core/blob/8825060eb3db7f610616d3cb7f5b54b6e53f930e/third_party/move/tools/move-package/src/compilation/compiled_package.rs#L125C6-L125C27) as well.

Ah yes, we'll need to persist the additional info in the `OnDiskCompiledPackage` as well. If you have the time, I'd be happy to guide you through the implementation. If not, no worries—just let me know, and I can take it from here.

**Comment by jasonxh** [comment]
Sure I'll prepare a PR.

**Comment by 0xshinobii** [comment]
I am facing the same issue. any update on the fix PR?

**Comment by vgao1996** [comment]
Hey @0xshinobii, thanks for your patience! 

@jasonxh has put up a partial fix (#14340), and I've done a bit more study to determine what needs to be done at the on-disk storage level. We'll follow up and see if we can get it implemented soon.

**Comment by particle4dev** [comment]
any update on the fix PR? @vgao1996

**Comment by vgao1996** [comment]
@particle4dev the fix is in review right now: https://github.com/aptos-labs/aptos-core/pull/14929

We'll try to get it landed early next week.
