### ISSUE TITLE
[move-compiler-v2] Update Move Book with Move 2 features

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#14343]
# 🐛 Feature Request

Let's list the needed features here and make sure they are not missed at launch.

See also https://github.com/aptos-labs/aptos-core/issues/14036

## Items to include

- `assert!` macro can take just 1 parameter 9see #14334.
- If PR #14254 has landed, then note that lambda parameters can have explicit types if desired.
- Once PR #14417 lands, then add note on new concise visibility syntax.
- Once PR #14415 lands, then add note on new syntax for structs with no fields.

**Comment by vineethk** [comment]
Also,
* `..` syntax (and its limitations),
* positional fields,
* vector and resource index
