### ISSUE TITLE
Unlock and Reactivate Delegation

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-core#14619]
when i created a unlock or reactivate transactions, its unlocking or reactivating whole balance even though i gave a differnet amount, whats the reason behind this?

[explorer](https://explorer.aptoslabs.com/txn/0x5249e11cb06063d1a7280f7529309bfebc3cbaf05afa7e384fe5890bb6a81125/changes?network=mainnet)

I'm using these functions:
```
0x1::delegation_pool::add_stake
0x1::delegation_pool::unlock
0x1::delegation_pool::reactivate_stake
```

ps: these apis parameters are same, signer, validator, amount

**Comment by dev-dantealighieri** [comment]
hey @0xmaayan, can you look into this?

**Comment by yyflightwatcher** [comment]
Hello sir, i met the same problem, are these any solutions ?
