### ISSUE TITLE
[Bug][move-compiler-v2] constants should not be able to refer to other constants

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#14648]
# 🐛 Bug

See the test outputs:
- third_party/move/move-compiler/tests/move_check/typing/constant_allowed_but_not_supported.exp
- third_party/move/move-compiler-v2/tests/checking/typing/constant_allowed_but_not_supported.exp
V2 does not complain about the use of const names in other consts.

In PR #14578 I'm adding a new test case
- third_party/move/move-compiler/tests/move_check/typing/recursive_constant.exp
- third_party/move/move-compiler-v2/tests/checking/typing/recursive_constant.exp
which shows totally unexpected code generated by V2 in the case of recursive constants.

This needs to be fixed.

**Comment by rahxephon89** [comment]
Instead of not allowing it, I am wondering whether we could check recursive use of other constants?
