### ISSUE TITLE
THANKFUL

### ISSUE THREAD

**Issue by Abidouz** [aptos-labs/aptos-core#14858]
I just want to use this medium to let everyone in Aptos family that they have been nothing but great network to the whole space. Aptos operates with honesty and transparency, upholding ethical standards and building trust with their clients and employees. Accountability: Aptos takes responsibility for their actions and decisions, holding themselves accountable for delivering results and meeting commitments.

**Comment by georgemitenkov** [comment]
Thank you! Closing the issue though😉
