### ISSUE TITLE
[Bug] Unused parameter 'self' in aptos-stdlib/sources/pool_u64_unbound.move - multiply_then_divide

### ISSUE THREAD

**Issue by 0xblockbard** [aptos-labs/aptos-core#14865]
# 🐛 Bug

I get this warning whenever any compilation or test is run.

```
warning[W09002]: unused variable
    ┌─ /Users/user/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/pool_u64_unbound.move:258:37
    │
258 │     public fun multiply_then_divide(self: &Pool, x: u128, y: u128, z: u128): u128 {
    │                                     ^^^^ Unused parameter 'self'. Consider removing or prefixing with an underscore: '_self'

warning[W09002]: unused variable
    ┌─ /Users/user/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/pool_u64.move:261:37
    │
261 │     public fun multiply_then_divide(self: &Pool, x: u64, y: u64, z: u64): u64 {
    │                                     ^^^^ Unused parameter 'self'. Consider removing or prefixing with an underscore: '_self'
```

It does not break anything, but it would be really nice if this could be fixed so it doesn't show up when compiling or running tests

**Comment by rahxephon89** [comment]
Hi @0xblockbard, which version of CLI are you using? Also, are you compiling using Compiler V2 (by specifying `--move-2`)?

**Comment by 0xblockbard** [comment]
> Hi @0xblockbard, which version of CLI are you using? Also, are you compiling using Compiler V2 (by specifying `--move-2`)? With this PR: #14368, no warning should be generated.

Thanks for getting back! Have upgraded aptos with `brew upgrade aptos` and compiling and testing with Compiler V2 works fine now without any issues
