### ISSUE TITLE
How to upgrade my move package (or module)

### ISSUE THREAD

**Issue by alphabiz-se2** [aptos-labs/aptos-core#1518]
## How to upgrade my move package (or module)

I try to modify my move module and execute the `publish` command after compilation

Old Package:

- sources
  - FooMessage.move

New Package:

- sources
  - FooMessage.move [ modified ]
  - BarMessage.move  [ created ]

but it tells me `DUPLICATE_MODULE_NAME`

```shell
{
  "Error": "API error: transaction execution failed: Transaction Executed and Committed with Error DUPLICATE_MODULE_NAME"
}
```

![image](https://user-images.githubusercontent.com/86668439/174702382-6b1a3a96-138c-4060-839f-817cb8858729.png)

My understanding of this is that duplicate FooMessage modules are published.

But I don't know how to update published modules ( `FooMessage.move` ), and add new modules ( `BarMessage.move` )

**Comment by gregnazario** [comment]
Currently move module republishing is off, and move upgradability is something we're working on cc @wrwg for visibility

**Comment by davidiw** [comment]
Please follow discord, we'll have an update on this topic in the coming weeks.
