### ISSUE TITLE
[Bug][Explorer] Incomplete transaction list in Explorer

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#1534]
# 🐛 Bug

The shows an incomplete transaction list for an account.

## To reproduce

Create an account and perform more than 25 transactions. Explorer will only display the first 25 transactions.
Here's an example account: https://explorer.devnet.aptos.dev/account/0xfb7da016289fecc705d503633e0dbcde083c273fd140f646f8ef6b31fa547178
Via the API you can see the account has way more transactions: https://fullnode.devnet.aptoslabs.com/accounts/0xfb7da016289fecc705d503633e0dbcde083c273fd140f646f8ef6b31fa547178/transactions?limit=500

## Expected Behavior

1. Explorer should display the most recent transactions in an account first (instead of the oldest ones)
2. Explorer should paginate over list of transactions for an account

**Comment by gregnazario** [comment]
Is this still an issue?  I'm going to close this in favor of the redesign for the explorer
