### ISSUE TITLE
[Bug][compiler-v2] Tests running for "move-unit-test" package are not using compiler v2

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#15385]
# 🐛 Bug

If we go to `third_party/move/tools/move-unit-test` and run: `MVC_V2=1 MVC_BLOCK_V1=1 cargo test`, we see that it panics with "V1 compiler not expected".

But the `scripts/move_pr.sh` runs these tests with `MVC_V2=1` (i.e., the equivalent `MOVE_COMPILER_V2=true`); we also have baseline files `*.v2_exp` added with the expectation that these outputs are from running compiler v2. However, all of these actually are just running compiler v1, giving us a false sense of testing.

## To reproduce

See steps above.

## Expected Behavior

We should be running the tests under `third_party/move/tools/move-unit-test` with compiler v2 when `MVC_V2=1`.

**Comment by vineethk** [comment]
cc @rahxephon89 @brmataptos: in case this was an already known issue.

**Comment by rahxephon89** [comment]
> cc @rahxephon89 @brmataptos: in case this was an already known issue.

Good catch @vineethk! We should use `plan_builder_v2` when V2 flag is turned on. cc @brianrmurphy
