### ISSUE TITLE
Coin pooling account

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#1556]
As part of our goals for standards, we seek to support composability rather than complexity in our standards. One such example in NFTs is royalties paid to a creator upon selling. To cope with varying different strategies, other tokens create complex data structures that sit with the NFT metadata. For our standard, we only want to have a single address. It would then be the responsibility of the account at that address to distribute out the royalties. The goal of this task is to make a simple shared account that works as follows:

* Assume that there are K accounts
* Each account is given some proportion of the assets stored in the Coin<TestCoin>
* Create a new module that contains
  * A SimpleMap to track <Account, State { Share Numerator, Share Denominator, Taken }> -- where share num / share denom is the percent of the total funds allocated to this account, and taken is the accumulation of what has been taken by this account
  * A u128 to represent the total amount taken, then we can represent the total amount as (available + amount taken).
  * A holder for the signer of a resource account (`create_resource_account`)
* The amount available for an account is then (available + amount taken) * (share num) / (share denom) - taken by account
* An account can withdraw from this, this will check the map for validity and will remove all available coins and deposit them into the accounts own Coin<TestCoin>

This assumes deep familiarity with Move and our AptosFramework.

**Comment by chloeqjz** [comment]
after discussion with @davidiw, we decided to use a SimpleMap to track <Account, { Share Numerator, Share Denominator }> without `Taken`. We will have a disperse function that could transfer the coins to different accounts as soon as the NFT is sold so we no longer need to track the `taken` amount.
