### ISSUE TITLE
how fix this

### ISSUE THREAD

**Issue by jaykeatlas** [aptos-labs/aptos-core#1663]
./aptos genesis generate-genesis --local-repository-dir /opt/test --output-dir /opt/test
thread 'main' panicked at 'Error calling Genesis.create_initialize_validators: status ABORTED of type Execution with sub status 1031', aptos-move/vm-genesis/src/lib.rs:180:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by quangthanh010290** [comment]
me same:
`Finished release [optimized + debuginfo] target(s) in 0.41s
     Running `target/release/aptos genesis generate-genesis --local-repository-dir /root/testnet --output-dir /root/testnet`
thread 'main' panicked at 'Error calling Genesis.create_initialize_validators: status ABORTED of type Execution with sub status 1031', aptos-move/vm-genesis/src/lib.rs:180:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by davidiw** [comment]
Need a lot more details, like branch, backtrace, and what you were doing. I suspect that since there are a lot of folks that made progress, this might have been a one-off? Feel free to re-open with more detail.
