### ISSUE TITLE
[Bug] Unable to start local test validator using Docker

### ISSUE THREAD

**Issue by leofisG** [aptos-labs/aptos-core#1700]
# 🐛 Bug

I was following the guide [here](https://aptos.dev/nodes/run-a-local-testnet#example). However, I am getting the following error:
```
Attaching to aptos_local_validator-faucet-1, aptos_local_validator-validator-1
aptos_local_validator-validator-1  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
aptos_local_validator-faucet-1     | Validator has not populated mint.key yet. Is it running?
```

## To reproduce
I ran the following command with docker daemon started:
```
mkdir aptos_local_validator && cd aptos_local_validator
wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/validator-testnet/docker-compose.yaml
wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/validator-testnet/validator_node_template.yaml
docker-compose up
```

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
Attaching to aptos_local_validator-faucet-1, aptos_local_validator-validator-1
aptos_local_validator-validator-1  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
aptos_local_validator-faucet-1     | Validator has not populated mint.key yet. Is it running?
```

## System information

**Please complete the following information:**
-  Macbook Pro M1 Max

## Additional context

ruyisu#5492 is also able to reproduce.

**Comment by sherry-x** [comment]
Yeah node docker image doesn't work on M1 chip, this is a known issue unfortunately haven't resolved yet.

**Comment by leofisG** [comment]
I also tried compiling from source, it doesn't seem to work either. It keeps giving me bus error. Is there any workaround that I can use? @sherry-x

**Comment by sherry-x** [comment]
Compiling should work, I’m on M1 chip and I can compile source with no problem. Maybe you can share the errors

**Comment by leofisG** [comment]
I can compile with no issue, but I can't run the local validator.

Here is the error that I am seeing:
```
[1]    16585 bus error  CARGO_NET_GIT_FETCH_WITH_CLI=true cargo run -p aptos-node -- --test
```

**Comment by hubert-da** [comment]
`Validator has not populated mint.key yet. Is it running?` happens to me too for the docker-compose setup on both a Debian VM as well as a Macbook Pro (Intel).

**Comment by hubert-da** [comment]
On the other hand, `aptos node run-local-testnet --with-faucet` hangs on `Aptos is running, press ctrl-c to exit` without starting the faucet.

**Comment by hubert-da** [comment]
Managed to run `aptos node run-local-testnet --with-faucet` with the latest CLI version (0.2.2):
```
Faucet is running.  Faucet endpoint: 0.0.0.0:8081
```
