### ISSUE TITLE
 process didn't exit successfully:  [Bug]

### ISSUE THREAD

**Issue by lazy1523** [aptos-labs/aptos-core#1720]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
failed to run custom build command for `cached-framework-packages v0.1.0 (/root/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/22fd977/aptos-move/framework/cached-packages)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installIfOyWF/release/build/cached-framework-packages-d17aff2bed849670/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../aptos-framework/sources
  cargo:rerun-if-changed=../move-stdlib/sources
  INCLUDING DEPENDENCY MoveStdlib
  BUILDING AptosFramework
  Checking layout compatibility
  Generating error map
  Generating script builders
// Paste the output here
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Aptos Core Version -->
- <!-- Rust Version -->
- <!-- Computer OS -->
ubuntu20.04

## Additional context

Add any other context about the problem here.

**Comment by banool** [comment]
Please provide a proper set of steps to repro this issue, otherwise we'll have to close it.
