### ISSUE TITLE
Execution error BlockNotFound

### ISSUE THREAD

**Issue by lukema95** [aptos-labs/aptos-core#1795]
### Please note that this issue tracker is not a help form and this issue will be closed.
2022-07-07T15:41:01.065872Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:278 Execution error BlockNotFound(HashValue(536ecd8aad8face5949ece27adb4dd925def24e750895d16a9e9e13b7e09db51))
How do I solve it?

**Comment by JoshLind** [comment]
Hi @lukema95. Do you have any additional information? What network are you targeting? What code version, build version, etc. Without this information, it's almost impossible to understand what's wrong 😄

**Comment by lukema95** [comment]
> Hi @lukema95. Do you have any additional information? What network are you targeting? What code version, build version, etc. Without this information, it's almost impossible to understand what's wrong 😄

I deployed according to the official AIT2 tutorial, using docker. https://aptos.dev/nodes/validator-node/run-validator-node-using-docker

**Comment by davidiw** [comment]
Closing out, feel free to re-open if issue persists.
