### ISSUE TITLE
[NHC] Add metrics support

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#1798]
# 🚀 Feature Request
Currently NHC (Node Health Checker) doesn't export any metrics, meaning we don't have great visibility into what it is doing beyond just basic logging and container level metrics (CPU usage for example). We should add metrics to NHC, such as:
- How many requests it handled in the last minute, per endpoint.
- How many of those failed.
- Per error code counters.
- Metrics for returning 500s.
- Metrics for returning 400s.
- Metrics for returning passing (100) and non-passing (<100 evaluation results).

This will help us track how well NHC is performing.

**Comment by gregnazario** [comment]
You output these metrics now right @banool?
