### ISSUE TITLE
[NHC] Add deep health checks

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#1800]
# 🚀 Feature Request
This issue isn't meant to track a single unit of work, but a general effort, in which we add deep health checks to NHC.

In short, deep health checks are checks that run over the noise / consensus port (6180 by default). In this mode of operation, NHC would take the role of an "observer node", which could be configured at genesis, and have permission to send requests using noise directly to each "microservice" of the node, vs. the current checks which speak to the API / metrics ports.

These deep health checks could help us assert things that we can't assert over the API, particularly in a trustless way, such as asserting that consensus is operating correctly, that storage can produce what it claims it can, etc.

I mostly open this issue now to make sure this work is tracked for the future, we can close it when we start building this out in earnest and open more specific issues.

**Comment by gregnazario** [comment]
We now have network health checks as deep as we'll probably get for now.
