### ISSUE TITLE
[NHC] Add web UI  

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#1801]
# 🚀 Feature Request
Today there are a few different node validation tools out there made by third parties. These are great community contributions, but one of the key issues with them is they're often configured incorrectly for the node type that users are trying to test. As far as I'm aware, today all of these tools only support a single baseline configuration, so if a particular tool is configured for devnet fullnodes, users who test AIT2 validators will potentially erroneously see that their nodes are configured incorrectly.

NHC is built with this requirement in mind, supporting multiple different baseline configurations from a single instance. We should make NHC available to the community with a hosted deployment of the backend and an appropriate frontend.

Another key difference is these tools often show users a bunch of information without necessarily telling them whether it is correct. NHC on the other hand is evaluation focused, in which it shows the user not only pieces of data, but whether they're meeting preconfigured requirements.

Some additional thoughts:
- We would likely want to disable the TPS test for this deployment. This would reduce our resource requirements greatly, make it much more reliable, and make a single test take only 10ish seconds vs over a minute.
- We would want to be able to show the user arbitrary information alongside evaluations, e.g. ledger storage state, traffic information. The API would have to be enhanced for this, plus we'd have to figure out if we return just prometheus metrics or something more structured.

**Comment by gregnazario** [comment]
You've added a web UI now right @banool ?

**Comment by banool** [comment]
Correct, we now have a basic web UI here: https://explorer.devnet.aptos.dev/node_checker.
