### ISSUE TITLE
[Feature Request] Support authentication for telemetry.

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#1895]
# 🚀 Feature Request

We're currently sending telemetry data to help track the health and usage of our software (e.g., validators, fullnodes and CLI). One thing we also need to support is authenticated telemetry data (i.e., telemetry data from trusted sources that we can verify). Right now, no telemetry data is authenticated.

There's a number of ways to approach this, including:
1. The hacky (but reasonable) approach that'll work for now: (i) assume we have a (semi-secure) way of contacting each operator directly; (ii) generate an authentication token using our service and send it to each operator; (iii) have the operator put it into a config/load it into the node; and (iv) have telemetry use it to authenticate to the server.
2. The non-hacky (but more complex) approach that'll require more work: (i) require the nodes to sign data using the consensus key (e.g., sign a nonce presented by the authentication service); (ii) have the authentication service contact a fullnode, identify the latest validator set on-chain and verify the signature and consensus key for the node; (iv) produce a new session key for the node; and (v) have the telemetry client use it to authenticate to the server.

Notes:
- There's also a number of other options that take a different approach to authentication, but those can be discussed if none of the above sound good enough.
- Regardless of the approach we take above, we'll need to update to a new telemetry service (if I remember correctly, GA measurement provides no authentication support at all)

**Comment by geekflyer** [comment]
this is completed with the new telemetry-service
