### ISSUE TITLE
[Feature Request] Support Websockets / Server Sent Event for Real Time Data Update

### ISSUE THREAD

**Issue by leofisG** [aptos-labs/aptos-core#1940]
# 🚀 Feature Request

It will be nice if we can have the server sent event implemented as discussed on [Discord](https://discord.com/channels/945856774056083548/946123778793029683/996328082212397147).

## Motivation
It will be useful for a lot trading related application that requires real-time updates. Without it, we will have to do polling on the client side.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by banool** [comment]
It's definitely on our radar, I'm looking at improvements to our API now. Stay posted :)

**Comment by Manahip** [comment]
Like this idea, or the general idea of "subscribing to changes in specific resource objects". The indexer can easily support these subscriptions.

**Comment by gregnazario** [comment]
This will likely be provided through our indexer in the future

**Comment by leofisG** [comment]
@gregnazario any update on this?

**Comment by gregnazario** [comment]
This is on the radar, and we haven't forgot about it.  We may have support for this through the indexer, but we're looking at options and planning for how to do this right

**Comment by mutable-dev** [comment]
This is super important, please prioritize this feature!!

**Comment by banool** [comment]
We'll start working on this soon!

**Comment by e99243506bigplay** [comment]
who wtf working on this, if has progress on it, pls tell me how to use it.

**Comment by jiOnederfull** [comment]
I also want to receive updates. Is there any progress?

**Comment by web-dev100** [comment]
Is there realistically a plan to support websockets or some sort of IPC mechanism for this network in the near future? This issue has been open for 2 years and frankly is the bare minimum expectation for anyone integrating with this chain. Having to constantly poll is a pretty wild "solution" for a chain that's tag line is "the world's most production ready blockchain". I think most would be quite happy with something similar to how Solana has their clients setup (which aren't amazing but do have good coverage):
- notifications for account data changes
- notifications for specific events (new blocks, txs by a specific signer, tx receipt confirmations)
