### ISSUE TITLE
[Bug] Cannot start Indexer due to deserialization error 

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#1950]
# 🐛 Bug

## To reproduce
Start indexer locally using 
```
argo run -- --pg-uri "postgresql://localhost/postgres" --node-url "https://fullnode.devnet.aptoslabs.com" --emit-every 25 --batch-size 100
```

**Stack trace/error message**
![Screen Shot 2022-07-13 at 1 53 41 PM](https://user-images.githubusercontent.com/1082769/178832427-726a481a-9fba-4dde-9240-c6e437c5f369.png)

**Comment by topazso** [comment]
Possibly related?  On M1 mac.
 
`diesel migration run --database-url postgresql://localhost/postgres`

```
dyld[56518]: missing symbol called
[1]    56518 abort      diesel migration run --database-url postgresql://localhost/postgres
```

**Comment by CapCap** [comment]
This should be fixed as of the deploy a few weeks ago :-)
