### ISSUE TITLE
[Bug] Add Hardware requirements  Bandwidth:  1 GBit/s

### ISSUE THREAD

**Issue by encipher88** [aptos-labs/aptos-core#1974]
# 🐛 Bug

## Additional context

Add please for future testers 
https://aptos.dev/nodes/ait/node-requirements
Hardware requirements 
Bandwidth:  1 GBit/s
Connection:  1 GBit/s port

I recommend adding this as it has been verified directly by several users including myself, the smaller channel is missing votes
![Screenshot_69](https://user-images.githubusercontent.com/36136421/179045203-76dc9593-6bc5-4720-9a12-d68dca4ff675.png)

**Comment by gregnazario** [comment]
It's now 1 Gbps
