### ISSUE TITLE
[Feature Request] Provide native function getter for database version number

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#1975]
As described in #910 , a proposed native function getter for the [Aptos database version number](https://aptos.dev/concepts/basics-txns-states#versioned-database) returns the Aptos ledger version number during transaction execution, which allows for chronological re-sequencing of data structures within Move, after they have been written to non-overlapping locations in memory.

Through Block-STM's optimistic concurrency, non-overlapping write sets execute in parallel, and if the data structure in each write set can be marked with the version number as proposed through this native function, then it is possible for a matching engine to determine chronology for data structures that were written, for example, to queues that were designed to take in orders in parallel.

Proposed function signature:

```move
/// Return the version number of the distributed database,
/// corresponding to the number of transactions the system will have
/// executed upon the conclusion of the current one
public native fun version_number(): u64;
```

@davidiw @movekevin

**Comment by alnoki** [comment]
@movekevin do you think `aptos_framework::transaction_context` would be the right place for this function? Git blame is showing you are the last person who modified that module, with `get_script_hash()` providing similar functionality

**Comment by wrwg** [comment]
Yes that is the right point to implement this. This function should go in the same module `transaction_context` and have a more descriptive name there.

**Comment by movekevin** [comment]
Yeah this sounds like it belongs there. The only thing I'm thinking through though is if parallel execution can reexecute transactions that failed due to conflict, wouldn't the version number potentially change? But may be this is okay anyway as long as the transaction is re-executed.

Can you give a bit more context on the matching engine use case you mentioned and why it needs the version number?

**Comment by alnoki** [comment]
> 

The implementation is to allow for re-sequencing of batched orders that queue up in parallel ring buffers - encoding each order with its version number allows for the linear submission sequence to be reconstructed during a batch reconciliation transaction

**Comment by movekevin** [comment]
I'm still not quite following what the flow looks like. Can you provide an example?

**Comment by alnoki** [comment]
> 

Consider two parallel buffers, `paraqueue A` and `paraqueue B`, each of which are independent resources (or `Table` items), such that read/write sets do not collide. `paraqueue A` is for orders having a tx hash less than `MIDWAY = U_64_MAX / 2`, and, `paraqueue B` is for orders having a tx has greater than or equal to `MIDWAY`.

User 1 submits an order with a hash of 0x1, which gets bucketed into `paraqueue A`, and User 2 submits an order with a hash of `0xffffffff.....`, which gets bucketed into `paraqueue B`. Each order gets stored in a struct that appends the version number during which the order was processed.

Later, the batch reconciliation inspects the version number and resequences the orders into chronological order before running them through the matching engine.

Is this helpful?

**Comment by davidiw** [comment]
Unfortunately it is impossible to reveal version numbers in an active move session. Versions are delegated after parallel execution. You could instead leverage a framework such that you use `sip hash (address | transaction sequence number | any other data if necessary) % number of paraqueues`
