### ISSUE TITLE
[Feature Request] Impractical: aptos-cli's looks for config.yaml in a location relative to where it is being run from

### ISSUE THREAD

**Issue by gaia** [aptos-labs/aptos-core#2031]
# 🚀 Feature Request

`aptos-cli` looks for `config.yaml` in `.aptos/` relative to the present working directory. It would be easier to manage a single location for the config, and it should default to `$HOME/.aptos/config.yaml`. If an user wants to run with an alternate config, it could be specified as `aptos-cli -c /new/path/to/alternate/config.yaml`

_PS: I know this seems so obvious and it must be in some shape or form in the roadmap, but I couldn't find an issue nor a roadmap for aptos-cli._

**Comment by gregnazario** [comment]
Hey!  This has been implemented now with the latest CLI.  I should probably make it the default, but I didn't want to change people's current flows.

You can enable global config version with the following command.

```
aptos config set-global-config --config-type global
```

Please re-open if you have issues / there's something this misses.
