### ISSUE TITLE
[Bug] aptos-logger fails to log crashes / panics in certain situations

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#2038]
see 
https://github.com/aptos-labs/aptos-core/runs/7381922155?check_suite_focus=true
https://github.com/aptos-labs/aptos-core/runs/7382080046?check_suite_focus=true

The TLDR is:
Aptos-logger appears to fail logging errors/panics in certain situations, such as when a process in its entirety crashes even when calling .flush in the crash handler.
As a workaround we're using synchronous `eprintln` etc. here https://github.com/aptos-labs/aptos-core/blob/main/crates/crash-handler/src/lib.rs#L39-L42 but a proper solution should be to have the aptos_logger write all pending messages to stdout when .flush() is being called and block until this is completed. Currently it doesn't seem to do this for whatever eason.

**Comment by gregnazario** [comment]
This doesn't look like the logger is panicking, this looks like the faucet fails to make a transaction and is why it fails

**Comment by geekflyer** [comment]
This actually isn't solved afaik, so reopening.
I just updated the title to reflect better what this is about.

**Comment by gregnazario** [comment]
Please provide more insight, or examples in this issue otherwise, it's very stale and there is no update about issues associated with it, so I'm closing it.
