### ISSUE TITLE
[Bug] Inaccessibility of metrics when running in Docker

### ISSUE THREAD

**Issue by Krishnacore** [aptos-labs/aptos-core#204]
# 🐛 Bug

It seems that inside the container, the application is listening to 127.0.0.1:9091 (instead of 0.0.0.0:9091), which causes no connection to be accepted from the host:
```logs
curl 127.0.0.1:9101/metrics 
curl: (7) Failed to connect to 127.0.0.1 port 9101: Connection refused
```
## To reproduce

Just run FullNode in Docker, then:

```bash
curl 127.0.0.1:9101/metrics 2> /dev/null | grep aptos_state_sync_version | grep type
```

## Expected Behavior
```
aptos_state_sync_version{type="committed"} 113184
aptos_state_sync_version{type="highest"} 113184
aptos_state_sync_version{type="synced"} 113184
aptos_state_sync_version{type="target"} 113185
```

**Comment by rustielin** [comment]
Thanks for reporting this issue! A fix is on the way https://github.com/aptos-labs/aptos-core/pull/205

**Comment by Krishnacore** [comment]
Yes, my mistake. I misplaced the ports. 
By the way, did you think to add to your Dockerfiles something like:
ENV PATH="${PATH}:/opt/aptos/bin"
So you don't have to specify the full path to the binaries in docker-compose?
