### ISSUE TITLE
[Feature Request] Support Resouce Account Creation in the Aptos CLI

### ISSUE THREAD

**Issue by leofisG** [aptos-labs/aptos-core#2044]
# 🚀 Feature Request

It will be nice if we can add a new command to create resource account on-chain. Something like:
```
aptos account create-resource-account --seed 0xabc --authentication-key
```

## Motivation
Resource accounts will be widely used for things such as program deployment.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Sure.

## Additional context
I can help send in a PR if the core team feels okay with having this.

**Comment by JoshLind** [comment]
Thanks @leofisG!

> I can help send in a PR if the core team feels okay with having this.

Feel free to send out a PR to do this. I'm sure the other folks won't mind as I can see this being a useful operation :)

**Comment by leofisG** [comment]
I already sent one #2071 
But I am not sure I am able to address all the comments given limited capacity

**Comment by davidiw** [comment]
Thanks!
