### ISSUE TITLE
[Feature Request]Support `Coin` related operation in Aptos CLI

### ISSUE THREAD

**Issue by leofisG** [aptos-labs/aptos-core#2045]
# 🚀 Feature Request
It will be nice if `Coin` related operation can be supported via the Aptos CLI similar to Solana's `spl-token` program. 

## Motivation
This will allow us to transfer, mint, burn various `Coin` for testing a lot easier.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Sure.

**Comment by gregnazario** [comment]
Transfer for the native coin exists, but for various coins it doesn't.  Sounds like a good testing feature to have!

**Comment by leofisG** [comment]
@gregnazario any update on this?

**Comment by davidiw** [comment]
considering how easy it is to call the entry functions directly via the cli... this is low pri.

**Comment by wrwg** [comment]
Closing for now, expecting to get similar feature with new CLI.

**Comment by wrwg** [comment]
Reopening, removing from `Move` project, and assigning to @gregnazario for re-assessment.

**Comment by gregnazario** [comment]
This is low priority since functions can be called with `aptos move run`.  The future coin v2 standard may need these updated if they aren't easy to call via `aptos move run`
