### ISSUE TITLE
[Feature Request] Dependency as binary/abi instead of source code

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#2053]
# 🚀 Feature Request

## Motivation

Let's say i have closed source repository contains my Move smart contracts. I want other projects to have a way to integrate their smart contracts with mine (which is closed source or source code is missed or whatever). In case of Solidity i could just provide interfaces, but in case of Move i can't .

## Pitch

Would be nice if i could just publish compiled Move package or ABI to Git and then add it as dependency.

## Additional context

I'm willing to help implement such PR, yet we want to hear other opinions, maybe there is better implementation i missed.

**Comment by wrwg** [comment]
We are actually planning to deploy enough metdata on chain so a package can be found there. We can discuss more on slack if you'd like to.

**Comment by wrwg** [comment]
Closing for now as we have no immediate plans to support this.
