### ISSUE TITLE
[Bug] Make all API endpoints that accept page params work the same way

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2090]
# 🐛 Bug
For events, if no paging params are given (`start` and `limit`), we return `default_limit` events starting from zero. For transactions, if no paging params are given, we return `default_limit` events starting from `latest_version - default_limit`.

AKA: For events, return the first n events. For transactions, return the last n events.

We should make these two work the same way. I figure returning the last n by default is more user friendly, but if we go with that by default, we'll need a good explanation in the spec / SDK, since if you specify `start` all of a sudden it starts from that point, instead of going back from that point.

**Comment by DeveloperInProgress** [comment]
https://github.com/aptos-labs/aptos-core/pull/2256

**Comment by ikabiljo** [comment]
Added #2582 to fix this. Thanks @DeveloperInProgress for helping
