### ISSUE TITLE
[CLI] make it possible to run a local testnet with *multiple* validator nodes

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#2096]
as per https://aptos-org.slack.com/archives/C034T4ZQ8DB/p1658251700487529?thread_ts=1658250757.767929&cid=C034T4ZQ8DB

**Comment by geekflyer** [comment]
cc @gregnazario @JoshLind

**Comment by JoshLind** [comment]
Done. See: https://github.com/aptos-labs/aptos-core/tree/main/testsuite/forge-cli/src.
