### ISSUE TITLE
[APT-5] [Feature Request] Add a compiler error if entry function returns any value

### ISSUE THREAD

**Issue by JackyWYX** [aptos-labs/aptos-core#2106]
# 🚀 Feature Request
Add a compile error if entry function returns any value.

## Motivation
For aptos network, it is illegal to have the entry function return any values. E.g.

```
module Dev::HelloWorld {
    public(script) fun hello(): u64 { 5 }
}
```

```
$ aptos move run --function-id default::HelloWorld::hello
{
  "Error": "API error: transaction execution failed: Transaction Executed and Committed with Error INVALID_MAIN_FUNCTION_SIGNATURE"
}
```
This error would be better reported at compile level.

## Pitch
Describe the solution you'd like

Add a compile error when entry function returns some values.

Are you willing to open a pull request? (See [CONTRIBUTING](https://github.com/move-language/CONTRIBUTING.md))

Don't think I am capable of handle this error.

<sub>[APT-5](https://linear.app/aptoslabs/issue/APT-5/[feature-request]-add-a-compiler-error-if-entry-function-returns-any)</sub>

**Comment by SteMak** [comment]
As i understood from the community discord, it is not a feature, it is a bug and developers are working on to make returning values from blockchain transactions possible.
https://discord.com/channels/945856774056083548/946123778793029683/1029108132397453352

**Comment by gregnazario** [comment]
These are coming up in an upcoming release of the CLI (it might even be 1.0.3, I have to check)

```
aptos move compile --package-dir aptos-move/move-examples/hello_blockchain --named-addresses hello_blockchain=0x22
Compiling, may take a little while to download git dependencies...
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Examples
error: entry function cannot return values
   ┌─ aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move:28:5
   │  
28 │ ╭     public entry fun set_message(account: signer, message: string::String): string::String
29 │ │     acquires MessageHolder {
30 │ │         let account_addr = signer::address_of(&account);
31 │ │         if (!exists<MessageHolder>(account_addr)) {
   · │
45 │ │         message
46 │ │     }
   │ ╰─────^

{
  "Error": "Move compilation failed: extended checks failed"
}

```
