### ISSUE TITLE
[Feature Request] Remove U64 / U128 / etc. wrapper types from API

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2108]
These types existed to help clients understand the number types they were dealing with, but with an appropriate SDK, these aren't really necessary. In JS (the main reason we do it like this today) this would necessitate a customized `JSON.parse` function that uses BigInt.

This is a low pri item right now, since the current system works fine.

**Comment by gregnazario** [comment]
This is pretty standard at this point to use strings for U64 and greater in JS and others, as I've talked to other partners.  I'm closing this out
