### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by grassets-tech** [aptos-labs/aptos-core#2114]
**Issue statement:**
We have noticed significant Tx increase utilising full 1Gbs network bandwidth since the latest changes applied about 12 hours ago. RX packets 1882428703  bytes 5192380941113 (5.1 TB) --> IP 129.151.73.134 using wide range of ports.

The latest changes were to update to the image testnet_f5d8013b0a1851da8e078394d83130d3adaf7670 and setting the timeout to 2000ms. 

On diagram below you can see Tx increase at around 8:30 UTC+1

![image](https://user-images.githubusercontent.com/82155440/180096472-6fcefa38-96e0-4518-bd17-5501f3a912ad.png)

**Workaround solution:**
- close metric port 9101. 

On diagram below you can see Tx is back to normal at around 23:30 UTC+1

<img width="450" alt="Screenshot 2022-07-21 at 00 10 46" src="https://user-images.githubusercontent.com/82155440/180097951-5d451ca6-346e-4a1a-afef-4b4d0ef650c8.png">

**Comment by teenu4** [comment]
Hi! Please open this issue at https://github.com/aptos-labs/aptos-ait2
