### ISSUE TITLE
[Bug] - send Chain_Id with every telemetry message. 

### ISSUE THREAD

**Issue by pr-aptos** [aptos-labs/aptos-core#2118]
# 🐛 Bug

Currently only Aptos_node_build_information sends the chain_id at node startup. We have more than 10k devnet nodes also sending out telemetry. We need a quick way to filter out the telemetry messages for the selected chain. For that, we need to include chain id to every telemetry message. Currently, IP Address and Telemetry Token are added to every message. 

Reference - https://www.notion.so/aptoslabs/AIT2-Telemetry-Schema-e902d5155cfe49b78bf986251264f431

**Comment by gregnazario** [comment]
Does this still apply @pr-aptos
