### ISSUE TITLE
[Feature Request] Add doc builder to Aptos CLI

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#2142]
Presently, the `aptos` CLI does not support the kind of doc building that is included in the `move` CLI:

```
move build --doc
```

For users to generate module documentation without installing an additional command line tool, it is advised that the `aptos` CLI be updated to include doc building functionality - especially given that Aptos' version of Move tends to lag behind the official version. Should Aptos developers be unable to autogenerate markdown documentation files for their source code, it will become difficult for other developers to build protocols on top.

@gregnazario

**Comment by junkil-park** [comment]
I am planning to add this feature this after this PR (https://github.com/move-language/move/pull/291) lands. After the PR, Move CLI run the doc builder by the new subcommand `$ move docgen`.

@gregnazario, can we also have a similar subcommand in Aptos CLI like `$ aptos move docgen`?

**Comment by gregnazario** [comment]
Yeah, go ahead and add it as well to the aptos CLI

**Comment by alnoki** [comment]
Addressed by #5187
