### ISSUE TITLE
Make sure all DB APIs return proper error message when the content requested is out of the pruner window.

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#217]
This is part of https://github.com/aptos-labs/aptos-core/issues/103

1. Whenever possible, our error message should indicate that content is pruned.
2. When not possible (get_txn_by_hash), return None
3. APIs shouldn't panic on out-of-window queries
4. would be nice if we convert the DB interface to return AptDbError, so the tests can assert by error types. We can do something like `impl From<anyhow::Error> for AptDbError` and a `AptDbError::Misc(anyhow::Error)` so that not much needs to change.

**Comment by gregnazario** [comment]
Has this been cleaned up?

**Comment by msmouse** [comment]
I think we are in good shape with all the checks.
