### ISSUE TITLE
[Bug] Unmonitored Coin types have infinite mint potential

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#2188]
Per discussion with @hariria , who suggested tagging @davidiw 

Presently, it is possible to mint an infinite amount of `coin::Coin` that was initialized via `initialize()` with `monitor_supply` set to `false`, because the `mint()` only tracks overflow for coins having an optional `supply` field

**Comment by hariria** [comment]
@alnoki can you tag the code line / lines you're referring to

**Comment by davidiw** [comment]
This makes sense. Help me understand the concern? It seems if we want to prevent this, the only solution is to require all coins have a monitored supply?

**Comment by hariria** [comment]
Is there ever a case where you'd need more than two hundred eighty two decillion coins in circulation 😆 ?

**Comment by movekevin** [comment]
Yeah I'm not quite sure why this is a concern either - someone can make a wrapper type around coin and add custom supply limit.

**Comment by davidiw** [comment]
> Is there ever a case where you'd need more than two hundred eighty two decillion coins in circulation 😆 ?

wen universe

**Comment by alnoki** [comment]
Indeed it is impractical for an agent to mint to such hyper-inflated levels - this issue was opened because @hariria explicitly requested it, but it appears now that there is no concern on Aptos Labs' side.
