### ISSUE TITLE
[Feature Request] Add non-colliding serial ID move native function

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#2201]
@davidiw @wrwg @movekevin @gregnazario 

#1975 Proposes a move native function getter for the Aptos database version number of the current transaction, with the underlying motivation of assigning serial IDs to transactions in a way that does not result in Block-STM transaction collisions.

As @davidiw just mentioned in Move Monday, an integer aggregator (under development) may allow for this functionality to be implemented without referencing the version number. This would result in a separate serial ID generator for each namespace, accessible by a Move native function. This would provide the additional performance characteristic of allowing multiple non-colliding serial IDs to be administered within a single transaction, instead of just a single one.

**Comment by movekevin** [comment]
Thanks Alnoki. Do you have examples of the use cases for this feature? This is likely something that can be supported with aggregators as you pointed out. cc @georgemitenkov @gelash

**Comment by georgemitenkov** [comment]
Hey @alnoki! Can you give a bit more background about the feature and the use cases? At the moment I do not see how an aggregator helps here, especially if the ID is meant to be read frequently.

**Comment by alnoki** [comment]
@movekevin @georgemitenkov the primary use case is for an order book application where each order has an ID number that encodes a serial GUID: if two users place limit orders at different price levels, for example, in a way that does not change an order book tree or alter the min/max key in the tree, then these two operations could theoretically be parallelized if the GUID itself could be. Here, the ID would need to be read right after generation, inside the runtime (for insertion into a bid/ask tree).

**Comment by georgemitenkov** [comment]
Thanks, I see! So to make sure I get things right: each order is associated with a GUID, generated once and then read. Later, whenever there are limit orders the ID is incremented by each transaction, right? Also, do you have an estimate on 1) GUID bounds, e.g. if it’s below `u64::max` etc. 2)  how many different GUIDs you have in the system (like roughly)?

In general, aggregator should be used in absence of reads (or at least when the reads are not frequent) for any kind of arithmetic updates.

**Comment by alnoki** [comment]
@georgemitenkov you explanation seems right to me, for further context ill note that the order ID is simply price concatenated with the GUID. This way, an ask with price 1234 and GUID 678 has a higher price-time priority than an ask with the same price but GUID 789: `000...0001234000...000678` < `000...0001234000...000789` (for bids, it is the bitwise complement of GUID to preserve the > comparison).

1) GUID bounds would indeed be below `u64_max`.
2) A different GUID for each order book, so however many registered markets there are. I'll note that if parallelizing GUIDs is possible, however, we would probably switch to a GUID each for the ask and bids trees, so 2x the number of markets (because the two sides are parallelizable as well).

As far as algorithm flow goes, it is:

1. Get the next GUID.
2. Assign it to an order ID, combining with price.
3. Insert the order ID as the key in a tree.

Here, the idea is that insertions to different parts of the tree could parallelize.

**Comment by georgemitenkov** [comment]
Thanks for the further explanation. But it seems to me that you do read GUID in every transaction. When you assign it to an order ID, combining with price, you essentially do a read, right? In this case aggregators do not help, because they work hen you do not want to observe the change of the value but only want the value to be changed eventually.

**Comment by alnoki** [comment]
> Thanks for further explanation. But it seems to me that you do read GUID in every transaction. When you assign it to an order ID, combining with price, you essentially do a read, right? In this case aggregators do not help, because they work when you do not want to observe the change of the value but only want the value to be changed eventually.

@georgemitenkov your understanding here is correct, and hence it looks like aggregators don't provide a solution for the given use case. More generally, this use case (non-colliding serial ID) has a major difference from aggregators that there is no arithmetic: aggregators are typically used for summation, if I'm not mistaken, but a non-colliding serial ID would just be used for parallelizable GUID assignment. Your thoughts?

**Comment by georgemitenkov** [comment]
Precisely. With this use case I do not think there is a way to get rid of such a sequential dependency, at least at the moment. Each new GUID depends on the previous one, and transaction execution flow depends on that GUID (because it influences price-time priority as you mentioned above), and so cannot be parallelized.

**Comment by alnoki** [comment]
> Precisely. With this use case I do not think there is a way to get rid of such a sequential dependency, at least at the moment. Each new GUID depends on the previous one, and transaction execution flow depends on that GUID (because it influences price-time priority as you mentioned above), and so cannot be parallelized.

@georgemitenkov agreed that at least with the present GUID/aggregator architecture this kind of serial ID parallelism is not yet possible.

Hence this feature request!
