### ISSUE TITLE
Add `aptos config --set do-not-prompt` or something similar

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2205]
Currently the aptos CLI prompts you whenever you're doing something potentially risky. To avoid this you can pass `--assume-yes` but this gets old very fast for people who are used to CLIs just executing their commands without confirming. It'd be nice to have some way to set something in the config that effectively enables `--assume-yes` for every command.

**Comment by gregnazario** [comment]
This can be added to the global configuration to override this behavior

**Comment by nf0x** [comment]
Hello! Is this up for grabs? Sounds like a good first issue to get to know a bit of the project :)

**Comment by Nike682631** [comment]
@gregnazario Is this issue available to work on?

**Comment by gregnazario** [comment]
Yes, this is up for grabs.

**Comment by gregnazario** [comment]
It should do the following:

```
aptos config set-global-config --default-prompt-response yes
```

```
aptos config set-global-config --default-prompt-response no
```

Then everywhere that uses the `prompt-options` it should look this up and use it if it's set.

Probably should add an unset command later as well.

**Comment by gregnazario** [comment]
If you have a PR for it, please mention me in it, and I'll see if I have the time to look

**Comment by Nike682631** [comment]
@gregnazario  I don't have a pr yet. I'll be working on this. Can you assign me this issue so I could keep track of it?

**Comment by gregnazario** [comment]
I'm putting this back up for grabs

**Comment by fzgem18** [comment]
hey @gregnazario, I added some update on this issue, and created new PR #5614 . it's still in WIP.
for now, I have a few questions for the further work. It's my first contribution on Aptos, so hope your kindly review and honest feedback. thank you.

**Comment by banool** [comment]
The PR landed, thanks @fzgem18!
