### ISSUE TITLE
[VM] investigate VM error scheme on state fetch failure

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#221]
In benchmark runs, when I accidentally broke the proof format which should've resulted in an error from VerifiedStateView::get(), the VM discards transactions, which seemed not the right thing to do (Panicking might be a better choice here.)

Try to reproduce, investigate, and probably fix.

**Comment by benallamar** [comment]
@msmouse any chance this issue is still open ?

**Comment by benallamar** [comment]
Alright, so I understand that's good to work on this issue ?

**Comment by msmouse** [comment]
@benallamar

start by running this command (figure out other parameters you need to pass in)
`cargo run -p executor-bencmark -- create-db`
and inject the error from the position I posted above.

**Comment by gelash** [comment]
judging from just the description, if there is an unrecoverable situation observed during StateView read, we could (and probably should) panic right there. If we return an error, the most MoveVM can do is to abort the transaction (the least is to successfully return an error status), which indeed leads to skipping the rest of the block (including the one with error?). So probably should panicking inside the StateView? @zekun000 @msmouse am I getting this right?

**Comment by msmouse** [comment]
Guess you are suggesting we change the StateView interface to not to return a `Result<>`  but panic whenever there's underlying storage related error?  

That kinda sucks since a true remote state view (like one that talks with other nodes' storage over the net) can rightfully yield an error and some party needs to know how to recover from that (by retrying, retyring from another remote, etc.). Maybe the resolvers should panic on storage fetch errors instead, or we create a wrapper layer.
