### ISSUE TITLE
[storage] `Either::or` should take closures

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#222]
https://github.com/aptos-labs/aptos-core/blob/3ba9b4eec953fbe221a81580618494d7ccbe5f77/storage/scratchpad/src/sparse_merkle/utils.rs#L39

^ take closures so that parameter evaluation can be lazy, like here:
https://github.com/aptos-labs/aptos-core/blob/3ba9b4eec953fbe221a81580618494d7ccbe5f77/storage/scratchpad/src/sparse_merkle/updater.rs#L336

`cargo bench -p scratchpad --features bench` to run the criteron based benchmark (https://github.com/diem/diem/pull/8388) and see if there's performance regression.

**Comment by benallamar** [comment]
@msmouse is this issue always active ?

**Comment by msmouse** [comment]
Yes this is still nice to have, if that's what you meant. :) Thank you for considering to contribute.

**Comment by msmouse** [comment]
This one is a good one to start with.

**Comment by Nike682631** [comment]
@msmouse Is this issue available to work on?

**Comment by msmouse** [comment]
Yes please.  Thank you.

**Comment by Nike682631** [comment]
@msmouse please assign

**Comment by msmouse** [comment]
@Nike682631  here you go, thanks.

**Comment by msmouse** [comment]
closing due to low priority (and no significant benefit projected)
