### ISSUE TITLE
[storage] remove SparseMerkleTree::batches_update()

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#223]
Now that we are moving towards per-block SMT update, the batches_update interface is no longer useful.

**Comment by GrapeBaBa** [comment]
@msmouse can you assign it to me?

**Comment by GrapeBaBa** [comment]
@sitalkedia Using latest code, run `cargo xtest`, several test will failed. Is it expected?

**Comment by sitalkedia** [comment]
@GrapeBaBa  - That is not expected - can you point to tests that are failing and with relevant output?
