### ISSUE TITLE
[storage] Result of deserialization of the `AccountStateBlob` should be cached

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#225]
Result of deserialization of the `AccountStateBlob` should be cached, probably on the struct itself.

Otherwise even if a frequently used account is hit from a in-mem leaf node (from previous block), the deserialization is repeated:

https://github.com/aptos-labs/aptos-core/blob/3ba9b4eec953fbe221a81580618494d7ccbe5f77/storage/storage-interface/src/state_view.rs#L185

**Comment by davidiw** [comment]
Probably irrelevant now, eh?
