### ISSUE TITLE
[Bug] "account not found by address" when listing accounts

### ISSUE THREAD

**Issue by hubert-da** [aptos-labs/aptos-core#2254]
# 🐛 Bug

`aptos account list` returns `account not found by address` for a local testnet without a faucet.

## To reproduce

```
aptos node run-local-testnet
aptos init # skip the faucet and generate a new key
aptos account list
```

The same happens for a docker-based setup.

**Stack trace/error message**
```
{
  "Error": "API error: Request failed: RestError { code: 404, message: \"account not found by address(0xe5a698c0fa4cc41bcce4919f2debf1c17989415e57e67bb447b96086d864ee91) and ledger version(53)\", aptos_ledger_version: Some(U64(53)) }"
}
```

## Expected Behavior

A list of accounts is returned.

## System information

aptos 0.2.1
Debian 5.10.120-1 (2022-06-09) x86_64

**Comment by gregnazario** [comment]
The faucet can't be skipped locally as that's what actually creates the account in aptos init.

You can run `aptos node run-local-testnet --with-faucet` to have a faucet run side by side.

We could make it use the mint key from run-local-testnet to create the accounts which would be interesting.
