### ISSUE TITLE
[Feature Request] Support for Apple Silicon on Aptos CLI

### ISSUE THREAD

**Issue by Treawlony** [aptos-labs/aptos-core#2258]
# 🚀 Feature Request

Support for Aptos CLI for Apple Silicon

## Motivation

I use M1 apple :D

**Comment by davidiw** [comment]
I believe this is already the case, most of the team uses M1. Closing out for an update, please advise.

**Comment by Treawlony** [comment]
I can’t find where is the m1 version, do you have a link please?

**Comment by davidiw** [comment]
Indeed, we currently only support it for build it yourself.

**Comment by banool** [comment]
For future us, GitHub Actions runners don't support ARM macs, so we'd have to do some toolchain stuff beyond what we're doing now to make this work: https://github.com/actions/virtual-environments/issues/2187

**Comment by gregnazario** [comment]
M1 mac is currently supported only with the `cargo install` or running `cargo build`.

The process can't be automated today with github actions like we do for the other versions.

**Comment by gregnazario** [comment]
Actually, M1 mac (as far as I've tested) does work with the x86 mac version via compatibility built into MacOS, until they remove it of course.
