### ISSUE TITLE
[API][v1] Unify MIME types

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2275]
Currently we use a mix of mime types for BCS:
- `application/x-bcs`
- `application/x.aptos.signed_transaction+bcs`
- `application/x.aptos.output+bcs`

I think we should just cut over to using only the first one, I don't think it's necessary to signal more information with the content type.

**Comment by gregnazario** [comment]
There's one for input and one for output now, and we'll stick with it for now

**Comment by e99243506bigplay** [comment]
https://github.com/aptos-labs/aptos-core/blob/a34544ea6c9b41b9f2078fb7a7eae4078d4b6883/api/src/transactions.rs#L110-L112
:eyes: the todo comment still exists on this moment now.
