### ISSUE TITLE
[API][v1] Capture all possible response codes in the API

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2279]
Today, the spec generated from our API says that it can return the success and error codes defined by the success / error response structs used in its result. To clarify, an endpoint might be defined like this:
```
    async fn get_events_by_event_key(
        &self,
        accept: Accept,
        // TODO: https://github.com/aptos-labs/aptos-core/issues/2278
        event_key: Path<EventKey>,
        start: Query<Option<U64>>,
        limit: Query<Option<u16>>,
    ) -> BasicResultWith404<Vec<Event>> {
```
Where it can return 200 in the success case or 400, 404, or 500 in the failure case.

This is an accurate representation of what our own code does, indeed with the way we've done the types, it's impossible for our own code to return anything else than what we've said it can return. However, the framework is able to return more error types than what we say in our error struct, since those originate prior to our endpoint handler. Different endpoints could conceivably return quite a few extra codes, such as 405, 406, 411, 413, 415. We should find a way to include those in the spec too, and ideally we do it in a way that introduces the same strictness on typing that we have for our own code. As in, it should be impossible to return a 406 if the types used to generate the spec don't indicate that they could return a 406.

**Comment by gregnazario** [comment]
Handled now afaik
