### ISSUE TITLE
[Bug] `/transactions?limit=1` returns every transaction when there are few transactions

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2286]
```
$  curl http://localhost:8080/v1/transactions?limit=1 | jq '.[] | length'
18
```
This command output pretty much says it all. There is a bug somewhere in how we calculate limits (likely in `page.rs`) where if there are few transactions (I believe probably < than the default limit value), it ignores the limit field and just returns all of them.

Should be an easy fix.

**Comment by gregnazario** [comment]
This has been fixed
