### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kaushalkumarop** [aptos-labs/aptos-core#2300]
# 🐛 Bug
To report a security issue, please email security@aptoslabs.com.

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by CapCap** [comment]
Please edit the description of the issue or resubmit a new one with details :-)
