### ISSUE TITLE
[network] Support Load balanced Full Nodes

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#234]
# 🚀 Feature Request

Supporting a load balancer in front of multiple full nodes.  E.g. `/dns/load-balancer-name/tcp/6080/.../`.  
## Motivation

Right now full nodes have to be addressed individually. This would allow for an operator to scale greater with a single address and not have to distribute lists of addresses.

## Pitch

Allow for sharing an identity (a public key, peer id pair) over multiple nodes without conflicts:
* The mempool client makes assumptions about the status of the upstream
* Ambiguous on state sync
* Are there any other services that need investigation, e.g. state sync v2

**Comment by davidiw** [comment]
@gregnazario , this issue is a bit ambiguous on what the work to be done here. There's nothing on the software side that stops us except quirky things that will go wrong. Considering the nature of what can go wrong, it might be good to elaborate. I took a quick stab.

**Comment by davidiw** [comment]
also @JoshLind for any feedback on state sync v2

**Comment by JoshLind** [comment]
> also @JoshLind for any feedback on state sync v2

From the description above, I don't see any specific code concerns with state sync v2. Internally, the Aptos Data Client makes data requests. It works using peer id's provided by the networking layer (e.g., get all connected peers from `PeerMetadataStorage` and select one that can service this response). If the network will still expose this interface we should be okay.

Where things could go wrong practically is when the nodes that share the same peer id (behind the load balancer) have different internal states (e.g., they are behind by different versions, have different data available, etc.). If this is the case, it will lead to data retrieval failures and the peer may eventually be ignored for some time, e.g., imagine if node `X` says it has data that node `Y` doesn't then the Aptos Data Client may request data from `X` but the load balancer forwards it to `Y` and the request fails. From the point of view of the Aptos Data Client, this peer is behaving badly.

But other than those quirks, I don't see any big blockers here. We might just have to come up with a story for keeping all nodes behind a load balancer "in sync".

**Comment by JoshLind** [comment]
One thing that's not clear to me is how we handle outbound requests and we might have to reason about all the different applications in turn. For example, the simplest application is probably the health checker. From the client side, this is fine (the client health checker will ping any node behind the load balancer and get a response). But, what about the health checker living on each node behind the load balancer? Will they all share connections and ping the same peers? Or will they have different connections and the load balancer is expected to be stateful? This is something that still needs to be figured out.
