### ISSUE TITLE
[Bug] My First transaction tutorial no longer mints 1 million test coin

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#2345]
# 🐛 Bug

The faucet limits to 20k, but the example requests 1 million.  We need to update it to use less.

These 3 sections need to be updated to 20k from 1million, as the max the faucet will output in 1 call is 20k.
https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/examples/typescript/first_transaction.ts#L238
https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/examples/rust/first_transaction/src/main.rs#L19
https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/examples/python/first_transaction.py#L189

**Comment by davidiw** [comment]
These were run on a local testnet. The behavior is different depending on where you run it. I'm not sure this is a bug.

**Comment by wrwg** [comment]
I really do not understand why we do not create a release branch for devenet and let folks consume aptos-core from there. Some selected folks can still go to our main, but the default shouldn't. Am I missing something?

**Comment by gregnazario** [comment]
> These were run on a local testnet. The behavior is different depending on where you run it. I'm not sure this is a bug.

It's easier just to have a tutorial that matches in all places

**Comment by gregnazario** [comment]
> I really do not understand why we do not create a release branch for devenet and let folks consume aptos-core from there. Some selected folks can still go to our main, but the default shouldn't. Am I missing something?

We do have a devnet branch.  Let's talk Monday and I can explain it out to you.
