### ISSUE TITLE
Ensure generated changes to cached packages are checked in

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2348]
Currently it's possible to make changes but not regenerate and check in the cached code changes. We should lint against this in CI.

More details TBA.

**Comment by wrwg** [comment]
I'm working on this already. PR coming out today.

**Comment by banool** [comment]
For context here is how I'm doing it for the API: https://github.com/aptos-labs/aptos-core/pull/2317. Christian hasn't looked at this yet though, plus this is probably too simple for your use case.
