### ISSUE TITLE
[Bug] Generated go code isn't correct anymore

### ISSUE THREAD

**Issue by prasanna-anchorage** [aptos-labs/aptos-core#2366]
# 🐛 Bug

The instructions in this [PR](https://github.com/aptos-labs/aptos-core/pull/2170)  that was added to create the go bindings work anymore

## To reproduce

In the `aptos-move/framework` folder:

`cargo run`

In the `aptos-move/aptos-sdk-builder` folder:

```
cargo run -- --language go --module-name aptosstdlib --package-name testing --with-aptos-types "../../testsuite/generate-format/tests/staged/aptos.yaml" --target-source-dir examples/golang "../framework/aptos-framework/releases/artifacts/current"
```

```
cd examples/golang
go mod init testing
go mod edit -replace testing=`pwd`
go mod tidy
go run stdlib_demo.go
```

**Stack trace/error message**
```
# testing/aptosstdlib
aptosstdlib/lib.go:1310:28: byte.BcsDeserialize undefined (type byte has no field or method BcsDeserialize)
aptosstdlib/lib.go:2595:24: arg.BcsSerialize undefined (type [][]byte has no field or method BcsSerialize)
```

## Expected Behavior

No error, prints out the serialized payload

## System information

**Please complete the following information:**
-  aptos-core: main@ead6451dee3b4f10f800db9224e8f2715359b1f2
-  Rust version 1.61
-  Debian 10

**Comment by wrwg** [comment]
@davidiw can this be related to newer changes on sdk builder?

**Comment by davidiw** [comment]
Not on the sdk builder, but more on which entry points we're exposing. I have an block list in the go generator. At some point, we'll need to expand on our BCS serializer for Go. It is excessively simplistic and only supports the historical Move primitives allowed for script functions.

**Comment by davidiw** [comment]
I'm going to evaluate and send out a PR shortly...

**Comment by davidiw** [comment]
This is fixed on the main branch now.
