### ISSUE TITLE
[Devnet] Unable to connect to other fullnodes with static identity generated with Aptos CLI

### ISSUE THREAD

**Issue by xorgal** [aptos-labs/aptos-core#2372]
Have tried to generate keys with Aptos CLI v0.2.1 and v0.2.2 to assign static identity to fullnode using:
```
aptos key generate --key-type x25519 --output-file private-key.txt (default encoding is hex so this option was not provided)
```
```
aptos key extract-peer  --private-key-file private-key.txt  --output-file peer-info.yaml
```
Both private key and network address are being generated using above commands with no issues but problem starts when fullnode is trying to connect to other peers.

Errors in logs says: `Transport error: most probably fullnode rejected our handshake` with no any successful connections seen.

It works well with no identity set in fullnode.yaml (when fullnode generates new keys on each startup) -- works well.

Then, another attempt was creating keys with `aptos-operational-tool` using:
```
aptos-operational-tool generate-key \
    --encoding hex \
    --key-type x25519 \
    --key-file private-key.txt
```
then
```
aptos-operational-tool extract-peer-from-file \
    --encoding hex \
    --key-file private-key.txt \
    --output-file peer-info.yaml
```
and starting fullnode with those keys -- works with no issues.
No any errors in logs, 5 stable outbound connections right from start.

Fullnode image tag: `devnet_7296f138e11113fab6a1e193fc3f18fa7d08bd3e`

**Comment by gregnazario** [comment]
Interesting, I didn't notice this.  This code hasn't really changed so it probably still is an issue.

**Comment by gregnazario** [comment]
Looking into this now

**Comment by gregnazario** [comment]
Yes, verified that this is wrong.

It should match the public key, this is mostly a convenience function

```
$ cat extracted-peer 
---
95010bbf4006e60074b8ec2931d9ca89c63669f0a677ae841d1ea975bd6ddf2b:
  addresses: []
  keys:
    - "0x95010bbf4006e60074b8ec2931d9ca89c63669f0a677ae841d1ea975bd6ddf2b"
  role: Upstream
$ cat private-key.txt.pub 
9B4E7EC9B02811258B482BB3CA2038A828EC6E6ED27B0A186C01B0B5262BA17E
```

**Comment by gregnazario** [comment]
Verified, it's trying to parse an ed25519 key and not an x25519 key.  Will fix this up soon
