### ISSUE TITLE
Usage Documentation and Examples

### ISSUE THREAD

**Issue by sblockTest** [aptos-labs/aptos-core#2377]
# 🚀 Feature Request
Documentation and examples

## Motivation

I'm new to DAP development and would like to use the Aptos chrome plug in to create a collectable. It points me here for the metadata format but I don't know how to use it. 

## Pitch
This feature would help increase the user base

## Additional context

For the time being I'm looking for as simple of an example as possible.

**Comment by davidiw** [comment]
@hariria , @kent-white please advise.

**Comment by davidiw** [comment]
Could you please update, it just says "here"? The team is working on an updated guide to NFTs. The basic options are:

1) Specify on chain in the property map and have the uri pont to media
2) Do what you see in other chains by using the relatively standard off-chain metadata format that then points to media
