### ISSUE TITLE
[Bug] pre-commit error in dev setup

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#2404]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by gregnazario** [comment]
There's no information in this, so I'm closing
