### ISSUE TITLE
[Feature Request] Change indexer version and chain id types to u64

### ISSUE THREAD

**Issue by bowenyang007** [aptos-labs/aptos-core#2418]
Currently they're in i64, e.g. 
https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/indexer/src/models/processor_statuses.rs#L13

We should change them to u64.

**Comment by gregnazario** [comment]
@bowenyang007 was this completed?

**Comment by jjleng** [comment]
This is only about the changes in the indexer, right? Otherwise, it is a big breaking change.
