### ISSUE TITLE
[Feature Request] Make typescript SDK use dictionaries as params

### ISSUE THREAD

**Issue by hariria** [aptos-labs/aptos-core#2426]
# 🚀 Feature Request

Would be really great if the typescript SDK supported dictionaries as params for a lot of the client functions.

ie. currently [TokenClient](https://github.com/aptos-labs/aptos-core/blob/2c54f3ffeeffa0e900868aeb28567a0b21712ed5/ecosystem/typescript/sdk/src/token_client.ts) looks like so:

```typescript
export class TokenClient {
  aptosClient: AptosClient;
  ...
  async createCollection(
      account: AptosAccount,
      name: string,
      description: string,
      uri: string,
    ): Promise<Types.HexEncodedBytes> { ... }
}
```

The `createCollection` function accepts 4 params, 3 of which are strings which can easily be confused for each other if a user puts them in the wrong order.

```typescript
interface CreateCollectionParams {
  account: AptosAccount;
  name: string;
  description: string;
  uri: string;
}

export class TokenClient {
  aptosClient: AptosClient;
  ...
  async createCollection({
      account,
      name,
      description,
      uri,
    }): Promise<Types.HexEncodedBytes> { ... }
}
```

where params are passed as a dictionary rather than an ordered list of params

This is helpful for the following reasons
1. If params are re-ordered in the future or removed or changed in any way, you don't need to worry about potential breaking changes due to the ordering changing (you will still need to be vigilant for breaking changes caused by removing or changing the parameter types)
2. Unlikely for users to mess up function parameter ordering since the parameters are now explicit

I've tagged @zacharydenton for any additional ideas on how we could improve the SDK for people

**Comment by banool** [comment]
Yeah this is a good idea, I made a mistake like this just today.

Note that the new client generator we're using in the SDK supports generating stubs that take in a dict instead of positional args, but we wrap the generated client right now so it doesn't help so much. Could be good inspiration / practice though.

**Comment by jjleng** [comment]
Sounds good. @banool is working on consolidating the APIs and client wrappers.

**Comment by gregnazario** [comment]
Did we do this @banool?
