### ISSUE TITLE
[TS SDK] Add back the multi-agent transaction example

### ISSUE THREAD

**Issue by jjleng** [aptos-labs/aptos-core#2431]
# 🚀 Feature Request

Add back the multi-agent transaction example to show people how multi-agent transactions can be submitted.

**Comment by banool** [comment]
I've got this currently in the v1 SDK but skipped, since it doesn't work right now.

Also I'm sad I missed this one, but we shouldn't let people just delete tests. We'll keep a closer eye on it.
