### ISSUE TITLE
build: avoid retriggering builds whenever the git sha1 changes

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#2436]
Currently we use shadow-rs to pull in build information.
As discussed in https://aptos-org.slack.com/archives/C034T4ZQ8DB/p1659397187648129?thread_ts=1659327216.600669&cid=C034T4ZQ8DB this currently triggers frequent cache invalidations of both the local cargo cache and when building in docker.
Let's refactor this to avoid this, for _example_ by:
- pull in shadow-rs only in some top level entry points (like `main.rs` of bins) instead of the widely used telemetry crate
- add ability to pass in information as environment variable _after_ the binary as been built to avoid docker layer cache invalidation
- others (as discussed in slack).

**Comment by gregnazario** [comment]
This was removed, and then re-added because this information was needed.  I haven't seen any particular com0plaints about the build performance recently

**Comment by ibalajiarun** [comment]
Closing this issue as completed. Let's open another issue if we find any degradations in the future.
