### ISSUE TITLE
[Bug] Bad Interpreter error on windows

### ISSUE THREAD

**Issue by 2manslkh** [aptos-labs/aptos-core#2438]
# 🐛 Bug

Getting `/bin/bash^M: bad interpreter: No such file or directory` when running ./scripts/dev_setup.sh on Windows WSL 2

## To reproduce

**Code snippet to reproduce**
```bash
./scripts/dev_setup.sh
```

**Stack trace/error message**
```bash
/bin/bash^M: bad interpreter: No such file or directory
```

## Expected Behavior

` ./scripts/dev_setup.sh` should run normally

## System information

**Please complete the following information:**
- Computer OS 
  - Windows 11, WSL2

### Solution

https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter

`sed -i -e 's/\r$//' scripts/dev_setup.sh`

**Comment by gregnazario** [comment]
I did have to do a bunch to get windows working, but are you still having issues?

I recently fixed some windows build issues, but I don't think I checked the dev setup script https://github.com/aptos-labs/aptos-core/pull/3751

**Comment by 2manslkh** [comment]
The solution I found worked for me
