### ISSUE TITLE
Submit transaction failed with "Transaction already in mempool with different payload"

### ISSUE THREAD

**Issue by passer-byzhang** [aptos-labs/aptos-core#2439]
## ❓ Questions and Help

I'm trying to submit a transaction in my local testnet but it fialed with `{"code":400,"message":"transaction is rejected: InvalidUpdate - Transaction already in mempool with different payload"} `
It happens on that I had created a collection and wanted to create a token.
When I submitted the "create_token" transaction , it seems like the last transaction(create_collection) was still in mempool.
How can I check the previous transaction to compare with the submitting one?
Thanks a lot.

**Comment by banool** [comment]
The likely reason you're running into this is your second transaction uses the same sequence number as the first. Could you share the code you're using that is producing this error? If you're using one of our SDKs, this might be an issue on our side.

**Comment by passer-byzhang** [comment]
I was tring to implement this example  https://aptos.dev/tutorials/your-first-nft in rust and reused the function related to transactions  in https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/examples/rust/first_transaction/src/lib.rs .
The TypeScript/Python examples  would not have this error.
My current approach is to sleep the thread for two seconds after each transaction and it works.
So I assume that is due to my program is serial.
the code is in https://github.com/passer-byzhang/aptos-core/blob/test/developer-docs-site/static/examples/rust/first_nft/src/main.rs
Thanks for your reply!

**Comment by passer-byzhang** [comment]
I was tring to implement this example  https://aptos.dev/tutorials/your-first-nft in rust and reused the function related to transactions  in https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/examples/rust/first_transaction/src/lib.rs .
The TypeScript/Python examples  would not have this error.
My current approach is to sleep the thread for two seconds after each transaction and it works.
So I assume that is due to my program is serial.
the code is in https://github.com/passer-byzhang/aptos-core/blob/test/developer-docs-site/static/examples/rust/first_nft/src/main.rs
Thanks for your reply!

**Comment by passer-byzhang** [comment]
I had sloved it by checking the transaction is on chain already or not,Thanks a lot

**Comment by passer-byzhang** [comment]
I had sloved it by checking the transaction is on chain already or not,Thanks a lot
