### ISSUE TITLE
[Bug] Aptos TS/JS SDK calls the getAccountResources method to return a problem, the first 0 of the address is omitted.

### ISSUE THREAD

**Issue by cryptosunshine** [aptos-labs/aptos-core#2440]
# 🐛 Bug

## To reproduce Typescript

**Code snippet to reproduce**
```rust
# const client = new AptosClient('https://fullnode.devnet.aptoslabs.com');
# const address = "0x0ed74576610ef9dcc5a89b9aee9203fa31ca28189f34591406dbce556a6e5aae"
# client.getAccountResources(address).then(result)
```

**Stack trace/error message**
```
...
4: {type: '0xed74576610ef9dcc5a89b9aee9203fa31ca28189f34591406dbce556a6e5aae::Message::MessageHolder', data: {…}
```

## Expect to return

```
...
4: {type: '0x0ed74576610ef9dcc5a89b9aee9203fa31ca28189f34591406dbce556a6e5aae::Message::MessageHolder', data: {…}
```

## Question
In the address in the type,0 is missing during base conversion.

## Supplementary question.

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/11716310/182797689-487a6b30-8c45-44da-9f9b-c6a9d4888c6e.png">

**Comment by jjleng** [comment]
Thanks for reporting. @banool, API returns the address with the leading 0 missing.

**Comment by banool** [comment]
I'll take a look, though this might be expected behaviour. Confusingly one of these trims zeroes while the other doesn't. I can audit this in the new API and make it work the same. Stay posted.

**Comment by banool** [comment]
Note, this behavior comes straight from the Move layer.

**Comment by gregnazario** [comment]
This comes straight from the Move layer.

Struct names, function names, and other identifiers use a short str approach which trims the leading 0s

**Comment by davidiw** [comment]
I think whatever we have is going to be in a quirky state for a long time... but we should probably have a longer term tracking issue to identify where 0 is truncated....
