### ISSUE TITLE
Benchmark performance with 1k nodes

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#250]
We'd like to benchmark with 1k nodes cluster for performance and see if there's any low hanging fruit we can optimize. Especially on consensus critical path.

Potential optimization we could do:
- support compression for network messages
- parallelize signature verification
- make message verification async

**Comment by JoshLind** [comment]
@zekun000, to clarify: this is a fully-connected validator set of size 1000? Or are you thinking of something else?

**Comment by zekun000** [comment]
@JoshLind yeah it's for fully-connected 1k nodes
