### ISSUE TITLE
[vm] adapter features

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#252]
there're a few features we'd want to land on adapter side to better support aptos framework:
- remove hard code error code and use errmap instead for prologue https://github.com/aptos-labs/aptos-core/issues/274
- move more rust logic into aptos framework and make vm more agnostic to business logic e.g. some gas check is done in rust. https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/aptos-move/aptos-vm/src/aptos_vm_impl.rs#L153 but some is done in the prologue. https://github.com/aptos-labs/aptos-core/blob/550688d66597e35d40147d1520570df050bcd6f3/aptos-move/framework/aptos-framework/sources/AptosAccount.move#L241
- support module publishing strategies https://github.com/aptos-labs/aptos-core/issues/275
- support native map

**Comment by davidiw** [comment]
Nice, could you elaborate on 2 and 3?

**Comment by zekun000** [comment]
@sitalkedia thanks! will update with more details and split into individual issues
