### ISSUE TITLE
How to execute transactions with concurrent requests

### ISSUE THREAD

**Issue by alphabiz-se2** [aptos-labs/aptos-core#2523]
I try to execute transaction with concurrent request, but it keeps getting error like below

- `Waiting for transaction 0x69e9d766a9f1663b021cba4d566e577af690592862eb92549cb72308cd2403f5 timed out!`

- `Bad Request - {"code":400,"message":"invalid transaction: SEQUENCE_NUMBER_TOO_OLD"}`

- `Bad Request - {"code":400,"message":"transaction is rejected: InvalidUpdate - Transaction already in mempool with different payload"}`

<img width="1369" alt="0" src="https://user-images.githubusercontent.com/86668439/182828784-aa8def92-570f-4721-bc01-cf5d893fd265.png">

<img width="1121" alt="1 5" src="https://user-images.githubusercontent.com/86668439/182828789-58e9db16-d4f7-4192-9c15-c08365a96efe.png">

<img width="1634" alt="1" src="https://user-images.githubusercontent.com/86668439/182976237-e034ca8e-8da6-416c-bee3-74c9969df02e.png">

**Comment by davidiw** [comment]
Please make sure they use distinct sequence numbers. Each transaction must have a distinct number and they must be sent in order or they may be rejected. Gonna close this but note that our documentation needs work to improve this. @rajkaramchedu
