### ISSUE TITLE
mempool enhancement

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#254]
- Issue #79: need to figure out a way to populate transactions that are discarded during execution back to fullnode.
- more efficient dissemination with more nodes
- leverage proof of availability from DAG protocols

**Comment by sitalkedia** [comment]
>> need to figure out a way to populate transactions that are discarded during execution back to fullnode.

Can you clarify this, if we want to notify all the fullnodes or just the fullnode where this transaction was received?

**Comment by zekun000** [comment]
@sitalkedia good question! the intention is to remove this txn from nodes that hold it so this txn won't be sent to validators again. 

we can alternatively have a negative cache of recent discarded txn on validators and only notify back when receive those txn again

**Comment by zekun000** [comment]
it's easy when we only have addition, it'd get tricky when we have both addition and deletion due to the race conditions. imagine one node deletes it and receive a broadcast to add it back.

the problem is discarded status is not persisted unlike committed, so it may get re-entered and eventually alive in all nodes.

**Comment by sitalkedia** [comment]
@zekun000 - Thanks for the explanation. IIUC, we also have a periodic GC to get rid of expired txns - do you know why that will not help in this case?

**Comment by zekun000** [comment]
GC indeed helps but system GC period can't be too short (it's 10 mins currently). txn expiration time is user specified and can be arbitrary long, it's not ideal if txn is stuck for min(10mins, specified expiration time)

**Comment by davidiw** [comment]
> need to figure out a way to populate transactions that are discarded during execution back to fullnode.

Let's bring this back to the original issue #79. But I have some thoughts!

**Comment by ahmed1107** [comment]
> > need to figure out a way to populate transactions that are discarded during execution back to fullnode.
> 
> Let's bring this back to the original issue #79. But I have some thoughts!

Do share please
