### ISSUE TITLE
Delete Scripts from the Repo

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#256]
Legacy code used Scripts to perform operations on the VM. Scripts are awesome in that you can perform complex operations in a single transaction. Scripts are not user friendly in that they required users to write and compile move snippets to even do trivial things like P2P transactions. The team then introduced Script Functions to complement Scripts to cover the common use cases. Script Functions are how many other blockchains works, where a transaction indicates a function and a set of parameters to be executed by the VM. As part of our migration to 32-bytes and to Aptos-Framework, we have a lot of (potentially) useful tests that depend on Script Functions, let's port them over and delete the DPN Scripts:

* Cleanup framework code on scripts (aptos-move/framework/*/*/legacy
* Review aptos-move/e2e-testsuite
* Identify other uses of script( and clean that up

**Comment by areshand** [comment]
-[ ] transaction failed as expected. however, the VM status is not explained "Failed to deserialize static error descriptions: NonCanonicalMap'" [test link](https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/api/src/tests/transactions_test.rs#L1376)

**Comment by areshand** [comment]
all need to do script to script function migration.

**Comment by areshand** [comment]
directly comparing on exp is too flaky [test](https://github.com/aptos-labs/aptos-core/blob/212bb55f9b1a487b1f83a4c3880b9f73c0f98d40/aptos-move/aptos-transactional-test-harness/tests/diem_test_harness/example.exp#L1-L0)
