### ISSUE TITLE
v1/spec hex value shows in exp format

### ISSUE THREAD

**Issue by olton** [aptos-labs/aptos-core#2562]
# 🐛 Bug

in all examples on the v1/spec hex values (address, ...) shown in exponential form `6.195948399647823e+76` instead of `0x12346...`

**Comment by banool** [comment]
Example demonstrating the issue: http://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account.

**Comment by banool** [comment]
As a guess, if I change `format` from `hex` it'll fix it. I'll experiment with that.

**Comment by banool** [comment]
Okay removing `hex` didn't work. I'll keep checking.

**Comment by banool** [comment]
Alright looks like we need to wrap the value in the example field in `"`, I'll make that happen.

**Comment by banool** [comment]
Fix is landing, thanks for discovering this issue @olton!
