### ISSUE TITLE
Ensure the NHC configuration examples are compatible with NHC

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2573]
Currently the NHC configuration examples are written by hand. This means if NHC gets updated, or one of its components, e.g. the txn-emitter, the configuration could become invalid. We saw this here, where a new flag got added but the configuration examples didn't get updated: https://github.com/aptos-labs/aptos-core/issues/2564.

This should be guaranteed in CI.

**Comment by sitalkedia** [comment]
@banool - Thanks for capturing this issue - do we not have any tests for the NHC to catch this currently?

**Comment by banool** [comment]
Yeah no tests today.
