### ISSUE TITLE
Migrate TokenClient to BCS based interaction

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2588]
Currently the TokenClient in the TS SDK interacts with the API via JSON. This is less performant than using BCS, so we should cut over.

As part of this, make sure to use the appropriate BCS representation for string arguments given to move module script functions, as they have recently changed to the explicit string type. In short, we shouldn't be hex encoding the strings anymore.

**Comment by jjleng** [comment]
Addressed with https://github.com/aptos-labs/aptos-core/pull/2596.
