### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lingxiyang** [aptos-labs/aptos-core#2614]
when  I  run the  command:
aptos move publish --package-dir /home/lansane/aptos/aptos-core/aptos-move/move-examples/hello_blockchain  --named-addresses HelloBlockchain=624cee55f5e051cf166b6934b69b3bc0c1766c5306b6da974020c75806970b8a
{
  "Error": "API error: error decoding response body: invalid type: string \"3\", expected u64 at line 1 column 26"
}

aptos cli version:0.2.2

**Comment by davidiw** [comment]
Probably need to update to 0.2.3. Closing out, please feel free to re-open if issue persists.

**Comment by lingxiyang** [comment]
yes, I upgrade to 0.2.3,it's ok
