### ISSUE TITLE
[Bug] Aptos CLI in combination with package systems messes paths up

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#2628]
# 🐛 Bug

## To reproduce

Consider a tree  as such

```
parent
   pack
      Move.toml
      sources
         ...
```

Now, if you do

```
> cd parent
> aptos move publish --package-dir pack
{
  "Error": "Error accessing 'pack/pack/sources/hello.move': No such file or directory (os error 2)"
}
```

Notice the `pack\pack` in the pass. I remember roughly that one possible cause could be that the package system messes around with the (global) processes current dir, so perhaps this is a lead.

Notice that one can also not `cd pack` because aptos then doesn't find the `config.yaml` (which really should search up the tree). The workaround is 

```
> aptos move publish --package-dir $PWD/pack 

```

**Comment by wrwg** [comment]
This is actually a bug in the new publish CLI code, removing @gregnazario as assignee.

**Comment by gregnazario** [comment]
Still an issue @wrwg ?
