### ISSUE TITLE
[Feature Request] REST operations which return lists of resources should include a type tag

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#2629]
# 🚀 Feature Request

When one calls `aptos account list`, or in other cases where the REST APIs return sequences of resources, no information about resource types is included. For example, this is a list of an account which contains both an `Account` and a `PackageRegistry`:

```
  "Result": [
    {
      "packages": [
        {
          "name": "test",
          "manifest": "[package]\nname = \"test\"\nversion = \"0.0.0\"\n\n[dependencies]\n#AptosFramework = { local = \"../../../../framework/aptos-framework\" }\n",
          ...
        }
      ]
    },
    {
      "coin": {
        "value": "99999975"
      },
      "deposit_events": {
         ...
       }
    }
  ]
```

Over time it will be very common to have many resources under one account. We should include the struct tag as an additional field in this JSON object.

Not sure where to route this, @banool @jjleng @davidiw  @gregnazario

**Comment by gregnazario** [comment]
This was fixed!
