### ISSUE TITLE
[Bug] Devnet fullnode /transactions/by_hash not working

### ISSUE THREAD

**Issue by kyleqian** [aptos-labs/aptos-core#2643]
# 🐛 Bug

Devnet `https://fullnode.devnet.aptoslabs.com/transactions/by_hash/{HASH}` is always returning 404. This causes `waitFroTransaction` to always fail and timeout in the TS SDK. I've verified that my transactions are getting picked up in the explorer.

**Comment by davidiw** [comment]
Should be v1

https://fullnode.devnet.aptoslabs.com/v1

lemme know how you're specifying your destination and why you picked that, so we can update documentation.

**Comment by gregnazario** [comment]
I think this might have to do with the new SDK, it builds that URL, but maybe doesn't specify v1 as the url.

**Comment by kyleqian** [comment]
Gotcha, changing the URL worked. It wasn't updated in https://aptos.dev/tutorials/your-first-dapp, which is where I was copying from.

**Comment by davidiw** [comment]
awesome, updated, thanks!
