### ISSUE TITLE
 "Error": "Unexpected error: missing field `recurring_lockup_duration_secs` at line 2 column 9"

### ISSUE THREAD

**Issue by pupudaye** [aptos-labs/aptos-core#2649]
aptos genesis generate-genesis --local-repository-dir ~/$WORKSPACE --output-di
r ~/$WORKSPACE

{
  "Error": "Unexpected error: missing field `recurring_lockup_duration_secs` at line 2 column 9"
}

**Comment by pupudaye** [comment]
Have you encountered this problem and what is the cause?

**Comment by stefiix92** [comment]
Also happened to me, I'm using 0.2.3 aptos-cli and 0.2.0 aptos-framework version. When I add the mentioned key to the `layout.yaml` I got 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PartialVMError { major_status: MALFORMED, sub_status: None, message: Some("Invalid visibility byte"), exec_state: None, indices: [], offsets: [] }', aptos-move/vm-genesis/src/lib.rs:99:64
```

**Comment by anythink-wx** [comment]
Also happened to me

**Comment by sainteye** [comment]
Also happened to me. I am using `aptos-cli 0.2.3` and `aptos-framework-v0.2.0`.

Command:
```
aptos genesis generate-genesis \
    --local-repository-dir ~/$WORKSPACE \
    --output-dir ~/$WORKSPACE
```
Output:
```
{
  "Error": "Unexpected error: missing field `recurring_lockup_duration_secs` at line 2 column 9"
}
```

**Comment by sainteye** [comment]
@stefiix92 
I think the error is caused by the mismatch of aptos-cli and aptos-framework version. We should use 0.2.0 for both of them.

**Comment by stefiix92** [comment]
Wasn't [aptos-cli 0.2.0](https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-0.2.0) released only for `AIT2` purposes? I guess now we aim `AIT3`. Or maybe it does not matter, idk...

**Comment by sainteye** [comment]
Yes. I guess we should wait for `AIT3` document and new aptos-framework.

**Comment by gregnazario** [comment]
This looks like it's due to a version mismatch, the newest CLI shouldn't have this issue anymore.  Feel free to reopen if you're still having issues / provide new details
