### ISSUE TITLE
Compiler warning testnet branch

### ISSUE THREAD

**Issue by dzovani** [aptos-labs/aptos-core#2654]
~/testnet/aptos-core$ cargo build -p aptos-node --release 
warning: field is never read: `author`
   --> consensus/src/liveness/leader_reputation.rs:327:5
    |
327 |     author: Author,
    |     ^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field is never read: `author`
   --> consensus/src/liveness/leader_reputation.rs:396:5
    |
396 |     author: Author,
    |     ^^^^^^^^^^^^^^

warning: `consensus` (lib) generated 2 warnings
    Finished release [optimized + debuginfo] target(s) in 0.31s

**Comment by gregnazario** [comment]
I believe this error is gone now
