### ISSUE TITLE
[API] Restructure Transaction response so common fields are always available

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2658]
Currently [Transaction](https://github.com/aptos-labs/aptos-core/blob/main/api/doc/v1/spec.yaml#L2344) is a union of different variants of transactions. We know however that all of these variants have some common fields, e.g. `success` in some cases, for example when reading an on-chain transaction (though in this case, we'd need two enums, one with PendingTransaction and one without). We should restructure the code such that there is a top level struct with these common fields, and then have the dissimilar variants be a field within that top level struct. That way you don't have to do something like this:
```ts
(transaction as any).success
```
But can instead just do this:
```
transaction.success
```

**Comment by Nike682631** [comment]
@banool Is this issue available to work on?
