### ISSUE TITLE
[Bug]The python examples didn't match the tags in your-first-nft doc

### ISSUE THREAD

**Issue by ChengYueJia** [aptos-labs/aptos-core#2691]
# 🐛 Bug

## Steps to reproduce

When I visit your first-nft, I wanna to  see some python or rust demo.
When I choose the Python tag, it shows the typescript info and link for me.

** Error message or problem **
<img width="777" alt="image" src="https://user-images.githubusercontent.com/108982045/183595239-8b393e4f-8b7b-4e1d-a667-3aa5ec07998d.png">

## Expected Behavior

The examples match the languages Tag.

## Additional context

Here Is docs link https://aptos.dev/tutorials/your-first-nft/#tokens

**Comment by jjleng** [comment]
Resolved
