### ISSUE TITLE
Build failed devnet branch

### ISSUE THREAD

**Issue by dzovani** [aptos-labs/aptos-core#2695]
~/aptos-fullnode-source/aptos-core$ cargo run -p aptos-node --release -- -f /home/adminko/aptos-fullnode-source/fullnode.yaml

   Compiling vm-validator v0.1.0 (/home/adminko/aptos-fullnode-source/aptos-core/vm-validator)
   Compiling state-sync-v1 v0.1.0 (/home/adminko/aptos-fullnode-source/aptos-core/state-sync/state-sync-v1)
   Compiling aptos-mempool v0.1.0 (/home/adminko/aptos-fullnode-source/aptos-core/mempool)
error[E0599]: no method named `get_startup_info` found for struct `Arc<(dyn DbReader + 'static)>` in the current scope
  --> state-sync/state-sync-v1/src/executor_proxy.rs:77:41
   |
77 |         let storage_info = self.storage.get_startup_info().map_err(|error| {
   |                                         ^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `get_table_info`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `state-sync-v1` due to previous error
warning: build failed, waiting for other jobs to finish...
adminko@adminkserver:~/aptos-fullnode-source/aptos-core$

**Comment by davidiw** [comment]
closing as likely stale, please feel free to reopen.
