### ISSUE TITLE
[VM] proper prologue error report

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#274]
Prologue is used to validate if the txn is good for execution, including checking sequence number, gas deposit, auth key etc.  https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/aptos-move/aptos-vm/src/aptos_vm.rs#L815

Failed checks are move-abort, but the error is translated to [DiscardedVMStatus](https://github.com/diem/move/blob/ebca3d587df239939f5a363f24021f544d3bf7f2/language/move-core/types/src/vm_status.rs#L95) in https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/aptos-move/aptos-vm/src/errors.rs#L44

DiscardedVMStatus is an enum of [hard-coded error code](https://github.com/diem/move/blob/ebca3d587df239939f5a363f24021f544d3bf7f2/language/move-core/types/src/vm_status.rs#L415).

The reason we do the conversion is because move-abort is supposed to charge gas and persist but move-abort in prologue is going to be discarded. `keep_or_discard` function is [here](https://github.com/diem/move/blob/ebca3d587df239939f5a363f24021f544d3bf7f2/language/move-core/types/src/vm_status.rs#L153).

We'd like a better way to report the prologue errors to users to provide flexibility on customized prologue errors instead of changing the move status code.

**Comment by davidiw** [comment]
@areshand, I believe this is done?
