### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by K-Pomian** [aptos-labs/aptos-core#2745]
# 🐛 Bug

`get_event_handle_counter` test function has been removed from `event` module. It probably has been removed accidentally during Move refactoring a few weeks ago. I don't see any reason to remove a function created purely for unit testing purpose.

## To reproduce

N/A

**Stack trace/error message**

N/A

## Expected Behavior

Undo removal of the function.

## System information

**Please complete the following information:**

aptos-cli: v0.2.3
rust: N/A
os: N/A

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/event.move#L45

seems this was renamed for prod use.
