### ISSUE TITLE
[Bug]Figure 1.0  in Lifecycle of a transaction is wrong.

### ISSUE THREAD

**Issue by ChengYueJia** [aptos-labs/aptos-core#2752]
# 🐛 Bug
The steps in the figure 1.0 doesn't match the descriptions of steps.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/108982045/183896911-44e70cf5-9be5-442d-978c-ef942f6eeaea.png">
[figure 1.0](https://user-images.githubusercontent.com/108982045/183896911-44e70cf5-9be5-442d-978c-ef942f6eeaea.png)

** Error message or problem **
I'll explain in an example: 

the flow of step 3 is Mempool → Virtual Machine (VM)  in the description.
however, the step in figure doesn't match the description.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/108982045/183897273-8d7f13bc-ecde-41f9-8ef1-6f54c2099f3f.png">

## Expected Behavior

I hope the docs is updated, the figures should not be left.

## Additional context

Here is the docs link
https://aptos.dev/guides/basics-life-of-txn#accepting-the-transaction

**Comment by rajkaramchedu** [comment]
Thanks, @ChengYueJia, I will take a look.

**Comment by davidiw** [comment]
The graphics are in dire need of attention, we're going to just replace them all sometime in the near future.

Reading this, the only thing that might be improved is moving the #3 to the line between mempool and vm.

thanks for the callout.
