### ISSUE TITLE
[SDK] Test against local testnet by default

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#2767]
For all the SDKs we maintain (TS, Rust, Python right now), we uphold these guarantees:
- SDK on commit X is compatible with node on commit X
- SDK published to npmjs is compatible with devnet

The problem is it's currently too easy to mix and match these, e.g. use an SDK from main with devnet.

When you're developing the SDK, you're generally working with the first of these two, so we should configure the tests for that.

Some changes to make:
1. Change the default URLs from devnet to localhost.
2. Use wait-port or some equivalent to make sure that the local testnet is up. If it's not (e.g. the user forgot) give them a very clear error saying something like this:

```
The SDK tests expect to run a local testnet by default, but it seems there isn't a local testnet running. Try one of the following:

Option 1: Start a local testnet:

cd ~/aptos-core
cargo run -p aptos -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes


Option 2: Configure the SDK to run against devnet:

cd ~/aptos-core/ecosystem/typescript/sdk
echo 'APTOS_NODE_URL="http://127.0.0.1:8080/v1' >> .env
echo 'APTOS_FAUCET_URL="http://127.0.0.1:8081' >> .env

Note, the SDK on any given commit is not guaranteed to work against devnet, so prefer to use Option 1 where possible.
```

**Comment by banool** [comment]
Potentially we could also add a new option to package.json that runs a local testnet for you too.

**Comment by gregnazario** [comment]
Does this use the local testnet now?

**Comment by banool** [comment]
Yep this is done.
