### ISSUE TITLE
Devex tooling

### ISSUE THREAD

**Issue by magnum6actual** [aptos-labs/aptos-core#278]
First impressions last. The perception of a dev coming into a new platform is shaped by how much time they to spend figuring out just how to get started vs being able to jump straight into code.  I've got some initial thoughts on tooling to make that onboarding devex more painless.  I'm approaching this from the view point of a developer who is going to build applications on top of Aptos (as opposed to someone who would meaningfully contribute to actual Aptos coding/development). There are a handful of things that can be done relatively quickly to speed the process of 0 to 1 for a new Aptos dev.

- A page on aptos.dev that provides guidance on basic IDE setup, e.g. links to VC Code/Intellij plugins with maybe a sentence or two on each one in terms of utility, is it a candidate for longer term support/development, etc.  Guidance on setting up IDE for debugging.

- Another page with quick links to relevant references.  There's some good material out there (move-book.com, https://diem.github.io/move/introduction.html, etc). Some of it is linked to currently, but it's buried in pages.  Having it all referenced in one prominent location would be helpful.

- In addition to the tutorial on running a local testnet, we need a tutorial on running a local faucet. At the bottom of the testnet tutorial page is a line that says, "It is important to note, that this solution does not include a Faucet. That is left as an exercise to the reader."  That's likely a punt from Diem that carried over, but I don't really want homework and there's not a lot of utility of blindly struggling through the faucet setup (which I am struggling with right now with INVALID_AUTH errors).  Local testnet is fairly useless without coin to pay gas fees.

- Some kind of debug support is critical.  I've got no way of knowing what's going on in code right now other than elaborate unit tests and waiting for errors or unexpected outcomes.  There is reference to Std::Debug in the code with a Debug::print function, but it doesn't seem to be implemented.  Not sure where the debug::print output would even show up - but assuming maybe it would hit the console in a local testnet?  

- Related, it would be great to have the ability to do a real debug session in VS Code with breakpoints, REPL, watches, etc. Implementing something like that is way beyond my domain knowledge, but that seems like a heavy lift.  Still very important, but that's probably a longer term item.

- Command line tools for basic things like account creation, compiling & publishing modules, faucet access, init a project shell, etc.  I've seen some references to CLI in the various repositories, but it's unclear as to whether or not those will be actively supported.

- The "will they be supported" comment applies broadly to the various things scattered throughout the Aptos repository. I'd prioritize an effort to separate things that are likely going away (#81 #83 and #183 address this partly).

- In advance of (or in addition to) the CLI, a reference repository with a shell of a project ready for development with the main.rs and move_unit_tests.rs files (and perhaps some explanation about their role in lining to .move files). Ideally, that would include tasks/scripts for compiling and deploying.

- Library packages/SDK (e.g npm and equivalents) of basic utility code (everything in first_transaction.(ts | py | rs) would be a good start.

Those are the thoughts I've had to date. Will add more here as I come up with additional bright ideas.

**Comment by davidiw** [comment]
Closing this out cause it is buried. Still ongoing efforts for better move tooling :)
