### ISSUE TITLE
[Feature Request] Add `aptos move fetch` as a wrapper to `move-cli build --fetch-deps-only`

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#2796]
# 🚀 Feature Request

Add a wrapper `move fetch` command to fetch git dependencies from the internet. 

## Motivation
This feature is required for the proper project initialization in the IDEs. It needs a source code of the dependencies to index the project. Now one have to call `aptos move compile` which changes the state of the project and can fail.

**Comment by wrwg** [comment]
It would probably be also fine if we add a flag to `move compile`, right? Want to keep the command set small because it surely will grow heavily over time.

**Comment by mkurnikov** [comment]
Yes, it's fine, `fetch` command would be similar to the `cargo fetch` with the same purpose, but it could be separate too, not much of a difference.
