### ISSUE TITLE
[CLI/Entrypoint] combine backup CLI and db bootstrapper into aptos-node binary or unified aptos binary

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#2836]
Currently we're building `db-backup` `db-restore` and `db-bootstrapper` and `aptos-node` as seperate binaries and add them to the validator docker image.
Since all these binaries share a _lot_ of code/dependencies that effectively get duplicated into each binary, it results in the docker image becoming unnecessarily large (~1.2 GB). This has some annoying side effects like longer bootstrap times  due to image pulling and also led to the root volume of our forge cluster filling up quicker than expected.

Therefore both to reduce the docker image size and for better usability we should combine all the db commands into a single binary and even consider adding it simply as subcommand to `aptos-node`.
Furthermore to take this a step further I think we should consider compiling everything, that is the CLI, node and all related tools like db-backup into a single unified binary. Effectively `aptos` is already close to being just that.
If you'd like to get a better understanding of each binary sizes have a look at the layers added in the tools image https://hub.docker.com/layers/tools/aptoslabs/tools/devnet_1570509e746b6626264cb6e9c0c8371683253961/images/sha256-a64c3a7c29edda15c561f29735551fa708bd4d88405af95dd06fd4965404283c?context=explore and the validator image: https://hub.docker.com/layers/validator/aptoslabs/validator/devnet_1570509e746b6626264cb6e9c0c8371683253961/images/sha256-5024050495b464283c5af56a4045c98471ec7993bb7b70ffe8bc874a44a7fdd2?context=explore

**Comment by msmouse** [comment]
The aptos cli now has the `node bootstrap-from-db-backup` sub-command that integrates the db-restore functionality.
However for the purpose of faster image build, a separate dev- oriented cli tool might need to be created.

**Comment by gregnazario** [comment]
I would say this is low priority, but we could just merge all those three tools together to make it simple enough.

**Comment by gregnazario** [comment]
For the person who will work on this:
1. Make a new crate that merges all 3 of these tools into one tool, maybe call it `aptos-db-tool` and have subcommands for each (with the same names)
2. Change the build to only build and use this new tool
3. Change all usages and references to these original tools to the new tool

**Comment by HgAmiui9** [comment]
I am interested in complete this job as my good first issue. There are some questions:

**Comment by msmouse** [comment]
We have the aptos-db-tool crate now that includes everything.
