### ISSUE TITLE
[Feature Request] support max size limit on bytes per block

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#2840]
# 🚀 Feature Request

## Motivation

we should be able to limit the total size per block to make sure we don't block network limit

e.g. 

```
consensus:
  max_block_size_txn: 6000
  max_block_size_bytes: 102400
```

**Comment by zekun000** [comment]
https://github.com/aptos-labs/aptos-core/pull/2844#event-7237204420
