### ISSUE TITLE
[Token] Make Direct Token Transfer Opt-in 

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#2883]
# 🚀 Feature Request
## Motivation
Existing token standard doesn't allow one user to directly transfer tokens to another account.
Users are also not allowed to directly deposit tokens to other users account. 
The transfer of tokens is a two steps process through offering and claiming. 
This two steps process can safe guard user accounts from getting unwanted NFTs. 
However, it does prevent a direct transfer for the users who don't have the same concern

## Pitch
we provide user an option so that they opt-in this direct token transfer. For the users opt-in this direct transfer, other people can direct send/deposit NFTs to their account without their consent.

**Comment by traitmeta** [comment]
This will be very convenient to use in certain scenarios
