### ISSUE TITLE
[Bug] Aptos Info not working

### ISSUE THREAD

**Issue by wintertoro** [aptos-labs/aptos-core#2899]
# 🐛 Bug

$aptos info
{
  "Result": {}
}

Result is blank.

**Comment by gregnazario** [comment]
This is due to removing shadow.rs

**Comment by wintertoro** [comment]
Oh do I have to install that in my machine? Or this has to be fixed on your end 

Jing

**Comment by gregnazario** [comment]
It's something we need to fix at build time.  Thanks for the issue!

**Comment by gregnazario** [comment]
Fixed by this https://github.com/aptos-labs/aptos-core/pull/3068
