### ISSUE TITLE
[Bug] python3 sdk query transaction error, need to be updated

### ISSUE THREAD

**Issue by sundafa** [aptos-labs/aptos-core#2921]
# 🐛 Bug
With rest api updated, but python sdk pypi library is not updated, resulting in error reading tx information

## To reproduce
pip install the current library, query transaction information
`pip install aptos-sdk`

Old error API code segment
{self.base_url}/transactions/{txn_hash}
```
    def transaction_pending(self, txn_hash: str) -> bool:
        response = self.client.get(f"{self.base_url}/transactions/{txn_hash}")
        if response.status_code == 404:
            return True
        assert response.status_code == 200, f"{response.text} - {txn_hash}"
        return response.json()["type"] == "pending_transaction"
```

New API
https://fullnode.devnet.aptoslabs.com/v1/transactions/by_hash/{txn_hash}

## System information
aptos-sdk 0.1.0.0
https://pypi.org/project/aptos-sdk/

## Additional context

![image](https://user-images.githubusercontent.com/24621599/184527947-6f775f05-72bf-41bc-8ad4-e3c9da4f1c72.png)

**Comment by davidiw** [comment]
oh this refers to the pypi version?

**Comment by davidiw** [comment]
I've updated the python-sdk, please try again with version 0.2
