### ISSUE TITLE
[Network] Move health checks inline

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#297]
Currently, health checks are ignorant of actual network traffic. The ideal case would be that health checker gets notification of incoming packets and only flags a health check if there has been a substantial period of time with no packet. Due to the way the system works, there's no point in follow up packets as these are all TCP based. If there's no response within "timeout period", than the connection should just be dropped. This involves two configurable parameters:
* The time to without any incoming messages before sending a ping: default to 10s
* The time to wait after a ping before resetting: default to 30s

**Comment by gregnazario** [comment]
We could have application based rate limiting, which would be on a packet basis.  Though it would likely just have it's own bucket to prevent spamming.
