### ISSUE TITLE
[Bug] spelling error in DiemBFT v4 doc

### ISSUE THREAD

**Issue by biquanlibai** [aptos-labs/aptos-core#3007]
In `aptos-core/developer-docs-site/static/papers/aptos-consensus-state-machine-replication-in-the-aptos-blockchain/2021-08-17.pdf`, section 2.2, "rather then" -> "rather than"

**Comment by davidiw** [comment]
Thanks for the heads up, not sure we have access to the original sources any more. Will update if we stumble across tem.
