### ISSUE TITLE
[Bug] Broken link for `state_sync` link in Node network topology page

### ISSUE THREAD

**Issue by k-r-e-b** [aptos-labs/aptos-core#3062]
# 🐛 Bug

The link for state sync is broken in [this page/section](https://aptos.dev/concepts/basics-node-networks-sync#synchronization-api) 

## Steps to reproduce

Go to [the docs page ](https://aptos.dev/concepts/basics-node-networks-sync#synchronization-api)and find below section at the bottom of the page:

> send chunks of transactions. Learn more about how this works in the specifications [here](https://github.com/aptos-labs/aptos-core/tree/main/documentation/specifications/state_sync).

link in the above paragraph is broken.

## Expected Behavior

The link should either be deleted or be replaced by the new one(couldn't find it, happy to add if guided)

**Comment by JoshLind** [comment]
Thanks @k-r-e-b!

@rajkaramchedu, can we remove this section?

```Synchronization API
The Aptos node's state synchronizer communicates with other nodes' state synchronizers to get and send chunks of transactions. Learn more about how this works in the specifications [here](https://github.com/aptos-labs/aptos-core/tree/main/documentation/specifications/state_sync).
```

It points to the state sync v1 spec (which was recently removed, along with all the state sync v1 code). We don't yet have any specs for state sync v2. 😄

**Comment by rajkaramchedu** [comment]
Thanks for the alert @k-r-e-b. Here is the PR, https://github.com/aptos-labs/aptos-core/pull/3232, @JoshLind. Thanks!
