### ISSUE TITLE
[Feature Request][Token] Create Basic Token Libraries for Supporting Marketplace and Auction House

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#3067]
# 🚀 Feature Request

## Motivation
1. We want to provide basic utility functions to have a standard to improve liquidity of token ecosystem.
2. We want app developers to be creative with how they run their their marketplace and auction house.

## Pitch
We provide fundamental token library functions and exemplary auction house marketplace contracts.
App developer can leverage these libraries and examplary code to create and deploy their own marketplace and auction house contracts. They can be 1. creative be the business logic , 2. be creative in aggregating listing and 3. reach interested buyer

Some key design choices: 

- NFT Owners have two options to store their listings (1) store listing at their own accounts,  (2) store their listing in a marketplace's accounts .  

Rational: the 1st option gives owner a choice to control their listings under their accounts, which can be aggregated by any marketplace on the chain. The 2nd option incentivizes marketplaces to work closely and provide value to creators so that creators choose to only list their NFT on a particular marketplace

- Escrowless listing: when the listing is active, the token is still stored at owner's account. the owner can still use and display their NFTs. But they cannot transfer the NFT. The NFT behind the listing is guaranteed to be available when the listing is still active.  So one token cannot exist in 2 different listings at the same time. 

Rational: the owner can still use their NFT or display their NFT in wallet before the listed NFT is sold, since the listing can exists for a long time. Meanwhile, we want to make sure the listing NFT exists to honor the transaction while the listing is still active

- Escrowless bidding: when users bid for a listing, their coin doesn't leave their account before the auction completes. The coins in the bid is guaranteed to exist when the auction completes.

- We don't provide auction house or marketplace contracts in token standard
Rational: we believe we should leave this to the community to come up with more creative ways of leveraging our basic marketplace utils functions to build their own marketplace. We will also provide example marketplace just for demonstration purpose

**Comment by areshand** [comment]
cc: @chloeqjz

**Comment by ericEnjoy** [comment]
Nice feature! 
Why not just store token in listing structure? 
If user transfer their token to others that already listing here, it will cause buying error.
If token stores in listing structure, user can not transfer their token to others anymore.

**Comment by ericEnjoy** [comment]
We are building auction house contracts, we will consider integrate this feature into our application and  leave a comment there if we have some idea about this feature

**Comment by areshand** [comment]
> Nice feature! Why not just store token in listing structure? If user transfer their token to others that already listing here, it will cause buying error. If token stores in listing structure, user can not transfer their token to others anymore.

Previously, I stored token so that buyer won't have buying error. 

Here are the reasons that I think it might be better not to store the tokens:
1.  buyer's coin won't be incorrectly charged if the listed token doesn't exist anymore
2. NFT display in the wallet requiring NFT in the tokenstore.
3. The creator could list the same token at multiple places with different prices and their listing may last a long time. 
4. I think it is better for the aggregator or marketplace's to cancel the invalid listing from their inventory since they can adjust the dynamics more easily compared to enforcing at standard level

**Comment by ericEnjoy** [comment]
Cool, nice job bro!
