### ISSUE TITLE
[AptosFramework] collect gas fee in buckets to allow parallelism

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#307]
Gas collection currently is serialized because every transaction touches the total supply. We could make 10s of buckets to collect the gas and decide how to distribute it later (e.g. epoch boundary) to make it more friendly to parallel execution.

https://github.com/aptos-labs/aptos-core/blob/227e208d33302c0d1f5b07f2445077986bb2f1fb/aptos-move/framework/aptos-framework/sources/TransactionFee.move#L7

**Comment by zekun000** [comment]
@davidiw no, we're not comfortable with the existing naive burning. it kills the parallel execution because of the total supply tracking.

**Comment by zekun000** [comment]
kill the total supply tracking?

**Comment by gregnazario** [comment]
I'm closing this now, since I think you've figured this out
