### ISSUE TITLE
[RPC Timeouts] Investigate why Aptos Data Client RPC timeout needs to be so high

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#308]
The current RPC timeout used by the Aptos Data Client is 10 seconds (https://github.com/aptos-labs/aptos-core/blob/main/config/src/config/state_sync_config.rs#L173). If we set it more aggressively (e.g., 5 seconds) we start to see some RPC timeouts in DevNet when a client is talking to the PFNs. To better understand why this is the case, we need to do some RPC tracing (e.g., client to server and see where the time is being spent).

Smaller tasks that will enable us to do this:
- [ ] Support log forwarding for the PFNs so that we can see what they are doing.
- [ ] Deploy all the dashboards in grafana for the PFNs so we can see interesting metrics (e.g., the storage and network dashboards).
- [ ] Create a new grafana dashboard to track the storage service metrics (the server side of the Aptos Data Client). Metrics exist, but we need to visualize them.

**Comment by gregnazario** [comment]
10 seconds is what is used for the total healthcheck period.  There are some backoffs and other things that come into play about having the timeout be less than 10 seconds, though a connection timeout for a normal service would usually be 5 seconds.

I suspect that something is time based or very slow in the connection process.
