### ISSUE TITLE
NFT Structure Concern

### ISSUE THREAD

**Issue by flappys** [aptos-labs/aptos-core#3080]
Hi there,

I am trying to create an NFT minting contract and found out something that might be by design or an issue. Please help me on this.

While creating a token for a collection in the function "create_token_script" there is a call to "create_tokendata" function where there are few validations. One of them is:

assert!(
            exists<Collections>(account_addr),
            error::not_found(ECOLLECTIONS_NOT_PUBLISHED),
        );

 It checks if collection is published or not by using the signer address.

If the minting is happening using the same account that was used to create collection, it works fine. But it does not allow minting by any other account.

In real world we would want any other user to mint from our collection but we would be the creator of the mint. As it happens in ethereum and solana.

How can we achieve this?

**Comment by areshand** [comment]
Solana candy machine allow other accounts to mint on the creator's behalf to help reduce the cost on creator's side. However, creator still needs to upload the config data on-chain (essentially token metadata) and pay the gas cost of deploy the candy machine. 

For creating and selling NFT, here is the option:
For NFTs, you need to create the token to store these raw metadata on-chain. This is cost paid by the creators. 
This is the reason we enforce only creator can create the token. I believe you also need to pay this cost on other chains (eg: candy machine deployment cost)
But once you created the metadata on-chain (create_token_script),
Here, we support semi-fungible token that you can create copies of same NFT only when someone demands it to reduce the cost. 
This is done through (mutate_token_properties), which will create NFT from existing fungible token with property_version = 0

**Comment by flappys** [comment]
With metadata on-chain (create_token_script), we would need a random function in place so that the minter doesn't find which NFT he is about to receive (he could read the data on-chain and find out the most rare NFT if we do serial mints). Do we have anything to create randomness.

 With mutate_token_properties we would need to send the token first to the user and then user have ability to create the NFT. I think this will resolve it. https://github.com/aptos-labs/aptos-core/issues/3087

**Comment by areshand** [comment]
1. I am not sure any chain support real randomness now. Buying random NFT is an interesting product feature. Meanwhile, the creator can also assign different prices based on the estimated demand of each Token. We could add this buying random NFT feature if there is strong need from the community.
2. mutate_token_properties doesn't change URI. it only creates a copy of existing token with its unique token_id (property_version). If creator want to create a total new NFT, they need to call the create_token_script.

**Comment by novaknole** [comment]
Hi, any news on this ? 

`mutate_token_properties` does not exist yet + how do we ensure randomness ? 

There're 2 choices we got.

1. creator of the collection from the very beginning mints all the tokens with their correct URI , tokenName. when someone wants to mint, all we do is transfer it to him. That't it.

2. When user wants to mint, that's when we call `createToken` from the creator and then we transfer it.

In both ways, randomness is not achieved. how can we do the randomness ?
