### ISSUE TITLE
[Bug] Cannot install aptos CLI in Windows 11/WSL (Ubuntu 22.04) due to error

### ISSUE THREAD

**Issue by sungkim11** [aptos-labs/aptos-core#3102]
# 🐛 Bug

I tried to install aptos CLI in two different instances of WSL (Windows 11/Ubuntu 22.04) and both fails at the same spot.

## To reproduce
1) New Ubuntu 22.04 WSL instance
2) Install RUST via rustup.rs
3) Run "source $HOME/.cargo/env"
4) Run "sudo apt install build-essential pkg-config openssl libssl-dev libclang-dev"
5) Run "cargo install --git https://github.com/aptos-labs/aptos-core.git aptos --branch devnet"

**Code snippet to reproduce**

# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
Compiling aptos-module-verifier v0.1.0 (/home/######/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/58d3f1b/aptos-move/aptos-module-verifier)
error[E0433]: failed to resolve: could not find `private` in `anyhow`
   --> types/src/network_address/mod.rs:487:21
    |
487 |             anyhow::private::Err(ParseError::EmptyProtocolString)
    |                     ^^^^^^^ could not find `private` in `anyhow`
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by MrReN** [comment]
I have the same problem and it sucks.

**Comment by davidiw** [comment]
Was addressed recently. Thanks for the bug report :)
