### ISSUE TITLE
add or destroy mint/burn capability on coin.move

### ISSUE THREAD

**Issue by namhoiyee** [aptos-labs/aptos-core#3124]
Request the ability to add/ destroy mint or burn capability inside coin.move in aptos-framework. So that the capability can be transferred.

**Is your feature request related to a problem? Please describe.**
I try to mint token by calling from a signer who has no capability. Wish to be able to do that for things like minting LP Token. Unless there is another way to it?
## Pitch

**Describe the solution you'd like**
```
    public fun remove_mint_capability<TokenType: store>(signer: &signer): MintCapability<TokenType>
    acquires MintCapability {
        move_from<MintCapability<TokenType>>(Signer::address_of(signer))
    }
    public fun add_mint_capability<TokenType: store>(signer: &signer, cap: MintCapability<TokenType>) {
        move_to(signer, cap)
    }
```

**Comment by davidiw** [comment]
These capabilities do not have key and therefore you need to make your own resource to store them. Please take a look at teh managed coin.
