### ISSUE TITLE
[Bug] Link Error (https://aptos-labs.github.io/aptos-core/aptos_types/transaction/enum.Transaction.html)

### ISSUE THREAD

**Issue by daoauth** [aptos-labs/aptos-core#3160]
# 🐛 Bug

## Steps to reproduce

I'm looking for a way to create a Transaction Hash. However, this [link](https://aptos-labs.github.io/aptos-core/aptos_types/transaction/enum.Transaction.html) seems to be wrong.

https://github.com/aptos-labs/aptos-core/blob/0eafde77585d91cbbd4fbdc285c9808449eb5ffa/api/src/transactions.rs#L105-L108

https://github.com/aptos-labs/aptos-core/blob/0eafde77585d91cbbd4fbdc285c9808449eb5ffa/api/doc/spec.json#L2065

https://github.com/aptos-labs/aptos-core/blob/0eafde77585d91cbbd4fbdc285c9808449eb5ffa/ecosystem/typescript/sdk/src/generated/services/TransactionsService.ts#L85-L88

https://github.com/aptos-labs/aptos-core/blob/main/api/doc/spec.yaml#L1474-L1477

## System information

**Please complete the following information:**
-

**Comment by gregnazario** [comment]
These docs haven't been regenerated in a while.  @geekflyer did we ever figure out how to automate our rustdoc builds?
