### ISSUE TITLE
[Bug] Extension Wallet - window.aptos.connect can not work anymore in v0.1.6 in Chrome.

### ISSUE THREAD

**Issue by lolieatapple** [aptos-labs/aptos-core#3178]
# 🐛 Bug

window.aptos.connect can not work anymore in v0.1.6 in Chrome.

## To reproduce
Run this code in F12 console of Chrome.
```
window.aptos.connect().then(console.log)
```
It will pending very long time and throw an error.

**Stack trace/error message**
```
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

## System information
- MacOS 12.5.1 MacBook Pro

**Comment by lolieatapple** [comment]
Ok, I found it try to access the public devnet even I select local test rpc.

**Comment by manhhuycao** [comment]
Hi @lolieatapple,

I have a issue same you. I dont know window.aptos.connect() dont work in Chrome, but window.ethereum still work
Have you fixed this case?

This is my code

![image](https://user-images.githubusercontent.com/40655080/197104307-d1e23334-c3c9-467a-9da2-e57830d3489b.png)

**Comment by lolieatapple** [comment]
Hi, my issue has been resolved. so have you tried to restart chrome after installed wallet?

On Oct 21, 2022, at 11:23, manhhuycao ***@***.******@***.***>> wrote:



Hi @lolieatapple<https://github.com/lolieatapple>,

I have a issue same you. I dont know window.aptos.connect() dont work in Chrome, but window.ethereum still work
Have you fixed this case?

This is my code

[image]<https://user-images.githubusercontent.com/40655080/197104307-d1e23334-c3c9-467a-9da2-e57830d3489b.png>

**Comment by manhhuycao** [comment]
Yes, i restarted Chorme & my computer, but it dont work.
This is error in consol

![image](https://user-images.githubusercontent.com/40655080/197108919-11f8e632-d880-45c4-98ee-ae9a2b93f10c.png)

**Comment by lolieatapple** [comment]
which wallet do you use? as I known different extension wallet use different api interface.

On Oct 21, 2022, at 12:03, manhhuycao ***@***.******@***.***>> wrote:



Yes, i restarted Chorme & my computer, but it dont work.
This is error in consol

[image]<https://user-images.githubusercontent.com/40655080/197108919-11f8e632-d880-45c4-98ee-ae9a2b93f10c.png>

**Comment by TanDucHRM** [comment]
i use Martian & Pontem, it dont work at all

**Comment by lolieatapple** [comment]
Martian is window.martian try to find it in F12 console.

On Oct 21, 2022, at 12:13, TanDucHRM ***@***.******@***.***>> wrote:



i use Martian & Pontem, it dont work at all

**Comment by TanDucHRM** [comment]
Yes it work. Thank you so much

**Comment by lolieatapple** [comment]
Happy to help :)

On Oct 21, 2022, at 12:29, TanDucHRM ***@***.******@***.***>> wrote:



Yes it work. Thank you so much

**Comment by manhhuycao** [comment]
Yes it work, thank you so much

**Comment by lolieatapple** [comment]
happy to help :)

On Oct 21, 2022, at 12:41, manhhuycao ***@***.******@***.***>> wrote:



Yes it work, thank you so much
