### ISSUE TITLE
[Bug] Local testnet with multiple validators

### ISSUE THREAD

**Issue by tuleyko** [aptos-labs/aptos-core#3234]
# Documentation extension request

Please extend official documentation with a description how to run a local testnet with multiple validators. 

Current [docs](https://aptos.dev/guides/local-testnet-dev-flow) has a guide of a single validator testnet only.

This was issue is created based on recommendation from a team member on Discord: https://discord.com/channels/945856774056083548/953421979136962560/1009508175491383346.

**Comment by vitruvvius** [comment]
Hey team - need this as well for benchmarking on a WAN cluster of nodes instead of testnet/devnet

**Comment by vitruvvius** [comment]
https://github.com/aptos-labs/aptos-core/issues/2096

**Comment by JoshLind** [comment]
Hey folks, be aware, we are adding this functionality now and will have documentation out in the next few days to enable it.

**Comment by vitruvvius** [comment]
superrr excited. let me know if team needs any help!

**Comment by JoshLind** [comment]
@tuleyko and @vitruvvius, official documentation will be coming soon. But, if you'd like to deploy a multi-node network locally, this tool and README should do the trick. Let us know if you have any feedback, etc.: https://github.com/aptos-labs/aptos-core/tree/main/testsuite/forge-cli/src

**Comment by vitruvvius** [comment]
Great!

At the very least, this forms the bedrock
on how to modify/run a cluster programmatically

At the very best, this becomes
the go-to for testing the network pre-prod

For us, we will need to test
standard deviation (ie, 0.999 v 0.99 v 0.9 %tile) 
in perf for a clob

As well as the cost per unit of an
optical flow storage network

**Comment by tuleyko** [comment]
First run and success. Works good on the latest main. Thank you

**Comment by JoshLind** [comment]
Done. See: https://github.com/aptos-labs/aptos-core/tree/main/testsuite/forge-cli/src
