### ISSUE TITLE
[Feature Request] Add more move examples related to creating and transferring coins or tokens

### ISSUE THREAD

**Issue by dhruvja** [aptos-labs/aptos-core#3260]
# 🚀 Feature Request

I would love to have more move module examples which would deal with creating coins, minting, depositing and many more functionalities related to coins. We could have the same thing for tokens as well. 

## Motivation

I was trying to build a module for a ticket platform where the venue owner can create tickets and the users can buy the tickets by transferring the amount to the venue owner. A big shoutout to @magnum6actual for the wonderful tutorial on this(https://medium.com/code-community-command/were-picking-up-where-we-left-off-at-the-last-episode-so-if-this-is-your-first-time-here-check-394ddb8950f0) . But the problem what i faced was i was unable to create tests where i was able to initialize a new coin. I used the functions in coin.move module but they didn't seem to work. After a lot of digging through the code, i found that using aptos_coin.move module, we could initialize the coin, mint and other functionalities as well. But there is no proper resource which would tell us how to use these modules and build the functionality around it. So i was thinking it would be great if we can have a few examples around this, so its easy for people to refer and build on it. And after a lot of digging in the code and asking people on discord,
 **James | Aptos Labs** (I am sorry couldnt find ur profile on github) suggested me to open an issue so that we can discuss and contribute.

### Solution
- We can have more examples which would how to use these modules and build a basic module around it.
- We can even have a tutorial which would take all these concepts and build a whole system from scratch.
- We can add more comments in coin.move and aptos_coin.move explaining the functions in more detail

**I would be glad to open a pull request and provide the examples mentioned above**

## Additional context

I have created a module in which i have tests where i initialize a new coin along with minting and transferring. I would like to have more examples regarding the functionalities in the module below.
https://github.com/dhruvja/aptos-concert-ticket

**Comment by areshand** [comment]
This is good idea.  love the pitch. I think there could a lot of examples. would be great to create an issue for each example so that we can discuss in more details for each individual example

**Comment by dhruvja** [comment]
> This is good idea. love the pitch. I think there could a lot of examples. would be great to create an issue for each example so that we can discuss in more details for each individual example

I am glad you loved it. Having more examples would definitely make building on aptos much easier.
