### ISSUE TITLE
Link to fullnode incorrect and API demo doesn't work.

### ISSUE THREAD

**Issue by olton** [aptos-labs/aptos-core#3262]
# 🐛 Bug

I use nginx before any servers and have config for fullnode (**everything is behind a firewall**):
```
server {
  listen 80;
  listen 443 ssl;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  server_name fullnode.aptos.net.ua;
  ssl_certificate /etc/letsencrypt/live/fullnode.aptos.net.ua/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/fullnode.aptos.net.ua/privkey.pem;
  location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_pass http://localhost:8080/v1;
  }
  location ~ /(.*) {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_pass http://localhost:8080/v1/$1;
  }
}
```

In API `spec` link has view `https://fullnode.aptos.net.ua/v1` which does not correspond to the current settings should be `https://fullnode.aptos.net.ua`.

<img width="530" alt="2022-08-21-19-05-19" src="https://user-images.githubusercontent.com/365108/185800221-441ed59f-f893-4704-a6c3-7d60576ad7f1.png">

**That's why the demo doesn't work!** One possible solution is to add another URL without adding /v1. And make a drop-down list for choosing the type of link to the API of the node.

I'm sure I'm not the only one with the same problem.

**Comment by gregnazario** [comment]
The `v1` path is expected to be kept as it's used for versioning.  If there was a `v2` version of the API, it would be incompatible.

This is specific to your NGINX setup due to redirecting `/` to `/v1`.  The other thing you could do is add a `/v1` redirect to `/` as well.
