### ISSUE TITLE
[Docs] Feedback for node docs

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#3280]
Hey all, would love to hear your feedback about node documentations:
- Initial node setup through cloud/docker/source code https://aptos.dev/nodes/validator-node/validators
- connecting to a network https://aptos.dev/nodes/ait/connect-to-testnet

Please comment in this issue for things you feel that's confusing, or commands which is not working. Or any general thought you have in mind, thank you!

**Comment by boczeratul** [comment]
It would be great if there's also a section that describes how to set up node/operator account with different stake pool owner address and operator address. Currently the default seems to be using the same account for both roles.

**Comment by boczeratul** [comment]
I'm using **Terraform** on **GCP**. The docs seems quite thorough and pretty easy to follow for this option.

**Comment by michaelh-laine** [comment]
The number of keys and config files is a bit confusing. It would be nice to have a primer on what the files mean, i.e. what's the layout.yaml for, what's the validator.yaml for, what's the operator.yaml for.

I also find it confusing that some places uses validator and others operator. 

It also seems confusing that one has a public key and an address which are separate. And in some places, e.g. initializing a stake pool, it uses `operator-address`  then `operator-account`.

![image](https://user-images.githubusercontent.com/68944931/185999571-89b422dd-42fe-45d2-b92b-c03126eaa25f.png)

Ideally some of these steps could be wrapped into a single command. Right now the entire setup process feels quite fragmented. The need to manually remove stuff like secure-data when changing chain IDs is cumbersome and easy to forget a step, the validator should clean this data automatically when it detects that its necessary.

Ideally one would have a single configuration file for the node/operator/validator, a set of key files, and a genesis. The waypoint  can be incorporated to the config file.

**Comment by dylanschultzie** [comment]
I agree with @michaelh-laine about the accounts being confusing. 

One improvement that would go a long was is giving an example input for each key/account for the command.
