### ISSUE TITLE
Dapp example does not work after update

### ISSUE THREAD

**Issue by flappys** [aptos-labs/aptos-core#3302]
Dapp example here: https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site/static/examples/typescript/dapp-example
used to work fine before the update. 
Getting 
GET https://fullnode.devnet.aptoslabs.com/accounts/0xa62ebbd4fa53c4ae861a7dff0884f06b02a758f0bc684ee163afc2cfe0305bd0/modules 404

**Comment by davidiw** [comment]
there are a plethora of issues out there for dapp example, also note that urls are reset after each devnet wipe, so it is based upon the user to repeat the operation to reproduce the data.
