### ISSUE TITLE
[Bug] [Azure] Illegal base64 data at input byte 727

### ISSUE THREAD

**Issue by oswy-cpu** [aptos-labs/aptos-core#3312]
# 🐛 Bug

## A clear and concise description of what the bug is.
Error in [version.tf](https://github.com/aptos-labs/aptos-core/blob/main/terraform/aptos-node/azure/versions.tf) does not allow to install a node using a terraform. 

## To reproduce

**Code snippet to reproduce**
``` 
terraform apply
```

**Stack trace/error message**
<img width="636" alt="image" src="https://user-images.githubusercontent.com/74738120/186037369-bd67409f-5d61-43cd-b6c6-0c5c06cf96db.png">

## System information

**Please complete the following information:**
-  0.3.1
-  1.63.0
-  Ubuntu 20.04

**Comment by davidiw** [comment]
feel free to re-open if the issue persists.
