### ISSUE TITLE
[Bug]wallet extension can't start up

### ISSUE THREAD

**Issue by wcw84** [aptos-labs/aptos-core#3324]
the wallet extension can't start up, just a blank window:
![image](https://user-images.githubusercontent.com/7152596/186088917-de35032a-1cfc-4145-8b21-04774a8bbac7.png)

and i got the error from the chrome extension:
![image](https://user-images.githubusercontent.com/7152596/186089728-de0614fa-9b87-40e1-83d2-c2098d50ebd1.png)

chrome version: 94.0.4606.71
MacOs: monterey

**Comment by kent-white** [comment]
believe this is fixed
