### ISSUE TITLE
Is there any concept of lease term or personal account storage limit for the move contract on aptos?

### ISSUE THREAD

**Issue by 99Kies** [aptos-labs/aptos-core#3329]
I didn't find any documentation or code for this and would appreciate any help.

**Comment by msmouse** [comment]
@99Kies  you can find relevant (but somewhat vague :P ) information on that topic -- details will come out in the coming months.
https://medium.com/aptoslabs/the-path-to-10x-lower-gas-fees-on-aptos-with-community-driven-feedback-7cca875a513f
