### ISSUE TITLE
[storage][state sync v2] Genesis clean up

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#335]
Currently a node always starts with the genesis in config committed, before state sync even kicks in. With SSv2 which will select a recent state checkpoint to sync from, a "gap" will be created in the ledger history between genesis and the snapshot version. The genesis in DB is practically required because state sync boots up from seeds in the genesis, which is doubtable since the genesis can be so old that all the seeds in it are stale anyway.

Proposed solutions:
1. Access the genesis with an in-mem StateView, don't commit it before SSv2 decides to. -- this can be messy for the implementation.
2. Add interface from DB to clean up genesis (or the entire db), and let SSv2 call it when proper.
3. The DB identifies this edge case and keeps a record of the actual left edge of the "history prune window" (this probably needs to be done anyway for the performance of finding the edge).

**Comment by davidiw** [comment]
status?
