### ISSUE TITLE
How to calculate transaction hash before submitting?

### ISSUE THREAD

**Issue by Wangmmx** [aptos-labs/aptos-core#3393]
Hi, I built a transaction with aptos sdk and submitted it successfully, and I want to get the transaction hash before submitting. I saw some codes in 'Transaction' class and show the hash function, but I didn't know how to create the 'Transaction' class, I just used the first_transaction code and ran it, is there any example to follow?  Thanks a lot

**Comment by dump-block** [comment]
same how to ?

**Comment by Wangmmx** [comment]
closed, solved

**Comment by dump-block** [comment]
@Wangmmx how to?

**Comment by jjleng** [comment]
@dump-block https://github.com/aptos-labs/aptos-core/commit/916896947c629fe02588d5c5977bff2fecf587ac
