### ISSUE TITLE
Receiver Register got Error onchain

### ISSUE THREAD

**Issue by Wangmmx** [aptos-labs/aptos-core#3394]
Hi, I want to transfer APTOS to a new address, and I need to register it first, I created a coin Register transaction and submit like: https://aptos.dev/tutorials/your-first-coin, and it got error when broadcast, cause the low balance

And I changed the gasPrice to 0 and submitted it again , no broadcast error this time, but the transaction got error either: Transaction Executed and Committed with Error EXECUTE_ENTRY_FUNCTION_CALLED_ON_NON_ENTRY_FUNCTION, but the account did register successfully, do I need to register it again? Or is there something I made wrong?

Looking forward to your reply, thanks

**Comment by davidiw** [comment]
We were slow in updating the demos, the new entry function name is `aptos_account::create_account`.

**Comment by Wangmmx** [comment]
> We were slow in updating the demos, the new entry function name is `aptos_account::create_account`.

Ok thanks, I tried a few times and it doesn't seem to work. 
My address was generated offline using ed25519. I did not use aptos-sdk to generate the address, so the address was not registered by any coin. Does `create_account` require me to sign and submit transactions? New address cannot receive coins without register, so there is not enough value for fee to send transactions. I'll try again anyway, thanks

**Comment by davidiw** [comment]
There's not a lot of clarity of what your end-to-end is.

1. your first coin is currently deprecated
2. would recommend you look at https://aptos.dev/tutorials/your-first-transaction for some examples
3. follow up on discord, folks there can help :)

**Comment by Wangmmx** [comment]
Yes, I use the example you mentioned. This example can run successfully. Faucet will help us register the coin and receive test coins.

but I need to generate an address offline, and get coins from others instead of faucet. I got the error all the time: `Move abort in 0x1::coin: ECOIN_STORE_NOT_PUBLISHED (0x60005): Account hasn't registered 'CoinStore' for 'CoinType',` 

I haven't seen an example of the new function  `aptos_account::create_account` you answered. In the source code, I see that signer is required, but I can not send the transaction cause there is no coin in the new address

Ok, thank you, I'll go to discord and ask, closing this issue now

**Comment by Developmc** [comment]
hi, did you solve it ？ @Wangmmx

**Comment by a943999733** [comment]
Can you give me an example

aptos_account::create_account
