### ISSUE TITLE
Error in validator Node setup - DevNet

### ISSUE THREAD

**Issue by dragoncrypto1** [aptos-labs/aptos-core#3396]
## ❓ Questions and Help
Hello guys, I am trying to setup validator node on AWS using the nodes guru script. However I am getting the following error:

Container aptos-validator-1  Creating
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/.aptos/genesis.blob

Can someone here help resolve this?

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by Krishnacore** [comment]
You should use the official instructions, it's pretty simple. From your error I can say that genesis.blob is missing, why - you should look at the execution of the script, it seems - something goes wrong before running the container. My guess - for some reason aptos-cli doesn't work, maybe some dependencies are missing

**Comment by Krishnacore** [comment]
I think I figured out what's wrong. I'm 99% sure it's because you're trying to do it on Ubuntu 22.04 (although the nodes guru clearly indicates 20.04). This version has a known problem with libssl. And if you try to do e.g. `aptos -V`, you will get an answer like this:
```
aptos: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
The solution to this is quite simple, you have to install this package manually:
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.0l-1~deb9u6_amd64.deb
sudo dpkg -i libssl1.1_1.1.0l-1~deb9u6_amd64.deb
```

**Comment by dragoncrypto1** [comment]
Worked fine when the command was executed using root credentials!
