### ISSUE TITLE
[storage][SSv2] get_transaction_outputs should leverage range_get

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#341]
https://github.com/aptos-labs/aptos-core/blob/90646f53e5a3a772fe9d8ba28e97e062a29a5974/storage/aptosdb/src/lib.rs#L844-L849

The API issues a lot of point gets for various things on a per txn basis, which is not ideal.

**Comment by GrapeBaBa** [comment]
@sitalkedia Could you assign it to me?

**Comment by sitalkedia** [comment]
@GrapeBaBa - Thank you so much for your interest in working on this issue. Please let me know if you have any questions or need any further clarification on the issue.

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa - Thank you so much for your interest in working on this issue. Please let me know if you have any questions or need any further clarification on the issue.

Sure.

**Comment by JoshLind** [comment]
I assume this has already been done. Feel free to reopen.
