### ISSUE TITLE
[Bug] Petra wallet doesn't use the correct decimal points for APT coins

### ISSUE THREAD

**Issue by kingaptos** [aptos-labs/aptos-core#3418]
# 🐛 Bug

Petra wallet needs to divide aptos coins by the correct number of decimals (8) before displaying it. Otherwise, it is showing the incorrect number of APT coins in your wallet, and that's bad.  The value below is wrong:

![IMAGE 2022-08-24 13:29:38](https://user-images.githubusercontent.com/111548547/186517149-a8ba8b42-d730-413e-8d46-a969a1a8a165.jpg)

## To reproduce

1. Create a new account
2. Use any of the faucets to get apt coin
3. Check that petra wallet directly shows the number of APT coins in the chain instead of dividing it by the decimals

## Expected Behavior

should show: value / 10 ^ 8

**Comment by gregnazario** [comment]
I believe this is going in the next release whenever it actually happens @kent-white

**Comment by davidiw** [comment]
fixed

**Comment by kingaptos** [comment]
Nice, thanks for fixing it! One issue, at least as a developer, is that now all my accounts show 0. For real users, this is probably fine, but dev mode would be nice to see the actual integer.
