### ISSUE TITLE
[Bug] multisig account can't rotate keys

### ISSUE THREAD

**Issue by WuBoBo** [aptos-labs/aptos-core#3450]
# 🐛 Bug
Hi, I'm the developer from Blocto team.
Our team are developing multisig wallet for Aptos.

Recently, I checked up on the latest updates including this [PR](https://github.com/aptos-labs/aptos-core/pull/3382) and I find that the `rotate_authentication_key` function has been changed to `rotate_authentication_key_internal` for internal use and the only way to rotate the key is to use `rotate_authentication_key_ed25519` which is for single signer.

For the past busy days, we have developed multisig wallet by using `rotate_authentication_key` in our account flow, but it seems no longer available, and there is no other way to rotate multisigner account which is unexpected for us.

Is that possible to provide multisig rotate function like `rotate_authentication_key_multi_ed25519` for use before the mainnet launch?

**Comment by scottphc** [comment]
It's important to add the multisig account key rotation before mainnnet launch. There're other multisig use cases for Exchanges and DAOs fund management. If they can't rotate keys, the only way to add/remove members is to create a new account.

**Comment by scottphc** [comment]
It's important to add the multisig account key rotation before mainnnet launch. There're other multisig use cases for Exchange and DAO fund management. If they can't rotate keys, the only way to add/remove members is to create a new account.

**Comment by scottphc** [comment]
It's important to add the multisig account key rotation before mainnnet launch. There're other multisig use cases for Exchanges and DAOs fund management. If they can't rotate auth key, the only way to add/remove members is to create a new account.

**Comment by xiaozzz** [comment]
@scottphc i see your repo, but this PR break it, `rotate_authentication_key_internal` is no longer public
https://github.com/aptos-labs/aptos-core/pull/3382

**Comment by alinush** [comment]
I assume you'd like to rotate from a $k$-out-of-$n$ MultiEd25519 PK to any (possibly-different) $k'$-out-of-$n'$ MultiEd25519 PK?

**Comment by scottphc** [comment]
> I assume you'd like to rotate from a k out-of n MultiEd25519 PK to any (possibly-different) k′ out-of n′ MultiEd25519 PK?

Yes! In Blocto's mechanism, $k$ is the same (always 2) and $n$ is probably different (greater than or equal to 4).

**Comment by boczeratul** [comment]
Thanks. This is pretty important for Blocto account operation. It would be great if this can be resolved.

**Comment by davidiw** [comment]
Yes, we are freezing our existing APIs and only supporting adding new ones. The current APIs were too permissive, so we deleted them and will work to quickly bring them back :).

**Comment by alinush** [comment]
This should be fixed now in https://github.com/aptos-labs/aptos-core/pull/3626: users can rotate from/to any key type.

**Comment by boczeratul** [comment]
@alinush everything looks good to me. thanks!
