### ISSUE TITLE
[Bug] no aptos coin register for aptos_framework::resource_account.move

### ISSUE THREAD

**Issue by xiaozzz** [aptos-labs/aptos-core#3454]
# 🐛 Bug

i think this function should also `coins::register<AptosCoin>(&resource);`
without that, rotate auth key to a resource account is meaningless, you can do nothing with it
https://github.com/aptos-labs/aptos-core/blob/35f6f61d7fdc8e9fc1dc90328eb8af817ab9b3c9/aptos-move/framework/aptos-framework/sources/resource_account.move#L55-L77

**Comment by macalinao** [comment]
I have a stopgap for fixing this here https://github.com/DeployDAO/aptos-deployer/blob/master/sources/deployer.move

**Comment by xiaozzz** [comment]
@macalinao  i see your repo, but this PR break it, `rotate_authentication_key_internal` is no longer public
https://github.com/aptos-labs/aptos-core/pull/3382

**Comment by davidiw** [comment]
We're discussing internally. Not every resource account needs a coin resource and so creating it automatically is wasteful. We'll likely add a `create_resource_account_and_fund` function.

**Comment by davidiw** [comment]
resolved.
