### ISSUE TITLE
[Feature Request] Add `#[test_only]` version of `genesis::initialize_aptos_coin` for unittests

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#3468]
# 🚀 Feature Request

Genesis has two steps, first one is `genesis::initialize` which is wrapped in the test only `genesis::setup`. 
Please wrap the second step `genesis::initialize_aptos_coin` in a `#[test_only]` function too. 

@movekevin

**Comment by movekevin** [comment]
You can technically use https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/stake.move#L1136 to achieve most of the same things as it will:
1. Initialize aptos coin
2. Store the mint cap in the stake module

The only thing that doesn't do is storing burn capability in transaction fee, but I don't think that matters much for on chain unit tests?
