### ISSUE TITLE
Zero gas fees - local cluster [Feature Request]

### ISSUE THREAD

**Issue by vitruvvius** [aptos-labs/aptos-core#3475]
# 🚀 Feature Request

Remove any/all gas fees for a local cluster in order to test the correctness & convergence of a contract.

An address K1 must send 100_000 units to an address K2.

It must hold some variable 100_000 + (gas_fee_max) units.

That gas_fee_max fluctuates over the lifecycle of a network.

Extrapolate this to now 1_000_000 transactions occur, simulating the final output of all addresses significantly more challenging.

The ability in a local/private cluster to get rid of any/all gas fees would be great!

Thanks :)

## Motivation

**Is your feature request related to a problem? Please describe.**
Extremely frustrated when testing the correctness of programs

## Pitch

**Describe the solution you'd like**
An option to get rid of fees when deployed in a local cluster.

**Describe alternatives you've considered**
Setting the gas_fee to a constant >0 - but the work required would be equivalent to setting the gas_fee to any # & thereby including 0

**Comment by gregnazario** [comment]
You should be able to set the minimum gas price to 0, which will be the same as not having to pay gas for any transaction.  Probably need directions for this

**Comment by vitruvvius** [comment]
Great little trick - closing this (documented now herein)
