### ISSUE TITLE
[TS][SDK] Convert ApiError into AptosError

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#3484]
The node API, in the error case, invariably returns an AptosError, no matter what. The TS SDK however only returns an ApiError in the non 2xx case. This means the caller is responsible for taking the error body in the ApiError and converting it into an AptosError.

Apparently this is something our generator does not support natively: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/728, https://github.com/ferdikoomen/openapi-typescript-codegen/issues/655. I suspect the best UX (though perhaps a bit messy) would be to postprocess the generated code. One cleanish option would be to add a function to ApiError like `intoAptosError` that tries to deserialize the error response body into an `AptosError`.

**Comment by jjleng** [comment]
We fork and modify it. https://github.com/aptos-labs/openapi-typescript-codegen. See this https://github.com/aptos-labs/aptos-core/pull/3385

**Comment by banool** [comment]
I think we avoid a fork if possible, that's a lot of effort to maintain.

**Comment by jjleng** [comment]
I don't think that's a lot. Indexer is also using a forked diesel

**Comment by banool** [comment]
Yeah I don't love that either lol.

**Comment by banool** [comment]
If we do have a fork, we need to hold a high bar, we can't just hack up the codebase because we won't be able to stay on top of upstream.

**Comment by jjleng** [comment]
https://github.com/aptos-labs/aptos-core/pull/2851 is using the fork already. Otherwise, the hack was cumbersome. I had some post-processing and deleted that as it is harder to maintain the postprocessing scripts if there are many.

**Comment by banool** [comment]
Alright we'll see how it goes.
