### ISSUE TITLE
[Feature Request]add new api to query account-related transactions combined

### ISSUE THREAD

**Issue by web3luhao** [aptos-labs/aptos-core#3510]
# 🚀 Feature Request

add a new API or add a new query parameter for `getAccountTransactions` to achieve query user transactions and deposit_event transactions combined

## Motivation

It's common practice to show receive events alongside send events, as they both are related to how the user's balance gets to the current status. the current APIs make it hard to combine these and paginated.

## Pitch

add a new API or add a new query parameter for `getAccountTransactions` for query account-related transactions

**Comment by davidiw** [comment]
This is the current behavior, is it not?

https://fullnode.devnet.aptoslabs.com/v1/accounts/0xa550c18/transactions

**Comment by web3luhao** [comment]
in [my test account ](fullnode.devnet.aptoslabs.com/v1/accounts/0x9083de9930e2b73f95dc93d8118c0f886388f900116a6fdc373f599d01be4923/transactions) only the `"0x1::coin::transfer"` from this account is listed, while [the deposit_event](https://fullnode.devnet.aptoslabs.com/v1/accounts/0x9083de9930e2b73f95dc93d8118c0f886388f900116a6fdc373f599d01be4923/events/0x1::coin::CoinStore%3C0x1::aptos_coin::AptosCoin%3E/deposit_events) and their transactions is not.

**Comment by web3luhao** [comment]
@davidiw consider reopen this?

**Comment by davidiw** [comment]
You want deposit events from transactions sent from other accounts?

**Comment by davidiw** [comment]
I feel like you're asking for an indexer. The rest interface won't have this type of index built into it.

**Comment by web3luhao** [comment]
> I feel like you're asking for an indexer. The rest interface won't have this type of index built into it.

I know it's not builtin right now, so that's a  Feature Request. I can see so many wallets not implementing their history correctly or forced to split receive and send apart. as I said before, users should be able to check how the account gets to its current status. consider adding this feature
