### ISSUE TITLE
Is there any API support register a new account

### ISSUE THREAD

**Issue by lynAzrael** [aptos-labs/aptos-core#3512]
I generate a new address and try to transfer to it by Petra Aptos Wallet but failed.
Then I build a transaction and submit successfully, but it returns "Move abort in 0x1::coin: ECOIN_STORE_NOT_PUBLISHED(0x60005): Account hasn't registered `CoinStore` for `CoinType`"

Refer to this document https://fullnode.devnet.aptoslabs.com/v1/spec#/, I can't find any API about register new address.
Is there any example about how to register new account?

**Comment by davidiw** [comment]
You need to first create the account with `aptos_account::create_account`.

**Comment by lynAzrael** [comment]
Hi @davidiw , Can you update the document about how to register the address by Aptos Node API.
https://fullnode.devnet.aptoslabs.com/v1/spec#/

**Comment by davidiw** [comment]
This doesn't belong in that spec. It belongs here: https://aptos.dev/guides/system-integrators-guide/#accounts-on-aptos and I'll update that tomorrow :)

**Comment by lynAzrael** [comment]
ok, thanks a lot

**Comment by lynAzrael** [comment]
Hi @davidiw, I have test the transfer function due to the system-integrators-guide and both api and sdk use coin::transfer for transfer. Is there any example about how to use account::transfer or account::create_account by api or sdk?

**Comment by Developmc** [comment]
try this: 
**create account and transfer** 

`const entryFunctionPayload = new TxnBuilderTypes.TransactionPayloadEntryFunction(
  TxnBuilderTypes.EntryFunction.natural(
    "0x1::aptos_account",
    "transfer",
    [],
    [BCS.bcsToBytes(TxnBuilderTypes.AccountAddress.fromHex("0xabc..")), BCS.bcsSerializeUint64(10)],
  ),
);
`

**Comment by ConnorChen97** [comment]
> try this: **create account and transfer**
> 
> `const entryFunctionPayload = new TxnBuilderTypes.TransactionPayloadEntryFunction( TxnBuilderTypes.EntryFunction.natural( "0x1::aptos_account", "transfer", [], [BCS.bcsToBytes(TxnBuilderTypes.AccountAddress.fromHex("0xabc..")), BCS.bcsSerializeUint64(10)], ), ); `

I try this and i got error: Move abort in 0x1::transaction_validation: 0x203ed
