### ISSUE TITLE
[Bug] Aptos CLI publish module

### ISSUE THREAD

**Issue by 0xZangetsueth** [aptos-labs/aptos-core#3521]
Hello, I'm following this tutorial: https://aptos.dev/tutorials/first-move-module-cli

But two problems, there is no command build for aptos move cli, so I guess it's aptos move compile, so I've done aptos init, then funded the account, then aptos move compile and aptos move test, everything works.
Inside my Move.toml I've added my address, but for aptos move publish (If I do it with named address without adding firstly my address or without named address and putting myself my address inside move.toml it's both the same) I get :

```package size 1630 bytes
{
  "Error": "API error: Unknown error transaction execution failed: Transaction Executed and Committed with Error LOOKUP_FAILED"
}
```

Do you know how to resolve it? I've reinstalled my cli with the latest version

**Comment by 0xZangetsueth** [comment]
Ok I've also reinstalled the aptos-core repo and now it's working

**Comment by passer-byzhang** [comment]
Hi bro,I met the same error when I published module to devnet without using local environment. Do you know the reason of this? Thank you!
