### ISSUE TITLE
[Better Engineering] Unify account/transaction generation

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#353]
In tests, there're a few different ways of generating test account and corresponding transactions.

We should unify them under the same framework i.e. LocalAccount. A few places for example: https://github.com/aptos-labs/aptos-core/blob/main/execution/executor-test-helpers/src/integration_test_impl.rs#L56

https://github.com/aptos-labs/aptos-core/blob/main/execution/executor-benchmark/src/transaction_generator.rs#L61

**Comment by kris524** [comment]
Hello, I would like to help with this issue. Could you give me more background as I am not sure I understand it? Am I correct in saying that instead of `.public_key()`, we should create a `LocalAccount` struct and use its properties?

**Comment by zekun000** [comment]
@kris524 Hi, thanks for the interests!

to give more details, there's a few different ways of creating a key-pair and signing a txn. `LocalAccount` encapsulates the key-pari generation, address derivation, sequence number tracking and transaction signing etc 
```
let mut account = LocalAccount::generate();
let txn = account.sign_with_transaction_builder(
  txn_factory.payload(
    encode_..._script_function(...),
  )
);
```
instead of the more verbose ways linked in the issue.

**Comment by kris524** [comment]
Hello, so I made a fork as it didn't allow me to push here. I am attaching the link here: https://github.com/aptos-labs/aptos-core/pull/382    I am sure the code might be incorrect, but I would be happy for any feedback so I can implement it and improve it in the next commit.
