### ISSUE TITLE
Need to rebuild validator node - asking for previous keys

### ISSUE THREAD

**Issue by Treawlony** [aptos-labs/aptos-core#3531]
Hello,
I had a major issue o Azure deployment and lost everything, I need to redeploy the validator node but I would like to use the same keys for obvious reasons.
I've already registered the node, it's possible to get the keys to reuse?
please let me know and what is the procedure
Thanks

**Comment by gregnazario** [comment]
I'm sorry, but there is no way to recover private keys from public keys.
