### ISSUE TITLE
[Feature Request] Get a signer with SignerCapability from resource account module

### ISSUE THREAD

**Issue by Silicon-III** [aptos-labs/aptos-core#3544]
# 🚀 Feature Request

There are only two function create_resource_account and retrieve_resource_account_cap in resource account module,  but mostly we need a resource account with SignerCapability, we can't get it from this module.

## Motivation

We need a function to get a signer with SignerCapability.

**Comment by leina05** [comment]
I think you should be able to use this function: https://github.com/aptos-labs/aptos-core/blob/721c0a202eca992a199a8323e865be684f2a7ae4/aptos-move/framework/aptos-framework/sources/account.move#L378-L381

**Comment by gregnazario** [comment]
I'm closing this out, because you can create the signer with the capability :). please reopen if you need something else.
