### ISSUE TITLE
[Bug] compile failed on mac m1

### ISSUE THREAD

**Issue by guotie** [aptos-labs/aptos-core#3548]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `aptos-indexer` due to previous error
```

## System information

**Please complete the following information:**
- 

- 
1.62.1
- 
macOS Monterey 12.4

**Comment by gregnazario** [comment]
Please provide the whole command and output

**Comment by gregnazario** [comment]
You may have to run the `scripts/dev_setup.sh` script to install associated libraries.  It should compile fine on M1 mac, as that's what I use to develop with.

**Comment by gregnazario** [comment]
Please reopen if you have more information or more questions
