### ISSUE TITLE
[Bug] publish move hello_blockchain failed

### ISSUE THREAD

**Issue by guotie** [aptos-labs/aptos-core#3551]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
aptos move publish --named-addresses hello_blockchain=0x393a63f47da7a757a252cb44fbab2afe602efe9d88e8ae84aac7db4949a9beb0
```

**Stack trace/error message**
```
// Paste the output here
package size 1736 bytes
{
  "Error": "API error: Unknown error transaction execution failed: Move abort in 0x1::util: 0x10001"
}
```

## Expected Behavior
success publish the move module

## System information

**Please complete the following information:**
-  Aptos Core Version 
0.3.2
-  Rust Version 
1.62.1
-

**Comment by shepherd1530** [comment]
I have this issue too!

**Comment by wrwg** [comment]
This error happens during deserialization of package data, and it indicates that the aptos CLI and the network you are using don't fit to each other. Those kind of errors will be soon going away, as we do not make breaking changes anymore.

**Comment by shepherd1530** [comment]
> This error happens during deserialization of package data, and it indicates that the aptos CLI and the network you are using don't fit to each other. Those kind of errors will be soon going away, as we do not make breaking changes anymore.

I am using the v0.3.2 vli on devnet. The cli doesn't work on both devnet and my local testnet.

**Comment by newcodepusher** [comment]
in `Move.toml`
```
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-cli-v0.3.2" }

**Comment by guotie** [comment]
```
package size 1806 bytes
{
  "Error": "API error: Unknown error transaction execution failed: Move abort in 0x1::util: 0x10001"
}
```

**Comment by shepherd1530** [comment]
> ```
> package size 1806 bytes
> {
>   "Error": "API error: Unknown error transaction execution failed: Move abort in 0x1::util: 0x10001"
> }
> ```

There's a new cli version. Downloading it fixed the issue for me.

**Comment by gregnazario** [comment]
This was an issue with the CLI that was incompatible.  Until the next devnet release 0.3.1a will work with devnet, and 0.3.2 will work with AIT3

**Comment by bigwineth** [comment]
```
aptos move publish --named-addresses MoonCoin=0x393a63f47da7a757a252cb44fbab2afe602efe9d88e8ae84aac7db4949a9beb0
package size 749 bytes
{
  "Error": "API error: Unknown error transaction execution failed: Move abort in 0x1::util: 0x10001"
}
```
