### ISSUE TITLE
[Bug] Wrong path to aptos framework during aptos move init command

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#3566]
# 🐛 Bug

Aptos move init command built new `Move.toml` with framework fork instead of original repo.

## To reproduce

`aptos move init`

```
[package]
name = 'whatever'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'
```

## System information

```
aptos --version
aptos 0.3.1
```

**Comment by gregnazario** [comment]
This looked like something snuck into the codebase, it's now been fixed for 0.3.2 and will be fixed in the next version 0.3.3
