### ISSUE TITLE
Documentation Bug Fix

### ISSUE THREAD

**Issue by RishiMalhotra920** [aptos-labs/aptos-core#3571]
# 🐛 Bug

On https://aptos.dev/tutorials/first-move-module, 

change 

`cd aptos-core/aptos-move/move-examples `

to

`cd aptos-core/aptos-move/move-examples/hello_blockchain`

and change 

`aptos move build`

to

`aptos move compile`

**Comment by ChengYueJia** [comment]
@rajkaramchedu I've fixed it.

Waiting for the merged.
