### ISSUE TITLE
NFT Features

### ISSUE THREAD

**Issue by flappys** [aptos-labs/aptos-core#3578]
Can we not have these features enabled for tokens:
1. To create a token, there can be only one royalty account. What if we want multiple accounts with different percentage.
2. Can we have function to get the current count of tokens for a collection.
3. The uri holds the the link for a image/media. Can we not have the url linked to a json that stores the metadata along with url of image/media like we have in ethereum or solana.

**Comment by areshand** [comment]
@flappys  
1. please take this shared account example https://github.com/aptos-labs/aptos-core/tree/8f7dee035f38e6a2cd508b450d656e22ca2dfb03/aptos-move/move-examples/shared_account. we support creating a shared account of multiple addresses with their own percentage. So the royalty account can be one shared account.
2. we current support collection `[supply](https://github.com/aptos-labs/aptos-core/blob/3d799d6804c360c29b45b382259b82651757a6ec/aptos-move/framework/aptos-token/sources/token.move#L641)` to track number of different types of token_data. for each token_data, it has a [supply](https://github.com/aptos-labs/aptos-core/blob/3d799d6804c360c29b45b382259b82651757a6ec/aptos-move/framework/aptos-token/sources/token.move#L89) to track number of tokens minted with this token_data type.  We don't have a API for getting total number of tokens of a collection now. Maybe, could you elaborate your usecase to let us see if there is a way to support it already? 
3. you can have a link to a json. It is recommended to follow the same standard as ERC-1155

**Comment by flappys** [comment]
> 2\. We don't have a API for getting total number of tokens of a collection now

for supply, if there is an API then it becomes easier for marketplaces or even nft viewer apps.
also for getting all token from collection, there is not straight forward simple way, as i think this will be a common use case.

**Comment by areshand** [comment]
I think it makes sense to have these API. do you mind creating an feature request specifying the APIs you want?
