### ISSUE TITLE
[Bug] aptos-operational-tool broken

### ISSUE THREAD

**Issue by mishutka200101** [aptos-labs/aptos-core#358]
# 🐛 Bug

aptos-operational-tool is broken. It happened yesterday-today. People who tries to run node today and creatte their peer and private key face with problem, that peer equal to key

## To reproduce

**Code snippet to reproduce**
 $ cargo run -p aptos-operational-tool -- generate-key --encoding hex --key-type x25519 --key-file /root/test/private-key.txt
 $ cargo run -p aptos-operational-tool -- extract-peer-from-file --encoding hex --key-file /root/test/private-key.txt --output-file /root/test/peer-info.yaml

## Expected Behavior

get peer and key to configure public_full_node.yaml

## System information

**Please complete the following information:**
- latest at this time
- 
- ubuntu 20.04

**Comment by JoshLind** [comment]
Thanks for the heads up. Two quick points before digging in:
1. Can you update the issue to show the error you're receiving when running the tool?
2. If you're building the tool from the source code (which I suspect you are?): you need to be on the `devnet` branch: https://github.com/aptos-labs/aptos-core/tree/devnet. We're breaking things on `main` pretty regularly.

**Comment by mishutka200101** [comment]
![image](https://user-images.githubusercontent.com/79220116/161124561-759cd52a-f30d-4a56-b8f7-e0ad1050a2b1.png)
maybee that would be helpfull

**Comment by JoshLind** [comment]
Thanks @Pa1amar. This is a result of updating our Aptos addresses to be 32-bytes instead of 16-bytes. See the announcement in the discord: https://discord.com/channels/945856774056083548/956692649430093904/959214243733966848.
