### ISSUE TITLE
[Bug] Unexpected error: malformed utf8

### ISSUE THREAD

**Issue by davaymne** [aptos-labs/aptos-core#3583]
Installation from source failed with "Error": "Unexpected error: malformed utf8"

Followed guide - https://aptos.dev/nodes/validator-node/run-validator-node-using-source

On step 5 - Compile genesis blob and waypoint - failed:
```
aptos genesis generate-genesis --local-repository-dir ~/$WORKSPACE --output-dir ~/$WORKSPACE
```
Error:
```
{
  "Error": "Unexpected error: malformed utf8"
}


Variable:
```
echo $WORKSPACE
.aptos
```
Folder:
```
drwxr-xr-x  4 root root     4096 Aug 29 10:38 .
drwx------ 11 root root     4096 Aug 29 10:23 ..
-rw-r--r--  1 root root 15530872 Aug 19 22:27 aptos-cli-0.3.1-Ubuntu-x86_64.zip
drwxr-xr-x  2 root root     4096 Aug 29 10:38 davaymne
-rw-r--r--  1 root root   241458 Aug 29 10:36 framework.mrb
drwxr-xr-x  2 root root     4096 Aug 29 10:25 keys
-rw-r--r--  1 root root      439 Aug 29 10:09 layout.yaml
```

version: `aptos 0.3.1`

**Comment by feraudet** [comment]
Same with `aptos 0.3.2`

**Comment by spasibotebe** [comment]
same to

**Comment by x4team** [comment]
same with 0.3.2, with 0.3.1 everything is ok

**Comment by davidiw** [comment]
re-open if the issue persists.

**Comment by stevekeol** [comment]
why close the issue ?  version 0.3.4  !
