### ISSUE TITLE
Step 4 Adding module bug [Bug]

### ISSUE THREAD

**Issue by rushimanche** [aptos-labs/aptos-core#3636]
Hello,
I am following the Aptos "Your First Dapp" tutorial. Here is my [pastebin](https://pastebin.com/Y0GUfVUv) for App.tsx. When I run this in VS code, I get two errors. 
1)  Argument of type 'Dispatch<SetStateAction<MoveModule[]>>' is not assignable to parameter of type '(value: MoveModuleBytecode[]) => void | PromiseLike<void>'.
I get this error with the .then for setModules.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/61168471/187474890-f40d64df-6cb4-44df-8813-81be0f92c2ab.png">

 

2) Property 'abi' does not exist on type 'MoveModule'. It says that the property does not exist

 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/61168471/187474937-876ad48a-c78e-4002-bf4e-e47a27681c5d.png">

Let me know if I am doing something wrong.

**Comment by davidiw** [comment]
closing out, let me know if the issue persists.
