### ISSUE TITLE
[VM] Remove gating by AptosVersion

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#366]
There're a few features gated by AptosVersion in the legacy diem world, we'd want to cleanup those since all features are enabled now. 

Examples: https://github.com/aptos-labs/aptos-core/blob/6fee498bfd3c3dd19727466e9515b73cb829f416/aptos-move/aptos-vm/src/aptos_vm.rs#L217

**Comment by kris524** [comment]
Hi @zekun000 Can I take this task? Is there anything else I need to know? If not I am ready to crack on.

**Comment by zekun000** [comment]
@kris524 thanks for your passion, I'd encourage you finish one issue before starting a new one

**Comment by xxm3** [comment]
Hi @zekun000 , may I take this issue ?
