### ISSUE TITLE
Rocks => CacheLib [Feature Request]

### ISSUE THREAD

**Issue by vitruvvius** [aptos-labs/aptos-core#3679]
# 🚀 Feature Request

Since aptos & co dominated by FB employees,
curious the thought on moving off rocksdb => cachelib
https://github.com/facebook/CacheLib

Since aptos/others network-derived state, with waypoints ie checkpoints, one does not in fact require
non-volatile storage - the catch up process, with the right tooling, always required/similar cost.

It'd be interesting to hear how the team thinks about moving to a more traditional DHT... rocksdb SST & cachelib quite similar, with the exception rocksdb SST tuned for offline-storage & cachelib tuned for online storage.

**Comment by msmouse** [comment]
Thanks for your interest in Aptos! We at Aptos do keep looking for ways to scale the storage layer and/or improve overall efficiency and performance. That said, with the team focusing on hardening the current implementation and verifying it via various test networks, changing the storage model is something we are not actively investing right now.
I'm closing this for now, please stay tuned.

**Comment by vitruvvius** [comment]
Rocks will eventually integrate publicly for plug-in-play (currently merged in private repositories as a plugin) - but would have preferred to see this from day 1 :)
