### ISSUE TITLE
[Bug] Your first dapp maybe broken

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#3700]
This may be referring to a soon-to-be-deleted tutorial, I'm still looking. Opening an issue for now.

## Original bug report from email
Hello,

I am following the Aptos "Your First Dapp" tutorial. Here is my [pastebin](https://pastebin.com/Y0GUfVUv) for App.tsx. When I run this in VS code, I get two errors. 

1)  Argument of type 'Dispatch<SetStateAction<MoveModule[]>>' is not assignable to parameter of type '(value: MoveModuleBytecode[]) => void | PromiseLike<void>'.

I get this error with the .then for setModules

  
<img width="407" alt="a" src="https://user-images.githubusercontent.com/7816187/187774579-2ceb2980-5852-42f1-87f3-ee0107be0ac3.png">

2) Property 'abi' does not exist on type 'MoveModule'. It says that the property does not exist

  
<img width="407" alt="b" src="https://user-images.githubusercontent.com/7816187/187774598-9e7e149d-8076-42b8-8a26-035f213c9178.png">

Let me know if I am doing something wrong.

**Comment by rushimanche** [comment]
Hey I have this same error. These errors went away went I tried using the dapp-example within the aptos-core folder. However, I have a new error that come with that check out: https://github.com/aptos-labs/aptos-core/issues/3760.

Let me know if you make any progress
