### ISSUE TITLE
[Help] File names with colons prevent repo from cloning on windows

### ISSUE THREAD

**Issue by tanqiangyes** [aptos-labs/aptos-core#373]
## Bug

**File names with colons prevent repo from cloning on windows**

like this : **api/goldens/aptos_api::tests::accounts_test::Atest_account_modules.json**

Please rename them, thanks.

**Comment by CapCap** [comment]
Should be fixable [here](https://github.com/aptos-labs/aptos-core/blob/0233b9a8deea7d6f9f5db8eb8ae96d6e35fcb018/api/src/tests/mod.rs#L62) (and then renaming golden files).  

Could replace the colons with a unicode version, or with double underscores

**Comment by sitalkedia** [comment]
@tanqiangyes  - Thanks for reporting the issue. https://github.com/aptos-labs/aptos-core/pull/386 should address this. Please try recloning the repo and let us know if you still encounter the issue.

**Comment by tanqiangyes** [comment]
@sitalkedia now, it`s ok. thanks for it.
