### ISSUE TITLE
[Feature Request] Function In TS SDK to return resource account address from source address and seeds

### ISSUE THREAD

**Issue by dhruvja** [aptos-labs/aptos-core#3739]
# 🚀 Feature Request

I have been using resource accounts for storing data and coins. But there is no function in move that returns the resource account when source address and seeds are provided. It is also expensive to derive it on chain. So we can send the resource account from the client side. But currently there is not function that does so on client side. So i would want a function in TS or any SDK that would return the resource address when the source address and seeds are provided.

## Motivation

**Is your feature request related to a problem? Please describe.**
I use resource accounts as escrow accounts and also to store resources ( data ). I can create resource accounts using the method but when i want the resource account again which has already been created, there is no method that can give it to me. I understand that having an on-chain method that derives the address is expensive. But there is no function in client side to get the resource account as well. 

## Pitch

**Describe the solution you'd like**
I would like to have a function in the SDK which would return the resource account address when the source address and seeds are provided. I am considering a function which would run the following code

```
const` sourceAddress = "9db1d65a321e4a86f8098cb04e76fce098890b84211fa06d65f24dc644bf0fec"
const seeds = "3031"

const source = BCS.bcsToBytes(AccountAddress.fromHex(sourceAddress));

const see = new HexString(seeds).toUint8Array();

let originBytes = new Uint8Array(source.length + see.length);
  
originBytes.set(source);
originBytes.set(see, source.length);

const hash = new SHA3(256);

hash.update(Buffer.from(originBytes));
const calculatedResourceAddress = hash.digest('hex');
```

**Describe alternatives you've considered**
The alternative i have considered is using the above the code snippet.

**I would love to open a Pull request to add this feature to the SDK.**

**Comment by gregnazario** [comment]
I think this would be a great feature to add to the SDK, if you want to open a pull request you can and we can review it

**Comment by dhruvja** [comment]
> I think this would be a great feature to add to the SDK, if you want to open a pull request you can and we can review it

Ya sure, i will open a PR soon.
