### ISSUE TITLE
[Bug] aptos module - The requested method and/or account has not been authorized by the user.

### ISSUE THREAD

**Issue by rushimanche** [aptos-labs/aptos-core#3760]
# 🐛 Bug

## Steps to reproduce

Go through the "[your first dapp](https://aptos.dev/tutorials/your-first-dapp/)" tutorial. The tutorial didnt really work for me so I just used the dapp example in the aptos core repo. /aptos-core/developer-docs-site/static/examples/typescript/dapp-example/src.

When I first publish a module, it shows up in the aptos explorer properly. 
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/61168471/188040958-31554ceb-d1ca-496e-8c7d-e9ecb1f7fec7.png">

However, when I try running the App.tsx, I notice this error in the browser: **The requested method and/or account has not been authorized by the user.** I am using the Petra Aptos Wallet.
** Error message or problem **
```
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/61168471/188041022-eba8fa6c-f882-42ac-b5d9-437ee7ad3747.png">

```

## Expected Behavior
 
 I expected the code the getAccountModules method to be able to return the modules for the designated account and render it within the browser. However, I am unable to do so. This is on chrome.
 
## System information

**Please complete the following information:**
Chrome (latest)

**Comment by 1500256797** [comment]
i also meet this bug.
```
Uncaught (in promise) 
{message: 'The requested method and/or account has not been authorized by the user.', code: 4100, name: 'Unauthorized'}
code
: 
4100
message
: 
"The requested method and/or account has not been authorized by the user."
name
```

**Comment by 1500256797** [comment]
> # 🐛 Bug
> ## Steps to reproduce
> Go through the "[your first dapp](https://aptos.dev/tutorials/your-first-dapp/)" tutorial. The tutorial didnt really work for me so I just used the dapp example in the aptos core repo. /aptos-core/developer-docs-site/static/examples/typescript/dapp-example/src.
> 
> When I first publish a module, it shows up in the aptos explorer properly. <img alt="image" width="1594" src="https://user-images.githubusercontent.com/61168471/188040958-31554ceb-d1ca-496e-8c7d-e9ecb1f7fec7.png">
> 
> However, when I try running the App.tsx, I notice this error in the browser: **The requested method and/or account has not been authorized by the user.** I am using the Petra Aptos Wallet. ** Error message or problem **
> 
> ```
> <img width="1594" alt="image" src="https://user-images.githubusercontent.com/61168471/188041022-eba8fa6c-f882-42ac-b5d9-437ee7ad3747.png">
> ```
> 
> ## Expected Behavior
> I expected the code the getAccountModules method to be able to return the modules for the designated account and render it within the browser. However, I am unable to do so. This is on chrome.
> 
> ## System information
> **Please complete the following information:** Chrome (latest)

i solved bug by  adding  `aptos.connect()`

like this 
```

import { useEffect,useState } from "react";
import { Types, AptosClient } from 'aptos';


declare global {
  interface Window { aptos: any; }
}

// Create an AptosClient to interact with devnet.
const client = new AptosClient('https://fullnode.devnet.aptoslabs.com/v1');

export default function Home() {
   // Retrieve aptos.account on initial render and store it.
   const [address, setAddress] = useState<string | null>(null);
   useEffect(() => {
     window.aptos.connect();
     window.aptos.account().then((data : {address: string}) => setAddress(data.address));
   }, []);

  // Use the AptosClient to retrieve details about the account.
  const [account, setAccount] = useState<Types.AccountData | null>(null);
  useEffect(() => {
    if (!address) return;
    client.getAccount(address).then(setAccount);
  }, [address]);
 
  return (
    <>
        {/* <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1> */}
        <p><code>{ address }</code></p>
        <p><code>{ account?.sequence_number }</code></p>
    </>

  )
}

```

**Comment by rushimanche** [comment]
> > # 🐛 Bug
> > ## Steps to reproduce
> > Go through the "[your first dapp](https://aptos.dev/tutorials/your-first-dapp/)" tutorial. The tutorial didnt really work for me so I just used the dapp example in the aptos core repo. /aptos-core/developer-docs-site/static/examples/typescript/dapp-example/src.
> > When I first publish a module, it shows up in the aptos explorer properly. <img alt="image" width="1594" src="https://user-images.githubusercontent.com/61168471/188040958-31554ceb-d1ca-496e-8c7d-e9ecb1f7fec7.png">
> > However, when I try running the App.tsx, I notice this error in the browser: **The requested method and/or account has not been authorized by the user.** I am using the Petra Aptos Wallet. ** Error message or problem **
> > ```
> > <img width="1594" alt="image" src="https://user-images.githubusercontent.com/61168471/188041022-eba8fa6c-f882-42ac-b5d9-437ee7ad3747.png">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Expected Behavior
> > I expected the code the getAccountModules method to be able to return the modules for the designated account and render it within the browser. However, I am unable to do so. This is on chrome.
> > ## System information
> > **Please complete the following information:** Chrome (latest)
> 
> i solved bug by adding `aptos.connect()`
> 
> like this
> 
> ```
> 
> import { useEffect,useState } from "react";
> import { Types, AptosClient } from 'aptos';
> 
> 
> declare global {
>   interface Window { aptos: any; }
> }
> 
> // Create an AptosClient to interact with devnet.
> const client = new AptosClient('https://fullnode.devnet.aptoslabs.com/v1');
> 
> export default function Home() {
>    // Retrieve aptos.account on initial render and store it.
>    const [address, setAddress] = useState<string | null>(null);
>    useEffect(() => {
>      window.aptos.connect();
>      window.aptos.account().then((data : {address: string}) => setAddress(data.address));
>    }, []);
> 
>   // Use the AptosClient to retrieve details about the account.
>   const [account, setAccount] = useState<Types.AccountData | null>(null);
>   useEffect(() => {
>     if (!address) return;
>     client.getAccount(address).then(setAccount);
>   }, [address]);
>  
>   return (
>     <>
>         {/* <h1 className="text-3xl font-bold underline">
>           Hello world!
>         </h1> */}
>         <p><code>{ address }</code></p>
>         <p><code>{ account?.sequence_number }</code></p>
>     </>
> 
>   )
> }
> ```

@1500256797 then I came across this error:

```
Module not found: Error: Can't resolve 'stream' in '/Users/rushikesh/Documents/GitHub/first-dapp/node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

```
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/61168471/188181590-f860ff93-f5fb-42f5-bbba-7d0b46937b40.png">

Did you figure it out?

**Comment by anlett10** [comment]
It works with create-next-app --typescript

**Comment by davidiw** [comment]
does this issue still exist? closing out, please re-open if it does.
