### ISSUE TITLE
[Feature Request] Create a messageboard demo

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#381]
# 🚀 Feature Request

## Motivation

This is to create messageboard to demonstrate the capability of Aptos blockchain

## Pitch

**Describe the solution you'd like**
1. A move module with admin of the messageboard, participants of the messageboard, pinned message
2. move script to support sending pinned message to the messageboard and view the pinned message
3. participants can get notified of the new messages if the pinned the message updated or a member send a message.

**Comment by areshand** [comment]
cc: @davidiw

**Comment by davidiw** [comment]
I like it! I think there's a lot of questions about what is the right way to do this in Move as there are many models, what I might propose is that we:
* Have an event to emit messages
* Store the last message (for vanity, I guess)
* Supports both an ACL for who can post
* Have a capability for who can modify the ACL

**Comment by areshand** [comment]
https://github.com/aptos-labs/aptos-core/pull/546
