### ISSUE TITLE
[move] improve resource account and friends

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#3818]
Current code: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/resource_account.move
Current tests: https://github.com/aptos-labs/aptos-core/blob/84fedee82cae6c5a6391e559a8fc121753aeea3a/aptos-move/e2e-move-tests/tests/code_publishing.rs#L276

Goals:
* Create an example of how someone can use `create_resource_account_and_publish_package` and some other logic to have the `signer_cap` be stored in the module, e.g., `init_module` is programmed with the creator address and calls `retrieve_resource_account_cap`.
* Make a CLI extension that supports deploying a package via `create_resource_account_and_publish_package`
* Explore potentially add this to the CLI

**Comment by osmantuzcu2** [comment]
Is tehere any updates about this?

**Comment by chloeqjz** [comment]
resource account tutorial PR: https://github.com/aptos-labs/aptos-core/pull/4097
resource account command PR: https://github.com/aptos-labs/aptos-core/pull/5354
