### ISSUE TITLE
Vec<u8> input to function, with the purpose to serialize/deserialize Move structs [Feature Request]

### ISSUE THREAD

**Issue by vitruvvius** [aptos-labs/aptos-core#3865]
# 🚀 Feature Request

(i) will  Vec< u8 > become a type that one can pass into functions?
(ii) will contract structs be able to serialize/deserialize into Vec<u8>?

important in designing our system.

most our apis/function 
the following pattern

fun put(
  addr: &signer, 
  data: &vec< u8 >
): acquires Trace {
  let inp = Trace::decode(data)
  for i in inp.list {
     let next = get(i.key)
     next = merge(i, next)
  }
}

w/ a simple data type as such:
struct Trace {
  data: Vec< u128 >,
  unit: u128,
  attr: u128,
  list: Vec< Trace >
}

this helps simplify txs during external state management,
and "rollup/batching" for better efficiency 🙂 that is, we can send
100_000 txs/traces/etc in a single function call! of course, it would
be great to have all of these propogate as a single unit (one by one, tx by tx hash), but
the common outcome of most kernels is that they go through
cycles of batching due to overhead....

## Motivation

**Is your feature request related to a problem? Please describe.**
The precise quantitative problem the networks loss function. 

This is the best way nowadays to describe reliability. When a client makes an API request, submits a request, and receives a response, what's the likelihood that transaction stored/readable? (ie, end to end reliability!)

This lowers the loss function today. Batching! Better state management! Cost of txs!

## Pitch

**Describe the solution you'd like**
Vec< u8 > as an input
Move function to deserialize/serialize structs

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Of course!

**Comment by davidiw** [comment]
We already have a few tracking tasks to add support for input structs on functions. There are precursors around validation and appropriate gas charge. Similarly, our current model for friends limits the ability to expose serialization primitives on chain in the fear that someone produces a struct that they should not :(. We'll figure it out and update in due time :)

**Comment by vitruvvius** [comment]
I would highly recommend implementing
arbitrary serialization/deserialization for the
sake of the community

We should all be able to in fact decide what type
of serialize/deserialize library implemented

That highlights a flaw in the Aptos Move programs,  at best.

**Comment by davidiw** [comment]
Implementing it without great care would result in the ability to generate any struct without permissions, it would completely violate move security.
