### ISSUE TITLE
[NHC] Add support for configuring baseline with many nodes

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#3913]
Currently NHC only supports configuring each baseline with a single baseline node. In terms of scale, you might say, oh just run many nodes behind a load balancer, right? Unfortunately with this setup, we run into consistency issues, where we might, for example, pull the latest transaction version from one node, and then try to pull that transaction by version from another node and fail, because the other node isn't as up-to-date.

To address this, we could make it possible for a baseline configuration to be configured with many nodes (not behind a LB), and for each run, it picks one to use for the whole run.

First we should see if we can do some kind of sticky routing in the LB based on the source address.

**Comment by banool** [comment]
To speak more about the problem I'm seeing. Currently this can fail:

-  Request 1: Get latest ledger version from node.
-  Request 2: Try to get transaction at that version from node.

Why? Because if the node in question uses a LB (or DNS with multiple IPs behind it) and behind that LB there are multiple nodes, NHC could hit a different node each time.

**Comment by sherry-x** [comment]
sticky routing make sense in this case, also I wonder if we can tolerate a range of difference, assume all fullnodes behind the LB is within some range of differences, and then we check the lower bound. Others also tried to solve this issue by applying consensus on top of the fullnode versions...so you query a handful of fullnodes and use the version that agreed by majority.

**Comment by banool** [comment]
Currently the check in question works roughly like this:
1. Get latest version from both nodes. Take the min of these.
2. Get the oldest version from both nodes. Take the max of these.
3. Ensure there is some gap between these two values.
4. Get the transaction using the latest shared version (from 1).

I could instead fetch a version in the middle (https://github.com/aptos-labs/aptos-core/pull/3911). This makes it much more likely it will succeed, unless there is a fullnode that is super far behind / completely stuck.

**Comment by banool** [comment]
This PR makes NHC work properly with a LB that's using cookie based sticky routing. This should be sufficient for now.
