### ISSUE TITLE
Why don't extract the dev-docs-site part  in a new project.

### ISSUE THREAD

**Issue by ChengYueJia** [aptos-labs/aptos-core#3974]
## ❓ Questions and Help

Feels the whole project  a little crowded .

So, Why don't extract the documents part  in a new project.

**Comment by banool** [comment]
The dev docs site use code snippets from elsewhere in the repo. Keeping them together in the same repo makes it easy for us to verify that the docs build with the snippets correctly as part of CI/CD.

I'll close this for now but if you have more questions / a good reason why we should split the dev docs site out, please feel free to re-open it.
