### ISSUE TITLE
[Feature Request] I18n the docs.

### ISSUE THREAD

**Issue by ChengYueJia** [aptos-labs/aptos-core#3975]
# 🚀 Feature Request

## Motivation

It's time for us to i18n the [dev docs](https://aptos.dev), white-papers etc.

## Pitch

**Describe the solution you'd like**
1. enable the i18n for the site. 
2. choose a TMS such as crowdin3. 
3. open the ability of TMS for community4. 
4. CI the i18n from TMS to repo.

## Additional context
Docs of ethereum is a good example.

**Comment by CapCap** [comment]
Yes, yes it is :-)

we are already ready with crowdin, and we’ll be able to get to this in the next few months! 

White papers are a bit harder though, as they are written in Latex

**Comment by ChengYueJia** [comment]
Can community join the crowdin?
if can, how to join? @CapCap
