### ISSUE TITLE
[Bug] panicked at 'Crashing after 330s no progress', consensus/src/epoch_manager.rs:849:37

### ISSUE THREAD

**Issue by gaia** [aptos-labs/aptos-core#3977]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
`cargo run -p aptos-node --release -- -f /home/ubuntu/testnet/config/validator.yaml`

**Stack trace/error message**
https://pastebin.com/raw/nkkbnYGN

## System information

**Please complete the following information:**
- 392dbd870a5dfc8e02503f8b2537903dc259baf1
- rustc 1.62.1
- Ubuntu 22.04.1

**Comment by sitalkedia** [comment]
@gaia - Thanks for reporting this issue. We are aware of this and there is a fix out, which will go out in the next release shortly - https://github.com/aptos-labs/aptos-core/pull/3948/. Please stay tuned to our AIT3 announcment channel for the next release with the fix.

**Comment by sitalkedia** [comment]
Closing this as no further action is needed on this.
