### ISSUE TITLE
[Feature Request] Checkout with local branch rather than origin branch in devnet tutorial

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#400]
Devnet tutorial should be `git checkout devnet` rather than `git checkout origin/devnet`, so that a detached HEAD state isn't used.  Then users can simply later `git pull` without issue.

https://aptos.dev/tutorials/run-a-fullnode#using-aptos-core-source-code

**Comment by gregnazario** [comment]
Your thoughts @rajkaramchedu?  This was a suggestion from the Discord

**Comment by rajkaramchedu** [comment]
This, for example: https://github.com/aptos-labs/aptos-core/pull/687#discussion_r860460650

**Comment by gregnazario** [comment]
> I was actually thinking we should recommend fork and then clone followed by `git checkout devnet` so we are consistent with how we internally do things (by forking first, and not cloning directly the aptos-core repo). Does that help address this issue? If not, then I am out of my depth on Git nuances here. 

It might be a little weird though, since not everyone is a developer to do a fork.  But that could also work

**Comment by rajkaramchedu** [comment]
I used `git checkout --track origin/devnet` after fork and clone. This feels a bit more sure way of tracking the fork HEAD state. Of course this means you fetched and merged your fork before you began setting up the fullnode.
