### ISSUE TITLE
[Feature Request] Being Able to Move StakePool.pending_active -> StakePool.inactive?

### ISSUE THREAD

**Issue by PaulFidika** [aptos-labs/aptos-core#4073]
I noticed that in the stake.move module, there is a way to move StakePool.pending_inactive -> StakePool.active; the function is called `reactivate_stake`.

However, there is no function that can move StakePool.pending_active -> StakePool.inactive. So basically, once you put AptosCoin into the pending_active balance, there's no way to take it back out again, other than to wait for the next epoch to occur, have the stake be moved into active, and then manually move it to pending_inactive, wait for pending_inactive_secs to expire, and then wait for the next epoch-boundary to sweep the money back into inactive. This could be a 14 - 28 day process (dependent upon the pending_inactive_secs value).

I could create a function that does this easily, however looking at the stake module makes me feel like this was an intentional omission. In the sense that allowing people to put lots of pending-stake in the current epoch, and then remove it right before the next epoch, might present some security risk. There seems to be a lot of logic around trying to predict voting power in the next epoch and making sure it doesn't increase too rapidly.

Thoughts?

**Comment by movekevin** [comment]
This is something we have on our list for implementation in Q1'23

**Comment by xindingw** [comment]
This is intended. pending_active also has voting power(check [here](https://github.com/aptos-labs/aptos-core/blob/b43e7c513b8d33faf1831a8467ff2372bdacc790/aptos-move/framework/aptos-framework/sources/aptos_governance.move#L437)). So it should freeze until the next lockup period.
