### ISSUE TITLE
[Bug] sdk package import

### ISSUE THREAD

**Issue by magnum6actual** [aptos-labs/aptos-core#408]
# 🐛 Bug

Starting to take a look at the typescript sdk, a couple of issues:

The example code as written won't work:
```typescript
import { AptosAccount, AptosClient } from "aptos"
const aptos = new AptosClient("https://fullnode.devnet.aptoslabs.com/");
const account = new AptosAccount();
const accountInfo = await client.getAccount(account.address());
```
the code in line [36](https://github.com/aptos-labs/aptos-core/blob/eb6f2d8a72c562e40f3c222d24b8d2eaca4b5a9a/ecosystem/typescript/sdk/README.md?plain=1#L36) was probably intended to be:
`const accountInfo = await aptos.getAccount(account.address());`
or swapping out aptos/client the other way.  Easy enough to fix.

The bigger issue is I cannot import `AptosAccount` from the package. I get `Module '"aptos"' has no exported member 'AptosAccount'.ts(2305)` and that's whether I import from the installed npm package or if I link directly to my cloned repo (freshly updated).  I can import AptosAccount if I link directly to "aptos_account.ts" though.

I won't have time to drill down into this until later in the week, but thought I'd put it on the teams radar.

**Comment by CapCap** [comment]
Sorry about that, and thank you for opening the issue :-) Fixed in https://github.com/aptos-labs/aptos-core/pull/418 - and added example folders for both typescript and javascript
