### ISSUE TITLE
[Feature Request] Lockup Expiration Event in stake.move

### ISSUE THREAD

**Issue by PaulFidika** [aptos-labs/aptos-core#4080]
In the stake.move module, `on_new_epoch` will call into `update_stake_pool`, which will process the unlocking of coins if it's time to do so (moving `stake_pool.pending_inactive` to `stake_pool.inactive`). However there is no event associated with this. This means it's difficult to for any external module to tell if an unlock has occurred; they can monitor the locked_until_secs parameter, but that's an imperfect measure because it can be bumped up by the `increase_lockup_with_cap` method as well as an actual unlock occuring.

There is an event associated with `increase_lockup_with_cap()`, so I think we should have an event that is triggered every time a lockup expires as well. Thoughts?

**Comment by davidiw** [comment]
One can listen for a new epoch event. https://github.com/aptos-labs/aptos-core/blob/1b8c0b9142d9fca4c7b1b7eadfc68f5320367ce4/aptos-move/framework/aptos-framework/sources/reconfiguration.move#L125

unfortunately we are no longer able to make modifications to this. I'll tag @movekevin .

**Comment by PaulFidika** [comment]
Why can't we make modifications to this file? I know there's going to be a code-lock for mainnet; is that code lock already in effect? After mainnet / code lock, what will be the process for adding functionality to core modules like reconfiguration.move?
