### ISSUE TITLE
is coin amount u64 enough?

### ISSUE THREAD

**Issue by guotie** [aptos-labs/aptos-core#4086]
### Please note that this issue tracker is not a help form and this issue will be closed.

is coin amount u64 enough? If decimals is 18, max u64 is just 18.446744073709553.
```
 0xffffffffffffffff/1e18
18.446744073709553
```

**Comment by davidiw** [comment]
At this point the coin amount is u64, it is unchangeable. We may consider larger numbers if we update to a coinv2 standard. It is also worth considering why you would want a coin that needs that much expressability.
