### ISSUE TITLE
[indexer schema] Create secondary btree index on inserted_at column in each table that is replicated to stitch

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#4093]
https://aptos-org.slack.com/archives/C041GNZC4TZ/p1662939359501349?thread_ts=1662939038.211849&cid=C041GNZC4TZ

Ran this manually for the writeset table to fix immediate problem:
```
CREATE INDEX concurrently write_set_changes_inserted_at ON write_set_changes(inserted_at);
```
but we should have this index on every table that is being replicated via stitch

**Comment by davidiw** [comment]
let's re-open if this isn't addressed..
