### ISSUE TITLE
[Bug] missing field `state_root_hash` when publishing

### ISSUE THREAD

**Issue by Fooooooooooox** [aptos-labs/aptos-core#4105]
# 🐛 Bug

"Error": "API error: error decoding response body: missing field `state_root_hash`" when I'm trying to publish a module.

## To reproduce

I use the [hello_blockchain.move example code ](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move)

These are my command:

```shell
aptos init
aptos move compile
aptos move publish
```

This is my Move.toml:
**Code snippet to reproduce**
```rust
[package]
name = 'example_project'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
Sender = "0xAFC93B69BB6960FF6FAE5B4D5B6B6790D870A9ABEEEBE391D0707853A1054969"

```

**Stack trace/error message**
```
-> % aptos move publish                                                                                     
{
  "Error": "API error: error decoding response body: missing field `state_root_hash`"
}
```

## System information

**Please complete the following information:**
-  aptos 0.3.1
-  rustc 1.63.0
-  mac monetary 12.3.1

**Comment by Fooooooooooox** [comment]
thanks for your reply.
i just updated my aptos cli into 0.3.3, and it worked.

but I noticed that there is no funding to the account anymore...
<img width="1030" alt="Screen Shot 2022-09-13 at 20 28 10" src="https://user-images.githubusercontent.com/83564432/189900958-41294cae-b299-4895-afe6-8e08cfd55750.png">

how can i fund my account now?

**Comment by banool** [comment]
Try `aptos account fund-with-faucet`. Thanks, if you see the original issue appear again please re-open this issue.
