### ISSUE TITLE
[Bug] Inconsistency between Move.toml and source code addresses

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#411]
# 🐛 Bug

At the [page](https://aptos.dev/tutorials/your-first-transaction) of the official tutorial, you rely on buggy behaviour, which allows to specify hex address without prefix. In case of hex number without a-f symbols in it, it could leads to confusion, as same address would mean different things in manifest and in sources.

Using `0x`  also make it easier to understand, as move users got used to the mandatory prefix in addresses.

See the linked [issue](https://github.com/diem/move/issues/141) in Move.

## To reproduce

* Go to [tutorial](https://aptos.dev/tutorials/your-first-transaction).
* See addresses in the output:

```sh
=== Addresses ===
Alice: e26d69b8d3ff12874358da6a4082a2ac
Bob: c8585f009c8a90f22c6b603f28b9ed8c
```
* Try to update `Move.toml`  with provided address:

```sh
A1 = "0xe26d69b8d3ff12874358da6a4082a2ac" # with prefix
A2 = "e26d69b8d3ff12874358da6a4082a2ac" # without prefix
```

## Expected Behavior

Would be good to create and follow some standard which allows to use addresses only with `0x` prefix, also in `Move.toml`.

**Comment by gregnazario** [comment]
Thanks for reporting the bug!  I've bene looking into what we can do in general to help this experience so that it's consistent with `0x` in front.
