### ISSUE TITLE
[Feature Request] Convert genesis.sh to python or rust

### ISSUE THREAD

**Issue by zcchahaha** [aptos-labs/aptos-core#4153]
More context: https://aptos-org.slack.com/archives/C03PKBQM2RY/p1662750492710499?thread_ts=1662750269.800579&cid=C03PKBQM2RY

**Comment by davidiw** [comment]
I'm not sure I see the issue with this being in bash. These are a bunch of ... CLI commands.

**Comment by gregnazario** [comment]
Using bash for a large script become in maintainable at some point.  Given there have been multiple instances where people have mistyped something into this script, I asked her to open this
