### ISSUE TITLE
Remove codegen deps in `dev_setup.sh`

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#4203]
Before doing this we should decide what we want to do with codegen, if any, but I'm sure there are items we could remove now if we wanted. For example, generating Python code that requires numpy is clearly bad.

**Comment by davidiw** [comment]
Do we still need numpy?

**Comment by davidiw** [comment]
this is actually pretty easy... we don't need any of that stuff... sending out a quick pr...

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/pull/4530
