### ISSUE TITLE
[Feature Request] A new and more detail  figure for Life of a Transaction

### ISSUE THREAD

**Issue by ChengYueJia** [aptos-labs/aptos-core#4304]
# 🚀 Feature Request

## Motivation

 In Dev-docs, there are some mistakes in the present figure-1.0 Life of a Transaction,
And the figure is lack of some details.

So I've draw a new and more detail one according to the docs.

Hope this can help all you guys.
If there is any problem in the figure, I'll appreciate it to point it out. 

## Pitch

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/108982045/190839190-0b3748b0-5325-4318-b7b3-70019bf7ea6c.png)

## Additional context

* here is the older one. 
https://aptos.dev/guides/basics-life-of-txn

![image](https://user-images.githubusercontent.com/108982045/190839340-7a2ad6c0-19d5-49e1-a359-d4c0b7fee987.png)

**Comment by davidiw** [comment]
Thanks this is great. There's a lot to go through there, but one quick call out, FNs talk the same aptos-net as they do to validators, only clients communicate via rest... that's the uglies thing about the whole diagram :/

**Comment by rajkaramchedu** [comment]
Thanks, @ChengYueJia. I will go over it next week. We are sticking to a consistent style for the diagrams, see here: https://aptos.dev/concepts/basics-txns-states and each diagram must have the dark mode equivalent. With these in mind, I will take a look. Thanks for the great work here!
