### ISSUE TITLE
[Feature Request] increase max transaction size for package uploading

### ISSUE THREAD

**Issue by fardream** [aptos-labs/aptos-core#4311]
# 🚀 Feature Request

Increase max transaction size of 32KB for package uploading

## Motivation

The max transaction size of 32KB is very limiting for uploading packages.

We have some source codes ~4000 lines and they already compile into more than 32KB with the `--include-artifacts none` option.

## Pitch

I understand the general concern of the transaction size, but for uploading package 32 bytes looks to be too small.

**Comment by leofisG** [comment]
We have encountered the same issue. And we have to extract some of our logic into a separate package. However, this process is not smooth since we must be careful not to create any circular dependency. It would be a lot easier if we could lift the limit.

**Comment by yuhanfang** [comment]
> To resolve this, we have to extract some of our logic into a separate package. However, this process is not smooth since we must be careful not to create any circular dependency. It would be a lot easier if we could lift the limit.

Completely agree with this. It's possible to work around, but it's adding a weird (and extremely intrusive!) gotcha to the developer experience. Wish I could give more than one thumbs up to this.

**Comment by PaulFidika** [comment]
Agreed. I think the best solution would be to increase the tx size limit to at least 128 KBs, or to allow modules to be deployed in pieces through a series of multiple transactions; a feature like this could be added to the Aptos CLI. We have to consider also that people will be including module artifacts on-chain as well (entire source-code files).

**Comment by davidiw** [comment]
We've bumped it up to 64KB. We will look into adding this to the CLI. Please note you can add `included-artifacts none` to reduce the size of your modules. Also note, that a package need only contain all friend modules. Those that are not friends can be published on the same address in different packages.
