### ISSUE TITLE
[Bug] Missing an installation guide for Windows OS

### ISSUE THREAD

**Issue by joaoaccaldeira** [aptos-labs/aptos-core#4335]
# 🐛 Bug

It is not possible to run ./scripts/dev_setup.sh on Windows. I alerted the team to this and they said it required some manual dependency additions and that it needed to be written up. They asked me to raise an issue here about it, so here it is.

**Comment by gregnazario** [comment]
This installation is just for developing with the direct `aptos-core` codebase.  Note that the CLI (minus the prover), will work out of the box with the precompiled binaries in the releases page.

I just started a new Windows EC2 instance to try it out

**Comment by gregnazario** [comment]
Thanks for being patient!  We should now have better Windows installation information here https://aptos.dev/cli-tools/aptos-cli-tool/install-aptos-cli

Please feel free to open other issues around feedback around them
