### ISSUE TITLE
[Bug] Fullnode get account transactions API not returning most recent transaction data for devnet

### ISSUE THREAD

**Issue by ElvisYong** [aptos-labs/aptos-core#4372]
# 🐛 Bug

## To reproduce
Take a look at transaction version [13988034](https://explorer.devnet.aptos.dev/txn/13988034), it was done by account sender `0x7d3e4478aca5d653293673148583ab042603956b88c0dd232b9abec6286a0725`, however when we query the full node's getAccountTransactions api, we would only get data up till version `12527848` and I was unable to get data until `13988034` even after including the `start` version from `12527848`.

**Curl requests that were made to check the data**
```
curl --request GET \
  --url https://fullnode.devnet.aptoslabs.com/v1/accounts/0x7d3e4478aca5d653293673148583ab042603956b88c0dd232b9abec6286a0725/transactions \
  --header 'Content-Type: application/json'
```
and 

```
curl --request GET \
  --url 'https://fullnode.devnet.aptoslabs.com/v1/accounts/0x7d3e4478aca5d653293673148583ab042603956b88c0dd232b9abec6286a0725/transactions?start=12527848' \
  --header 'Content-Type: application/json'
```

## Expected Behavior
To be able to get transactions made by the account, including the latest transactions.

**Comment by jjleng** [comment]
Will get this fixed soon. But for now, you should use sequence numbers as pagination offset. try this 
```
curl -fsSL --request GET \
  --url 'https://fullnode.devnet.aptoslabs.com/v1/accounts/0x7d3e4478aca5d653293673148583ab042603956b88c0dd232b9abec6286a0725/transactions?limit=2&start=93214' \
  --header 'Content-Type: application/json'
```

**Comment by ElvisYong** [comment]
> Will get this fixed soon. But for now, you should use sequence numbers as pagination offset. try this
> 
> ```
> curl -fsSL --request GET \
>   --url 'https://fullnode.devnet.aptoslabs.com/v1/accounts/0x7d3e4478aca5d653293673148583ab042603956b88c0dd232b9abec6286a0725/transactions?limit=2&start=93214' \
>   --header 'Content-Type: application/json'
> ```

@jjleng Awesome! Just to clarify would the future release be using the sequence number instead of the version number for this api?

**Comment by davidiw** [comment]
versions make sense when querying for all transactions
sequence numbers make sense when querying from an account
our APIs will not support mixing between the two
