### ISSUE TITLE
Faucet is not running

### ISSUE THREAD

**Issue by qpb8023** [aptos-labs/aptos-core#4373]
### Please note that this issue tracker is not a help form and this issue will be closed.
aptos node run-local-testnet --with-faucet
```
Completed generating configuration:
	Log file: "/root/.aptos/testnet/validator.log"
	Test dir: "/root/.aptos/testnet"
	Aptos root key path: "/root/.aptos/testnet/mint.key"
	Waypoint: 0:e4d9fac01bcaf4f25db20169662f477fc45bf31db5b855c5c592ca2f45d208dc
	ChainId: testing
	REST API endpoint: http://0.0.0.0:8080
	Metrics endpoint: http://0.0.0.0:9101/metrics
	Aptosnet Fullnode network endpoint: /ip4/0.0.0.0/tcp/6181

Aptos is running, press ctrl-c to exit

{
  "Error": "Unexpected error: Failed to startup local node before faucet"
}

```

**Comment by ChengYueJia** [comment]
It works fine for me.

May be you can try more. 

![image](https://user-images.githubusercontent.com/108982045/191900843-08a0c065-3783-4cb7-a00f-32aea9392301.png)

**Comment by davidiw** [comment]
I run this on a daily basis. We'll need a lot more info to repro. Feel free to re-open if you can help us here.
