### ISSUE TITLE
[Bug] deposit_token causes Tokens to lose properties

### ISSUE THREAD

**Issue by jquesnelle** [aptos-labs/aptos-core#4384]
# 🐛 deposit_token causes Tokens to lose properties

When transferring a `Token` to an account via `aptos_token::token::deposit_token` the resulting `Token` will lose any `token_properties`. The main cause is because `direct_deposit` calls `merge` if the destination account already has an entry for the `token_id` -- and `merge` simply increases the `amount` value of the entry. However, immediately before calling `direct_deposit`, `deposit_token` calls `initialize_token` which will create an empty entry (`amount = 0`, empty properties) under the `token_id`, which means that the condition to call `merge` (i.e. `token_id` already has an entry) will always be true, causing just the empty token's `amount` to increase rather than assuming the `token_properties` of the incoming `Token`.

## To reproduce

In `test_mutate_token_property`, replace 

```
initialize_token_store(owner);
opt_in_direct_transfer(owner, true);
transfer(creator, new_id_1, signer::address_of(owner), 1);
```

with

```
direct_transfer(creator, owner, new_id_1, 1);
```

This will cause the test to fail.

## Expected Behavior

The above two alternate methods for transferring produce the same results.

## System information

- Aptos Core `971c160079263a8d3e1d2503a570b01ecaaf10ba` (devnet 2022/15/09)

## Additional context

`initialize_token` seems to be unneeded within the framework, and calling it can cause `Token`s with custom `token_properties` to fail in unexpected ways, depending on the order of calls.

**Comment by areshand** [comment]
thanks for the report. This is indeed a bug!
