### ISSUE TITLE
[Feature Request] Gas used in a TX

### ISSUE THREAD

**Issue by ahermida** [aptos-labs/aptos-core#4390]
# 🚀 Feature Request

An interface for getting the current transaction's gas used would be extremely useful. 

## Motivation

**Is your feature request related to a problem? Please describe.**

Trying to do transaction scheduling is really hard to do in a trustless way without being able to calculate total spend. Gas used and the gas price the tx was sent with are important here. 

So a crank architecture is hard to do well with what's currently available in terms of rewarding the crank turner. 

## Pitch

**Describe the solution you'd like**

it would be awesome if we could use a `gas` module like so
```move
use aptos_framework::gas;
use crank::escrow;

const REWARD = 100;

public fun do_something_expensive(account: &signer, crank_escrow: addr) {
    call_expensive_function();
    let gas_used = gas::current_gas_used(); // u64 (should include the cost of calling this function)
    let gas_price = gas::current_gas_price();
    // or 
    // let gas_price = @switchboard::aggregator::latest_value(escrow::gas_price_feed_addr(crank_escrow));
   
    // cover the cost of the tx + the reward for doing the expensive action
    escrow::payout(account, escrow, gas_used * gas_price + reward);
}
```

**Describe alternatives you've considered**

There is no alternative that I can think of for getting the gas used from within a tx (in a trustless way).

For my use case, I'll be manually figuring out gas costs for each of these cranked operations (once we know what these are).  Each operation's gas cost could be a setting in a shared resource. Of course this will be a bit trickier.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by davidiw** [comment]
We've already seen a proposal for giving rewards / tips to the validator. The challenge here is that this defeats parallelism in our current model. We have the aggregator framework that we're looking to expand upon. At which point gas will be paid to the validator. One could also pay into that fund to give additional rewards to the validator. It is on the roadmap... a roadmap which we haven't published :P
