### ISSUE TITLE
[Feature Request] Support `u128` in `Coin`

### ISSUE THREAD

**Issue by leina05** [aptos-labs/aptos-core#4393]
# 🚀 Feature Request

Request to update the `Coin` struct in `coin.move`:

```
    struct Coin<phantom CoinType> has store {
        /// Amount of coin this address has.
        value: u64,
    }
```

to use `u128` for `value`, and update all associated modules/functions (e.g. `transfer()`, `mint()`) to use `u128` as well.

## Motivation

**Is your feature request related to a problem? Please describe.**

`u64` severely limits the quantity of tokens that can be stored in a single account on-chain. For example, ETH canonically has 18 decimals. With `U64_MAX = 18446744073709551615`, the most ETH that a single account can hold is ~18 ETH, as only one coin store per coin type can be stored in a single account.

## Pitch

**Describe the solution you'd like**
The change is straightforward, although it would be a significant breaking change. I think it is worth it in the long run, unless there is a reason not to support this that I'm not aware of.

**Describe alternatives you've considered**
The only alternative would be to use multiple accounts (e.g. resource accounts) to store overflow coin balances. However, this still doesn't solve the problem of transferring an overflowing quantity to another account.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

yes, although this may be something better handled by the core team

**Comment by PaulFidika** [comment]
This is actually a really good point I hadn't thought of. There will be lots of bridged tokens from Ethereum, and they use much higher decimal precision than the Aptos Coin. I support this.

**Comment by davidiw** [comment]
At this point, the default Coin will only support 64-bits of precision. This is frozen. We may consider introducing a 128-bit precision coin, but I'd like feedback from bridges before doing that. The additional decimals of precision offer very low ROI for example .00000001 of Eth is worth `.00001311` USD as of this morning. Eth would have to 100x to become a fraction of a US penny and 1000x to become a penny. Bitcoin also only supports 8 digits.

Unfortunately it is too significant of a breaking change at this point :(

I'd recommend submitting a proposal for a higher precision coin and a framework for seamlessly converting between the two. E.g., one can hold a balance of Coin128 and move it around as a Coin64 and store it as a Coin64 as appropriate. We'll be introduce Aptos Improvement Proposal framework shortly :).
