### ISSUE TITLE
[API] Add CI that fails if existing goldenfiles have changed

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#4428]
Moving forward, we don't expect goldenfiles to ever change within a single API version, because pretty much any change represents a breaking change (more TBA on specifically what is and is not breaking). We should have CI that fails if goldenfiles change, though it should allow new goldenfiles.

**Comment by banool** [comment]
https://github.com/aptos-labs/aptos-core/issues/4429

**Comment by davidiw** [comment]
There are issues here in that adding new resources that may impact different aspects of why a golden file has changed. You'll need to do some invasive evaluation here and even then. I think it is about decoupling the client and server and ensuring that the client still works as expected.
