### ISSUE TITLE
[Bug][Rust SDK] `transfer-coin` example seems failed with `GAS_UNIT_PRICE_BELOW_MIN_BOUND`

### ISSUE THREAD

**Issue by stevenatcrypto** [aptos-labs/aptos-core#4470]
# 🐛 Bug

It seems that the `transfer-coin` example could not work in `sdk` folder.

## To reproduce

Go to `sdk` folder and run `transfer-coin` example, it seems that failed with error `GAS_UNIT_PRICE_BELOW_MIN_BOUND` as below:
```
$ cd sdk
$ cargo run --example transfer-coin

Error: Failed to submit transaction to transfer coins

Caused by:
    0: Failed to submit transfer transaction
    1: API error Error(VmError): Invalid transaction: Type: Validation Code: GAS_UNIT_PRICE_BELOW_MIN_BOUND
```

## Expected Behavior

Expect to transfer successfully as before.

**Comment by stevenatcrypto** [comment]
Sorry. It seems the update `main` branch could work.

**Comment by ChengYueJia** [comment]
Yeah, I do meet the same problem on devnet.
I'm still trying to find out why the gas_min_bound is so high..

Meanwhile, the testnet has the normal gas_min_bound, 
You can run the transfer-coin demo on testnet with little modification.
What you need to do is like below.

![image](https://user-images.githubusercontent.com/108982045/191899110-99553f18-0671-4aed-9b89-b89b095844da.png)

**Comment by EricGerbers** [comment]
Please increment gas price from 1 to 100 on devnet. you can add extra args into func that you call. some func will call **{gas_unit_price: '100'}** some func call **{gasUnitPrice: BigInt('100')}**
