### ISSUE TITLE
[Bug] safety rules report address is not in the validation set, can't fast sync

### ISSUE THREAD

**Issue by A7610605** [aptos-labs/aptos-core#4481]
# 🐛 Bug

## To reproduce

Unable to reproduce consistently, all I did was just `docker compose down -v` to remove the whole volume include db and safety rules. Then run `docker compose up -d` to bootstrap the node. No config file modification, no transaction on the owner voter and operator.    
You can also see in the first line of both log that the yaml configuration file is correctly parsed.  `bootstrapping_mode: DownloadLatestStates, commit_notification_timeout_ms: 5000, continuous_syncing_mode: ApplyTransactionOutputs` The first log file contains error `The validator is not in the validator set. Address not in set: 4428fefbc147d0170f9bbdfd7310adb642f9a50fcf7df338e4a95f2ea2033ed2`    
In the slack group and discord, I saw that several people were unable to get into fast sync
![aptos-test](https://user-images.githubusercontent.com/51876816/191908268-0c835e4b-23f4-4522-a45f-deeca96547b6.png)
The time in grafana is UTC +8

## Expected Behavior
use fast sync to bootstrap the node

## System information
- docker image tag: testnet_2b16401aa24688f1a6294f9ccde5386b9bf726d9

## The former is a failure log, the latter is normal
[21a236161c04f3b819bee47b9e6d1483756ae4932ab062b637f3b0e2ff574ac4-json.log](https://github.com/aptos-labs/aptos-core/files/9631255/21a236161c04f3b819bee47b9e6d1483756ae4932ab062b637f3b0e2ff574ac4-json.log)
[5fb046d25850c160603029f27026f77baa46671edf6e63850f97e8bdb79a037f-json.log](https://github.com/aptos-labs/aptos-core/files/9631257/5fb046d25850c160603029f27026f77baa46671edf6e63850f97e8bdb79a037f-json.log)

@sherry-x @zekun000

**Comment by davidiw** [comment]
This is a known issue. If you are not in the validator set, you will need to set your node as a fullnode and synchronize that way.

@JoshLind , @zekun000 , @sherry-x , @rajkaramchedu to validate and provide documentation if so.

**Comment by A7610605** [comment]
> This is a known issue. If you are not in the validator set, you will need to set your node as a fullnode and synchronize that way.
> 
> @JoshLind , @zekun000 , @sherry-x , @rajkaramchedu to validate and provide documentation if so.

Not quite sure why it's not in the validator set, I joined the validator set on 22 Sep 7:30 UTC. At 23 Sep 3:55 UTC, I was still participating in the consensus and making proposals. Then 5 minutes later I tried to reproduce the bug and I succeeded.  Then at 4:20 UTC I run the docker command again and it managed to get into fast sync.

**Comment by davidiw** [comment]
So the issue is that the machine interprets its view of the current validator set. In the ideal case, your node can connect to other nodes and it never checks with safety rules. Unfortunately the code needs some massaging to handle these quirks.
