### ISSUE TITLE
[Bug][API] `estimate_gas_price` API has performance issue

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#4486]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
1. Run a fullnode
2. Keep call `estimate_gas_price` API or do performance test on it
3. The QPS of it is very low
```

## Expected Behavior

**The QPS of this API should be much higher**

## System information

**Please complete the following information:**
- 
- 
-

**Comment by nolanxyg** [comment]
I looked into the `estimate_gas_price` API implement code, here's my thoughts about the cause:

1. The [`GasEstimationCache`](https://github.com/aptos-labs/aptos-core/blob/89f24ac053bd14f0ddc92d91955d9870dfbbbbe0/api/src/context.rs#L46) cache will be always missing
Because the code does not update [`last_updated_version `](https://github.com/aptos-labs/aptos-core/blob/89f24ac053bd14f0ddc92d91955d9870dfbbbbe0/api/src/context.rs#L734) when updating the cache, so the cache hit condition will never be satisfied.

2. Because of cache missed, all requests need to **compete for the write lock** of [`GasEstimationCache`](https://github.com/aptos-labs/aptos-core/blob/89f24ac053bd14f0ddc92d91955d9870dfbbbbe0/api/src/context.rs#L46) to continue, which will also effect the performance

**Comment by gregnazario** [comment]
Thanks for calling this out!  Guess I made a mistake https://github.com/aptos-labs/aptos-core/pull/4492

**Comment by davidiw** [comment]
closing as fixed -- likely not in testnet or devnet yet though....
