### ISSUE TITLE
[api] simulate_transaction should not require signature

### ISSUE THREAD

**Issue by 0xys** [aptos-labs/aptos-core#4517]
# 🚀 Feature Request
[simulate_transaction](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/simulate_transaction) request should not contain signature field.

## Motivation
In current API, [simulate_transaction](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/simulate_transaction) requires that the caller signs simulated transaction. However, the purpose of the simulation is to know the outcome of execution of the code on Move VM, which includes security assessment and gas estimation rather than the validity of the transaction. If validation is wanted, one can run signature validation script locally, no need to pass an entire transaction to remote nodes. 

Also, from security standpoint, this design is vulnerable to phishing attack.
Submitting the signature gives the middleman an ability to submit an effective transaction. In most of dapps in other chain, before submitting the transaction, dapps will show users, as a final check, an outcome of the transaction before submission, listing the estimated gas being paid and affected storage values through simulating the transaction. However, on Aptos, at the time of this pre-validation, signature would be sent to Dapps backend (or wallet, RPC server etc.) and the transaction can be submitted without further consent from users. Simulating is equivalent to executing in effect in an untrusted environment.

 To mitigate such an attack, I suggest that simulate_transaction endpoint should not require a signature in a request body.

## Pitch
Omit signature validation from simulate_transaction and corresponding schema changes.

## Additional context
Solana doesn't require a signature by default in its [simulateTransaction](https://www.quicknode.com/docs/solana/simulateTransaction) rpc method. It's optional.

**Comment by gregnazario** [comment]
TransactionSignatures are required to be all zeros when submitting for simulation.

The purpose of this is to always submit with the same structure as provided normally, including the BCS version.

**Comment by 0xys** [comment]
Oh, so can invalid signature be used?

**Comment by davidiw** [comment]
Yes, it is expected to be all 0s.

https://github.com/aptos-labs/aptos-core/blob/5314b72c45e8cf4987c19e1885e97ec27007c7ba/crates/aptos/src/common/types.rs#L1376
but I cannot see where we ensure that the user didn't actually send us a properly signed txn

rest assured it is never verified, since it bypasses signature verification checks.

There's definitely a chance to further enhance this, but it would probably break a lot of builds already, so going to mark as not fix for now.
