### ISSUE TITLE
[Bug] Compiler/gas schedule paradigm disincentivizes abstraction, function decomposition

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#4647]
Presently, [`instr.rs`](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-gas/src/instr.rs) charges per function call the most gas out of any operation, effectively penalizing abstraction and function decomposition. Hence, rather than writing modular code with easily verifiable inner functions, developers are instead rewarded for writing undecomposed functions of excessive length, with duplicate code across functions. This impairs code readability, maintainability, and auditability.

A proposed solution is a compiler optimization that compiles nested functions into a single call on the stack, which will result in larger bytecode files, but lower transaction fees.

@vgao1996 @davidiw @wrwg @chen-robert @runtian-zhou @gregnazario @movekevin  @msmouse @zekun000

**Comment by wrwg** [comment]
This should be partly addressed by templates/macros.

**Comment by alnoki** [comment]
> This should be partly addressed by upcoming templates/macros.

Agreed that these would be helpful. @fcremo also suggested an `#always_inline` attribute for intra-module functions.

**Comment by wrwg** [comment]
Hey @alnoki , we believe that this is addressed by the inline function feature. Let me know if you disagree.

**Comment by alnoki** [comment]
> Hey @alnoki , we believe that this is addressed by the inline function feature. Let me know if you disagree.

Agreed, thanks!

**Comment by alnoki** [comment]
@wrwg is it appropriate to open this back up as a tracking issue for function call gas refactors in Move 2?

Inlines have some issues, namely that they don't work well with the prover or coverage
