### ISSUE TITLE
how can i use python to init aptos account with a 12 words mnemonic

### ISSUE THREAD

**Issue by satisfywithmylife** [aptos-labs/aptos-core#4704]
as title, im not good at cryptology
plz help

**Comment by satisfywithmylife** [comment]
bysearch， only known its relate 637 | 0x8000027d
 | bip39 | purpose, coinType, account, change, index

**Comment by jjleng** [comment]
You can refer to the TS SDK implementation https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_account.ts#L54.

**Comment by satisfywithmylife** [comment]
> 

i am a backend, do not good at ts, i am good at python

**Comment by satisfywithmylife** [comment]
> You can refer to the TS SDK implementation https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_account.ts#L54.

sorry, i never use ts, i am a backend, always use python

**Comment by satisfywithmylife** [comment]
> You can refer to the TS SDK implementation https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_account.ts#L54.

![1664786833006](https://user-images.githubusercontent.com/30144807/193536815-34acb8a7-2f34-4b4a-a0c6-47ed477a497f.png)
i think this offset may be 0x8000027d right ? 0x80000000 is eth used privdev

**Comment by satisfywithmylife** [comment]
> 



> You can refer to the TS SDK implementation https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_account.ts#L54.

i made it with python !, so difficult https://github.com/satisfywithmylife/aptos_wallet_mnemonic

**Comment by jjleng** [comment]
Great. Let us know when you have other questions.
