### ISSUE TITLE
[Bug] Get account transactions API uses sequence number instead of ledger version

### ISSUE THREAD

**Issue by Poytr1** [aptos-labs/aptos-core#4710]
# 🐛 Bug

In the document of getAccountTransactions API(https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account_transactions). It says the query parameter 'start' is the ledger version to start list of transactions. But in practice, I feel it is more like the sequence number in the response rather than ledger version. Is it by design? 
![image](https://user-images.githubusercontent.com/20534718/193491602-576d244c-b156-4b3f-9065-fd010aea239c.png)

## To reproduce
Http request:

https://testnet.aptoslabs.com/v1/accounts/4188c8694687e844677c2aa87171019e23d61cac60de5082a278a8aa47e9d807/transactions?limit=1&start=3

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by jjleng** [comment]
yes. /accounts/xxxx/transactions paginates with sequence numbers.

**Comment by davidiw** [comment]
We should just update the documentation here.
