### ISSUE TITLE
[Feature Request] table::borrow_with_default(&t, key, default_val)

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#4712]
# 🚀 Feature Request

imagine a table {1: 1, 2: 2};

```
table::borrow_with_default(&t, 1, 0) == 1
table::borrow_with_default(&t, 3, 0) == 0
```

## Motivation

**Is your feature request related to a problem? Please describe.**
tired of doing this:
```
if (table::contains(&t, k)) {
  *table::borrow(&t, k)
} else {
  0 // or other default value
}
```
prefer a one-liner alternative though it doesn't exist

## Pitch

**Describe the solution you'd like**
add a `default_with_default` method to aptos_std::table

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
yes, if the idea looks good to aptos team

**Comment by 0xbe1** [comment]
> Sounds a valid asking, but would you think `table::borrow_with_default(&t, 3, &0) == &0` fits the current interface better?

yeah the interface you suggest works for me as well

**Comment by lightmark** [comment]
@0xbe1 Then a PR is welcome.
