### ISSUE TITLE
[Bug] [Aptos-CLI] [Move] When try to running/compiling a Move Script, an crash happens.

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#4713]
# 🐛 Bug

I don't know what the bug is, It does crash.

## To reproduce

To reproduce:
```sh 
wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v0.3.7/aptos-cli-0.3.7-Ubuntu-x86_64.zip
unzip aptos-cli-0.3.7-Ubuntu-x86_64.zip
echo "module 0x2::A {struct B has key {}}script{use 0x2::A::B;fun _() acquires B {}}" > bug.move
./aptos move run-script --script-path ./bug.move
```
Output:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/git/checkouts/move-0639dd674f581c30/94552a7/language/move-compiler/src/typing/globals.rs:37:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

if do `echo "module 0x2::A {struct B has key {}}script{use 0x2::A::B;fun _() acquires B {}fun main(){}}" > bug.move` it telling different story:
```
error[E01002]: unexpected token
  ┌─ /tmp/.tmpLHa6Kf/sources/bug.move:1:78
  │
1 │ module 0x2::A {struct B has key {}}script{use 0x2::A::B;fun _() acquires B {}fun main(){}}
  │                                                                              ^^^ Unexpected characters after end of 'script' function

{
  "Error": "Unexpected error: Compilation error"
}
```

## Expected Behavior

Sorry but I don't know which expected result to be.

## System information

**Please complete the following information:**
- 
- 
- 
Arch Linux

**Comment by gregnazario** [comment]
I'm a little confused here because you're combining modules and scripts.  I'm pretty sure you can't declare both in a script file, which is why the compiler is not working for you.

Here's an example of a script

https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/scripts/minter/sources/minter.move

**Comment by e99243506bigplay** [comment]
Actually it could, it is when try to call the module of function.
Sorry, I am forgot about this issue detail, it pass away for 2 weeks, feel free to close it.
I remember there is another situation will happen ICE, but I didn't report it so I unable reproduce it out now.
