### ISSUE TITLE
[BLK-217] Improve First NFT Tutorial

### ISSUE THREAD

**Issue by KEY-L-LC** [aptos-labs/aptos-core#4748]
when I run the demo "my first nft" I got the wrong, who can help me

    txn_hash = rest_client.create_collection(
  File "/Users/oker/Library/Python/3.8/lib/python/site-packages/aptos_sdk-0.3.0-py3.8.egg/aptos_sdk/client.py", line 310, in create_collection
  File "/Users/oker/Library/Python/3.8/lib/python/site-packages/aptos_sdk-0.3.0-py3.8.egg/aptos_sdk/client.py", line 112, in submit_bcs_transaction
aptos_sdk.client.ApiError: {"message":"Invalid transaction: Type: Validation Code: GAS_UNIT_PRICE_BELOW_MIN_BOUND","error_code":"vm_error","vm_error_code":15}

<sub>[BLK-217](https://linear.app/aptoslabs/issue/BLK-217/improve-first-nft-tutorial)</sub>

**Comment by e99243506bigplay** [comment]
Pleaae update your aptos sdk to newest version, I recommend to use git main branch version.

**Comment by clay-aptos** [comment]
Let me look into this. We are getting some complaints from our users on this doc:
https://discord.com/channels/945856774056083548/1034215378299133974/1038288215032995890

**Comment by clay-aptos** [comment]
Adding @movekevin as this is one of our more popular docs that could use review and improvement by the team.

**Comment by clay-aptos** [comment]
I am noting we held a Move workshop today focused upon minting NFTs today that should fuel improvements here. 

@cathyaptos, please send me the recording when its available.

@0xchloe, let's work on this documentation when you get a chance, starting with your internal workshop steps. Thanks!

**Comment by clay-aptos** [comment]
@0xchloe is working on a new version of this tutorial, and the team has also compiled a Q&A document for a partner regarding NFTs we should consider useful here and in the general FAQ we are working on.

**Comment by clay-aptos** [comment]
I also also wondering whether we should consider learnings from:
https://medium.com/@CryptoOcean_/how-to-mint-aptos-zero-testnet-nft-6b07d5fff60c

**Comment by 0xchloe** [comment]
> I am noting we held a Move workshop today focused upon minting NFTs today that should fuel improvements here.
> 
> @cathyaptos, please send me the recording when its available.
> 
> @0xchloe, let's work on this documentation when you get a chance, starting with your internal workshop steps. Thanks!

hey sorry just saw this! feel free to directly dm me next time. I'll update the NFT tutorial by the end of this week and then we can start working on the docs!

**Comment by cathyaptos** [comment]
@0xchloe I want to confirm that the tutorial we're doing will be a NEW tutorial separate from the existing "Your First NFT" Tutorial 

I was thinking with our Move sessions we would create a new series - something like "Learn Move via Tutorials" and our NFT session would be the first one under this new umbrella. Let me know if you agree with this!

**Comment by cathyaptos** [comment]
Also repasting the recording link here: https://aptoslabs.zoom.us/rec/share/gBMEIoSYxsk4w5UPbvmlEZuT4NWKdogYNvQEDZ5eo3cXbE08CY0UJ_lG9UcquVse.AAV_FxjlG6c26M8g 
Passcode: #g*B=P$5

**Comment by clay-aptos** [comment]
Reopening as I need to update the doc to match the code.

**Comment by davidiw** [comment]
Folks, this is not the right issue for tracking documentation issues. Please create a new issue.

**Comment by clay-aptos** [comment]
> Folks, this is not the right issue for tracking documentation issues. Please create a new issue.

New issue filed:
https://github.com/aptos-labs/aptos-core/issues/5774

**Comment by clay-aptos** [comment]
> > Folks, this is not the right issue for tracking documentation issues. Please create a new issue.
> 
> New issue filed: #5774

@davidiw , please explain why this is not the right issue to track this work so we can avoid making the same mistake in the future.
