### ISSUE TITLE
Remove Safety-rule from validator deployment

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#479]
* Move to local deployment
* Update kubernetes / terraform
* Make it possible to use a rocksdb instance as a secure storage
* Explore reference based API to eliminate unnecessary copies in local mode
* Eliminate usage of remote signing in vault
* Support importing of private key via env variable

**Comment by JoshLind** [comment]
@davidiw, to be clear. This issue is arguing for moving to a local safety rules as "default", but we still would like to maintain configurability, right? e.g., if we ever decide to adopt the more secure (but complex) architecture?

**Comment by davidiw** [comment]
Agreed, we shouldn't delete that code unless there's a really strong motivation behind it.

**Comment by davidiw** [comment]
@JoshLind , you said you were tracking this? Could you update the above with either a tasklist, strike out, or close the issue :)
