### ISSUE TITLE
[storage] SchemaBatch::range_delete() & SchemaBatch::range_delete_inclusive()

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#48]
1. expose range_delete() RockDB API to the code base. 

It's currently available on schemadb::DB but not the batch, so one can't include a range delete operation in a batch, mixed with other write ops.

2. add range_delete_inclusive() capability to the DB and the batch.

range_delete() deletes a half open range, as in [begin, end), the right side of which is exclusive. For convenience, we want to have range_delete_inclusive([first, last]). 

-------
> I think we can implement it as range_delete([first, last || 0x0), lmk if I'm wrong.

yeah I was wrong..  it takes a bit more to calculate the next possible key.. (only when it's 0xFF..F that the next key is that affixed with a 0 byte)

**Comment by sitalkedia** [comment]
@msmouse/ @areshand   - Is this done? Should we close this issue if so?

**Comment by msmouse** [comment]
I'm considering making the range_delete_inclusive() one single operation instead of a range_delete() plus a delete() -- so keep it open for another bit.
