### ISSUE TITLE
[Feature Request] Automatically split transactions and Submit transactions for cli, or Increase MAX_TRANSACTION_SIZE

### ISSUE THREAD

**Issue by uvd** [aptos-labs/aptos-core#4811]
# 🚀 Feature Request

add an automatic subpackage for cli, or increase MAX_TRANSACTION_SIZE

## Motivation

My package is over the limit
```json
package size 81942 bytes
{
  "Error": "API error: API error Error(VmError): Invalid transaction: Type: Validation Code: EXCEEDED_MAX_TRANSACTION_SIZE"
}
```

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment]
Are you able to work around this with `move publish --included-artifacts=none ...`? 

Another options is perhaps splitting your code into smaller packages.

Allowing incremental publishing is on the todo list, but not sure when it will come.

**Comment by uvd** [comment]
> move publish --included-artifacts=none   this is ok， I try to split my package
