### ISSUE TITLE
[Bug] make fmt will scan .venv

### ISSUE THREAD

**Issue by zhenfeng-zhu** [aptos-labs/aptos-core#4859]
# 🐛 Bug

## To reproduce

In `aptos-core/ecosystem/python/sdk` folder, run `make fmt`.  This command spend much time to scan `.venv`

## Expected Behavior

It should only scan examples and aptos_sdk folder. 

## System information
macos

**Comment by davidiw** [comment]
This should land shortly: https://github.com/aptos-labs/aptos-core/pull/4858/files#
