### ISSUE TITLE
[Bug] the rust SDK demo can not work

### ISSUE THREAD

**Issue by aplomb2** [aptos-labs/aptos-core#4861]
# 🐛 Bug

Hello, I run the rust SDK demo using below command:

cargo run --example transfer-coin

the output is：

=== Addresses ===
Alice: 0x29d5214b2f753a5c179dac71ec57fd2ecc679b31c244e2d537bdbce713efa042
Bob: 0xd71acef4b37500b0ba6e945e8828c17db2a1ca634d3fd50ade9faffa9d6c3e5
Error: Failed to fund Alice's account

Caused by:
    FaucetClientError { inner: Inner { kind: HttpStatus(411), source: None } }

-----------------------
on the anther hand , the similar typescript SDK demo is OK .

**Comment by valpaq** [comment]
And only with rust, I can create same post in python/ts and everything will be fine

**Comment by aplomb2** [comment]
I also run the python/ts demo, it works . but the only rust demo can not work

**Comment by valpaq** [comment]
https://github.com/aptos-labs/aptos-core/pull/4904 hope this pull request will help

**Comment by aplomb2** [comment]
#4904 bug fixed , great! I test it. it works well.
