### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by lobotech13** [aptos-labs/aptos-core#4862]
Hi, I have an error while creating a validator node.
https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-docker/
I make the steps in your documentation but an error occured on step 3.

wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/aptos-node/haproxy.cfg
wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/aptos-node/blocked.ips

HTTP request sent, awaiting response... 404 Not Found

Does it means that the links are dead ?

**Comment by gregnazario** [comment]
Both links are accessible as provided by you.  Perhaps it was a temporary issue?  Could you try again?

**Comment by JoshLind** [comment]
Closing this out. Feel free to reopen.
