### ISSUE TITLE
[Feature Request] Need a new API/extend the account transactions API to retrieve transactions to the account in addition to transactions from the account

### ISSUE THREAD

**Issue by Poytr1** [aptos-labs/aptos-core#4867]
# 🚀 Feature Request

In the smart contract monitoring scenario, we need to retrieve transactions to an smart contract address. But currently it seems we don't have such a API to do so, I'm asking to:

Extend the [Get account transactions API](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account_transactions) to retrieves transactions to an account in addition to transactions from the account.
Or create a new API only used to retrieve transactions to an account.

## Motivation

We found an issue that this transaction https://explorer.aptoslabs.com/txn/161068193 is basically account 0x29ed2d58cad3218ed5f3a18d1e5905ec64ccd97722fa71a58394dc76ccc5c7d9 calls into 0xc2bdb7930529b78010b90ecdc1986d8bbd123239991696161e5aa5700995c673::vault_scripts::deposit_collateral method
i am able to find this transaction under https://explorer.aptoslabs.com/account/0x29ed2d58cad3218ed5f3a18d1e5905ec64ccd97722fa71a58394dc76ccc5c7d9, though not https://explorer.aptoslabs.com/account/0xc2bdb7930529b78010b90ecdc1986d8bbd123239991696161e5aa5700995c673

By using get account transaction API, we only can get transactions from this address but not transactions to this address:
![image](https://user-images.githubusercontent.com/20534718/194600619-6a25722c-d510-42f0-ad08-40f1035a545e.png)

Is it expected?  If so, is there a way to get transactions that calls into methods under account?

## Pitch

Extend the current [Get account transactions API](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account_transactions)  or create a new API to retrieve transactions to an account.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by gregnazario** [comment]
Thanks for your issue!  However, it's technically prohibitive to find transactions to an account without an indexer.  This would require scanning all transactions and checking if any transaction has ever written to an account.

If you're looking for "transfer" transactions to an account, please take a look at the events API, and looking at deposit events.  More information is here https://aptos.dev/guides/system-integrators-guide/#exchanging-and-tracking-coins

**Comment by gregnazario** [comment]
Future work can probably enable that, but it will probably be a while off

**Comment by davidiw** [comment]
I think this is better for an indexer, the API won't really handle this, check this out: https://aptos.dev/guides/indexing/
