### ISSUE TITLE
[APT-8] [Feature Request] REST API: Get block by hash

### ISSUE THREAD

**Issue by vokracko** [aptos-labs/aptos-core#4911]
# 🚀 Feature Request

Add REST API endpoint to get block by hash:  GET `/blocks/by_hash/{block_hash}`

<sub>[APT-8](https://linear.app/aptoslabs/issue/APT-8/[feature-request]-rest-api-get-block-by-hash)</sub>

**Comment by gregnazario** [comment]
We've considered this, though I'm curious what the use case is to get a block by hash, considering that blocks are numbered, which is also a unique identifier

**Comment by davidiw** [comment]
closing this out and waiting for motivation
