### ISSUE TITLE
[Move-CLI] Indirect dependencies conflict

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#4912]
## ❓ Questions and Help

Wonder if there is a way to resolve conflicting indirect dependencies. 
Say I want to add package A and B as dependency. Pkg A depends on AptosFramework rev 01. Pkg B depends on AptosFramework rev 02. There would be such a build failure:

```
While resolving dependency 'Liquidswap' in package 'thala-protocol-v1': Unable to resolve package dependency 'Liquidswap': While resolving dependency 'AptosFramework' in package 'Liquidswap': Unable to resolve package dependency 'AptosFramework': Conflicting dependencies found: package 'AptosFramework' conflicts with 'AptosFramework'"
```

Is there any standard approach to fix it? In case we don't want to create local forks.

Thanks

**Comment by xiaozzz** [comment]
save problem. stuck on developing cross-contract contract. i think contract developer need abi dependency not source code dependency

**Comment by wrwg** [comment]
How did you get that error? There shouldn't be different "revisions" of a given package, specifically not the Aptos framework. Because of the compatible upgrade policy, the latest version on chain can always be used instead of some older version. Newer package is fully substitutable anywhere. In fact, if the code is deployed on chain, any given package is deployed only once there. The 'diamond' problem for dependencies you are describing does not exist in Aptos.

**Comment by wjw12** [comment]
> How did you get that error? There shouldn't be different "revisions" of a given package, specifically not the Aptos framework. Because of the compatible upgrade policy, the latest version on chain can always be used instead of some older version. Newer package is fully substitutable anywhere. In fact, if the code is deployed on chain, any given package is deployed only once there. The 'diamond' problem for dependencies you are describing does not exist in Aptos.

By "revision", I wanted to mean commit hash. For example, our module uses the one below
```
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "985f19d40457a5f09f2d741b1feca6bf7ba1f8a6"
```

If one of our dependencies define their dependency on AptosFramework but a different `rev`, build fails.

**Comment by wrwg** [comment]
The `rev` field in the dependency section makes no sense for the Aptos use case. You don't need it. On chain, there is one and only one version of the framework, and it is the newest one. This one is downwards to all older versions. All modules will use the same version of the framework when the code is eventually executed on chain. Also see discussion of upgrades and compatibility: https://aptos.dev/guides/move-guides/upgrading-move-code

Closing for now, feel free to re-open if needed.

**Comment by mkurnikov** [comment]
@wrwg By this logic, all the projects on Aptos should have `AptosFramework` `rev = "mainnet"`, right? Instead, most projects either:
* use `main` as a rev value
* use a specific commit that they used for development

Do you think the Aptos team could do something to address the issue? What about making `AptosFramework` an implicit dependency, and instead letting users specify a version of the network, like `mainnet`, `testnet`, `devnet`?
