### ISSUE TITLE
[APT-9] [Feature Request][RPC]Add call view function 

### ISSUE THREAD

**Issue by uvd** [aptos-labs/aptos-core#4915]
# 🚀 Feature Request

## Motivation
The dapp wants to retrieve the return value of a very complex algorithmic data, which does not involve any changes to the information on the chain, and is only read only ，The dapp side is difficult to implement this algorithm, or the contract provided by others can not implement the algorithm, need to be able to get this return value ,For example

```
public fun get_data(): u64 {
 ///  Very complicated algorithm

}
```

 the dapp wants the return value

## Pitch

#4900

<sub>[APT-9](https://linear.app/aptoslabs/issue/APT-9/[feature-request][rpc]add-call-view-function)</sub>

**Comment by mutable-dev** [comment]
This is super important!! Please prioritize this as this is a #1 feature request for our team :)

**Comment by johnyjt** [comment]
This is super important!!

**Comment by devfans** [comment]
I see another Move chain has this feature.

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/blob/38f5f8a9004b8b17a91f1d05358d1c6fbaf2cd50/aptos-move/framework/aptos-framework/sources/coin.move#L226
and https://github.com/aptos-labs/aptos-core/blob/38f5f8a9004b8b17a91f1d05358d1c6fbaf2cd50/api/src/tests/view_function.rs#L20

yay
