### ISSUE TITLE
[Bug] address type in event, lost head 0.

### ISSUE THREAD

**Issue by liuxiaobleach** [aptos-labs/aptos-core#4917]
# 🐛 Bug

event hex miss head zero

https://explorer.aptoslabs.com/txn/414451
event return
{
  "receiver": "0x47ae560441fca4364680930970921b655b3b81bef1fed02927ab586f26d5b88",
}
it should be 0x047ae560441fca4364680930970921b655b3b81bef1fed02927ab586f26d5b88

struct MintEvent has drop, store {
        receiver: address,
}

**Comment by davidiw** [comment]
This is intentional, leading 0s are removed.
