### ISSUE TITLE
[Bug] Compiler/gas schedule paradigm incentivizes magic numbers, storage bloat

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#4926]
Currently, the gas schedule assesses a gas cost of 13000 units to load a constant (`ld_const_base`), plus 700 units per byte (`ld_const_per_byte`) as defined in `instr.rs`.

One primary use case for constants is bitmasks, for example when bit-packing fields into a `u128`, a strategy that reduces overall storage costs through bitwise compression. However, if bitmasks are considered prohibitively expensive at the instruction level, then developers will be:

1. Less likely to use data compression strategies which rely on bitmasks, thus bloating global storage.
2. More likely to manually inline the constants as magic numbers, thus diminishing code readability, maintainability, and auditability.

A straightforward solution is for the compiler to inline all constants, thus eliminating the `ld_const_base` and `ld_const_per_byte` fields from the gas schedule.

@chen-robert @davidiw @wrwg @vgao1996 @runtian-zhou @gregnazario @movekevin @msmouse @zekun000 @CapCap

**Comment by vgao1996** [comment]
Yeah, this also caught my intention when I did the initial benchmarks. 
1. My take is that our current implementation of load_const is very inefficient for some reasons. For the short term, let's try to figure out why it is so slow and see if there is a quick fix. I also believe we can also lower the cost a bit, while still being safe from attacks. cc @lightmark 
2. In the long term, we do plan to re-do the runtime data representation, thus lowering the execution costs drastically. (Although to be clear, large-scale refactoring like this is still months away.)
3. I also agree with you that eventually, when we get to the stage where we start to have the bandwidth to implement real compiler optimizations, we'll likely want to replace some load_const with the cheaper alternatives for smaller constants. There's simply no way we can make an instruction with indirection faster than one without.
