### ISSUE TITLE
Mainnet Commit #8e98b1fa7675e0d8923d7bc6e0ed672df563e083 Deployment Issues [Bug]

### ISSUE THREAD

**Issue by null-ref-ex** [aptos-labs/aptos-core#4992]
# 🐛 Bug

It was requested at 21:42 EST on Tuesday October 11th 2022 that pre-mainnet participants deployment mainnet branch commit hash 8e98b1fa7675e0d8923d7bc6e0ed672df563e083 to their infrastructure.
I undertook the same steps as I have done for the previous 20 releases which is to compile, stop service, copy new binary, start service.
Upon startup of the new service binary the following panics were observed:

```
panicked at 'Transport listen on fails: Os { code: 98, kind: AddrInUse, message: "Address already in use" }'...
```

This error repeated for ~1 minute (our service is set to restart on failure) at which time the node was able to bind to target ports and successfully started.
This occurred on 2 out of 3 upgraded nodes and resulted in 4 proposal misses on our validator.
I verified in system logs that I had indeed issues `stop` as expected and that everything else was aligned with our usual process; it was. The same issue has been reported by at least 3 other node runner in pre-mainnet.

## To reproduce

**Code snippet to reproduce**
The below is the logical process which resulted in the issue for us, not sure if it will be reproducible or would require high intensity load tests to have executed for it to manifest.
- run a source installation of commit a059b3d6965c63d124da09db83eed4f1221c6896 from mainnet branch
- ... load tests? be online for 5 days?
- compile 8e98b1fa7675e0d8923d7bc6e0ed672df563e083 from mainnet
- stop aptos service
- copy new binary to correct location
- start aptos service

**Stack trace/error message**
```
panicked at 'Transport listen on fails: Os { code: 98, kind: AddrInUse, message: "Address already in use" }'...
```

## Expected Behavior

We expect for the stop signal to terminate the aptos-node binary and for said binary to release it's ports bindings before releasing control back to the terminal so that ports are available for when we issue a start command.
Alongside this, the start up time (1 minute) is unacceptable for validator operations given tight constraints for uptime.

## System information

**Please complete the following information:**
- a059b3d6965c63d124da09db83eed4f1221c6896 ----> 8e98b1fa7675e0d8923d7bc6e0ed672df563e083
- Ubuntu 20.04
aptos-node/src/log_build_information.rs:21 Build information:
aptos-node/src/log_build_information.rs:24 build_branch: 
aptos-node/src/log_build_information.rs:24 build_cargo_version: cargo 1.63.0 (fd9c4297c 2022-07-01)
aptos-node/src/log_build_information.rs:24 build_commit_hash: bf4ef2c571b4265476dfd91c5a3698f0f013d292
aptos-node/src/log_build_information.rs:24 build_is_release_build: true
aptos-node/src/log_build_information.rs:24 build_os: linux-x86_64
aptos-node/src/log_build_information.rs:24 build_pkg_version: 0.1.0
aptos-node/src/log_build_information.rs:24 build_profile_name: release
aptos-node/src/log_build_information.rs:24 build_rust_channel: 1.63.0-x86_64-unknown-linux-gnu
aptos-node/src/log_build_information.rs:24 build_rust_version: rustc 1.63.0 (4b91a6ea7 2022-08-08)
aptos-node/src/log_build_information.rs:24 build_tag: 
aptos-node/src/log_build_information.rs:24 build_time: 2022-10-03 23:34:26 +00:00
aptos-node/src/log_build_information.rs:24 build_using_tokio_unstable: true

**Comment by bchocho** [comment]
Thank you for the report! We investigated and resolved in #5005 for mainnet branch.
