### ISSUE TITLE
[Bug] Incorrect number of upgrade policies in the move-guides

### ISSUE THREAD

**Issue by Flyy-yu** [aptos-labs/aptos-core#4994]
# 🐛 Bug

## Steps to reproduce

https://aptos.dev/guides/move-guides/upgrading-move-code/#upgrade-policies
The doc states, "Currently, three different upgrade policies are supported:". But the doc only shows the definition for two, which are "compatible" and "immutable". 

## Expected Behavior

The doc should say "Currently, **two** different upgrade policies are supported:"

**Comment by gregnazario** [comment]
Thanks for the callout! https://github.com/aptos-labs/aptos-core/pull/5083
