### ISSUE TITLE
[Bug] New nodes should be able to start up with any waypoint they want.

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#5007]
> I start a completely new node. I give it the genesis blob to start up for the first time, and I want the waypoint to be at the version that I trust. State sync will verify the waypoint matches the data from the peers before syncing.

This doesn't work today unless the waypoint is for the genesis version because of some limitations around the storage bootstrapping logic. We should fix it ASAP: https://aptos-org.slack.com/archives/C0369TWS4Q4/p1665597275496869

**Comment by msmouse** [comment]
.
