### ISSUE TITLE
[Bug]The function to calculate collection_data_id_hash of TokenDataID in Indexer 

### ISSUE THREAD

**Issue by stopWarByWar** [aptos-labs/aptos-core#5037]
# 🐛 Bug

The function to calculate collection_data_id_hash of TokenDataID in Indexer 

## To reproduce
When we run fullnode with indexer, we found that in Table "token_ownerships" different tokens with the same "creator_address" and "collection_name" in postgres have different collection_data_id_hash.

**Code snippet to reproduce**
https://github.com/aptos-labs/aptos-core/blob/83641d3f083762f31700060e5e95fbb1cbc28bf0/crates/indexer/src/models/token_models/token_utils.rs#L48
```rust
pub fn get_collection_data_id_hash(&self) -> String {
        CollectionDataIdType {
            creator: self.creator.clone(),
            name: self.name.clone(),
        }
        .to_hash()
    }
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
aptos-core branch: main

## Additional context

I think this func should be 
```rust
pub fn get_collection_data_id_hash(&self) -> String {
        CollectionDataIdType {
            creator: self.creator.clone(),
            name: self.collection.clone(),
        }
        .to_hash()
    }
```

**Comment by davidiw** [comment]
Please re-open if the issue persists.
