### ISSUE TITLE
Upgrade to move-Sep-2022

### ISSUE THREAD

**Issue by simsekgokhan** [aptos-labs/aptos-core#5073]
## Info

**//// Dev. branch:**
https://github.com/OLSF/move-0L/commits/v6-move-sep-22 < move-sep-22 + 0L patch >, < builds >
https://github.com/OLSF/libra/commits/v6-Sep-22 < v6(diem-jan-22+0L patch) + aptos-core-sep-22 >, < not building >
**// Move upstream 0L patched:**
(20-Sep-2022) https://github.com/OLSF/move-0L/commit/0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa 
**// Compatible Aptos(Libra) version for move-sep-22:**  
(20-Sep-22) https://github.com/aptos-labs/aptos-core/commit/d76fc80ce683f09fad7a596e3819b76e594dabbb
**// Last working/buildable 0L v6 version:**  
https://github.com/OLSF/libra/commit/5e5ffce8e9a9b169a46c792f5f640a46d804b681

**Comment by gregnazario** [comment]
I'm not sure what this issue entails?  Is this for the 0L network instead?

**Comment by simsekgokhan** [comment]
Yeah, sorry for that.
