### ISSUE TITLE
[Feature Request] Add bulk getting interface for table

### ISSUE THREAD

**Issue by Disperito** [aptos-labs/aptos-core#5080]
# 🚀 Feature Request

For now, if users want to get a series of table data items, they are only allowed to get one-by-one with the [Get Table Item](https://fullnode.testnet.aptoslabs.com/v1/spec#/operations/get_table_item) of REST API.
This will result in the user needing to call the REST API multiple times in a short period of time, and will cause some performance issues.
So I suggest that Aptos team can provider an API for getting table items in bulk.

**Comment by fardream** [comment]
We run into the same issue. Overall we are very happy with how table works, but the off-chain access pattern can definitely be improved.

**Comment by davidiw** [comment]
I think the better solution for now is to use the indexer. This won't be addressed in the existing API.
