### ISSUE TITLE
[Question] Format of gas parameters

### ISSUE THREAD

**Issue by JSHan94** [aptos-labs/aptos-core#5092]
## ❓ Questions and Help

I wonder why some gas parameter has EXECUTION_GAS_MULTIPLIER `MUL` and others don't.

For example, in [table gas](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-gas/src/table.rs), `.common.load_base` doesn't have multiplier and others have. 

```rust

crate::natives::define_gas_parameters_for_natives!(GasParameters, "table", [
    // Note(Gas): These are legacy parameters for loading from storage so they do not
    //            need to be multiplied.
    [.common.load_base, "common.load.base", 8000],
    [.common.load_per_byte, "common.load.per_byte", 1000],
    [.common.load_failure, "common.load.failure", 0],

    [.new_table_handle.base, "new_table_handle.base", 1000 * MUL],

    [.add_box.base, "add_box.base", 1200 * MUL],
    [.add_box.per_byte_serialized, "add_box.per_byte_serialized", 10 * MUL],

    [.borrow_box.base, "borrow_box.base", 1200 * MUL],
    [.borrow_box.per_byte_serialized, "borrow_box.per_byte_serialized", 10 * MUL],

    [.contains_box.base, "contains_box.base", 1200 * MUL],
    [.contains_box.per_byte_serialized, "contains_box.per_byte_serialized", 10 * MUL],

    [.remove_box.base, "remove_box.base", 1200 * MUL],
    [.remove_box.per_byte_serialized, "remove_box.per_byte_serialized", 10 * MUL],

    [.destroy_empty_box.base, "destroy_empty_box.base", 1200 * MUL],

    [.drop_unchecked_box.base, "drop_unchecked_box.base", 100 * MUL],
]);
```

Doesn't we have to have same formatting? 

related [PR](https://github.com/aptos-labs/aptos-core/pull/4841/files#diff-58a5ed5865506ea8146261f67a477b04cb65b9f7df47e96205b3e3d6018bc13b)

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by davidiw** [comment]
We wrote up a gas blog: https://aptoslabs.medium.com/the-making-of-the-aptos-gas-schedule-508d5686a350

**Comment by vgao1996** [comment]
```
[.common.load_base, "common.load.base", 8000],
    [.common.load_per_byte, "common.load.per_byte", 1000],
    [.common.load_failure, "common.load.failure", 0],
```
These are legacy fields that are no longer used. I'm working on a plan to get them deleted safely.

Storage-related gas costs are now governed by the `storage-gas` module in the framework using dynamic curves. Please have a look at those if you are interested in the details.

The costs for the event natives also don't have the multiplier and that is also intentional. This multiplier is only meant for things that are in the "execution" category.
