### ISSUE TITLE
erros: MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS??

### ISSUE THREAD

**Issue by GAVINNB** [aptos-labs/aptos-core#5093]
### Please note that this issue tracker is not a help form and this issue will be closed.
{
  "Error": "Simulation failed with status: Transaction Executed and Committed with Error MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS"
}

**Comment by davidiw** [comment]
Not sure how to help, please make sure you set your max gas units and gas unit price appropriately.

**Comment by Gilgames000** [comment]
I'm getting this when trying to publish the `hello_blockchain` example by following the getting started tutorial on the docs.
