### ISSUE TITLE
[Feature Request] Interface Pattern

### ISSUE THREAD

**Issue by babyface001** [aptos-labs/aptos-core#5095]
# 🚀 Feature Request

Interface Pattern for Wallet

## Motivation

current wallet use `0x1::coin::transfer` to transfer tokens, but how about a token with custom `transfer`

maybe we need some interface like `ERC20`
```
account::module::balance_of(address)
account::module::transfer
```

**Comment by dulumao** [comment]
No interface, import module source

**Comment by babyface001** [comment]
@dulumao I mean for client side.

wallet app. token interface.

**Comment by babyface001** [comment]
@dulumao I want a coin with custom `transfer`, but I can not override `0x1::coin::transfer`,
and wallet only call `0x1::coin::transfer` to transfer, so my coin not work.

interface just a convention that a module should has some functions.

**Comment by babyface001** [comment]
for example.
```
module Token::erc20 {
    public entry fun transfer(){
        // interface override.
        // your logic or just call 0x::coin::transfer
    }
}
```

**Comment by babyface001** [comment]
maybe move should have some primitive like `trait`

**Comment by babyface001** [comment]
someone get in touch in upstream
