### ISSUE TITLE
[Feature Request] add git hash to aptos info for the node binary

### ISSUE THREAD

**Issue by sirouk** [aptos-labs/aptos-core#5111]
# 🚀 Feature Request

It would be very helpful if the git hash could be reported from the aptos-node binary just the same as the git hash is available via:
`curl 127.0.0.1/v1 2> /dev/null | jq` from the node API

This could help confirm the hash used to produce the build before a node restart!

ex. 
`aptos-node --info`

**Comment by sirouk** [comment]
@gregnazario  thank you!🙏

**Comment by gregnazario** [comment]
This would likely be similar to `aptos info` used in the CLI.

**Comment by sirouk** [comment]
That's exactly right. It would be able to tell the git commit hash for the aptos-node binary realtime. That is unlike what we have now, where we have to restart the aptos-node binary to obtain the git commit hash via `curl 127.0.0.1:8180/v1 2> /dev/null | jq`
