### ISSUE TITLE
How to activate an address for transfer？

### ISSUE THREAD

**Issue by 17621859515** [aptos-labs/aptos-core#5115]
I want to transfer money to an address, first I need to activate this address.

Use the following code in devnet to activate
`await faucetClient.fundAccount(bob.address(), 0);`

But I need to transfer money in maitnet.
There is no faucet in mainnet

So how do I activate this address?

**Comment by davidiw** [comment]
use `0x1::aptos_account::transfer` or use a wallet and transfer to that address, most wallets will use that function.
