### ISSUE TITLE
[Bug] mainnet aptos-node can not pass "assert_no_test_natives"

### ISSUE THREAD

**Issue by stopWarByWar** [aptos-labs/aptos-core#5116]
# 🐛 Bug mainnet aptos-node can not pass "assert_no_test_natives"

## To reproduce

When i switch to the mainnet commit and run the aptos-node, it showed :

```
thread 'main' panicked at 'assertion failed: aptos_natives(NativeGasParameters::zeros(),\n            AbstractValueSizeGasParameters::zeros(),\n            LATEST_GAS_FEATURE_VERSION).into_iter().all(|(_, module_name,\n            func_name, _)|\n        module_name.as_str() != \"unit_test\" &&\n            func_name.as_str() != \"create_signers_for_testing\")', aptos-move/aptos-vm/src/natives.rs:55:5
```
And when i print  all native move module and function I fould 

![image](https://user-images.githubusercontent.com/73871177/196373172-01e3f475-31cc-4091-80a2-10cd6081a617.png)

## System information

**Please complete the following information:**
- branch: mainnet
- commit: 86b29874ff68bece908494a8c54ea35ac2cb0c43

**Comment by butabara** [comment]
Yea this also happens if you import aptos-sdk into aptos-node and then build it...

**Comment by flofi-dev** [comment]
same issue here - no chance to get the indexer working with
```cargo run --bin aptos-node --features "indexer"  -- --config ```

**Comment by unordered-set** [comment]
As a temporary measure you can do `git checkout 79009d61de776ac6f096634dd545be5730818c16` and then `cargo run --release --bin aptos-node --features "indexer" -- --config` meanwhile I will try to figure out what was the cause why testing modules happened to appear in prod release.

**Comment by DaveWK** [comment]
One thing to note -- I am doing `cargo build --release` not `cargo run --release` -- I make my own docker images for deploys (I have a strong preference for RHEL/Fedora) and am copying the bins out to `/opt/bin` rather than running the app inside the source folder directly. This seems a bit safer to ensure I am running a static build with less potential for unexpected side effects.
