### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zhengyiqun** [aptos-labs/aptos-core#5118]
# 🐛 Bug

[using-azure.md](https://github.com/aptos-labs/aptos-core/blob/dc9ff4ad5239a771485054fe019eebd6a7def309/developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-azure.md)  

### First words
*This is a step-by-step guide to install an Aptos node on **AWS**.*

### The "AWS" here should be "Azure"

**Comment by davidiw** [comment]
resolved, thanks
