### ISSUE TITLE
I created the address using python sdk, but I get an error when transferring

### ISSUE THREAD

**Issue by lyyzj** [aptos-labs/aptos-core#5121]
I generate a new address and try to transfer to it by python sdk on devnet or testnet
 but failed.
Then I build a transaction and submit successfully, but it returns "Move abort in 0x1:🪙 ECOIN_STORE_NOT_PUBLISHED(0x60005): Account hasn't registered CoinStore for CoinType"
![微信图片_20221018202452](https://user-images.githubusercontent.com/16589899/196428921-54abd691-fc29-494b-bd67-73471ecafebb.png)

How do I deal with this problem?

**Comment by lyyzj** [comment]
not bug

**Comment by davidiw** [comment]
an account must be created first, in the case of non Aptos coins, the coin store must be registered. You can also use 0x1::aptos_account::transfer to create and transfer in a single call.
