### ISSUE TITLE
[Bug] Aptos, this work does not belong to you

### ISSUE THREAD

**Issue by letstalkaboutaptos** [aptos-labs/aptos-core#5135]
# 🐛 Bug
Hi Aptos folks, you can't pass off the work of a very large Facebook team spanning over 4 years as your own. This is offensive to your former colleagues and the wider ecosystem.

<img width="597" alt="Screen Shot 2022-10-18 at 3 42 30 PM" src="https://user-images.githubusercontent.com/116122733/196551911-64ae3990-4e4b-46ce-a092-10b9c5f44154.png">

See this commit from May 2022, five short months ago, where you are still pulling out "Diem" text references from the code.
https://github.com/aptos-labs/aptos-core/commit/05952c29775a3f9ea3f9d3d3f26ff4ed981d80b3

A chain “for the people” does not mean taking your employer’s hundreds of millions of dollars of investment, splitting it with Silicon Valley investors, and rushing it to exchanges within the span of a few months.

The standard of ethics was low at Facebook, and blockchain has even an even lower one, but at least now your actions are public.

**Comment by vivekascoder** [comment]
Isn't it the same team that was working on Diem previously ?

**Comment by vivekascoder** [comment]
Isn't it the same team that was working on Diem previously ?

**Comment by definitelynotlegaladvice** [comment]
I don't think this is resolved.
