### ISSUE TITLE
[Bug] Claiming airdrop failed. Please ensure that your account has sufficient tokens to perform the transaction and try again.

### ISSUE THREAD

**Issue by chech-debug** [aptos-labs/aptos-core#5142]
# 🐛 Bug

Hello Aptos Team and Community, hope you all are fine!

This is my situation:   
I received two emails from the Aptos Foundation, saying that I'm eligible to claim,  but when I try to claim with the official wallet of Aptos that I use (The one I did faucet 0.025)  I have a lot of errors when I do it, like this: 

**_Claiming airdrop failed. Please ensure that your account has sufficient tokens to perform the transaction and try again._**

**_Current account doesn't match with the acoount connected to this website. Please connect again and retry_** 

Also I tried on Brave Browser, then it showed a lot of errors with Martian wallet, so I deleted cache, nothing happened, I switched to Chrome and this is the last error that shows me. The one about "Claiming airdrop failed" 

![image](https://user-images.githubusercontent.com/73460819/196596715-f574f643-447a-4613-b5fe-c4cb6527bd8f.png)

I give you some information: 
This is my account with the elegible faucet 0.025:  0x0213f32d7b7066b8be53a0dc934b480b98a36fc927b830278262811807772565 
But also, some month ago I get Aptos Zero NFT with this adress: https://aptoslabs.com/nft_offers/aptos-zero?v=2848117
Unfortunately I switched my PC and I can't get access to this adress with the Zero NFT. 
Also I'm connected in my account of the community, it's this one: https://forum.aptoslabs.com/u/imgacevi22/summary 
Discord member since 26, jul 2022 - imgacevi#8299 

If someone can help me to understand what I'm doing bad... I'll be so grateful. 

Thanks in advance for your time and for this space.

Greetings!!!

**Comment by chech-debug** [comment]
UPDATE: 
It finally worked!

**Comment by davidiw** [comment]
For folks that were eligible, they are supposed to go to the faucet first: https://aptoslabs.com/foundation-faucet
We do know that some wallets may have been asking for excessive gas that could have resulted in this issue.

It is important to note that the address is irrelevant, it is about the account used on the community platform.

**Comment by chech-debug** [comment]
Thank you so much for your answer! 
Have a nice weekend!
