### ISSUE TITLE
[Feature Request] Sign structured message

### ISSUE THREAD

**Issue by fico308** [aptos-labs/aptos-core#5150]
# 🚀 Feature Request

## Motivation
Like [EIP-4361](https://eips.ethereum.org/EIPS/eip-4361), standardize the sign-in workflow.

**Comment by gregnazario** [comment]
Right now we just sign arbitrary messages, putting this on the backlog for the wallet adapter space

**Comment by gregnazario** [comment]
Would you mind making a proposal for this?

**Comment by alinush** [comment]
AFAICT, the OP is asking for implementing something like [EIP-712](https://eips.ethereum.org/EIPS/eip-712)? If so, it's in our roadmap.

Currently, we have a way to verify signatures on structs, although it's not perfectly domain-separated via, for example, the  `ed25519::signature_verify_strict_t` Move APIs.

One important missing domain-separator there is the chain ID.

**Comment by magnum6actual** [comment]
I don't think this is what the OP was asking for - but I'd like to have a way of signing a message on-chain from a resource account, which would fit more broadly into the title of "Sign structured message". The idea being if I had some structured data that I needed to later "prove" had been reviewed/authorized by a particular resource account address, I could submit that signature with some arbitrary transaction, verify the signature, and then act on the data. Sort of functioning as an access control list without the overhead of maintaining a large list on chain.

**Comment by magnum6actual** [comment]
Although I'm realizing now the above is not possible given that resource accounts have no way to receive/manage a private key.

**Comment by dellwatson** [comment]
@alinush  is there eip-712 equivalent in aptos already? i need to authenticate offline

**Comment by alinush** [comment]
There is not one yet.
