### ISSUE TITLE
[Bug] Unsupported Terraform Core version

### ISSUE THREAD

**Issue by XingyuLi20** [aptos-labs/aptos-core#5168]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
Check Terraform Verison:
```
terraform -v
```
I get:
```
Terraform v1.3.3
on darwin_arm64
```
To reproduce (step5 on the [doc](https://aptos.dev/nodes/full-node/run-a-fullnode-on-gcp/)):
```rust
terraform init
```

**Stack trace/error message**
```
Initializing modules...
Downloading git::https://github.com/aptos-labs/aptos-core.git?ref=main for fullnode...
- fullnode in .terraform/modules/fullnode/terraform/fullnode/gcp
╷
│ Error: Unsupported Terraform Core version
│
│   on .terraform/modules/fullnode/terraform/fullnode/gcp/versions.tf line 2, in terraform:
│    2:   required_version = "~> 1.2.0"
│
│ Module module.fullnode (from
│ git::https://github.com/aptos-labs/aptos-core.git?ref=main//terraform/fullnode/gcp) does not support
│ Terraform version 1.3.3. To proceed, either choose another supported Terraform version or update this
│ version constraint. Version constraints are normally set for good reason, so updating the constraint
│ may lead to other errors or unexpected behavior.
```

## Expected Behavior

I am trying to run a public full node on GCP following this [doc](https://aptos.dev/nodes/full-node/run-a-fullnode-on-gcp/). The newest version of Terraform is `1.3.3`, however the version on the doc / git is still `~> 1.2.0`. Wonder if there is any update regarding the newest version of Terraform. Thanks!

## System information

**Please complete the following information:**
- Aptos Core Version: Lastest
- Rust Version: 1.62.1
- Computer OS: macOS Monterey Version 12.3 (M1 Pro)

## Additional context
I created a [PR](https://github.com/aptos-labs/aptos-core/pull/5169) for the fix.

**Comment by davidiw** [comment]
Use tfenv to download and use the required terraform version. The team updates when there's sufficient reason to do so. It isn't fun for folks with active deployments to take in upgrades as frequently as hashicorp updates:P
