### ISSUE TITLE
[Help] Dependency could not be resolved to any published package,How to solve the problem of not depend on others'  package

### ISSUE THREAD

**Issue by uvd** [aptos-labs/aptos-core#5181]
## ❓ Questions and Help

```
{
  "Error": "Simulation failed with status: Move abort in 0x1::code: EPACKAGE_DEP_MISSING(0x60005): Dependency could not be resolved to any published package."
}

```

**Comment by wrwg** [comment]
This error can happen if you publish a package which compiles fine locally, but on chain not all dependencies are (yet) published. So this looks as expected. Re-open if you see need.

**Comment by manhhuycao** [comment]
Hi @uvd ,
i have issue same you when i try public moon_coin pagkage.
Have you resolve this issue?
