### ISSUE TITLE
[Bug] The aptos-token on the mainnet has no `transfer_with_opt_in` entry function

### ISSUE THREAD

**Issue by icodezjb** [aptos-labs/aptos-core#5195]

**Comment by dhruvja** [comment]
it is not on devnet as well. Can u specify which function you are talking about by providing the link?

**Comment by davidiw** [comment]
@areshand , curious why we didn't make this a public entry function?

**Comment by areshand** [comment]
The change is on  testnet. we should release the change to mainnet soon to enable this entry function
