### ISSUE TITLE
Get real-time pending transactions from a local fullnode's mempool

### ISSUE THREAD

**Issue by leeeddin** [aptos-labs/aptos-core#5200]
# 🚀 Feature Request

Is there any method that can get real-time pending transactions from a local fullnode's mempool? Like the `eth_subscribe newPendingTransactions` method in geth.
I tried to use node's `/v1/transactions` API  and it doesn't seem like would return pending transactions.

**Comment by davidiw** [comment]
are you looking for all pending transactions or just your own? You can query the transaction hash and get its status from mempool.

**Comment by diwu1989** [comment]
Reading the full mempool via a stream is mostly used for sandwiching / arbitrage / MEV.

Pro of building this API into Aptos-core:
- lower entry to barrier for people to run MEV on the network

Con of building this API into Aptos-core:
- MEV / sandwich / frontrunning, etc... becomes a lot easier

**Comment by leeeddin** [comment]
Took a little peek at the code, seems like the `/v1/transactions` API will only retrieve on-chain committed transactions. The `get transaction by hash` API will retrieve transactions in mempool if they are not in storage. Guess I need to modify the client for now to retrieve all pending transactions(not just my own).

Thanks.

**Comment by vivekascoder** [comment]
can someone update on what's the scene of MEV on aptos as of now.

**Comment by greyireland** [comment]
+1
