### ISSUE TITLE
[Bug] can not start devnet 

### ISSUE THREAD

**Issue by yourmoonlight** [aptos-labs/aptos-core#5203]
# 🐛 Bug

Just can't start devnet, without any error msg, after run the docker run cmd, it will exit.

## To reproduce

mkdir aptos-fullnode && cd aptos-fullnode

mkdir data && curl -O https://raw.githubusercontent.com/aptos-labs/aptos-core/devnet/config/src/config/test_data/public_full_node.yaml && curl -O https://devnet.aptoslabs.com/waypoint.txt && curl -O https://devnet.aptoslabs.com/genesis.blob

docker run --pull=always --rm -p 8080:8080 -p 9101:9101 -p 6180:6180 -v $(pwd):/opt/aptos/etc -v $(pwd)/data:/opt/aptos/data --workdir /opt/aptos/etc --name=aptos-fullnode aptoslabs/validator:devnet_83641d3f083762f31700060e5e95fbb1cbc28bf0 aptos-node -f /opt/aptos/etc/public_full_node.yaml

OS：ubuntu22.04

**Comment by davidiw** [comment]
why are you using such an old container? 
also follow this guide: https://aptos.dev/nodes/full-node/fullnode-source-code-or-docker#method-2-using-docker

you're using an older config, if you could actually tell me how you got that config path, that'd be great.

**Comment by yourmoonlight** [comment]
[devnet_83641d3f083762f31700060e5e95fbb1cbc28bf0](https://hub.docker.com/layers/aptoslabs/validator/devnet_83641d3f083762f31700060e5e95fbb1cbc28bf0/images/sha256-9dc89a374f1b8856953f397b4e4efa57d0452d64d5b05f191b7ea8a56433f01b?context=explore)
This tag is the latest image tag for devnet.
