### ISSUE TITLE
[Bug] Outdated Terraform version 

### ISSUE THREAD

**Issue by jspeigner** [aptos-labs/aptos-core#5210]
# 🐛 Bug

The GCP Terraform version is hard set to 1.2.0 but most clients are using terraform 1.3.3 now. 
https://github.com/aptos-labs/aptos-core/blob/main/terraform/aptos-node/gcp/versions.tf

**Stack trace/error message**

Error: Unsupported Terraform Core version
│
│   on main.tf line 2, in terraform:
│    2:   required_version = "~> 1.2.0"
│
│ This configuration does not support Terraform version 1.3.3. To proceed, either choose another supported Terraform version or update this
│ version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│
│   on .terraform/modules/aptos-node/terraform/aptos-node/gcp/versions.tf line 2, in terraform:
│    2:   required_version = "~> 1.2.0"
│
│ Module module.aptos-node (from git::https://github.com/aptos-labs/aptos-core.git?ref=mainnet//terraform/aptos-node/gcp) does not support
│ Terraform version 1.3.3. To proceed, either choose another supported Terraform version or update this version constraint. Version
│ constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵
```



## Expected Behavior

Do not require version or update to 1.3.3

**Comment by davidiw** [comment]
Please use an older version of terraform. The team doesn't upgrade to the latest version of terraform unless there's a reason to do so. Please use tfenv to set to an older version.

It might be useful to give a brief overview of how we handle terraform upgrades and tfenv. I've seen several of these requests over the past week.
