### ISSUE TITLE
How can we fix  Move abort in 0x1::resource_account: 0x60001 error?

### ISSUE THREAD

**Issue by osmantuzcu2** [aptos-labs/aptos-core#5221]
I am playing with **move-examples/mint_nft** I can compile properly but I cant publish it. I am getting this error :

```
{
  "Error": "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001"
}
```
I read instructions and says use **create_resource_account_and_publish_package** function but I cant use it. Pls explain how can we properly use aptos-cli.

```
move run --function-id 0x1::resource_account::create_resource_account_and_publish_package --args XXX

```

**Comment by alice010101** [comment]
same issue I have, someone can help?

**Comment by davidiw** [comment]
Looks like you're hitting this issue: https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/aptos-move/framework/aptos-framework/sources/resource_account.move#L167

I'd suspect there's something wrong with your `init_module`, it probably isn't retrieving from the right source account.

**Comment by ozgursef** [comment]
Same not working
