### ISSUE TITLE
Indexing advanced data structures on the Node

### ISSUE THREAD

**Issue by flappys** [aptos-labs/aptos-core#5222]
No easy way to get the ownership of a token. Either you are dependent on indexers or have to go through all events to find the ownership. 

There should be an easier way to find who is the current owner of a token.

**Comment by davidiw** [comment]
I agree and disagree at the same time. And maybe we should write an article about this.

* Most existing systems today do not depend on a single service to do everything. They might have a core storage unit, caching, indexing, lookup services, routing, data interpretation layers. No production environment will shove that much logic into a single application, it wouldn't work very well.
* The existing storage / data structures in Move are only in the early days. Early on we demonstrated complex tables and vectors for more efficient storage... those wouldn't work with built-in data parsers either. We also wouldn't want to make the node depend on the Move framework.
* Doing this would make a untenable situation where developers would be required to provide updates to the node itself for any rich data that Move might store.

I'll leave this open for more discussion -- but it needs to move to aptos.dev on how to build with aptos.

@rajkaramchedu / @clay-aptos / @movekevin / @wrwg

**Comment by clay-aptos** [comment]
I will take this up in our token standard meeting tomorrow. Adding my peers as an FYI for now.

**Comment by clay-aptos** [comment]
We can try to emulate:
https://spl.solana.com/associated-token-account#finding-the-associated-token-account-address

**Comment by clay-aptos** [comment]
@areshand and @davidiw , do you have guidance for how to resolve this? Should we supplement the token standard with the information David has provided? Thanks!

**Comment by clay-aptos** [comment]
Adding @bowenyang007 since I recall Bowen saying changes to our indexer are coming. Bowen, would it address this request? Thanks!

**Comment by bowenyang007** [comment]
Well finding owners of a token will still rely on indexer, aka offchain database. There's no good way to resolve this in the smart contract right now. However token v2 solves this problem.

**Comment by bowenyang007** [comment]
Basically token v2 will have owners on the token itself. https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-11.md. It's work in progress.
