### ISSUE TITLE
Ipv6 only support 

### ISSUE THREAD

**Issue by diwu1989** [aptos-labs/aptos-core#5225]
Is it possible to run a Aptos node on a ipv6 only server?

**Comment by JoshLind** [comment]
Yes, it should be possible. Were there any specific issues you were seeing?

**Comment by gregnazario** [comment]
It's possible to be Ipv6 only in our node standard addresses. https://github.com/aptos-labs/aptos-core/blob/main/types/src/network_address/mod.rs#L789. please reopen if you have other questions
