### ISSUE TITLE
[Bug] TS SDK is able to produce SignedTransaction that gets rejected by the API without type or serialization error

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5228]
This repro was adapted from a user report (https://discord.com/channels/945856774056083548/946123778793029683/1033788411405930496) that I then verified myself.

`package.json`:
```
{
  "name": "bleh",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "blah": "node index.js"
  },
  "dependencies": {
    "aptos": "^1.3.16",
    "dotenv": "^16.0.3"
  }
}
```

`index.js`:
```
require('dotenv').config()

const aptos = require("aptos");

const NODE_URL = "https://fullnode.testnet.aptoslabs.com";

(async () => {
    const client = new aptos.AptosClient(NODE_URL);
    const sender = new aptos.AptosAccount(aptos.HexString.ensure(process.env.PRIVATE_KEY).toUint8Array());

    console.log(`Sender address: ${sender.address().toString()}`);

    const payload = aptos.TxnBuilderTypes.EntryFunction.natural(
        "0x1::aptos_account",
        "transfer",
        [],
        [
            aptos.BCS.bcsSerializeStr('0x33ee7deba6ff93be64463f4b5bcacc3b81481bc8234b088b9840b8319f6ead90'),
            aptos.BCS.bcsSerializeStr('1000')
        ]
    )

    console.log("Built payload");

    const raw = await client.generateRawTransaction(sender.address(), payload)

    console.log("Built raw transaction");

    const signed = aptos.AptosClient.generateBCSTransaction(sender, raw)

    console.log("Built signed transaction");

    const response = await client.submitSignedBCSTransaction(signed)

    console.log(`Response: ${response}`);

})();
```

Output of running `PRIVATE_KEY=<key> yarn blah`:
```
Sender address: 0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823
Built payload
Built raw transaction
Built signed transaction
/Users/dport/test/node_modules/aptos/dist/index.js:5358
        throw new ApiError2(
              ^

ApiError2: {"message":"Failed to deserialize input into SignedTransaction: DeserializationError with Ed25519PublicKey","error_code":"invalid_input","vm_error_code":null}
    at _AptosClient.wrapper (/Users/dport/test/node_modules/aptos/dist/index.js:5358:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/dport/test/index.js:33:22 {
  status: 400,
  errorCode: 'invalid_input',
  vmErrorCode: null
}
```

This error comes from the API: https://github.com/aptos-labs/aptos-core/blob/main/api/src/transactions.rs#L834.

I can't see what is wrong with the above code snippet. I have confirmed that the receiver address is a valid address format (this account already exists on chain). I've also confirmed that my private key is legit, the address above maps to a real account on testnet.

Even if the payload is invalid, we should be trying to validate it more client side first if possible.

**Comment by banool** [comment]
Note, the user reported that this snippet gave them this error instead:
```
{
  error: {
    code: 400,
    message: `Unexpected token 'C', "C9C\x17�^t�p�"... is not valid JSON`
  }
}
```

**Comment by banool** [comment]
If I remove the explicit arg serialization (`aptos.BCS.bcsSerializeStr`) it still fails in the same way. Same if I just remove the args entirely. So the deserialization API-side is failing before we even get to validation of the data itself.

**Comment by banool** [comment]
Okay figured it out, this is the correct code:
```
    const payload = new aptos.TxnBuilderTypes.TransactionPayloadEntryFunction(
        aptos.TxnBuilderTypes.EntryFunction.natural(
            "0x1::aptos_account",
            "transfer",
            [],
            [
                '0x81e2e2499407693c81fe65c86405ca70df529438339d9da7a6fc2520142b591e',
                '1000'
            ]
        ));
```
Notably, the top level payload needs to be a TransactionPayloadEntryFunction, not an EntryFunction.

This is a massive footgun, I'm gonna leave this issue open until we can find a fix. This example is in JS, but I just experimented with the above incorrect code in TS and there is no type error there either. Ideally there should be both:
- A type error
- A serialization error 

There is neither right now.

**Comment by LycrusHamster** [comment]
BTW, the ts definition and doc is quite opaque

Here is an FINE example:

    let txn = await client.generateSignSubmitWaitForTransaction(
        bob,

        new TxnBuilderTypes.TransactionPayloadEntryFunction(
            new TxnBuilderTypes.EntryFunction(
                ModuleId.fromStr("0xYourAddress::YourModuleName"),
                new Identifier("set_message"),
                [],
                [
                    // BCS.bcsToBytes(TxnBuilderTypes.AccountAddress.fromHex(`0xYourAddress`)),
                    BCS.bcsSerializeStr("Some Strings"),
                ],
            ),
        )
    )


And the following is a WRONG case:


    let txn = await client.generateSignSubmitWaitForTransaction(
        bob,

       // new TxnBuilderTypes.TransactionPayloadEntryFunction(
            new TxnBuilderTypes.EntryFunction(
                ModuleId.fromStr("0xYourAddress::YourModuleName"),
                new Identifier("set_message"),
                [],
                [
                    // BCS.bcsToBytes(TxnBuilderTypes.AccountAddress.fromHex(`0xYourAddress`)),
                    BCS.bcsSerializeStr("Some Strings"),
                ],
            ),
       // )
    )


Don't forget to put a TransactionPayloadEntryFunction class out of EntryFunction
