### ISSUE TITLE
[Bug] failed to fill whole buffer

### ISSUE THREAD

**Issue by icodezjb** [aptos-labs/aptos-core#5233]
# 🐛 Bug

## To reproduce
```bash
$ aptos move download --package arb   --url https://fullnode.mainnet.aptoslabs.com --account 0x8150d1f99683d92ce5b9eff5251705dd65988efdafa7e9bf8a3044b339d2ddb1
{
  "Error": "Unexpected error: Failed to save package: failed to fill whole buffer"
}
```

## Expected Behavior

download success

## System information

**Please complete the following information:**
Aptos CLI Version: v1.0.0
Rust Version: 1.64.0-x86_64-unknown-linux-gnu
OS: ubuntu 20.04

**Comment by icodezjb** [comment]
The guy doesn't seem to upload the code.

**Comment by icodezjb** [comment]
Fix https://github.com/aptos-labs/aptos-core/pull/5234

**Comment by davidiw** [comment]
Do you have any relationship with that package? Any idea why that one might fail?

**Comment by icodezjb** [comment]
> Do you have any relationship with that package? Any idea why that one might fail?

Maybe he run `aptos move publish --included-artifacts none`.

Here is the fix: https://github.com/aptos-labs/aptos-core/pull/5234
