### ISSUE TITLE
[Bug]how to create blockchain account on mainnet use typescript sdk.

### ISSUE THREAD

**Issue by ningjingzhiyuande** [aptos-labs/aptos-core#5240]
how to create blockchain account on mainnet use typescript sdk?

there is no fauct url.

payload = {
    "type": "entry_function_payload",
    "function": "0x1::aptos_account::create_account",
     "type_arguments": ["0x1::aptos_coin::AptosCoin"],
     "arguments": [
      account1.address,
      account1.authKey(),
      ]
    };

can't get resource.

**Comment by nixjs** [comment]
Hi @ningjingzhiyuande Can you tell, how can I create an account without using faucets? Please and thanks
