### ISSUE TITLE
[Feature Request]Sign Message With Python SDK

### ISSUE THREAD

**Issue by KucingSelenium** [aptos-labs/aptos-core#5241]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by davidiw** [comment]
I don't understand the ask, please feel free to add more details.
