### ISSUE TITLE
[Bug] aptos-rest-client error parsing with wrong entry function id `RestClient.get_transactions`

### ISSUE THREAD

**Issue by Astrapolis-peasant** [aptos-labs/aptos-core#5243]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
  use aptos_rest_client::{Client as RestClient, State, Transaction};

  let client = RestClient::new_with_timeout(node_url, Duration::from_secs(20));
  let res = client.get_transactions(Some(self.version), Some(TRANSACTION_FETCH_BATCH_SIZE)).await;
```

**Stack trace/error message**
```
 Could not fetch 1000 transactions starting at 7994873, will retry in 5000ms. Err: Unknown(error decoding response body: Invalid entry function ID 0x0:::: at line 1 column 49183
```

## Expected Behavior

The `deserialize on API types doesn't handle error entry function ids`
## System information

**Please complete the following information:**
- 
- 
-

**Comment by Astrapolis-peasant** [comment]
`https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos-rest-client/src/lib.rs`

**Comment by davidiw** [comment]
I believe this was fixed, please re-open if issue persists.
