### ISSUE TITLE
Error on Mint NFT move file on example

### ISSUE THREAD

**Issue by ozgur3512** [aptos-labs/aptos-core#5253]
{
  "Error": "Simulation failed with status: Move abort in 0x1::simple_map: 0x10002"
}

mint_nft.move file needs more explanation , I wasted my hours solving 0x60001 problem opened here before and now jumped on this one. I couldn't see anyone on discord to help as well.

**Comment by areshand** [comment]
@ozgur3512  0x10002 means key doesn't exist [[code](https://github.com/aptos-labs/aptos-core/blob/21991ffa96acde5ec211ba73dea42528a29b1e01/aptos-move/framework/aptos-stdlib/sources/simple_map.move#L16)]. I think we are add more documentation to the example cc: @chloeqjz

**Comment by areshand** [comment]
I suppose we should display the error name instead of the error code here. something went wrong with the simulation API ?@wrwg @banool

**Comment by ozgur3512** [comment]
Yes but the minting.move example on files is not working so why is it there

**Comment by ozgur3512** [comment]
> 

No update on my side, probably not going to bother more until aptos gets stable

**Comment by chloeqjz** [comment]
hey can you guys give guidance on how we can reproduce the errors?  @songliling @ozgur3512

**Comment by songliling** [comment]
@chloeqjz. Hi, The following is my operation steps, can not publish successfully, can you give me a correct publishing steps?
1. run a local node
2. aptos account fund-with-faucet --account 'default_address' --amount 1000000000
3. aptos move compile --named-addresses mint_nft=default
4. aptos move publish --named-addresses mint_nft=default
5. "Error": "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001"
6. modify mint_nft.move: 83 line of code    @0xcafe -> 0x'default_address'
7. aptos account create-resource-account --seed 1
8. aptos move compile --named-addresses mint_nft=default
9. aptos move publish --named-addresses mint_nft=default
10. "Error": "Simulation failed with status: Move abort in 0x1::simple_map: 0x10002"

**Comment by songliling** [comment]
@chloeqjz 
Thank you for your reply, I solved the error problem, the more reason is that I don't understand the mechanism of aptos, I modified the contract code to ensure that it can run correctly

**Comment by chloeqjz** [comment]
> @chloeqjz Thank you for your reply, I solved the error problem, the more reason is that I don't understand the mechanism of aptos, I modified the contract code to ensure that it can run correctly

Thanks for your feedback! We will run thru the steps ourselves, and update the documentation to make it less confusing : )

**Comment by chloeqjz** [comment]
to address this issue, we 
- added an explicit error message to the resource_account module: https://github.com/aptos-labs/aptos-core/pull/5378
- added an command to run `create_resource_account_and_publish_package`: https://github.com/aptos-labs/aptos-core/pull/5354
- updated the NFT tutorial to be less confusing: https://github.com/aptos-labs/aptos-core/pull/5388

**Comment by SuperBlockchainDeveloper** [comment]
Can anybody describe me how to solve "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001" issue?
Please help me.
Thanks in advance.

**Comment by chloeqjz** [comment]
> Can anybody describe me how to solve "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001" issue? Please help me. Thanks in advance.

Hi, it means that the specified resource account is not created by the specified source account. If you rebase off main, you'll see an updated explicit error message that says `EUNAUTHORIZED_NOT_OWNER`.

**Comment by AsfndAmin** [comment]
> @chloeqjz Thank you for your reply, I solved the error problem, the more reason is that I don't understand the mechanism of aptos, I modified the contract code to ensure that it can run correctly

can you please explain how you solved the error?

**Comment by AsfndAmin** [comment]
> Can anybody describe me how to solve "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001" issue? Please help me. Thanks in advance.

hi, did you solved this error? please help me solve this error

**Comment by 0xchloe** [comment]
> > @chloeqjz Thank you for your reply, I solved the error problem, the more reason is that I don't understand the mechanism of aptos, I modified the contract code to ensure that it can run correctly
> 
> can you please explain how you solved the error? SOLVED

Hi - if you still have questions, we updated the tutorial for it to be clearer - if you rebase off main, you could follow the steps here: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/mint_nft/sources/minting.move#L27. Lmk if you have any other questions : )

**Comment by hoang14x** [comment]
i run cmd
`aptos  move create-resource-account-and-publish-package --seed hex_array:4321 --address-name mint_nft=default --named-addresses source_addr=default
`
return
`Compiling, may take a little while to download git dependencies...
{
  "Error": "Unexpected error: Unable to resolve packages for package 'nft_mint'"
}
`
what is error?

**Comment by hoang14x** [comment]
hi @0xchloe 
i changed cmd
`cargo run -p aptos -- move create-resource-account-and-publish-package --seed hex_array:4321 --address-name mint_nft --profile default
`
respond:
`Do you want to publish this package under the resource account's address 7bd93b7892163de7465047b57bce13dc83fbb3861cfae1890fab421a7f733daf? [yes/no] >
y
package size 8802 bytes
{
  "Error": "Simulation failed with status: Move abort in 0x1::resource_account: 0x60001"
}
`
it does not create resource account? right?

**Comment by mihir1739** [comment]
Can you guys help me solve this issue ? 
` "Error": "Simulation failed with status: Move abort in 0x1::resource_account: 0x10002" `
I have referred to resource_account.move but couldn't find error with error code 2.
Thanks a lot !
