### ISSUE TITLE
[gas][storage] making sure transaction output is not too large in size

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#527]
At all levels of the system we don't want gigantic items, specifically our network frame has a hard limit.

* the gas limit on the transaction divided by per byte storage (state and events) write cost should be a reasonable upper limit
* a fallback hard limit might be needed close to the VmAdaptor / Executor boundary to give us added  confidence.

**Comment by JoshLind** [comment]
We learnt this the hard way 😄 Feel free to reopen.
