### ISSUE TITLE
How to update modules published under resource account

### ISSUE THREAD

**Issue by XD-OK** [aptos-labs/aptos-core#5271]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

Hi, 
as resource_account_cap cannot copy, so how can we update the modules published under resource account ?

**Comment by davidiw** [comment]
this is application specific, and we should probably write a more comprehensive guide, but one could imagine making an entry function associated with a contract on a resource account. that entry function has access to the cap and take as input updates to the contract to be upgraded.

unfortunately this is a choose your own adventure type of situation, so going to close this out without getting more input
