### ISSUE TITLE
Aptos sdk python transaction_argument

### ISSUE THREAD

**Issue by tufeilol** [aptos-labs/aptos-core#5274]
I have made a bot in python for minting, but there is one problem. When I'm sending args in payload for contract, It's sending this:
![image](https://user-images.githubusercontent.com/25890748/197719154-7c5de54e-653e-453d-bba9-de719264b3fd.png)
But when I do a manual mint, arguments are in string and not bytes¨
![image](https://user-images.githubusercontent.com/25890748/197719225-1fbd67c8-d38a-4de5-b8d9-8003bca2fbe1.png)

I'm using aptos_sdk
![image](https://user-images.githubusercontent.com/25890748/197719309-27ba3ada-5167-4aeb-9eb8-390c70385ef0.png)

**Comment by GilgameshH0** [comment]
Hello, how can i contact with you? Telegram? I think i have decesion

**Comment by tufeilol** [comment]
> Hello, how can i contact with you? Telegram? I think i have decesion

Telegram https://t.me/+ipUHoeWyqYA3Y2Q1

**Comment by davidiw** [comment]
I'm a bit confused... it would probably be best to see a more comprehensive example.

For now, I'll close this out with two pointers:
https://github.com/aptos-labs/aptos-core/blob/3973311dac6bb9348bfc81cf983c2a1be11f1b48/ecosystem/python/sdk/examples/simple-nft.py#L39
https://github.com/aptos-labs/aptos-core/blob/3973311dac6bb9348bfc81cf983c2a1be11f1b48/ecosystem/python/sdk/aptos_sdk/client.py#L311

Your first value looks like an address, but you're telling the system it is a string.
