### ISSUE TITLE
Is indexer service without graphql service?

### ISSUE THREAD

**Issue by 99Kies** [aptos-labs/aptos-core#5278]
I built indexer service locally and tried to query through graphql but it failed. There seems to be no documentation for the graphql service.

<https://aptos.dev/guides/indexing/#aptos-indexer-graphql-servers>

**Comment by Flofie** [comment]
Also interested in that. Is the graphql layer open source - or will it be?

**Comment by AKnownEntity** [comment]
Following, please add some documentation and or OS code for this

**Comment by davidiw** [comment]
Much of this is on aptos.dev now, feel free to re-open if you can't find what you're looking for.

**Comment by makstr** [comment]
I am trying to retrieve account tx history, I have been playing with the SDK getAccountTransactions method but got mixed results.

Following this discussion and the instructions https://aptos.dev/nodes/indexer-fullnode/ I have a running instance but as it's been already pointed out the service does not offer GraphQL.

Official documentation is inviting to use https://aptos.dev/guides/indexing/#use-the-aptos-provided-indexing-service but with a rate limit. Perhaps there is a paid plan?

There is some 3rd party apis. I explored the https://blockeden.xyz/docs/aptos/analytics-and-graphql/ which provides an indexer but the aggregate queries are locked out. There is also moralis, it gives similar results as the public GraphQL indexer but is also lacking aggregate data. 

Are there any other options out there now?
