### ISSUE TITLE
Getting the following error when trying to build the CLI on Linux Ubuntu

### ISSUE THREAD

**Issue by gideonlouw** [aptos-labs/aptos-core#5280]
Compiling libsecp256k1 v0.7.1
error: could not compile `libsecp256k1`

Caused by:
  process didn't exit successfully: `rustc --crate-name libsecp256k1 --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libsecp256k1-0.7.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="hmac"' --cfg 'feature="hmac-drbg"' --cfg 'feature="sha2"' --cfg 'feature="static-context"' --cfg 'feature="std"' --cfg 'feature="typenum"' -C metadata=1a3b062de40633bd -C extra-filename=-1a3b062de40633bd --out-dir /root/aptos-core/target/release/deps -L dependency=/root/aptos-core/target/release/deps --extern arrayref=/root/aptos-core/target/release/deps/libarrayref-0b153fe8a3900574.rmeta --extern base64=/root/aptos-core/target/release/deps/libbase64-360dcb512b9cd712.rmeta --extern digest=/root/aptos-core/target/release/deps/libdigest-d293a6310723e0a1.rmeta --extern hmac_drbg=/root/aptos-core/target/release/deps/libhmac_drbg-b5a674cae74104aa.rmeta --extern libsecp256k1_core=/root/aptos-core/target/release/deps/liblibsecp256k1_core-2cdd875a561bec14.rmeta --extern rand=/root/aptos-core/target/release/deps/librand-7c0fd0dfec1af306.rmeta --extern serde=/root/aptos-core/target/release/deps/libserde-87b1f77d3165c009.rmeta --extern sha2=/root/aptos-core/target/release/deps/libsha2-0bb076c58390aaed.rmeta --extern typenum=/root/aptos-core/target/release/deps/libtypenum-c93855bfef9a2987.rmeta --cap-lints allow --cfg tokio_unstable -C link-arg=-fuse-ld=lld` (signal: 9, SIGKILL: kill)

**Comment by JoshLind** [comment]
Are you giving the process enough memory? Can you monitor it during compilation? I suspect it's OOMing.
