### ISSUE TITLE
[Feature Request] Staking coins to validators 

### ISSUE THREAD

**Issue by anasaijaz** [aptos-labs/aptos-core#5282]
# 🚀 Feature Request

## Motivation
functions to get validators addresses and stake coins to a particular validator

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by davidiw** [comment]
I think you're asking for delegation? This is actively being worked on https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-6.md :)
