### ISSUE TITLE
[Feature Request] Need list of known coin resource addresses

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5286]
# 🚀 Feature Request

Folks in Discord are asking for a Coin type.

See:
https://discord.com/channels/945856774056083548/1034215378299133974/1034466778207764583

And:
https://aptos-labs.github.io/ts-sdk-doc/modules/Types.html

**Comment by davidiw** [comment]
aptos.dev and aptos-core aren't the right places for this. we should create a distinct onboarding guide for aptos... maybe we can change this issue?

**Comment by clay-aptos** [comment]
> aptos.dev and aptos-core aren't the right places for this. we should create a distinct onboarding guide for aptos... maybe we can change this issue?

Hrm, I thought this was a code request rather than docs. And @davidiw , are you saying we should create an onboarding guide somewhere else than Aptos.dev? I am trying to figure out how that came from this. :-)

I am adding folks involved in the coin standard to sort this out along with us. Thanks!

**Comment by clay-aptos** [comment]
More details from Discord:
```
t1dev — 10/25/2022 3:13 PM
Ecosystem documentation question:
Is there a list of known coin resource addreesses? I.E USDC, ETH, BTC, etc.

There's conflicting addresses of USDC between 2 AMMs I just tried using...
(Figured out my concern for the 2 USDC addresses, one is Layer Zero USDC and one is Wormhole USDC, but my question still stands on knowing if these are legit tokens) 
```

**Comment by clay-aptos** [comment]
I am noting @0xchloe pointed to this file in the Discord thread as an intermediary solution and also said our solution was coming:
https://github.com/hippospace/aptos-coin-list/blob/main/typescript/src/defaultList.mainnet.json

Can I help with the doc update? Is this still relevant? Thanks, all.

**Comment by gregnazario** [comment]
This is a commonly asked question https://github.com/hippospace/aptos-coin-list is the right answer for this as it is community owned

**Comment by clay-aptos** [comment]
Thanks, @gregnazario . Please see:
https://github.com/aptos-labs/aptos-core/pull/7292
