### ISSUE TITLE
Offer token without creator account

### ISSUE THREAD

**Issue by GilgameshH0** [aptos-labs/aptos-core#5295]
Hello! I am trying to send offer to claim nft, but i have not private key of creator, which needs for build AptosAccount object. Then how can i send offer? Usually we don't know private key of creator!

**Comment by GilgameshH0** [comment]
![unknown-2](https://user-images.githubusercontent.com/44002824/197906808-424fed09-de14-435c-869e-9d01474d5d21.png)

**Comment by GilgameshH0** [comment]
> > Merhaba! Nft talebinde bulunmak için teklif göndermeye çalışıyorum, ancak AptosAccount nesnesini oluşturmak için gereken yaratıcının özel anahtarına sahip değilim. O zaman nasıl teklif gönderebilirim? Genellikle yaratıcının özel anahtarını bilmiyoruz!
> 
> Oluşturucu hesabınız yok

yes, i has not account. Can you help me, how can i create transaction for mint?

**Comment by davidiw** [comment]
that's the creator's address, which you need, that is part of the token's id
