### ISSUE TITLE
How to get coin info in deposit event

### ISSUE THREAD

**Issue by KKimos** [aptos-labs/aptos-core#5302]
## ❓ Questions and Help
how to get the coin info in events in transaction? for example,  i don't know what specific coin type for what i withdraw or deposit
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/87573686/198016285-1e3c1d33-4522-4059-9eac-d3cbb5b8b3c5.png">

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by gregnazario** [comment]
I'll point you to this guide https://aptos.dev/guides/system-integrators-guide/#tracking-coin-balance-changes

But, the events itself don't hold the information, the creation number of the handle will point you to which coin it is
