### ISSUE TITLE
Can I get library for custody Verification

### ISSUE THREAD

**Issue by ratneshpatil-rp** [aptos-labs/aptos-core#5303]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by davidiw** [comment]
please add more context and re-open
