### ISSUE TITLE
`token.move` doesn't have any method to update the collection parameters based on `CollectionMutabilityConfig`

### ISSUE THREAD

**Issue by vivekascoder** [aptos-labs/aptos-core#5307]
## ❓ Questions and Help

We do have `CollectionMutabilityConfig` in `token.move` but I can't find functions to actually mutate collection parameters, I can only find `mutate_token_properties` to mutate token info, Is it possible to mutate collection params that are specified in `CollectionMutabilityConfig`?

![image](https://user-images.githubusercontent.com/54495208/198107874-2de60baf-68dd-4110-8663-61f337f5f063.png)

**Comment by vivekascoder** [comment]
If it's an issue, I would love to send an PR for it.

**Comment by davidiw** [comment]
These exist now: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-token/sources/token.move#L648
