### ISSUE TITLE
[Code Quality] Find (or implement) a custom human-readable label derive.

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#531]
We have a load of places in our code base where we implement custom human-readable labels (e.g., for enums). For example:
- https://github.com/aptos-labs/aptos-core/blob/7af7ffe81e3fe4ac85daf22babdfad5c3b56de43/state-sync/aptos-data-client/src/lib.rs#L47
- https://github.com/aptos-labs/aptos-core/blob/7af7ffe81e3fe4ac85daf22babdfad5c3b56de43/state-sync/aptos-data-client/src/lib.rs#L199
- https://github.com/aptos-labs/aptos-core/blob/94217183fd3cfe248db6947a05db61917e3af293/state-sync/storage-service/types/src/lib.rs#L67
- ....

There must be a crate that could do this for us. If not, we should create our own macro derive to handle this. This seems like a good starter task.

**Comment by msmouse** [comment]
strum? We used to use it, but stopped doing so and worked around it as part of the external dependency removal effort.
https://docs.rs/strum/latest/strum/derive.AsRefStr.html

**Comment by davidiw** [comment]
Jeez, those guys that were anal about dependencies... hahahaha
