### ISSUE TITLE
can't fetch resources from 0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948 

### ISSUE THREAD

**Issue by gcc2ge** [aptos-labs/aptos-core#5316]
## ❓ can't fetch resources from 0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948 

when fetch resoruces from 0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948

https://fullnode.mainnet.aptoslabs.com/v1/accounts/0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources

i got these error:
```
Unknown error (Unhandled) fetching an Account with address 0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948:
Error: {"message":"Too many values requested for key_prefix StateKeyPrefix { tag: AccessPath, bytes: [5, 169, 121, 134, 169, 208, 49, 196, 86, 126, 21, 183, 151, 190, 81, 105, 16, 207, 203, 65, 86, 49, 36, 130, 239, 198, 161, 156, 10, 48, 201, 72] } - maximum allowed 10000","error_code":"internal_error","vm_error_code":null}
Try again later
```

how can i get all resources from 0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948

**Comment by olivbau** [comment]
Issue already opened here #5298

**Comment by banool** [comment]
Closing this issue as #5298 is indeed referring to the same problem.
