### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by John-Smith-Ed** [aptos-labs/aptos-core#5317]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
only copy coin.move then build use playground
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
error[E01002]: unexpected token
    ┌─ /helloSam/sources/coin.move:282:12
    │
282 │     public entry fun freeze_coin_store<CoinType>(
    │            ^^^^^
    │            │
    │            Unexpected 'entry'
    │            Expected a module member: 'spec', 'use', 'friend', 'const', 'fun', or 'struct'

// Paste the output here
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Aptos Core Version -->
- <!-- Rust Version -->
- <!-- Computer OS -->
-
use playground


## Additional context

Add any other context about the problem here.

**Comment by gregnazario** [comment]
Hi, you'll have to give more information here, but I believe you're using an outdated version of the aptos CLI.  Please use the latest version `1.0.1`

https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.1

**Comment by JoshLind** [comment]
Closing this out given that there's been no response. Feel free to reopen if you require.
