### ISSUE TITLE
[Bug] testnet got OOM

### ISSUE THREAD

**Issue by yourmoonlight** [aptos-labs/aptos-core#5318]
# 🐛 Bug

## System information

**Please complete the following information:**
OS: ubuntu 22.04
Docker image tag: testnet_30447612f6505f0767405a35023dfc8a0482f06f

## Additional context

Oct 26 23:03:07 kernel: [460422.616108] Out of memory: Killed process 62539 (aptos-node) total-vm:44755712kB, anon-rss:30949020kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:79900kB oom_score_adj:0

**Comment by davidiw** [comment]
closing out stale issue.
