### ISSUE TITLE
[Bug]move prover panicked

### ISSUE THREAD

**Issue by Zzz1997Aptos** [aptos-labs/aptos-core#5319]
# 🐛 Bug

When there's `EventHandle` in module, the move prover will always panic with `thread 'tokio-runtime-worker' panicked at 'inconsistent borrow information: undefined output: table::borrow_mut'`

## To reproduce

Package manifest:
```
[package]
name = "TestProver"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "72421d32d77f1877ded478e96f5b95914de1df91" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "72421d32d77f1877ded478e96f5b95914de1df91" }
```

Module:

```
module 0x1::test {
    use aptos_framework::event::EventHandle;

    struct Container has key {
        event_handle: EventHandle<SomeEvent>
    }

    struct SomeEvent has drop,store {}
}
```

## Expected Behavior

```
$ aptos move prove
[INFO] preparing module 0x1::test
[INFO] transforming bytecode
thread 'tokio-runtime-worker' panicked at 'inconsistent borrow information: undefined output: table::borrow_mut
', /Users/USERNAME/.cargo/git/checkouts/move-0639dd674f581c30/64a03b1/language/move-prover/bytecode/src/borrow_analysis.rs:324:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
{
  "Error": "Unexpected error: task 11 panicked"
}
```

## System information

aptos 1.0.1
stable-aarch64-apple-darwin - rustc 1.64.0 (a55dd71d5 2022-09-19)
macos 13.0

**Comment by meng-xu-cs** [comment]
Working on a solution.

**Comment by meng-xu-cs** [comment]
The reason for the panic is that `table::borrow_mut` has special borrow semantics and currently we provide this information in our borrow analysis by hardcoding the function name. The solution will be to use the `is_intrinsic` test.

**Comment by Zzz1997Aptos** [comment]
@meng-xu-cs What is `is_intrinsic` test?

**Comment by meng-xu-cs** [comment]
@Zzz1997Aptos The `is_intrinsic_of` test is already added there so the Prover is expected to work fine. I confirmed that by running your example on latest `main` of aptos and does not see this error. Would you mind updating your aptos repo and try again. Let me know if you still see the same error or if you have other concerns (by re-opening this issue).

**Comment by Zzz1997Aptos** [comment]
Thx. I tried and it succeed indeed( have to change the rev of dependency to `mainnet`). However, there'e new error: 
```
[INFO] transforming bytecode
[INFO] generating verification conditions
[INFO] 10 verification conditions
[INFO] running solver
{
  "Error": "Move Prover failed: [internal] boogie exited with compilation errors:\n MYWORKDIR/boogie.bpl(3346,4): Error: call to undeclared procedure: $1_aptos_hash_keccak256\n1 name resolution errors detected in MYWORKDIR/boogie.bpl\n"
}
```
which I believe comes from this function in my module:
```
    use std::vector;
    use std::bcs;
    use std::signer;
    use aptos_std::aptos_hash::keccak256;

    public fun compute_next_id(user: address, index: u64): vector<u8> {
        let bytes = bcs::to_bytes<address>(&user);
        vector::append(&mut bytes, bcs::to_bytes<u64>(&index));
        keccak256(bytes)
    }
```
