### ISSUE TITLE
Why im getting INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE even though i have 3 apt on my wallet

### ISSUE THREAD

**Issue by M1n007** [aptos-labs/aptos-core#5323]
Why im getting INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE even though i have 3 apt on my wallet

can anyone tell me ?

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/22836345/198237454-7d4bb210-2aef-4bbe-be00-7995e65a36b9.png">

**Comment by caelumdev** [comment]
Same issue.

**Comment by caelumdev** [comment]
Did you resolved this??
