### ISSUE TITLE
"Error": "Move compilation failed: Unable to find package manifest in 'aptos-move/move-examples/hello_blockchain/' or in its parents"[Bug]

### ISSUE THREAD

**Issue by AsfndAmin** [aptos-labs/aptos-core#5324]
"Error": "Move compilation failed: Unable to find package manifest in 'aptos-move/move-examples/hello_blockchain/' or in its parents"# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by Youdonate** [comment]
I had the same bug, any solution yet

**Comment by AsfndAmin** [comment]
> 

Yes found the solution, just clone the aptos repo cd in to core_aptos and then call

**Comment by calebhughes16** [comment]
you are in the wrong directory trying to use the command. you need to be in the directory with the .toml file describing the move module you are trying to publish.

**Comment by gregnazario** [comment]
This is an error driven if it's the wrong directory.  You'll need to ensure `--package-dir` points to the directory with the `Move.toml` file

**Comment by stevekeol** [comment]
? This issue has been closed ?

**Comment by gregnazario** [comment]
To not have unable to find package manifest.  Your structure must be as follows:
```
top_folder/
top_folder/Move.toml
top_folder/sources
top_folder/sources/Module1.move
top_folder/sources/Module2.move
```

Then you can run
```
--package-dir /path-to-top-folder/top_folder
```

**Comment by avishkarabhishek786** [comment]
I was getting this error when I did not enclose address in quotes in Move.toml file:

This will not compile 
```
[addresses]
basic_address = 0x635bc91e8f3cd9759b5d90f80e94bb34fae17f9fa48345970667955d63084e3e
```

This will compile
```
[addresses]
basic_address = "0x635bc91e8f3cd9759b5d90f80e94bb34fae17f9fa48345970667955d63084e3e"
```
