### ISSUE TITLE
[Feature Request] Support u256 

### ISSUE THREAD

**Issue by icodezjb** [aptos-labs/aptos-core#5333]
[move-language has been integrated into the u256 support related code](https://github.com/move-language/move/pull/547), does aptos-coin have any plans to support u256?

**Comment by wrwg** [comment]
Indeed, we have been co-initiating this. (Aptos is move-language together with others.) But it takes some time.

**Comment by icodezjb** [comment]
> Indeed, we have been co-initiating this. (Aptos is move-language together with others.) But it takes some time.

This is good news.
