### ISSUE TITLE
mainnet  branch  install an Aptos node on AWS  EKS，validator and the validator fullnode pod  status ContainerCreating。

### ISSUE THREAD

**Issue by thangzhongyan** [aptos-labs/aptos-core#5335]
mainnet  branch  install an Aptos node on AWS  EKS，validator and the validator fullnode pod  status ContainerCreating。
![WechatIMG198](https://user-images.githubusercontent.com/18298117/198511362-f196ffef-4ce8-4135-8de3-be0b39993334.jpeg)

**Comment by davidiw** [comment]
please re-open if the issue persists.
