### ISSUE TITLE
[APT-7] dynamically create lots of cointypes in move?

### ISSUE THREAD

**Issue by aihuawu** [aptos-labs/aptos-core#5339]
I'd like to create unlimited coins for different users.
That means I have to compile a module for every user.
Is there any method to do it without compiling a module for all unknown users?

	fun m(sender: &signer) {
		aptos_framework::managed_coin::initialize<coin::MoonCoin>(
			sender,
			b"Moon Coin",
			b"MOON",
			6,
			false,
		);
	}

<sub>[APT-7](https://linear.app/aptoslabs/issue/APT-7/dynamically-create-lots-of-cointypes-in-move)</sub>

**Comment by gregnazario** [comment]
With the way it's built you need a struct in an account to create it, so you would need to still compile a module for each coin you want to create.  I'm interested in what the use case is

**Comment by davidiw** [comment]
Unfortunately this is a limitation in the implementation, you cannot dynamically create new coins out of thin air. You must publish a distinct struct for each coin. Closing out as this isn't something we'll address at the move layer.
