### ISSUE TITLE
[Feature Request] Make AccountAddress formatting consistent

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#534]
# 🚀 Feature Request

## Motivation
there are a set of methods that convert accountaddress into multiple formats (1) with 0x prefix (2) without 0x prefix (3) without leading 0s. These are not compatible with each other now. 
We should either 
1. keep the account address and its string representation consistent, 
2. or provide APIs that is used to read from string or convert account address to string.

Here are some places to be cleaned up. 

- [ ] test_from_and_to_account_address
- [ ] remove auth_key from faucet
- [ ] mint param receiver ([link](https://github.com/areshand/aptos-core-1/blob/f692805781524756482f531f6a9f2ed3db97c9e4/crates/aptos-faucet/src/mint.rs#L82)), make sure we can have an API to consume both 0x or non 0x for user input.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by gregnazario** [comment]
https://github.com/move-language/move/pull/54 to make the 0x inputs more consistent
