### ISSUE TITLE
[Feature Request] Add Create Resource account and publish package API in TS SDK

### ISSUE THREAD

**Issue by dhruvja** [aptos-labs/aptos-core#5349]
# 🚀 Feature Request

Adding a function in SDK that would create resource account and publish package i.e. call this function in module - https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/resource_account.move#L121 . Right now we only have a function to publish package, adding this would be a great thing.

## Motivation

- There is a lot of ambiguity in what parameters mean and where to fetch them. The `publish` function in SDK makes it clear and takes care of the serializing part.
- Many people are struggling to call the module function and it would really good to have a function which can do by just passing the important parameters and serializing and other things done under the hood.

## Pitch

Having a function in SDK which takes parameters and does serializing under the hood . And then make a transaction to `0x1::resource_account::create_resource_account_and_publish` . 

I would be willing to open a pull request and add the above solution.

**Comment by davidiw** [comment]
> I would be willing to open a pull request and add the above solution.

Please do :)

**Comment by Shusanta** [comment]
has this been added? @dhruvja @davidiw
