### ISSUE TITLE
What's the "create_resource_account_and_publish_package()"

### ISSUE THREAD

**Issue by tmac2yt** [aptos-labs/aptos-core#5356]
**call create_resource_account_and_publish_package() to publish this module under the resource account's address.
/// init_module() will be called as part of publishing the package. In init_module(), we set up the NFT collection to mint.**

I saw this description, but I can't understand its meaning. Who can explain it to me?

Where is this method? Why can't I find it? How do I call it?
**create_resource_account_and_publish_package()**

**Comment by tmac2yt** [comment]
And I tried the NFT example:
https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/move-examples/mint_nft

When I runned the test,I got this issue:
PS D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft> D:\aptos\aptos.exe move test --named-addresses mint_nft=default
?[1;32mINCLUDING DEPENDENCY?[0m AptosFramework
?[1;32mINCLUDING DEPENDENCY?[0m AptosStdlib
?[1;32mINCLUDING DEPENDENCY?[0m AptosToken
?[1;32mINCLUDING DEPENDENCY?[0m MoveStdlib
?[1;32mBUILDING?[0m Examples
Running Move unit tests
[ ?[1;91mFAIL?[0m    ] 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting::test_happy_path
[ ?[1;91mFAIL?[0m    ] 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting::test_invalid_signature
[ ?[1;91mFAIL?[0m    ] 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting::test_minting_expired
[ ?[1;91mFAIL?[0m    ] 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting::test_update_expiration_time
[ ?[1;91mFAIL?[0m    ] 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting::test_update_minting_enabled

Test failures:

Failures in 0xae5bd28f05078d708022a539fcf6c83c3e8676fc856fb7a71d1bcce212331ea::minting:

┌── ?[1mtest_happy_path?[0m ──────
│ ITE: An unknown error was reported. Location: ?[0m?[1m?[38;5;9merror[E11001]?[0m?[1m: test failure?[0m
│     ?[0m?[36m┌─?[0m D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft\../../framework/aptos-framework\../aptos-stdlib\sources\cryptography\ed25519.move:228:16
│     ?[0m?[36m│?[0m
│ ?[0m?[36m228?[0m ?[0m?[36m│?[0m     native fun ?[0m?[31mgenerate_keys_internal?[0m(): (vector<u8>, vector<u8>);
│     ?[0m?[36m│?[0m                ?[0m?[31m^^^^^^^^^^^^^^^^^^^^^^?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36m│?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36mIn this function in 0x1::ed25519?[0m
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },
│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
└──────────────────


┌── ?[1mtest_invalid_signature?[0m ──────
│ ITE: An unknown error was reported. Location: ?[0m?[1m?[38;5;9merror[E11001]?[0m?[1m: test failure?[0m
│     ?[0m?[36m┌─?[0m D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft\../../framework/aptos-framework\../aptos-stdlib\sources\cryptography\ed25519.move:228:16
│     ?[0m?[36m│?[0m
│ ?[0m?[36m228?[0m ?[0m?[36m│?[0m     native fun ?[0m?[31mgenerate_keys_internal?[0m(): (vector<u8>, vector<u8>);
│     ?[0m?[36m│?[0m                ?[0m?[31m^^^^^^^^^^^^^^^^^^^^^^?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36m│?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36mIn this function in 0x1::ed25519?[0m
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },
│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
└──────────────────


┌── ?[1mtest_minting_expired?[0m ──────
│ ITE: An unknown error was reported. Location: ?[0m?[1m?[38;5;9merror[E11001]?[0m?[1m: test failure?[0m
│     ?[0m?[36m┌─?[0m D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft\../../framework/aptos-framework\../aptos-stdlib\sources\cryptography\ed25519.move:228:16
│     ?[0m?[36m│?[0m
│ ?[0m?[36m228?[0m ?[0m?[36m│?[0m     native fun ?[0m?[31mgenerate_keys_internal?[0m(): (vector<u8>, vector<u8>);
│     ?[0m?[36m│?[0m                ?[0m?[31m^^^^^^^^^^^^^^^^^^^^^^?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36m│?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36mIn this function in 0x1::ed25519?[0m
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },
│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
└──────────────────


┌── ?[1mtest_update_expiration_time?[0m ──────
│ ITE: An unknown error was reported. Location: ?[0m?[1m?[38;5;9merror[E11001]?[0m?[1m: test failure?[0m
│     ?[0m?[36m┌─?[0m D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft\../../framework/aptos-framework\../aptos-stdlib\sources\cryptography\ed25519.move:228:16
│     ?[0m?[36m│?[0m
│ ?[0m?[36m228?[0m ?[0m?[36m│?[0m     native fun ?[0m?[31mgenerate_keys_internal?[0m(): (vector<u8>, vector<u8>);
│     ?[0m?[36m│?[0m                ?[0m?[31m^^^^^^^^^^^^^^^^^^^^^^?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36m│?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36mIn this function in 0x1::ed25519?[0m
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },
│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
└──────────────────


┌── ?[1mtest_update_minting_enabled?[0m ──────
│ ITE: An unknown error was reported. Location: ?[0m?[1m?[38;5;9merror[E11001]?[0m?[1m: test failure?[0m
│     ?[0m?[36m┌─?[0m D:\projects\myth\myth-aptos\aptos-core\aptos-move\move-examples\mint_nft\../../framework/aptos-framework\../aptos-stdlib\sources\cryptography\ed25519.move:228:16
│     ?[0m?[36m│?[0m
│ ?[0m?[36m228?[0m ?[0m?[36m│?[0m     native fun ?[0m?[31mgenerate_keys_internal?[0m(): (vector<u8>, vector<u8>);
│     ?[0m?[36m│?[0m                ?[0m?[31m^^^^^^^^^^^^^^^^^^^^^^?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36m│?[0m
│     ?[0m?[36m│?[0m                ?[0m?[36mIn this function in 0x1::ed25519?[0m
│
│
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },











│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
└──────────────────

Test result: ?[1;91mFAILED?[0m. Total tests: 5; passed: 0; failed: 5
{
  "Error": "Move unit tests failed"
}

Who can help me?A lot thanks!

**Comment by chloeqjz** [comment]
Could you try global searching the function `create_resource_account_and_publish_package` in the `aptos-core` codebase? It's inside aptos-core/aptos-move/framework/aptos-framework/sources/resource_account.move`. 

Also, could you please follow up on an existing issue instead of creating a new issue next time? This helps us keep track of things. Thanks. For examples, resouce-account-related existing issues: https://github.com/issues?q=is%3Aissue+assignee%3Achloeqjz+archived%3Afalse+is%3Aclosed and https://github.com/aptos-labs/aptos-core/issues/5373
