### ISSUE TITLE
[Bug] 0x3::token::TokenStore Deposit Event got Stuck without Paging

### ISSUE THREAD

**Issue by HaMaTechnology** [aptos-labs/aptos-core#5359]
# 🐛 Bug
How to get  all my NFT in wallet?. I'm use to reading event from deposit and subtract to withdraw_event from Token Store.
But Deposit Event got Stuck without Paging.
Ex:
FAIL case: https://fullnode.testnet.aptoslabs.com/v1/accounts/0x86911211690c8b39915370f86f8b15b2062177d9c3738d68ff6553779d69e95b/events/0x3::token::TokenStore/deposit_events
SUCCESS case: https://fullnode.testnet.aptoslabs.com/v1/accounts/0x86911211690c8b39915370f86f8b15b2062177d9c3738d68ff6553779d69e95b/events/0x3::token::TokenStore/deposit_events?start=1
Could you explain this?. 

Expected: Skip if current data table is empty and go to next data table.

**Comment by gregnazario** [comment]
Yes, this looks like a recent regression, and it's interesting that this is happening now.

Limiting by 1 also fixes the issue

https://fullnode.testnet.aptoslabs.com/v1/accounts/0x86911211690c8b39915370f86f8b15b2062177d9c3738d68ff6553779d69e95b/events/0x3::token::TokenStore/deposit_events?limit=1

**Comment by gregnazario** [comment]
This looks like it's been fixed
