### ISSUE TITLE
[Feature Request] On-Chain Query with function

### ISSUE THREAD

**Issue by babyface001** [aptos-labs/aptos-core#5365]
# 🚀 Feature Request

query data with functions 
## Motivation

now we can only query storage.

can we query data like ethereum eth_call

**Comment by babyface001** [comment]
the biggst problem now is we must implement some algorithm with move and js.

**Comment by gregnazario** [comment]
Duplicate of view functions https://github.com/aptos-labs/aptos-core/issues/4915
