### ISSUE TITLE
[RFE] Integrate auto-generated reference materials directly in Aptos.dev

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5366]
# Request for Enhancement (RFE)

We have numerous auto-generated reference materials we should consider integrating directly into Aptos.dev for better discovery and search indexing:

Our API docs:
https://fullnode.devnet.aptoslabs.com/v1/spec#/

Move reference files:
https://aptos.dev/guides/move-guides/aptos-move-guides#aptos-move-documentation

And forthcoming Rustdoc for our SDK.

@banool  is working on integrating the API docs in:
https://github.com/aptos-labs/aptos-core/pull/5345/files

@wrwg added the refreshed Move docs to the repo in:
https://github.com/aptos-labs/aptos-core/pull/5187

And I am working with @gregnazario on generating Rustdoc output in:
https://github.com/aptos-labs/aptos-core/pull/5029

I am asking @zacharydenton for his thoughts on integrating Move Generator and Rustdoc directly into Aptos.dev. And I've copied the parties above for their thoughts and we can coordinate. Thanks, all.

We should also explore how to expose all of the Markdown files in our repo, even if through manual links from relevant pages (possibly tracked in a distinct issue).

**Comment by wrwg** [comment]
Just to be clear about #5187 this is not just about refreshing the docs, this is a mechanism which keeps documents automatically up-to-date with each code change. I'm not sure whether something similar will be possible if integrated into the aptos.dev. Moreover, currently at least some of the generated markdown format is specific to the Github MD dialect, so the generator would likely have to be changed if addressing another MD engine.

**Comment by clay-aptos** [comment]
> Just to be clear about #5187 this is not just about refreshing the docs, this is a mechanism which keeps documents automatically up-to-date with each code change. I'm not sure whether something similar will be possible if integrated into the aptos.dev. Moreover, currently at least some of the generated markdown format is specific to the Github MD dialect, so the generator would likely have to be changed if addressing another MD engine.

Ah, thanks for the context. Noted.

**Comment by clay-aptos** [comment]
@banool reminds me we have another whole class of docs to consider at:
https://aptos-labs.github.io/ts-sdk-doc/
https://pypi.org/project/aptos-sdk/

With the former automated and the latter manually updated. We are writing up some internal docs to make the API doc flow clear.

**Comment by clay-aptos** [comment]
@gregnazario and @geekflyer , can we work together to publish our Rustdoc for the Rust SDK?

**Comment by wrwg** [comment]
I think this is done now? Reopen as needed.

**Comment by clay-aptos** [comment]
Removing @wrwg and adding @Mine77 , who I raised this with today.

We still could better integrate the Python, Rust, and TypeScript reference files into Aptos.dev. @banool delivered the API docs, and @wrwg explained why we can't add the Move reference docs (perpetually updated in place).

**Comment by clay-aptos** [comment]
We have integrated what we can now. Closing this as further work for Rust is requested and tracked in:
https://github.com/aptos-labs/aptos-core/issues/6275#issuecomment-1505711373
