### ISSUE TITLE
[RFE] Improve Staking documentation, explain configuration

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5368]
# 🐛 Request for Enhancement

Regarding:
https://aptos.dev/concepts/staking/#staking-on-the-aptos-blockchain

We should include the data that's currently on chain and a pointer to it. Specifically:
https://mainnet.aptoslabs.com/v1/accounts/0x1/resource/0x1::staking_config::StakingConfig
That points to:
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/configs/staking_config.move

We should also interpret the parameters in our tech doc too.

Finally, I see now this link in the doc:

```
Triggers at the epoch start
TIP
See https://github.com/aptos-labs/aptos-core/blob/0daade4f734d1ba29a896b00d7ddde2249e87970/aptos-move/framework/aptos-framework/sources/configs/stake.move#L862 for the full code.
```

But I think that might be an older version of the `staking_config.move` file above. If so, we should re-link and make clear the purpose of that file.

**Comment by movekevin** [comment]
Should we track Aptos Governance in a separate issue?

**Comment by clay-aptos** [comment]
> Should we track Aptos Governance in a separate issue?

Yes, removed from here. Want me to file the separate issue? What are we looking to document in governance?

**Comment by clay-aptos** [comment]
Hi @movekevin and @davidiw , please see:
https://github.com/aptos-labs/aptos-core/pull/5401

**Comment by clay-aptos** [comment]
I also saw this referenced in a thread about ` request_commissions`:
https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/aptos-move/framework/aptos-framework/sources/staking_contract.move

Should we point to all of the stak*.move files in this directory for more information.
https://github.com/aptos-labs/aptos-core/tree/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/aptos-move/framework/aptos-framework/sources

**Comment by clay-aptos** [comment]
And link to:
https://aptos.dev/nodes/validator-node/operator/staking-pool-operations/#requesting-commission

**Comment by clay-aptos** [comment]
https://aptos.dev/nodes/validator-node/operator/staking-pool-operations/#description-of-output-fields

**Comment by clay-aptos** [comment]
@movekevin , please reopen this if you have more planned for this topic soon. Thanks!
