### ISSUE TITLE
[Feature Request] Aptos Version Manager

### ISSUE THREAD

**Issue by daweth** [aptos-labs/aptos-core#5375]
# 🚀 Feature Request

An Aptos Version Manager, like [Go Version Manager](https://github.com/moovweb/gvm) and [Anchor Version Manager](https://www.anchor-lang.com/docs/avm), etc.

## Motivation

**Is your feature request related to a problem? Please describe.**
It's a pain to install updates to the aptos cli

## Pitch

**Describe the solution you'd like**
Aptos Version Manager, (aptvm to not be confuseed with anchor version manager)

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes I'm willing to break ground on this issue.

**Comment by gregnazario** [comment]
Just wondering, which platform are you running on?

We were considering something like brew for Mac, etc which is more native than building a standalone version management application

**Comment by bbenzikry** [comment]
Hi, I would greatly appreciate brew / equivalent for aptos-cli. I'm currently using zsh/zinit installations to follow releases on GH.
