### ISSUE TITLE
[Performance] Unify the Tokio Runtimes

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#538]
Our code base has a lot of Runtimes. Tokio is a cooperative multitasking system, which means it runs work until it is complete or hits an await. If there were only a single runtime, contention on the CPU would come from competing processes. Each process naturally has to pay a cost for task switching. However, the cost for switching executions from one tokio task to another is not substantial as the task is waiting for work to complete -- it aligns on natural boundaries. However, having multiple runtimes increases the tension on a processor where total number of threads can quickly exceed the number of processors resulting in substantial tension. Imagine a consensus thread being interrupted by networking or mempool that would pre-empt work that might have saved those processes from doing unnecessary operations resulting in non-negligible CPU waste. The goal of this project is to better understand the impact from our executor explosion, by merging them and to potentially fine-tune the number of threads we have. We can use forge (/canary) to evaluate the impact of these decisions.

The problem can be further explored by exploring the Rayon dependency and figuring out if there's an appropriate way to balance out the contention that might bring to a node -- here's something to chew on: https://thenewstack.io/using-rustlangs-async-tokio-runtime-for-cpu-bound-tasks/

```
./crates/debug-interface/src/node_debug_service.rs:        let runtime = Builder::new_multi_thread()
./api/src/runtime.rs:    let runtime = Builder::new_multi_thread()
./mempool/src/tests/mocks.rs:        let runtime = Builder::new_multi_thread()
./mempool/src/tests/shared_mempool_test.rs:    let runtime = Builder::new_multi_thread().enable_all().build().unwrap();
./mempool/src/tests/node.rs:    let runtime = Builder::new_multi_thread()
./mempool/src/shared_mempool/runtime.rs:    let runtime = Builder::new_multi_thread()
./consensus/src/twins/twins_node.rs:        let runtime = Builder::new_multi_thread()
./consensus/src/consensus_provider.rs:    let runtime = runtime::Builder::new_multi_thread()
./consensus/src/test_utils/mod.rs:    runtime::Builder::new_multi_thread()
./aptos-node/src/lib.rs:    let streaming_service_runtime = Builder::new_multi_thread()
./aptos-node/src/lib.rs:    let aptos_data_client_runtime = Builder::new_multi_thread()
./aptos-node/src/lib.rs:    let storage_service_runtime = Builder::new_multi_thread()
./aptos-node/src/lib.rs:        let runtime = Builder::new_multi_thread()
./aptos-node/src/lib.rs:    let telemery_runtime = Builder::new_multi_thread()
./state-sync/state-sync-v1/src/bootstrapper.rs:        let runtime = Builder::new_multi_thread()
./state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs:                Builder::new_multi_thread()
./state-sync/inter-component/consensus-notifications/src/lib.rs:        Builder::new_multi_thread().enable_all().build().unwrap()
./state-sync/inter-component/mempool-notifications/src/lib.rs:        Builder::new_multi_thread().enable_all().build().unwrap()
./storage/backup/backup-service/src/lib.rs:    let runtime = Builder::new_multi_thread()
```

**Comment by JoshLind** [comment]
@davidiw, I like it!

it's worth calling out that I actually did this a while back (maybe 6 months 🤔) and the result was a significant decrease in consensus tps (through canary). My suspicion at the time was that there's probably tasks that are being spawned that are CPU or I/O bound that don't yield frequently (thus leading to starvation for the rest). On different runtimes, it wasn't so bad, but with a single runtime we're seeing starvation of more important tasks (e.g., consensus tasks). These should likely be spawned with [`spawn_blocking`](https://docs.rs/tokio/0.2.25/tokio/task/fn.spawn_blocking.html).

Either way, it would be cool to see how much this can help us. 🚀

**Comment by zekun000** [comment]
the assumption of a single runtime is that all tasks are cooperative/IO intensive. we should at least split CPU and IO pool
