### ISSUE TITLE
[Feature Request] event handle api return txhash

### ISSUE THREAD

**Issue by liuxiaobleach** [aptos-labs/aptos-core#5383]
# 🚀 Feature Request

Now, the api for querying event by handle only return version.
While most system need the txhash.
Can we support returning txhash in this api?
https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_events_by_event_handle

**Comment by gregnazario** [comment]
Transaction version is synonymous with the hash, and is immutable.  If the hash is needed it can be pulled from the API via the version.

I'm curious about the exact use case that doesn't support version.

**Comment by liuxiaobleach** [comment]
Thx for your relay.

**Comment by liuxiaobleach** [comment]
While I know I can get the txhash by version with another api, but get the txhash just in event handle can save more requests. And I think it is not hard to get the txhash and return it in curretn event api.

**Comment by liuxiaobleach** [comment]
Version also can support my requirement.
But it can be more easy to use for multi bridge DAPP, if the event return txhash.
Developers do not need to change their code when use aptos.

**Comment by liuxiaobleach** [comment]
@gregnazario Any idea?
