### ISSUE TITLE
Aptos Move Clean can't clean local package download cache

### ISSUE THREAD

**Issue by daweth** [aptos-labs/aptos-core#5387]
# 🐛 Bug

When `aptos move clean` is run the user is prompted with 'Do you also want to delete the local package download cache at '/Users/u/.move'? [y/n]

If 'y' is selected, the following error occurs every time:
 
```
{
  "Error": "Error accessing 'Removing Move build dir': No such file or directory (os error 2)"
}
```

I suspect this has to do with the bundling of the move CLI within the aptos CLI?

**Comment by gregnazario** [comment]
This just looks like a bug because it assumes that there's a local `build` folder.  By adding a `build` folder, it successfully deletes the cache.

It's a bug in the Aptos CLI code.

**Comment by gregnazario** [comment]
Fix here: https://github.com/aptos-labs/aptos-core/pull/5500
