### ISSUE TITLE
"Error": "API error: API error Error(ResourceNotFound): Resource not found by Address

### ISSUE THREAD

**Issue by AsfndAmin** [aptos-labs/aptos-core#5390]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by hoangman1108** [comment]
i know this issue.
it happen when your wallet not have APT deposit in to wallet. not bug

**Comment by banool** [comment]
Not enough detail to resolve, closing for now. If you still run into this, please reach out in #dev-discussion on Discord.
