### ISSUE TITLE
Error connection 

### ISSUE THREAD

**Issue by lijianl** [aptos-labs/aptos-core#5393]
when i scan TX on chain, the sdk is unstable, could you give some advice for this,

the testnet url  and the mainnet rest url

ApiError2: {"message":"Generic Error"}

**Comment by movekevin** [comment]
Can you provide more information on how you ran into this issue and the full stacktrace so we can reproduce? Code snippets would be great as well

**Comment by gregnazario** [comment]
It would be helpful to give the following:
1. Which SDK is it
2. how did you run into this issue, and how can it be reproduced?
3. Any code snippets or traces associated
