### ISSUE TITLE
[Feature Request] Improve generated documentation + How to navigate and find the right libraries

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#5397]
Currently generated docs for Move libraries are not the easiest to find and navigate. The documentation is also not the easiest to follow and there are missing details in several places.

**Comment by clay-aptos** [comment]
Thanks, @movekevin. We have published links here:
https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/framework#readme
https://aptos.dev/guides/move-guides/aptos-move-guides#aptos-move-documentation

With more improvements on the way:
https://github.com/aptos-labs/aptos-core/pull/5442
https://github.com/aptos-labs/aptos-core/issues/5366

**Comment by clay-aptos** [comment]
And now:
https://github.com/aptos-labs/aptos-core/pull/5510
