### ISSUE TITLE
[Bug] using window.aptos, send a transaction, got an unit price error

### ISSUE THREAD

**Issue by magk4ce** [aptos-labs/aptos-core#5409]
# 🐛 Bug

In example Dapp, trying to send a transaction by window.aptos.signAndSubmitTransaction(transaction), got an error.  

**Code snippet to reproduce**
```javascript
window.aptos.signAndSubmitTransaction(transaction)
```

**Stack trace/error message**
```
"Transaction Failed: Invalid transaction: Type: Validation Code: GAS_UNIT_PRICE_BELOW_MIN_BOUND     at t " .
```

 Any place to set the default gas unit price?

**Comment by davidiw** [comment]
This api has been revamped to address these issues :)
