### ISSUE TITLE
[RFC] Explore network compression for AptosNet.

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#541]
## Motivation
In AptosNet today, we're currently seeing network message serialization sizes of: 0.7KB per transaction and 1.5KB per transaction output. This means a chunk of 1k transactions is 770KB and 1k outputs is 1.5MB (!). This is a lot of data to synchronize if we're targeting global TPS.

## Compression

To reduce data sizes, we can employ compression at the AptosNet layer. I wrote a super-hacky benchmark to get some approximate numbers when running a fullnode (e.g., https://github.com/aptos-labs/aptos-core/pull/540). The preliminary results were interesting:
- I looked at `flate2`(https://docs.rs/flate2/latest/flate2/), `minize_oxide`(https://docs.rs/miniz_oxide/0.5.1/miniz_oxide/) and `snap`(https://docs.rs/snap/1.0.5/snap/). These seem well known.
- Overall, looking at the best numbers offered by each one (including the different encoding types and compression levels), I saw:
    - 1k transactions can be compressed by 5x (reducing data sizes by 80%) in about 100-200ms, and decompressed in < 100ms
    - 1k transaction outputs could be compressed by 10x (reducing data sizes by 90%) in about 200ms and decompressed in < 100ms.
    - As messages get bigger, the compression results stay relatively similar 5x -> 10x smaller and the time grows somewhat linearly. More investigation required.
    - There is (of course) variance depending on what configuration you use but the crates were relatively similar.
    - Tiny messages get bigger by 2x-5x (due to compression encoding overheads), e.g., anything smaller than 100 bytes.

## Discussion
- To support backward compatibility in AptosNet in the future, we'd eventually like to serialize messages using JSON. We're currently doing this for [consensus](https://github.com/aptos-labs/aptos-core/blob/79acf64ccadc4a4394a50dac8cf8ea293fa81cba/network/src/protocols/wire/handshake/v1/mod.rs#L96) messages, but not for anything else (we're using BCS, otherwise). The disadvantage of JSON is that it's ~3x larger than BCS (last time I checked). Without compression, this isn't great. But, with compression, I'd imagine we'd get even better results than above. This needs to be investigated.
- For latency sensitive applications (e.g., consensus) compression isn't ideal because it could introduce TPS regression if network latency is on the critical path. For other applications that are avoiding network bottlenecks (e.g., state sync because it does parallel pre-fetching), compression shouldn't even make an impact. 
- Given that state sync is currently the largest data consumer, it might make sense to employ compression for state sync only. Especially when we get to larger TPS.
- There is a network/CPU trade-off with compression. The same goes for transaction vs. transaction output syncing. If a client is low on CPU, compression might be a no-go. But, on the plus side, one could argue that it's easier/better to perform compression than it is to execute transactions because compression is: (i) well understood and stable; (ii) can be trivially parallelized (across messages); and (iii) is widely available in different environments and programming languages. I don't think the same can be argued for the VM executor today 😄 
- We currently have hard-coded upper bounds on the sizes of a single message. This leads to some concerns with large items (e.g., https://github.com/aptos-labs/aptos-core/issues/527#event-6441480428). Compression can help reduce these concerns (but, it won't entirely eliminate them).

## Takeaways
- We currently have higher priorities but, eventually, this seems like a promising direction to explore. More thorough benchmarking should be done, even if it's only for data-intensive applications (e.g., state sync and mempool).
- I found an old EIP that argued for similar findings (https://eips.ethereum.org/EIPS/eip-706). But, unlike the EIP I don't currently think it makes sense to do this for *all applications*.

**Comment by zekun000** [comment]
I think the 5x comes mainly from compressing the block metadata txns, I have https://github.com/aptos-labs/aptos-core/issues/350 opened to optimize that. (because all the duplicate validator addresses).

I wonder how much we'd get from ordinary p2p txns, probably not as much.
