### ISSUE TITLE
[Feature Request] rust sdk get_transaction_by_version should return gas_unit_price

### ISSUE THREAD

**Issue by liuxiaobleach** [aptos-labs/aptos-core#5410]
# 🚀 Feature Request

rust sdk get_transaction_by_version should return gas_unit_price

**Comment by gregnazario** [comment]
`gas_unit_price` can always be found in the `RawTransaction` that is provided in the `TransactionOnChainData` as the `transaction`

https://github.com/aptos-labs/aptos-core/blob/main/types/src/transaction/mod.rs#L59-L89
