### ISSUE TITLE
How to use the CLI to transfer the parameter type Vec<bool>.

### ISSUE THREAD

**Issue by weishengbin** [aptos-labs/aptos-core#5413]
I'm having a problem using the cli, the original array is: [false,false,false]. What do I do if I want to use cli to pass arguments? Better have examples Thank you!

**Comment by gregnazario** [comment]
Current CLI doesn't support it, but there is a PR out for it, just needs some tests and all https://github.com/aptos-labs/aptos-core/pull/5192

**Comment by weishengbin** [comment]
> 当前的 CLI 不支持它，但是有一个 PR，只需要一些测试和所有#5192



> Current CLI doesn't support it, but there is a PR out for it, just needs some tests and all #5192

Ok, thank you.

**Comment by weishengbin** [comment]
> Current CLI doesn't support it, but there is a PR out for it, just needs some tests and all #5192

Ok, thank you.

**Comment by gregnazario** [comment]
It's in the latest release
