### ISSUE TITLE
[Bug] submit transaction with api error

### ISSUE THREAD

**Issue by hoangman1108** [aptos-labs/aptos-core#5414]
# 🐛 Bug
post this api:
`https://fullnode.devnet.aptoslabs.com/v1/transactions/transactions `

get

```
Message: Http status error [202]
```
and balance nó change + hash search on explore not found
i dont know what i can do to continue

**Comment by gregnazario** [comment]
202 means a successful submission.  However, your transaction may be dropped because your expiration time is too short.  It has to be propagated to the validators via the Mempool, and it will be dropped if it expires before it makes it there.

https://aptos.dev/reference/glossary/#expiration-time
