### ISSUE TITLE
i generate wallet and see this error? How to solved?

### ISSUE THREAD

**Issue by hoang14x** [aptos-labs/aptos-core#5417]
### Please note that this issue tracker is not a help form and this issue will be closed.

` 228 │     native fun generate_keys_internal(): (vector<u8>, vector<u8>);
│     │                ^^^^^^^^^^^^^^^^^^^^^^
│     │                │
│     │                In this function in 0x1::ed25519
│ 
│ 
│ VMError (if there is one): VMError {
│     major_status: MISSING_DEPENDENCY,
│     sub_status: None,
│     message: Some(
│         "Missing Native Function `generate_keys_internal`",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "ed25519",
│             ),
│         },
│     ),
│     indices: [],
│     offsets: [
│         (
│             FunctionDefinitionIndex(1),
│             0,
│         ),
│     ],
│ }
`

**Comment by 0xJackJun** [comment]
Same problem

**Comment by davidiw** [comment]
generate wallet where? feel free to re-open with more steps on how to repro
