### ISSUE TITLE
Clarify what `get_message` is for in hello blockchain / remove it completely

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5420]
This recently came up in a StackOverflow question: https://stackoverflow.com/questions/74133381/how-do-you-define-and-query-a-read-function-in-a-move-module-on-aptos-blockchain.

Indeed, when I was first onboarding, I made this comment in my notes:
> The get_message function in HelloBlockchain is misleading. It implies you'd call that to read the message from an external application, whereas really you'd read the account resources via the REST API.

We should make this clear in the example or just remove this function.

**Comment by gregnazario** [comment]
This function allows you to build another application that would read that from onchain.  I think it can probably stay around for view functions
