### ISSUE TITLE
[Bug]  Invalid transaction: Type: Validation Code: TRANSACTION_EXPIRED

### ISSUE THREAD

**Issue by Jsoooooooo** [aptos-labs/aptos-core#5428]
<img width="1267" alt="截屏2022-11-03 14 51 54" src="https://user-images.githubusercontent.com/104627404/199662396-578cee6c-64d6-4bd1-9152-74b1f7724e9a.png">

Hello, I frequently meet the error, could you tell how to fix it?

**Comment by gregnazario** [comment]
This means that the expiration time for a transaction was too short for your time period. You can set the expiration time with the value `expiration_timestamp_secs`

https://aptos-labs.github.io/ts-sdk-doc/types/Types.SubmitTransactionRequest.html#__type.expiration_timestamp_secs

**Comment by Jsoooooooo** [comment]
One more question, thanks. The script below comes with an error ‘invalid_auth_key’. I know there must be something wrong while initiating the AptosAccount. While, I didn’t find  any answer on how to new an AptosAccount while knowing account address.

Many thanks,

**Comment by davidiw** [comment]
invalid auth key means that you generated your txn incorrectly -- maybe mixing up the sending accounts credentials?

**Comment by hanho1** [comment]
![62520863-4EA1-4528-A9C0-7733B7845F9D](https://github.com/aptos-labs/aptos-core/assets/160141765/bbe9a89b-bc83-46b7-8a34-1cbb509d42d0)
![image](https://github.com/aptos-labs/aptos-core/assets/160141765/62070e5c-cfe0-406a-bf22-e94ef5567433)
![IMG_8385](https://github.com/aptos-labs/aptos-core/assets/160141765/1256675f-cf72-4a7b-bc53-6016389abfc7)
![IMG_8394](https://github.com/aptos-labs/aptos-core/assets/160141765/e9f8bab1-7be2-4915-9fd4-cee3c4254bb9)

invalid-------key error
my aptos wallet is cant send and swap
help me please

**Comment by 4taras4** [comment]
@hanho1 i have a same issue how you solve it?

**Comment by RubyEDE** [comment]
same issue here, anyone managed to solve it?

the account worked and sent transactions and now it just stopped working getting INVALID_AUTH_KEY, in code and in extension wallet

**Comment by hosseinsanjaei** [comment]
> same issue here, anyone managed to solve it?
> 
> the account worked and sent transactions and now it just stopped working getting INVALID_AUTH_KEY, in code and in extension wallet

Are the issue solved or not? I have same problem with this.anyone can help?

**Comment by hosseinsanjaei** [comment]
I have problem to send token with error invalid_auto_key,
Anyone managed to solved it?

**Comment by hosseinsanjaei** [comment]
can any one solved this?

**Comment by adeshkhari** [comment]
Hi sir

**Comment by adeshkhari** [comment]
> same issue here, anyone managed to solve it?
> 
> the account worked and sent transactions and now it just stopped working getting INVALID_AUTH_KEY, in code and in extension wallet

Hi brother

**Comment by Johnivan113** [comment]
same problem. Account was rotated without my participation. How can I fix it?
