### ISSUE TITLE
[Bug] Struct reference parameter is used in entry function

### ISSUE THREAD

**Issue by IIMP** [aptos-labs/aptos-core#5429]
# 🐛 Bug
In aptos-move/framework/aptos-framework/sources/coin.move, there are entry functions accepting struct references as parameters, like: 
```
    public entry fun freeze_coin_store<CoinType>(
        account_addr: address,
        _freeze_cap: &FreezeCapability<CoinType>,
    ) acquires CoinStore {
        let coin_store = borrow_global_mut<CoinStore<CoinType>>(account_addr);
        coin_store.frozen = true;
    }
```
Since aptos doesn't support structs in entry function parameters, I think it is a bug.

**Comment by magnum6actual** [comment]
While an entry function is often used to initiate a transaction from off-chain, they aren't restricted to that use case.  From Move documentation (https://move-language.github.io/move/functions.html):
```
Note though, an entry function can still be called by other Move functions. So while they can serve as the start of a Move program, they aren't restricted to that case
```

**Comment by IIMP** [comment]
> While an entry function is often used to initiate a transaction from off-chain, they aren't restricted to that use case. From Move documentation (https://move-language.github.io/move/functions.html):
> 
> ```
> Note though, an entry function can still be called by other Move functions. So while they can serve as the start of a Move program, they aren't restricted to that case
> ```

However, the function should not be assigned with the entry. The entry attribute is useless if nobody can initiate a transaction from off-chain with a struct parameter.

**Comment by wrwg** [comment]
This is related to https://github.com/aptos-labs/aptos-core/issues/1886. In general, we need better error messages on compilation level (instead of of runtime level) about non-allowed signatures of transactions.

**Comment by magnum6actual** [comment]
This makes sense to me, but what then is the purpose of non-public entry functions that are allowed by Move language?

**Comment by davidiw** [comment]
> This makes sense to me, but what then is the purpose of non-public entry functions that are allowed by Move language?

only callable by a txn and not by a script or another function (outside the module where it is defined)
