### ISSUE TITLE
[observability] single source of truth for grafana dashboards

### ISSUE THREAD

**Issue by rustielin** [aptos-labs/aptos-core#543]
Currently our Grafana dashboards are in a few places, and there's a mess of symlinks amongst them:
* Fullnode dashboards https://github.com/aptos-labs/aptos-core/tree/main/terraform/fullnode/aws/fullnode/files/dashboards
* Monitoring docker-compose: https://github.com/aptos-labs/aptos-core/tree/main/docker/compose/monitoring/grafana/dashboards
* Validator dashboards https://github.com/aptos-labs/aptos-core/tree/main/terraform/helm/validator/files/dashboards

We should have a single top level directory that has all the dashboards and their compressions. This can then be symlinked as necessary.
* For kubernetes workloads, this could be realized as a separate `monitoring` helm chart
* Consider modularity for the dashboards
    * Filter by `chain_name`
    * Group dashboards into folders, as some may not be relevant to certain deployments (e.g. fullnode does not need all dashboards)

**Comment by kris524** [comment]
Hello! Can I pick this task? Would I have to use Rust here? Sadly I am unfamiliar with Kubernetes, will that be an issue? What do I need to know before I start?

**Comment by rustielin** [comment]
Hey! Thanks for showing interest. To complete this task, one would need some basic familiarity with the various support ways to deploy and monitor aptos nodes, notably: binary, docker(compose), and kubernetes (via helm). All of these can be done locally. For example, you should be able to run a fullnode locally on kubernetes via minikube.

To start, essentially one would have to:
1. Move the dashboards to their new location
2. Test that the dashboards work in each of the various deployment methods. This will not likely work out of the box due to different data sources and filters necessary, so...
3. Do some modularization work such that the same dashboards work everywhere

**Comment by toanphamhd** [comment]
Thanks for showing interest. Nice word
