### ISSUE TITLE
[Move] freeze_coin_store should not be entry function

### ISSUE THREAD

**Issue by x24870** [aptos-labs/aptos-core#5430]
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/coin.move#L282
The **freeze_coin_store** function shouldn't be an entry function, scripts are not allowed to borrow resources.
The **FreezeCapability** is stored in a resource, so it should be a public function that allows other module to borrow the capability resource to use it.

**Comment by IIMP** [comment]
already described in issue#5429

**Comment by x24870** [comment]
Yeah, duplicated to issue#5429.
Will close it.

**Comment by x24870** [comment]
Yeah, duplicated to issue#5429.
Will close it.
