### ISSUE TITLE
[Feature Request] Publish aptos-sdk 0.0.3 to create.io

### ISSUE THREAD

**Issue by YusongWang** [aptos-labs/aptos-core#5446]
# 🚀 Feature Request

Publish aptos-sdk 0.0.3 to create.io PLS

## Motivation

- right now, the aptos-sdk is depend aptos-core and aptos-core depend a lot pacakge. include rockdb.
- aptos-sdk 0.0.27 not work anymore.  
- depend github sourcecode. when doing static build. what well require build rock-db, that package can't be static. also we not use rockdb. just use REST service.

**Comment by gregnazario** [comment]
The Rust SDK needs to be updated appropriately.  As such it hasn't been updated on crates.io yet.
