### ISSUE TITLE
Is there a doc for teaching how to write ERC721 NFT contract?

### ISSUE THREAD

**Issue by tmac2yt** [aptos-labs/aptos-core#5450]
## ❓ Questions and Help

I readed this tutorial, but I find it very obscure. It does not say how to distinguish ERC721 from ERC1155. Whether there is a better tutorial to refer to?This tutorial is really difficult to understand.

https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/move-examples/mint_nft

**Comment by tmac2yt** [comment]
I can only ask questions here because no one in Discard has replied to me.

Please see if my understanding is correct:
![图片](https://user-images.githubusercontent.com/36565628/199944577-bcc7e3b6-059e-41e1-9db8-e3d1e4131d15.png)
1.**token_data_id** corresponds to the tokenId in ERC721

2. The example here should correspond to ERC1155, because a token_ data_ ID can have multiple nfts


The following code is too difficult to understand. I hope someone can explain it to me:
![图片](https://user-images.githubusercontent.com/36565628/199945999-dc3faba6-7325-4fd2-b3d8-db5e289b60d9.png)

1.What's the meaning of t**oken::mutate_ token_ properties**？

2. Why is the maximum supply of collection 0?

**Comment by tmac2yt** [comment]
if you set tokendata maximum = 1, the token become a NFT. If the property_version > 0, it is also NFT. The first type NFT only has 1 token generated from the tokendata. The 2nd type of NFT might have multiple token with the same tokendata

**Comment by tmac2yt** [comment]
![图片](https://user-images.githubusercontent.com/36565628/200100535-9b4dac51-6c16-49e5-9b81-65af4a24b266.png)
1.What's the "token_mutate_config" for?
2.property_keys: vector<String>,
   property_values: vector<vector<u8>>,
   property_types: vector<String>
Is these are the metadata of this NFT like ERC721?

**Comment by 0xchloe** [comment]
maximum supply of 0 means that the supply of that token is untracked. see documentation here: https://aptos.dev/concepts/coin-and-token/aptos-token/#overview-of-nft

**Comment by 0xchloe** [comment]
in terms of `mutate_ token_ properties`, let's say you have an NFT that has a lot of printing editions, you update the `property_version` after minting every printing edition of this NFT. the tutorial we have is for generating a lot of editions from the same token data. but for most NFT, I'd imagine they'd have different token data (e.g. if you are looking at collections on NFT marketplaces, the tokens all have different names and pics). in their case they don't need to use `mutate_token_properties`

**Comment by 0xchloe** [comment]
thank you for creating a github ticket - it's easier for us to keep track of instead of discord. pls let us know if you have any other questions : )

**Comment by tmac2yt** [comment]
Thank you for your patient explanation. I have understood these problems, thx @0xchloe
