### ISSUE TITLE
Make it possible to view API spec with sidebar layout

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5459]
Currently the API spec viewer in aptos.dev (pending https://github.com/aptos-labs/aptos-core/pull/5345 landing) uses stacked view. Stacked view has two issues:
1. It is harder to navigate and looks a bit busier.
2. You can't link directly individual sections like you can with the sidebar view

It'd be nice to be able to hit a toggle and show it in sidebar view. In this case, it'd be ideal to hide the top level nav sidebar and make it full the entire width of the page.

One way to hide the sidebar easily is by just removing the doc from the sidebars and have it only linkable from the top nav bar. This doesn't make the content fill the whole width though.

**Comment by banool** [comment]
More context: https://aptos-org.slack.com/archives/C03EG004E56/p1667580759259119.

**Comment by clay-aptos** [comment]
Hi @banool , what remains here? Thanks!

**Comment by banool** [comment]
Still not done unfortunately, but this is definitely just a wishlist item.

**Comment by davidiw** [comment]
I think this is resolved.

**Comment by banool** [comment]
It's not but it's also not that important, so we can leave it closed. The ask here is to make it possible to view the API spec how it looks here, where there is a nav on the side: https://fullnode.devnet.aptoslabs.com/v1/spec#/.
