### ISSUE TITLE
[APT-3] > aptos-core\aptos-move\move-examples\mint_nft

### ISSUE THREAD

**Issue by tmac2yt** [aptos-labs/aptos-core#5474]
> aptos-core\aptos-move\move-examples\mint_nft

HI,thx for your fast reply.
But I tried it in the “**aptos-core\aptos-move\move-examples\mint_nft directory**”,I got the same issue:
![图片](https://user-images.githubusercontent.com/36565628/199917709-b18cc279-b9e3-4737-adeb-9288fd79be2f.png)

_Originally posted by @tmac2yt in https://github.com/aptos-labs/aptos-core/issues/5357#issuecomment-1303071375_
      

<sub>[APT-3](https://linear.app/aptoslabs/issue/APT-3/aptos-core\aptos-move\move-examples\mint-nft)</sub>

**Comment by gregnazario** [comment]
Looks like you don't have CLang installed.

You can also use the prebuilt CLI https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.1, though it may still not work if you don't have CLang installed.

And I see you're using Windows, so you may need to install the dependencies listed here: https://aptos.dev/cli-tools/build-aptos-cli#windows

**Comment by tmac2yt** [comment]
> Looks like you don't have CLang installed.
> 
> You can also use the prebuilt CLI https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.1, though it may still not work if you don't have CLang installed.
> 
> And I see you're using Windows, so you may need to install the dependencies listed here: https://aptos.dev/cli-tools/build-aptos-cli#windows

Thx,I will try when I'm free.I will back.

**Comment by tmac2yt** [comment]
> Looks like you don't have CLang installed.
> 
> You can also use the prebuilt CLI https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v1.0.1, though it may still not work if you don't have CLang installed.
> 
> And I see you're using Windows, so you may need to install the dependencies listed here: https://aptos.dev/cli-tools/build-aptos-cli#windows

Hi,I install LLVM(include CLang),and this issue was fixed.
But I faced another issue,pls look at this:
![图片](https://user-images.githubusercontent.com/36565628/201060972-1f063272-80f0-4874-a4fb-7cc50c5cab07.png)

It shows "thread 'main' has overflowed its stack",do you know why? @ @gregnazario

**Comment by gregnazario** [comment]
Ah, sorry I missed this.  It's a common issue with [Windows](https://users.rust-lang.org/t/stack-overflow-when-compiling-on-windows-10/50818/9) and the Move compiler since it has a very large stack. 

Here's an example we actually raise the stack size https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/src/aptos.rs#L140-L162

I will try to fix it and test it on a Windows machine.  Most of us don't develop in Windows so we don't realize the issue

**Comment by gregnazario** [comment]
With the newer version of this tutorial, this no longer happens:
```
PS C:\Users\Administrator\Desktop\aptos-core> C:\Users\Administrator\Desktop\aptos move create-resource-account-and-publish-package --address-name mint_nft  --package-dir .\aptos-move\move-examples\mint_nft\4-Getting-Production-Ready\ --named-addresses source_addr=default --seed 4
Compiling, may take a little while to download git dependencies...
←[1;32mINCLUDING DEPENDENCY←[0m AptosFramework
←[1;32mINCLUDING DEPENDENCY←[0m AptosStdlib
←[1;32mINCLUDING DEPENDENCY←[0m AptosToken
←[1;32mINCLUDING DEPENDENCY←[0m MoveStdlib
←[1;32mBUILDING←[0m Examples
Do you want to publish this package under the resource account's address c5ec3954e1c09f14b91515cedbbff597fbd98d853edf153aa2af93cf15b7fabc? [yes/no] >
yes
package size 9848 bytes
Do you want to submit a transaction for a range of [1836100 - 2754100] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
  "Result": "Success"
}
PS C:\Users\Administrator\Desktop\aptos-core> C:\Users\Administrator\Desktop\aptos move create-resource-account-and-publish-package --address-name mint_nft  --package-dir .\aptos-move\move-examples\mint_nft\3-Adding-Admin\ --named-addresses source_addr=default --seed 3
Compiling, may take a little while to download git dependencies...
←[1;32mINCLUDING DEPENDENCY←[0m AptosFramework
←[1;32mINCLUDING DEPENDENCY←[0m AptosStdlib
←[1;32mINCLUDING DEPENDENCY←[0m AptosToken
←[1;32mINCLUDING DEPENDENCY←[0m MoveStdlib
←[1;32mBUILDING←[0m Examples
Do you want to publish this package under the resource account's address d587900fb243bb58ef257c13f19e395e85ea5698a4adc8ddd41103b6a9f5f95f? [yes/no] >
yes
package size 6688 bytes
Do you want to submit a transaction for a range of [1598100 - 2397100] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
  "Result": "Success"
}
```
