### ISSUE TITLE
[APT-20] [Bug] Remove debug information for Release mode builds

### ISSUE THREAD

**Issue by jyap808** [aptos-labs/aptos-core#5491]
### Description

Release mode builds have debug information explicitly turned On (set to True).

This results in huge compiled binaries. For example, aptos-node is over 1.5 GB when built.

The [documentation says to build with —release](https://github.com/aptos-labs/aptos-core/blob/0c3bc9982d8409dbb68e5e5bf5491c3152d8810e/developer-docs-site/docs/cli-tools/build-from-source.md?plain=1#L83) which is the default Release build option for Rust projects. I.e. a “release” build without Debug information should be commonly what people want when they build with that flag.

Perhaps Aptos developers can create another build profile if they want a build with debug information?

Setting debug to default False:
```
$ export CARGO_PROFILE_RELEASE_DEBUG=false
$ cargo build --locked --profile=release -p aptos-node
```

Compiled binary is a manageable 74M:
```
$ ls -lh target/release/aptos-node
-rwxr-xr-x 2 julian julian 74M Nov  7 13:37 target/release/aptos-node
```

Associated (Closed) PR #5488 

<sub>[APT-20](https://linear.app/aptoslabs/issue/APT-20/[bug]-remove-debug-information-for-release-mode-builds)</sub>

**Comment by jyap808** [comment]
Not stale

**Comment by wrwg** [comment]
@zekun000 is this something the blockchain team is planning to do? Why do we have debug info on for release builds?

**Comment by zekun000** [comment]
this is not something we plan to do for our build, we need debug info for profiling/debugging etc but we can have another build profile for community to remove it

**Comment by lbmeiyi** [comment]
@zekun000 can we close this ticket?

**Comment by zekun000** [comment]
as said we don't want to remove the debug for release build, but open to have a different build profile that strips out the debug info. we already do that for the CLI build
