### ISSUE TITLE
[BLK-201] crates/aptos-network-checker is missing some feature declarations

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#5504]
crates/aptos-network-checker is missing some feature declarations: [https://github.com/aptos-labs/aptos-core/actions/runs/3418322399/jobs/5690474663](https://github.com/aptos-labs/aptos-core/actions/runs/3418322399/jobs/5690474663) cc <@U03F08PRCQ0>

[Slack Message](https://aptos-org.slack.com/archives/C03F71PU3B5/p1667903414066559?thread_ts=1667903414.066559&cid=C03F71PU3B5)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Markuze** [comment]
Dup of #5560
