### ISSUE TITLE
[RFE]  Rewrite Life of a Transaction

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5519]
# 🐛 RFE

@davidiw indicates the following page is old and needs to be rewritten from the perspective of the user:
https://aptos.dev/guides/basics-life-of-txn

David says our sources of truth are @CapCap , @gregnazario and @bchocho . Folks, let's make some time for this when you have cycles. All, raise the priority as you desire.

**Comment by clay-aptos** [comment]
Per David, we should also define the goal for the page itself. What are we trying to teach? To whom? We should target app developers.

**Comment by davidiw** [comment]
I think it is in a bit better state now :)

**Comment by clay-aptos** [comment]
> I think it is in a bit better state now :)

Thanks to you, @davidiw . Thank you!
