### ISSUE TITLE
[Bug] Cached state view and asynchronous mempool notifications

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#553]
We previously added a cached state view to mempool (https://github.com/diem/diem/pull/9722) so that we'll only reload the state view after commit notifications (and not after each transaction). However, state sync v2 only notifies mempool of a commit asynchronously, so it's possible that there's a time gap between when storage is updated and mempool is notified, meaning that mempool won't have the latest view. As a result, some transactions might fail VM validation until mempool is notified.

For now, I've updated state sync v2 to notify mempool asynchronously, but, we might want to identify a better solution going forward.

**Comment by JoshLind** [comment]
'cc @zekun000 -- this is something that I'll tackle tomorrow :D Annoying that we're always running into this :P

**Comment by zekun000** [comment]
re-validation on failed transaction seems hacky though, it also opens the gate for DDoS by sending many invalid txns (although refresh the view shouldn't be too expensive). maybe we should have a better way of syncing the state view instead of using notifications cc @msmouse

**Comment by msmouse** [comment]
From this I don't quiet understand the reason why the notification is asynchronous (to the extend that creates a meaningful "gap"). Is it possible to special case this notification so mempool gets the information "synchronously" as before (I assume)?

**Comment by zekun000** [comment]
@msmouse before mempool starts a new state view for each transaction, that's how it gets the information "synchronously"

**Comment by msmouse** [comment]
I mean, what's the difference between state sync v1 and v2? your cache worked with v1, right?

**Comment by JoshLind** [comment]
@zekun000:
> re-validation on failed transaction seems hacky though, it also opens the gate for DDoS by sending many invalid txns (although refresh the view shouldn't be too expensive).

Yeah, it's not ideal, but I guess it depends on which operation is more expensive: reloading the state view or verifying the transactions?

@alden:
> I mean, what's the difference between state sync v1 and v2? your cache worked with v1, right?

Yeah, this is the issue: state sync v1 doesn't notify mempool asynchronously. When it gets a commit notification it will notify mempool immediately (on the critical path). With state sync v2, however, the commit is asynchronous. The reason for this is more code structure than anything.

> Is it possible to special case this notification so mempool gets the information "synchronously" as before (I assume)?

Let me get back to you and see how difficult this will be. There's no reason it can't, it's just that the system is different now: storage synchronizer notifies driver of commit, which notifies event subscription service and mempool :) So, there's more layers to refactor if we need to do this 😄

**Comment by gregnazario** [comment]
This cleaned up @JoshLind ?
