### ISSUE TITLE
[APT-22] [Feature Request] Petra Wallet support add custom network programatically

### ISSUE THREAD

**Issue by nodereal-keeper** [aptos-labs/aptos-core#5532]
# 🚀 Feature Request

## Motivation

We wish to let [MegaNode](https://nodereal.io/meganode) users add their api endpoint as node URL for new network programmatically in Petra

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/90318075/200993743-ead1bde6-3773-4320-b8e8-c90aabc0e03d.png)

similar function like metamask https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain

## Additional context

<sub>[APT-22](https://linear.app/aptoslabs/issue/APT-22/[feature-request]-petra-wallet-support-add-custom-network)</sub>

**Comment by gregnazario** [comment]
@kent-white maybe this belongs in https://github.com/aptos-labs/petra-wallet
