### ISSUE TITLE
[APT-15] [Feature Request] Allow validator operator to request a percentage <100% of the Unrequested Commission amount

### ISSUE THREAD

**Issue by ericjohncarlson** [aptos-labs/aptos-core#5540]
# 🚀 Feature Request

Today, the `request-commission` command will request 100% of the "unrequested commission" that is available to the operator.  Many operators would be interested in allowing a percentage of this amount to stay in the pool to help secure the network, earn rewards and hold until a later date.

## Motivation

To allow validator operators to better manage incoming commission amounts.  To allow operators to help secure the network and continue to earn rewards from those staked tokens.

## Pitch

The feature request is to add a `--percentage` or `--amount` or similar flag to allow the operator to select the raw request amount in APT or percentage of the "unrequested commission" amount as a input to the request.  At the unlock time, only this amount of APT would be ready for withdraw, while the remaining amount would continue forward as if this command was not called.

## Additional context

Discussed by node operators.  Tagging @wintertoro per request.

<sub>[APT-15](https://linear.app/aptoslabs/issue/APT-15/[feature-request]-allow-validator-operator-to-request-a-percentage)</sub>

**Comment by movekevin** [comment]
This makes sense and is an item on our Q1 roadmap
