### ISSUE TITLE
Why do we need the signer of the receiver while sending to a user who has opted for direct transfer? 

### ISSUE THREAD

**Issue by vivekascoder** [aptos-labs/aptos-core#5545]
## ❓ Questions and Help
Hello, don't you think it'll be better to allow direct transfer to some address without needing the receiver's signer if the receiver has opted for direct transfer?

To protect the user from receiving an unwanted NFT we've claimed and offered but if he's opting for direct transfer why do we need the signer of the receiver?

**Comment by davidiw** [comment]
This is the current case: https://github.com/aptos-labs/aptos-core/blob/5444f5be076bd2add24de85b61b978ce35fe9deb/aptos-move/framework/aptos-token/sources/token.move#L476

There's also the `direct_transfer` where the user did not opt-in, in which case you do need the receiver signer. Documentation is forthcoming.

**Comment by vivekascoder** [comment]
Shit, how can I forget this function, thanks.

**Comment by davidiw** [comment]
I have an idea why.... when every function looks similar it is hard to disambiguate ;)
