### ISSUE TITLE
[Bug] Get Account Transactions API returns same timestamp for all txn.

### ISSUE THREAD

**Issue by xorgal** [aptos-labs/aptos-core#555]
# 🐛 Bug
It looks like there is an issue in Get Account Transactions API. Let's say address has a history of several executed transactions and API returns same timestamp for all of them. It's equal to first transaction timestamp. 

And here is [Example:](https://fullnode.devnet.aptoslabs.com/accounts/0x429781d9a97c054e259ca466405364d5d7262ba090ccbf7aeab6f6eeec5600a9/transactions)
```
"timestamp": "1650016354838210"
```

**Comment by xorgal** [comment]
Also, it would be great to update 0x1::TestCoin::TransferEvents with time when event was actually registered in blockchain :)

**Comment by davidiw** [comment]
We just added version to event, it will be available in the next release. Given a version, one can look up the time.
