### ISSUE TITLE
Provide signature Library

### ISSUE THREAD

**Issue by ratneshpatil-rp** [aptos-labs/aptos-core#5550]
Hi team,

can you provide signating function and also keygen and signature verification

**Comment by alinush** [comment]
If you open an issue, please state the issue clearly.

1. For what types of signatures? Ed25519, BLS signatures over BLS12-381 curves?
2. Where do you want to generate signatures? In Rust, in Move?
3. Generally, what's your use case? What are you trying to do and where are you failing?

**Comment by ratneshpatil-rp** [comment]
Hi @alinush ,

1. we need Ed25519 signature, which takes input as message, privatekey and gives output as signed message
2. Actually we want to set-up this in nodejs project.
3. so we are doing Custody verification. there is user signs message and then we verify that by lib verify signature.
 is the same library available for Kava.

**Comment by alinush** [comment]
Sorry, I do not understand how we can help you. There are plenty of Ed25519 signature library, including for nodejs: https://www.npmjs.com/package/ed25519

I will close this issue for now, since this does not appear as an issue on our end.
