### ISSUE TITLE
[APT-16] Should change the token URI when mint_nft function called

### ISSUE THREAD

**Issue by y0unghe** [aptos-labs/aptos-core#5551]
It seems this `mutate_token_properties` function won't set the correct token URI when a new token was minted. Each token should have different Metadata URI like `https://arweave.net/bLlRFRTUioMMbT7eIqxehNvfrjwtK_Dujk6PIA0HU_4/1.json` for `token 1` and `https://arweave.net/bLlRFRTUioMMbT7eIqxehNvfrjwtK_Dujk6PIA0HU_4/2.json` for `token 2`.  

It would be great to have this function. 

<sub>[APT-16](https://linear.app/aptoslabs/issue/APT-16/should-change-the-token-uri-when-mint-nft-function-called)</sub>

**Comment by kachurun** [comment]
If you want different metadata for different NFT (like ERC721) you need to create own token_data_id for every NFT. For example, if you want to create an ERC721 collection of 8000 NTF you have to create 8000 token_data_id with unique name, uri or whatever you want

**Comment by davidiw** [comment]
In Aptos, each token has a distinct url, you need to set it manually. It is worth noting that in tokenv2, you can implement your own URL function, if you want to save space.
