### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Dvnch** [aptos-labs/aptos-core#556]
I use some dummy return values in the AptosTestAdapter to bypass the error as the return values are not used now. However, we should figure out how to implement AptosTestAdapter to solve the conflict in the fist place.

         //TODO: replace this dummy value with actual txn return value
        let a = SerializedReturnValues {
            mutable_reference_outputs: vec![(0, vec![0], MoveTypeLayout::U8)],
            return_values: vec![(vec![0], MoveTypeLayout::U8)],
        };

        Ok((output, a))

**Comment by kris524** [comment]
Hello, is this a good first issue? I would like to help with it if that's the case. Is there any additional info I might need?

**Comment by davidiw** [comment]
I don't understand this.
