### ISSUE TITLE
[Bug][Indexer] `collection_data_id_hash` in table current_collection_datas inconsistent with that in other token tables

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#5570]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
The `collection_data_id_hash` of creator_address `0x043ec2cb158e3569842d537740fd53403e992b9e7349cc5d3dfaa5aff8faaef2` and collection_name `Bruh Bears` is `da59e5f610419f274a20341fb198bf98415712de11a4468cfd45cbe495600c2a` in `current_collection_datas` table

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/33241113/201844723-1e90c946-cda9-42dd-8051-f9ebe5eedfd1.png">

However, the `collection_data_id_hash` of same creator_address and collection_name in other token tables(e.g. `token_activities`) is `f35f523ef93b63db9dc9f7ac5766534b3b10aaba1cde38c821d31ad45008b9bd`, which is inconsistent

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/33241113/201844569-6ba18f24-4d72-4c72-a794-d13bcd57558b.png">

## Expected Behavior

`collection_data_id_hash` of the same collection  should be the same value in all token tables

## System information

**Please complete the following information:**
-  code version:  https://github.com/aptos-labs/aptos-core/commit/d2eece2e1d232c2a8bd8cce532cb25ac16981639
- 
-

**Comment by nolanxyg** [comment]
I opened a PR to fix: https://github.com/aptos-labs/aptos-core/pull/5571
PTAL

**Comment by bowenyang007** [comment]
Fix looks good. For prosperity this will need a db backfill otherwise old data is still bad.

**Comment by gregnazario** [comment]
Closing out, please re-open / comment if there's still an issue
