### ISSUE TITLE
[API] Getting account resources via TS SDK slow

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5589]
User report that now that you can get more than 10k resources (which uses multiple calls now), it is much slower.

**Report from @guijunchen**:

After we upgraded the node, we used this interface to get data, and found that the request speed was very slow, it took 13 seconds

```
sdk:
poolInfosRaw = (await this.aptosClient.getAccountResources("0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948")

log show call time
book@BookdeMBP test % node ./test1.js
[2022-11-16T10:38:57.285] [DEBUG] aptos - get liquid swap pool start
[2022-11-16T10:39:10.675] [INFO] aptos - resource len: 18442
[2022-11-16T10:39:10.721] [DEBUG] aptos - get liquid swap pool end
```

Originally from https://github.com/aptos-labs/aptos-core/issues/5298.

**Comment by banool** [comment]
https://github.com/aptos-labs/aptos-core/pull/5590

**Comment by guijunchen** [comment]
This is not a sdk problem, it is that the processing node is too slow to return more than 10k data at a time

**Comment by guijunchen** [comment]
#precondition
this address 0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948 has resource 18442 lel

## case 1  without limit， it took  about 13 seconds
about 13 seconds
curl --request GET \
  --url https://aptos.xx**.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources \
  --header 'Content-Type: application/json'


##case 2: limit=10000, it took about 9 seconds
curl --request GET \
  --url 'https://aptos.***.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=10000' \
  --header 'Content-Type: application/json'

##case 3: limit=6000, it took about 4 seconds
curl --request GET \
  --url 'https://aptos.mytokenpocket.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=6000' \
  --header 'Content-Type: application/json'

**Comment by guijunchen** [comment]
#precondition
this address 0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948 has resource 18442 lel

case 1 without limit， it took about 13 seconds
about 13 seconds
curl --request GET
--url [https://aptos.xx**.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources](https://aptos.xx%2A%2A.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources)
--header 'Content-Type: application/json'

##case 2: limit=10000, it took about 9 seconds
curl --request GET
--url '[https://aptos.***.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=10000](https://aptos.%2A%2A%2A.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=10000)'
--header 'Content-Type: application/json'

##case 3: limit=6000, it took about 4 seconds
curl --request GET
--url '[https://aptos.****.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=6000](https://aptos.%2A%2A%2A%2A.vip/v1/accounts/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resources?limit=6000)'
--header 'Content-Type: application/json'

**Comment by guijunchen** [comment]
The resource obtaining interface should support obtaining a certain type of resource under the same address, or obtaining a resource by regular matching, or obtaining a resource with a specified prefix, or obtaining the corresponding resource by passing a different type type id.

**Comment by banool** [comment]
This is awesome feedback, we're looking to make our API more expressive.

> support obtaining a certain type of resource under the same address
By this, do you for example mean requesting all resources that use the same parent type regardless of the type used in the generic? e.g. `Coin<AptosCoin>`, `Coin<OtherCoin>`, etc. If not, could you explain what you mean? A single account can only have one of a resource.

**Comment by banool** [comment]
Thanks for the detailed research, it does indeed seem to be mostly a factor of request size -> time spent by the server reading information from storage.

@lightmark @msmouse is this performance expected?

**Comment by guijunchen** [comment]
> This is awesome feedback, we're looking to make our API more expressive.
> 
> > support obtaining a certain type of resource under the same address
> 
> By this, do you for example mean requesting all resources that use the same parent type regardless of the type used in the generic? e.g. `Coin<AptosCoin>`, `Coin<OtherCoin>`, etc. If not, could you explain what you mean? A single account can only have one of a resource.

From a business point of view, I need to get the data I need instead of getting all the data, which will cause the request to be too slow

**Comment by banool** [comment]
Sure I understand the business need, I'm asking about what kind of query you mean. I'm not sure how your first request is different from what we already offer here: https://fullnode.mainnet.aptoslabs.com/v1/spec#/operations/get_account_resource.

**Comment by banool** [comment]
I see so you want a batch request, got it.

**Comment by lightmark** [comment]
I replied in the wechat. Our node api is not a database so the prefix scan + filtering + deserialization is sort of slow.
MultiGet can be supported.

**Comment by guijunchen** [comment]
> I replied in the wechat. Our node api is not a database so the prefix scan + filtering + deserialization is sort of slow. MultiGet can be supported.

yes, i see
aptos labs team Plan to support multiget?  
Approximately when the planned support is expected, if it is too slow we may need to modify the custom node ourselves

**Comment by guijunchen** [comment]
Currently the TS SDK sends requests resources for 1000 items at a time， It may be better to modify it to requests 2000 records at a time

**Comment by banool** [comment]
We have landed a change to make it get 9999 items at a time.

As for if / when we'll add multiget support, I don't expect we'll do it in the next month at least, we would need to meet and discuss prioritization. If you indeed plan to add this yourselves, we'd really love a PR! Please feel free to suggest your changes here and we can discuss them and if they sound good, we'll review a PR.
