### ISSUE TITLE
Move Prover failed with paincked

### ISSUE THREAD

**Issue by Alivers** [aptos-labs/aptos-core#5612]
### Please note that this issue tracker is not a help form and this issue will be closed.
I was running `aptos move prove --package-dir [mydir]` and got the panicked error: 
```
$ aptos move prove --package-dir packages/module
thread 'tokio-runtime-worker' panicked at 'callee borrow annotation', /Users/runner/.cargo/git/checkouts/move-0639dd674f581c30/6a32284/language/move-prover/bytecode/src/borrow_analysis.rs:603:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
{
  "Error": "Unexpected error: task 11 panicked"
}
```
version info:
- aptos cli:  v1.0.0
- os: macos 13 ventura

**Comment by Alivers** [comment]
I just tried the move cli. `move prove ` worked correctly.

**Comment by junkil-park** [comment]
@Alivers , thank you for reporting this. Move Prover evolves in the move repo first (where the move cli is), and then the updates are reflected in the aptos repo regularly. Is there a still issue? If so, is the problematic Move package available online somewhere?

**Comment by wrwg** [comment]
Closing, feel free to reopen if the problem still persists.
