### ISSUE TITLE
How to check if a function was called by EOA Account or by Another Module.

### ISSUE THREAD

**Issue by TonyProMax** [aptos-labs/aptos-core#5632]
## ❓ Questions and Help
I would like to check in the contract to require the function called from a user. Not from another modules.
This required for some of onchain random could be pre-computed in the same transaction or script.

With script, I can check that from `transaction_context::get_script_hash()`. But if that function was called from module, I didn't know is there any method.
Alternative to EVM is, `require(msg.sender == tx.origin)` => We can make sure that a function was call from an EOA.

Thanks,

**Comment by geekflyer** [comment]
I think you can define a function as:

```
entry fun do_stuff(foo: String)  {}
```
which will make it an entry function which can not be called from other modules.

**Comment by TonyProMax** [comment]
@geekflyer  If we didn't declare public then we didn't saw that on ABI and we couldn't define that for EOA to interact on that.

**Comment by TonyProMax** [comment]
I can solve this by declare `public(friend)`
