### ISSUE TITLE
[Feature Request] Add groth16 to Aptos native function

### ISSUE THREAD

**Issue by VegeBun-csj** [aptos-labs/aptos-core#5646]
# 🚀 Feature Request

Add `groth16` zkp algorithm to Aptos native function

## Motivation
ZKP is a very important infrastructure. I have noticed that [Sui has added groth16](https://github.com/MystenLabs/sui/commit/630a14b0f4e58f980d46aa09a5d236fc3066448b). Does aptos have this idea?

## Pitch
May i push pr to add bellman library to the native function of Aptos?

**Comment by zjma** [comment]
@VegeBun-csj that's definitely in our roadmap. We are gonna start working on it but if you have PR ready feel free to send it out!

**Comment by zjma** [comment]
> > @VegeBun-csj that's definitely in our roadmap. We are gonna start working on it but if you have PR ready feel free to send it out!
> 
> OK，thanks！So, I'm ready and i have noticed that there are some gas parameters in native method. Do we need to discuss in advance?

I guess the gas parameter discussion can happen during the review process. Adding @alinush @vgao1996 who will have more insights.

**Comment by alinush** [comment]
Hey folks, this is indeed part of our roadmap. 

A 1st milestone before adding Groth16 (or any other pairing-based SNARK) will be to add support for pairing-friendly elliptic curves (e.g., BLS12-381) in Move. Once that's done, we will implement a generic Groth16 module that can verify proofs over any curve we have support for.

@VegeBun-csj, appreciate your excitement but please don't submit a PR for this, since we need to complete the 1st milestone.

**Comment by VegeBun-csj** [comment]
@alinush OK,thanks, i understand. 
`add support for pairing-friendly elliptic curves (e.g., BLS12-381) in Move` which means aptos will use `bls curve` in Move to implement groth16 in Move? Why not use the existing curve implementation to serve as native method implementation, such as `arkwork_ Bls12381` or `bls12_381` of bellman. Actually, we can take them directly or modify them slightly, because they are very mature.

**Comment by alinush** [comment]
> Why not use the existing curve implementation to serve as native method implementation?

That's exactly what we will do. The choice of library remains to be decided. My point above was that we will try to have a generic elliptic curve Move module that can be easily extended with new curves. Then, we can implement Groth16 and any other SNARK on top of that module. This will allow more flexibility for developers in picking not just their favorite SNARK scheme but also their favorite elliptic curve.

**Comment by VegeBun-csj** [comment]
> > Why not use the existing curve implementation to serve as native method implementation?
> 
> That's exactly what we will do. The choice of library remains to be decided. My point above was that we will try to have a generic elliptic curve Move module that can be easily extended with new curves. Then, we can implement Groth16 and any other SNARK on top of that module. This will allow more flexibility for developers in picking not just their favorite SNARK scheme but also their favorite elliptic curve.

that's great, thank you for your answer!

**Comment by alinush** [comment]
Closing, as this is in the works.

**Comment by alinush** [comment]
Solved by #6550
