### ISSUE TITLE
[Feature Request] TypeScript SDK: Allow account address in coinClient.transfer -> to method

### ISSUE THREAD

**Issue by kachurun** [aptos-labs/aptos-core#5648]
# 🚀 Feature Request

Just looks the code what I need to write because I dont have private keys for addresses for who I send the coins
```
...
await coinClient.transfer(owner, { address: () => module.address } as AptosAccount, 100000000);
...
```

I wanna do just:
```
...
await coinClient.transfer(owner, module.address, 100000000);
...
```

**Comment by banool** [comment]
Good call, we should do this.

**Comment by banool** [comment]
We should address in the same stroke as https://github.com/aptos-labs/aptos-core/issues/5720, we might indeed need a different function.

**Comment by banool** [comment]
Implemented, we'll release a new TS SDK with this change soon.
