### ISSUE TITLE
[Bug] Cannot use aptos-node as dependencie

### ISSUE THREAD

**Issue by pu0238** [aptos-labs/aptos-core#5655]
# 🐛 Bug

## To reproduce

add:
aptos-node = { git = "https://github.com/aptos-labs/aptos-core", package = "aptos-node"}
do rust dependencies

**Code snippet to reproduce**
```rust
[dependencies]
aptos-node = { git = "https://github.com/aptos-labs/aptos-core", package = "aptos-node"}
```

**Stack trace/error message**
```
error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
  --> /home/pu0238/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/23d258d/storage/backup/backup-service/src/lib.rs:28:10
   |
28 |         .disable_lifo_slot()
   |          ^^^^^^^^^^^^^^^^^ private field, not a method

For more information about this error, try `rustc --explain E0599`.
error: could not compile `backup-service` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope   --> /home/pu0238/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/23d258d/mempool/src/shared_mempool/runtime.rs:114:10
    |
114 |         .disable_lifo_slot()
    |          ^^^^^^^^^^^^^^^^^ private field, not a method

error: could not compile `aptos-mempool` due to previous error
```
## System information

**Please complete the following information:**
- rust 1.65.0
- ubuntu 20.04

**Comment by JoshLind** [comment]
Can you retry with the latest version of main? It looks like `tokio` is not compiling on your machine with the correct feature to enable this code.

**Comment by pu0238** [comment]
O with branch can i find latest mainnet?

**Comment by JoshLind** [comment]
`main` branch will be compatible 😄

**Comment by pu0238** [comment]
I set branch to main as yoy may see here:
aptos-node = { git = "https://github.com/aptos-labs/aptos-core", package = "aptos-node", branch="main"}

On main got only one one error insted of two:

error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
   --> /home/pu0238/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/91824bc/mempool/src/shared_mempool/runtime.rs:114:10
    |
114 |         .disable_lifo_slot()
    |          ^^^^^^^^^^^^^^^^^ private field, not a method

For more information about this error, try `rustc --explain E0599`.

**Comment by JoshLind** [comment]
Thanks for following up. The issue is that `aptos-node` requires `tokio-unstable`, so you'll need to add this to your config file if you want to depend on it. FWIW, we're still working on making our code easier to depend on.

```
[build]
rustflags = ["--cfg", "tokio_unstable"]
```

**Comment by pu0238** [comment]
on my Cargo.toml: 
[build]
rustflags = ["--cfg", "tokio_unstable"]
[dependencies]
aptos-node = { git = "https://github.com/aptos-labs/aptos-core", package = "aptos-node", branch="main"}

sitill got sames errors as abow

**Comment by davidiw** [comment]
Closing out as potentially stale, but can you give more details. Is this the entirety of your cargo.toml? What is your os?

**Comment by ivanfong01** [comment]
> on my Cargo.toml: [build] rustflags = ["--cfg", "tokio_unstable"] [dependencies] aptos-node = { git = "https://github.com/aptos-labs/aptos-core", package = "aptos-node", branch="main"}
> 
> sitill got sames errors as abow

you can use add RUSTFLAGS="--cfg tokio_unstable" before cargo build


for example:
RUSTFLAGS="--cfg tokio_unstable" cargo build -p aptos-node --release
