### ISSUE TITLE
[Bug] Transaction timestamp returned from the indexer is ISO8601 UTC but does not have 'Z' suffix

### ISSUE THREAD

**Issue by leeric92** [aptos-labs/aptos-core#5656]
# 🐛 Bug

transaction timestamp returned from the indexer is ISO8601 UTC values but does not have 'Z' suffix at the end. This makes it impossible to parse in the FE and convert from UTC -> local time

## To reproduce

query a list of pending offer/claim for a token using from/to address or token id hash
observe the transaction timestamp in any of the offer/claim transaction does not have the Z suffix

## Expected Behavior

the transaction timestamp should have Z suffix at the end so the FE can parse and convert from UTC -> local time

## Additional context

https://aptos-org.slack.com/archives/C036V52D9U4/p1668994968110669

**Comment by CapCap** [comment]
You can use strparse or equivalent, no?

**Comment by gregnazario** [comment]
@leeric92 could you add a title to the issue as well

**Comment by leeric92** [comment]
done
