### ISSUE TITLE
[Bug] Make resource account doc not seem NFT specific

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5661]
Currently the docs here read like you need to use this mint_nft module to use resource accounts: https://aptos.dev/guides/resource-accounts. Unless I'm mistaken, you don't actually need that module to use resource accounts, the docs just refer to it for an example.

**Comment by clay-aptos** [comment]
I'm asking our sources @0xchloe and @movekevin to take a look. Thanks, Daniel!

**Comment by 0xchloe** [comment]
ah yeah daniel is right, we don't need the module to use a resource account. it's just an example. currently an easy way to set up a resource account is by 
1. using CLI: `aptos account create-resource-account` creates a resource account, and `aptos move create-resource-account-and-publish-package` creates a resource account and publishes the specified package under the resource account's adddress.
2. writing custom smart contracts code - in `resource_account.move` module, developers can find resource account creation functions like `create_resource_account`, `create_resource_account_and_fund`, and `create_resource_account_and_publish_package`. developers can then call those functions to create resource accounts in their smart contracts.

**Comment by clay-aptos** [comment]
> ah yeah daniel is right, we don't need the `mint_nft` module to use a resource account. it's just an example. currently an easy way to set up a resource account is by
> 
> 1. using CLI: `aptos account create-resource-account` creates a resource account, and `aptos move create-resource-account-and-publish-package` creates a resource account and publishes the specified package under the resource account's adddress.
> 2. writing custom smart contracts code: in `resource_account.move` module, developers can find resource account creation functions like `create_resource_account`, `create_resource_account_and_fund`, and `create_resource_account_and_publish_package`. developers can then call those functions to create resource accounts in their smart contracts.

Let me try and rewrite this page and use much of the existing text as a more complex example for NFTs.

**Comment by clay-aptos** [comment]
@banool please see:
https://github.com/aptos-labs/aptos-core/pull/5805
