### ISSUE TITLE
[Bug] Mention `LINKER_ERROR` in "Handle Errors in Aptos"

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5663]
https://aptos.dev/guides/handle-aptos-errors/. Either that or find a better home for it, but we should have something, since this is a common and confusing error.

**Comment by banool** [comment]
Ideally it also explains everything that could cause the error and how to fix it.

**Comment by 0xbe1** [comment]
@banool feel free to take a look #5702

**Comment by banool** [comment]
Awesome thanks!
