### ISSUE TITLE
[BLK-204] [CLI] aptos move test doesn't run tests when there is warning

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#5671]
Currently `aptos move test` doesn't run tests when there is a compiler *warning*, such as an unused import.

I find it surprising that it does so for a warning (I think rust and most common compilers do so - except for maybe golang). Can we change it so that it still runs the tests regardless of these warnings? The reason is that sometimes during development one temporarily comments out some code which makes a certain import unused but shouldn't prevent the tests from running. It probably should still exit with the same exit code as right now but it would be helpful if it would run the tests regardless.

addtl context: https://aptos-org.slack.com/archives/C036X27DZNG/p1669022983703909

> From [SyncLinear.com](https://synclinear.com)

**Comment by gregnazario** [comment]
Can you please provide an example

**Comment by vivekascoder** [comment]
I think this issue still exists.

**Comment by vivekascoder** [comment]
I sent a PR for it. #6190 6190

**Comment by rahxephon89** [comment]
Close the issue because #6190 is landed.
