### ISSUE TITLE
[BLK-205] [Docs] Resource account restrictions section is confusing

### ISSUE THREAD

**Issue by geekflyer** [aptos-labs/aptos-core#5672]
This section [https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/guides/resource-accounts.md#restrictions](https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/guides/resource-accounts.md#restrictions) about resource accounts is confusing. Needs to be rewritten/clarified what this means.

[https://aptos-org.slack.com/archives/C036X27DZNG/p1669018188094459](https://aptos-org.slack.com/archives/C036X27DZNG/p1669018188094459)

> From [SyncLinear.com](https://synclinear.com)

**Comment by clay-aptos** [comment]
@movekevin, can you help here? Thanks!

**Comment by clay-aptos** [comment]
Trying to address this in:
https://github.com/aptos-labs/aptos-core/pull/5805
