### ISSUE TITLE
[Question] installing aptos full node..

### ISSUE THREAD

**Issue by bohyun-korbit** [aptos-labs/aptos-core#5678]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

Hello.

While installing aptos full node, I am getting the error below. I need help.
Can you tell me how to handle it? Thanks.

Nov 22 10:04:17 ip-10-243-2-241 aptos-node[88951]: 2022-11-22T10:04:17.054591Z [sync-driver-1] ERROR state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:881 {"message":"Storage synchronizer error: \"Failed to execute/apply the storage data chunk! Error: Transaction list too new. Expected version: 12253262. First transaction version: 12297262.\"","name":"storage_synchronizer"}

Nov 22 10:04:17 ip-10-243-2-241 aptos-node[88951]: 2022-11-22T10:04:17.058717Z [sync-driver-1] ERROR state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:881 {"message":"Storage synchronizer error: \"Failed to execute/apply the storage data chunk! Error: Transaction list too new. Expected version: 12253262. First transaction version: 12299262.\"","name":"storage_synchronizer"}

**Comment by zhy827827** [comment]
Failed to execute/apply the storage data chunk! Error: Transaction list too new!!

when docker stop and start docker again,then have this error log!

**Comment by zhy827827** [comment]
> > Failed to execute/apply the storage data chunk! Error: Transaction list too new!!
> > when docker stop and start docker again,then have this error log!
> 
> ???

Have you solved this problem?

**Comment by 1makarov** [comment]
https://github.com/aptos-labs/aptos-core/issues/5692

**Comment by JoshLind** [comment]
Can you retry with the latest version of the `main` branch? This should solve your issue 😄
