### ISSUE TITLE
How to faucet for testnet account in typescript?

### ISSUE THREAD

**Issue by Redmon540** [aptos-labs/aptos-core#5679]
Anyone know how to open faucet for testnet account in typescript?
In dapp, for test, I created 3 testnet accounts.
But no funds.
So this causes an insufficient funds error.
How to get funds?

**Comment by e99243506bigplay** [comment]
Currently I think, testnet need to do recaptcha to get fund in https://aptoslabs.com/testnet-faucet

**Comment by Redmon540** [comment]
yeah, btw there are AptosClient in aptos sdk.
Is there way to faucet by AptosClient?

**Comment by e99243506bigplay** [comment]
Try in Devnet

**Comment by Redmon540** [comment]
I already tried in devnet several times, it sometimes dies.
I think it is because a lot of transactions work in devnet.
So I wanna try it in testnet.
Anyway thanks a lot for your time and help.

**Comment by banool** [comment]
This is not possible in testnet, you must either use a wallet like Petra or https://aptoslabs.com/testnet-faucet. We used to have a completely open faucet for testnet (like in devnet) but unfortunately it was getting abused by bots, so we had to change to this model.

**Comment by Redmon540** [comment]
thanks for your help
