### ISSUE TITLE
[RFE] Develop Build Apps index and diagram depicting flow

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5680]
# RFE

## Request

We should create an introductory page and diagram depicting user flow. @movekevin is suggesting this outline:

1. Dapp diagram: smart contracts, UI, full nodes, validators and how they all fit in. Who sends requests to whom from a simplified app developer perspective.
2. References while explaining the above diagram to concepts, reading/writing block chain data, smart contracts, etc.
3. Network urls + reference to the running node locally section
4. Further research
    a. API reference
    b. SDK reference
    c. Move reference, books, playground
     d. Courses/education material
     e. Bug bounty reference

Here has a draft diagram for our use here:

![App-Dev-Flow](https://user-images.githubusercontent.com/114445310/203383252-13e3b552-eb74-4473-a64c-51b6cc8c280a.jpg)

**Comment by clay-aptos** [comment]
![build-apps-flow](https://user-images.githubusercontent.com/114445310/206301677-175b58c3-dee0-40a7-b856-bcfa16a207d0.svg)
![build-apps-flow](https://user-images.githubusercontent.com/114445310/206301690-d5e174e7-2ce4-4420-b287-b5a572ae600e.png)

Hi @movekevin , I have started this diagram yet imagine it is far from complete. For instance, I don't know what you wrote between the smart contract boxes or even the purpose of the outer boxes there.

Please take a look. Ideally, we can get you editing directly. If not, I can make the necessary changes.

**Comment by clay-aptos** [comment]
And remember you have the Doc titled "Aptos Developer Guide Organization" that would serve well as the index page you desire.

**Comment by movekevin** [comment]
Looks good to me!

**Comment by clay-aptos** [comment]
> Looks good to me!

So what goes where the question mark is now? Apps? I can't read it in your image (see OP).

**Comment by clay-aptos** [comment]
@movekevin , we should consider including information from the doc we built out for the partner with first letter D. :-)

I can remind you when we talk.

**Comment by clay-aptos** [comment]
I have included this issue and the doc in the platform ecosystem meeting notes. @gregnazario is suggesting we develop an e2e tutorial in a single page. The developer index proposed here could serve that purpose.

I suggest we cover: checkout to simple change, troubleshooting, and reversion. Here is an example I proudly helped create:
https://source.android.com/docs/setup/start

**Comment by clay-aptos** [comment]
@gregnazario is working up related materials in:
https://github.com/aptos-labs/aptos-core/pull/6236
