### ISSUE TITLE
[Bug] API return 507 but storage if sufficient

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#5691]
# 🐛 Bug

## To reproduce
call submit transaction api

**Stack trace/error message**
```
// Paste the output here
{"level":"WARN","source":{"package":"aptos_api","file":"api/src/log.rs:49"},"thread_name":"api-0","hostname":"fullnode-aptos-fullnode-e1-0","namespace":"aptos-testnet-fullnode","timestamp":"2022-11-23T09:25:08.000786Z","data":{"elapsed":"657.135µs","method":"POST","path":"/v1/transactions","remote_addr":"10.73.204.73:45604","status":507,"user_agent":"Go-http-client/2.0"}}
```

## Expected Behavior

our storage usage is 67%, so it should not return 507

## System information

**Please complete the following information:**
-  aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b
- 
-

**Comment by gregnazario** [comment]
507 is returned if the mempool is full for your account.

**Comment by gregnazario** [comment]
https://github.com/aptos-labs/aptos-core/blob/main/api/src/transactions.rs#L1073-L1078

Does this answer your question?

**Comment by nolanxyg** [comment]
Yes, thanks!
