### ISSUE TITLE
Failed to execute/apply the storage data chunk! Error: Transaction list too new. Expected version: 12253262

### ISSUE THREAD

**Issue by zhy827827** [aptos-labs/aptos-core#5692]
# 🐛 Bug

**Code snippet to reproduce**
```rust
{
“chain_id”: 1,
“epoch”: “153”,
“ledger_version”: “12189261”,
“oldest_ledger_version”: “0”,
“ledger_timestamp”: “1666697734982542”,
“node_role”: “full_node”,
“oldest_block_height”: “0”,
“block_height”: “3322594”,
“git_hash”: “83f4b2222a81b30a771e0966b55711b0c4caed23”
}
```
I deploy aptos-full-node, where synchronize to block height 3322594, and it will be out of sync. and aptos-node have an error: "Failed to execute/apply the storage data chunk! Error: Transaction list too new. Expected version: 12253262. First transaction version: 12299262"

No one officially can provide suggestions?？

**Comment by JoshLind** [comment]
@zhy827827, thanks for the bug report. The easiest way to work around this is to change your syncing mode to transaction output syncing, see here: https://aptos.dev/guides/state-sync/#applying-all-transaction-outputs. This should unblock you. Just to confirm, this is for mainnet, correct?

**Comment by zhy827827** [comment]
yes, for mainnet

**Comment by zhy827827** [comment]
> @zhy827827, thanks for the bug report. 😄 The easiest way to work around this is to change your syncing mode to transaction output syncing, see here: https://aptos.dev/guides/state-sync/#applying-all-transaction-outputs. This should unblock you. Just to confirm, this is for mainnet, correct?

According to the official documents.https://aptos.dev/nodes/full-node/fullnode-source-code-or-docker：
Method 1: Building and running from source：
cp config/src/config/test_data/public_full_node.yaml fullnode.yaml ，Why not write the synchronization options to the fullnode.yaml  file? 
for example:
```
base:
    # Update this value to the location you want the node to store its database
    data_dir: "/opt/rockx/aptos/data"
    role: "full_node"
    waypoint:
        # Update this value to that which the blockchain publicly provides. Please regard the directions
        # below on how to safely manage your genesis_file_location with respect to the waypoint.
        from_file: "./waypoint.txt"

execution:
    # Update this to the location to where the genesis.blob is stored, prefer fullpaths
    # Note, this must be paired with a waypoint. If you update your waypoint without a
    # corresponding genesis, the file location should be an empty path.
    genesis_file_location: "./genesis.blob"

full_node_networks:
    - discovery_method: "onchain"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6180"
      network_id: "public"
      # Define the upstream peers to connect to
      seeds:
        {}

 **state_sync:
     state_sync_driver:
         bootstrapping_mode: ExecuteTransactionsFromGenesis
         continuous_syncing_mode: ExecuteTransactions**
api:
    enabled: true
    address: 0.0.0.0:8080
```

**Comment by JoshLind** [comment]
>Why not write the synchronization options to the fullnode.yaml file?

The latest version of the `main` branch no longer requires this -- the code works this way by default now. 😄 It should work out of the box. Let me know if you continue to see any issues.

**Comment by zhy827827** [comment]
thancc guys!

**Comment by dusmart** [comment]
It works around by the recommendation config. Thanks for your guys.

Do someone know why is this happen? Is there a hard-fork on mainnet at 12253262?
