### ISSUE TITLE
[Feature Request] How to get info about token owners

### ISSUE THREAD

**Issue by kachurun** [aptos-labs/aptos-core#5693]
# 🚀 Feature Request
I need to write typical for any ERC721 collection methods, such as:
  - token_of_owner_by_index(address, index)
  - token_by_index(index)
  - balance_of(address)
  - owner_of(tokenId)

or get this info from script/cli, it is possible? I research docs and sources and couldn't find any way to do that, but then how marketplaces can display tokens for users?

I also found similar question without answer on forum (https://forum.aptoslabs.com/t/get-nft-owned-by-address/113836)

**Comment by e99243506bigplay** [comment]
Learn how to check "Table" on Fullnode, then take research on https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-token/sources/token.move
Every account should has 0x1::token::TokenStore, check them on Aptos Explorer.

**Comment by davidiw** [comment]
You will need an indexer for this: https://aptos.dev/guides/indexing/#aptos-indexer-graphql-servers
