### ISSUE TITLE
How to send an ed25519 signature via Petra wallet?

### ISSUE THREAD

**Issue by Stumble** [aptos-labs/aptos-core#5696]
There seems to be some discrepencies between Typescript SDK and Petra wallet when it comes to sending an ed25519 signature.

We have a move function that takes a ed25519 signature (typed as `vector<u8>`) as the last parameter
```
    public entry fun verify(
        ...
        signature: vector<u8>,
    )
```

It is perfectly fine to send signature to this function using TypeScript SDK with ABI.
```
  public async verify(
   .....
    signature: aptos.HexString,
  ) {

    const payload = this.txBuilder.buildTransactionPayload(
      this.typeName('verify'),
      [],
      [...., signature.toUint8Array()],
    );
    await broadcast(payload);
}

await verify(....., '0xdeadbeef');
```

However, when we try to do the same thing with Petra wallet:
```
  const debugSig = '0xdeadbeef';
  const transaction = {
    arguments: [
      ....
      debugSig,
    ],
    function: `${moduleAddr}::pkg::verify`,
    type: 'entry_function_payload',
    type_arguments: [],
  };
    const pendingTransaction = await window.aptos.signAndSubmitTransaction(
      transaction
    );
```

we got this error:
```
Transaction error
Wrong number of bytes were given as input when deserializing an Ed25519 signature.
```
![image](https://user-images.githubusercontent.com/3461891/203745175-aff1566e-6fb8-4c1b-8b85-9ccd9cd1a928.png)

NOTE: `0xdeadbeef` is just an example, in our test, it is replaced with an actual hex-encoded signature string, for example
```
"0x397be8ba1cdb31072922a733049b65fbe2855a02a532b0c18cad38fa5e53ba48445f4703fb65604681257a067bea4d847191ea63ec8608e4bd1a9ee63718210f"
```

We have tried 
1. use BCS to encode the signature first and then convert it to HexString to send it to Petra wallet, didn't work.
2. removing `0x` prefix, didn't work.
3. convert HexString to Uint8Array, got a different error: `Invalid vector args.`

**Comment by Stumble** [comment]
It turns our the Petra wallet just do not like Uint8Array... Here is how we solved it:
```
// convert hex-encoded string without 0x prefix to an Uint8Array.
const hexToBytes = (hex: string) : Uint8Array => {
    if (typeof hex !== 'string') {
        throw new TypeError('hexToBytes: expected string, got ' + typeof hex);
    }
    if (hex.length % 2)
        throw new Error('hexToBytes: received invalid unpadded hex');
    const array = new Uint8Array(hex.length / 2);
    for (let i = 0; i < array.length; i++) {
        const j = i * 2;
        const hexByte = hex.slice(j, j + 2);
        const byte = Number.parseInt(hexByte, 16);
        if (Number.isNaN(byte) || byte < 0)
            throw new Error('Invalid byte sequence');
        array[i] = byte;
    }
    return array;
}

// convert hex-encoded string without 0x prefix to a number array.
const hexStrToArray = (hexStr: string) : number[] => {
  return Array.from(hexToBytes(hexStr));
}

// ....... 
// change original code to:

const transaction = {
  arguments: [
    ....
    hexStrToArray(debugSig.substring(2)),
  ],
  function: `${moduleAddr}::pkg::verify`,
  type: 'entry_function_payload',
  type_arguments: [],
};
```

**Comment by kent-white** [comment]
yea I think the latest release fixed uint8arrays, but it might not be perfect. We can take a look.

> use BCS to encode the signature first and then convert it to HexString to send it to Petra wallet, didn't work.

You should be able to just send a plain string BCS

ex.
```
const typeArgs = [
    new TxnBuilderTypes.TypeTagStruct(TxnBuilderTypes.StructTag.fromString('0x1::aptos_coin::AptosCoin')),
  ];

  const encodedArgs = [
    BCS.bcsToBytes(TxnBuilderTypes.AccountAddress.fromHex('0x3d78ef065f4dd973dd755b33028137184cd72a76410c3252936e3be502142b33')),
    BCS.bcsSerializeUint64(BigInt(1)),
  ];

  const entryFunction = TxnBuilderTypes.EntryFunction.natural(
    '0x1::coin',
    'transfer',
    typeArgs,
    encodedArgs,
  );
  const txn = new TxnBuilderTypes.TransactionPayloadEntryFunction(entryFunction);
  window.aptos.signAndSubmitTransaction(txn);
  ```

**Comment by Stumble** [comment]
Thanks for the reply. We didn't use BSC to encode it for two reasons:
1. Aptos Typescript SDK needs some polyfills to work in browser, which our front-end team prefer not, and
2. we were trying to send the raw signature bytesthat should not be encoded again, to the contract.

**Comment by jjleng** [comment]
Can you give us some details about the polyfills. We strived to make Aptos SDK able to run in browsers without any polyfills. If that's not the case, please let us know.
