### ISSUE TITLE
[Question] Why when I submit a multi signer txn, signers must be de-duplicate?

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#5703]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

https://github.com/aptos-labs/aptos-core/search?q=SIGNERS_CONTAIN_DUPLICATES

My question is, why signers must be de-duplicate? I have such of usage case about: someone made a contract with `public entry fun func(s: signer)`, because the function signature by that, now I need multiple signer to interact on the function if I want to interact it multiple time and without gas cost but sadly, there is signer verification were mentioned on above.

**Comment by davidiw** [comment]
This is ... interesting to say the least. It does seem like the author of that contract should have made an appropriate entry point to handle this correctly. You can still construct a script that might be able to call into this interface effectively. You can also likely construct your own entry function that does what you're looking for.

Given the nuance here to change this and the security implications of having the same signer multiple times, I'm marking this as not going to fix. There's a good likelihood that the design of the contract seems likely not well thought out and we should ask that developer to add appropriate entry functions.
