### ISSUE TITLE
[Bug] config `max_transactions_page_size` not working

### ISSUE THREAD

**Issue by Astrapolis-peasant** [aptos-labs/aptos-core#5706]
# 🐛 Bug

the max_page_size in config is no longer working
## To reproduce
**Code snippet to reproduce**
```
curl http://localhost:8080/v1/transactions?start=149376&limit=1024
```
```
const DEFAULT_PAGE_SIZE: u16 = 25;
```
This is hardcoded in `https://github.com/aptos-labs/aptos-core/blob/5ff03ee2dcf81cd955a73fd1f95fec615efdb2f9/api/src/page.rs`

**Stack trace/error message**
```
// Paste the output here
```

## Expected Behavior

The requested page size should be configurable
## System information

**Please complete the following information:**
- 
- 
-

**Comment by banool** [comment]
Hi, you can see here that the max limit you can specify depends on the API config: https://github.com/aptos-labs/aptos-core/blob/main/config/src/config/api_config.rs#L77. So if you're using the default config, you should be able to retrieve up to 100 txns in a single request.

**Comment by davidiw** [comment]
closing out, feel free to re-open if you need further guidance.

**Comment by norbubb** [comment]
https://github.com/aptos-labs/aptos-core/pull/6116
