### ISSUE TITLE
[Bug] aptos move create-resource-account-and-publish-package creates unexpected resource account addresses  

### ISSUE THREAD

**Issue by jjleng** [aptos-labs/aptos-core#5718]
# 🐛 Bug

aptos move create-resource-account-and-publish-package creates unexpected resource account addresses  

## To reproduce

aptos move create-resource-account-and-publish-package --seed hex:1 --package-dir contracts/mint_nft --address-name mint_nft --named-addresses source_addr=default

This command should interpret the `seed` value `hex:1` as `1`. The current behavior is interpreting `hex:1` as a string.

**Comment by gregnazario** [comment]
I would not call this a bug, but rather a documentation error.

You can see here where the docs are for the `create-resource-account` and this mirrors it in the seed

https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos/src/account/create_resource_account.rs#L22-L27

There are two actions that need to be taken:

- [ ] Fix documentation here to use a string without `hex:` before it: https://github.com/aptos-labs/aptos-core/blob/cfef6f0ffdb2e823aa70356760283695fa1012d3/aptos-move/move-examples/mint_nft/sources/minting.move#L38
- [ ] Add documentation for these two fields accordingly / consider renaming `address-name` https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos/src/move_tool/mod.rs#L605-L609

**Comment by clay-aptos** [comment]
Do we address this in the following PR?:
https://github.com/aptos-labs/aptos-core/pull/5714

Please add me to any documentation bugs, and I will do my best to help. Or use the Documentation bug link here to get me auto-assigned:
https://github.com/aptos-labs/aptos-core/issues/new/choose

That said, I agree these changes should come from Eng. Please let me know if you want me to review. I am just seeing this...

**Comment by 0xchloe** [comment]
yeah we addressed the documentation error in https://github.com/aptos-labs/aptos-core/pull/5714.

@gregnazario, I think you're right, the `address-name` variable name is confusing. any suggestion for a better name?

**Comment by clay-aptos** [comment]
> yeah we addressed the documentation error in #5714.
> 
> @gregnazario, I think you're right, the `address-name` variable name is confusing. any suggestion for a better name?

@gregnazario do we have an answer for this? Any further action needed?
