### ISSUE TITLE
[Bug] CLI: Unexpected error: Not a directory (os error 20)

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#5725]
# 🐛 Bug

If folder contains `.DS_Store` the command `aptos move test` returning unexpected error.

```
{
  "Error": "Unexpected error: Not a directory (os error 20)"
}
```

## To reproduce

Create new move package folder and add `.DS_Store` there.

## Additional context

Tested on CLI v1.0.0

**Comment by gregnazario** [comment]
Could you provide me an example?  I just did the following to reproduce, and I did not see an issue

```
$ aptos move test --named-addresses hello_blockchain=0x22
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Examples
Running Move unit tests
[ PASS    ] 0x22::message_tests::sender_can_set_message
[ PASS    ] 0x22::message::sender_can_set_message
Test result: OK. Total tests: 2; passed: 2; failed: 0
{
  "Result": "Success"
}
$ mkdir .DS_Store
$ aptos move test --named-addresses hello_blockchain=0x22
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Examples
Running Move unit tests
[ PASS    ] 0x22::message_tests::sender_can_set_message
[ PASS    ] 0x22::message::sender_can_set_message
Test result: OK. Total tests: 2; passed: 2; failed: 0
{
  "Result": "Success"
}
```

**Comment by gregnazario** [comment]
@borispovod please let me know if this is still an issue, I cannot reproduce

**Comment by 0xZihan** [comment]
I run into this error and `aptos move clean` helped.

**Comment by borispovod** [comment]
@gregnazario Essentially, it occurred due to the presence of the .DS_Store directory on a Mac within the build directory, I believe. Recently, I haven't encountered this issue, so it should be resolved now.

Sorry for delayed answer.

**Comment by BenDavis36** [comment]
Just ran into this error `aptos move clean` is indeed the solution.
