### ISSUE TITLE
`aptos move run-script --script-path` does not compile in the same way as `aptos move compile`

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5733]
Imagine you have this project:

`Move.toml`:
```
[package]
name = 'my_script'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
addr = "_"
```

`sources/my_module.move`:
```
module addr::my_module {
    public entry fun do_nothing() { }
}
```

`sources/my_script.move`:
```
script {
    use std::signer;
    use aptos_framework::aptos_account;
    use aptos_framework::aptos_coin;
    use aptos_framework::coin;

    fun main(src: &signer, dest: address, desired_balance: u64) {
        let src_addr = signer::address_of(src);

        addr::my_module::do_nothing();

        let balance = coin::balance<aptos_coin::AptosCoin>(src_addr);
        if (balance < desired_balance) {
            aptos_account::transfer(src, dest, desired_balance - balance);
        };
    }
}
```

Now, this works because as part of compilation, the address is baked in and `my_module` is considered as part of compilation. Same thing if you have the address in Move.toml:
```
aptos move compile --named-addresses addr=81e2e2499407693c81fe65c86405ca70df529438339d9da7a6fc2520142b591e

aptos move run-script --compiled-script-path build/my_script/bytecode_scripts/main.mv --args address:b078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823 --args u64:5
```

If you do this however, it does not know about the address (it ignores addresses in Move.toml). In addition, it doesn't consider the other modules:
```
aptos move run-script --script-path sources/my_script.move --args address:b078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823 --args u64:5
```

It seems like `--script-path` introduces multiple footguns. Either we add the following features:
- Make the tool compile everything like it would do with `aptos move compile` when using `--script-path`
- Make the tool read Move.toml when using `--script-path`
- Add the `--named-addresses` argument to `run-script`

Or we just remove `--script-path` entirely and require people to compile first. We can discuss and see how hard it'd be to implement those features. My first thought was we just nuke `--script-path`, but at first glance it is much more user friendly than `--compiled-script-path`, which requires you to understand the output of compilation.

**Comment by banool** [comment]
More context can be found in the conversation leading up to this message: https://discord.com/channels/945856774056083548/946123778793029683/1047513936951509075. 

See also https://stackoverflow.com/questions/74627977/how-do-i-execute-a-move-script-with-the-aptos-cli/74628085 for the full guide on how I got this example code working.

**Comment by davidiw** [comment]
This is a bit unfortunate. I would reckon that as is `run-script` is only viable for framework scripts. Even if you pass in named-addresses, you still need to know which modules to download. Per your comment, you could try to get the data from a nearby move.toml. I think it is also unfortunate that move compilation of scripts doesn't place the scripts into an appropriately named bytecode file, e.g., compile(package with script_name.move) -> script_name.mv.

I think run-script should likely be hidden and left as a private API interface -- since it still offers some conveniences.

**Comment by banool** [comment]
I think `run-script` with `--compiled-script-path` isn't too bad, the footguns are definitely fewer in number. The main downside is that you have to know where to look to find the bytecode.

**Comment by gregnazario** [comment]
I added a way to do this with https://github.com/aptos-labs/aptos-core/pull/6441

Though the UX isn't great.  There was no way to compile the scripts correctly, now it's ready so you can compile the scripts, and run them with that command.

**Comment by wrwg** [comment]
Should we close?

**Comment by wrwg** [comment]
Ping @gregnazario : is this bug covered by your new command to compile scripts?

**Comment by gregnazario** [comment]
This did provide a new way to compile scripts, the UX is not great.  We can close this for now.
