### ISSUE TITLE
Add configurable simulation gas for VM-derived SDK queries

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#5743]
# Simulation and SDKs

Presently, transaction simulations involve the assessment of gas costs per standard [base gas parameters], enabling builders to estimate gas costs for their transactions.

Another use case for transaction simulations is for VM-derived SDK queries, most notably through the [`move-to-ts` tool's `query` attribute], which enables streamlined indexing SDK generation:

1. Developers write indexing code in Move, which operates directly on data structures in their native form, and which can be robustly unit tested at the VM level.
2. An auto-generated SDK then queries indexed data through transaction simulation mode.

The SDK entry point transaction simulation is bound by standard base gas parameters, however, which means that for complex indexing queries, the simulation may fail due to gas limits. Here, developers may be forced to dedicate resources to creating custom indexing solutions that query exotic data structures via REST, etc., rather than simply writing an entry point in Move and transpiling into a handy SDK tool.

# Proposed solution

To enable convenient indexing workflows, it is suggested that full nodes incorporate configurable simulation gas. Here, the intent is to eliminate indexing transaction simulation failures due to gas limits, including the need to deposit excess `APT` at an account used as a simulation signer. For instance, if one were to run a custom full node they would want to modify the following parameters from [`transaction.rs`]  as such:

1. `maximum_number_of_gas_units` (raise for desired behavior)
2. `min_price_per_gas_unit` (lower for desired behavior)
3. `gas_unit_scaling_factor` (raise for desired behavior)

However, rather than requiring builders to run custom full nodes, it is suggested that full nodes simply incorporate a transaction simulation `bool` flag like:

1. `rail_transaction_gas_parameters`, which would update the relevant parameters per above, or
2. `rail_transaction_gas_to_one_octa`, which would simply drop transaction gas down to 1 octa at the conclusion of a transaction.

Regardless of the implementation, transaction simulation still requires full node resources and as such it may not be appropriate to enable such configurability on a public full node. Hence node initialization could simply incorporate another bool flag `allow_simulation_gas_configurability`, such that builders can run their own private full nodes with gas configurability enabled.
This will allow builders with simulation gas configurability needs to run a standard full node rather than build a custom one from source.

@wrwg @yevgenypi @Manahip @davidiw @gregnazario @CapCap @vgao1996 @msmouse 

[base gas parameters]: https://aptos.dev/concepts/base-gas/
[`move-to-ts` tool's `query` attribute]: https://github.com/hippospace/move-to-ts#query
[`transaction.rs`]: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-gas/src/transaction.rs

**Comment by wrwg** [comment]
We are actually planning to make `#[view]` functions a supported feature (perhaps to some extend in Q4 already), as this is a highly desired feature. Would this make this obsolete, or do you still see a use?

**Comment by davidiw** [comment]
@wrwg is planning on implementing a robust view function similar to eth_call. Will that require gas parameters? We still need some way to limit execution of a request, otherwise individuals can create infinite loops in move and burn a fullnode. There may be other ways around this other than gas, such as running move in thread and limiting how long any view function can run.

**Comment by alnoki** [comment]
> @wrwg is planning on implementing a robust view function similar to eth_call. Will that require gas parameters? We still need some way to limit execution of a request, otherwise individuals can create infinite loops in move and burn a fullnode. There may be other ways around this other than gas, such as running move in thread and limiting how long any view function can run.

@davidiw the functionality you describe will of course be helpful, especially if @wrwg 's implementation does not require `APT` to be held on-chain for a corresponding simulation account.

However, as I noted above it looks like this approach will not support mutations, which may be necessary for some more complex simulation purposes. Thread limiting sounds like a worthwhile approach, but I would add that DoS mitigation need only be implemented for public instantiations (e.g. rate-limiting IP addresses, allowing a certain free thread count with the rest paid, etc.). For private nodes, especially indexers, it may be necessary to run expensive computations every once in a while as a checkpoint then just sum up event diffs between checkpoints, for example. Here it seems most straightforward to allow private nodes to use as many resources as required.

**Comment by wrwg** [comment]
The `#[view]` functions have been implemented and are coming out with the next testnet.

**Comment by alnoki** [comment]
> The `#[view]` functions have been implemented and are coming out with the next testnet.

Excellent, thanks for the update! Do these entail the same gas limitations as typical transactions?

**Comment by wrwg** [comment]
> > The `#[view]` functions have been implemented and are coming out with the next testnet.
> 
> Excellent, thanks for the update! Do these entail the same gas limitations as typical transactions?

No they do not. They can be executed on any full node. One can pass a gas meter if the caller wants to restrict them for some reason.

**Comment by clay-aptos** [comment]
Hi @alnoki , does this meet the request?
https://aptos.dev/guides/aptos-api/#reading-state-with-the-view-function

I will take a look through this issue to see if we're missing anything. Thanks.

**Comment by alnoki** [comment]
> Hi @alnoki , does this meet the request? https://aptos.dev/guides/aptos-api/#reading-state-with-the-view-function
> 
> I will take a look through this issue to see if we're missing anything. Thanks.

View functions should probably be sufficient for most use cases. If someone needs to query state in a way that exceeds gas limitations, then they are probably doing some heavy-duty back end tooling that will require them to run an indexer anyways.

**Comment by clay-aptos** [comment]
Thanks for confirming, @alnoki . I am adding @wrwg and @runtian-zhou for credit and closing this out. Pleas reopen if you see anything amiss. Thanks again.
