### ISSUE TITLE
[Bug] Security improvement: limit access rights to generated keys 

### ISSUE THREAD

**Issue by Al3c5** [aptos-labs/aptos-core#575]
# 🐛 Bug

When generating a private key with 

`  cargo run -p aptos-operational-tool -- generate-key --encoding hex --key-type x25519 --key-file /path/to/private-key.txt`

the generated file is readable by everyone
```
ubuntu@aptos-devnet:~/aptos-core$ ll /home/ubuntu/.aptos/private_keys.txt
-rw-rw-r-- 1 ubuntu ubuntu 64 Apr 20 18:11 /home/ubuntu/.aptos/private_keys.txt
```

## To reproduce

**Code snippet to reproduce**
```rust
N/A
```

**Stack trace/error message**
```
N/A
```

## Expected Behavior

User must  change rights with

`chmod 600 /path/to/priv_key.txt`

Doing it at generation time is easy and more secure.

## System information

**Please complete the following information:**
- Aptos Core Version : 0.1.0
- Computer OS : Ubuntu 20.04

**Comment by JoshLind** [comment]
'cc @gregnazario, @kent-white 🚀

**Comment by gregnazario** [comment]
Good callout, we can definitely improve that!

**Comment by gregnazario** [comment]
This is platform specific and this trait will work for the more constrained permissions required for Unix. https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html

It'll need to be gated by OS, since Windows doesn't support it.

**Comment by zsluedem** [comment]
@gregnazario Can I take this one?

**Comment by davidiw** [comment]
resolved.
