### ISSUE TITLE
[BLK-206] consensus-only forge tests

### ISSUE THREAD

**Issue by ibalajiarun** [aptos-labs/aptos-core#5750]
Enable the ability to trigger run forge tests with consensus only (no execution, storage, etc).

<sub>From [SyncLinear.com](https://synclinear.com) | [BLK-206](https://linear.app/aptoslabs/issue/BLK-206/consensus-only-forge-tests)</sub>

**Comment by geekflyer** [comment]
hello this is a test

**Comment by ibalajiarun** [comment]
this is in progress.
