### ISSUE TITLE
[Bug] Indexer fails after running for about 15 minutes. 

### ISSUE THREAD

**Issue by dbfreem** [aptos-labs/aptos-core#5764]
# 🐛 Bug
Has anyone seen this. I run an **indexer** fullnode for a while and it just keeps stopping. I setup RUST_LOG to debug and still didn't get any output about why the indexer was stopping.

`017917777, d4e43fa15a4cf475b35f7278f02ae5a694e14fbd7ef2494e39e7978781b3eefe: 101001973494946, da557f6d45952778e0c4c7296dc8f8303d846d5453800efd7b03cfbd5f8def04: 101002092621626, 947c6451ad9a8659cba4e60a6da41086eb66e73fc07936bd3b7044873b5e094d: 2186904942761653, 86da6288dd50be1653aa2a8269acf881d3b4b414938ca7ab3b662c2dfeb794df: 2193259859520264, e8fac9c24a3bfc71ed79d466fa3c2c2b4787f1f9686e1d1e9e97fde473898788: 2193377083326064, ee49776eff9fd395eb90d601449542080645e63704f518b31c6f72b6a95d7868: 2194715492719240, 48179547b95487f77214c12e2561d53531122a91e5f79ee9be968ce8185bc444: 2193210921230423, b5064f2e6d2d4887c836c8cbd90d23a75cd7afd4530e4a82f06bf528abcb30d6: 2193210206601287, fcbc1da54b125c093d49bf4a604a1854d38f99b6cffc09255d8af5446898ddba: 2193208119392085, 4c893cf8d614f503e982df5b48e9443bab4ea6be4f922a5d3858305c0a3af3ee: 2193208889419457, c32f662cd9718f02d8a8e5628f8f642fa27cd9b5f457b406ed734901a4939e34: 1993430433804042, 324df1e27c4129a58d73851ae0e9366064dc666a73e747051e203694a4cb257: 1993419719812060, 3d654d35d558d6381fe6a0484d81c4fed128cd8adc1ca7a1482c297da80ee039: 1641767228887411, ea733e480c379c61dae9cfb3f14a388f6a683d7a797c135f86b924fb7a2e8cdb: 100885661164433, bcb83e07eed46120a0143bd9861ea82495293228b9cd64cc43bda722edaeb7ad: 100884529071920, c067ce10f1faa4812fe608e2d4b3e1fe0bb629e91cfff532cccc23803a624414: 100885181956404, c1f31446852220ffdf2fe294fd42fa5d7ced48c7d0f1378d6813ae8d972f1adf: 100883366023940, 52b48fb6e6883d4cdf244cde8d7e972ea2d8ece9b5e484ed5085aacef0e306a1: 100884832287491, 9dfeca70acb3e01328d9dbbda4a6c23913fcd81ef25f74fab52cb2e96b0a1486: 100884139831175, 85bec1dcb618004064ab52a594321e8f047bac53be8244c5d10ac136128e30f7: 100885545583977, 4cfeaf68aacfd0cd459c292837854ce058b9ba6c1cc35e8684b1a5030b1dc922: 100884644812144, 447fc1fc130cf9245d9ca291785d0f8a00c3ebdc26b2e4c6165801b0af01c917: 100883375012497, d60280852b50c341b22bba06562a817293d7b834eac251e7600b25d8bdd9efa3: 100998829521464, dca6aaf410e984463b37e192652b3c09b0ae3968b3e0171bb076ae0e21112ef9: 100883384585249, d2dc57e95669c9bf102cb5693fe8b2a8b10d330213d7ddd9fb417f86f183dc1d: 100889232136760, ae139fd4e266beb28925227dcd220d89348117680e48d4aa20685ae102ae2a13: 2193217986498799, 568fdb6acf26aae2a84419108ff13baa3ebf133844ef18e23a9f47b5af16b698: 100998714755449, 99d623e94981c2a6d41306785d69d66c237c6d3ac305cb6f32307785fde7fda2: 2193188033640562, 2fa9d01fb4a1c2fdac5f45419b98213604bc215817d4b394ab372e5d59d2753c: 167667061578331, 35b922386bd35db0f33c732a70d7b6a2e91e463812c8d710f925f6da0e0ace07: 100998666611323, 4b2c524fc36698caf9d049b6088faa002cea3bbcbf5ed764f59768b4fe96efcf: 100881756020475, 18a3ef480b7883d05b917873a8b6d5f5a5f763372b650242ede89836a67cdce8: 100883044358179, c807d24a6ac70599cc9b72c649eb6b00c34a0e9c704447c44d75fade07213a26: 1851773901758790, adbfddd3d10cad1eed59d2c0793df0bfd1d16255309c38b34b8351daaddecccc: 2186803292717751, e9f7d36334768683b85ec1df892dfd8fc389c8f6dbe0b890195d579a6e390c78: 100883785696250, e1abb4ea11673aad3137052dce831eb20a1907815cb4a03ccac38ba7a9e988d3: 100884372758363, 6fdb6516f550ceada7d1fb687b52e4d334c0805a856f17c85f1eb852cbe66ffb: 499718309634021, 925ec5ab56572964dc3cc69bb86c224367dbfc186f6831c26639f9428326c2b4: 100996789286867, 6c8a3474cb49202515d121fea0f3217d303e41f6bdc43e615f1cd90855118089: 1556339425915471, df0996b6998ec080ea7931ccd87400fa74eb57f8129bb0f11996ae8bae12d565: 230534804727413, b840f1cfae5aaa4b50a11a6a23e2e859717e2f355fcd614592b219fc4d4e44a3: 100881587532637, 8d5c9e82d612c390b5dea347918b6421146bb638724854300eed065cc4211a6e: 100881475219185, 32f23e884c0c6f663997c7d4602ef0916bae15492833ee8e7266135e40ff8b14: 100880805419089, cf2a5df3737cd33344dc332416c35278431aed26ff684491b1bf7f9d19e3ee93: 100881378608476, b3254509d1cd652d6e1ca06fd37f3d20aaa42f7faeaf297577b85cf92d2f7462: 2186768345057516, a6eb54c274da96778a6702740a763f6aa7b02eef3d1efc2623d28289d185118: 2186766534212960, 1c6a051d9a5ec4cf4200bab21a794d3afe8259d625f6b78aa4d01ab4652327d5: 1556061245487165, 649127a4d1b26b4cf936f7b795917dbcb571c59c2926ae473fe4d9df3575790e: 1686657867860767, 9df537cbe360f51499f53ca27b83f1c3a92fb7b068bc79eb8e33c85a50f84380: 115265327284219, be4e66094c14a8c69361173fbd6694279db5fd8401bcb1d9c5df066755820a30: 115265445301671, 22dd12212d76bc5844b4a0605bf59fa56547f42a40fb42267e29adca5efecfc8: 937343819197561, 6b5b8d5904ee259636314d6d914f1a59bb6430126dd91a6118202dc734b1df8a: 109777732725830, f08bb83cf89d299e4cddee7ef987b850a35a399900ba22860cc1553da3682a84: 100879434223312, 904bc056aa17a45c2715113e06cb42f5762581a7b839206f5348938db69425be: 100995569911379, 6a1d3313a58719cf5abc1aaee6b4b74bc7e2c69036a8a02f02eb4f3ab4a3d678: 100879778552380, b87476d8877cfc324a520cef4d0cd6e42e26ec3ce613a8127220e2e444561e16: 766328036063300, b225277ba076b6620447f7b10abb30911966eb66d25fb526b7f09c2227425a11: 384221514171233, c29a231581f243ddcbf97de8b93c8aabb466dd6912ce5ba12579ff2f13cb8da5: 384221663772389, fc307ecd61ac025f5ec1828d2114d11b474b4d8a1b0c228c38614dc96b940048: 384221767558769, e8a71d40da724ac1ff522d9686dbf1da21bab2d803441df73c86c4bae76d399: 137672579159450, 371dfdee9fbecaa358683936c5946aa28393067fa60e1e185c4250da461e15cf: 2194581524408928, 9da88926fd4d773fd499fc41830a82fe9c9ff3508435e7a16b2d8f529e77cdda: 1993288127205865, 8e943e68e8e4a1ebb7e5a250b081af507d40e616283f38d2d2a2a4b6523c02ac: 100879704808675, 46b51b26710797faed701722bfc809386110c9720328f2b431e193cb5dc161f7: 2193068636628485, 302b69423fde5c7dd333ee50d48df16f076072e61f95e0f6db5685ee6c70d35b: 100880820108973, f2b6feeea4546648c257c7e33ff4f0aa8db3bb2949cca065c9db015478363458: 100993978186298, 81d41a31fb5d3f827d188511e6fca1ddbed6cfa0ffbd46fa6d84a7adfe59f356: 2186695523007836, 71debfa733376c4f2dc8970de8962931fe107c7dc1daad3bf189101bfd4adc4b: 100885565351245, 4cc22e5d2e84794c3c672b0b34145898ee971a4ff042eabae23627547f6dac80: 2186706878554289, dc37463c5782469908d7ff43873390075980a8fa5b1c0770457c48f8891a5bff: 650782793314922, 6fd3ee60a084952162d62ead1a09f4ccd611f17608789ae45eba4f54967a295e: 504825573169018, ef191e643c2ed2d103de4109a506e020f5dde818cbc1ffe5e4ee36328cd22e9b: 2194546326978088, 209154f6e735562ff13b963b91588039a162fa95f409c068f917f27b762dfff8: 1773475823779549, 9a41af5c002f91dc29cb2843ab823e3d6cdaa6cc86e6331646a4f1328609a744: 1645455367700080, 483cf8942c76d86ed28a9849940abdea14952a551be84c38c844208e13d976d4: 100878755779299, 67af497cdd68361b18dda2409f244ebf6f776aee99094e16a5f371e39456de35: 100876466653337, 3eaf3ebc49555c705c34ec1ffe77404bdb7383b388476c36538b92b7b1b806c9: 1993225531387041, ffb19e4519bc434d3a064652064d14dd34fabc8f785f6be8670d7465d8419c45: 2193100070592572, b4a4f1ef8b0702d85547dc444571a473f736e1205a86db36dad13815ad9bbbf6: 2194511860410948, a286a9187c86b4a3cef60478e5c61bb45757b795a8e6577ebbf0fa990db574cc: 1583058367585265, f05d2fe6618a3cb4258e94f2da24c1ee71ae4e7942b4f8b5836ad5267e59568f: 1707679299754405, dc3d30891191132b668fef5304e32b869e53741ee4f3fbb514e9ae2b05dcfc50: 329312034884993, 8be2ba62bfd783e5fbff57a07acf2a9a95f4d234b3729fbfda9c63f3f42fb78f: 1652700403881242, 401a881d9770f054a1b8cd6829f3d65a040bbe9b387ebcce50bddf0f853077d9: 179328704781924, ]]) }, consensus_data_hash: HashValue(1139729dce190dfef081b9ab3ceae653f2be982c8a53e382a2652da023c1ddad) }, signatures: AggregateSignature { validator_bitmask: BitVec { inner: [190, 221, 231, 239, 175, 192, 239, 94, 143, 229, 255, 191, 156] }, sig: Some(a352f4dcc4bdc42bcd7fe6574be6d43fb88a889b3f431434e447ac5ba080059486af5b74c733dc0091d664f505233d6c00746034fba3c594dc8386388c956f9b6176ff38b3402fe36d8b5e5111a6135662f3dd643aa89a50977e62921e2868f6) } }), bootstrapping_mode is ExecuteTransactionsFromGenesis.","name":"bootstrapper"}Killed`

## To reproduce
I run the below command to start the indexer and also I am running postgres in docker locally

`cargo run -p aptos-node --features indexer -- -f ../aptos/mainnet/fullnode-local.yaml`

## Build Config

```
2022-12-04T01:26:37.265899Z [main] INFO aptos-node/src/log_build_information.rs:21 Build information:
2022-12-04T01:26:37.266673Z [main] INFO aptos-node/src/log_build_information.rs:24 build_branch: main
2022-12-04T01:26:37.266701Z [main] INFO aptos-node/src/log_build_information.rs:24 build_cargo_version: cargo 1.64.0 (387270bc7 2022-09-16)
2022-12-04T01:26:37.266720Z [main] INFO aptos-node/src/log_build_information.rs:24 build_commit_hash: 579848dc6a911aa880c90d36f5dc3d0f6592b347
2022-12-04T01:26:37.266733Z [main] INFO aptos-node/src/log_build_information.rs:24 build_is_release_build: false
2022-12-04T01:26:37.266745Z [main] INFO aptos-node/src/log_build_information.rs:24 build_os: linux-x86_64
2022-12-04T01:26:37.266757Z [main] INFO aptos-node/src/log_build_information.rs:24 build_pkg_version: 0.1.0
2022-12-04T01:26:37.266771Z [main] INFO aptos-node/src/log_build_information.rs:24 build_profile_name: debug
2022-12-04T01:26:37.266784Z [main] INFO aptos-node/src/log_build_information.rs:24 build_rust_channel: 1.64.0-x86_64-unknown-linux-gnu
2022-12-04T01:26:37.266798Z [main] INFO aptos-node/src/log_build_information.rs:24 build_rust_version: rustc 1.64.0 (a55dd71d5 2022-09-19)
2022-12-04T01:26:37.266811Z [main] INFO aptos-node/src/log_build_information.rs:24 build_tag: 
2022-12-04T01:26:37.266824Z [main] INFO aptos-node/src/log_build_information.rs:24 build_time: 2022-11-18 07:38:02 -05:00
2022-12-04T01:26:37.266839Z [main] INFO aptos-node/src/log_build_information.rs:24 build_using_tokio_unstable: true
2022-12-04T01:26:37.266855Z [main] INFO aptos-node/src/log_build_information.rs:26 Feature information:
2022-12-04T01:26:37.267015Z [main] INFO aptos-node/src/log_build_information.rs:27 Running with failpoints feature disabled
2022-12-04T01:26:37.267030Z [main] INFO aptos-node/src/log_build_information.rs:27 Running with assert-private-keys-not-cloneable feature disabled
```

**Comment by dbfreem** [comment]
After looking through the kernel logs looks like the kernal killed the process for Out of Memory. I think this is similar to #5318 so closing this one.

**Comment by bowenyang007** [comment]
If this keeps happening I'd recommend reducing the size of the batch and number of tasks, for example
```
    batch_size: 200
    fetch_tasks: 5
    processor_tasks: 3

```
