### ISSUE TITLE
[Docs][TODO] Add indexer guide for localnet

### ISSUE THREAD

**Issue by bowenyang007** [aptos-labs/aptos-core#5789]
We have instructions on how to run an indexer fullnode for public net, but not how to run a validator w/ indexer on local testnet. Here's the instruction for that 
https://www.notion.so/aptoslabs/Indexer-localnet-fb88322561574541bab71dd06946923a

**Comment by clay-aptos** [comment]
I am adding @0xmaayan as they report during testing this process wasn't smooth and some things didn't work right away and they needed to run some commands. Also there was something weird with the data flow into the DB, when starting a new node transactions didn't show up in the table.

Team, please confirm in new testing these issues don't appear when running through the steps as documented. Also, I am adding @davidiw for help guiding this process of: Draft > Test > Refine > Publish before taking docs live.

Finally, @davidiw do let us know how to avoid including links to internal docs in public issues while still supplying the needed mapping for finding the internal doc later...

**Comment by clay-aptos** [comment]
And thanks, @bowenyang007 ! This is looking good!

**Comment by clay-aptos** [comment]
Please feel free to raise the priority when ready to move. And thanks for filing the issue!

**Comment by clay-aptos** [comment]
Hi @bowenyang007 , you can see a first draft online in:
https://github.com/aptos-labs/aptos-core/pull/6259

We still need to include images or better list the tables. Finally, we should announce in See what's new.

Let me know what you think. Thanks!

**Comment by clay-aptos** [comment]
@bowenyang007 , @gregnazario suggests we need to test the following doc on Linux:
https://aptos.dev/nodes/indexer-fullnode

Unless v2 lands soon.

**Comment by clay-aptos** [comment]
Moving TODOs from PR #6259 to get this document across the line:

4. Create an `indexer_test` database in Postgres.

TODO: How does this reconcile with? `diesel migration run --database-url postgresql://localhost/postgres` on?
https://aptos.dev/nodes/indexer-fullnode/#set-up-database

2. Find the `node.yaml` file in the `Test dir` directory from the paths above.

TODO: Make this mor clear. Ex. Does this `testnet` directory exist in the `main` branch.

 2. Validate your setup by connecting to the local database and confirming all tables are created, for instance using DBeaver.

  TODO: List the tables expected rather than include an image.

**Comment by clay-aptos** [comment]
Hi @zacharydenton and @moonclavedev , this is not a burning issue. I'm just trying to figure out why sometimes Markdown links give Docusaurus fits. See the errors below:

```
Error: Docs markdown link couldn't be resolved: (local-testnet/localnet-indexer.md) in "/Users/claymurphy/aptos-core/developer-docs-site/docs/nodes/indexer-fullnode.md" for version current
    at Array.forEach (<anonymous>)
Error: Docs markdown link couldn't be resolved: (localnet-indexer.md) in "/Users/claymurphy/aptos-core/developer-docs-site/docs/nodes/local-testnet/index.md" for version current
    at Array.forEach (<anonymous>)
client (webpack 5.74.0) compiled with 2 errors
```

VSCode shows the file paths work. Still, I had to strip the `.md` extension to get these links to work in:
https://github.com/aptos-labs/aptos-core/pull/6259

When you get a chance, please guide me. :-) No big hurry. Thanks!

**Comment by clay-aptos** [comment]
Per the related PR, we're closing for v2:
https://github.com/aptos-labs/aptos-core/pull/6259
