### ISSUE TITLE
[Feature Request][Indexer] Add default ans contract address on mainnet  to process ans_lookup.

### ISSUE THREAD

**Issue by Lredhdx** [aptos-labs/aptos-core#5797]
# 🚀 Feature Request

## Motivation
When I use indexer to process ans_lookup, I found there is no data. And I need to add ans contract address in config.But I don't know what is ans contract address. So I don't know if the indexer is ok.

**Comment by davidiw** [comment]
let me route internally to aptos names, I think this would be better handled by them sharing the information on their website.
