### ISSUE TITLE
[Feature Request] Reducing gas cost when mutate token property

### ISSUE THREAD

**Issue by ericEnjoy** [aptos-labs/aptos-core#5799]
# 🚀 Feature Request

Reducing gas cost when mutate token properties. 

## Motivation

Dynamic NFT is an innovation and a way forward. aptos allows us to store properties in chains and dynamic updates of properties can be easily tracked. However, the gas consumption for changing properties has been found to be high in some cases, which is not very friendly for dynamic NFTs that need to update properties frequently.

Some example here:
https://explorer.aptoslabs.com/txn/45893866/payload

Souffl3 has posted an interesting campaign where they use dynamic NFTs for the sweepstakes, as seen in the transaction, each NFT has a 0x3::token::MutateTokenPropertyMapEvent. After calculation, the mutate gas consumption for 5 times is about 0.04 APT, which accounts for most of the transaction cost

## Pitch

Optimize the storage and update of properties in token.move to make the gas lower

**Comment by areshand** [comment]
Thanks for the request. We merged the AIP and the its fix. The mainnet should have the fix soon
