### ISSUE TITLE
[Feature Request] Present authors of pages automatically in Aptos.dev

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5808]
# 🚀 Feature Request

@davidiw was just asking me for a mapping of contents to owners, and I pointed out I have already asked for an Authors list at the bottom of every page on Aptos.dev.

## Motivation

This would provide that mapping while giving an incentive to external and internal contributors both to maintain and enhance the docs.

## Pitch

Our competitors are already doing it and getting more external contributions as a result:
https://docs.sui.io/devnet/learn

This would go a long way toward establishing co-ownership of these materials rather than them being owned by everyone and no one at once.

## Additional context

@moonclavedev and I spoke about this already. I simply need some tracking mechanism to ping from time to time until the feature is complete. :-)

**Comment by zacharydenton** [comment]
Thanks for the reminder, Clay. https://github.com/aptos-labs/aptos-core/pull/5827 adds the list of contributors.

**Comment by clay-aptos** [comment]
Thank you, @zacharydenton! May I ask when we will see this on Aptos.dev? For example, on the bottom of:
https://aptos.dev/concepts/accounts/

**Comment by clay-aptos** [comment]
I'm going to reopen for us to test this out.

**Comment by zacharydenton** [comment]
It's possible that the process for generating the list of authors doesn't work when we're building for Netlify (it won't work for example if Netlify does a shallow clone instead of retrieving the full git history). If that's the case, we can adjust the build process so that we manually generate a JSON file of the authors locally, and check it in to the repository, so that it's available during the Netlify build process.

**Comment by clay-aptos** [comment]
> It's possible that the process for generating the list of authors doesn't work when we're building for Netlify (it won't work for example if Netlify does a shallow clone instead of retrieving the full git history). If that's the case, we can adjust the build process so that we manually generate a JSON file of the authors locally, and check it in to the repository, so that it's available during the Netlify build process.

Thanks, @zacharydenton . That would be great!

**Comment by clay-aptos** [comment]
Actually, this still isn't working. Asking @zacharydenton for an update. Thanks, Zach!

**Comment by clay-aptos** [comment]
I am noting we need to manually regenerate this list per:
https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site#re-generate-contributors

I will do so weekly. In the long term, Zach says we can try to implement this:
https://medium.com/@songulerdemguler/running-scheduled-code-on-github-8e6a03a8d88b

Reopening for tracking. Thanks, @zacharydenton !

**Comment by clay-aptos** [comment]
I do this manually on a weekly basis and so am closing this out.

**Comment by clay-aptos** [comment]
Reopening as @saharct has expressed interest in generating the .json file

**Comment by clay-aptos** [comment]
Adding @banool so he knows we are looking to automate this and perhaps guide Christian on GH actions.
