### ISSUE TITLE
[Bug] make `instanceof` more robust in `aptos` sdk

### ISSUE THREAD

**Issue by Manahip** [aptos-labs/aptos-core#5820]
# 🐛 Bug

Use aptos version 1.3.15 to construct a transaction, and send it using aptos version 1.3.16, [this exception](https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/ecosystem/typescript/sdk/src/transaction_builder/builder.ts#L76) will be triggered.

In complex projects it is common to see multiple versions of aptos sdk present as the project may depend on lots of other packages that use their own aptos versions. We need multiple versions of aptos sdk to maintain some level of compatibility. The use of the instanceof keyword is breaking that compatibility. This problem could be remedies by using a mechanism similar to [Symbol.hasInstance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance)

## To reproduce
Use aptos version 1.3.15 to construct a transaction, and send it using aptos version 1.3.16, [this exception](https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/ecosystem/typescript/sdk/src/transaction_builder/builder.ts#L76) will be triggered.

**Comment by banool** [comment]
@Manahip If you'd be willing to suggest a fix, have us agree on it, and then implement it, that'd be much appreciated. Given that this is a somewhat niche problem, we likely won't have time to address this in the near future.

**Comment by SUPPORTTEAMHERR** [comment]
> # 🐛 Bug
> 
> Use aptos version 1.3.15 to construct a transaction, and send it using aptos version 1.3.16, [this exception](https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/ecosystem/typescript/sdk/src/transaction_builder/builder.ts#L76) will be triggered.
> 
> In complex projects it is common to see multiple versions of aptos sdk present as the project may depend on lots of other packages that use their own aptos versions. We need multiple versions of aptos sdk to maintain some level of compatibility. The use of the instanceof keyword is breaking that compatibility. This problem could be remedies by using a mechanism similar to [Symbol.hasInstance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance)
> 
> ## To reproduce
> Use aptos version 1.3.15 to construct a transaction, and send it using aptos version 1.3.16, [this exception](https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/ecosystem/typescript/sdk/src/transaction_builder/builder.ts#L76) will be triggered.

We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/2dzBgxwuZoBaD3ab6

**Comment by Manahip** [comment]
> Thanks for reporting! It is dangerous to pass instances across different versions of SDKs. In my opinion, JS did the right thing by not passing the `instanceof` check. Imagine that, we added a field or deleted a field to the same class in the new version of SDK, passing instances from the old SDK would cause unknown issues if `instanceof` passed. Instead, I would assume class instances are different across package boundaries. Thoughts?

actually... the typescript team itself avoids the `instanceof` keyword like plague. When a field is deleted from any class, it is ground for major version bump. It really shouldn't break across minor or bug fix versions.

**Comment by Manahip** [comment]
> @Manahip If you'd be willing to suggest a fix, have us agree on it, and then implement it, that'd be much appreciated. Given that this is a somewhat niche problem, we might not have time to address this in the near future.

This is an example, using an explicit `kind` tag: https://github.com/microsoft/TypeScript/blob/main/lib/typescript.d.ts#L847

**Comment by Manahip** [comment]
also, now that we're past mainnet launch.. probably it's time to pick up semantic versioning and bump the sdk's major version to 100 or something :P
