### ISSUE TITLE
[api] remove TransactionOnChainData::accumulator_root_hash

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#583]
I don't think it's useful in any case.

**Comment by davidiw** [comment]
why?

**Comment by msmouse** [comment]
Not useful. 

The root hash at a end-of-block version is signed by validators, the root hash at a random version, on the other hand, doesn't mean much to any one.

**Comment by gregnazario** [comment]
@msmouse you still want to get rid of this?

**Comment by msmouse** [comment]
unless there's a reason to keep it

**Comment by msmouse** [comment]
decided to keep it as in https://github.com/aptos-labs/aptos-core/pull/3189
