### ISSUE TITLE
Fix the go and rust SDKs

### ISSUE THREAD

**Issue by vgao1996** [aptos-labs/aptos-core#5837]
Right now both of our go and rust SDKs are broken. We need to
1. Get them fixed
2. Make sure they handle the new integer types (u16, u32, u256) properly.
  a. We'll likely need to find a suitable u256 representation in Go (there's a related `unimplement()!` in the code introduced by https://github.com/aptos-labs/aptos-core/pull/5626)

**Comment by SUPPORTTEAMHERR** [comment]
> Right now both of our go and rust SDKs are broken. We need to
> 1. Get them fixed
> 2. Make sure they handle the new integer types (u16, u32, u256) properly.
>   a. We'll likely need to find a suitable u256 representation in Go (there's a related `unimplement()!` in the code introduced by https://github.com/aptos-labs/aptos-core/pull/5626)

We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/2dzBgxwuZoBaD3ab6

**Comment by gregnazario** [comment]
@vgao1996 did you clean this up or is it still an issue?

**Comment by vgao1996** [comment]
@gregnazario No I didn't have any time (or plan) to work on this, so I'd assume they are still broken unless someone else already took care of it.

**Comment by gregnazario** [comment]
Closing this, we do not support code generated SDKs anymore, we have a Go SDK fully built, and the Rust one still exists / we can improve upon later.
