### ISSUE TITLE
[RFC] `aptos move new-package` feature

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#5861]
# 🚀 Feature Request

@movekevin on the call proposed to add a command to Aptos CLI, which would allow users to create their packages from templates. 

This is my PR https://github.com/aptos-labs/aptos-core/pull/5727 for the feature. I've implemented what was my take on the design. In the PR review, there was a suggestion https://github.com/aptos-labs/aptos-core/pull/5727#issuecomment-1345444814 to make a proper discussion out of it.

My take is:
```
aptos move new-package [-t TEMPLATE_NAME] PACKAGE_NAME
```
default of `TEMPLATE_NAME` would be `empty`, which will correspond to the current `aptos move init`. 

There's also a `-t coin` for the coin contract, and `-t dapp` for the frontend app.

**Comment by davidiw** [comment]
where do templates come from?

ideally we either place templates in the core repo or require a URL to them.

we should also be able to compile templates directly into the binary so we don't require internet access to generate new projects.
