### ISSUE TITLE
[Docs] links to token standard do not work

### ISSUE THREAD

**Issue by rustielin** [aptos-labs/aptos-core#5870]
# Aptos Documentation Issue

## Location

https://aptos.dev/concepts/coin-and-token/index/
* broken link to: https://aptos.dev/concepts/coin-and-token/index/aptos-coin
* broken link to: https://aptos.dev/concepts/coin-and-token/index/aptos-token

## Description

expected links do not have `../index/..`

**Comment by clay-aptos** [comment]
Hi @rustielin , I don't see these links on the page. From what text?

**Comment by clay-aptos** [comment]
Are you looking at the file in GitHub instead?

**Comment by clay-aptos** [comment]
Perhaps this?:
https://github.com/aptos-labs/aptos-core/issues/5873

**Comment by rustielin** [comment]
Nope I'm looking at aptos.dev. (https://aptos.dev/concepts/coin-and-token/index/)

<img width="864" alt="image" src="https://user-images.githubusercontent.com/12578616/207680233-4ac264d2-d137-4f6a-8422-d18d98692697.png">

The circled link takes me to https://aptos.dev/concepts/coin-and-token/index/aptos-coin

**Comment by clay-aptos** [comment]
Ah, so the next question is how you get to:
https://aptos.dev/concepts/coin-and-token/index/

As the left navigation takes me to:
https://aptos.dev/concepts/coin-and-token/index

No trailing slash, where these links work. And I can't find links to that end URL:
```
➜  developer-docs-site git:(main) grep -r "coin-and-token/index/" docs               
➜  developer-docs-site git:(main) 
```

So I am wondering how you got to the original URL in question as it doesn't appear navigable in Aptos.dev. Thanks, @rustielin !

**Comment by clay-aptos** [comment]
Regardless, this should fix the issue for all users:
https://github.com/aptos-labs/aptos-core/pull/5881

Thanks for the report, @rustielin !

**Comment by clay-aptos** [comment]
Thanks again, @rustielin . More to come in:
https://github.com/aptos-labs/aptos-core/issues/5873
