### ISSUE TITLE
[Bug] burn_by_creator Execution failed in 0x3::token::burn at code offset 143

### ISSUE THREAD

**Issue by binnz** [aptos-labs/aptos-core#5876]
`0x3::token::burn` failed at code offset 156
`0x3::token::burn_by_creator` failed at code offset 143

**Comment by davidiw** [comment]
We'll need more than this, there are tests that show that this works, so it seems like there's just not great unhappy path handling. Closing out, but please re-open if you have more context. An example would be great!

**Comment by cheshire-kiim** [comment]
Anybody here?
My contract occurred this error too.
