### ISSUE TITLE
[APT-26] [1342] Audit and summarize feature set discrepancies between each SDK

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5967]
Currently each SDK we support (TS, Rust, and Python) have different levels of support. We should enumerate specifically what each SDK can and can't do as a first step to closing the gaps.

<sub>[APT-26](https://linear.app/aptoslabs/issue/APT-26/[1342]-audit-and-summarize-feature-set-discrepancies-between-each-sdk)</sub>

**Comment by geekflyer** [comment]
test

**Comment by charlestonxorg** [comment]
Agree
