### ISSUE TITLE
[APT-27] [1342] Port all TS SDK tests over to the Rust SDK

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5969]
Currently the TS SDK test suite is significantly more comprehensive than the Rust SDK test suite (which barely exists, just some tests in the rest client crate). This "super issue" is to track the work of getting the Rust SDK test suite to the same level.

<sub>[APT-27](https://linear.app/aptoslabs/issue/APT-27/[1342]-port-all-ts-sdk-tests-over-to-the-rust-sdk)</sub>

**Comment by gitmalong** [comment]
Where is the Rust SDK? Where can I find the Rust RPC client?
