### ISSUE TITLE
[web-wallet] Add as extension

### ISSUE THREAD

**Issue by kent-white** [aptos-labs/aptos-core#599]
- [ ] Chrome extension compatibility
- [x] Instructions to use the extension from source

## Context
We don't want to deal with full releases right now so we are just going to keep it in development, and in the future may add it to extension stores.

## Additional context

Basic wallet committed: #593

**Comment by kris524** [comment]
Hello, I would like to help with anything on the wallet if possible :)

**Comment by kent-white** [comment]
@kris524 Awesome! Feel free to take this task if you plan to do it in the next day. Otherwise I will knock it out. (Assign it to yourself if you are going to start on it)

I'll file some other improvements later this week too that might be better fits for 1 off tasks :)

**Comment by kris524** [comment]
Hi @kent-white thank you for the response and giving me the opportunity, I am afraid I need to finish my current task and would not be able to do this one in 1 day
