### ISSUE TITLE
[Bug] CLI doesn't allow to have a script in dependency (if module itself empty)

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#6003]
# 🐛 Bug

If I have a local package containing a script and then I use this local package as a dependency in another package (empty one) - I'm getting errors:

```
error: unbound module
  ┌─ /another-move-project/../sources/my_script.move:5:17
  │
5 │         assert!(signer::address_of(acc) == @0x1, 1);
  │                 ^^^^^^ Unbound module '(std=0x1)::signer'

{
  "Error": "Move compilation failed: extended checks failed"
}
```

## To reproduce

Create the package with a structure like this:

```
├── Move.toml
├── another-move-project
│   ├── Move.toml
│   └── sources
└── sources
    └── my_script.move
```

Put the following code in `my_script.move`:

```move
script {
    use std::signer;

    fun my_script(acc: &signer) {
        assert!(signer::address_of(acc) == @0x1, 1);
    }
}
```

In the `another-move-project` update `Move.toml` with local dependency:

```toml
[package]
name = 'EmptyPackage'
version = '1.0.0'

[dependencies.PackageWithScript]
local = '..'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
```

Try to compile `another-move-project` folder with Aptos CLI 1.0.3. 

```
aptos move compile
```

**Stack trace/error message**
```
error: unbound module
  ┌─ /Users/PycharmProjects/test-script-bug-aptos/another-move-project/../sources/my_script.move:5:17
  │
5 │         assert!(signer::address_of(acc) == @0x1, 1);
  │                 ^^^^^^ Unbound module '(std=0x1)::signer'

{
  "Error": "Move compilation failed: extended checks failed"
}
```

## Additional context

And I want to say why it can be important because, for example, a sub-package could have just tests (let's say we have a package only to run tests), and the result will be the same.

**Comment by davidiw** [comment]
humor me, does it work if you remove the 

What's in your Move.toml for PackageWithScript?

Is there a compiler issue with scripts :thinking: 

FWIW, this seems like an anti-pattern since the current compiler doesn't compile scripts to distinct names, it makes more sense to put each script into its own top-level package.

**Comment by wrwg** [comment]
Can you clarify whether the error is there? And if so please give content of all Move.toml files. Feel free to reopen with this information.
