### ISSUE TITLE
Aptos indexer memory leak

### ISSUE THREAD

**Issue by gabronick** [aptos-labs/aptos-core#6008]
# 🐛 Bug

the node crashes due to lack of memory, tested with 32Gb and 64Gb

## To reproduce

**Code snippet to reproduce**
FULLNODE.YAML

----------------------------
base:
    # Update this value to the location you want the node to store its database
    data_dir: "/external/aptos/data"
    role: "full_node"
    waypoint:
        # Update this value to that which the blockchain publicly provides. Please regard the directions
        # below on how to safely manage your genesis_file_location with respect to the waypoint.
        from_file: "/external/waypoint.txt"

execution:
    # Update this to the location to where the genesis.blob is stored, prefer fullpaths
    # Note, this must be paired with a waypoint. If you update your waypoint without a
    # corresponding genesis, the file location should be an empty path.
    genesis_file_location: "/external/genesis.blob"

full_node_networks:
    - discovery_method: "onchain"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6180"
      network_id: "public"
      # Define the upstream peers to connect to
      seeds:
        {}

api:
    enabled: true
    address: 0.0.0.0:8545
    
storage:
    enable_indexer: true
    # This is to avoid the node being pruned
    storage_pruner_config:
        ledger_pruner_config:
            enable: false

indexer:
    enabled: true
    postgres_uri: "postgres://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    processor: "default_processor"
    check_chain_id: true
    emit_every: 500
    
    ----------------------------

**Stack trace/error message**
DMESG:

[118252.628273] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=aptos.service,mems_allowed=0,global_oom,task_memcg=/system.slice/aptos.service,task=aptos-node,pid=1983072,uid=1000

[118252.628680] Out of memory: Killed process 1983072 (aptos-node) total-vm:36505660kB, anon-rss:31495152kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:65096kB oom_score_adj:0

## Expected Behavior

the node should work correctly

## System information

**Please complete the following information:**

Aptos Core Version: Origin/Testnet (d7fe6d2f68e6b25bddce8e13546e0b24076f47a5)
rustc 1.64.0
Ubuntu 22.04.1 LTS (X86_64), 3.5Tb NVME, 64Gb RAM, 16VCPU (instance H1.4XLARGE AWS)

## Additional context

node without indexer works fine

**Comment by gregnazario** [comment]
@bowenyang007 is there a memory leak here / has it been fixed?
