### ISSUE TITLE
'.' is not recognized as an internal or external command after using npm ci

### ISSUE THREAD

**Issue by Gojic** [aptos-labs/aptos-core#6017]
# 🐛 Bug

When i try to run npm ci like in documentation for example repo

**Code snippet to reproduce**
 after cloning example repo i try to run npm ci

**Stack trace/error message**
`1494 error code 1
1495 error path C:\Users\Milos\Documents\GitHub\axelar-local-gmp-examples\node_modules\@axelar-network\axelar-cgp-aptos
1496 error command failed
1497 error command C:\WINDOWS\system32\cmd.exe /d /s /c run-s build
1498 error > @axelar-network/axelar-cgp-aptos@1.0.2 build
1498 error > run-s build-aptos
1498 error
1498 error
1498 error > @axelar-network/axelar-cgp-aptos@1.0.2 build-aptos
1498 error > ./aptos/build.sh
1499 error '.' is not recognized as an internal or external command,
1499 error operable program or batch file.
1499 error ERROR: "build-aptos" exited with 1.
1499 error ERROR: "build" exited with 1.
1500 verbose exit 1
1501 timing npm Completed in 32626ms
1502 verbose unfinished npm timer reify 1672310036118
1503 verbose unfinished npm timer reify:build 1672310057010
1504 verbose unfinished npm timer build 1672310057012
1505 verbose unfinished npm timer build:deps 1672310057013
1506 verbose unfinished npm timer build:run:postinstall 1672310060516
1507 verbose unfinished npm timer build:run:postinstall:node_modules/@axelar-network/axelar-cgp-aptos 1672310060516
1508 verbose code 1`

## Expected Behavior

well i guess to get success message

## System information

**Please complete the following information:**
- Aptos Core Version dont know how o see this
- using node 16.15.0
- rustc 1.62.0
- win 11

**Comment by Helpcenter101** [comment]
@Gojic 'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/2dzBgxwuZoBaD3ab6

**Comment by gregnazario** [comment]
Can you point at the documentation that you're speaking of?  I'm assuming it's set up for Linux and not Windows / needs to be updated
