### ISSUE TITLE
aptos have an archive node

### ISSUE THREAD

**Issue by zhy827827** [aptos-labs/aptos-core#6024]
Aptos can deploy full-nodes, but I don't know whether archive nodes can be deployed?

**Comment by JoshLind** [comment]
You can, you just need to run a fullnode with the ledger pruner disabled, e.g., here: https://aptos.dev/guides/data-pruning/#disabling-the-ledger-pruner. Perhaps we should make this more obvious in the docs? 'cc @clay-aptos, thoughts?

**Comment by JoshLind** [comment]
@zhy827827, the docs have been updated to call this out: https://aptos.dev/guides/state-sync/#running-archival-nodes. Please let me know if there's anything missing, otherwise we can close this.

**Comment by davidiw** [comment]
Feel free to re-open if necessary.

**Comment by gustavsama** [comment]
Hi!

I'm looking into deploying a mainnet _archive_ node and a testnet _archive_ node. What are the storage requirements? How large are the chains with all data?
