### ISSUE TITLE
[network] better handle message size exceeds limit

### ISSUE THREAD

**Issue by zekun000** [aptos-labs/aptos-core#604]
network message size is limited by a config value today and the request would just fail to send/receive if it exceeds the limit. It's dangerous if there's no backoff approach on the application level e.g. if consensus block grows bigger than the limit, it'll just fail on broadcasting without a way to reduce the block size automatically.

we need to have a way to propagate this error to each component and handle it properly.

**Comment by gregnazario** [comment]
This is handled now right @zekun000 ?
