### ISSUE TITLE
[Bug] [Consensus] flaky consensus tests 

### ISSUE THREAD

**Issue by gelash** [aptos-labs/aptos-core#609]
On Apple M1 Max, cd aptos-core/consensus, cargo x test sometimes leads to the following two tests failing

test persistent_safety_storage::tests::test_waypoint_counters ... FAILED
test persistent_safety_storage::tests::test_safety_data_counters ... FAILED

MacOS Monterey (version 12.1)
rustup 1.24.3
git commit 63435610cbc5d9ed0e63aa15547b2ec3321158e1 on main branch

**Comment by zekun000** [comment]
@gelash if you still can reproduce, can you add some backtrace on the failures?

**Comment by gelash** [comment]
failures:

---- persistent_safety_storage::tests::test_waypoint_counters stdout ----
thread 'persistent_safety_storage::tests::test_waypoint_counters' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `3`', consensus/safety-rules/src/persistent_safety_storage.rs:277:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:182:5
   4: safety_rules::persistent_safety_storage::tests::test_waypoint_counters
             at ./src/persistent_safety_storage.rs:277:13
   5: safety_rules::persistent_safety_storage::tests::test_waypoint_counters::{{closure}}
             at ./src/persistent_safety_storage.rs:240:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    persistent_safety_storage::tests::test_waypoint_counters

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 10.04s

error: test failed, to rerun pass '-p safety-rules --lib'
        WARN [09:16:36.052] - Failed in 11861ms: "cargo" "test" "--package" "consensus" "--package" "consensus-types" "--package" "safety-rules"
Error: failed to run cargo command

**Comment by gelash** [comment]
One more observation is that I haven't been able to get them to fail when running individually, so the tests might be affecting each other?
