### ISSUE TITLE
[Docs] Add documentation for view function API

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#6119]
# Aptos Documentation Issue

## Location

This can likely be added to the existing API page - https://aptos.dev/guides/aptos-api. We can also consider adding it the integrator guide https://aptos.dev/guides/system-integrators-guide/

## Description

View function API was recently added and there's not a lot of documentation. We should add docs around:
1. Which endpoint can the user call? Some examples would be nice.
2. What the returned data looks like for different value types?

**Comment by clay-aptos** [comment]
Thanks! Let me know when you and Runtian are ready to work on this.

**Comment by clay-aptos** [comment]
Adding @movekevin as he offered to add the docs on the Move part separately in the Move doc.

**Comment by clay-aptos** [comment]
Hi @movekevin , @runtian-zhou and I have started work on this but need your Move work to continue. Please let us know when it has landed and where. Thanks!

**Comment by clay-aptos** [comment]
@runtian-zhou , @movekevin has supplied the following references:

Example - https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/coin.move#L226

Spec - https://github.com/aptos-labs/aptos-core/blob/main/api/doc/spec.yaml#L8513

I link to both from our shared doc. Please describe there how to employ them. Thanks!

**Comment by clay-aptos** [comment]
Hi team, I am starting these changes in:
https://github.com/aptos-labs/aptos-core/pull/6315

I have added @wrwg for his review. As I understand, we could still use guidance on writing Move code to include View functions, as well as the examples Kevin requested at the top. Over to @movekevin for next steps.

**Comment by clay-aptos** [comment]
One small fix coming:
https://github.com/aptos-labs/aptos-core/pull/6323
