### ISSUE TITLE
[Docs] Expand Window OS support across docs

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#6127]
# Aptos Documentation Issue

## Location

What are the existing URLs containing the issue, if any?

Many, especially dev and node docs.

## Description

How would you describe the issue?

Our survey results show we have a lot of Windows users. Yet we don't support them fully. See our setup script as but one example. See our node docs and use of `brew` for more.

**Comment by clay-aptos** [comment]
Adding @davidiw , @gregnazario and @sherry-x to help figure out access to Windows machines.

Adding @wintertoro , @perryjrandall and @michelle-aptos to create and test Windows nodes steps.

**Comment by gregnazario** [comment]
It's pretty easy to start up windows machines.  I would say we focus on development tooling first, then node running

**Comment by clay-aptos** [comment]
@christian-aptos is ready to work on this. @sherry-x or @CapCap , how would he get Parallels? Get and expense? Some corp setup?

**Comment by clay-aptos** [comment]
Christian, this needs the most Windows love:
https://aptos.dev/guides/getting-started#set-up-build-dependencies

**Comment by saharct** [comment]
@clay-aptos My Windows machine is arriving by the end of tomorrow, so I'll be able to start working on this next week.

**Comment by clay-aptos** [comment]
@saharct is getting set up for this.

**Comment by clay-aptos** [comment]
> 

This is fantastic news. Thank you, @saharct !

**Comment by clay-aptos** [comment]
How is it going, @saharct ?

**Comment by saharct** [comment]
Hi @clay-aptos , after a lot of testing I created a script that works on both Windows 10 and Windows 11. You can find it in [PR 6999](https://github.com/aptos-labs/aptos-core/pull/6999). I am in the process of making it work on Windows Server 2022 before expanding it to include operations and move prover dependencies. Please let me know if you have any feedback. Thanks!

**Comment by clay-aptos** [comment]
> Hi @clay-aptos , after a lot of testing I created a script that works on both Windows 10 and Windows 11. You can find it in [PR 6999](https://github.com/aptos-labs/aptos-core/pull/6999). I am in the process of making it work on Windows Server 2022 before expanding it to include operations and move prover dependencies. Please let me know if you have any feedback. Thanks!

Thanks, @saharct ! Let's get the script's use documented here and further tested:
https://aptos.dev/guides/getting-started#set-up-build-dependencies
