### ISSUE TITLE
[Contracts] Define and build a DAO

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#613]
There are a lot of different types of DAOs we could create:
* Online DAO with each member registered in a table (ACL)
* Offline DAO that uses our multisignature architecture -- though our current cryptography architecture is limited to 32
* Decentralized DAO that pushes to each member a voting capability
* Using a DAO currency to vote

Then DAOs can have some of the following features:
* Propose actions
* Vote on actions
* Remove votes on actions
* Execute actions that have passed

Some thing to figure out:
* Our DAO will likely be responsible for handling upgrades so
  * How does the action work (i.e., action would toggle a bit that lets a transaction upgrade the framework to the next version)
  * If we have a single utility currency, say TST, should that be used for system management or should we use another one?
  * If the same, then should delegation and staking give receipts so that active delegators and stakers can vote on upgrades

**Comment by chech-debug** [comment]
Amazing idea!
