### ISSUE TITLE
[Language] Prettier for Aptos Move

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#615]
Prettier is an opinionated code formatter that we should be adding to our system to find all ".move" files and applying it much like `cargo fmt`.

https://prettier.io/

it would also be great to share with the community

**Comment by magnum6actual** [comment]
Is there a "yes please!" label I can add to this?? :)

**Comment by wrwg** [comment]
There is ongoing work on a pretty printer in the Move repo. Moreover, a basic pretty printer has been added to the IntelliJ plugin from Pontem. Closing here.

**Comment by mshakeg** [comment]
Hi @wrwg are there any aptos move formatters/linters yet? couldn't find any

**Comment by wrwg** [comment]
The formatter is in beta testing, @vineethk or @rahxephon89 may provide a link to the tool.

**Comment by rahxephon89** [comment]
Hi @mshakeg, thank you for your interest in the formatter, which is currently in beta testing. You could find the instruction in the repo: https://github.com/movebit/movefmt to install and try it out. Please feel free to report issues in the movefmt repo. Thanks!
