### ISSUE TITLE
[DevEx Proposal] Example Proposal

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#6171]
# Context
- [Links to other relevant proposals / RFCs]
- [Links to previous issues]
- [Links to previous discussions]
- etc.

# Motivation

With the API as it is today, it is not possible for devs to write code that subscribes to changes on chain. Instead, they must poll the API for changes. Some problems with this include:
- The dapp will not know about the change as soon as it happens.
- The dapp might poll but nothing new has happened.
- The dapp must manage its own record of the latest state.

For example, a common use case for dapp development is to listen to events coming from a particular Move module. Today devs must roll their own stream-like abstraction for this.

# Proposals

To address this problem we should add streaming endpoints to the API. Some ideas for this include:

## gRPC streaming
Pros:
- Efficient representation of on-chain state as bytes.
- Typed message structure, enabling typed code generation.

Cons:
- Unusable out of the box, a custom client with protobuf support must be used.

## Websockets + JSON
Pros:
- Industry standard (at least in web3).
- Wide support in all languages.
- JSON messages are easily introspected.

Cons:
- JSON is not an efficient message format.
- No support for building typed requests / responses.

# Detailed proposal
Given the pros and cons above, I think we should go with gRPC streaming. Here is an example of what that would look like in terms of the protocol definition, client side, server side, etc.

<todo>

## FAQ

**Q:** Could we have both grpc streaming and websockets?
**A:** If there is sufficient demand, yes.

**Q**: What about asynchronous notifications?
**A**: We could consider webhooks for that if there is sufficient demand, see [link to other proposal]. If demand is light however, you can build a working notification system based on these streaming APIs.

**Comment by e99243506bigplay** [comment]
Websockets + BCS pls? and how about on AIP for this?

**Comment by MrReN** [comment]
we waited too long
