### ISSUE TITLE
Add documentation for running fullnodes on AWS and Azure

### ISSUE THREAD

**Issue by michelle-aptos** [aptos-labs/aptos-core#6185]
# Add documentation for running fullnodes on AWS and Azure

## Motivation

We have documentation for running fullnodes on source/docker and GCP but not for AWS and Azure

We should have multiple cloud provider options similar to our validator node docs

## Pitch

**Describe the solution you'd like**

Replicate this doc https://aptos.dev/nodes/full-node/run-a-fullnode-on-gcp/ for AWS and Azure

## Additional context

Refer to validator + VFN instructions:
https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-azure
https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-aws

Initial steps are the same but replace 'aptos-node' module with 'fullnode' module?

**Comment by clay-aptos** [comment]
Thanks, Michelle! We may even be able to make the GCP doc generic.

**Comment by michelle-aptos** [comment]
@clay-aptos yes defer to you on how to best organize this information!

**Comment by charlestonxorg** [comment]
Wip

**Comment by clay-aptos** [comment]
> @clay-aptos yes defer to you on how to best organize this information!

Thanks! Just let me know when we have the basic steps nailed down, and I will help.

**Comment by clay-aptos** [comment]
I agree this is still a priority, although @davidiw may disagree. :-) Removing the stale tag to keep this open for hopeful, eventual time to work on Node docs.

**Comment by michelle-aptos** [comment]
@abbyxion is working on something related to this

**Comment by clay-aptos** [comment]
I am adding @JoshLind for guidance on prioritizing and perhaps getting help on this. Thanks, Josh!
