### ISSUE TITLE
[VM] Gas model

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#619]
The existing gas schedule in Move is from 2019.
There is no code to generate a new gas schedule.
There is no formula or way to predict gas for a given transaction
There are no estimations for what might be an upper bound for gas
The gas schedule is part of [upstream move](https://github.com/move-language/move/blob/2ab0b168c28504a3a586e64f9ae10f97f4b40b69/language/move-vm/types/src/gas_schedule.rs)
Integration with storage is murky (storing resources is expensive, modules is cheap)
There's no gas estimation api.

Let's fix all of these! And also give folks an API to validate their transaction with their own fullnode without going through consensus!

**Comment by Manahip** [comment]
We made a transaction simulation feature here which gives relatively accurate gas estimate (gets the entire write set, actually): https://github.com/hippospace/aptos-core/commit/f0015a4b96b1455c58ca274a775a8a83a55b3998. Totally agree that `borrow_global` is way too expensive.

**Comment by davidiw** [comment]
@Manahip, WOW, submit a PR, please?

**Comment by Manahip** [comment]
Will do once I figure out how you guys generate stuffs under ecosystem/typescript/api

**Comment by davidiw** [comment]
> Will do once I figure out how you guys generate stuffs under ecosystem/typescript/api

No worries about that as long as it doesn't result in any broken tests and it can make it through our CI :)

**Comment by Manahip** [comment]
here it is: https://github.com/aptos-labs/aptos-core/pull/1358

**Comment by davidiw** [comment]
New gas model on the way, closing this out.
