### ISSUE TITLE
[Feature Request] List certain generic structs in global storage

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#6192]
# 🚀 Feature Request

Add `list` as a global storage operator that lists all structs of a certain type.

## Motivation

**Is your feature request related to a problem? Please describe.**

Let's say I store `LiquidityPool<CoinType>` in the global storage. Currently, there is no way to tell what `LiquidityPool` I have stored in the global storage (BTC? ETH? APT?), without using extra data structures to keep track of the info. A `list<LiquidityPool<?>>` operation is what I kinda want (however the ideal return type is unclear to me)

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by davidiw** [comment]
Could you elaborate on why a transaction would need access to this? It seems more likely that whatever generates your transaction can do this more effectively than we can do this in Move.

**Comment by lbmeiyi** [comment]
This will be supported in Token V2. Confirmed with Kevin.
