### ISSUE TITLE
[Docs] Verify and document validator node setup flow

### ISSUE THREAD

**Issue by rustielin** [aptos-labs/aptos-core#6193]
# Aptos Documentation Issue

## Location

https://aptos.dev/nodes/validator-node/operator/connect-to-aptos-network
and
https://aptos.dev/nodes/validator-node/operator/staking-pool-operations

## Description

Imply some sort of dependency between "Connecting to Aptos Network" and "Staking Pool Operations". 

When the docs are followed out of order, the validator will not be valid. For example, if you spin up a validator without following the steps in "Connecting to Aptos Network" first (e.g. deleting secure-data.json and replacing the validator-identity and valiator-fullnode-idenity with your pool address), and jump straight to "Staking Pool Operations", your node will be set up incorrectly. Some success metrics may be good (state sync will be making process, and you will have peers, after joining the validator set), but consensus will not be working correctly

At the minimum, probably a note at the top of "Staking Pool Operations" is sufficient, with a warning like: Did you make sure your node has been started with validator-identity and validator-fullnode-identity addresses as your staking pool address?

## Audience

Validator ndoe operators

**Comment by clay-aptos** [comment]
Thanks, Rustie. It sounds like we need to also include this flow in the validator setup and update docs:

https://aptos.dev/nodes/validator-node/operator/index

https://aptos.dev/nodes/validator-node/operator/update-validator-node

**Comment by rustielin** [comment]
@clay-aptos Yea I think on the index page, include it under the "Detailed steps" header:
1. Read the node requirements...
2. Deploy the node
  a.  Probably in this page, note that your nodes will not be running correctly (not syncing, not participating in consensus), until they're added to the validator set (refer to step 4). This is expected though, as this step is mainly for bringing up the infrastructure
3. Run through the steps in https://aptos.dev/nodes/validator-node/operator/connect-to-aptos-network/ to prepare your validator to join the network
4. Then only after running the steps in https://aptos.dev/nodes/validator-node/operator/staking-pool-operations to join the validator set, will your node actually start syncing and participating 

It's a bit confusing of a flow since you have to jump between a few pages (and has a lot of back-references). If you want, I can take a stab at it first

**Comment by clay-aptos** [comment]
Hi @rustielin and @michelle-aptos , please see progress in:
https://github.com/aptos-labs/aptos-core/pull/6214

Thanks!

**Comment by clay-aptos** [comment]
Updating the subject to show the new scope as requested in:
https://github.com/aptos-labs/aptos-core/pull/6214#discussion_r1072701833
