### ISSUE TITLE
[Docs] Link to JSON-RPC client 404

### ISSUE THREAD

**Issue by dr497** [aptos-labs/aptos-core#6197]
# Aptos Documentation Issue

## Location

https://github.com/aptos-labs/aptos-core/blob/main/sdk/README.md

## Description

The link to `JSON-RPC client` leads to https://github.com/aptos-labs/aptos-core/blob/master/json-rpc/json-rpc-spec.md which does not exist (or is private)

## Audience

Developers

**Comment by clay-aptos** [comment]
@jjleng and @gregnazario , shouldn't this be REST anyway? And link to:
https://aptos.dev/nodes/aptos-api-spec#/

If not, what is the correct target for this [JSON-RPC client](https://github.com/aptos-labs/aptos-core/blob/master/json-rpc/json-rpc-spec.md) link?

If so, should we replace all references to JSON-RPC? See another example of a broken link in the Glossary here:
https://aptos.dev/reference/glossary/#mempool

**Comment by jjleng** [comment]
This is a very very old doc. Definitely out of date. Will defer this to @gregnazario to decide if we want to delete or update this doc.

**Comment by gregnazario** [comment]
This is old, we can update to REST client, and point to the aptos.dev site
