### ISSUE TITLE
[bug][example] in the "hello_blockchain"

### ISSUE THREAD

**Issue by vladimirovmm** [aptos-labs/aptos-core#620]
Hello. You seem to have a typo in the example

https://github.com/aptos-labs/aptos-core/blob/cc5774c4584f24f8fb587bdbe8e4119d42f67eb8/developer-docs-site/static/examples/rust/hello_blockchain/src/main.rs#L29-L30

**Output:**

> === Initial Balances ===
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `404`,
>  right: `200`: {"code":404,"message":"account not found by address(0x161b1a7f396264254ae29831efb8bc9043db263836e8de7a83423b37781e2c80) and ledger version(571260)","aptos_ledger_version":"571260"} - 161b1a7f396264254ae29831efb8bc9043db263836e8de7a83423b37781e2c80', first_transaction/src/lib.rs:96:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If you replace it with the code from "first_transaction", then it will work. 
https://github.com/aptos-labs/aptos-core/blob/cc5774c4584f24f8fb587bdbe8e4119d42f67eb8/developer-docs-site/static/examples/rust/first_transaction/src/main.rs#L19-L20

**pub_key** -> **auth_key** 
or 
**pub_key** -> **address** 

``` rust
faucet_client.fund_account(&alice.auth_key().as_str(), 10_000_000);
faucet_client.fund_account(&bob.auth_key().as_str(), 10_000_000);
```

But the string "Hello, Blockchain" is not returned, as indicated in the example. Returns "None"

https://github.com/aptos-labs/aptos-core/blob/cc5774c4584f24f8fb587bdbe8e4119d42f67eb8/developer-docs-site/docs/tutorials/first-move-module.md?plain=1#L273

Please check your example. 
Thanks

**Comment by maxi-zhang** [comment]
Yes，this is a bug.
Did you compile the HelloBlockchain.move to binary Message.mv ?
and change  aptos-core/aptos-move/move-examples/Move.toml  address to Alice's address.
then you'll get the right output

**Comment by vladimirovmm** [comment]
@maxi-zhang Thank you. It work with **Dove 1.7.1-bc80107**


```bash
cd ./aptos-core/developer-docs-site/static/examples/rust/hello_blockchain
cargo run -- ./aptos-core/aptos-move/move-examples/build/Examples/bytecode_modules/Message.mv
```

> === Addresses ===
> Alice: 0x903318cceacb1342efa35f043247ca3c361c2f3df6ad374317b9a67a9626067f
> Bob: 0x56139dad9bee8eae23c244e579de658b04ad335cfd3eebf442de3df05ecb714b

Replaced the address with "**0x903318cceacb1342efa35f043247ca3c361c2f3df6ad374317b9a67a9626067f**"

https://github.com/aptos-labs/aptos-core/blob/3ac7c04d0bb6764cddf74f0940b5ee64fa8bb742/aptos-move/move-examples/Move.toml#L6

```bash
cd ./aptos-core/aptos-move/move-examples/
rm -r build
dove build
```
Continued execution of "hello_blockchain"

Output:
> === Testing Alice ===
> Publishing...
> Initial value: None
> Setting the message to "Hello, Blockchain"
> New value: Some("Hello, Blockchain")
> 
> === Testing Bob ===
> Initial value: None
> Initial value: None
> Setting the message to "Hello, Blockchain"
> New value: Some("Hello, Blockchain")

-------------------------------

Not work with move-cli https://github.com/diem/move/tree/main/language/tools/move-cli

> Error: Error parsing '[addresses]' section of manifest
> 
> Caused by:
>     0: Invalid address '0x903318cceacb1342efa35f043247ca3c361c2f3df6ad374317b9a67a9626067f' encountered.
> 
>     1: Unable to parse AccountAddress (must be hex string of length 16)
