### ISSUE TITLE
[Bug] postgres's password is printed to logger

### ISSUE THREAD

**Issue by fgfm999** [aptos-labs/aptos-core#6206]
# 🐛 Bug

Aptos will log  Postgres password when indexer is enabled

## To reproduce

1. Prepare a Postgres instance with a password
2. Start node with Indexer enabled
3. There two places which print the `NodeConfig`

https://github.com/aptos-labs/aptos-core/blob/35976bfa00bc06d376285da38739ee86f8a96d75/aptos-node/src/lib.rs#L126
```
Using node config NodeConfig { base: BaseConfig........ 
indexer: IndexerConfig { enabled: true, postgres_uri: Some("postgres://postgres:11111111@172.17.0.3:5432/postgres")
```

https://github.com/aptos-labs/aptos-core/blob/35976bfa00bc06d376285da38739ee86f8a96d75/aptos-node/src/logger.rs#L80
```
{"level":"INFO","source":{"package":"aptos_node","file":"aptos-node/src/lib.rs:221"},"thread_name":"main","hostname":"a678817f8a36","timestamp":"2023-01-16T05:23:57.894680Z","message":"Loaded AptosNode config","data":{"config":{"base"
......
"indexer":{"enabled":true,"postgres_uri":"postgres://postgres:11111111@172.17.0.3:5432/postgres"
```

## Expected Behavior

The password should be masked or hidden.

If this is not a issue , feel free to close this issue

**Comment by vivekascoder** [comment]
Can this be done without implementing the `Debug` trait for `NodeConfig`?
