### ISSUE TITLE
[Docs] Storage Size Archive Node for Mainnet and Testnet

### ISSUE THREAD

**Issue by gustavsama** [aptos-labs/aptos-core#6210]
# Aptos Documentation Issue

Hi,

It would be great to share how much storage is required to run a mainnet _archive_ node and a testnet _archive_ node? In the [documentation](https://aptos.dev/nodes/validator-node/operator/node-requirements) it's well described the recommended hardware requirements for a _full_ node, but not for an _archive_ node. 

Storage size is important information to know for node operators. You would want to know this information in advance before one deploys an archive node in a public node, because it could be very expensive in the storage requirements are extensive.

**Comment by msmouse** [comment]
Storage requirement for the full history of the blockchain is indefinite. Atpos's official explorers and solutions will be backed by data source other than a node with out the ledger pruner (so called "archive node"), the technology will be opened once matured. But currently the full DB size is less than 200GB.

**Comment by clay-aptos** [comment]
Asking @JoshLind and @bowenyang007 for guidance. Shall we say start with 1TB and expect constant growth?

**Comment by clay-aptos** [comment]
I think we agreed this is an ever-growing number. @gustavsama , would it help to have that answer in the docs?

**Comment by gustavsama** [comment]
@clay-aptos I think it would be great to state that in the docs, and also state what the current storage size is when the doc is updated.

**Comment by clay-aptos** [comment]
> @clay-aptos I think it would be great to state that in the docs, and also state what the current storage size is when the doc is updated.

Let's see if this works:
https://github.com/aptos-labs/aptos-core/pull/7001
