### ISSUE TITLE
[Docs] Document Aptos Unity SDK throughout

### ISSUE THREAD

**Issue by chrispmonkey** [aptos-labs/aptos-core#6217]
# Aptos Documentation Issue

## Location

Currently, there is no documentation about the upcoming SDK. It is actively being built. It should accompany the other Aptos SDKs here https://aptos.dev/sdks/index

## Description

We have an upcoming SDK that will be coming out soon, and we need documentation to accompany it. 

We need the existing Aptos SDK documentation updated to include a new SDK for Unity which will also be available in the Unity Asset Store.

The SDK should have detailed and extensive documentation. The overview of the solution should define supported Unity streams and platforms. If some graphics pipelines (HDRP, URP, Built-in) or scripting backends (Mono, IL2CPP) are not supported, have limitations, or require different setup steps, this also needs to be mentioned. 

The documentation should detail the integration process and all the features available to the user, making sure to include examples when possible. All publicly available and intended-for-use APIs should be documented, with descriptions of passed and returned parameters as well as all possible Exceptions that could be thrown. Core APIs could also have examples documented of how they should be used. 

If known issues could be invasive or affect a large portion of the user base, they need to be documented alongside any available workarounds. 

Product changes need to be tracked in a changelog; this will give insight to users and help speed up the VS verification process, especially if the solution needs to be re-verified. The changelog should include descriptions of newly added and updated features and any bug fixes done in each version.

## Audience

Developer, Programmer, Engineer, Game Developer, Game Designer, Game Programmer, Blockchain Game Developer, Blockchain Game Engineer, Game Producer, Unity Engineer, Unity Programmer, Software Engineer

The audience should be able to add the Aptos Unity SDK to either a new or existing Unity project.

## Additional context

We will possibly be able to add a demo video and reference application 

Private repository https://github.com/aptos-labs/unity-sdk
Documentation needs to align to the Unity Asset Store technical solutions review document: https://docs.google.com/document/d/1bRJrmRIKQC5atYFsHn5ZJQkAhYMzZYUr_0_FJANaoos/edit

**Comment by clay-aptos** [comment]
Thanks for the detailed set of requirements, @chrispmonkey! From Slack, I will include some starter recommendations:

1. Review our existing SDK docs: https://aptos.dev/sdks/index 
2. Update the accompanying tutorials to include Unity support: https://aptos.dev/tutorials/aptos-quickstarts
3. See the API-related templates here for starting points on newly created docs: https://github.com/thegooddocsproject/templates
4. Attempt to offer auto-generated reference docs from source. Perhaps from:
https://github.com/NormandErwan/DocFxForUnity

Let's do this!

**Comment by clay-aptos** [comment]
Adding @kPatch and @cricel here for review. @chrispmonkey and @CapCap.

1. Here is the first PR to get a Unity SDK page onto Aptos.dev:
[LINK](https://github.com/aptos-labs/aptos-core/pull/6292)

2. Once the package is live and announced, we will then add that file to the SDKs list and navigation and announce it in See what's new:
https://aptos.dev/sdks/index/
https://aptos.dev/whats-new-in-docs

3. Next up, I am requesting the Eng team help update the tutorials to include Unity support and examples starting with:
https://aptos.dev/tutorials/your-first-transaction/

4. Then hopefully:
https://aptos.dev/tutorials/your-first-coin

5. We should also generate reference materials for the SDK, akin to:
https://aptos-labs.github.io/ts-sdk-doc/

Please let me know if you have questions. Thanks!

**Comment by clay-aptos** [comment]
Hi @chrispmonkey , I have added a section on user flows from the video demo you sent me. Thanks!

I am also moving these TODOs from the PR to this issue (by section):

Prerequisites
TODO: Do we ned to guide them on finding these packages or specify verions supported?

Install by Unity Package Manager
TODO: Explain what the GitHub URL should be above or include it directly.

Please let me know next steps. Again, we will want to add this file to navigation and announce in See what's new when ready. Thanks again!

**Comment by clay-aptos** [comment]
Reopening to edit the Unity SDK README.

**Comment by clay-aptos** [comment]
I made my edits to the README in:
https://github.com/aptos-labs/Aptos-Unity-SDK/commit/7066b5e14d9ff1e38136bbbc656aafb122d47837
