### ISSUE TITLE
[Docs] Explain CONSTRAINT_NOT_SATISFIED

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#6232]
# Aptos Documentation Issue

## Location

We should add an explanation of `CONSTRAINT_NOT_SATISFIED` in https://aptos.dev/guides/handle-aptos-errors/#move-virtual-machine-vm.

## Description

As above.

## Audience

dapp devs

## Additional context
N/A

**Comment by clay-aptos** [comment]
Thanks, Daniel. Adding @gregnazario for guidance.

**Comment by gregnazario** [comment]
We need to put more description on the errors page

**Comment by wrwg** [comment]
Instead of documenting every error, the error message should be more descriptive.
