### ISSUE TITLE
[Feature Request] abort earlier when executing a transaction if the signature doesn't match 

### ISSUE THREAD

**Issue by 0xchloe** [aptos-labs/aptos-core#6237]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment]
Abort earlier than what? Please a bit more context.

**Comment by movekevin** [comment]
This is actually currently checked as part of validation in the fullnode mempool so the submit_transaction API request would actually still fail if the signature is invalid.
