### ISSUE TITLE
[Bug] Create Account in CLI requires chain id when using faucet

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#624]
# 🐛 Bug

It should not require chain id since it isn't used.

## To reproduce

**Code snippet to reproduce**
```rust
$ aptos account create --use-faucet --public-key-file ~/test.pem.pub
error: The following required arguments were not provided:
    --chain-id <CHAIN_ID>

USAGE:
    aptos account create --chain-id <CHAIN_ID> --use-faucet --public-key-file <PUBLIC_KEY_FILE>


```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by gregnazario** [comment]
This can be cleaned up by not reusing write-transaction-options https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos/src/account/create.rs#L23-L37

Additionally could probably get the chain id for people and not require it.

**Comment by kris524** [comment]
Hello, can I pick this issue? 😊

**Comment by davidiw** [comment]
Do it, note that it will require changes to terraform for faucet, docker compose for testnet, as well as the aptos-faucet crate.

**Comment by gregnazario** [comment]
Hi, sorry about this, but I removed the need for ChainId entirely in the latest changes, and this no longer applies
