### ISSUE TITLE
[Feature Request] clearer error report when running Move tests

### ISSUE THREAD

**Issue by 0xchloe** [aptos-labs/aptos-core#6247]
# 🚀 Feature Request
Ambiguous errors - I eventually figured out that I forgot to declare a test, but would be nice to have clearer errors. 

<img width="576" alt="Screen Shot 2023-01-18 at 3 53 06 PM" src="https://user-images.githubusercontent.com/79347459/213322571-e1497f3a-886b-4bb1-a6ec-ab63da094def.png">

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by brmataptos** [comment]
@wrwg clarifies: Looks to me like a #[test-only] function is called from regular code, which is compiled as part of package publishing, when testing is not enabled.

Which seems like something that we can't fix.  You can't please everyone.

**Comment by brmataptos** [comment]
Closing.
