### ISSUE TITLE
how to integrate my new wallet on https://aptoslabs.com/testnet-faucet like martian,pontem,petra... ? 

### ISSUE THREAD

**Issue by ShaYha271097** [aptos-labs/aptos-core#6254]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by davidiw** [comment]
Will bring back to team -- we hope we can get rid of web-site based faucets and move back to an open one...

**Comment by gregnazario** [comment]
Looks like we just need to add documentation on how to integrate with the faucet

**Comment by clay-aptos** [comment]
I am asking @saharct to take a look as this is related to ongoing work to document funding now tracked in:
https://github.com/aptos-labs/aptos-core/issues/7067

**Comment by saharct** [comment]
Hi @ShaYha271097, we are expanding the integrator's guide to describe how wallet / SDK developers can integrate with the faucet. You can follow along in [PR 7293](https://github.com/aptos-labs/aptos-core/pull/7293). Feel free to provide feedback. Thanks!
