### ISSUE TITLE
[Bug] How to construct 0x1::code::PackageMetadata to publish module package?

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#6278]
https://github.com/aptos-labs/aptos-core/blob/f279d68ba1f69136166fc2e6789b98a4fc9e8949/aptos-move/framework/aptos-framework/sources/code.move#L132

If developer is going to customize publish_package, then how are they able to construct `0x1::code::PackageMetadata` ?

**Comment by davidiw** [comment]
Could you elaborate? Right now, we expect users to build both of these using the CLI, we don't support other methods. It also isn't clear to me why anyone would want to modify the package metadata?

**Comment by e99243506bigplay** [comment]
> Could you elaborate? Right now, we expect users to build both of these using the CLI, we don't support other methods. It also isn't clear to me why anyone would want to modify the package metadata?

For example, by using multi signer transactions and custom move script to publish package, so main account to pay the gas fee, sub account to deploy the contract without touch sub account sequence number.

Sorry, Probably that is be rare case, not worth be improve.

**Comment by wrwg** [comment]
Notice that with `aptos move compile --save-metadata` the package metadata will be stored to disc from where it can be picked up for custom publishing flows.
