### ISSUE TITLE
[Feature Request] Please let "./aptos move download" to support ledger version option.

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#6279]
# 🚀 Feature Request

Currently, I am try to downloading contract code, however it on current version that module package do not expose any source code, but in history they are exposed their module package source code, so if we could support ledger_version on `./aptos move download --ledger_version` then we could download module packages history source code on chain.

## Motivation

**Is your feature request related to a problem? Please describe.**

Aptos CLI can't download move contract history source code on chain.

## Pitch

**Describe the solution you'd like**

Support to specify `./aptos move download --ledger_version` option

**Describe alternatives you've considered**

Hardcoded the option for hack.
MITM attack.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
That is difficult for me for this moment, so no.

**Comment by wrwg** [comment]
Duplicate of #5279
