### ISSUE TITLE
[Bug] Get rid of the step of increasing tx size limit to keep things more consistent between testnet or mainnet

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#6284]
# 🐛 Bug

Currently when generating upgrade scripts, the release CLI also generates an extra step to increase the tx size limit. This is required in testnet as we don't go through the full governance proposal process (which automatically whitelists a proposal tx to exceed the default limit). We should look into removing this requirement in testnet so we can keep the release process as similar in testnet and mainnet as possible

**Comment by runtian-zhou** [comment]
I think we can close this issue now that the tool can send multi-step proposals to a testnet
