### ISSUE TITLE
[Docs] Update State Sync page to highlight use cases for different sync modes

### ISSUE THREAD

**Issue by michelle-aptos** [aptos-labs/aptos-core#6308]
# Aptos Documentation Issue

## Location

https://aptos.dev/guides/state-sync/

## Description

We say this "The below sections provide instructions for how to configure your node for different use cases" under state sync modes but don't associate the use cases.

1. Someone wants to process all data since genesis. Then, use txn execution or output application. **This is useful for indexer builders.**
2. Someone just wants to bring a node up quickly and doesn't require processing all data. Then, use fast sync. **This is probably useful for folks who care more about querying the latest state of the blockchain and less about historic data.**

Another flow is for troubleshooting when a node stops syncing:

1. First try enabling output syncing mode 
2. Then try fast sync
3. etc.

**Comment by michelle-aptos** [comment]
adding @JoshLind for additional sync modes

**Comment by e99243506bigplay** [comment]
Are we unable to switch different sync modes now? At least I can't do execute sync mode from version 0 by using latest version of Aptos Node.
#5997 #5692

**Comment by clay-aptos** [comment]
@JoshLind thankfully took care of this:
https://github.com/aptos-labs/aptos-core/pull/6649

Closing out.
