### ISSUE TITLE
[Docs] Create Contribute section and highlight internal and external contributions

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#6311]
# Aptos Documentation Issue

We need to create a *Contribute* section with Josh to include pages on:

* Highlights for external contributions
* Research papers
* Examples summarizing:
https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/move-examples 
* Specifications in our `documentation/` subdirectory
* Help for contributors to update docs and code (see: https://github.com/aptos-labs/aptos-core/issues/6310)

## Location

What are the existing URLs containing the issue, if any?

N/A

Where should this information land if new? (Start Aptos, Build Apps, Run Nodes, Reference, etc.)

This will be an entirely new section, which may reside under Reference until we have the pages to justify a distinct tab.

## Description

How would you describe the issue?

We need to highlight more of our existing materials while creating a clear path for more, from both internal and external contributors.

## Audience

Who is the audience for that information? (App developers, investors, creators, validators, someone else?)

Internal and external contributors.

What precisely must they do with it? (Configure a new service? Process some output?

Learn from our deeper docs and contribute new tutorials.

**Comment by clay-aptos** [comment]
Throwing a line out to @JoshLind and @banool , two of my favorite co-conspirators, I mean contributors. ;-)

**Comment by clay-aptos** [comment]
Here are some models for:
https://developer.algorand.org/tutorials/

**Comment by clay-aptos** [comment]
Here is another candidate:
https://forum.aptoslabs.com/t/transfer-validator-node-to-other-server-no-fn-required/194629

Any objections to linking that from the proposed Highlights list in?
https://github.com/aptos-labs/aptos-core/pull/6417
https://deploy-preview-6417--aptos-developer-docs.netlify.app/contribute/community-highlights

**Comment by michelle-aptos** [comment]
Can we also add a page for "community resources"? 

This would be a list of services that node operators provide (i.e. fullnodes, APIs, etc). They should pull a PR to add to the page and we should have a disclaimer that the services are not endorsed by Aptos.

**Comment by clay-aptos** [comment]
Hi @michelle-aptos , I have updated the following PR to include that new page, labeled External Resources to disambiguate from the proposed Community Highlights already here:
https://github.com/aptos-labs/aptos-core/pull/6417

Please you and @JoshLind let me know if that table and the intro text is what you had in mind. Thanks for the input!

**Comment by clay-aptos** [comment]
Here is another external resource from Tom and team we should include:
https://medium.com/mokshyaprotocol/write-your-first-smart-contract-on-aptos-a-step-by-step-guide-e16a6f5c2be6

**Comment by clay-aptos** [comment]
I am noting we will want to move and link to the Remix IDE contents in from the Community Highlights page:
https://github.com/aptos-labs/aptos-core/pull/6458#pullrequestreview-1313887937

And these resources from the Contribute index:
https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md
https://github.com/aptos-labs/aptos-core/blob/main/CODE_OF_CONDUCT.md
https://aptos.dev/guides/move-guides/book/coding-conventions

**Comment by clay-aptos** [comment]
Moving some TODOs from PR to this issue:

Restore these entries to the Community Highlights table, replace PRs with relative links, and of course update the dates:

```
| [Multisig Python SDK tooling and tutorial](https://github.com/aptos-labs/aptos-core/pull/6788) | This tutorial introduces assorted [K-of-N multi-signer authentication](../../concepts/accounts.md#multi-signer-authentication) operations | [alnoki](https://github.com/alnoki) | 2023-03-06 |
| [Remix IDE plugin for Move](https://github.com/aptos-labs/aptos-core/pull/6458) | This tutorial describes a plugin that can develop you develop Aptos Move modules with the Remix IDE. | [0xhsy](https://github.com/0xhsy) | 2023-03-02 |
```

Update Multisig and Remix IDE with live documents once in place. Note Multisig is landing in two parts:
https://github.com/aptos-labs/aptos-core/pull/6788/
https://github.com/aptos-labs/aptos-core/pull/6356
Also announce in See what's new as sub-bullets of each page announcement.
