### ISSUE TITLE
[Docs] Edit, test and publish tutorial on how to build an e2e dapp on Aptos

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#6312]
# Aptos Documentation Issue

@0xmaayan has written an incredible doc internally we should take public. The title: how to build an e2e dapp on Aptos

She is having others in Engineering review the document internally.

Once that is done, we should take it public. This issue tracks that work.

**Comment by clay-aptos** [comment]
Reopening to announce this bad boy and get it in upper navigation. Fantastic work, @0xmaayan. Thank you!

**Comment by 0xmaayan** [comment]
> Reopening to announce this bad boy and get it in upper navigation. Fantastic work, @0xmaayan. Thank you!

thanks @clay-aptos ! I have this open PR to add the tutorial to the upper navigation https://github.com/aptos-labs/aptos-core/pull/6386

**Comment by clay-aptos** [comment]
> > Reopening to announce this bad boy and get it in upper navigation. Fantastic work, @0xmaayan. Thank you!
> 
> thanks @clay-aptos ! I have this open PR to add the tutorial to the upper navigation #6386

Thanks so much, @0xmaayan ! This LGTM. May I ask if you want me to fix the spelling in the tutorial directory we have on the index page:
https://github.com/aptos-labs/todolist-dapp-toturial

If not, I will take of this while announcing. Thanks for making that directory public!

**Comment by 0xmaayan** [comment]
> > > Reopening to announce this bad boy and get it in upper navigation. Fantastic work, @0xmaayan. Thank you!
> 
> > 
> 
> > thanks @clay-aptos ! I have this open PR to add the tutorial to the upper navigation #6386
> 
> 
> 
> Thanks so much, @0xmaayan ! This LGTM. May I ask if you want me to fix the spelling in the tutorial directory we have on the index page:
> 
> https://github.com/aptos-labs/todolist-dapp-toturial
> 
> 
> 
> If not, I will take of this while announcing. Thanks for making that directory public!

I think I fixed it..? I fixed the repo name, is there another place we have this typo?

**Comment by clay-aptos** [comment]
> > > > Reopening to announce this bad boy and get it in upper navigation. Fantastic work, @0xmaayan. Thank you!
> > 
> > 
> > > 
> > 
> > 
> > > thanks @clay-aptos ! I have this open PR to add the tutorial to the upper navigation #6386
> > 
> > 
> > Thanks so much, @0xmaayan ! This LGTM. May I ask if you want me to fix the spelling in the tutorial directory we have on the index page:
> > https://github.com/aptos-labs/todolist-dapp-toturial
> > If not, I will take of this while announcing. Thanks for making that directory public!
> 
> I think I fixed it..? I fixed the repo name, is there another place we have this typo?

It's in the tip here:
https://aptos.dev/tutorials/build-e2e-dapp/e2e-dapp-index

Let me fix it as I need to announce this awesome documentation anyway. :-)

**Comment by clay-aptos** [comment]
Hi @0xmaayan , here is the PR to announce and fix:
https://github.com/aptos-labs/aptos-core/pull/6396

I added links to prerequisites too for ease of use.

Finally, I wonder whether we should link to the files landing in:
https://github.com/aptos-labs/aptos-core/pull/6381

Just let me know. Thanks!

**Comment by 0xmaayan** [comment]
> Hi @0xmaayan , here is the PR to announce and fix: #6396
> 
> I added links to prerequisites too for ease of use.
> 
> Finally, I wonder whether we should link to the files landing in: #6381
> 
> Just let me know. Thanks!

I think we can ignore https://github.com/aptos-labs/aptos-core/pull/6381 for now and use the repo the tutorial is pointing to. @movekevin wanted this template in aptos-core for a future feature. Once it lands, we can think on whether we want to use it for the tutorial also.

**Comment by clay-aptos** [comment]
> I think we can ignore #6381 for now and use the repo the tutorial is pointing to. @movekevin wanted this template in aptos-core for a future feature. Once it lands, we can think on whether we want to use it for the tutorial also.

Thanks, @0xmaayan ! Understood.
