### ISSUE TITLE
[Docs] Document use of scripts in Aptos

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#6318]
# Aptos Documentation Issue

We need to explain how we expect scripts to be used in Aptos. They are powerful yet not truly leveraged in our instructions.

## Location

What are the existing URLs containing the issue, if any?

We have only this:
https://aptos.dev/reference/glossary#transaction-script

This is from NFT creator feedback last week.

Asking @gregnazario and @movekevin for starting points and a partner in docs. Thanks!

**Comment by gregnazario** [comment]
This is huge, maybe we can knock this out soon or I will on the plane to Korea

**Comment by movekevin** [comment]
We should include the following details:

- Scripts
    - Constraints
        - cannot have multiple scripts in the same directory / Move.toml
        - put a script in a normal package with modules???
    - Use cases
        - Do multiple things atomically without having to deploy a module

**Comment by alnoki** [comment]
@clay-aptos @gregnazario @movekevin PR #6356 adds a Move script example, within the context of multisig governance operations. It demonstrates script arguments and provides a commentary of how scripts streamline the multisig governance process.

**Comment by clay-aptos** [comment]
@alnoki , this is a thing of beauty. Making another pass now. Related, see my (still draft) attempts to recognize you and other community members for direct contributions to our knowledge set:
https://github.com/aptos-labs/aptos-core/pull/6417
https://deploy-preview-6417--aptos-developer-docs.netlify.app/contribute/community-highlights

I would love to add your multisig work there along with How Base Gas Works, if that makes sense.

**Comment by clay-aptos** [comment]
Let's also see if we can compile a definition for scripts in Aptos and then link to the multisig doc as an example of use. What do you think, @gregnazario ? Can you help?

**Comment by clay-aptos** [comment]
@alnoki thankfully made this happen in:
https://github.com/aptos-labs/aptos-core/pull/6788

I am announcing it now and getting it on the Community Highlights page.

**Comment by clay-aptos** [comment]
We announced the multisig tutorial:
https://aptos.dev/whats-new-in-docs#19-march-2023

And highlighted it:
https://aptos.dev/community/contributions/community-highlights

Now I am seeing if we should link to it as an example from the Transaction script definition in our glossary with:
https://github.com/aptos-labs/aptos-core/pull/7409

I am asking @movekevin and @gregnazario to take a look. Thank you!

**Comment by clay-aptos** [comment]
I am noting @banool has Move Scripts docs on the way in:
https://github.com/aptos-labs/aptos-core/pull/7449

I am wondering the difference between those and:
https://aptos.dev/reference/glossary#transaction-script

Should we create a distinct Move Script definition that links out to the new doc?

Regardless, Daniel we should also announce your new doc in See what's new. I will do that. Thank you!

**Comment by banool** [comment]
Good question. It sounds like a Move script to me by a different name.

**Comment by clay-aptos** [comment]
> Good question. It sounds like a Move script to me by a different name.

@movekevin and team, should we rename Transaction script in the glossary to simply Script and link into Daniel's Move Scripts doc landing in this PR?
https://github.com/aptos-labs/aptos-core/pull/7449

Thanks!

**Comment by movekevin** [comment]
How about we rename it to "Move Scripts"?

**Comment by clay-aptos** [comment]
> How about we rename it to "Move Scripts"?

We can do that yet note the many uses of it within the glossary Move-related definitions starting at:
https://aptos.dev/reference/glossary

Our blockchain deep dive (life of a transaction):
https://aptos.dev/guides/basics-life-of-txn/#life-of-a-transaction

And the Move Book:
https://aptos.dev/guides/move-guides/book/packages/
https://aptos.dev/guides/move-guides/book/signer/

Adding @wrwg before we alter the Move Book. All, please advise.

**Comment by clay-aptos** [comment]
And I am linking to the Move scripts page from the Transaction scripts glossary definition and starting to associate those terms in:
https://github.com/aptos-labs/aptos-core/pull/7409
