### ISSUE TITLE
[Feature Request] 'Batch Get' way for resource

### ISSUE THREAD

**Issue by molefund** [aptos-labs/aptos-core#6320]
# 🚀 Feature Request

Could Aptos support 'Batch Get' resource? Now only has 'One by One get' way to get resource. 

## Motivation

**Is your feature request related to a problem? Please describe.**

Dapps can benefit from 'Batch Get' that page load time and node pressure will decrease dramaticly. Currently the page load time is high and node pressure is high. If we have Batch Get. It will decrease.

## Pitch

**Describe the solution you'd like**
Change 'One by One Get' way to 'Batch Get' way.

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by gregnazario** [comment]
To be more clear, this is of the form:

I provide multiple resource identifiers e.g. `[0x1::coin::CoinStore, 0x1::account::Account]`

I receive back those resources, instead of the entire list, or requesting 1 at a time.

Likely would be limited to something like 20 resources.
