### ISSUE TITLE
[Bug] aptos move test doesn't fail when entry functions contain Option<_> arguments

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#6340]
# 🐛 Bug

aptos move compile currently fails when there are entry functions with Option<_> arguments, for example:
`type option::Option<u64> is not supported as a parameter type`

while aptos move test doesn't.

**Comment by wrwg** [comment]
Extended checks are not run when you do `aptos move test`.

**Comment by rahxephon89** [comment]
@wrwg In this case, we should add extended checks when executing `aptos move test`?

**Comment by wrwg** [comment]
Yes
