### ISSUE TITLE
[Improvement] Create and track yaml file for future framework releases

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#6354]
# 🐛 Context

We use yaml files with feature flag values to generate proposals for enabling/disabling features in testnet/mainnet (via the release CLI). We should track these into the core repo along with the binary commit hashes that are required.

**Comment by runtian-zhou** [comment]
Ideally we need a `current.yaml` for the framework release in main branch and we will be just renaming this file to `vx.x.x.yaml` at branch cut time.

**Comment by runtian-zhou** [comment]
Also we need a full README doc for how to use the framework release tooling.
