### ISSUE TITLE
[Feature Request] Support running specific Move unit tests

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#6365]
# 🚀 Feature Request

In Rust, we can do cargo run test_name to filter which tests are run. This is not possible in Move.

**Comment by wrwg** [comment]
This is actually there but the command line syntax does not support this without a flag. The way to do this:

```
aptos move test --help
...
   -f, --filter <FILTER>
            A filter string to determine which unit tests to run
```

If you think we need a different syntax, feel free to reopen (it might be a problem of the command line parser).

**Comment by movekevin** [comment]
I see thanks. Let me file another issue to document this somewhere then
