### ISSUE TITLE
[Bug] can't publish package on devnet

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-core#6380]
# 🐛 Bug

trying to publish https://github.com/aptos-labs/todolist-dapp-tutorial/tree/main/move  with `aptos move publish` to devnet but getting
```
{
  "Error": "Transaction Executed and Committed with Error TYPE_MISMATCH"
}
```

## To reproduce

**Code snippet to reproduce**
use the files on this repo
https://github.com/aptos-labs/todolist-dapp-tutorial/tree/main/move

run `aptos move publish`, getting

```
{
  "Error": "Transaction Executed and Committed with Error TYPE_MISMATCH"
}
```

**Stack trace/error message**
```
{
  "Error": "Transaction Executed and Committed with Error TYPE_MISMATCH"
}
```

## Expected Behavior

a move package published successfully 

## System information

**Please complete the following information:**
`aptos info`
```
{
  "Result": {
    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_commit_hash": "f8283fbd85472b3f880a2457f4a794761a6eeb55",
    "build_is_release_build": "true",
    "build_os": "macos-aarch64",
    "build_pkg_version": "1.0.4",
    "build_profile_name": "release",
    "build_rust_channel": "1.66.1-aarch64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-01-28 11:24:24 -08:00",
    "build_using_tokio_unstable": "true"
  }
}
```

## Additional context

publishing to a local testnet works

**Comment by gregnazario** [comment]
Looks like there are some fixes I will make on the codebase

**Comment by gregnazario** [comment]
Cause:

module name `main` has a conflict.  modules need to be named with conflicts in mind

**Comment by gregnazario** [comment]
This no longer has an issue.  It was due to a bug on main.  All packages deployed to devnet should use devnet branch for the framework
