### ISSUE TITLE
[Bug] create-resource-account-and-publish-package (cli) produces different resource address from account::create_resource_address (move)

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#6392]
# 🐛 Bug

I wonder: why does `account::create_resource_address` and `aptos move create-resource-account-and-publish-package` produce different resource address?

```
➜  troubleshoot-create-resource-account git:(main) aptos move test --named-addresses example=0x2
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING example
Running Move unit tests
[debug] "Derived Resource Address"
[debug] @0xe279a702e4aca7bce93900a3d324dd9ffb4eaa6dd3f3ff78caf8c314fb997b7e
[ PASS    ] 0x2::example::print_derived_resource_address
Test result: OK. Total tests: 1; passed: 1; failed: 0
{
  "Result": "Success"
}

➜  troubleshoot-create-resource-account git:(main) aptos move create-resource-account-and-publish-package --seed example_seed --address-name example
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING example
Do you want to publish this package under the resource account's address 7a53caaa16aa43ef8ce0a9d7ae5905e1415473ff2053c4c6014fd856a3a4e424? [yes/no] >
^C
```

Obviously `0xe279a702e4aca7bce93900a3d324dd9ffb4eaa6dd3f3ff78caf8c314fb997b7e` is different from `7a53caaa16aa43ef8ce0a9d7ae5905e1415473ff2053c4c6014fd856a3a4e424`.

## To reproduce

check out this repo https://github.com/0xbe1/troubleshoot-create-resource-address for a full reproduction

## Expected Behavior

They should instead be the same address

## System information

```
$ aptos info
{
  "Result": {
    "build_branch": "",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_commit_hash": "",
    "build_is_release_build": "true",
    "build_os": "macos-x86_64",
    "build_pkg_version": "1.0.4",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-01-12 00:02:30 +00:00",
    "build_using_tokio_unstable": "true"
  }
}
```

**Comment by gregnazario** [comment]
So simple answer, the CLI is doing a different encoding of the input from the CLI

b"example_seed" is interpreted as the UTF-8 bytes for the seed

but when you provide "example_seed" into the CLI, it BCS encodes the string, which UTF-8 encodes the text, and adds a ULEB128 at the beginning of the string, in this case the byte 12.


BCS: [12, 101, 120, 97, 109, 112, 108, 101, 95, 115, 101, 101, 100]
UTF: [101, 120, 97, 109, 112, 108, 101, 95, 115, 101, 101, 100]
 
This is purely a tooling issue vs onchain.

To get the same input as the CLI, you'd have to prefix the byte 12.

**Comment by hamdiallam** [comment]
Hi @gregnazario

is it possible to improve the tooling here? Or is there something we can do on the Move front reconcile the two?

On the Move side:
> const RESOURCE_ACCOUNT_SEED: vector<u8> = b"example_seed";

**Comment by hamdiallam** [comment]
It would be nice if `--seed` utilized the same parser as the `--args` command on `aptos move run`. Where the format can be supplied `hex/string/raw` etc
