### ISSUE TITLE
[Bug] Disallow module metadata which is not yet supported by aptos-vm

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#6420]
Currently, if we define new module metadata (using a new metadata key) an older VM will just ignore this metadata. However, if the metadata is later supported by the VM and influences behavior, a compatibility problem appears. We should disallow publishing of code with metadata the VM does not understand.

**Comment by lbmeiyi** [comment]
This is implemented. confirmed by Wolfgang.
