### ISSUE TITLE
Collision if your module has multiple dependencies with the same named address but different values

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#6464]
Say you have two packages:
```
[package]
name = 'DepA'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
admin = "0xaaaaaaaa"
```
```
[package]
name = 'DepB'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
admin = "0xbbbbbbb"
```

Now let's say you have a parent package that depends on both of them:
```
[package]
name = "MyProject"
version = "0.0.0"

[dependencies]
DepA = { git = "https://github.com/banool/testing.git", subdir = "dep_a", rev = "main" }
DepB = { git = "https://github.com/banool/testing.git", subdir = "dep_b", rev = "main" }
```

If you try to compile this, you will get an error that looks like this:
```
Move compilation failed: Unable to resolve packages for package 'MyProject': Unable to resolve named address 'admin' in package 'MyProject' when resolving dependencies: Attempted to assign a different value '0xbbbbbbb' to an a already-assigned named address '0xaaaaaaaa'
```

In other words, if you depend on two packages that use the same named address with different values, they will collide and compilation will fail.

This seems like a package ecosystem problem waiting to happen. Essentially in this setup, all named addresses exist within a global namespace. The two packages I depend on might be written by totally separate entities and they just independently chose to use the same name, e.g. `admin` (which is quite common). If that's the case, I have to ask one of them to go use a different named address, like admin1 and admin2. Or I just don't use one of the packages.

I feel the solution would be to "scope down" named addresses, so that a named address exists only within a single package, so when you compile two dependent modules, their names won't collide, since as siblings, those named address should have no meaning to each other.

Alternatively, there could be some scheme where you namespace the named addresses, so you could do `package::named_address` or something. But I don't know if this is actually necessary.

**Comment by wrwg** [comment]
Can you reopen this in the move repo? This code is 100% over there. The original author of the package system has recently joined Mysten and may be either able to explain the solution or fix this.

**Comment by banool** [comment]
https://github.com/move-language/move/issues/867
