### ISSUE TITLE
could you please update aptos npm package?

### ISSUE THREAD

**Issue by zfy0701** [aptos-labs/aptos-core#6477]
## ❓ Questions and Help

https://github.com/aptos-labs/aptos-core/commit/36267e43c0c74e800e0f2dbdd1814d3314106cc1

this commit seems really important and has been in the repo for several days, is it  a good time to get this released?

### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

**Comment by gregnazario** [comment]
I believe the aptos SDK npm package has been updated
