### ISSUE TITLE
[Docs] Insufficient documentation of code in `aptos-token` and token royalties

### ISSUE THREAD

**Issue by armyhaylenko** [aptos-labs/aptos-core#6502]
# Aptos Documentation Issue

This is an issue related to code documentation.

## Location

Location: https://github.com/aptos-labs/aptos-core/blob/43dae07f5a16ff6f01ecd8b85a3d4c4f80fec050/aptos-move/framework/aptos-token/sources/token.move#L1091
AND
Build Apps > Follow the Aptos Standards > Aptos Token

## Description

There are two things I see as a point of improvement.

#### Royalties

The royalty concept is clear to anyone who worked with NFTs before. On the other hand, it's unclear what the "royalty points" are and why they are represented as fractions (numerator/denominator). To add to that, there seems to be no check when both `royalty_points_numerator` and `royalty_points_denominator` are equal to `0` - but that is more a code issue rather than a documentation issue. Still, it would be of great help to see `///` docs for functions in `aptos-token`.

#### General code documentation
The code only seems to contain meaningful descriptions for `structs`, but not `fun`s. This makes developers look into the code of the function, making `aptos-token` IMHO much harder to work with. 

#### Points of improvements

* Create docs for all functions in `aptos-token`, with a quick description of what the functions do, their parameters and possible values, and cases for unacceptable arguments (like the denominator being `0`, for example). Or at least references to the documentation of other functions (like, `/// See documentation for X for more details.`)
* Add royalty documentation to `Build Apps > Follow the Aptos Standards > Aptos Token` page.

## Audience

Developers, technical writers.

## Additional context

I was trying to create a very simple NFT-related charity app and now seem to be failing because of insufficient documentation.

**Comment by clay-aptos** [comment]
Thank you so much, Oleksandr! I am adding our subject matter experts for their input.
