### ISSUE TITLE
[Bug] aptos move publish fails with `--bytecode-version 6`

### ISSUE THREAD

**Issue by devfans** [aptos-labs/aptos-core#6510]
# 🐛 Bug

Using the latest aptos cli v1.0.5 or build from main branch, aptos move publish failed on simulation 
```  "Error": "Simulation failed with status: Transaction Executed and Committed with Error CODE_DESERIALIZATION_ERROR"``` with `--bytecode-version 6`  while compile with it succeeded. Publish without `--bytecode-version 6` was a success.

## To reproduce

**Code snippet to reproduce**
Not able to write an equivalent yet

**Stack trace/error message**
```
{
  "Error": "Simulation failed with status: Transaction Executed and Committed with Error CODE_DESERIALIZATION_ERROR"
}
```

## Expected Behavior

Simulation should succeed.

## System information

**Please complete the following information:**
- 
- aptos cli/framework dependency: https://github.com/aptos-labs/aptos-core/commit/d57b97bae0b64b617869f2ff26e749e503848846
- 
- 

## Additional context

Using mainnet official rpc node.

#6418 might be related or not

**Comment by ivanfong01** [comment]
Mainnet support of --bytecode-version 6 is not yet enabled...

**Comment by devfans** [comment]
Oh I see, thanks
