### ISSUE TITLE
[Release] Upgrade Mainnet framework to v1.2

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#6557]
Use this issue as general tracking and gathering any questions community has.

**Comment by great9** [comment]
Can we get the crates updated please?

**Comment by movekevin** [comment]
> Can we get the crates updated please?

What do you mean by crates?

**Comment by lbmeiyi** [comment]
Confirmed with Kevin that we can close now. Mainnet is complete.
