### ISSUE TITLE
Aptos View Function

### ISSUE THREAD

**Issue by evilgon** [aptos-labs/aptos-core#6558]
Hi, hope doing well.
I am working in Aptos for 4 months.
When I need data, I used functions which can read resource from endpoint.
But there is some problems.
How to get some results by params immediately?
Plz answer me.

**Comment by e99243506bigplay** [comment]
Not yet on this moment if you mean mainnet, you need to wait for mainnet framework v1.2 upgrade.

**Comment by evilgon** [comment]
I see, thank you for your responding.
