### ISSUE TITLE
[Feature request] support HTTP API over UNIX Socket

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#6559]
# 🚀 Feature Request

Support HTTP API over UNIX Socket. 

## Motivation

**Is your feature request related to a problem? Please describe.**

Currently, I am suffering kernel panic cause by aptos-node that I dont know why causing it, possible reason could be my wireless card problem or kernel sys tcp params wrong, or aptos-node tcp related params too high.

And I have a arbitrage serivce is running on my computer, that service are try to poll bombarding my aptos node tcp api interface for getting newest infomation.
So I would like to try to use unix socket to bypass the problem to see does it working.

By the speaking, my node just crashed my linux kernel again.

## Pitch

**Describe the solution you'd like**

if possible, I would like to fix up why aptos-node could causing linux kernel crashing, but I dont know why is it.
For now, I would like try to using unix socket api interface for circumvent the linux kernel crashing problem.

**Describe alternatives you've considered**

Provide event interface or "newest transaction happened" subscribe mechanism. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Maybe.

## Additional context

Arch Linux 
```
$ uname -a
Linux Android 6.1.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 06 Feb 2023 09:28:04 +0000 x86_64 GNU/Linux
```

**Comment by e99243506bigplay** [comment]
I optimized my arbitrage service, hopefully it wont crash my node again...

**Comment by gregnazario** [comment]
Interesting, what kind of hardware / OS are you running?  UNIX socket support in the addresses shouldn't be too bad, but it does require a lot of plumbing

**Comment by e99243506bigplay** [comment]
> Interesting, what kind of hardware / OS are you running? UNIX socket support in the addresses shouldn't be too bad, but it does require a lot of plumbing

Arch Linux Rolling.
ASUS TUF Gaming A17 FA707RW_FA707RW

**Comment by e99243506bigplay** [comment]
> > Interesting, what kind of hardware / OS are you running? UNIX socket support in the addresses shouldn't be too bad, but it does require a lot of plumbing
> 
> Arch Linux Rolling. ASUS TUF Gaming A17 FA707RW_FA707RW
> 
> Now I thinking my btrfs filesystem is goes wrong, because the btrfs are sometime go read only mode. I am not going to install unstable btrfs filesystem in future.

I think I found problem, it maybe tha problem was from the power supply.

**Comment by lbmeiyi** [comment]
Sounds like the issue was resolved. Would you please confirm before I close this out? thank you!

**Comment by gregnazario** [comment]
Cool, let us know if you have any other issues.

**Comment by e99243506bigplay** [comment]
Hey, the UNIX Socket APT wasn't implemented now! Although my issue fixed.
