### ISSUE TITLE
[Question] Why coin::burn function is not allow to burn zero coin?

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#6560]
https://github.com/aptos-labs/aptos-core/blob/5dcc815baaf250fbbdb1fd474cefae402ffb364f/aptos-move/framework/aptos-framework/sources/coin.move#L279-L291

I suggest change be:

```
    public fun burn<CoinType>(
        coin: Coin<CoinType>,
        _cap: &BurnCapability<CoinType>,
    ) acquires CoinInfo {
        let Coin { value: amount } = coin;
        if (amount == 0) return ();

        let maybe_supply = &mut borrow_global_mut<CoinInfo<CoinType>>(coin_address<CoinType>()).supply;
        if (option::is_some(maybe_supply)) {
            let supply = option::borrow_mut(maybe_supply);
            optional_aggregator::sub(supply, (amount as u128));
        }
    }
```

by such change, so for some situation this is could be more gas optimized.

**Comment by wrwg** [comment]
This is shipped code and we cannot just change it. Moreover, the check for zero is by design and we have no intention to change this.

**Comment by e99243506bigplay** [comment]
> This is shipped code and we cannot just change it. Moreover, the check for zero is by design and we have no intention to change this.

I have no idea why be design like that. What situation will need to so...

**Comment by davidiw** [comment]
Thanks for your post and PR to address it. As Wolfgang said, this was by design and now it is potentially expected behavior. Changing it at this point, could render other applications to be invalidated.

When we consider a revamp to the current coin standard, we'll take this into consideration.

**Comment by e99243506bigplay** [comment]
> Thanks for your post and PR to address it. As Wolfgang said, this was by design and now it is potentially expected behavior. Changing it at this point, could render other applications to be invalidated.
> 
> When we consider a revamp to the current coin standard, we'll take this into consideration.

I hopefully at that time we could do move bytecode assembly for optimize gas fee usage.
