### ISSUE TITLE
[Feature Request] Pure rustls dependency mode as a option, let OpenSSL be optional.

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#6572]
# 🚀 Feature Request

Try to clean up OpenSSL dependency for avoid OpenSSL for additional step about OpenSSL manual compiling.

## Motivation

Try to get rid of openssl-sys manual compiling for smooth experience on compiling.
Imporve cross compiling experience.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

I think I would later open the PR by myself for process this stuff, currently looks like isahc are stucking on rustls support.
https://github.com/sagebind/isahc/issues/199

**Describe alternatives you've considered**

What alternatives?

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes.

**Comment by gregnazario** [comment]
I agree, openssl is a real pain sometimes. I've thought about either including OpenSSL statically in the binaries, which would be another option

**Comment by gregnazario** [comment]
Let me know if you are able to update the dependency, but this is low priority for now
