### ISSUE TITLE
[Feature Request] checking if public key and account address are connected

### ISSUE THREAD

**Issue by coado** [aptos-labs/aptos-core#6581]
# 🚀 Feature Request

## Motivation
I am building a web app on Aptos where users can log in using an Aptos wallet. I verify if the log in message is signed by a user's wallet, then I want to store the user's address account in db. I also have to check if the provided public key and account address are connected (to be sure that provided address account belongs to the user), so it would be awesome to have some typescript sdk function that will handle that.

## Pitch
the typescript sdk function that will check if the public key and account address are connected

**Alternatives**
At this point, I retrieve auth key from the public key and check if this auth key is stored on the given address account. Is it an appropriate approach?

**Comment by e99243506bigplay** [comment]
Your logic possible has flaw, although that don't exists for now, what if your user that someone rotated their authentication key, Now are you keep going to bind their public key with address? Correct me if I wrong.
https://github.com/aptos-labs/aptos-core/blob/6fc03c4c5ecc9a814e3843bc2207ccc6d603398d/aptos-move/framework/aptos-framework/sources/account.move#L290-L298

**Comment by coado** [comment]
I do not store public key, only account address under my user in db. If someone rotate auth key, then this new auth key will be stored under account address I think, so this logic will still be valid in my opinion, but I can be wrong.

**Comment by gregnazario** [comment]
So, what I see is you want the ability to lookup the public key, address lookup table on chain.  It's definitely useful to determine the address from a public key, though it should already be trusted from the wallet.

The address will always be the same but the auth key & public key will be different

**Comment by gregnazario** [comment]
This would be very useful in the SDK for wallets
