### ISSUE TITLE
[Feature Request] get SDK/API support to access the source code deployed in the move module

### ISSUE THREAD

**Issue by jillxuu** [aptos-labs/aptos-core#6589]
# 🚀 Feature Request

Explorer is working on adding write/read/view smart contract features to its product. As part of the design, we'd like to display move smart contract source code as explained below in the screenshot. 

<img width="1539" alt="Screenshot 2023-02-14 at 1 26 23 PM" src="https://user-images.githubusercontent.com/121921928/218866731-aa56a8b8-cc23-4150-a7ce-ef7fa1e28fdb.png">

Right now there are ways to achieve this goal with the CLI support:
```
env CONTRACT_ADDR="0xbeaa9e5ef5bee0781476a4adf293aae7dc3a28e9bd79fda89fca7211fb94c80" curl -fsSL "https://fullnode.mainnet.aptoslabs.com/v1/accounts/$CONTRACT_ADDR/resources" | jq '.[]| select(.type=="0x1::code::PackageRegistry") | .data.packages[].name' | xargs -n1 -I{} aptos move download --account "$CONTRACT_ADDR" --url https://mainnet.aptoslabs.com/v1 --output-dir ~/Downloads/ --package {}
```

as well as getting the source from the client side TS: 

> request the account's [`0x1::code::PackageRegistry`](https://fullnode.mainnet.aptoslabs.com/v1/accounts/0x96be8b77f364acc83b5cf7097116c4c34a404f8e357941dff04b1d0baebcf29d/resource/0x1::code::PackageRegistry), then iterate through the packages and modules to find the one that matches the module name you're trying to look up. Then you take the source field, hex decode it, and then gunzip it and you have the source code. Not all modules have source available.

However, having SDK support would help make SDK/API queries consistent across different client usages and provide a better developer experience in the Aptos ecosystem. 

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**
A solution would be to have a pull request that adds the SDK support to get the source code smart contract deployers deployed. 

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by e99243506bigplay** [comment]
I have a question, what if a move module on chain was binary only without source code?

**Comment by gregnazario** [comment]
Keep in mind, that sometimes you don't have the source code.  https://tracemove.io shows the disassembled code in this case.
