### ISSUE TITLE
[Bug] Update aptos-sdk crates

### ISSUE THREAD

**Issue by great9** [aptos-labs/aptos-core#6631]
# 🐛 Bug

aptos-sdk crate needs a long overdue update. My crate depends on aptos-sdk and publishing fails as the specified version is the devnet branch of aptos-core.
The version available on crates.io is 0.2.7, it's over 6 months old and can't be used with the devnet / mainnet codebase.

## To reproduce

**Cargo.toml**
```rust
[workspace.dependencies]
aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core", branch = "devnet" }
```

**Stack trace/error message**
```
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `aptos-sdk` does not specify a version
```

**Comment by gregnazario** [comment]
Yeah, agreed.  Will take a look into this
