### ISSUE TITLE
[Feature Request] supporting paying gas on behalf of other users

### ISSUE THREAD

**Issue by 0xchloe** [aptos-labs/aptos-core#6632]
# 🚀 Feature Request

Add a new transaction type that allows a separate gas payer. The separate gas payer will sign on the same raw txn and its own account address for us to verify that this gas payer transaction is also authorized by the gas payer. 

Currently in the MoveVM, to pay for gas, we essentially do two things - verify the sender's signature, and charge the sender upon successful verification.
To allow a separate gas payer, we need to also verify the gas payer's signature, and instead charge the gas payer.

Signature Verification
![Screen Shot 2023-02-24 at 3 19 55 PM](https://user-images.githubusercontent.com/79347459/221319650-3e2010ac-0d76-4bdb-af87-c93bc817428f.png)
`preprocess_transactio()` checks the transaction sender's signature - for the purpose of adding a gas payer, we would need to modify the `check_signature()` and the `verify()` functions to also check the gas payer's signature on the raw transaction and the gas payer's account address.

Gas Charging
![Screen Shot 2023-02-24 at 3 20 03 PM](https://user-images.githubusercontent.com/79347459/221319620-388cce1c-5b74-461b-b79d-7d3e2aa89f65.png)
`execute_user_transaction()` takes in a transaction of type `SignatureCheckedTransaction` which includes the sender's account address, and then converts it to `TransactionMetadata` and passes along the sender's account address to the Move function `transaction_validation::epilogue` to deduct the gas amount on-chain. 
For the purpose of gas payer, we will extend `TransactionMetadata` to also include an optional gas payer - if a transaction has a gas payer, we will then pass in the gas payer's signer to `transaction_validation::epilogue`. 

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by raul1ro** [comment]
It would be nice to be possible to pay the gas from a different wallet. 
Also, it would be nice to be available a wrap-apt(1wapt = 1apt; all the time, no exception). You can trade `WAPT`, and take the gas from `APT`.

**Comment by magnum6actual** [comment]
Thinking this is best accomplished from the SDK/API without impacting established Move framework. We could create the raw transaction like normal, but providing an alternate function to sign the transaction like:
`generateBCSTransactionWithPayor(accountFrom: AptosAccount, payorAccount: AptosAccount, rawTxn: RawTransaction): Uint8Array`

This would be the least disruptive way to implement. Everything about the transaction, including sequence number, would function as perviously, just the gas fees would be charged to payorAccount.

**Comment by borispovod** [comment]
Hello,

I have reviewed it, and it appears to be a good start. However, it seems quite basic. Would it be possible to incorporate a custom gas payment logic using a function in the future?

What I don't particularly like, as seen in EIP 4337, is that someone must still sign the transaction using their private key. This solution does not seem ideal. Aptos could benefit greatly from additional work on top of the current `Account.move` logic, such as the ability to pay for gas using a treasury or smart contract balance. 

Essentially, by moving the gas payment verification/processing logic to the level of a smart contract.

**Comment by magnum6actual** [comment]
Any updates on this one? This is the last big piece we need to fully deploy our model.

**Comment by wrwg** [comment]
@gerben-stavenga are you actually working on this? If not move to backlog

**Comment by gerben-stavenga** [comment]
Yes this is one of my priorities

**Comment by magnum6actual** [comment]
Any updates on this? Branch/fork we could take a look at to preview?
