### ISSUE TITLE
[Bug] gas_used simulated always different from real transaction

### ISSUE THREAD

**Issue by web3luhao** [aptos-labs/aptos-core#6635]
# 🐛 Bug
gas_used simulated always different from the actual one

## To reproduce

at 0 second simulate gas_used: "552";
at 10 second real transaction gas_used: "585";
at 20 second another simulate , gas_used: "552".

## Expected Behavior
same value most time.

## System information
aptos npm 1.6.0

## Additional context
function been tried: 
`0x1::coin::transfer `
`0x1::aptos_account::transfer`
```
options: {
  estimateGasUnitPrice: true,
  estimateMaxGasAmount: true,
  estimatePrioritizedGasUnitPrice: false,
}
```

**Comment by gregnazario** [comment]
I ran this a few times, and it came out the same each time.  The gas used and the gas unit price = the simulated amount (which was 750)

```
./target/debug/aptos account transfer --account default --profile default --amount 0 
Do you want to submit a transaction for a range of [750 - 1050] Octas at a gas unit price of 150 Octas? [yes/no] >
yes
{
  "Result": {
    "gas_unit_price": 150,
    "gas_used": 5,
    "balance_changes": {
      "e42895bdea9ffef448368a95f51b4c883a8e025be3f8e7d08df39f46861a0dc5": {
        "coin": {
          "value": "399245580"
        },
        "deposit_events": {
          "counter": "9",
          "guid": {
            "id": {
              "addr": "0xe42895bdea9ffef448368a95f51b4c883a8e025be3f8e7d08df39f46861a0dc5",
              "creation_num": "2"
            }
          }
        },
        "frozen": false,
        "withdraw_events": {
          "counter": "3",
          "guid": {
            "id": {
              "addr": "0xe42895bdea9ffef448368a95f51b4c883a8e025be3f8e7d08df39f46861a0dc5",
              "creation_num": "3"
            }
          }
        }
      }
    },
    "sender": "e42895bdea9ffef448368a95f51b4c883a8e025be3f8e7d08df39f46861a0dc5",
    "success": true,
    "version": 470101455,
    "vm_status": "Executed successfully",
    "transaction_hash": "0x1c81eb4a72b4fb23542ed2762a4d8f75247da884105fefe49abc3f1854dabd29"
  }
}

```

**Comment by gregnazario** [comment]
Can I see a direct example of a simulation result and the transaction that is successful?

**Comment by gregnazario** [comment]
Simulation is the same,  as long as the gas price you use is exactly the same as the gas price you use to submit the transaction.

Is this on testnet?

**Comment by gregnazario** [comment]
Gas used varies now based on the gas unit price.  This is because the storage cost is constant, but the execution cost is varied.  In order to make this compatible with the old version, that means that the gas used actually goes down, as gas unit price goes up.
