### ISSUE TITLE
Document how to create account and transactions in mainnet

### ISSUE THREAD

**Issue by gitsupi** [aptos-labs/aptos-core#6692]
in the page of https://aptos.dev/tutorials/your-first-transaction/
you said :
![image](https://user-images.githubusercontent.com/65791341/219874678-95832368-9498-46b9-b147-a9e22741b2c6.png)

where are from this 100_000_000 for Alice in main network????????

**Comment by e99243506bigplay** [comment]
mainnet? what are you talking about? why you are not play around in devnet?

**Comment by loveyandex** [comment]
> mainnet? what are you talking about? why you are not play around in devnet?

because real world transactions is in mainnet
do u understand

**Comment by e99243506bigplay** [comment]
> > mainnet? what are you talking about? why you are not play around in devnet?
> 
> because real world transactions is in mainnet do u understand

no, why mainnet has FaucetService?

**Comment by loveyandex** [comment]
> > > mainnet? what are you talking about? why you are not play around in devnet?
> > 
> > 
> > because real world transactions is in mainnet do u understand
> 
> no, why mainnet has FaucetService?

my question is clear
how to create account and tranactions in mqinnet not in dev net

the document is for devnet....so how we do it in main net

**Comment by e99243506bigplay** [comment]
> > > > mainnet? what are you talking about? why you are not play around in devnet?
> > > 
> > > 
> > > because real world transactions is in mainnet do u understand
> > 
> > 
> > no, why mainnet has FaucetService?
> 
> my question is clear how to create account and tranactions in mqinnet not in dev net
> 
> the document is for devnet....so how we do it in main net

There is no faucet serivce on mainnet, that literally free cash grab. if you want APT you must buy it some where else with your crypto or your real money, that sounds yours, Well, Please go to CEX to buy some APT then transfer APT to your Petra Wallet for your safely lol.

With nothing to create account on mainnet? Hopefully you able to request someone to send some APT for you. :eyes:

**Comment by clay-aptos** [comment]
I recommend reading:
https://aptos.dev/guides/get-test-funds
https://aptos.dev/guides/system-integrators-guide/

As noted by @e99243506bigplay, mainnet requires real-world funds. Otherwise, the process is the same as described in:
https://aptos.dev/tutorials/your-first-transaction/

**Comment by clay-aptos** [comment]
I am asking @christian-aptos to take a look at this.

**Comment by loveyandex** [comment]
@clay-aptos we are waited

**Comment by clay-aptos** [comment]
> @clay-aptos we are waited

Did you review the docs I posted? What is missing from them?

**Comment by loveyandex** [comment]
> > @clay-aptos we are waited
> 
> Did you review the docs I posted? What is missing from them?

the doc explain creating account and transactions in main net???whats about that doc u linked

our problem is mqinet  not dev net

**Comment by clay-aptos** [comment]
Take a look at:
https://github.com/aptos-labs/aptos-core/pull/6947
