### ISSUE TITLE
convert private key hex string to SignKeyPair or Uint8Array

### ISSUE THREAD

**Issue by gitsupi** [aptos-labs/aptos-core#6695]
how to convert `0xe8223b61b296cb10 ` to` Uint8Array[23,23,23,423,...]`

**Comment by clay-aptos** [comment]
What doc?

**Comment by loveyandex** [comment]
@clay-aptos #6705

**Comment by clay-aptos** [comment]
I am asking @christian-aptos to take a look at this.

**Comment by gregnazario** [comment]
This is in the Typescript SDK, he wants to convert a Hex string to a byte array (Uint8Array)

**Comment by saharct** [comment]
@gitsupi You can use `new HexString("<hex string>").toUint8Array()`. It is defined in [hex_string.ts](https://github.com/aptos-labs/aptos-core/blob/7bc3f195928488963bb947dc0e300f26527f2675/ecosystem/typescript/sdk/src/utils/hex_string.ts#L119) and usage can be found in the publish a Move module [TypeScript SDK code example](https://aptos.dev/tutorials/your-first-dapp/#step-4-publish-a-move-module). 

@0xmaayan, please let me know if I missed anything.
