### ISSUE TITLE
create account and make transaction in mainnet by code

### ISSUE THREAD

**Issue by gitsupi** [aptos-labs/aptos-core#6705]
create account and make transaction in mainnet in typescript or any programing language

**Comment by loveyandex** [comment]
@clay-aptos

**Comment by clay-aptos** [comment]
> @clay-aptos

See and reply to:
https://github.com/aptos-labs/aptos-core/issues/6692#issuecomment-1439018673

**Comment by loveyandex** [comment]
> > @clay-aptos
> 
> See and reply to: [#6692 (comment)](https://github.com/aptos-labs/aptos-core/issues/6692#issuecomment-1439018673)

why not here you clarify yow creat real account and real user transaction in typescript ...

clarify in doc real world main net and dev net requirments 


what requirments needs to do in mqin net

**Comment by clay-aptos** [comment]
I am asking @christian-aptos to take a look at this.

**Comment by davidiw** [comment]
Our current position is to leave mainnet acquisition to the users. Creating accounts is consistent across networks.

Follow along here: https://github.com/aptos-labs/aptos-core/issues/7067

**Comment by loveyandex** [comment]
> Our current position is to leave mainnet acquisition to the users. Creating accounts is consistent across networks.
> 
> Follow along here: #7067

how to make a tranasction in mainnet by code

**Comment by davidiw** [comment]
https://aptos.dev/guides/system-integrators-guide

**Comment by clay-aptos** [comment]
Also see:
https://github.com/aptos-labs/aptos-core/pull/6947
https://github.com/aptos-labs/aptos-core/issues/6692

**Comment by loveyandex** [comment]
> Also see: #6947 #6692

tou did not answer a direct answer 
goodbye forever clay you deaft me eventually 🐯🙂😀
