### ISSUE TITLE
[Feature Request] Typescript sdk support bcs serialize vector<vector<T>>

### ISSUE THREAD

**Issue by ccbond** [aptos-labs/aptos-core#6724]
# 🚀 Feature Request

## Motivation

Now , if i defined a vector<vector<T>> args in move program. I can't use bcs native function to serialize vector<vector<T>>  to Sqp<Bytes>.

## Pitch
move :
```
    public entry fun mutil_swap<CoinA, CoinB>(
        pool_addresses: vector<vector<address>>
        amounts: vector<u64>,
    ) 
```
but how can i pass arg ues typescript sdk?

**Comment by gregnazario** [comment]
I believe this is possible, but I'll have to check.  @0xmaayan have you tested out the nested vectors with the typescript SDK?

**Comment by ccbond** [comment]
> I believe this is possible, but I'll have to check. @0xmaayan have you tested out the nested vectors with the typescript SDK?

**Comment by ccbond** [comment]
I have submitted an excellent solution and done a complete test, please check. This work also comes from my project that we run on the aptos public network.
