### ISSUE TITLE
[Bug] framework.mrb does not exist

### ISSUE THREAD

**Issue by stevekeol** [aptos-labs/aptos-core#6778]
# 🐛 Bug

When following  the instructions of `generating-a-genesis-and-waypoint` (https://aptos.dev/cli-tools/aptos-cli-tool/use-aptos-cli/#generating-a-genesis-and-waypoint).

 I run `cargo run --package aptos -- genesis generate-genesis --local-repository-dir genesis`. 

there is a error: "Error": "Unexpected error: while reading `genesis/framework.mrb`"

(BTW: I have followed the instructions to complete the relative operations, such as layout.yaml, ValidatorConfiguration, framework dir with xx.mv ... )

The instructions just say to "place the framework release .mv files into the framework directory." There seems no framework.mrb ???

**Comment by davidiw** [comment]
did you copy the framework from `aptos-move/framework` to `genesis/framework`?

**Comment by davidiw** [comment]
Feel free to re-open if this doesn't resolve your issue.

**Comment by stevekeol** [comment]
Yes.
It `works` 👋🏻 when i copy the framework.mrb from `aptos-move/framework/release` to `genesis/framework` (which is in `$WORKSPACE`)
