### ISSUE TITLE
Aptos Docs - Create smart contract   - aptos compile issue 

### ISSUE THREAD

**Issue by tiff0000** [aptos-labs/aptos-core#6812]
## Location

https://aptos.dev/tutorials/build-e2e-dapp/create-a-smart-contract/

## Description

When following the tutorial on creating the smart contract, and trying to compile `aptos move compile`  from this step:
![Screen Shot 2023-02-27 at 9 18 13 PM](https://user-images.githubusercontent.com/20705520/221736120-97dfbc46-3cc6-42c9-a3ab-0b71220c2005.png)
it would throw this error: 
![image](https://user-images.githubusercontent.com/20705520/221734799-a8439baf-89d7-4e60-9081-39bbc42be65d.png)
`thread main() panicked at called 'Result::unwrap()'`

I solved the issue by adding `--bytecode-version 6`.
So, `aptos move compile --bytecode-version 6` would solve the issue. I was able to compile the codes using this command.

The doc needs to be updated to let people know how to solve this error if they encounter the same issue. 
I would suggest adding a tip section beneath this:
![Screen Shot 2023-02-27 at 9 15 23 PM](https://user-images.githubusercontent.com/20705520/221735676-c70f304d-c573-471d-abd5-f11b531cc9c9.png)
This tip component below can be used to suggest how to resolve the issue.
![Screen Shot 2023-02-27 at 9 15 53 PM](https://user-images.githubusercontent.com/20705520/221735756-936a1216-340b-4c8b-aca6-34e62211c1b6.png)

## Audience

Developers

Follow the tutorial, compile aptos codes

**Comment by clay-aptos** [comment]
Thank you, Tiffany! Sadly, this appears to have come up elsewhere.  I am adding my peers to see what the actual fix will be.

**Comment by clay-aptos** [comment]
Thanks for the report and workaround! Our team is working on a fix in:
https://github.com/aptos-labs/aptos-core/pull/6799
