### ISSUE TITLE
[Bug] Builds are broken for aarch64

### ISSUE THREAD

**Issue by vd-rd** [aptos-labs/aptos-core#6859]
Hello,

It is my understanding that different architectures other than amd64 are not currently supported, but it can pave the way to use generic tags in the Dockerfile, because manifests for different archs have different digests.
 Rather than 
`FROM rust:1.66.1-bullseye@sha256:f72949bcf1daf8954c0e0ed8b7e10ac4c641608f6aa5f0ef7c172c49f35bd9b5 AS rust-base`
should be enough to use
`FROM rust:1.66.1-bullseye AS rust-base`

**Comment by vd-rd** [comment]
As a follow-up, build is successful on aarch64 after removing the digest for the debian-base and rust-builder. I will update the issue after running the node on graviton instances

**Comment by lbmeiyi** [comment]
Is this issue still outstanding?

**Comment by vd-rd** [comment]
Yes.
Also, the aptos-node binary is running without errors for a few days now and serving requests.
I have also run the 'cargo test' suite for aptos-node-v1.2.6 tag with no errors encountered.

**Comment by lbmeiyi** [comment]
Great,If the builds are successful and you are no longer experiencing errors or issues. I will go ahead and close this down. Thank you for reporting and testing.

**Comment by vd-rd** [comment]
I will open a PR with the changes for the docker file, and reference this issue.
