### ISSUE TITLE
[Bug] Inline functions do not properly check dropping values

### ISSUE THREAD

**Issue by gerben-stavenga** [aptos-labs/aptos-core#6870]
# 🐛 Bug

https://github.com/move-language/move/issues/955

Currently inline functions do not type check on dropping values, ie.

struct OnlyMove { val: u64 }
public inline fun drop_onlymove(x: OnlyMove) {}

compiles cleanly. Now if you use it will complain in the caller function, but I think this should be rejected in the module.

**Comment by wrwg** [comment]
This is by design. Ability and borrow analysis does not happen on inline function definitions but only on inlined code. In this sense inline functions are more like macros. It opens a number of capabilities for inline functions which regular functions do not have.
