### ISSUE TITLE
[Feature Request] Prevent Transfer of Tokens which have Withdraw Capability Created and Delegated

### ISSUE THREAD

**Issue by newton-raphson** [aptos-labs/aptos-core#6900]
# 🚀 Feature Request

In the token.move, there is feature to create withdraw capability which can be used to withdraw the token from users token store for certain expiration time. But, in the mean time , this capability can be delegated to a module resource and user can transfer the same token. This should be prevented for different use cases

## Motivation
There are several use cases where the transfer authority of a token can be delegated to a module. For example, Sharkifi named borrowing lending protocol in Solana uses a similar approach and claims itself to be the  first vault-less borrowing lending protocol. Similarly, this feature has a variety of use cases in NFT renting, NFT raffle and NFT staking (you can view your NFT in your wallet, not locked in some vault )

## Pitch
 Simple updates in the token.move can solve this issue.
1. Adding a field named "authority_delegation" in token

<img width="810" alt="Screen Shot 2023-03-03 at 17 17 18" src="https://user-images.githubusercontent.com/98687675/222709879-61b3b8d0-d5af-471b-906a-25e4af64f141.png">

2. Setting the value of the authority_delegation to "true" in the function "create_withdraw_capability"
<img width="807" alt="Screen Shot 2023-03-03 at 17 25 24" src="https://user-images.githubusercontent.com/98687675/222711431-50e1baaf-33ba-4d61-837b-7a1694118841.png">

3.  Setting a check for authority_delegation in the function "withdraw_with_event_internal" 
<img width="760" alt="Screen Shot 2023-03-03 at 17 26 39" src="https://user-images.githubusercontent.com/98687675/222711651-c5f4c9c6-c675-4800-a6bb-eec914778dc8.png">

4.  Similar function as "withdraw_with_event_internal" named "withdraw_with_event_internal_delegated" for delegated case
<img width="829" alt="Screen Shot 2023-03-03 at 17 27 03" src="https://user-images.githubusercontent.com/98687675/222711725-f501410c-7153-4af1-902b-5c2c08a2a98a.png">

5.  Updating the function to "withdraw_with_event_internal_delegated" in function "withdraw_with_capability"
<img width="573" alt="Screen Shot 2023-03-03 at 17 28 23" src="https://user-images.githubusercontent.com/98687675/222712025-ae40162f-bbf0-4d59-aa12-8db540735782.png">

6.  A function to remove the  "withdraw_with_capability" : "remove_withdraw_capability"
<img width="691" alt="Screen Shot 2023-03-03 at 17 29 10" src="https://user-images.githubusercontent.com/98687675/222712167-9675e8f6-579b-4807-8a4f-aa338f2e30ca.png">

## Additional context
Some additional errors can arise
<img width="581" alt="Screen Shot 2023-03-03 at 17 29 49" src="https://user-images.githubusercontent.com/98687675/222712286-e6fea515-9e7f-4950-b44e-4beddd2872ba.png">

**Comment by movekevin** [comment]
We'll do this better in token v2: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-11.md
