### ISSUE TITLE
[Bug] Compiler failing bytecode verifier with inline functions 

### ISSUE THREAD

**Issue by gerben-stavenga** [aptos-labs/aptos-core#6907]
# 🐛 Bug

Compiling an function calling an inline function results in an internal compiler error

## To reproduce

at this commit 

https://github.com/aptos-labs/aptos-core/tree/f6070b81e0c791eec38227b5c0227e84907f0639

compile the move-stdlib with 

cargo run -p aptos -- move compile 

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```
 for_each_ref(v, |elem| push_back(&mut result, f(elem)));
      │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ICE failed bytecode verifier: VMError {
      major_status: STLOC_TYPE_MISMATCH_ERROR,
      sub_status: None,
      message: None,
      exec_state: None,
      location: Module(
          ModuleId {
              address: 0000000000000000000000000000000000000000000000000000000000000001,
              name: Identifier(
                  "vector",
              ),
          },
      ),
      indices: [
          (
              FunctionDefinition,
              20,
          ),
      ],
      offsets: [
          (
              FunctionDefinitionIndex(20),
              9,
          ),
      ],
  }

## Expected Behavior

A normal compile error or working compile

**Comment by brmataptos** [comment]
@gerben-stavenga can you provide a specific test case or at least a branch illustrating the problem?  It's hard to figure out what is going on with a dangling commit that's not even in the repo.

"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

https://github.com/aptos-labs/aptos-core/tree/f6070b81e0c791eec38227b5c0227e84907f0639

**Comment by brmataptos** [comment]
Gerben's example is in this dangling commit: https://github.com/aptos-labs/aptos-core/blob/f6070b81e0c791eec38227b5c0227e84907f0639/aptos-move/framework/move-stdlib/sources/vector.move

I've added a test based on this code here in my branch brm-issue-6907-new:
https://github.com/brmataptos/aptos-core/tree/brm-issue-6907-new

Not sure it's the same erorr, but there's a compiler ICE when you run:

cargo test -p bytecode-verifier-transactional-tests -- --skip prover gerbens_test --nocapture

**Comment by brmataptos** [comment]
Gerben's example in my branch now includes gerbens_test.move and gerbens_test_printonly.move/exp which shows the bytecode which would be printed if the publish had succeeded.

https://github.com/brmataptos/aptos-core/tree/brm-issue-6907-new

To run, I suggest:

`UB=1 cargo test -p bytecode-verifier-transactional-tests -- --skip prover gerbens_test --test-threads 1 --nocapture |& tee tests.out11`

The failed publish test output is:
```
processed 1 task

task 0 'publish'. lines 1-91:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::test_case'. Got VMError: {
    major_status: STLOC_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::test_case,
    indices: [(FunctionDefinition, 3)],
    offsets: [(FunctionDefinitionIndex(3), 9)],
}
```

This needs VM debugging help, I think.
