### ISSUE TITLE
silence linter errors "4-fetch-data-from-chain.md"

### ISSUE THREAD

**Issue by abebeos** [aptos-labs/aptos-core#6933]
## Status 

* linter signals errors

https://github.com/aptos-labs/aptos-core/actions/runs/4337586660/jobs/7573690857

```
Mispelled words in docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md:
useEffect
fetchList
const
accountHasList
setAccountHasList
useState
```

## Expected

* silence the linter errors

## Reproduction

- #6931 
- #6932

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/pull/6935

thanks
