### ISSUE TITLE
[REPO] Increase Main Branch Protection

### ISSUE THREAD

**Issue by abebeos** [aptos-labs/aptos-core#6943]
# Feature Request

This is essentially a bug-report

## Motivation

Currently, a PR can be merged to the `main` branch even if:

- the CI has failures
- no review happened

## Pitch

PRs should be merged to main only if:

- all checks passed (= green checkmark)
- at least one reviewer gave the OK

## Additional context

- #6941
- https://github.com/aptos-labs/aptos-core/pull/6934#issuecomment-1455721828

**Comment by lazaridiscom** [comment]
( @davidiw, @wrwg @zekun000 )

Hello!

Contributing account "abebeos" was blocked on aptos-labs, without notice, cause, process.

"Our goal is to make contributing to Aptos Core easy and transparent"
https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#contributing

In the name of transparency, please inform me who blocked the access of account "abebeos" and marked the (clearly in-topic, contributing) messages as "spam".

You can review the contributions here:

* PRs many were merged
  * https://github.com/search?q=repo%3Aaptos-labs%2Faptos-core+involves%3Aabebeos&type=pullrequests&s=created&o=asc
* Issues
  * https://github.com/search?q=repo%3Aaptos-labs%2Faptos-core+involves%3Aabebeos&type=issues&s=created&o=asc

All messages were marked as "spam", even within the merged PRs.

I ask you to restore the access of "abebeos" and ensure something like this does not happen in future.

Thank you.

P.S.:

> Your message wasn't delivered to conduct@aptoslabs.com because the address couldn't be found, or is unable to receive mail.
