### ISSUE TITLE
[BlockSTM] Avoid unnecessary re-validation in BlockSTM 

### ISSUE THREAD

**Issue by sitalkedia** [aptos-labs/aptos-core#6951]
# 🚀 Feature Request

Today, BlockSTM does 4-10x higher number of validations than executions - this is even in case of the block doesn't have any conflict. This is because of a side effect of optimization that lets BlockSTM skip the validation index and validate higher index transactions. When a higher index transaction finishes, we immediately validate that transaction however, the first incarnation of the lower index transaction always writes outside of its previous write set (which is null), which causes the validation index to fallback and causes a bunch of unnecessary re-validation.

**Comment by gelash** [comment]
The ideas of @sitalkedia and @sasha8 should work - in particular, we should be able to only touch the next task selection heuristic. It currently reads and compares validation and execution indices, but if validation index is lower, we can additionally check that execution status at the observed validation index is not Ready_to_execute(0), executing(0) or suspended(0), i.e. it has been executed at least once. If this doesn't hold, the thread picks an execution task.

Note that this additional logic would ensure the validation index doesn't skip over indices and go faster than the initial execution wave, and the only observable difference from the prior logic would be that sometimes when previously we would pick a validation task we'll now pick the execution task (as desired) - however, we can't get stuck, as eventually the first execution of each transaction finishes and validation tasks will continue to be picked up as before.

We should check that there is no overhead from the additional locking - and it should be simple to get rid of it if and when we need by adding another atomic indicator per txn (or a counter).

**Comment by gelash** [comment]
Now that https://github.com/aptos-labs/aptos-core/pull/7034 is also merged, should we close this issue?
