### ISSUE TITLE
[Feature Request] Add "is_view_function" flag in ABI to differentiate view functions from others

### ISSUE THREAD

**Issue by jillxuu** [aptos-labs/aptos-core#6964]
# 🚀 Feature Request

Explorer's implementing the feature to enable contract function reads. In order for us to get a list of view functions, we need a way to differentiate whether a function is view function or not. Currently there's no good ways of doing so except parsing through the source code, which's not dev friendly nor efficient.

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**
Similar to what we see in get modules API call, there's a flag in the ABI called "is_entry" to differentiate entry functions from others. We'd like to have something along the line for view functions.

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes but need SC support / help.

**Comment by wrwg** [comment]
I don't understand this feature request. Doesn't the current ABI in the explorer only show `entry` functions? How can an is_view attribute be helpful?

FWIW, a better ABI has been on the roadmap for a while, but this is a bit more difficult than just adding an attribute.

**Comment by jillxuu** [comment]
@wrwg, thanks for the feedback. We are currently working on new features on explorer where we display contract source code if it exists, provide functionalities to read and write to contracts. Therefore we need a way to tell that a function is a view function so that these functions can be queried to get the function return without mutating the state. 
here's the [design](https://www.figma.com/file/HoHbGZxCJYfyR3A1PRjvWG/Contract-features---View-code%2C-Read%2C-Write?t=RKIyIyppZb7AXeKr-0) we have put up, which helps understanding what product we're building.

Yes based on the conversation, it's not a very small effort to pull it through, but it does bring benefits to the dev ecosystem.

**Comment by banool** [comment]
This is done.
