### ISSUE TITLE
How to create a new token with a transfer function written by myself?

### ISSUE THREAD

**Issue by 0x18A** [aptos-labs/aptos-core#6992]
I am creating a new token on aptos. I want to transfer it by my own transfer function instead of the transfer function of 0x1, what should i do?

**Comment by e99243506bigplay** [comment]
Hint:
You need `token::create_token_id_raw` for query your TokenStore and operation Tokens.
Tools: `token::withdraw_token` `token::deposit_token` `token::balance_of`

Further more, you can't make a function that same effect like `0x1::token::transfer` able to direct transfer token to someone.

**Comment by davidiw** [comment]
Are you hoping to prevent the default transfer from working?

**Comment by lbmeiyi** [comment]
This will be addressed in Token V2. Closing for now. thanks!
