### ISSUE TITLE
api error:web_framework_error

### ISSUE THREAD

**Issue by zhy827827** [aptos-labs/aptos-core#6995]
my aptos full node when run: (aptos version 1.2.4 &&aptos version 1.2.5  )
curl 'http://127.0.0.1:8080/v1/accounts/0x4823b29c5f3b501a074ebfc5c82b38966cf12a0613d35f836b41bb8423a82cb8/resource' |jq
{
  "message": "not found",
  "error_code": "web_framework_error",
  "vm_error_code": null
}
**and**
 curl -v  'http://127.0.0.1:8080/v1/accounts/0x4823b29c5f3b501a074ebfc5c82b38966cf12a0613d35f836b41bb8423a82cb8/resource/0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>'
{
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
}

**/opt/fullnode.yaml:**

base:
  role: "full_node"
  data_dir: "/opt/data"
  waypoint:
    from_file: "/opt/genesis/waypoint.txt"
execution:
  genesis_file_location: "/opt/genesis/genesis.blob"
full_node_networks:
- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  max_inbound_connections: 100
mempool:
  shared_mempool_max_concurrent_inbound_syncs: 16 # default 4
  max_broadcasts_per_peer: 4 # default 1
  default_failovers: 0 # default 3
  shared_mempool_batch_size: 200 # default 100
  shared_mempool_tick_interval_ms: 10 # default 50

api:
  enabled: true
  address: "0.0.0.0:8080"

**Where do I configure the problem?**

**Comment by davidiw** [comment]
Not sure I follow the problem or issue. So more info might be needed.

You're not querying resources correctly, you need an "s" at the end of the first query

Your second query isn't querying a legitimate resource, this is the right query on testnet: `https://testnet.aptoslabs.com/v1/accounts/0x4823b29c5f3b501a074ebfc5c82b38966cf12a0613d35f836b41bb8423a82cb8/resource/0x1::coin::CoinInfo>0x1::aptos_coin::AptosCoin>`

Please try again with corrected URLs and feel free to re-open.

**Comment by zhy827827** [comment]
I found this issues:it is caused by the version.

By the way, how many blocks are reserved for fullnode by default? How many historical  blocks can be debugged?

**Comment by davidiw** [comment]
Historically? https://aptos.dev/guides/data-pruning
