### ISSUE TITLE
[Bug] Aptos CLI v1.0.7 breaks unit testing support

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#7040]
@gregnazario @wrwg 

# Description/steps to reproduce

v1.0.6 of `aptos` has no problem running all of the unit tests in the [Econia](https://github.com/econia-labs/econia) suite (347 unit tests total), but v1.0.7 fails with the following tracebacks:

```bash
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Econia
Running Move unit tests
2023-03-09T23:36:49.874516Z ERROR /Users/brew/Library/Caches/Homebrew/cargo_cache/git/checkouts/move-0639dd674f581c30/69c1bd0/language/move-vm/runtime/src/logging.rs {"message":"[VM] Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!\nError: VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: Some(\"program too complex (in `<unknown>` with `7796455 current + 345975 new > 8000000 max`)\"), exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000000, name: Identifier(\"market\") }), indices: [(FunctionDefinition, 118)], offsets: [] }"}
[ FAIL    ] 0x0::market::test_swap_invalid_quote

Test failures:

Failures in 0x0::market:

┌── test_swap_invalid_quote ──────
│ Test did not error as expected. Expected test to abort with code 8 originating in the module 0000000000000000000000000000000000000000000000000000000000000000::market but instead it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 0000000000000000000000000000000000000000000000000000000000000000::market rooted here
└──────────────────

Test result: FAILED. Total tests: 1; passed: 0; failed: 1
{
  "Error": "Move unit tests failed"
}
```

The behavior in question can be reproduced by calling `source scripts.sh tf test_swap_invalid_quote` from the top level of the [Econia](https://github.com/econia-labs/econia) repository: this is just a representative single test failure (the `tf` shorthand runs a test with the filter argument), but plenty of other tests fail as well.

# Additional information

The unit tests function as expected for the following standalone modules which do not have friends (data structure libraries):

* `source scripts.sh tf tablist::`
* `source scripts.sh tf avl_queue::`

But all tests fail for modules associated with the friend/use network:

* `source scripts.sh tf resource_account::`
* `source scripts.sh tf market::`

Based on the error code it appears the `v1.0.7` introduces some kind of breaking change associated with the size required for compilation:

```zsh
Some(\"program too complex (in `<unknown>` with `7796455 current + 345975 new > 8000000 max`)
```

Note that even though unit tests fail on `v1.0.7`, the package can still be successfully compiled and published.

**Comment by wrwg** [comment]
@alnoki can you provide a pointer to the source of some of those failing tests? Are these rather large tests?

Background is that we shipped stronger restrictions on code complexity to protect the network from DoS attacks via the bytecode verifier. While this on the validators since over a week (via hotfix), its hitting the CLI now for the first time.

We can perhaps have some relaxation for tests, but I'd like to see the tests first.

**Comment by alnoki** [comment]
> @alnoki can you provide a pointer to the source of some of those failing tests? Are these rather large tests?
> 
> Background is that we shipped stronger restrictions on code complexity to protect the network from DoS attacks via the bytecode verifier. While this on the validators since over a week (via hotfix), its hitting the CLI now for the first time.
> 
> We can perhaps have some relaxation for tests, but I'd like to see the tests first.

@wrwg here is an example test that fails and is only one line:

https://github.com/econia-labs/econia/blob/0599945f9423af1223ce554dc8109ee8b07c2cfa/src/move/econia/sources/registry.move#L2044-L2055

The traceback:

```zsh
% pwd                                                         
/Users/alnoki/repos/econia/src/move/econia
% aptos move test --filter remove_recognized_market_not_econia
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Econia
Running Move unit tests
2023-03-10T17:52:26.058875Z ERROR /Users/brew/Library/Caches/Homebrew/cargo_cache/git/checkouts/move-0639dd674f581c30/69c1bd0/language/move-vm/runtime/src/logging.rs {"message":"[VM] Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!\nError: VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: Some(\"program too complex (in `<unknown>` with `7796455 current + 345975 new > 8000000 max`)\"), exec_state: None, location: Module(ModuleId { address: 3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200, name: Identifier(\"market\") }), indices: [(FunctionDefinition, 118)], offsets: [] }"}
[ FAIL    ] 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::registry::test_remove_recognized_market_not_econia

Test failures:

Failures in 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::registry:

┌── test_remove_recognized_market_not_econia ──────
│ Test did not error as expected. Expected test to abort with code 9 originating in the module 3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::registry but instead it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module 3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::market rooted here
└──────────────────

Test result: FAILED. Total tests: 1; passed: 0; failed: 1
{
  "Error": "Move unit tests failed"
}
```

As I mentioned above, I've deduced that it is not the size of the test that matters, but rather that the test in included in a group of modules that must all be compiled together: it appears that if the group exceeds a certain size then all tests for all modules in the group fail. In contrast modules that can be compiled standalone have no such faiures:

```bash
% aptos move test --filter tablist::         
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Econia
Running Move unit tests
[ PASS    ] 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::tablist::test_destroy_empty_not_empty
[ PASS    ] 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::tablist::test_iterate
[ PASS    ] 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::tablist::test_iterate_remove
[ PASS    ] 0x3c04538036604862c67261221a6167fa4ae5121d3649e29b330fa8c248b66200::tablist::test_mixed
Test result: OK. Total tests: 4; passed: 4; failed: 0
{
  "Result": "Success"
}
```

**Comment by wrwg** [comment]
Fix landed, but CLI still needs to be released

**Comment by alnoki** [comment]
@wrwg @gregnazario all tests pass as of `v1.0.8`
