### ISSUE TITLE
[aptos-cli] Add ability to pass in configuration as inputs on aptos init

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#706]
Currently, `aptos init` is an interactive process, where users put in values as they go.  However, it requires you to actively type things in, and that can be hard when the values are long or complicated.

So, we should allow overwriting by taking in values.  The values that should be supported are:

```
--private-key
--private-key-file
--url
--faucet-url
```

The account address and public key should be derived from the private key.

**Comment by kris524** [comment]
Hi @gregnazario, can I pick this one? :)

**Comment by gregnazario** [comment]
Yes, I won't touch this one :)  Though it may have merge conflicts with my current PR that's out https://github.com/aptos-labs/aptos-core/pull/692

**Comment by gregnazario** [comment]
Sorry @kris524 again, but I needed to get this one done faster, so I've also done it in a pull request :(

**Comment by kris524** [comment]
Hi @gregnazario no problem, I was exploring the files and started making changes. But obviously I'm slow and such things need to get done fast. I will look for another issue I can pick up. 

Apologies I'm slow

**Comment by gregnazario** [comment]
No worries!  Everything is moving so fast (and I didn't expect this one to be needed as quickly).
