### ISSUE TITLE
[Docs] Document and announce CLI features for generating testing coverage and passing bytecode as dependencies

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#7060]
# Aptos Documentation Issue

## Location

Where should this information land if new? (Start Aptos, Build Apps, Run Nodes, Reference, etc.) 

What are the existing URLs containing the issue, if any?

https://aptos.dev/cli-tools/aptos-cli-tool/use-aptos-cli/#compiling-and-unit-testing-move

https://aptos.dev/guides/move-guides/aptos-move-guides/

## Description

Teng and I met to document two new Move-related features landing in the Aptos CLI:

1. Generate testing coverage information for Move packages.

2. Support for using bytecode as dependencies for compilation and publishing of Move packages.

For #1, Teng notes this functionality existed in the Move compiler and has ported the functionality to Aptos in:
https://github.com/aptos-labs/aptos-core/pull/6893

We will add that information to the Using the Aptos CLI doc, below the section highlighted above.

For #2, Teng has an excellent internal doc titled "Use bytecode as dependencies in compilation" we will edit, convert and place among the Move guides, linking from the same #compiling-and-unit-testing-move section of Using the Aptos CLI above.

We are also asking @thepomeranian to help us get these features in the Aptos CLI release notes. We can help summarize. Frances, let us know what you need from us.

## Audience

Our audience is Move developers.

## Additional context

We recorded the meeting, so I will pull details from that as well.

**Comment by rahxephon89** [comment]
Hi @clay-aptos, this [page](https://aptos.dev/guides/move-guides/book/unit-testing/#running-unit-tests) is dedicated to introducing move unit testing. Maybe we should add coverage to this page too.

**Comment by clay-aptos** [comment]
> Hi @clay-aptos, this [page](https://aptos.dev/guides/move-guides/book/unit-testing/#running-unit-tests) is dedicated to introducing move unit testing. Maybe we should add coverage to this page too.

Hi Teng, we can certainly do that.  In fact, @wrwg is working on a tutorial that mentions test coverage too. Perhaps we can update both to point to the page we have in development. Thank you!

**Comment by wrwg** [comment]
> > Hi @clay-aptos, this [page](https://aptos.dev/guides/move-guides/book/unit-testing/#running-unit-tests) is dedicated to introducing move unit testing. Maybe we should add coverage to this page too.
> 
> Hi Teng, we can certainly do that. In fact, @wrwg is working on a tutorial that mentions test coverage too. Perhaps we can update both to point to the page we have in development. Thank you!

Oh wow. Good find Teng! I wasn't aware that the Move book (just recently copied into our docset) uses the Move CLI to document unit testing. We should rewrite this to use the Aptos CLI. Also as we do we should definitely document the coverage.

In general, I think we should document all `aptos move *` commands in our version of the Move book, as a kind of reference to the language platform. Do you want to take a try on updating the unit test page, @rahxephon89 ?

**Comment by wrwg** [comment]
PS. The test documentation is also outdated. I think there is a `location = Self` field missing in the abort specs.

**Comment by rahxephon89** [comment]
@wrwg The [PR](https://github.com/aptos-labs/aptos-core/pull/7205) to add documents for coverage and bytecode as dependencies have been merged. I will add the corresponding content to the test document when fixing the Aptos move book.

**Comment by clay-aptos** [comment]
Let's track the site link fixes to the book and tutorial here:
https://github.com/aptos-labs/aptos-core/issues/7364#issuecomment-1485361832

Closing this out. Please reopen if you see anything amiss here. Thank you, Teng, Wolfgang and team!
