### ISSUE TITLE
[aptos-cli] Improve aptos move test

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#709]
- [ ] Allow to run single unit tests
- [ ] Convert entire output to JSON only
- [ ] Improve output to tell more than just success & failure
- [ ] Add progress bar for waiting on compile etc.

**Comment by mkurnikov** [comment]
I would like to be able to provide multiple module or function names for the command. 
```
aptos move test --filter test_function_a --filter test_function_b
```
