### ISSUE TITLE
[Prover] Issues with Boogie

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#7121]
[Prover] Prover isn't compatible to the newest Boogie (2.15.9) due to its breaking change
https://github.com/move-language/move/issues/626

[Move Prover] Move prover returns: cannot extract version from Users/username/.dotnet/tools/boogie
https://github.com/move-language/move/issues/534

**Comment by e99243506bigplay** [comment]
That is why I first time to manually install move prover dependencies with Boogle latest version, later to running prover are failed to showing massive error messages, make move prover is unusable.

**Comment by wrwg** [comment]
> That is why I first time to manually install move prover dependencies with Boogle latest version, later to running prover are failed to showing massive error messages, make move prover is unusable.

Yes, because you did not follow the instructions how to install the prover, as given here: https://aptos.dev/cli-tools/install-move-prover

**Comment by rahxephon89** [comment]
This issue is obsolete because we are using a newer version of boogie 3.2.4.
