### ISSUE TITLE
[Feature Request] Make prover tool installation independent of aptos-core

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#7148]
Currently, as described in https://aptos.dev/cli-tools/install-move-prover, one needs to clone the aptos repo to install prover tools. That is not a good UX. We need to make those tools installable independent of the repo.

@rahxephon89 @junkil-park

**Comment by rahxephon89** [comment]
Maybe we could write a script similar to `dev_setup.sh` for users to install the prover dependencies conveniently.

**Comment by gregnazario** [comment]
We also, could possibly have a command in the CLI that installs the dependencies so you don't have to leave the packaged CLI

**Comment by junkil-park** [comment]
Yeah, that's a good idea. 

We may need an Prover installation script that lives outside of the `aptos-core` repo anyway (like `https://aptos.dev/scripts/install_cli.py`). We can make the Aptos CLI invoke it when the installation is needed.

**Comment by wrwg** [comment]
Script in general is better because this allows people to fix stuff if installation goes wrong. (Which it always does -- ideally indeed would a fool proof way to install but it is hard because of Boogie/.Net :-/ )

**Comment by rahxephon89** [comment]
I added a repo independent script in this [PR](https://github.com/aptos-labs/aptos-core/pull/7173)
