### ISSUE TITLE
[Bug] Unit test failure doesn't show stack trace when there's a native function involved

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#7224]
When the error comes from within a native function, there doesn't seem to be any stack trace shown. For example:

┌── test_create_and_transfer ──────
│ error[E11001]: test failure
│     ┌─ /Users/kevin/aptos-core/aptos-move/move-examples/token_objects/../../framework/aptos-framework/sources/object.move:148:16
│     │
│ 148 │     native fun exists_at<T: key>(object: address): bool;
│     │                ^^^^^^^^^
│     │                │
│     │                INTERNAL TEST ERROR: Unexpected Verification Error
│ Test was not expected to error, but it gave a MISSING_DEPENDENCY (code 1021) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::object rooted here
│     │                In this function in 0x1::object
│ 
│ 
└──────────────────

Test result: FAILED. Total tests: 1; passed: 0; failed: 1
{
  "Error": "Move unit tests failed"
}

**Comment by runtian-zhou** [comment]
closed by #9936
