### ISSUE TITLE
[Bug] Conflicting usage requirements for Std::Signer in CLI compile vs test

### ISSUE THREAD

**Issue by magnum6actual** [aptos-labs/aptos-core#725]
# 🐛 Bug

When compiling a simple module, the compiler complains about unused alias of Signer:
```
warning[W09001]: unused alias
  ┌─ sources/TicketTutorial.move:2:14
  │
2 │     use Std::Signer;
  │              ^^^^^^ Unused 'use' of alias 'Signer'. Consider removing it
```
Removing the `use` statement allows successful compiling & publishing.  However, after removing the `use` statements, in module unit tests no longer run, with the following error:
```
error[E03002]: unbound module
   ┌─ sources/TicketTutorial.move:36:26
   │
36 │         let venue_owner_addr = Signer::address_of(&venue_owner);
   │                                ^^^^^^ Unbound module alias 'Signer'
```
Maybe there is a separate declaration for in-module unit testing that I'm not aware of. As it is, I have to go back and forth deleting and reinserting the use statement to test vs compile. This is probably an edge case where a particular `use` is needed for testing only - although I'm not completely clear why `Std::Signer` isn't needed for compiling here.
 
## To reproduce
This is the entirety of the module:
```
module TicketTutorial::Tickets {

	use Std::Vector;
    
	struct ConcertTicket has key, store, drop {
		seat: vector<u8>,
		ticket_code: vector<u8>,
		price: u64
	}

	struct Venue has key {
		available_tickets: vector<ConcertTicket>,
		max_seats: u64
	}
	
	const ENO_VENUE: u64 = 0;

	public fun init_venue(venue_owner: &signer) {
		let max_seats: u64 = 3;
		let available_tickets = Vector::empty<ConcertTicket>();
		move_to<Venue>(venue_owner, Venue {available_tickets, max_seats})
	}

	#[test(venue_owner = @0x1)]
    public(script) fun sender_can_buy_ticket(venue_owner: signer)  {
		
		let venue_owner_addr = Signer::address_of(&venue_owner);
		init_venue(&venue_owner);
		assert!(exists<Venue>(venue_owner_addr), ENO_VENUE);
    }
}
```
compiling with: `aptos move compile --package-dir sources`

testing with: `aptos move test --package-dir sources`

On commit b748229fd5008e1b969243563e284f31fa16ecbd

**Comment by gregnazario** [comment]
What's your `Move.toml` look like?  I know the `move-cli` defaults to create a package with the `StdLib` rather than `AptosFramework` which can cause some inconsistency in compile caching.

**Comment by magnum6actual** [comment]
I had lost the `Std:0x1` from the Move.toml somewhere.  Good to go now.

**Comment by traitmeta** [comment]
> 
how to solve this by modifying Move.toml?
