### ISSUE TITLE
[Bug][Move-compiler] Move compiler does not know mutable references cease to exist after the spec block

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#7250]
# 🐛 Bug

## To reproduce

When running the prover against the code:
```
  fun borrow_mut(): Table<u8, u64> {
        let t = table::new<u8, u64>();
        table::add(&mut t, 1, 2);
        let r = table::borrow_mut(&mut t, 1);
        spec {
           assert r == 2;
        };
        t
    }
```
The following compiler error will be generated:
```
error: invalid operation, could create dangling a reference
    ┌─ ./sources/test_table.move:158:9
    │
152 │         let r = table::borrow_mut(&mut t, 1);
    │                 ---------------------------- It is still being mutably borrowed by this reference
    ·
158 │         t
    │         ^ Invalid move of variable 't'
```
However, when the spec block is removed, no error will be generated. As pointed by @meng-xu-cs, "the compiler is aware that the spec block uses `r`, which is expected. But for some reason, the compiler does not know that `r` ceases to exist after the spec block. Hence, it is still considered as being used when `t` is moved. Hence the error message. "

**Comment by wrwg** [comment]
Teng, is the priority really low?

**Comment by rahxephon89** [comment]
> Teng, is the priority really low?

@wrwg I think so because the spec work is not blocked by it for now.

**Comment by rahxephon89** [comment]
To avoid the compiler error, we can manually add `assert!(*r == *r, 1)` after the spec block.
