### ISSUE TITLE
Add tap to Mushu

### ISSUE THREAD

**Issue by lbmeiyi** [aptos-labs/aptos-core#7260]
Every time we release tap to devnet we need to turn off the devnet fullnodes, wipe the DB, update the genesis and waypoint, restart, then restart the taps themselves. It'd be nice to automate this, and Mushu is our tool for doing k8s stuff.

See https://aptos-org.slack.com/archives/C03EP0XM99D/p1677769156322249.

**Comment by gregnazario** [comment]
Closing, does not belong in aptoos-core
