### ISSUE TITLE
[Feature Request]rocksdb multi_get improve read performance

### ISSUE THREAD

**Issue by nkysg** [aptos-labs/aptos-core#728]
# 🚀 Feature Request

## Motivation
There are some places it can use rocksdb multi_get improve read performance, like
https://github.com/aptos-labs/aptos-core/blob/main/storage/accumulator/src/lib.rs#L350
```rust
  fn get_hashes(&self, positions: &[Position]) -> Result<Vec<HashValue>> {
        positions.iter().map(|p| self.get_hash(*p)).collect()
    }
```
It use a for loop.It may be can use rocksdb multi_get improve read performance,
may be other places also can use.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

use rocksdb multi_get
**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by msmouse** [comment]
Closing as there's no immediate action planned on this topic.
