### ISSUE TITLE
[Bug][CLI] Coverage tool is prohibitively slow

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#7295]
@gregnazario @movekevin @wrwg @rahxephon89 #6893 

Running the [Econia](https://github.com/econia-labs/econia) unit test suite takes only about 17 seconds without coverage, but 
 over 7 minutes with coverage:

```zsh
# From inside Econia repo core dir
cd src/move/econia/
# Running without coverage
time aptos move test
...
Test result: OK. Total tests: 347; passed: 347; failed: 0
{
  "Result": "Success"
}
aptos move test  32.48s user 0.39s system 192% cpu 17.033 total
# Running with coverage
time aptos move test --coverage
...
+-------------------------+
| % Move Coverage: 100.00  |
+-------------------------+
Please use `aptos move coverage -h` for more detailed source or bytecode test coverage of this package
{
  "Result": "Success"
}
aptos move test --coverage  84.08s user 379.89s system 108% cpu 7:09.38 total
```

The coverage run in question also included up to two-minute delays between successive tests.

Run on a 2021 MackBook Pro M1 Max with 32 GB memory.

**Comment by wrwg** [comment]
Wow. Is it a big deal for you to flamegraph this?

**Comment by rahxephon89** [comment]
Thanks for the feedback, @alnoki! We will look into this. Btw, is it specific to Aptos CLI or it also happens for the Move CLI?

**Comment by rahxephon89** [comment]
@alnoki @wrwg When running test with`--coverage`,  `MOVE_VM_TRACE` will be set, which triggers the `trace` function and slows down the execution probably because of the file IO. There is no immediate solution for this but we will continue looking into it.

**Comment by wrwg** [comment]
Not sure whether this enormous performance problem is a result of i/o? In this time, you can fill up terra bytes. This sounds to me more like something goes non-linearly out of bound with the size of the test (and related to coverage), e.g. a dumb hasher in HashTable or something. Flamegraph would be really helpful, we can also do this ourselves, just recommend to do this first before assuming it is i/o. https://github.com/flamegraph-rs/flamegraph

**Comment by rahxephon89** [comment]
@wrwg I checked the flamegraph, the function `move_vm_runtime::tracing::trace` took about 93% of the total execution time and within it, aptos-core::fmt::write took about 87% of the execution time.

**Comment by alnoki** [comment]
> Thanks for the feedback, @alnoki! We will look into this. Btw, is it specific to Aptos CLI or it also happens for the Move CLI?

@rahxephon89 I haven't used the Move CLI with coverage in months because it does not natively support Aptos Framework tables, so I can not say for sure, but I do recall being able to do on the order of a hundred tests or so with vector-only operations without significant performance delays.

> Not sure whether this enormous performance problem is a result of i/o? In this time, you can fill up terra bytes. This sounds to me more like something goes non-linearly out of bound with the size of the test (and related to coverage), e.g. a dumb hasher in HashTable or something. Flamegraph would be really helpful, we can also do this ourselves, just recommend to do this first before assuming it is i/o. https://github.com/flamegraph-rs/flamegraph

@wrwg I haven't used the flamegraph tool before but thank you for the reference! I'll check this out moving forward if I have other performance problems, but for now it looks like you and @rahxephon89 have isolated it to some problem areas.

**Comment by alnoki** [comment]
Bumping to remove stale label

**Comment by rahxephon89** [comment]
Hi @alnoki, sorry for the long overdue response. With more experiments, we now believe that the slow execution time of the coverage tool is indeed due to the `write` operation when generating the trace file. With the change in #9944, the execution time is reduced to less than 3mins. The PR still needs to be further validated since the format of the trace file is changed. At the same time, you could check this commit out and test it on your machine. We will let you know once it is landed.

**Comment by rahxephon89** [comment]
@alnoki The PR has been merged. It would be nice if you could test on the newest main on your end and let us know if there are any other issues. Thanks

**Comment by alnoki** [comment]
Thanks for the heads up! Is this in a CLI release or will it require building from source?

**Comment by alnoki** [comment]
@rahxephon89 Confirming that I just ran v2.3.0 from `brew` and it is much faster, thanks!
