### ISSUE TITLE
[Bug] Improve test coverage for coin_client and token_client

### ISSUE THREAD

**Issue by movekevin** [aptos-labs/aptos-core#7314]
coin_client and token_client in the SDK have very minimal test coverage, we need to add more tests. This would be important to make sure when we start adding support for token v2 and fungible assets, there are no bugs/issues.

**Comment by lbmeiyi** [comment]
@gregnazario pls update us, thanks.

**Comment by gregnazario** [comment]
We are moving towards replacements for both in Fungible assets and Token objects, so closing for those.
