### ISSUE TITLE
[Bug] Python SDK is out of date on the PyPI

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#7351]
The Python SDK is at version `0.6.0` ([ref 1](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/python/sdk/setup.py#L22), [ref 2](https://github.com/aptos-labs/aptos-core/blob/154e450a77c593e93bbd1ba224bb2fd532d4ffb8/ecosystem/python/sdk/pyproject.toml#L3)), but the PyPI reflects [0.5.1](https://pypi.org/project/aptos-sdk/).

@davidiw @banool is the PyPI release process automated?

**Comment by dannysheridan** [comment]
@alnoki if you want to use a publishing pipeline to keep PyPI up to date, check out our open source project: www.buildwithfern.com

**Comment by banool** [comment]
It is not currently automated, we can look at making a release this week.

**Comment by alnoki** [comment]
Bump

**Comment by banool** [comment]
Just released a new version (0.6.1) and included publishing instructions and the like: https://github.com/aptos-labs/aptos-core/pull/8149.

**Comment by dannysheridan** [comment]
@banool are you interested in automating the generation and publishing of the Python SDK? here's [a python SDK](https://github.com/vellum-ai/vellum-client-python) where the team uses Fern.

**Comment by banool** [comment]
Hi, I've previously spoken with someone from Fern at length and we decided that Fern was not a good fit for our needs, given we're moving away from the OpenAPI stack.

**Comment by davidiw** [comment]
tonight!
