### ISSUE TITLE
[Docs] Some docs missed

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#7405]
# Aptos Documentation Issue

I get 404 error on upgrading move modules doc.

For example:

https://aptos.dev/guides/move-guides/upgrading-move-code/#upgrade-policies

**Comment by clay-aptos** [comment]
Thanks for the report, @borispovod ! I believe this is fixed (redirected) with:
https://github.com/aptos-labs/aptos-core/pull/7370/files

**Comment by clay-aptos** [comment]
And I am announcing this migration in:
https://github.com/aptos-labs/aptos-core/pull/7415

So closing this out. Thanks.
