### ISSUE TITLE
[Bug] Token APIs

### ISSUE THREAD

**Issue by MartianSiddharth** [aptos-labs/aptos-core#742]
# 🐛 Bug

The new API structure makes it hard to retrieve users' tokens. 
The following steps are required to get a token's data from the account which minted a token:

1. Use the Collection handle and collection name to get the tokens in that collection
2. Use the token's handle received and the token name, make another query to get the token data

There are two ways to get a token from an account that received the token:

1. Using Gallery: Get the token ID from somewhere (do we have to store it locally?) and use it to retrieve the token's data. The token data received using this method is incomplete and doesn't consist of the token description and the token uri.
2. Using Creator's Collection: Get the creator address, collection name and token name (same as token ID, where do we store it?). Repeat the steps for getting a token from the creator account (as mentioned above)

The problem is, where do we store the information about the token creator/ token name/ collection name? This information is not currently accessible from the account resources of the user.

The second problem is that the gallery table doesn't contain complete information about the token.

These problems make it really hard for testing NFT related code and impacting projects where you need to fetch the NFT data of users.

## To reproduce
I am describing the API calls I made for each step.
### For getting the collections handle of a user:
POST https://fullnode.devnet.aptoslabs.com/tables/310182765781555669148448757155360386693/item
{
    "key_type": "0x1::ASCII::String",
    "value_type": "0x1::Token::Collection",
    "key": "AliceCollection"
}
### For getting the tokens using the token handle from the above query
POST https://fullnode.devnet.aptoslabs.com/tables/39777417351404590782294261868704095696/item
{
    "key_type": "0x1::ASCII::String",
    "value_type": "0x1::Token::TokenData",
    "key": "AliceToken"
}
### For getting the token data using the gallery handle
POST https://fullnode.devnet.aptoslabs.com/tables/241439479000841577456467733707553032881/item
{
    "key_type": "0x1::GUID::ID",
    "value_type": "0x1::Token::Token",
    "key": {
        "addr": "0x225e22023aac5522025c4f9adc79fd19d739b6ffc0998b7d8b462fffb37ca1de",
        "creation_num": "2"
    }
}

**Comment by sitalkedia** [comment]
cc - @davidiw wondering if we should keep the creator's address as a part of the `Token` struct so that we can use that to query the creator's account for the `TokenData` .

**Comment by MartianSiddharth** [comment]
We can also consider storing the token_creation_num or {collection name and token name} along with the creator's address. This will complete the Token ID that we need to pass to get the Token

**Comment by davidiw** [comment]
The fundamental issue is that storing all this data in a single resource quickly becomes impractical due to storage requirements. This is why there are indexer projects. We're exploring building one in the node for standard assets. I'm also working on unifying token ids, the creators address, collection, token and token metadata type are actually a globally unique id too.

As a short term hack, we could create a vector of token ids within the gallery resource.

**Comment by davidiw** [comment]
A longer term alternative would just be to emit the events that are so desperately missing :). I'd prefer events, but recognize that that may increase development burdens by too much. Will ask in Discord too.

**Comment by MartianSiddharth** [comment]
Copying my discord reply here.
I agree with events too. One thing to keep in mind with this approach would be to store the creator of a token (and not the sender of the token) in the received event. Otherwise, it will be a chain of API calls leading back to the creator, which is not scalable. I can contribute on this end but would need some support

**Comment by MartianSiddharth** [comment]
Thanks for the changes made in https://github.com/aptos-labs/aptos-core/pull/748
Calling the API https://fullnode.devnet.aptoslabs.com/accounts/%7Baddress%7D/events/0x1::Token::TokenStore/deposit_events gives the events with the TokenId needed to get details about the token
Ref: https://fullnode.devnet.aptoslabs.com/spec.html#/operations/get_events_by_event_handle
