### ISSUE TITLE
[since last update building from source code problems on VPS]

### ISSUE THREAD

**Issue by mathematicw** [aptos-labs/aptos-core#749]
# bilding from source code problems on VPS
Since the launch of devnet all the updates followed have been installed with no issues.
After the last update (29.04.22) the problem occurred: tries to build Aptos node from source code using VPS (in my case Contabo, so KVM virtualization) led to errors:
_`note: collect2: fatal error: ld terminated with signal 9 [Killed]`
`could not compile 'backup-cli' due to previous error'
`fatal error: ld terminated with signal9 [Killed]`_
ultimately everything leaded to _error: build failed_
The problem is (obviously) bc of virtualization. Both machines meet the requirements: 6/16/400 and 10/64/1600; no other significant loading from other software were detected.

The problem solved: 
## To reproduce
limiting the simultaneous jobs for rust cargo:
**`cargo build --verbose --jobs 1`**
This leads the node building success.

**Stack trace/error message**
```
```

## Expected Behavior
the building should be possible with this hardware, initial installation and all previous updates were passed with absolutely no issues

## System information
last update from April 29
rustc 1.60.0 (7737e0b5c 2022-04-04)
Contabo VPS 6/16/400 and 10/64/1600 Ubuntu 20.04.4 LTS

**Comment by davidiw** [comment]
if the issue persists, please re-open.
