### ISSUE TITLE
[Docs] Add example demonstrating how to execute a Move script with the TS SDK

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#7507]
# Aptos Documentation Issue
## Description
We have this already for the CLI (https://aptos.dev/guides/move-guides/move-scripts) and Rust (https://stackoverflow.com/questions/74452702/how-do-i-execute-a-move-script-on-aptos-using-the-rust-sdk), we just need to expand it to TS.

**Comment by clay-aptos** [comment]
If we are in fact talking about the same scripts, we also have this for Python:
https://aptos.dev/tutorials/your-first-multisig

I am asking @saharct if he would like to take this on. Along the way, we should update the Move scripts page to link to all of these example uses.

Christian, please let me know if you can't get to this or need help. Thanks!

**Comment by saharct** [comment]
@clay-aptos, I'd love to take this on!

**Comment by clay-aptos** [comment]
> @clay-aptos, I'd love to take this on!

You are my hero, @saharct !

**Comment by asfman** [comment]
the example  of execute move script with the ts sdk in this link: https://aptos.dev/en/build/smart-contracts/scripts/running-scripts can't work, @banool  can you check it ?
