### ISSUE TITLE
[Feature Request] Add `Debug` module with `#[test_only]` print function to the stdlib

### ISSUE THREAD

**Issue by mkurnikov** [aptos-labs/aptos-core#751]
# 🚀 Feature Request

Let's add `Debug` module with print function to the aptos-core's `move-stdlib`. See the example here https://github.com/pontem-network/move-stdlib/blob/main/sources/Debug.move
It was also at some point available in the original move stdlib. 

## Motivation

It's very useful to be able to introspect objects at time of testing. This function is basically the only debugging feature there is. 

## Pitch

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes.

**Comment by gregnazario** [comment]
that would be pretty cool.  We did just add debug print and I think tracing for `aptos move test` https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos/src/move_tool/aptos_debug_natives.rs
