### ISSUE TITLE
[Feature Request][Move-prover] Generating error message when the spec is misplaced 

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#7514]
# 🚀 Feature Request

Current, if a spec for module B is by accidentally added to A.spec.move, the prover can still generate the spec. Maybe it would be better for the prover to generate an error message instead.

**Comment by aalok-t** [comment]
The compiler does not require specification for a module `A` to be in a file named `A.spec.move`. As of now, the spec and modules may be in any files that end in `.move` under the same directory. Implementing the requested feature by requiring that the specifications for any modules in a file `modules.move` must be in `modules.spec.move` is highly restrictive and disruptive.

The following is an example of the current flexibility: [test-move.zip](https://github.com/aptos-labs/aptos-core/files/12875313/test-move.zip)
