### ISSUE TITLE
[Docs] Enhance NFT documentation for artists

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#7531]
# Aptos Documentation Issue

## Location

Where should this information land if new? (Start Aptos, Build Apps, Run Nodes, Reference, etc.) 

Tokens menu

## Description

How would you describe the issue?

While working on a revised developer hub (tracked in https://github.com/aptos-labs/aptos-core/issues/7496) , some questions arose:

---
1. I saw in Docs line “The two most common types of NFT are event ticket / certificates and profile picture NFTs.” But I can see only Profile pictures examples published on Topaz. And the whole page is biased on this only one type of NFTs. Can we include any information about Ticket/Certificates usage?

2. What about videos, VR and other `properties.category`? Do we have examples of such NFTs?

3. Are steps in *Creating NFTs* comprehensive? Is there something missing? Can you explain in steps what an NFT artist is supposed to take in order to have a collection like [[this](https://www.topaz.so/collection/Aptos-Monkeys-f932dcb983)](https://www.topaz.so/collection/Aptos-Monkeys-f932dcb983) published?

4. When a minted token gets associated with an image of a Monkey from the link above? Is it off-chain url property I need to set up before minting?

5. What is the price of minting? Is it high or low comparing to other platforms?
---

What needs changing?

We need to better address this new audience.

## Audience

NFT artists

**Comment by cathyaptos** [comment]
1. Check out Kydlabs, our partners for ticketing! There's lots of examples of events where NFTs are used as tickets. 
2. We support these asset types but we havent seen a lot of uses of this yet 
3. 
4. Yea the assets needed to be uploaded on Arweave or some other storage solution. I think the CLI tool instructions should cover this 
5. Yes! Minting on Aptos is cheap but I need to get the exact number for comparison.

**Comment by clay-aptos** [comment]
Thanks, @cathyaptos ! I will look into what Kydlabs is doing. @antiflasher, we should also link into this document for publishing NFTs:
https://aptos.dev/concepts/coin-and-token/nft-minting-tool/

@lightmark , I have added you as we should work together to make the mint tool doc even simpler to use. Will follow up with questions.

@0xchloe , may we split the Mint NFTs with the Aptos CLI page into sub-pages for easier links into the material?
https://aptos.dev/guides/move-guides/mint-nft-cli/

Thanks, all.

**Comment by antiflasher** [comment]
> @antiflasher, we should also link into this document for publishing NFTs: https://aptos.dev/concepts/coin-and-token/nft-minting-tool/
@clay-aptos, previously you gave me another link for Publishing NFTs (https://aptos.dev/guides/move-guides/mint-nft-cli/#publish-the-module). Do we replace it with https://aptos.dev/concepts/coin-and-token/nft-minting-tool/ or should we have both of them?

**Comment by clay-aptos** [comment]
> > @antiflasher, we should also link into this document for publishing NFTs: https://aptos.dev/concepts/coin-and-token/nft-minting-tool/
> 
> @clay-aptos, previously you gave me another link for Publishing NFTs (https://aptos.dev/guides/move-guides/mint-nft-cli/#publish-the-module). Do we replace it with https://aptos.dev/concepts/coin-and-token/nft-minting-tool/ or should we have both of them?

Hi @antiflasher , I would use both for now.

**Comment by clay-aptos** [comment]
Here is the link to the SDK doc:
https://aptos.dev/tutorials/your-first-nft
