### ISSUE TITLE
[Feature Request] Test for sequential / parallel execution-only performance

### ISSUE THREAD

**Issue by danielxiangzl** [aptos-labs/aptos-core#7544]
# 🚀 Feature Request

Adding tests for execution-only performance, to ensure the TPS numbers do not degrade after any change on the VM or the parallel executor. 

The following set of tests would be great to have:
1. Sequential execution performance test. Having **an isolated machine** running the sequential executor for certain block sizes and calculate the average throughput numbers. Compare the numbers before / after the change. Ideally to make this test land blocking. 
2. Parallel execution performance test. Having **an isolated machine** (ideally single-socket with enough number of cores, i.e., AMD EPYC CPU) running the parallel executor for various concurrency level (# threads), conflicts rate (# accounts) and block sizes, and calculate the average throughput numbers. Compare the numbers before / after the change.

**Comment by perryjrandall** [comment]
A simple start here and lets iterate https://github.com/aptos-labs/aptos-core/pull/7546

**Comment by danielxiangzl** [comment]
PR here: https://github.com/aptos-labs/aptos-core/pull/7552
