### ISSUE TITLE
[TS SDK RFC] Add axios wrapper

### ISSUE THREAD

**Issue by 0xjinn** [aptos-labs/aptos-core#7590]
Creating this issue to keep track and remind me of creating axios wrapper down the road.

Down the road, in addition to adding "User-Agent" to request header, there could be more stuff needed to intercept the axios request we send to API and Indexer. It would be a good idea to create an `axios` wrapper to keep everything in one piece

**Comment by cybercent** [comment]
Aptos SDK does not work in browser extensions due to the use of `axios`.
Would the proposed wrapper solve this issue ?
