### ISSUE TITLE
[Bug][Indexer] Incorrect current_table_items items.

### ISSUE THREAD

**Issue by fgfm999** [aptos-labs/aptos-core#7602]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```GQL
query MyQuery {
  current_table_items(
    where: {table_handle: {_eq: "0xd4e4e90ccdc627a47729038b61aa57443b8118bb2fcc6525745ee26c4b16b98e"}}
  ) {
    key
    last_transaction_version
  }
  table_items(
    where: {table_handle: {_eq: "0xd4e4e90ccdc627a47729038b61aa57443b8118bb2fcc6525745ee26c4b16b98e"}}
  ) {
    key
    transaction_version
  }
}

```

**Query Result**
```JSON
{
  "data": {
    "current_table_items": [
      {
        "key": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea04636f696e0154",
        "last_transaction_version": 18343958
      }
    ],
    "table_items": [
      {
        "key": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea04636f696e0154",
        "transaction_version": 18343958
      },
      {
        "key": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea04636f696e0154",
        "transaction_version": 18344436
      }
    ]
  }
}
```

## Expected Behavior

the `transaction_version` of `current_table_items` should be `18344436`

## System information

https://cloud.hasura.io/public/graphiql?endpoint=https://indexer.mainnet.aptoslabs.com/v1/graphql

## Additional context

I checked the `current_table_items` code, it already has a `WHERE current_table_items.last_transaction_version <= excluded.last_transaction_version`  for the upsert.
I'd run two indexer myself, one has the same result as the official indexer, the other had the correct result. So i guess it was caused by  concurrent issues.
If you figured out what cause this, please also let me know, thanks

**Comment by bowenyang007** [comment]
Hmm we did backfill a few times after so it got fixed at some point. It was likely a transient issue at the time.
