### ISSUE TITLE
[Docs] Add Move Prover to Windows dev environment setup script and test Windows support

### ISSUE THREAD

**Issue by saharct** [aptos-labs/aptos-core#7605]
## Description
Currently, the Windows dev environment [setup script](https://github.com/aptos-labs/aptos-core/blob/2e646fc66bd8bf7792ff5bd0a0906f6d26020203/scripts/windows_dev_setup.ps1) is more limited than the [Unix version](https://github.com/aptos-labs/aptos-core/blob/2e646fc66bd8bf7792ff5bd0a0906f6d26020203/scripts/dev_setup.sh). We need to allow for arguments and set up the Move Prover environment. Afterward, we should thoroughly test the Move Prover on Windows 10, 11, and Server 2022.

See the [related PR](https://github.com/aptos-labs/aptos-core/pull/7607) for my progress on the script. I'm currently testing on Windows 11 and will try it on Windows 10 and Server 2022 if I don't have any issues.

**Comment by clay-aptos** [comment]
Shall we announce this?
