### ISSUE TITLE
[Bug] aptos-node-v1.3.3.tar.gz is a blank tar file

### ISSUE THREAD

**Issue by lcgogo** [aptos-labs/aptos-core#7657]
tar -zxf of the https://github.com/aptos-labs/aptos-core/archive/refs/tags/aptos-node-v1.3.3.tar.gz is a blank folder

**Comment by davidiw** [comment]
unfortunately this is a side effect of us using github for release management.

1.3.3 is a hot fix release and hence we don't share source code in the relase.
