### ISSUE TITLE
[Docs] Write resource account guides for SDKs

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#7702]
# Aptos Documentation Issue

Currently we sort of have a guide for resource accounts for the CLI (though it is partially buried in another guide: https://aptos.dev/guides/move-guides/mint-nft-cli/#create-resource-account-and-publish-package). A common ask is how to do this in the SDKs too (particularly TS, but Python too).

We should ideally have a top level guide for making resource accounts and publishing packages to them and that guide should have tabs for each tool being used (CLI, TS SDK, Python SDK, Rust SDK).

**Comment by banool** [comment]
Awesome I missed this. This addresses the (non) problem of the docs being a bit buried. But it still only discussed how to work with resource accounts via the CLI.

**Comment by clay-aptos** [comment]
> Awesome I missed this. This addresses the (non) problem of the docs being a bit buried. But it still only discussed how to work with resource accounts via the CLI.

What about the contents starting with?

```
Writing custom smart contracts code: in the resource_account.move module, developers can find the resource account creation functions create_resource_account, create_resource_account_and_fund, and create_resource_account_and_publish_package. Developers can then call those functions to create resource accounts in their smart contracts.
```

And all of the text below describing accomplishing this in a `.move` file? I am adding @0xchloe for guidance too. Thanks, Daniel!

**Comment by banool** [comment]
What people want is a full end to end guide for how to create a resource account and publish it. The doc as it is now tells you where to look, but it isn't as comprehensive as one of our full end to end guides (e.g. https://aptos.dev/tutorials/your-first-coin). That's the purpose of this issue, to make sure we eventually get around to writing a guide like this, where we explain how to do it in each language.
