### ISSUE TITLE
[Docs] Create a guide explaining how to use your own GraphQL queries with the Indexer provider in the TS SDK

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#7705]
# Aptos Documentation Issue

The TS SDK these days has support for querying the indexer. The indexer bundles up a lot of common queries but it is also possible for users to provide their own queries.

We should have a guide that explains how to:
1. Execute queries via the indexer provider.
1. Generate your own helpers for building those queries.

For the second point, in the guide we should acknowledge that different people likely use different ways to generate queries and the one we describe is just one option (the one we use in the TS SDK).

More context: https://aptos-org.slack.com/archives/C03N83P7QUC/p1680460512620209.

**Comment by clay-aptos** [comment]
Thanks, Daniel. I am asking @saharct to take this on.
