### ISSUE TITLE
[Testnet Deployments] Support an idle/cheap testnet deployment mode.

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#771]
We're spawning up a lot of test networks. When we aren't actively using these testnets, it would be great to run the testnet in an idle state to avoid wasting resources (and money 😅). Even if it's just a significantly reduced deployment.

Note: the professionals among us might be able to do this by killing everything manually, but I worry that the steps required to revive the testnet might be too complicated for the n00bs (e.g., me). If they aren't, then maybe a runbook would be good 😄

**Comment by rustielin** [comment]
Forge CLI has something today where an operator (currently just me 😛 ) can manually spin down the cluster to its idle state. Basically uninstalls stuff and spins down the nodegroup size. Perhaps we can generalize that into a new `testnet` CLI tool? 

Alternatively, if we have k8s cluster autoscaling (cc @geekflyer), we could just `helm uninstall` all the validators and fullnodes, and the cluster should take care of the rest
