### ISSUE TITLE
Fix sequence number resetting

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#7737]
Currently this order of operations is possible. Assume seqnum starts at 0.
1. Lock account, submit transaction, bump local seqnum. Request A.
2. Do step 1 again, from a different request. Request B.
3. Do step 1 yet again, from another request. Request C.
4. Request B is successful.
5. Request C is successful.
6. Request A is unsuccessful (e.g. it was rejected by the chain). We reset the seq num to what it was before submitting A.

Now the seqnum is 0, but it should be 2. Calling `update_sequence_numbers` at the start of each request I _think_ fixes this up, but I'm not 100% sure.

In any case, the test plan https://github.com/aptos-labs/aptos-tap/pull/41 proves that it is possible for a single tap instance to submit a transaction with the same seqnum twice. More investigation required.

The error messages are these:
```
AssertionError: Transaction submission failed: API error Error(InvalidTransactionUpdate): Transaction already in mempool with a different payload
```
```
Transaction submission failed: API error Error(VmError): Invalid transaction: Type: Validation Code: SEQUENCE_NUMBER_TOO_OLD
```

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos-faucet/core/src/funder/common.rs#L357

We shouldn't just bump back -1, we should resync.
