### ISSUE TITLE
[Bug] Suspect Transaction gas fee price priority bug on mainnet here

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#7763]
# 🐛 Bug

Transaction 121025265 has been first processed than my transaction 121025268.
121025265 of Gas Unit Price: 0.00001009 APT
121025268 of Gas Unit Price: 0.00010724 APT

https://explorer.aptoslabs.com/txn/121025268/userTxnOverview
https://explorer.aptoslabs.com/txn/121025265/userTxnOverview

https://explorer.aptoslabs.com/block/47049185/transactions
https://explorer.aptoslabs.com/txn/121095090
https://explorer.aptoslabs.com/txn/121095091

https://explorer.aptoslabs.com/block/47061763/transactions
https://explorer.aptoslabs.com/txn/121129993
https://explorer.aptoslabs.com/txn/121129994

https://explorer.aptoslabs.com/block/47095117/transactions
https://explorer.aptoslabs.com/txn/121220546
https://explorer.aptoslabs.com/txn/121220548

## To reproduce
Unknown, Possible was send a low gas unit price transaction first then second high gas unit price transaction at same times.

**Stack trace/error message**
None

## Expected Behavior

My transaction should be in processed first.

## System information

**Please complete the following information:**
- 
Unrelated
- 
Unrelated
- 
Alpine Linux

**Comment by banool** [comment]
I double checked and these two txns are in the same block.

**Comment by banool** [comment]
Hey so when you specify a higher gas unit price, this increases the priority of your transaction in terms of putting it in the next block. But it doesn't affect the ordering of your transaction _within_ that block.

**Comment by e99243506bigplay** [comment]
> Hey so when you specify a higher gas unit price, this increases the priority of your transaction in terms of putting it in the next block. But it doesn't affect the ordering of your transaction _within_ that block.

Ah well, that is something sad, I thought high gas unit price fee was could affect the order...

**Comment by bchocho** [comment]
@e99243506bigplay actually, the gas unit price does affect the ordering within the block. However, if there is a preceding transaction with a lower sequence number, the high gas unit price transaction can only go in after the transaction with lower sequence number.

We're changing the docs to make this more clear, and for how to ensure the order: https://github.com/aptos-labs/aptos-core/pull/7765/commits/9fdae2a75f58c7d8bebba97f1629ab5fe4d9a7fb
