### ISSUE TITLE
[Feature Request] add coin_type to slip-0044, use DerivePath

### ISSUE THREAD

**Issue by pierreneter** [aptos-labs/aptos-core#779]
# 🚀 Feature Request

should we choose a number that represents `Aptos` and add it to https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types?

After that we can use:

```
m/purpose'/coin_type'/account'/change/address_index
```

Example:

```
m/44'/<number of aptos>'/0'/0/0
```

And can create multi accounts:

```
m/44'/<number of aptos>'/0'/0/1
m/44'/<number of aptos>'/0'/0/2
m/44'/<number of aptos>'/0'/0/3
```

## Motivation

I want to use 1 mnemonic to create multi accounts.
More standard for wallets.

### Refer

- https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
- https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki xprv | Custom Derivation Path
- https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki xprv
  - https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types
-  https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki yprv
- https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki zprv
- https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki zprv
- https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki Segwit
  - https://github.com/satoshilabs/slips/blob/master/slip-0173.md

**Comment by pierreneter** [comment]
if we do not follow that, we can choose the way: 1 mnemonic for only 1 account, right?

**Comment by Doge-is-Dope** [comment]
It seems Aptos has been added into the list as [coin type 637](https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types).

**Comment by jjleng** [comment]
Yes. Our coin type is 637.
