### ISSUE TITLE
[Docs] View Function

### ISSUE THREAD

**Issue by xindingw** [aptos-labs/aptos-core#7807]
# Aptos Documentation Issue

## Location

https://aptos.dev/guides/move-guides/book/SUMMARY

Aptos Move Book.

## Description

Missing documentation about view functions.

Add more details about view functions. For example:

- Can a view function call a non-view function which mutates states?
- What's the expected behavior when calling a view function through CLI/Node API if it mutates states?
- Does adding #[view] annotation require package publish?

## Audience

App developers.

**Comment by gnattishness** [comment]
@saharct I believe this issue has been mistakenly closed.
There does not appear to be any official documentation that clarifies whether it is possible to mark a function that mutates state as `#[view]`, and whether this is enforced by the compiler or VM runtime

#8791 does not appear to be related to or resolve this issue.
