### ISSUE TITLE
[Bug] Compile works very slow first time

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#784]
# 🐛 Bug

When i'm running `aptos move compile` first time i have to wait around 30 seconds i think, and nothing happens in output.

It's probably because you fetch Standard Library and Aptos Framework from [aptos-core](https://github.com/aptos-labs/aptos-core) repository and it's very large.

## To reproduce

Create new package using `aptos move init`, add new module, try to compile.

**Comment by gregnazario** [comment]
Yes, this is likely why it takes this long.  Maybe we can put a progress bar or something so that people are not confused
