### ISSUE TITLE
[web-wallet] Wallet Documentation and Getting Started

### ISSUE THREAD

**Issue by hariria** [aptos-labs/aptos-core#786]
# 🚀 Feature Request

# MVP
- [x] Get rid of HOC (withWalletExtension...) for production build (@kent-white)
- [x] Add png logo for Aptos icon on manifest.json (@kent-white)

# Not MVP
- [ ] dark mode isn't persisted to localstorage? Maybe not...

# Documentation
- [x] Documentation on getting started
- [x] How to create a wallet
- [x] How to transfer / fund with faucet
- [x] How to use with a Dapp

**Comment by pierreneter** [comment]
Can we discuss about https://github.com/aptos-labs/aptos-core/issues/779 for the task: `How to create a wallet`?

**Comment by kent-white** [comment]
@pierreneter I thats unrelated to this task. We can discuss your issue separately.


@hariria lets close this issue, the dark mode persistence doesn't matter too much because I made darkmode the only mode for the extension

**Comment by hariria** [comment]
Done
