### ISSUE TITLE
[CLI] Ledger support

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#7906]
Per recent discussion with @gregnazario @davidiw @CapCap on Move Monday.

Currently Petra supports the Ledger hardware wallet integration, but the Aptos CLI does not.

The lack of support on the CLI imposes burdensome development costs on builders: if they want to publish, sign a transaction etc. from a hardware wallet, they will need to develop some kind of bespoke interface that feeds in a transaction request to Petra.

Adding ledger support to the CLI will improve the pace of development, without discouraging secure practices (as a result of burdensome inconveniences).

See also https://docs.solana.com/wallet-guide/hardware-wallets/ledger#use-ledger-nano-with-solana-cli

**Comment by dylanschultzie** [comment]
+1. Adding Ledger support to CLI will allow us at Lavender.Five to rotate our operator key to our hardware wallet. Currently we still have a soft key to manage pulling commissions, then immediately move the commission to our hardware wallet.

**Comment by ericjohncarlson** [comment]
+1 to this as well.  Hugely valuable to validator operations.

**Comment by gregnazario** [comment]
Yes, we plan to add Ledger support to the CLI, I as well would love to use it instead of a hot wallet :)

**Comment by alnoki** [comment]
@0xjinn

**Comment by banool** [comment]
I just put discussing this item on the agenda for our team sync, stay posted!

**Comment by alnoki** [comment]
> I just put discussing this item on the agenda for our team sync, stay posted!

@banool thanks for the update! One detail worth mentioning is the ability to sign publication transactions up to the 64k transaction limit, since I believe this may involve chunking into the ledger internal RAM

**Comment by alnoki** [comment]
Bumping this issue per stale label

Ledger support is a key feature for secure development

**Comment by 0xjinn** [comment]
Hi @alnoki , the ledger integration is in a feature branch right now - https://github.com/aptos-labs/aptos-core/blob/feature_branch/cli_ledger_integration, and here is the doc - [https://github.com/aptos-labs/aptos-core/blob/feature_branch/cli_ledger_integratio[…]oper-docs-site/docs/tools/aptos-cli/use-cli/use-aptos-ledger.md](https://github.com/aptos-labs/aptos-core/blob/feature_branch/cli_ledger_integration/developer-docs-site/docs/tools/aptos-cli/use-cli/use-aptos-ledger.md)

Please feel free to test it out in devnet/testnet. We will be releasing this soon.

**Comment by dylanschultzie** [comment]
@0xjinn I was unable to get the `--derivation-path` command line argument to work. Here's what I tried:

```sh
❯ ./aptos init --profile lavender.five --ledger --derivation-path [m/44'/637'/30'/0'/0]
zsh: no matches found: [m/44/637/30/0/0]
❯ ./aptos init --profile lavender.five --ledger --derivation-path [m/44'/637'/30'/0'/0]
zsh: no matches found: [m/44/637/30/0/0]
❯ ./aptos init --profile lavender.five --ledger --derivation-path [m/44/637/30/0/0]
zsh: no matches found: [m/44/637/30/0/0]
❯ ./aptos init --profile lavender.five --ledger --derivation-path m/44/637/30/0/0
Aptos already initialized for profile lavender.five, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile lavender.five
Choose network from [devnet, testnet, mainnet, local, custom | defaults to devnet]
mainnet
{
  "Error": "Unexpected error: Unexpected Ledger Error: \"Error - Failed to compute hash digest of raw transaction\""
}
❯ ./aptos init --profile lavender.five --ledger --derivation-path m/44'/637'/30'/0'/0
Aptos already initialized for profile lavender.five, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile lavender.five
Choose network from [devnet, testnet, mainnet, local, custom | defaults to devnet]
mainnet
{
  "Error": "Unexpected error: Unexpected Ledger Error: \"Error - Failed to compute hash digest of raw transaction\""
}
❯ ./aptos init --profile lavender.five --ledger --derivation-path m/44\'/637\'/30\'/0\'/0
Aptos already initialized for profile lavender.five, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile lavender.five
Choose network from [devnet, testnet, mainnet, local, custom | defaults to devnet]
mainnet
{
  "Error": "Unexpected error: Unexpected Ledger Error: \"Error - Failed to compute hash digest of raw transaction\""
}
❯ ./aptos init --profile lavender.five --ledger --derivation-path "m/44'/637'/30'/0'/0"
Aptos already initialized for profile lavender.five, do you want to overwrite the existing config? [yes/no] >
yes
Configuring for profile lavender.five
Choose network from [devnet, testnet, mainnet, local, custom | defaults to devnet]
mainnet
{
  "Error": "Unexpected error: Unexpected Ledger Error: \"Error - Failed to compute hash digest of raw transaction\""
}
```

However, I was able to get `--derivation-index` to work just fine:
```
❯ ./aptos init --profile lavender.five --ledger --derivation-index 30
...
{
  "Result": "Success"
}
```

**Comment by 0xjinn** [comment]
@dylanschultzie Ah, sorry about the confusion on the derivation path. I should be updated the doc reflect this. You have to escape all of the `'`, try the following

`--derivation-path m/44\'/637\'/0\'/0\'/0\'`

Thank you for pointing this out. Will update the doc soon

**Comment by 0xjinn** [comment]
Ledger support has been published - https://aptos.dev/tools/aptos-cli/use-cli/use-aptos-ledger

Closing this issue.
