### ISSUE TITLE
SDK test coverage

### ISSUE THREAD

**Issue by lbmeiyi** [aptos-labs/aptos-core#7917]
Look into the test coverage for SDK, determine the most critical functionalities can work e2e

This is a SEV folllow up item from 'We can’t actually call private entry functions'
https://aptoslabs.pagerduty.com/incidents/1809

**Comment by lbmeiyi** [comment]
TS sdk only.

**Comment by lbmeiyi** [comment]
We will come back to this after re-factor is done for the SDK.

**Comment by gregnazario** [comment]
Closing, the SDK had been rewritten as V2
