### ISSUE TITLE
[Docs] Updating Public Full Nodes recommends deleting entire data directory

### ISSUE THREAD

**Issue by dconroy** [aptos-labs/aptos-core#8085]
# Aptos Documentation Issue

## Location

https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/nodes/full-node/fullnode-source-code-or-docker.md

https://aptos.dev/nodes/full-node/fullnode-source-code-or-docker

Run Nodes

## Description

Currently the instructions to run a public full node recommend deleting the entire data directory when updating. Is this necessary on mainnet?  

Should the instructions be updated to only delete the data dir on dev or testnets?

**Comment by sherry-x** [comment]
Thanks for pointing it out! will update it
