### ISSUE TITLE
Eliminate compiled code from the repo

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#81]
There's a lot of compiled move code in the repository, there are a few tasks to eliminate it. First the motivation, compiled code makes it very tricky make sense of our eventual complete renaming and this is a legacy of the past. There's a lot of fragility around the compiled code and it doesn't mesh with our working model. For example, when trying to rename, one must actually update the compiled binaries manually otherwise a complete rebuild of the project will fail. There's no documentation around that.

* Eliminate genesis and framework binaries and instead rely on "fresh" instances
* Delete all notion of compiled scripts and maybe even scripts from within the codebase since we don't have any applications right now (this includes in porting all the e2e-testssuites to use script functions)

One should be able to delete the following from .gitignore:

!aptos-move/diem-framework/DPN/releases/artifacts/**
!aptos-move/diem-framework/experimental/releases/artifacts/**
!aptos-move/diem-framework/aptos-framework/releases/artifacts/**

**Comment by areshand** [comment]
the script bytes code is broken has to replaced. Ideally, we should replace these with move script and do compiling directly in the test
[] https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/api/src/tests/string_resource_test.rs#L14
[] https://github.com/aptos-labs/aptos-core/blob/049819344493ade599241b72cc26c47fc0780f2d/api/src/tests/accounts_test.rs#L540

**Comment by gregnazario** [comment]
I believe you already cleaned this up @davidiw with the cached packages?
