### ISSUE TITLE
[Bug] CLI hangs on shutdown when there is no internet

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#8113]
After doing a lot of on-plane development, I notice the CLI hangs after the command is done if you have no internet. My guess is the CLI is trying to push some analytics info. There should be a timeout for this, I’ve noticed cases where it hangs indefinitely.

**Comment by wrwg** [comment]
This is kind of a duplicate or related to this one: https://github.com/aptos-labs/aptos-core/issues/5909. Should we reconcile those two?

**Comment by banool** [comment]
Agreed, let's move to that issue.

**Comment by banool** [comment]
Reopening this because the other one was closed.

**Comment by banool** [comment]
So we've confirmed that this is due to telemetry.

With telemetry:
```
$ time aptos info
{
  "Result": {
    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "83250343e09f10e56f6ddbd8019f6d4634488349",
    "build_is_release_build": "true",
    "build_os": "macos-x86_64",
    "build_pkg_version": "2.0.1",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-06-05 18:03:07 +00:00",
    "build_using_tokio_unstable": "true"
  }
}

real    0m10.903s
user    0m0.057s
sys     0m0.032s
```

Without telemetry:
```
$ APTOS_DISABLE_TELEMETRY=true time aptos info
{
  "Result": {
    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "83250343e09f10e56f6ddbd8019f6d4634488349",
    "build_is_release_build": "true",
    "build_os": "macos-x86_64",
    "build_pkg_version": "2.0.1",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-06-05 18:03:07 +00:00",
    "build_using_tokio_unstable": "true"
  }
}
        0.03 real         0.01 user         0.01 sys
```

A few followups here:
1. Add a timeout on pushing telemetry. Probably 3 seconds at most.
2. Investigate the backend. It is is possible that performance has degraded.
3. Make sure the telemetry ingestion API is globally distributed, it should not be slower for those outside of the US for example.

**Comment by banool** [comment]
Jin landed a change to add a timeout on the telemetry stuff.
