### ISSUE TITLE
[TS SDK] add read/indexer operations for tokenv2

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-core#8141]
- [x] P0: Users can query for all tokens (v2) that an account owns
- [x] P0: Users can query for all collections that an account has tokens for
- [x] P0: Users can query for all tokens of a specific collection that an account owns
- [ ] P0: Users can get all the attributes (in all resources) a token has
- [ ] fetch token by name (filter)

**Comment by gregnazario** [comment]
Closed, this was for SDK v1
