### ISSUE TITLE
[Bug] cannot disassemble: Module blob can't be deserialized

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#8181]
# 🐛 Bug

`aptos move disassemble` responds with "Unexpected error: Module blob can't be deserialized"

## To reproduce

1. get bytecode from [this txn](https://explorer.aptoslabs.com/txn/140122302/payload?network=mainnet) 
2. write the bytecode into a file named `test.mv`
3. try to disassemble the file
  ```
  $ cat test.mv
0xa11ceb0b0600000008010016021624033a32046c22058e015407e201fe0108e003800206e005280000000100020003010402010305040605070601070803090700000d0800051100000a1200000413000007150000091100000a1700000a180000020a030400010b04060100010c03020100010e04080100060f090201000310020a010008140f0202000008160f02030000000105020503070405050505070305050b050c050d060e05100511071205130514071502060c05080101010103030800050001060c01050109000101010801010303060c050a05010800010802010803010804020900080103060c030301080501080603090008020801010807010808030900080308010a6170746f735f636f696e04636f696e067369676e657209747970655f696e666f036f66740d7661756c745f73637269707473117374616b65645f6170746f735f636f696e06726f757465720561737365740854797065496e666f0a616464726573735f6f661569735f6163636f756e745f72656769737465726564087265676973746572094170746f73436f696e0762616c616e6365096c697175696461746507747970655f6f66015404555344430743616b654f465410737761705f65786163745f696e7075740f5374616b65644170746f73436f696e1a737761705f65786163745f696e7075745f646f75626c65686f70045553445404574554480000000000000000000000000000000000000000000000000000000000000001159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca65e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac0184d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114c7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850facc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abbf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa0308640000000000000003080a00000000000000030814000000000000000308000000000000000001000001780a0011000c090a0938002004090a0038010a0938020c060a0606000000000000000024041105150b00010701270a000b0140040000000000000000380338040c080a08380522046d0a0938060c070a07060000000000000000240427052b0b00010702270a083807210432080c0205360a083808210c020b02043b080c03053f0a083809210c030b0304460b000b07060100000000000000380a056c0a08380b21044d080c0405510a08380c210c040b0404580b000b07060100000000000000380d056c0a08380e21045f080c0505630b08380f210c050b05046a0b000b070601000000000000003810056c0b0001056f0b00010b0938020b06240475057707002702

$ aptos move disassemble --bytecode-path ./test.mv
{
  "Error": "Unexpected error: Module blob can't be deserialized"
}
  ```

## Expected Behavior

disassemble successfully

## System information

```
$ aptos info
{
  "Result": {
    "build_branch": "",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "true",
    "build_commit_hash": "",
    "build_is_release_build": "true",
    "build_os": "macos-x86_64",
    "build_pkg_version": "1.0.13",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-04-29 04:44:27 +00:00",
    "build_using_tokio_unstable": "true"
  }
}
```

**Comment by aquynh** [comment]
> # 🐛 Bug
> `aptos move disassemble` responds with "Unexpected error: Module blob can't be deserialized"
> 
> ## To reproduce
> 1. get bytecode from [this txn](https://explorer.aptoslabs.com/txn/140122302/payload?network=mainnet)
> 2. write the bytecode into a file named `test.mv`
> 3. try to disassemble the file
> 
> ```
> $ cat test.mv
> 0xa11ceb0b0600000008010016021624033a32046c22058e015407e201fe0108e003800206e005280000000100020003010402010305040605070601070803090700000d0800051100000a1200000413000007150000091100000a1700000a180000020a030400010b04060100010c03020100010e04080100060f090201000310020a010008140f0202000008160f02030000000105020503070405050505070305050b050c050d060e05100511071205130514071502060c05080101010103030800050001060c01050109000101010801010303060c050a05010800010802010803010804020900080103060c030301080501080603090008020801010807010808030900080308010a6170746f735f636f696e04636f696e067369676e657209747970655f696e666f036f66740d7661756c745f73637269707473117374616b65645f6170746f735f636f696e06726f757465720561737365740854797065496e666f0a616464726573735f6f661569735f6163636f756e745f72656769737465726564087265676973746572094170746f73436f696e0762616c616e6365096c697175696461746507747970655f6f66015404555344430743616b654f465410737761705f65786163745f696e7075740f5374616b65644170746f73436f696e1a737761705f65786163745f696e7075745f646f75626c65686f70045553445404574554480000000000000000000000000000000000000000000000000000000000000001159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca65e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac0184d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114c7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850facc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abbf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa0308640000000000000003080a00000000000000030814000000000000000308000000000000000001000001780a0011000c090a0938002004090a0038010a0938020c060a0606000000000000000024041105150b00010701270a000b0140040000000000000000380338040c080a08380522046d0a0938060c070a07060000000000000000240427052b0b00010702270a083807210432080c0205360a083808210c020b02043b080c03053f0a083809210c030b0304460b000b07060100000000000000380a056c0a08380b21044d080c0405510a08380c210c040b0404580b000b07060100000000000000380d056c0a08380e21045f080c0505630b08380f210c050b05046a0b000b070601000000000000003810056c0b0001056f0b00010b0938020b06240475057707002702
> 
> $ aptos move disassemble --bytecode-path ./test.mv
> {
> "Error": "Unexpected error: Module blob can't be deserialized"
> }
> ```
> 
> ## Expected Behavior
> disassemble successfully
> 
> ## System information
> ```
> $ aptos info
> {
>   "Result": {
>     "build_branch": "",
>     "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
>     "build_clean_checkout": "true",
>     "build_commit_hash": "",
>     "build_is_release_build": "true",
>     "build_os": "macos-x86_64",
>     "build_pkg_version": "1.0.13",
>     "build_profile_name": "cli",
>     "build_rust_channel": "1.66.1-x86_64-apple-darwin",
>     "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
>     "build_tag": "",
>     "build_time": "2023-04-29 04:44:27 +00:00",
>     "build_using_tokio_unstable": "true"
>   }
> }
> ```

Your problem is that you are passing the broken .mv file to the disassembler.

**Comment by brmataptos** [comment]
As @aquynh mentions above, the problem is that you are creating the .mv file incorrectly.  The bytecode field shown in the explorer is a hexadecimal string representing the bytecode data, but the .mv file must contain the actual bytes.

There are many ways to convert this hex string to byte data.  One simple way to do so without any programming is to generate the bytes from hex using the `xxd` program on linux/macos systems:

First remove the `0x` header and save the hex string in a file such as test.hex.  Then convert, disassemble, and view it as follows:
```
$ cat test.hex
a11ceb0...
$ xxd -r -p test.hex test.mv
$ aptos move disassemble --bytecode-path ./test.mv
{
  "Result": "./tmp.mv.asm"
}
$ cat tmp.mv.asm
// Move bytecode v6
module 1.aptos_coin {
use 0000000000000000000000000000000000000000000000000000000000000001::aptos_coin;
use 0000000000000000000000000000000000000000000000000000000000000001::signer;
use 0000000000000000000000000000000000000000000000000000000000000001::type_info;
use 159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft;
use 5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin as 1coin;
use 6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac01::vault_scripts;
use 84d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114::staked_aptos_coin;
use c7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850fa::router;
use cc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin as 2coin;
use f22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset;





}% 
```
Perhaps someday we'll fix `aptos move disassemble` to optionally send output to stdout so you can just use it.
