### ISSUE TITLE
Remove experimental framework and related code

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#83]
Experimental framework is no longer necessary as we already have an aptos-framework, let's clean that and any code surrounding it up (e.g., NFTs): https://github.com/aptos-labs/aptos-core/tree/main/diem-move/diem-framework/experimental

**Comment by magnum6actual** [comment]
Let's not remove the experimental code until the other related issues (ie NFT) are put to bed. No need to reinvent.

**Comment by davidiw** [comment]
> Let's not remove the experimental code until the other related issues (ie NFT) are put to bed. No need to reinvent.

We have Git History -- so nothing is ever lost!
The team is eager to support only a single and well vetted framework.
