### ISSUE TITLE
Compiling a Move module causes an ICE

### ISSUE THREAD

**Issue by chuacw** [aptos-labs/aptos-core#8390]
# 🐛 Bug

Compiling a Move module causes an ICE.
Even after 

- aptos move clean --assume-yes
- aptos move compile --named-addresses overmind=default

The bug is still seen.

## To reproduce
Use the attached files.

**Stack trace/error message**
PS K:\Development\Move\pay-me-a-river> aptos move compile --named-addresses overmind=default
Compiling, may take a little while to download git dependencies...
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING pay_me_a_river
thread 'main' panicked at 'ICE type constraints failed 055d9d249126ed1feaea5910a42a9a8cd14d49fe0ba062d1ae05207482906c11:3035-3048', third_party\move\move-compiler\src\hlir\translate.rs:481:13
stack backtrace:
   0:     0x7ff6ee755e06 - <unknown>
   1:     0x7ff6edd86c2b - <unknown>
   2:     0x7ff6ee7315da - <unknown>
   3:     0x7ff6ee757e9b - <unknown>
   4:     0x7ff6ee757a81 - <unknown>
   5:     0x7ff6ee7589ad - <unknown>
   6:     0x7ff6ee758465 - <unknown>
   7:     0x7ff6ee7583af - <unknown>
   8:     0x7ff6ee758384 - <unknown>
   9:     0x7ff6eebe4b95 - <unknown>
  10:     0x7ff6edf7c77b - <unknown>
  11:     0x7ff6edfffe13 - <unknown>
  12:     0x7ff6edff81b4 - <unknown>
  13:     0x7ff6edff3c14 - <unknown>
  14:     0x7ff6edff0b6e - <unknown>
  15:     0x7ff6edffef40 - <unknown>
  16:     0x7ff6edff81b4 - <unknown>
  17:     0x7ff6edff3c14 - <unknown>
  18:     0x7ff6edff0472 - <unknown>
  19:     0x7ff6edfef5bb - <unknown>
  20:     0x7ff6edfeeb51 - <unknown>
  21:     0x7ff6ee085346 - <unknown>
  22:     0x7ff6ee11eab1 - <unknown>
  23:     0x7ff6ee0f7ea7 - <unknown>
  24:     0x7ff6ee15e3e1 - <unknown>
  25:     0x7ff6ee15e9e3 - <unknown>
  26:     0x7ff6ee15e996 - <unknown>
  27:     0x7ff6ee15ea2c - <unknown>
  28:     0x7ff6ee15eb69 - <unknown>
  29:     0x7ff6ee0dbce9 - <unknown>
  30:     0x7ff6ee15dd10 - <unknown>
  31:     0x7ff6ed7c9229 - <unknown>
  32:     0x7ff6ed7c086e - <unknown>
  33:     0x7ff6ed091c74 - <unknown>
  34:     0x7ff6ecede1fa - <unknown>
  35:     0x7ff6eceba82d - <unknown>
  36:     0x7ff6eced3809 - <unknown>
  37:     0x7ff6ecee9fe8 - <unknown>
  38:     0x7ff6eceb1789 - <unknown>
  39:     0x7ff6eceeb544 - <unknown>
  40:     0x7ff6eebcd13c - <unknown>
  41:     0x7ffaa6b84de0 - BaseThreadInitThunk
  42:     0x7ffaa8c3e3db - RtlUserThreadStart

## Expected Behavior

Code to either compile, or fail to compile, with indications why it failed to compile.

## System information

**Please complete the following information:**
    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "7f864d4af722bf538f1a904e321130a261e92b3a",
    "build_is_release_build": "true",
    "build_os": "windows-x86_64",
    "build_pkg_version": "1.0.13",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-pc-windows-msvc",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-04-29 15:21:14 +00:00",
    "build_using_tokio_unstable": "true"

Microsoft Windows 2022 64-bit

[pay-me-a-river.zip](https://github.com/aptos-labs/aptos-core/files/11577044/pay-me-a-river.zip)

**Comment by yart123** [comment]
Seeing very similar issue:
```
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ICE failed bytecode verifier: VMError {
    major_status: CALL_TYPE_MISMATCH_ERROR,
    sub_status: None,
    message: None,
    exec_state: None,
    location: Module(
        ModuleId {
            address: 0000000000000000000000000000000000000000000000000000000000001337,
            name: Identifier(
                "broker_it_yourself",
            ),
        },
    ),
    indices: [
        (
            FunctionDefinition,
            2,
        ),
    ],
    offsets: [
        (
            FunctionDefinitionIndex(2),
            14,
        ),
    ],
}
```
