### ISSUE TITLE
[Bug] nested mul_div panicked 

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#8516]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**

This test passes

```rust
#[test]
fun test_nested_mul_div() {
    let a = math64::mul_div(1, 1, 1);
    assert!(math64::mul_div(1, a,1) == 1, 0);
}
```

This test throws exception.

```rust
#[test]
fun test_nested_mul_div() {
    assert!(math64::mul_div(1, math64::mul_div(1, 1, 1),1) == 1, 0);
}
```

error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', third_party/move/move-compiler/src/to_bytecode/context.rs:204:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

nested should be fine

## System information

```
{
  "Result": {
    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "c9cb442e6f03aaa37687d30899480d40408d0719",
    "build_is_release_build": "true",
    "build_os": "macos-x86_64",
    "build_pkg_version": "2.0.0",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-apple-darwin",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-06-01 19:50:01 +00:00",
    "build_using_tokio_unstable": "true"
  }
}
```

**Comment by movekevin** [comment]
After some quick debugging, I think this is due to the way inline functions work - you can't have inline functions inside inline functions. cc @wrwg

**Comment by wrwg** [comment]
> After some quick debugging, I think this is due to the way inline functions work - you can't have inline functions inside inline functions. cc @wrwg

Definitely you can have inline functions inside inline functions, it happens frequently in the functionals in the framework. This must be something different.

**Comment by movekevin** [comment]
I actually got nested mul_div to work when doing this outside of the math64 module. When doing the same test inside math64, where mul_div is defined as an inline function, I got:

```
bug[ICE12001]: BYTECODE GENERATION FAILED
  ┌─ /Users/kevin/aptos-core/aptos-move/framework/aptos-stdlib/sources/math64.move:2:19
  │
2 │ module aptos_std::math64 {
  │                   ^^^^^^ IR ERROR: Unbound function Self.mul_div
```

**Comment by movekevin** [comment]
Doing this currently fails with the following error:
```
bug[ICE12001]: BYTECODE GENERATION FAILED
  ┌─ /Users/kevin/aptos-core/aptos-move/framework/aptos-stdlib/sources/math64.move:2:19
  │
2 │ module aptos_std::math64 {
  │                   ^^^^^^ IR ERROR: Unbound function Self.mul_div
```

**Comment by mkurnikov** [comment]
> Definitely you can have inline functions inside inline functions, it happens frequently in the functionals in the framework. This must be something different.

I think it currently requires nested inline function to be defined at the same module as the invocation place. 

> BYTECODE GENERATION FAILED

The same appears with inline functions that have constants, try to call `math128::ceil_div()` from anywhere other than `math128` itself. 

P.S. I suggest Aptos developers to implement tests for the public functions in modules different from the declaration module. It helps catch those bugs early.

**Comment by wrwg** [comment]
Fixed
