### ISSUE TITLE
[Feature Request] add vector::range(start, end, step)

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-core#8555]
# 🚀 Feature Request

## Motivation

I find myself trying to replicate what the two functions do very often.

## Pitch

**Describe the solution you'd like**
range(0, 5, 2) => vec[0, 2, 4]
zip([a, b], [1, 2]) => [(a, 1), (b, 2)]

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes.

**Comment by JohnChangUK** [comment]
Feature has been added as part of this PR: https://github.com/aptos-labs/aptos-core/pull/11173
