### ISSUE TITLE
0x546ccaAA604B1C2E30313577071C9D4BBf0E64e2

### ISSUE THREAD

**Issue by wijesinghe1967** [aptos-labs/aptos-core#8603]
0x546ccaAA604B1C2E30313577071C9D4BBf0E64e2

_Originally posted by @wijesinghe1967 in https://github.com/aptos-labs/aptos-core/issues/8602#issuecomment-1585004364_

**Comment by wijesinghe1967** [comment]
0x546ccaAA604B1C2E30313577071C9D4BBf0E64e2

**Comment by gregnazario** [comment]
Closing as spam
