### ISSUE TITLE
[Bug] INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION

### ISSUE THREAD

**Issue by chuacw** [aptos-labs/aptos-core#8614]
# 🐛 Bug

Internal test error encountered when running Aptos move test

## To reproduce

```
module diamond_clicker::game {

    #[test_only]
    use aptos_std::debug;
    #[test_only]
    use std::signer;
    #[test_only]
    use std::vector;

    struct InnerStruct has key, store, copy {
        amount: u64
    }

    struct OuterStruct has key {
        any_field: vector<InnerStruct>
    }

    #[test(account=@0x1234)]
    public entry fun test_upgrade(account: &signer) acquires OuterStruct {
        let account_address = signer::address_of(account);
        let upgrade_amount = 0;
        move_to(account, OuterStruct {any_field: vector::empty()});
        let anystruct = borrow_global_mut<OuterStruct>(account_address);
        vector::for_each_mut<InnerStruct>(&mut anystruct.any_field, |field| {
            debug::print(field); /// INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION
            // let field: &mut InnerStruct = field;
            // field.amount = field.amount + upgrade_amount;
        });

    }

}
```

**Stack trace/error message**
```
┌── test_upgrade ──────
│ error[E11001]: test failure
│    ┌─ K:\Development\Move\diamond-clicker-bug\sources\diamond_clicker.move:25:13
│    │
│ 19 │     public entry fun test_upgrade(account: &signer) acquires OuterStruct {
│    │                      ------------ In this function in 0xe9fa01aaa1a483c6c598d470ae9b8174226590499b25812d8f0e86192a3b8711::game
│    ·
│ 25 │             debug::print(field);
│    │             ^^^^^^^^^^^^^^^^^^^ INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a UNEXPECTED_VERIFIER_ERROR (code 2017) error originating in the module e9fa01aaa1a483c6c598d470ae9b8174226590499b25812d8f0e86192a3b8711::game rooted here
│ 
│ 
└──────────────────

```

## Expected Behavior

No "internal VM invariant violation" encountered.

## System information

    "build_branch": "main",
    "build_cargo_version": "cargo 1.66.1 (ad779e08b 2023-01-10)",
    "build_clean_checkout": "false",
    "build_commit_hash": "83250343e09f10e56f6ddbd8019f6d4634488349",
    "build_is_release_build": "true",
    "build_os": "windows-x86_64",
    "build_pkg_version": "2.0.1",
    "build_profile_name": "cli",
    "build_rust_channel": "1.66.1-x86_64-pc-windows-msvc",
    "build_rust_version": "rustc 1.66.1 (90743e729 2023-01-10)",
    "build_tag": "",
    "build_time": "2023-06-05 18:04:18 +00:00",
    "build_using_tokio_unstable": "true"

**Comment by sausagee** [comment]
@junkil-park can you take a look at this issue if it is a duplicate of the same issue in https://github.com/aptos-labs/aptos-core/issues/8865?

**Comment by brmataptos** [comment]
I can reproduce this.  Will take a deeper look.

**Comment by brmataptos** [comment]
I can no longer reproduce this, due to https://github.com/aptos-labs/aptos-core/pull/9835.  I hope @davidiw and @wrwg can write a reproducing test from which we can print bytecode for both inline and non-inlined case to allow comparison.

**Comment by brmataptos** [comment]
This is now illustrated in 
```
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/diamond_clicker.exp
```
but V2 seems to avoid the problem, as shown in 
```
aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/diamond_clicker.v2_exp
```

**Comment by brmataptos** [comment]
FYI, the problem here is that the local variable `field` has a `&mut` type, so a `freeze` operation must be applied to it before passing it as a parameter to `debug::print`.  For no clear reason, the inlined version fails to add the `freeze` operation.  

Debugging outputs show that the IR for a manually-inlined version is identical, modulo symbol renaming, to the inlined version, until just before the V1 "hlir" pass, which inserts needed `freeze` operations.  The V1 "hlir" pass is too complex to easily figure out what's going on, so this will not be fixed until Compiler V2.

**Comment by brmataptos** [comment]
Use Compiler V2 instead, or manually insert a freeze as needed here.
