### ISSUE TITLE
[Feature Request] [Deployment] GCP Validator deployment - Spanner is overkill?

### ISSUE THREAD

**Issue by dr-smo** [aptos-labs/aptos-core#871]
# 🚀 Feature Request

Replace Spanner with Cloud Storage

## Motivation

Spanner is a mighty piece of Google tech, however it commands a hefty price tag at 1 USD/h or more depending on the region.
Looking as to how DynamoDB is fine for AWS and just Azure storage for Azure I think it would make sense to have the Vault backend set to GCS also.
Otherwise GCP will be at a heavy disadvantage as it will cost 720 USD per month for running Spanner ONLY.
Probably that would be better invested in more capacity for the validator itself.

Here is the code: 
https://github.com/aptos-labs/aptos-core/blob/main/terraform/validator/gcp/vault.tf#L97

Not sure if this is related: https://github.com/aptos-labs/aptos-core/issues/678

**Comment by sherry-x** [comment]
Yes this will be removed for AIT1! the current validator terraform was from the old Diem days, which had different consideration back then.

**Comment by dr-smo** [comment]
sounds great :)
