### ISSUE TITLE
[Prover] Need to lock down the dependency (Z3 and Boogie) version

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#8718]
The upgrade of Z3 and Boogie is mostly backward compatible, but not always. Prover currently warns users when they have installed some outdated version of Z3 and Boogie. However, Prover also need to warn users for the higher version of Z3 and Boogie because those may be incompatible.

**Comment by rahxephon89** [comment]
PR to fix this: https://github.com/aptos-labs/aptos-core/pull/8750

**Comment by aalok-t** [comment]
PR to fix this #9524
