### ISSUE TITLE
[Feature Request] Support `#[deprecated]` attribute

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#8720]
Should produce a warning in extended type checker.

**Comment by 0xbe1** [comment]
hey @wrwg is this going to happen sometime this year?

**Comment by brmataptos** [comment]
Probably.  I'm thinking about it now.

> Should produce a warning in extended type checker.

I might prefer to do it a different way.  I note that Rust complains about use of deprecation at each use site, even if there are multiple.  I am skeptical that we can properly show the source code for all uses so late in compilation.  @wrwg We can discuss first, though.

**Comment by wrwg** [comment]
> Probably. I'm thinking about it now.
> 
> > Should produce a warning in extended type checker.
> 
> I might prefer to do it a different way. I note that Rust complains about use of deprecation at each use site, even if there are multiple. I am skeptical that we can properly show the source code for all uses so late in compilation. @wrwg We can discuss first, though.

We can do this, here is an example how we report something on every code side (for events v2): https://github.com/aptos-labs/aptos-core/pull/9507. This will also easily port over to the new compiler.

**Comment by brmataptos** [comment]
> We can do this, here is an example how we report something on every call site (for events v2): https://github.com/aptos-labs/aptos-core/pull/9507. This will also easily port over to the new compiler.

That is nice and simple for function calls, but I suspect that we also want to #[deprecate] struct, module, and maybe even friend and use.  (Really not sure about the last 2, but any types are a problem to localize uses late in compilation.)

**Comment by wrwg** [comment]
> > We can do this, here is an example how we report something on every call site (for events v2): #9507. This will also easily port over to the new compiler.
> 
> That is nice and simple for function calls, but I suspect that we also want to #[deprecate] struct, module, and maybe even friend and use. (Really not sure about the last 2, but any types are a problem to localize uses late in compilation.)

Not a problem either.
