### ISSUE TITLE
Improve error messages when building payloads for functions that take `Object<T>`

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#8735]
It is not obvious to new users what you're meant to do when an entry function takes `Object<MyThing>` as an argument. I have seen people try to do things like actually build an object in whatever native representation and/or serialize as BCS and pass that in (since they're new, they don't understand that it's really just a pointer).

In our SDKs if you're building a payload for an entry function that takes `Object<T>` you can just pass in an address. Indeed this is the only thing that works. As such our payload builders should return a very clear error in this case, like this:
```
Argument with type Object<T> expects an address (the address of the object) as an argument when building the payload
```

**Comment by gregnazario** [comment]
Is this a documentation thing or an error thing?

**Comment by gregnazario** [comment]
Yes, the error messages need to be improved in the type_tag parsing

**Comment by gregnazario** [comment]
Closed, SDK v1
