### ISSUE TITLE
Run SDK tests against local testnets from the prod branches

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#8740]
Pretty much make the SDK tests work how the faucet and CLI tests work, where the local testnet against which they run is built from the devnet / testnet / mainnet branch.

**Comment by banool** [comment]
See https://github.com/aptos-labs/aptos-core/pull/8769.

**Comment by banool** [comment]
This was done and then somewhat reverted. More investigation required, I don't agree with the latest decision. More TBA.

**Comment by gregnazario** [comment]
Let's close this as we're moving forward to SDK V2
