### ISSUE TITLE
[Feature Request] Pre-build all move bytecode for AptosFramework

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#877]
Currently for building genesis, we need to get all the framework bytecode, and it requires cargo build, copy from folders and make sure the commit version you build from is correct. So we should:
- create framework release, pre-builld all bytecode
- host all the bytecode somewhere so that it's easy to download
- have release version for them to ensure compatibility

**Comment by zekun000** [comment]
lol this was exactly what @davidiw deleted a few weeks ago

**Comment by davidiw** [comment]
We synced today on this, because you can imagine my excitement in seeing this.

This is specifically an ask to have a guide that describes how to package the binaries and creates a release for them. This isn't about adding the byte code to the aptos main branch.

**Comment by sherry-x** [comment]
That's why I said `host all the bytecode somewhere` :p

**Comment by gregnazario** [comment]
This is more about releasing byte code on releases rather than constantly like we were before

**Comment by davidiw** [comment]
@zekun000 ===== :trollface:

**Comment by gregnazario** [comment]
We... Actually have this now
