### ISSUE TITLE
`--named-addresses` should allow 0x prefixed addresses

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#8770]
As it is now you get this error:
```
error: Invalid value "aptos_names=0x0x585fc9f0f0c54183b039ffc770ca282ebd87307916c215a3e692f2f8e4305e82,aptos_names_admin=0x0x585fc9f0f0c54183b039ffc770ca282ebd87307916c215a3e692f2f8e4305e82,aptos_names_funds=0x0x585fc9f0f0c54183b039ffc770ca282ebd87307916c215a3e692f2f8e4305e82" for '--named-addresses <NAMED_ADDRESSES>': Invalid arguments: Failed to parse AccountAddress Unable to parse AccountAddress (must be hex string of length 32)
```

**Comment by gregnazario** [comment]
This is double '0x' in the front.  Are you sure it doesn't work with just one 0x?

**Comment by banool** [comment]
Yep lol you're right, that's my bad.

**Comment by gregnazario** [comment]
I think though, it may be useful to add a validation error where:
1. It validates that it's one 0x, or no 0x, and provides a proper error if it's missing
2. Length check and error with a friendly error

**Comment by banool** [comment]
This kind of thing is part of the address standard, I can include a solid "from_str" function in the reference implementation that gives good errors.

See the standard here: https://github.com/aptos-foundation/AIPs/blob/main/aips/address-standard-v1.md.
