### ISSUE TITLE
[Bug] an issue of `string_utils::native_format` in formatting signer values

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#8865]
# 🐛 Bug

`string_utils::native_format` has an issue with formatting signer values.

## To reproduce

**Code snippet to reproduce**
Try to print signer values
```rust
    #[test(s1=@0x123)]
    fun test_print(s1: signer) {
        print(&s1); // aptos_std::debug::print
    }
```

**Stack trace/error message**
```
┌── test_print ──────
│ error[E11001]: test failure
│    ┌─ /Users/jpark/Work/aptos-core/aptos-move/framework/aptos-stdlib/sources/string_utils.move:71:16
│    │
│ 71 │     native fun native_format<T>(s: &T, type_tag: bool, canonicalize: bool, single_line: bool, include_int_types: bool): String;
│    │                ^^^^^^^^^^^^^
│    │                │
│    │                INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a INTERNAL_TYPE_ERROR (code 2009) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::string_utils rooted here
│    │                In this function in 0x1::string_utils
│
│
└──────────────────

Test result: FAILED. Total tests: 10; passed: 9; failed: 1
{
  "Error": "Move unit tests failed"
}
```

## Expected Behavior
It prints out `signer(@0x123)` without any error.

**Comment by Ksu8Happy** [comment]
> # 🐛 Bug
> `string_utils::native_format` has an issue with formatting signer values.
> 
> ## To reproduce
> **Code snippet to reproduce** Try to print signer values
> 
> ```rust
>     #[test(s1=@0x123)]
>     fun test_print(s1: signer) {
>         print(&s1); // aptos_std::debug::print
>     }
> ```
> 
> **Stack trace/error message**
> 
> ```
> ┌── test_print ──────
> │ error[E11001]: test failure
> │    ┌─ /Users/jpark/Work/aptos-core/aptos-move/framework/aptos-stdlib/sources/string_utils.move:71:16
> │    │
> │ 71 │     native fun native_format<T>(s: &T, type_tag: bool, canonicalize: bool, single_line: bool, include_int_types: bool): String;
> │    │                ^^^^^^^^^^^^^
> │    │                │
> │    │                INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
> │ Test was not expected to error, but it gave a INTERNAL_TYPE_ERROR (code 2009) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::string_utils rooted here
> │    │                In this function in 0x1::string_utils
> │
> │
> └──────────────────
> 
> Test result: FAILED. Total tests: 10; passed: 9; failed: 1
> {
>   "Error": "Move unit tests failed"
> }
> ```
> 
> ## Expected Behavior
> It prints out `signer(@0x123)` without any error.
