### ISSUE TITLE
[Bug] error out in compilation when encounter an unknown annotation/attribute

### ISSUE THREAD

**Issue by lightmark** [aptos-labs/aptos-core#8875]
# 🚀 Feature Request

Compiler ignores unknown annotations but actually it should just error out. Otherwise, typo must be introduced while the author doesn't know. For example -> https://github.com/aptos-labs/aptos-core/pull/8866 for examples.

## Motivation
`#[testonly]` in  https://github.com/aptos-labs/aptos-core/pull/8866 for examples.

**Comment by brmataptos** [comment]
list of allowed attributes is implicitly in the constants defined [here](https://github.com/aptos-labs/aptos-core/blob/564f66ad09f3fe26cfa10e63c834c2de69a7ca31/third_party/move/move-compiler/src/shared/mod.rs#L518).   

Oops, [extended_checks.rs](https://github.com/aptos-labs/aptos-core/blob/c8e0581f9b8a8aa1888f118c881a8073d1e5172a/aptos-move/framework/src/extended_checks.rs#L24) also has a few known attributes ("legacy_entry_fun", "view", "group", "scope", "resource_group", "resource_group_member", "group"), with an odd variety of constant names associated with them.

We’re also missing #[deprecated{

----
More from Slack discussion:

Kevin Hoang
Another thing to note is we need a good error message in case users already use some custom attributes

Wolfgang Grieskamp
The cli needs a flag to skip those checks

Kevin Hoang
We might also consider giving a harsher warning for variants of test_only such as testonly as those are the most risky ones (accidentally releasing test code)

**Comment by brmataptos** [comment]
Specific Requirements:
- mechanism to register and check known attribute names from various code
- register attributes
  - third_party/move/move-compiler/src/shared/mod.rs#L518
  - aptos-move/framework/src/extended_checks.rs#L24
  - #[deprecated]
- good error message in case users use custom attributes
  - CLI needs a flag to skip those checks
  - maybe a flag to allow registering more attributes
- also consider harsher warning for variants of test_only such as testonly
- tests

**Comment by brmataptos** [comment]
Wolfgang is apparently greatly proposed to a flag registering more attributes, so we'll just have a flag to skip checks.

**Comment by wrwg** [comment]
Yes, I do think we should leave user registerable attributes to the compiler v2 and language extensions. Specifically, I propose to do attributes similar as in C#/Java, so they can be declared in the language, together with typing of their parameters, as in:

```
#[define_attribute] public fun my_attribute(param1: u64, param2: String)
```

Besides this being more general, the flag approach doesn't seem to cover what people expect from compiler command line options. A user would have to every single time specify this options, if he forgets, then compilation fails. Moreover, the allowed parameters of the attributes cannot be easily defined this way.

I assume at this point not many people are out there which actually use there own attributes. Those few can be grandfathered by the the single flag `--skip-attribute-checks`.
