### ISSUE TITLE
[Bug] [TS SDK] Incorrect serialization of TypeTagU16, TypeTag32 и TypeTag256

### ISSUE THREAD

**Issue by buuni** [aptos-labs/aptos-core#8899]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```ts
const serializer = new Serializer()
const tag = new TypeTagU32()

tag.serialize(serializer)
const deserialized = TypeTag.deserialize(new Deserializer(serializer.getBytes()))
console.log(deserialized) // TypeTagU8 {}
```

## Expected Behavior

Expected to get back the same TypeTagU32.
This also applies to TypeTagU16 and TypeTagU256.

## System information

**Please complete the following 

information:**
- Typescript AptosSDK v1.11.0
-  MacOS 13.1 (22C65)

## Additional context

Due to this error, it is not possible to correctly generate transactions for sending to the blockchain

**Comment by davidiw** [comment]
looks like this was fixed.
