### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sohaibb98** [aptos-labs/aptos-core#8953]
# 🐛 Invalid usage of reference as function argument. Cannot transfer a mutable reference that is being borrowed

While working with `simple_map`, i am trying to remove an element from it while having one of the elements in the map stored in a variable. Move Compiler doesn't let me do this operation as it is unable to transfer mutable reference to a function in this situation, giving me the error.

## To reproduce

**Code snippet to reproduce**

```
let offer = simple_map::borrow(&state.offers, &offer_id);
assert_dispute_opened(offer);

// Call assert_singer_is_arbiter function
assert_singer_is_arbiter(arbiter, offer);

// Remove the offer from the list of available offers
simple_map::remove(&mut state.offers, &offer_id);
```

**Stack trace/error message**
```
424 │         let offer = simple_map::borrow(&state.offers, &offer_id);
    │                     -------------------------------------------- It is still being borrowed by this reference
    ·
431 │         simple_map::remove(&mut state.offers, &offer_id);
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of reference as function argument. Cannot transfer a mutable reference that is being borrowed
```

## Expected Behavior

This should be working without any problems, unless i am missing some built-in functionality of the Simple map

## System information
Aptos 2.0.1
Windows 10

**Comment by iArunava** [comment]
@Sohaibb98 what was the resolution here?
