### ISSUE TITLE
[Bug] The Aptos CLI does not accept u64 arguments in view functions

### ISSUE THREAD

**Issue by xbtmatt** [aptos-labs/aptos-core#8982]
# 🐛 Bug

When you try to run a view function with the aptos CLI where an argument is of type `u64`, the CLI will give an error if you don't pass it a `string` type:

## To reproduce

**Code snippet to reproduce**
```rust
module package_name::test {
    #[view]
    public fun test_u64(n: u64): u64 {
        n
    }
}
```

Publish:

`aptos move publish --named-addresses package_name=default --url https://fullnode.devnet.aptoslabs.com`

Run:

`aptos move view --function-id default::test::test_u64 --args u64:1`

**Stack trace/error message**
```shell
{
  "Error": "API error: API error Error(InvalidInput): parse arguments[0] failed,
    expect string<u64>, caused by error: invalid type: integer `1`, expected a string"
}
```

## Current workaround

In the CLI, change `u64` to `string` and it will work.

```shell
aptos move view --function-id default::test::test_u64 --args string:1 --profile default
{
  "Result": [
    "1"
  ]
}
```

## Expected Behavior

The CLI should work with a `u64`.

## System information

Tested on Mac and Windows with aptos version 2.0.1

## Additional context

I suspect the issue is with the lack of serialization for view functions, because `entry` functions work just fine with the same exact function declaration.

**Comment by 0xjinn** [comment]
This is actually fixed from 2 release ago. Closing this issue now
