### ISSUE TITLE
[Bug][Explorer] Explorer does not render private view functions

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#8991]
@davidiw @banool @CapCap

View functions can be declared as private when the output of the view function is generated by consuming a resource such that the write set is simply thrown away per #8539 

Presently, the explorer does not render view functions that are declared private, even though these should be publicly accessible outside of the VM

**Comment by davidiw** [comment]
https://github.com/aptos-labs/explorer

please re-open here and maybe a link to an example where this doesn't work?

**Comment by alnoki** [comment]
> https://github.com/aptos-labs/explorer
> 
> please re-open here and maybe a link to an example where this doesn't work?

@davidiw the issue I linked in this issue's description contains such an example in its description. Here it is again:

Private view function source code: https://github.com/econia-labs/econia/blob/c79e58eeb7129029d9336edd6205c8aaf73e3866/src/move/econia/sources/market.move#L935-L980

CLI view output:

```
econia_testnet_addr=0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135
aptos move view \
    --function-id $econia_testnet_addr::market::index_orders \
    --args String:1
{
  "Result": [
    {
      "asks": [],
      "bids": [
        {
          "custodian_id": "0",
          "order_access_key": "1",
          "price": "900",
          "size": "1",
          "user": "0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135"
        },
        {
          "custodian_id": "0",
          "order_access_key": "2",
          "price": "899",
          "size": "1",
          "user": "0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135"
        },
        {
          "custodian_id": "0",
          "order_access_key": "3",
          "price": "898",
          "size": "1",
          "user": "0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135"
        }
      ]
    }
  ]
}
```

Explorer link with missing view function:

https://explorer.aptoslabs.com/account/0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135/modules/view/assets?network=testnet

Explorer render with `market::index_orders` missing:

<img width="641" alt="Screenshot 2023-07-16 at 06 57 11" src="https://github.com/aptos-labs/aptos-core/assets/43892045/53e458d5-604f-48c0-8dd0-40ccf6169aef">

**Comment by alnoki** [comment]
@davidiw will you please re-open the issue per my above description?

Apparently I do not have permissions to re-open as I am a community contributor

**Comment by alnoki** [comment]
Per @davidiw 's suggestion closing in lieu of https://github.com/aptos-labs/explorer/issues/571
