### ISSUE TITLE
aptos 2.0.2 build failure

### ISSUE THREAD

**Issue by chenrui333** [aptos-labs/aptos-core#8993]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
    --> crates/aptos-runtimes/src/lib.rs:34:10
     |
  29 | /     builder
  30 | |         .thread_name_fn(move || {
  31 | |             let id = atomic_id.fetch_add(1, Ordering::SeqCst);
  32 | |             format!("{}-{}", thread_name_clone, id)
  33 | |         })
  34 | |         .disable_lifo_slot()
     | |         -^^^^^^^^^^^^^^^^^ private field, not a method
     | |_________|
     | 
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5481229282/jobs/9985309756?pr=136021
relates to Homebrew/homebrew-core#136021

**Comment by gregnazario** [comment]
@chenrui333 Can we get a little more info about the architecture and all it's running on so we can reproduce and see what we can do?

This should be enabled with `--cfg tokio_unstable`, but I'm not super familiar with the brew build stack

**Comment by gregnazario** [comment]
All cleaned up now.  Thanks for opening the issue!
