### ISSUE TITLE
[Docs Request] Indexer SLA

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#9083]
From Dev Rel feedback, users are reporting that their balances do not show using the Petra in-app browser when they connect their wallet to Tsunami. The Petra team concluded that there may be some race condition on the Tsunami side. The lack of Indexer SLA on latency can lead to confusion in race condition.

**Comment by bowenyang007** [comment]
Can you be more specific on the issue? They're using our public indexer APIs? On testnet? Mainnet? And what is the specific behavioral. 

Latency from PFNs to indexer should be < 500ms. Our SLA is likely guaranteeing 1s (still in the works). But will this solve the problem?
