### ISSUE TITLE
[storage] put a hard limit to the size of a table key.

### ISSUE THREAD

**Issue by msmouse** [aptos-labs/aptos-core#920]
and maybe overall all state key and values, to be defensive.

**Comment by davidiw** [comment]
where should this exist? move? the native function? storage?

**Comment by lightmark** [comment]
a super linear gas cost function based on size wouldn't be enough?

**Comment by msmouse** [comment]
Economical pressure and all are needed, but I think we'd put in a hard limit (from Move side, I think) anyway to have a peace of mind. Once put in, a large value will cost us much any time any one tries to load it, even if the loader doesn't have enough gas -- because we don't know the size before reading it out, and I'd avoid the possibility.

**Comment by sitalkedia** [comment]
@msmouse - Why does this apply only to table keys? We have a similar problem with account resource path as well, right? Do we want to limit that as well?

**Comment by davidiw** [comment]
Have we considered taking a hash and using constant sizing?

**Comment by msmouse** [comment]
Sorry I was thinking state values when I replied yesterday. 
But keys have similar issues, just trying to be defensive here. 

> similar problem with account resource path
It's less of a concern because the language sorta strictly constrains it (it's addr+module_name+type_name), but yeah. 
In the case of table keys, nothing currently prevent one to use a whole large vector as a key.

> taking a hash and using constant sizing
We'll lose the ability to scan an account or a table (can work around, at the cost of even more storage), and/or the benefit when a key/path is actually way smaller than a hash (a u64 is 25% the size of a HashValue)
