### ISSUE TITLE
[compiler v2] Constant folding and constant references

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#9330]
Apparently, the v1 compiler supports constant folding and this effects type checking and allowed values for constants, for example:

```
const C: u64 = 1 + 2;
const BYTES: vector<u8> = b"hello";
const VALUES: vector<u64> = vector[1, 2, 3];
```

It is also possible to take references for constants, e.g. `&BYTES`. This is not supported right now by the v2 compiler. There are a number of test cases around this in `move-compiler/transactional-tests/tests/constants/.

**Comment by wrwg** [comment]
It also turns out that the v1 compiler supports something like `1 << var` and the result will still be an integer of any desired type, similar as a direct constant. This lets compiler v2 currently fail to compile `fixed_point32` in the Move stdlib.

**Comment by wrwg** [comment]
> It also turns out that the v1 compiler supports something like `1 << var` and the result will still be an integer of any desired type, similar as a direct constant. This lets compiler v2 currently fail to compile `fixed_point32` in the Move stdlib.

This particular issue has been fixed, so its only constant folding itself.

**Comment by vineethk** [comment]
Some clarification here: what is remaining to be done is implement constant folding as an optimization pass.

**Comment by wrwg** [comment]
> Some clarification here: what is remaining to be done is implement constant folding as an optimization pass.

Yes, but there is one functional aspect as well, namely that one can write `const FOO: u64 = 1 + 2`, which is currently not possible. However, I don't think there are many use cases for this.

**Comment by brmataptos** [comment]
I take this as the problem of (1) writing move-model AST which represents non-literal constant expressions such as the above, (2) [optional] a pass to rewrite those non-literal expressions to literals before code generation, and (3) supporting constants like `&BYTES`.

**Comment by vineethk** [comment]
We should revert this change: https://github.com/aptos-labs/aptos-core/pull/11101/files (i.e., change this function back to a constant: https://github.com/aptos-labs/aptos-core/blob/d1f883907cd11d3fee5847fcbbc7d19545018fb5/aptos-move/framework/aptos-stdlib/tests/fixedpoint64_tests.move#L5) after this issue is resolved.
