### ISSUE TITLE
[Bug] There cannot send to balance to receiving wallet if the receiving wallet has not been faucet

### ISSUE THREAD

**Issue by pierreneter** [aptos-labs/aptos-core#934]
# 🐛 Bug

## To reproduce

We have:
- Valid address A has been faucet
- Valid address B has not been faucet
-  Send a amount of `0x1::TestCoin` of address A to valid address B
- Got error transaction

**Stack trace/error message**

- Error transaction: https://explorer.devnet.aptos.dev/txn/1061125

```
Move abort by NOT_PUBLISHED - EBALANCE_NOT_PUBLISHED A resource is required but not published. Example: access to non-existing AccountLimits resource.
```

## Expected Behavior

Can send the balance to a valid address

## System information

- Node use: https://fullnode.devnet.aptoslabs.com

## Additional context

If address B has been faucet, the tx will success.

**Comment by davidiw** [comment]
The account hasn't been created. You can either create B from A or have Faucet create account for B. We are exploring implicit account creation, but have not landed on whether or not that's something we're going to support. In the meantime, we should add more to our guides.

cc: @jjleng who is working in this space.

**Comment by arya0067** [comment]
i have used fewcha wallet more than 15 days everything work  is fine
