### ISSUE TITLE
[Feature Request][API] Add event lookup by transaction

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#9362]
@bogberry @davidiw @banool 

Presently the Aptos explorer shows the events for a transaction, but there is no simple way to query this information using the REST API

It is suggested that the REST API include an endpoint for getting the events associated with a transaction

**Comment by davidiw** [comment]
Considering that you can get the events by querying the transactions API, this seems redundant.

If you select the 2nd option here, you can see the events: https://mainnet.aptoslabs.com/v1/spec#/operations/get_transaction_by_hash

Validated in Python: https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/python/sdk/aptos_sdk/aptos_token_client.py#L626

**Comment by alnoki** [comment]
> Considering that you can get the events by querying the transactions API, this seems redundant.
> 
> If you select the 2nd option here, you can see the events: https://mainnet.aptoslabs.com/v1/spec#/operations/get_transaction_by_hash
> 
> Validated in Python: https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/python/sdk/aptos_sdk/aptos_token_client.py#L626

@davidiw right, thanks!
