### ISSUE TITLE
[Bug] Patched merlin dependency not picked up when using aptos-sdk

### ISSUE THREAD

**Issue by JasperTimm** [aptos-labs/aptos-core#9377]
# 🐛 Bug

When attempting to build a Rust project with the `aptos-sdk` (current devnet branch) as a dependency, the patched version of `merlin` created by Aptos Labs is not used, but the original version 3, which causes compilation issues as follows:

`error[E0597]: `dst` does not live long enough
   --> /home/opc/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/2759c32/aptos-move/framework/src/natives/cryptography/bulletproofs.rs:207:45`

## To reproduce

`cargo build` with the devnet branch of `aptos-sdk`

**Stack trace/error message**
```
error[E0597]: `dst` does not live long enough
   --> /home/opc/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/2759c32/aptos-move/framework/src/natives/cryptography/bulletproofs.rs:207:45
```

## Expected Behavior

Compiles successfully

## System information

**Please complete the following information:**
-  
-  1.70.0
-  MacOS

## Additional context

A patched version of the `merlin` dep is used in the Aptos libs, with [this](https://github.com/aptos-labs/merlin/commit/3454ccc85e37355c729ba40e6dac6e867ddf59f5) commit added. 

[This](https://github.com/aptos-labs/aptos-core/blob/devnet/Cargo.toml#L682) line has been added to the main Cargo.toml to ensure the patched version of `merlin` is used, but that doesn't seem to resolve the problem for those that use the `aptos-sdk` themselves (at least it didn't for me!), i.e. the crates-io version is used, not the patched version.

Current workaround: whoever used the `aptos-sdk` also needs to add the patched version to their Cargo.toml. I'm not sure if there's a better solution than this.

**Comment by crazybits** [comment]
same issue here when use rest-client depends on aptos-core main branch, below is the project dependencies

[dependencies]

> aptos-rest-client = { git = "https://github.com/aptos-labs/aptos-core",branch ="main" }
> aptos-types = { git = "https://github.com/aptos-labs/aptos-core",branch ="main" }
> aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core",branch ="main" }
> aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core",branch ="main" }
> move-core-types =  { git = "https://github.com/aptos-labs/aptos-core", branch ="main" } 
> bcs = { git = "https://github.com/aptos-labs/bcs", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" }
> 
> anyhow = "1.0.57"
> futures = "0.3.24"
> hex = "0.4.3"
> serde = "1.0.147"
> url = "2.3.1"
> actix-rt = "*"
> clap = "4.0.22"
> primitive-types = "0.12.1"
> async-trait = "0.1.58"
> tokio = { version = "1.32.0", features = ["full"] }

**Comment by gregnazario** [comment]
Associated with https://github.com/aptos-labs/aptos-core/issues/9340

**Comment by gregnazario** [comment]
I've attached more information here: https://github.com/aptos-labs/aptos-core/issues/9340 about fixing this dependency, but it's dependent on the authors of Merlin.  Please follow that issue for updates.
