### ISSUE TITLE
[Feature Request] Return 410 for queries on pruned data

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#9523]
Because the change would've been more complicated, we chose to just return 404 when querying by version for a transaction here: https://github.com/aptos-labs/aptos-core/pull/9520. In reality we should return 410. There are other cases where we should return 410 but currently return 404 as well, we should make sure to return 410 in all appropriate places.

**Comment by banool** [comment]
Actually I got it to work in the issue, so the txn by version endpoint works with 410 as intended now. I'm leaving this issue open to make sure we investigate all other endpoints though.

**Comment by lbmeiyi** [comment]
Confirmed with @banool that we are good to close this issue out now.
