### ISSUE TITLE
[Bug] Mainnet aptos indexer node stuck

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#9591]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
run aptos indexer node(mainnet) v1.5.1
```

**Stack trace/error message**
```
[sync-driver-6] ERROR state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:957 {"message":"Storage synchronizer error: \"Failed to commit executed chunk! Error: base_state_version Some(216019951) does not equal to the base_version Some(216020123) in buffered state with current version Some(216020123)\"","name":"storage_synchronizer"}
```
indexer node need set `enable_indexer=true`, which will result in the error

## Expected Behavior
should not stuck

## System information

**Please complete the following information:**
-  v1.5.1
- 
- 

## Additional context

and restart indexer node will fail:
```
2023-08-10T01:12:42.563552Z [main] WARN aptos-node/src/lib.rs:193 Failpoints are enabled!
details = '''panicked at 'Node should start correctly: DB failed to open There is still pending table items to parse due to unknown table info for table handles: [TableHandle(088848d56cffcf0b77e60702a4faf78d0e98ea7d910ca7f1d30544daf5932e8a), TableHandle(2d229d50f952c8a677c1515de3ed7624cb5f6c9678bef8f8c2567c66fb5ecb96)]', aptos-node/src/lib.rs:154:39'''
backtrace = '''
   0:     0x55992cd78d86 - backtrace::backtrace::libunwind::trace::h1e56b38ae1db3894
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hba3a90c0e28417ff
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::he3569da9cd8cfddb
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x55992cd626b1 - backtrace::capture::Backtrace::create::hc5a4da796d4be649
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::hba93c373b59be48d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x55992ab6e0e4 - aptos_crash_handler::handle_panic::h537984001687c0b2
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::h3a07a66527e50d44
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:29:9
   3:     0x55992d109669 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbb63890df2a28e48
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
                           std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:692:13
   4:     0x55992d1093e7 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
   5:     0x55992d107ccc - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
   6:     0x55992d109102 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   7:     0x55992d12bf23 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   8:     0x55992d12c433 - core::result::unwrap_failed::h065c02f906ca4578
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   9:     0x55992a6c965d - core::result::Result<T,E>::expect::h717c614bb1b63ad4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1070:23
                           aptos_node::AptosNodeArgs::run::ha84a727332d40de1
                               at /usr/src/indexer-node/aptos-node/src/lib.rs:154:13
  10:     0x55992a5ebe56 - aptos_node::main::h7416ec47e11788dc
                               at /usr/src/indexer-node/aptos-node/src/main.rs:19:5
  11:     0x55992a5e9a36 - core::ops::function::FnOnce::call_once::h36ac7eb7d6834d37
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
                           std::sys_common::backtrace::__rust_begin_short_backtrace::hfa71b0f0adc537e5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121:18
  12:     0x55992a5ebf8c - std::rt::lang_start::{{closure}}::h645a61d9c7131eaa
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:166:18
  13:     0x55992d0f9bcb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8cbb48ae40ddb046
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:286:13
                           std::panicking::try::do_call::h92db802eb38b49b7
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
                           std::panicking::try::ha8949d2082cf3644
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
                           std::panic::catch_unwind::h5e34c1f8a5992ed9
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
                           std::rt::lang_start_internal::{{closure}}::hea52a0bb3f8ff16a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:48
                           std::panicking::try::do_call::h5bc358faf3d68a8b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
                           std::panicking::try::h675304212928379d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
                           std::panic::catch_unwind::h7ce3ad349ed5c844
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
                           std::rt::lang_start_internal::hcd7e45acd25ab5ab
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:20
  14:     0x55992a5ebf74 - main
  15:     0x7fe2df02ed0a - __libc_start_main
  16:     0x55992a5e77aa - _start
  17:                0x0 - <unknown>
'''
```

**Comment by lhenriks** [comment]
Same problem here with v1.5.1 and exactly the same error message.

**Comment by sherry-x** [comment]
Hey folks, could you please try upgrading your indexer fullnode to v1.6.2 and see if your issue is resolved by it? https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.6.2

**Comment by lhenriks** [comment]
> Hey folks, could you please try upgrading your indexer fullnode to v1.6.2 and see if your issue is resolved by it? https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.6.2

I can confirm that the indexer is syncing again, thanks a lot!

**Comment by Astrapolis-peasant** [comment]
I started to resync from block 0 with version 1.6.2. Here is the error I got
```
details = '''panicked at 'Node should start correctly: DB failed to open Write set missing for version 1, got version 227130524', aptos-node/src/lib.rs:153:39'''
backtrace = '''
   0:     0x55e110fcc207 - backtrace::backtrace::libunwind::trace::hac1dc6e0bd6020bd
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h10a35bea07747b6e
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h63f960f423be8f75
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x55e110fdfb8a - backtrace::capture::Backtrace::create::h520cae756dd2df1a
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::hdb6a7b0d58516c7d
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x55e10f173f66 - aptos_crash_handler::handle_panic::hb28489fdde810d86
                               at /home/ubuntu/aptos-core/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::h56194758976ae17f
                               at /home/ubuntu/aptos-core/crates/crash-handler/src/lib.rs:29:9
   3:     0x55e111361fa4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb9b860f5a1175bda
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
                           std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   4:     0x55e111361d19 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   5:     0x55e111360806 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   6:     0x55e111361a72 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   7:     0x55e111387283 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   8:     0x55e111387733 - core::result::unwrap_failed::h8090202169109f9c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   9:     0x55e10ed1a1f6 - core::result::Result<T,E>::expect::h1a7c3416bc166250
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1046:23
                           aptos_node::AptosNodeArgs::run::h4aead42a98e196ea
                               at /home/ubuntu/aptos-core/aptos-node/src/lib.rs:153:13
  10:     0x55e10ec68ad6 - aptos_node::main::h17c6dd5fd597cfff
                               at /home/ubuntu/aptos-core/aptos-node/src/main.rs:19:5
  11:     0x55e10ec68c06 - core::ops::function::FnOnce::call_once::h272c4c189b2088ba
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
                           std::sys_common::backtrace::__rust_begin_short_backtrace::h5a2472a52db3d36f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  12:     0x55e10ec68c1c - std::rt::lang_start::{{closure}}::h183963cacd7a4427
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  13:     0x55e11135416e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
                           std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
                           std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
                           std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
                           std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
                           std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
                           std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
                           std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
                           std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  14:     0x55e10ec68bf4 - main
  15:     0x7f78fc629d90 - <unknown>
  16:     0x7f78fc629e40 - __libc_start_main
  17:     0x55e10ec660a5 - _start
  18:                0x0 - <unknown>
'''
```

**Comment by larry-aptos** [comment]
> I started to resync from block 0 with version 1.6.2. Here is the error I got
> 
> ```
> details = '''panicked at 'Node should start correctly: DB failed to open Write set missing for version 1, got version 227130524', aptos-node/src/lib.rs:153:39'''
> backtrace = '''
>    0:     0x55e110fcc207 - backtrace::backtrace::libunwind::trace::hac1dc6e0bd6020bd
>                                at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
>                            backtrace::backtrace::trace_unsynchronized::h10a35bea07747b6e
>                                at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:66:5
>                            backtrace::backtrace::trace::h63f960f423be8f75
>                                at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:53:14
>    1:     0x55e110fdfb8a - backtrace::capture::Backtrace::create::h520cae756dd2df1a
>                                at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:176:9
>                            backtrace::capture::Backtrace::new::hdb6a7b0d58516c7d
>                                at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:140:22
>    2:     0x55e10f173f66 - aptos_crash_handler::handle_panic::hb28489fdde810d86
>                                at /home/ubuntu/aptos-core/crates/crash-handler/src/lib.rs:37:38
>                            aptos_crash_handler::setup_panic_handler::{{closure}}::h56194758976ae17f
>                                at /home/ubuntu/aptos-core/crates/crash-handler/src/lib.rs:29:9
>    3:     0x55e111361fa4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb9b860f5a1175bda
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
>                            std::panicking::rust_panic_with_hook::hafdc493a79370062
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
>    4:     0x55e111361d19 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
>    5:     0x55e111360806 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
>    6:     0x55e111361a72 - rust_begin_unwind
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
>    7:     0x55e111387283 - core::panicking::panic_fmt::h0f6ef0178afce4f2
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
>    8:     0x55e111387733 - core::result::unwrap_failed::h8090202169109f9c
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
>    9:     0x55e10ed1a1f6 - core::result::Result<T,E>::expect::h1a7c3416bc166250
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1046:23
>                            aptos_node::AptosNodeArgs::run::h4aead42a98e196ea
>                                at /home/ubuntu/aptos-core/aptos-node/src/lib.rs:153:13
>   10:     0x55e10ec68ad6 - aptos_node::main::h17c6dd5fd597cfff
>                                at /home/ubuntu/aptos-core/aptos-node/src/main.rs:19:5
>   11:     0x55e10ec68c06 - core::ops::function::FnOnce::call_once::h272c4c189b2088ba
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
>                            std::sys_common::backtrace::__rust_begin_short_backtrace::h5a2472a52db3d36f
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
>   12:     0x55e10ec68c1c - std::rt::lang_start::{{closure}}::h183963cacd7a4427
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
>   13:     0x55e11135416e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
>                            std::panicking::try::do_call::h4044173225fe83dd
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
>                            std::panicking::try::hd8a722c09d156a53
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
>                            std::panic::catch_unwind::hd2ca07971cf0119b
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
>                            std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
>                            std::panicking::try::do_call::hf47aa1aa005e5f1a
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
>                            std::panicking::try::h73d246b2423eaf4e
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
>                            std::panic::catch_unwind::hbaaeae8f1b2f9915
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
>                            std::rt::lang_start_internal::h76f3e81e6b8f13f9
>                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
>   14:     0x55e10ec68bf4 - main
>   15:     0x7f78fc629d90 - <unknown>
>   16:     0x7f78fc629e40 - __libc_start_main
>   17:     0x55e10ec660a5 - _start
>   18:                0x0 - <unknown>
> '''
> ```

You need a node with full history to start indexing. check this: https://aptos.dev/nodes/full-node/aptos-db-restore/
