### ISSUE TITLE
[Bug] [compiler-v2] transactional tests have problems with module use

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#9629]
# 🐛 Bug

The stdlib doesn't seem to be useable in compiler-v2/transactional-tests/, see sorter.move.  Lots of errors due to "unbound module" shown in sorter.exp.  It works under compiler-v1, as shown.

After replacing stdlib calls with some stubs I got sorter_gutted.move, which fails with the same error for a locally-defined module.  Oddly, there seems to be a working transactional test with a  similar locally-defined module use (control_flow/if_assignment.move) so this may be nontrivial.

## To reproduce

Cherry-pick
https://github.com/aptos-labs/aptos-core/commit/ac7f00faf408aa169ea8defc6a4a73bdcbe0def9

For transactional-tests inputs and outputs for sorter.move and sorter_gutted.move, for both v1 and v2.

## Observed output for sorter_gutted.move:

```
task 0 'publish'. lines 1-88:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::heap'.  Got VMError: {
     major_status: CALL_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::heap,
    indices: redacted,
    offsets: redacted,
}

task 1 'run'. lines 90-96:
Error: compilation errors:
 error: unbound module
   ┌─ /var/folders/vj/lyj2zgcs56lgg2jlktrz55rc0000gn/T/.tmp4wjMYK:92:9
   │
92 │     use 0x42::heap::main;
   │         ^^^^^^^^^^ Invalid 'use'. Unbound module: '0x42::heap'
```

**Comment by f13end** [comment]
It seems like you are facing issues with using the stdlib and locally-defined modules in the context of the compiler-v2/transactional-tests/ environment. The errors you're encountering are related to "unbound module" errors, both in the context of the stdlib (sorter.move) and in your locally-defined module (sorter.exp and sorter_gutted.move).

Best Regards
https://landindex.io
