### ISSUE TITLE
[Bug] [Compiler] Error message for lambda param to non-inlined methods is poor

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#9694]
# 🐛 Bug

Max reported a misleading error message when a lambda parameter is provided to a non-inlined function:
> when trying this, I get Incompatible type '|T,T| -> bool', expected '|T,T| -> bool' ; is this because it’s recursive, or am I missing something?
```
    /// Predicate expects result that is (a < b)
    public fun quicksort<T: copy>(arr: &mut vector<T>, a_less_b: |T, T| bool) {
        let n = vector::length(arr);
        quicksort_rec<T>(arr, 0, n - 1, a_less_b)
    }

    public fun quicksort_rec<T: copy>(arr: &mut vector<T>, low: u64, high: u64, a_less_b: |T, T| bool) {
        if (low < high) {
            let pi = partition(arr, low, high, a_less_b);
            quicksort_rec(arr, low, pi - 1, a_less_b);
            quicksort_rec(arr, pi + 1, high, a_less_b);
        };
    }
```

We need to make the error messages more informative.

There are 2 problems with this code:

- lambda parameters are only allowed on inline functions
- lambda parameters currently can't be passed to other calls, even inline

If we make the functions inline there should be a complaint about recursive inlines instead.

We should add a test case and fix the error messages.

**Comment by wrwg** [comment]
Some clarification

> There are 2 problems with this code:
> 1. lambda parameters are only allowed on inline functions
> 2. lambda parameters currently can't be passed to other calls, even inline

(1) should be: function parameters (that is parameters with function types) are only allowed for inline functions
(2) should be: the actual parameter for a function parameter can only be a lambda

Adding this as @vineethk may work on this

**Comment by vineethk** [comment]
Closing on account of the PR: https://github.com/aptos-labs/aptos-core/pull/10037
