### ISSUE TITLE
[Docs] Write docs for the indexer

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#9758]
This issue tracks progress on writing docs for the new indexer stack. These docs are meant to just get us going, there are more we could write and a lot of additional polish we could apply. In many cases we already have most of what we need, we just need to adjust it to fit into the docs site + the indexer docs story properly.

These issues are for docs to work on with the team:

- https://github.com/aptos-labs/aptos-core/issues/9777
- https://github.com/aptos-labs/aptos-core/issues/9778
- https://github.com/aptos-labs/aptos-core/issues/9779
- https://github.com/aptos-labs/aptos-core/issues/9780
- https://github.com/aptos-labs/aptos-core/issues/9781
- https://github.com/aptos-labs/aptos-core/issues/9782

---

This checklist is for items in the initial docs spree:

- [x] `indexer/indexer-landing`: This needs a diagram for the new system. The overview needs to be updated. This is an index, the focus needs to be on helping users find the docs they’re looking for.
  - https://github.com/aptos-labs/aptos-core/pull/9738
- [x] `api/labs-hosted`: Explain how to get a key for using our Indexer API.
  - https://github.com/aptos-labs/aptos-core/pull/9763
- [x] `api/self-hosted` **(processor)**: Explain how to run the API. Start with pointing out that they can choose to use our txn stream or run their own. Link to txn-stream/labs-hosted for information about our instance, e.g. URLs, keys, etc. Talk about how to run the service.
  - https://github.com/aptos-labs/aptos-core/pull/9762
- [x] `api/example-queries`: Either flesh this out or eliminate it and just link to somewhere else where we have the queries (e.g. in the TS SDK). Could be a subpage of the usage guide.
  - I reference the queries in the TS SDK in this PR: https://github.com/aptos-labs/aptos-core/pull/9738
- [x] `txn-stream/labs-hosted`: Add ratelimit information. Use URLs instead of IPs when we have them. Explain how to get a key for using our Indexer API.
  - https://github.com/aptos-labs/aptos-core/pull/9737
- [x] `txn-stream/local-development`: Pretty much just explain the prereqs and how to use the Python script in aptos-core.
  - https://github.com/aptos-labs/aptos-core/pull/9734
- [x] `custom-processors/txn-parsing`: Guide to parsing transactions. Should have a tab per language with code snippets for how to do particular things, e.g. get the args to an entry function, to get the events, etc. Might not be worth writing until we make this much easier. Bowen wrote some stuff here: [How to read a transaction](https://www.notion.so/How-to-read-a-transaction-a66ac334cd7945159915a2fa110b058f?pvs=21).
  - https://github.com/aptos-labs/aptos-core/pull/9756
- [ ] `custom-processors/tutorial`: Tutorial for writing (and perhaps deploying) your own processor. For now just take Matt’s tutorial and adapt it for each language (in tabs if they’re similar enough or separate pages otherwise).
  - Partially complete, but we need to release the SDK as a package before continuing. See more in https://github.com/aptos-labs/aptos-core/pull/9755.

**Comment by banool** [comment]
The custom processing tutorial and quick start are somewhat blocked on this: https://aptos-org.slack.com/archives/C057CMMRLKT/p1692877496467279.

**Comment by banool** [comment]
The self hosted txn stream service is somewhat blocked on https://aptos-org.slack.com/archives/C04PRP1K1FZ/p1692733343741049.

**Comment by bowenyang007** [comment]
For the initial partner launch, we should prioritize
* indexer-landing
* api/self-hosted
* txn-stream/labs-hosted

we actually don't have any api gateway for indexer right now.
