### ISSUE TITLE
arm architecture Linux

### ISSUE THREAD

**Issue by chan-bing** [aptos-labs/aptos-core#9815]
Can Linux with arm architecture install aptos-cli?

**Comment by banool** [comment]
Hi, this is not possible right now, we only publish an x86 build of the CLI. Could you talk more about your use case?

**Comment by chan-bing** [comment]
Hi, I finally used brew to install cli, but got the following error when installing Move Prover with “./scripts/dev_setup.sh -yp”:
<img width="565" alt="截屏2023-08-30 01 08 44" src="https://github.com/aptos-labs/aptos-core/assets/115219896/b7407993-08b5-4ef9-9ba3-c40eaff7d3d8">
My system is macos Ventura.

**Comment by rahxephon89** [comment]
Hi @chan-bing, the error comes from installation of cvc5 while the prover only uses z3 now. With this error, can you still use the prover?

**Comment by chan-bing** [comment]
A new issue has arisen where the version of boogie installed using the script is too high:
<img width="719" alt="截屏2023-08-30 03 01 58" src="https://github.com/aptos-labs/aptos-core/assets/115219896/4dac30cf-df75-4d38-ae37-fda7b4c945d6">

**Comment by rahxephon89** [comment]
you need to generate a new aptos cli on main

**Comment by chan-bing** [comment]
Do you mean I install cli via script instead of brew?

**Comment by rahxephon89** [comment]
Running `dev_setup` along only installs z3 and boogie for you. You still need to build the cli by 1) switch to the `main` branch; 2) under `aptos-core/crates/aptos`, execute the command `cargo install --path . --locked`. After the new cli is built, you need to make sure that `aptos move` commands uses this new binary.

**Comment by chan-bing** [comment]
Ohhhh! It works,thank you!
