### ISSUE TITLE
[Bug] error[E0599] when executing "cargo install"

### ISSUE THREAD

**Issue by apollox-apx** [aptos-labs/aptos-core#9833]
# 🐛 Bug

I encountered an error while executing the command `cargo install --git https://github.com/aptos-labs/aptos-core aptos --branch main`. The error is related to the method `disable_lifo_slot` for mutable reference `&mut tokio::runtime::Builder`.

## To reproduce

**Command to reproduce**
```
cargo install --git https://github.com/aptos-labs/aptos-core aptos --branch main
```

**Stack trace/error message**
```
error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
  --> crates/aptos-runtimes/src/lib.rs:45:10
   |
39 | /     builder
40 | |         .thread_name_fn(move || {
41 | |             let id = atomic_id.fetch_add(1, Ordering::SeqCst);
42 | |             format!("{}-{}", thread_name_clone, id)
43 | |         })
44 | |         .on_thread_start(on_thread_start)
45 | |         .disable_lifo_slot()
   | |         -^^^^^^^^^^^^^^^^^ private field, not a method
   | |_________|
   |
```

## Expected Behavior

The command should run successfully without encountering the error mentioned above.

## System information

**Please complete the following information:**
- Aptos Core Version (main branch)
- Rust Version: 1.72.0
- Computer OS: MacOS 13.5.1 (Apple M-series chip)

## Additional context

Please let me know if there are any additional information or steps needed to resolve this issue.
```

**Comment by crazybits** [comment]
@apollx-apx  `RUSTFLAGS="--cfg tokio_unstable"  cargo build `  could solve your issue

**Comment by lbmeiyi** [comment]
Is this issue still outstanding?

**Comment by lbmeiyi** [comment]
I'm going to close this out for now, please feel free to reopen a new one if the issue still persist. thanks.
