### ISSUE TITLE
[Bug]Can not get Rpc api transactions by "Get account transactions"

### ISSUE THREAD

**Issue by and2352000** [aptos-labs/aptos-core#9856]
# 🐛 Bug

I am trying to check history data through rpc api by "get account transactions", but found out some of transaction is missing.
This is account I tried to get [Explorer link]
(https://explorer.aptoslabs.com/account/0x4922feaf9457b85ea25422df63bd50d40894bb08549d93f5fea77ffbd33c4f56?network=mainnet)
## To reproduce
[API Doc](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account_transactions)
  
0x4922feaf9457b85ea25422df63bd50d40894bb08549d93f5fea77ffbd33c4f56 is reciever
Got empty array
```shell
curl --request GET --url 'https://fullnode.mainnet.aptoslabs.com/v1/accounts/0x4922feaf9457b85ea25422df63bd50d40894bb08549d93f5fea77ffbd33c4f56/transactions?limit=5&start=243204796' --header 'Accept: application/json'
```
0xa444c6ac449f3552f960d201ad15d350c77a3c52467a6f8d9ca3d75feecb9601 is sender
```shell
curl --request GET --url 'https://fullnode.mainnet.aptoslabs.com/v1/accounts/0xa444c6ac449f3552f960d201ad15d350c77a3c52467a6f8d9ca3d75feecb9601/transactions?limit=5&start=243204796' --header 'Accept: application/json'
```
How can I get complete transaction data?
Thanks.

**Comment by bowenyang007** [comment]
There is actually no bug here, although the API is not well built. The account by transaction version API only shows you transaction that this account signed, and the start and limits are used as pagination. For example, start = 0 means show me first page, in ascending order. In your case this returns only 252881871. 
https://fullnode.mainnet.aptoslabs.com/v1/accounts/0x4922feaf9457b85ea25422df63bd50d40894bb08549d93f5fea77ffbd33c4f56/transactions

If you want the same result as explorer, you can use this graphql query
https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer.mainnet.aptoslabs.com%2Fv1%2Fgraphql&query=query+AccountTransactionsData+%7B%0A++account_transactions%28%0A++++where%3A+%7Baccount_address%3A+%7B_eq%3A+%220x4922feaf9457b85ea25422df63bd50d40894bb08549d93f5fea77ffbd33c4f56%22%7D%7D%0A++++order_by%3A+%7Btransaction_version%3A+desc%7D%0A++++limit%3A+100%0A++++offset%3A+0%0A++%29+%7B%0A++++transaction_version%0A++%7D%0A%7D
