### ISSUE TITLE
[Bug][Cargo][Node][Versioning] Node release 1.6.3 is marked 1.6.0 in Cargo.toml

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#9907]
@banool @bowenyang007 @larry-aptos

https://github.com/aptos-labs/aptos-core/blob/aptos-node-v1.6.3/aptos-node/Cargo.toml

**Comment by lbmeiyi** [comment]
Thank you for reporting this, we will ensure the version in cargo.toml matches the node releases version in the future. Closing this out for now.
