### ISSUE TITLE
[Bug] [move compiler] Compiler allows vector copy without explicit copy statement

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#9916]
# 🐛 Bug

Apparently the move compiler generates a copy of a vector that has Copy without an explicit copy statement.  See https://github.com/aptos-labs/aptos-core/pull/9796.

## To reproduce

The following move code apparently succeeds:
```rust
module 0xcafe::capy {
    #[test_only]
    use std::vector;

    struct Book has copy, drop {}

    #[test]
    fun implicty_copy() {
        let v0 = vector[Book {}, Book {}, Book {}];

        let v1 = v0; // implicit copy. The keyword `copy` is not required.

        assert!(vector::length(&v0) == 3, 0);
        assert!(vector::length(&v1) == 3, 1);

        let _ = vector::pop_back(&mut v1);

        assert!(vector::length(&v0) == 3, 2); // the original vector is not modified
        assert!(vector::length(&v1) == 2, 3);

    }
}
```

## Expected Behavior

Compiler failure.  See https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/move/book/vector.md#destroying-and-copying-vectors

**Comment by xbtmatt** [comment]
I assumed this was explicitly permitted since it's so ubiquitous throughout the codebase. In general there are a lot of implicit `ability` actions, like implicit drops, as well.

**Comment by brmataptos** [comment]
Yes, Wolfgang confirms that this is the case.

I do wonder if we should warn when a copy is generated, especially for large types, but that's a new feature, not a bug.

**Comment by brmataptos** [comment]
Closing for now, maybe someone can file a feature request for a warning if the value being copied is large.

**Comment by brmataptos** [comment]
closing
