### ISSUE TITLE
[Bug] https://aptosfoundation.org/ecosystem/project/aptos-explorer link to explorer is incorrect

### ISSUE THREAD

**Issue by cryptomolot** [aptos-labs/aptos-core#9979]
# 🐛 Bug

https://aptosfoundation.org/ecosystem/project/aptos-explorer link on aptos explorer leads you to apscan

## To reproduce

<a href='https://hostingkartinok.com/show-image.php?id=05d0dec7c21ed98f1154f426fcfceb9f' title='image host'><img style="width:100%" src='https://s1.hostingkartinok.com/uploads/images/2023/09/05d0dec7c21ed98f1154f426fcfceb9f.jpg' alt='Yes'  /></a>

## Expected Behavior

replace on https://explorer.aptoslabs.com/

**Comment by cryptomolot** [comment]
@gregnazario sorryy 😅

**Comment by moonclavedev** [comment]
@gregnazario Fixed. @cryptomolot thank you!

<img width="1704" alt="image" src="https://github.com/aptos-labs/aptos-core/assets/98909677/ee023ffc-24bf-4839-b451-e33ae2b35ec6">
