### ISSUE TITLE
small typo in documentation

### ISSUE THREAD

**Issue by ddim77** [aptos-labs/aptos-core#999]
Hello!
Small typo in documentation (attached a screenshot)

**<username you created in step 5>** - This text will be correct only for section **"Run Validator Node Using Docker"**
For the rest of the sections it needs to be corrected:
**Run Validator Node Using GCP** (correct step is 11)
**Run Validator Node Using AWS** (correct step is 11)
**Run Validator Node Using Azure** (correct step is 11)
**Run Validator Node Using Source Code** (correct step is  8)

![14-05-2022 19-43-20](https://user-images.githubusercontent.com/28446928/168426373-afe99302-8b66-439e-8c91-2a3065ef2fd8.jpg)

**Comment by davidiw** [comment]
Thanks! There was a lot of jumping around here, we got there though :)
